Repository dealii/dealii, pull requests merged in 2018-06, with the labels that each got.

#6700 Modify pushed flags for CLANGAUTODEBUG_BUG
  cmake/checks/check_01_cxx_features.cmake
Labels: Build system

#6706 Update LICENSE file
  LICENSE.md
Labels: Infrastructure, Miscellaneous

#6712 Fix compile error with CUDA 9.2
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
Labels: GPU, Reviewed and ready to merge

#6720 Use static constexpr in VectorizedArray
  include/deal.II/base/vectorization.h
Labels: Reviewed and ready to merge

#6719 Fix instantiations of SymmetricTensor
  include/deal.II/base/symmetric_tensor.h
  source/base/symmetric_tensor.cc
Labels: Reviewed and ready to merge

#6688 Find all active cells around point
  doc/news/changes/minor/20180528MartinKronbichlerNiklasFehn
  include/deal.II/grid/grid_tools.h
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
  source/grid/grid_tools_dof_handlers.cc
  source/grid/grid_tools_dof_handlers.inst.in
  tests/grid/find_all_active_cells_around_point_01.cc
  tests/grid/find_all_active_cells_around_point_01.output
  tests/grid/find_all_active_cells_around_point_02.cc
  tests/grid/find_all_active_cells_around_point_02.output
Labels: Mapping, Triangulation

#6601 Manage relations of p4est quadrants and dealii cells.
  include/deal.II/distributed/tria.h
  source/distributed/tria.cc
Labels: Parallel distributed, Reviewed and ready to merge, Triangulation

#6722 Avoid using NOLINT
  include/deal.II/lac/full_matrix.templates.h
  include/deal.II/numerics/vector_tools.templates.h
Labels: Reviewed and ready to merge

#6730 Make n_array_elements static const again
  include/deal.II/base/vectorization.h
  source/base/vectorization.cc
Labels: Reviewed and ready to merge

#6732 Trick doxygen into doing the right thing.
  doc/doxygen/headers/multithreading.h
Labels: Reviewed and ready to merge

#6731 Silence gcc-8 warnings in bundled TBB
  bundled/tbb-2018_U2/include/tbb/concurrent_vector.h
  bundled/tbb-2018_U2/include/tbb/internal/_concurrent_unordered_impl.h
Labels: Reviewed and ready to merge

#6733 Fix compiling with CUDA
  include/deal.II/base/exceptions.h
Labels: GPU, Reviewed and ready to merge

#6734 Avoid warning reagrding unused Variable in Utilities::unpack
  include/deal.II/base/utilities.h
Labels: Reviewed and ready to merge

#6694 combine CPU and wallclock tables in TimerOutput
  doc/news/changes/minor/20180529DenisDavydov_b
  include/deal.II/base/timer.h
  source/base/timer.cc
  tests/base/timer_08_b.cc
  tests/base/timer_08_b.output
Labels: Miscellaneous, Reviewed and ready to merge

#6749 Allow using FEFaceEvaluation with degree=-1
  include/deal.II/matrix_free/fe_evaluation.h
  tests/matrix_free/faces_value_optimization_02.cc
  tests/matrix_free/faces_value_optimization_02.output
Labels: Matrix-free

#6748 fixed a bug where exchanger.ghosts_were_set was not set for vectors …
  doc/news/changes/minor/20180612DenisDavydov
  include/deal.II/lac/block_vector.h
  include/deal.II/matrix_free/matrix_free.h
  tests/matrix_free/matrix_vector_blocks.cc
Labels: Matrix-free

#6758 fe/fe_nothing.cc: put a string literal where it belongs
  source/fe/fe_nothing.cc
Labels: Reviewed and ready to merge

#6757 Fix #6756
  doc/news/changes/minor/20180614PiYuehChuang
  examples/step-51/step-51.cc
Labels: Reviewed and ready to merge

#6762 contrib/utilities/indent: Reorganize script
  contrib/utilities/indent
  contrib/utilities/indent_common.sh
  tests/matrix_free/compare_faces_by_cells.with_mpi=true.mpirun=1.output
  tests/matrix_free/compare_faces_by_cells.with_mpi=true.mpirun=5.output
Labels: Reviewed and ready to merge

#6759 Avoid unnamed namespaces
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/fe/fe_series.h
  include/deal.II/fe/fe_system.h
  include/deal.II/fe/fe_tools.templates.h
  include/deal.II/fe/fe_tools_extrapolate.templates.h
  include/deal.II/fe/fe_tools_interpolate.templates.h
  include/deal.II/fe/fe_values.h
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/block_linear_operator.h
  include/deal.II/lac/full_matrix.templates.h
  include/deal.II/lac/la_parallel_block_vector.templates.h
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/lac/linear_operator.h
  include/deal.II/lac/matrix_out.h
  include/deal.II/lac/packaged_operation.h
  include/deal.II/lac/sparse_matrix.templates.h
  include/deal.II/lac/trilinos_sparse_matrix.h
  include/deal.II/lac/trilinos_vector.h
  include/deal.II/matrix_free/dof_info.templates.h
  include/deal.II/matrix_free/evaluation_selector.h
  include/deal.II/matrix_free/mapping_info.templates.h
  include/deal.II/matrix_free/matrix_free.templates.h
  include/deal.II/matrix_free/operators.h
  include/deal.II/matrix_free/shape_info.templates.h
  include/deal.II/multigrid/mg_transfer.templates.h
  include/deal.II/multigrid/mg_transfer_internal.h
  include/deal.II/numerics/data_out_dof_data.templates.h
  include/deal.II/numerics/error_estimator.templates.h
  include/deal.II/numerics/matrix_creator.templates.h
  include/deal.II/numerics/vector_tools.templates.h
  include/deal.II/physics/notation.h
  include/deal.II/physics/transformations.h
  source/fe/fe_system.cc
Labels: Reviewed and ready to merge

#6751 bugfix for TrilinosWrapper::SparseMatrix ::add and ::copy_from
  doc/news/changes/minor/20180614UweKoecher
  include/deal.II/lac/trilinos_sparse_matrix.h
  source/lac/trilinos_sparse_matrix.cc
  tests/trilinos/sparse_matrix_add_03.cc
  tests/trilinos/sparse_matrix_add_03.with_trilinos=true.with_mpi=true.mpirun=3.output
  tests/trilinos/sparse_matrix_copy_from_02.cc
  tests/trilinos/sparse_matrix_copy_from_02.with_trilinos=true.with_mpi=true.mpirun=3.output
Labels: Bug, Linear Algebra, Reviewed and ready to merge

#6764 Fix unused variables in Debug mode
  include/deal.II/numerics/error_estimator.templates.h
  source/numerics/error_estimator_1d.cc
Labels: Reviewed and ready to merge

#6766 add a few missing instantiation after the switch to AffineConstraints
  source/dofs/dof_tools_constraints.inst.in
  source/numerics/vector_tools_boundary.inst.in
Labels: Reviewed and ready to merge

#6673 Add script that reindents recently changed files.
  cmake/setup_custom_targets.cmake
  contrib/utilities/indent-branch
  contrib/utilities/indent_common.sh
Labels: Infrastructure

#6767 Avoid crash for no iteration in GMRES eigenvalue approximation
  doc/news/changes/minor/20180615DanielArndt
  include/deal.II/lac/solver_gmres.h
  tests/lac/gmres_eigenvalues_02.cc
  tests/lac/gmres_eigenvalues_02.with_lapack=true.output
Labels: Reviewed and ready to merge

#6768 Use clang-tidy's modernize-deprecated-headers
  contrib/utilities/run_clang_tidy.sh
  examples/step-42/step-42.cc
  source/base/data_out_base.cc
  source/base/utilities.cc
  tests/quick_tests/adolc.cc
Labels: Reviewed and ready to merge

#6772 AffineConstraints Cleanup #2: Add file deprecation and add a note
  include/deal.II/lac/affine_constraints.h
  include/deal.II/lac/constraint_matrix.h
Labels: Reviewed and ready to merge

#6776 Exceptions: Do not set verbose terminate handler
  cmake/checks/check_02_compiler_features.cmake
  include/deal.II/base/config.h.in
  source/base/exceptions.cc
Labels: Reviewed and ready to merge

#6783 Remove unused variables.
  source/lac/trilinos_sparse_matrix.cc
Labels: Reviewed and ready to merge

#6769 Fix compiling with older Intel compilers
  include/deal.II/fe/fe_system.h
Labels: Reviewed and ready to merge

#6787 Reinsert dofs/function_map.h includes
  include/deal.II/dofs/deprecated_function_map.h
  include/deal.II/dofs/dof_handler.h
  include/deal.II/dofs/function_map.h
  include/deal.II/hp/dof_handler.h
  include/deal.II/numerics/error_estimator.h
  include/deal.II/numerics/matrix_tools.h
  include/deal.II/numerics/vector_tools.h
Labels: Reviewed and ready to merge

#6786 Avoid constraint matrix headers h
  examples/step-11/step-11.cc
  examples/step-13/step-13.cc
  examples/step-14/step-14.cc
  examples/step-15/step-15.cc
  examples/step-16/step-16.cc
  examples/step-17/step-17.cc
  examples/step-18/step-18.cc
  examples/step-21/step-21.cc
  examples/step-22/step-22.cc
  examples/step-23/step-23.cc
  examples/step-24/step-24.cc
  examples/step-25/step-25.cc
  examples/step-26/step-26.cc
  examples/step-27/step-27.cc
  examples/step-28/step-28.cc
  examples/step-31/step-31.cc
  examples/step-32/step-32.cc
  examples/step-35/step-35.cc
  examples/step-36/step-36.cc
  examples/step-37/step-37.cc
  examples/step-40/step-40.cc
  examples/step-41/step-41.cc
  examples/step-42/step-42.cc
  examples/step-43/step-43.cc
  examples/step-44/step-44.cc
  examples/step-45/step-45.cc
  examples/step-46/step-46.cc
  examples/step-48/step-48.cc
  examples/step-50/step-50.cc
  examples/step-51/step-51.cc
  examples/step-52/step-52.cc
  examples/step-55/step-55.cc
  examples/step-56/step-56.cc
  examples/step-57/step-57.cc
  examples/step-59/step-59.cc
  examples/step-6/step-6.cc
  examples/step-60/step-60.cc
  examples/step-7/step-7.cc
  examples/step-8/step-8.cc
  examples/step-9/step-9.cc
  include/deal.II/lac/affine_constraints.h
  include/deal.II/matrix_free/dof_info.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/multigrid/mg_transfer_block.templates.h
  include/deal.II/multigrid/mg_transfer_component.h
  include/deal.II/multigrid/mg_transfer_component.templates.h
Labels: Reviewed and ready to merge

#6725 TrilinosWrappers::MPI::Vector::reinit check parallel_partitioner is_ascending_and_one_to_one
  doc/news/changes/minor/20180616JohsuaHanophy
  source/lac/trilinos_vector.cc
  tests/trilinos/vector_reinit_to_linear_map.cc
  tests/trilinos/vector_reinit_to_linear_map.mpirun=2.output
Labels: Linear Algebra

#6798 Remove redundant namespace identifier
  include/deal.II/numerics/vector_tools.templates.h
Labels: Reviewed and ready to merge

#6695 Generate lapack bindings
  contrib/utilities/generate_lapack_templates
  contrib/utilities/lapack_templates_data/blas_subroutines
  contrib/utilities/lapack_templates_data/fp_subroutines
  contrib/utilities/lapack_templates_data/lapack_subroutines
  include/deal.II/lac/lapack_full_matrix.h
  include/deal.II/lac/lapack_templates.h
  source/lac/lapack_full_matrix.cc
Labels: Infrastructure, Linear Algebra

#6810 Fix macOS indenting
  contrib/utilities/indent_common.sh
Labels: Reviewed and ready to merge

#6811 reflow incode comments
  include/deal.II/numerics/data_out_dof_data.templates.h
  source/base/data_out_base.cc
Labels: Documentation, Reviewed and ready to merge

#6809 Define FE_NedelecSZ with a spacedim argument.
  include/deal.II/fe/fe_nedelec_sz.h
  source/fe/fe_nedelec_sz.cc
Labels: Reviewed and ready to merge

#6813 range loop in write vtu main
  source/base/data_out_base.cc
Labels: Miscellaneous, Reviewed and ready to merge

#6812 contrib/utilities: rename to indent and indent-all
  cmake/setup_custom_targets.cmake
  contrib/git-hooks/pre-commit
  contrib/utilities/check_indentation.sh
  contrib/utilities/indent
  contrib/utilities/indent-all
  contrib/utilities/indent_common.sh
  doc/doxygen/headers/coding_conventions.h
Labels: Reviewed and ready to merge

#6815 Improve formatting in base/data_out_base.cc
  source/base/data_out_base.cc
Labels: Reviewed and ready to merge

#6816 extend/rename get_vector_data_ranges() to return extra element in the…
  doc/news/changes/minor/20180621DenisDavydov
  include/deal.II/base/data_out_base.h
  include/deal.II/numerics/data_out_dof_data.h
  include/deal.II/numerics/data_out_dof_data.templates.h
  source/base/data_out_base.cc
  source/base/data_out_base.inst.in
  source/grid/grid_out.cc
  tests/base/functions_04.cc
  tests/data_out/data_out_04.cc
  tests/data_out/data_out_base.cc
  tests/data_out/data_out_base_dx.cc
  tests/data_out/data_out_base_eps.cc
  tests/data_out/data_out_base_gmv.cc
  tests/data_out/data_out_base_gnuplot.cc
  tests/data_out/data_out_base_gnuplot_02.cc
  tests/data_out/data_out_base_gnuplot_labels.cc
  tests/data_out/data_out_base_povray.cc
  tests/data_out/data_out_base_tecplot.cc
  tests/data_out/data_out_base_tecplot_bin.cc
  tests/data_out/data_out_base_vtk.cc
  tests/data_out/data_out_base_vtk_02.cc
  tests/data_out/data_out_base_vtk_cycle.cc
  tests/data_out/data_out_base_vtk_time.cc
  tests/data_out/data_out_base_vtk_time_and_cycle.cc
  tests/data_out/data_out_base_vtu.cc
  tests/data_out/data_out_base_vtu_02.cc
  tests/data_out/data_out_base_vtu_compression_levels.cc
  tests/data_out/data_out_base_vtu_cycle.cc
  tests/data_out/data_out_base_vtu_time.cc
  tests/data_out/data_out_base_vtu_time_and_cycle.cc
  tests/data_out/data_out_faces_04.cc
  tests/data_out/data_out_reader_01.cc
  tests/data_out/data_out_rotation_04.cc
Labels: Miscellaneous

#6808 Fix using DEAL_II_INVOKE_AUTOPILOT with CUDA enabled
  cmake/macros/macro_deal_ii_invoke_autopilot.cmake
Labels: Reviewed and ready to merge

#6821 Fix comments in @code blocks in matrix_free headers
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/operators.h
Labels: Reviewed and ready to merge

#6825 reflow comments in dof_tools_constraints.cc
  source/dofs/dof_tools_constraints.cc
Labels: Documentation, Reviewed and ready to merge

#6827 minor code cleanup in dof_tools_constraints
  source/dofs/dof_tools_constraints.cc
Labels: Miscellaneous, Reviewed and ready to merge

#6802 update indentation in step-8 plus minor code cleanup
  examples/step-8/step-8.cc
Labels: Tutorials

#6803 improve indentation of step-18 and minor code cleanup
  examples/step-18/step-18.cc
Labels: Tutorials

#6804 improve indentation of step-36 and minor cleanup
  examples/step-36/step-36.cc
Labels: Tutorials

#6799 Also deprecate the p::d::[Block]?Vector header files themselves
  include/deal.II/lac/parallel_block_vector.h
  include/deal.II/lac/parallel_vector.h
Labels: Linear Algebra, Miscellaneous

#6784 examples/step-45: Update indenting and modernize
  examples/step-45/doc/intro.dox
  examples/step-45/step-45.cc
Labels: Tutorials

#6797 Fix overload resolution for FETools::back_interpolate
  doc/news/changes/minor/20180620DanielArndt
  include/deal.II/fe/fe_tools_interpolate.templates.h
  tests/mpi/parallel_vector_back_interpolate_02.cc
  tests/mpi/parallel_vector_back_interpolate_02.with_trilinos=true.mpirun=4.output
Labels: Miscellaneous, Reviewed and ready to merge

#6829 fix failing HDF5 test
  tests/mpi/data_out_hdf5_02.cc
Labels: Reviewed and ready to merge

#6830 Restore backward-compatibility for #6816
  include/deal.II/base/data_out_base.h
  source/base/data_out_base.cc
  source/base/data_out_base.inst.in
Labels: Reviewed and ready to merge

#6834 Fix some clang-tidy findings
  examples/step-18/step-18.cc
  examples/step-36/step-36.cc
  examples/step-8/step-8.cc
  include/deal.II/matrix_free/matrix_free.h
  source/dofs/dof_tools_constraints.cc
Labels: Reviewed and ready to merge

#6806 example/step-20: Update indenting and modernize
  examples/step-20/doc/intro.dox
  examples/step-20/step-20.cc
Labels: Tutorials

#6831 Run clang-format on the step-49 example code.
  examples/step-49/doc/results.dox
Labels: Documentation

#6833 examples/step-35: Update indenting and modernize
  examples/step-35/step-35.cc
Labels: Reviewed and ready to merge, Tutorials

#6842 Simplify test failing for older gcc
  tests/trilinos/sparse_matrix_add_03.cc
  tests/trilinos/sparse_matrix_copy_from_02.cc
Labels: Reviewed and ready to merge

#6843 Use brace initialization instead of writing Point<2> a lot.
  examples/step-49/doc/results.dox
Labels: Documentation, Reviewed and ready to merge

#6844 Return dereferenced IteratorOverIterators object by const reference
  include/deal.II/base/iterator_range.h
Labels: Reviewed and ready to merge

#6780 examples/step-5: Update indenting
  examples/step-5/TODO
  examples/step-5/step-5.cc
Labels: Reviewed and ready to merge, Tutorials

#6779 examples/step-4: Update indenting
  examples/step-4/step-4.cc
Labels: Reviewed and ready to merge, Tutorials

#6857 Make IdentityMatrix constructor explicit
  tests/lac/identity_matrix_07.cc
  tests/lac/identity_matrix_07.output
Labels: Reviewed and ready to merge

#6839 Update step-40.
  examples/step-40/doc/intro.dox
  examples/step-40/step-40.cc
Labels: Tutorials

#6860 Update step 11
  examples/step-11/doc/intro.dox
  examples/step-11/step-11.cc
Labels: Reviewed and ready to merge, Tutorials

#6859 Use a range-for in step-10.
  examples/step-10/step-10.cc
Labels: Reviewed and ready to merge, Tutorials

#6866 Reformat bibtex code
  include/deal.II/base/mpi.h
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/fe/fe_enriched.h
  include/deal.II/fe/fe_p1nc.h
  include/deal.II/lac/precondition.h
  include/deal.II/lac/utilities.h
  include/deal.II/numerics/error_estimator.h
  include/deal.II/physics/notation.h
Labels: Documentation

#6865 Fix an exception description.
  include/deal.II/grid/manifold_lib.h
Labels: Documentation

#6849 example/step-16: Update indenting and modernize
  examples/step-16/doc/intro.dox
  examples/step-16/doc/results.dox
  examples/step-16/step-16.cc
Labels: Tutorials
