Repository dealii/dealii, pull requests merged in 2018-07, with the labels that each got.

#6817 examples/step-22: Update indenting and modernize
  examples/step-22/doc/intro.dox
  examples/step-22/step-22.cc
Labels: Tutorials

#6881 Let 'attach_data_01' consider case with more procs than cells.
  tests/mpi/attach_data_01.cc
  tests/mpi/attach_data_01.mpirun=8.output
Labels: Reviewed and ready to merge

#6793 Require TBB 4.2.0 or newer.
  cmake/configure/configure_1_threads.cmake
Labels: Build system, External libraries

#6870 examples/step-27: Update indenting and modernize
  examples/step-27/doc/intro.dox
  examples/step-27/step-27.cc
Labels: Tutorials

#6869 examples/step-14: Update indenting and modernize
  examples/step-14/step-14.cc
Labels: Tutorials

#6807 add component_is_part_of_tensor
  doc/news/changes/minor/20180621DenisDavydov_b
  include/deal.II/base/tensor.h
  include/deal.II/numerics/data_component_interpretation.h
  include/deal.II/numerics/data_out_dof_data.h
  include/deal.II/numerics/data_out_dof_data.templates.h
  source/base/data_out_base.cc
  tests/data_out/data_out_12.cc
  tests/data_out/data_out_12.output
Labels: Feature, Reviewed and ready to merge

#6889 Restrict tests requiring p4est to the case when we actually have it
  tests/multigrid/transfer_04.with_p4est=true.with_trilinos=true.mpirun=1.output
  tests/multigrid/transfer_04.with_p4est=true.with_trilinos=true.mpirun=2.output
  tests/multigrid/transfer_04a.with_p4est=true.with_trilinos=true.mpirun=1.debug.output
  tests/multigrid/transfer_04a.with_p4est=true.with_trilinos=true.mpirun=2.debug.output
  tests/multigrid/transfer_04b.with_p4est=true.with_petsc=true.with_petsc_with_complex=false.mpirun=1.output
  tests/multigrid/transfer_04b.with_p4est=true.with_petsc=true.with_petsc_with_complex=false.mpirun=2.output
  tests/multigrid/transfer_04b.with_p4est=true.with_petsc=true.with_petsc_with_complex=true.mpirun=1.output
  tests/multigrid/transfer_04b.with_p4est=true.with_petsc=true.with_petsc_with_complex=true.mpirun=2.output
Labels: Reviewed and ready to merge

#6888 Fix a formula in a comment in step-14.
  examples/step-14/step-14.cc
Labels: Reviewed and ready to merge

#6788 Introduce min and max to VectorOperation
  doc/news/changes/minor/20180618SvenjaSchoeder
  include/deal.II/base/partitioner.templates.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/read_write_vector.templates.h
  include/deal.II/lac/vector_operation.h
  source/lac/cuda_vector.cu
  source/lac/trilinos_epetra_vector.cc
  source/lac/trilinos_sparse_matrix.cc
  source/lac/trilinos_vector.cc
  tests/mpi/parallel_vector_22.cc
  tests/mpi/parallel_vector_22.mpirun=10.output
  tests/mpi/parallel_vector_22.mpirun=4.output
  tests/mpi/parallel_vector_23.cc
  tests/mpi/parallel_vector_23.mpirun=4.output
Labels: Linear Algebra, Parallel distributed

#6858 examples/step-39: Update indenting and modernize
  examples/step-39/doc/results.dox
  examples/step-39/output.reference.dat
  examples/step-39/plot_errors.gpl
  examples/step-39/step-39.cc
  include/deal.II/meshworker/functional.h
Labels: Reviewed and ready to merge, Tutorials

#6876 Simplify some code in DataOut_DoFData.
  include/deal.II/numerics/data_out_dof_data.templates.h
Labels: Reviewed and ready to merge

#6887 Fix comments in @code blocks in fe headers
  include/deal.II/fe/block_mask.h
  include/deal.II/fe/component_mask.h
  include/deal.II/fe/fe.h
  include/deal.II/fe/fe_enriched.h
  include/deal.II/fe/fe_system.h
  include/deal.II/fe/fe_values.h
  include/deal.II/fe/mapping_q1_eulerian.h
Labels: Reviewed and ready to merge

#6818 Reflow some code samples.
  include/deal.II/base/array_view.h
  include/deal.II/base/data_out_base.h
  include/deal.II/base/function.h
Labels: Documentation, Reviewed and ready to merge

#6893 Fix comments in @code blocks in grid headers
  include/deal.II/grid/filtered_iterator.h
  include/deal.II/grid/grid_out.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/tria.h
  include/deal.II/grid/tria_iterator.h
Labels: Reviewed and ready to merge

#6864 Refactored data transfer across distributed meshes.
  include/deal.II/base/quadrature_point_data.h
  include/deal.II/base/utilities.h
  include/deal.II/distributed/p4est_wrappers.h
  include/deal.II/distributed/solution_transfer.h
  include/deal.II/distributed/tria.h
  include/deal.II/particles/particle_handler.h
  source/distributed/p4est_wrappers.cc
  source/distributed/solution_transfer.cc
  source/distributed/tria.cc
  source/particles/particle_handler.cc
  tests/mpi/attach_data_01.cc
  tests/mpi/repartition_02.cc
  tests/particles/particle_handler_05.cc
  tests/serialization/particle_handler_01.cc
Labels: Enhancement, External libraries, Parallel distributed, Reviewed and ready to merge

#6897 Fix comments in @code blocks in hp headers
  include/deal.II/hp/dof_handler.h
Labels: Reviewed and ready to merge

#6899 Avoid spurious warning for older clang compiler
  examples/step-14/step-14.cc
  examples/step-27/step-27.cc
Labels: Reviewed and ready to merge

#6903 Use std::is_same instead of typeid in static_cast
  include/deal.II/lac/trilinos_block_sparse_matrix.h
Labels: Reviewed and ready to merge

#6905 Static variable cannot be allocated inside a __device__ function
  include/deal.II/base/tensor.h
Labels: GPU, Reviewed and ready to merge

#6873 Improve SolutionTransfer documentation
  include/deal.II/distributed/solution_transfer.h
  include/deal.II/numerics/solution_transfer.h
  tests/hp/solution_transfer_14.cc
  tests/hp/solution_transfer_14.with_trilinos=true.mpirun=2.output
  tests/hp/solution_transfer_14.with_trilinos=true.output
  tests/hp/solution_transfer_15.cc
  tests/hp/solution_transfer_15.with_trilinos=true.mpirun=2.output
  tests/hp/solution_transfer_15.with_trilinos=true.output
  tests/mpi/solution_transfer_02.cc
  tests/mpi/solution_transfer_02.with_trilinos=true.mpirun=2.output
  tests/mpi/solution_transfer_02.with_trilinos=true.output
  tests/mpi/solution_transfer_03.cc
  tests/mpi/solution_transfer_03.with_trilinos=true.mpirun=2.output
  tests/mpi/solution_transfer_03.with_trilinos=true.output
Labels: Documentation, Parallel, Reviewed and ready to merge, Tests

#6907 Fix Assert indenting
  examples/step-33/step-33.cc
  source/distributed/tria.cc
  source/grid/tria.cc
  source/matrix_free/task_info.cc
  tests/base/functions_08.cc
  tests/base/geometry_info_7.cc
  tests/fe/shapes.h
Labels: Reviewed and ready to merge

#6913 Fix a bug with DEAL_II_TRILINOS_WITH_SACADO
  cmake/configure/configure_2_trilinos.cmake
Labels: Bug, Build system, Reviewed and ready to merge

#6914 Add instantiations of project_boundary_values() with complex arguments
  source/numerics/vector_tools_boundary.inst.in
Labels: Reviewed and ready to merge

#6916 Better document TrilinosWrappers::SparsityPattern::row_length().
  include/deal.II/lac/trilinos_sparsity_pattern.h
  source/lac/trilinos_sparsity_pattern.cc
Labels: Reviewed and ready to merge

#6892 add GridGenerator::plate_with_a_hole()
  doc/doxygen/images/plate_with_a_hole.png
  doc/doxygen/images/plate_with_a_hole_3D.png
  doc/news/changes/minor/20180706DenisDavydov
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  tests/grid/grid_generator_plate_with_a_hole.cc
  tests/grid/grid_generator_plate_with_a_hole.output
  tests/grid/grid_generator_plate_with_a_hole_2.cc
  tests/grid/grid_generator_plate_with_a_hole_2.output
  tests/grid/grid_generator_plate_with_a_hole_3.cc
  tests/grid/grid_generator_plate_with_a_hole_3.output
Labels: Triangulation

#6915 Iterate trilinos sparsity parallel
  doc/news/changes/minor/20180711MathiasAnselmannDanielArndt
  include/deal.II/lac/trilinos_sparsity_pattern.h
  source/lac/trilinos_sparsity_pattern.cc
  tests/trilinos/sparsity_pattern_06.cc
  tests/trilinos/sparsity_pattern_06.with_trilinos=true.with_mpi=true.mpirun=3.output
Labels: Reviewed and ready to merge

#6851 ReduceScatter for compute p2p communication pattern
  source/base/mpi.cc
  tests/mpi/point_to_point_pattern_01.cc
Labels: Parallel distributed, Reviewed and ready to merge

#6921 Minor AD updates
  include/deal.II/differentiation/ad/sacado_math.h
  include/deal.II/differentiation/ad/sacado_number_types.h
  include/deal.II/differentiation/ad/sacado_product_types.h
Labels: Automatic / Symbolic Differentiation

#6896 Fix comments in @code blocks in base headers
  include/deal.II/base/auto_derivative_function.h
  include/deal.II/base/conditional_ostream.h
  include/deal.II/base/parameter_acceptor.h
  include/deal.II/base/parameter_handler.h
  include/deal.II/base/patterns.h
  include/deal.II/base/quadrature_point_data.h
  include/deal.II/base/template_constraints.h
  include/deal.II/base/tensor_accessors.h
  include/deal.II/base/thread_management.h
  include/deal.II/base/utilities.h
Labels: Reviewed and ready to merge

#6925 Add a glossary entry on colorization.
  doc/doxygen/headers/glossary.h
  include/deal.II/grid/grid_generator.h
Labels: Documentation, Reviewed and ready to merge, Triangulation

#6927 Address clang-tidy suggestions
  include/deal.II/numerics/data_out_dof_data.templates.h
  source/grid/grid_generator.cc
  tests/quick_tests/sundials-ida.cc
Labels: Reviewed and ready to merge

#6933 Add missing boost header for p::d::Triangulation
  include/deal.II/distributed/tria.h
Labels: Reviewed and ready to merge

#6932 Use different FESystem constructor in tests
  tests/grid/grid_tools_extract_used_vertices_03.cc
  tests/grid/grid_tools_find_closest_vertex_01.cc
Labels: Reviewed and ready to merge

#6939 hp::DoFHandler::distribute_dofs on p::d::Triangulation fails.
  doc/news/changes/minor/20180720MarcFehling
  source/hp/dof_handler.cc
  tests/mpi/hp_distribute_dofs_01.cc
  tests/mpi/hp_distribute_dofs_01.mpirun=1.output
  tests/mpi/hp_distribute_dofs_01.mpirun=2.output
Labels: Parallel distributed, Triangulation

#6942 Use common ancestor as base for formatting recent files
  contrib/utilities/indent_common.sh
Labels: 6th deal.II Workshop

#6952 Match doxygen markup in the .cc file to that in the .h file.
  include/deal.II/grid/grid_tools.h
  source/grid/grid_tools.cc
Labels: 6th deal.II Workshop, Documentation, Reviewed and ready to merge

#6943 Add AD number static asserts for FullMatrix and Vector classes.
  include/deal.II/lac/full_matrix.h
  include/deal.II/lac/vector.h
Labels: 6th deal.II Workshop

#6949 Avoid #warning using MSVC
  include/deal.II/base/config.h.in
  include/deal.II/base/sacado_product_type.h
  include/deal.II/dofs/function_map.h
  include/deal.II/grid/tria_boundary.h
  include/deal.II/grid/tria_boundary_lib.h
  include/deal.II/lac/constraint_matrix.h
  include/deal.II/lac/parallel_block_vector.h
  include/deal.II/lac/parallel_vector.h
  source/base/timer.cc
Labels: 6th deal.II Workshop

#6958 Make it even clearer that a function is 'virtual'.
  include/deal.II/fe/fe_values.h
Labels: 6th deal.II Workshop, Reviewed and ready to merge

#6823 cmake check for using and DEAL_II_DEPRECATED
  cmake/checks/check_02_compiler_features.cmake
Labels: Reviewed and ready to merge

#6963 Fix generate lapack templates
  contrib/utilities/generate_lapack_templates
Labels: Bug, External libraries

#6962 Fix indentation for 'tests/hp/fe_collection_05'.
  tests/hp/fe_collection_05.cc
Labels: 6th deal.II Workshop

#6966 Restrict tests requiring p4est
  tests/dofs/dof_tools_22a.with_p4est=true.with_trilinos=true.mpirun=1.output
  tests/dofs/dof_tools_22a.with_p4est=true.with_trilinos=true.mpirun=3.output
  tests/dofs/dof_tools_22a.with_p4est=true.with_trilinos=true.mpirun=5.output
  tests/grid/distributed_compute_point_locations_01.with_p4est=true.mpirun=1.output
  tests/lac/linear_operator_12.with_p4est=true.with_trilinos=on.with_mpi=true.mpirun=1.output
  tests/lac/linear_operator_12.with_p4est=true.with_trilinos=on.with_mpi=true.mpirun=2.output
  tests/lac/linear_operator_12a.with_p4est=true.with_trilinos=on.with_mpi=true.mpirun=1.output
  tests/lac/linear_operator_12a.with_p4est=true.with_trilinos=on.with_mpi=true.mpirun=2.output
  tests/lac/linear_operator_14.with_p4est=true.with_trilinos=on.with_mpi=true.mpirun=1.output
  tests/lac/linear_operator_14.with_p4est=true.with_trilinos=on.with_mpi=true.mpirun=2.output
  tests/mappings/mapping_fe_field_03.with_p4est=true.mpirun=1.output
  tests/mappings/mapping_fe_field_03.with_p4est=true.mpirun=3.output
  tests/matrix_free/compare_faces_by_cells.with_p4est=true.with_mpi=true.mpirun=1.output
  tests/matrix_free/compare_faces_by_cells.with_p4est=true.with_mpi=true.mpirun=5.output
  tests/non_matching/coupling_05.with_p4est=true.with_trilinos=true.mpirun=2.output
  tests/non_matching/coupling_06.with_trilinos=true.with_p4est=true.mpirun=2.output
  tests/petsc_complex/fe_get_function_values.with_p4est=true.mpirun=3.output
  tests/petsc_complex/parallel_sparse_matrix_01.with_p4est=true.mpirun=3.output
  tests/trilinos/assemble_matrix_parallel_02.with_p4est=true.mpirun=1.output
  tests/trilinos/assemble_matrix_parallel_02.with_p4est=true.mpirun=4.output
  tests/trilinos/assemble_matrix_parallel_03.with_p4est=true.mpirun=4.output
  tests/trilinos/assemble_matrix_parallel_04.with_p4est=true.mpirun=4.output
  tests/trilinos/assemble_matrix_parallel_05.with_p4est=true.mpirun=1.output
  tests/trilinos/assemble_matrix_parallel_05.with_p4est=true.mpirun=4.output
  tests/trilinos/assemble_matrix_parallel_06.with_p4est=true.mpirun=4.output
  tests/trilinos/assemble_matrix_parallel_07.with_p4est=true.mpirun=4.output
  tests/trilinos/direct_solver_2.with_p4est=true.with_mpi=true.output
  tests/trilinos/n_nonzeros_02_parallel.with_p4est=true.mpirun=9.with_trilinos=true.with_mpi=true.output
  tests/trilinos/renumbering_01.with_p4est=true.mpirun=1.output
  tests/trilinos/renumbering_01.with_p4est=true.mpirun=2.output
  tests/trilinos/solver_control_06.with_p4est=true.mpirun=1.output
  tests/trilinos/solver_control_06.with_p4est=true.mpirun=1.output.2
  tests/trilinos/solver_control_06.with_p4est=true.mpirun=1.output.3
  tests/trilinos/solver_control_06.with_p4est=true.mpirun=2.output
  tests/trilinos/solver_control_06.with_p4est=true.mpirun=2.output.2
  tests/trilinos/solver_control_06.with_p4est=true.mpirun=2.output.3
  tests/trilinos/sparsity_pattern_02.with_p4est=true.output
  tests/trilinos/trilinos_sparsity_pattern_02.with_p4est=true.mpirun=4.output
  tests/trilinos/vector_reinit.with_p4est=true.mpirun=3.output
  tests/trilinos/vector_reinit_to_linear_map.with_p4est=true.mpirun=2.output
Labels: 6th deal.II Workshop

#6944 Add new constructor to function parser
  doc/news/changes/minor/20180721LucaHeltai
  include/deal.II/base/function_parser.h
  source/base/function_parser.cc
  tests/base/function_parser_10.cc
  tests/base/function_parser_10.with_muparser=true.output
Labels: 6th deal.II Workshop

#6973 CMake: Do not check for the geometry component in FindBOOST.cmake
  cmake/modules/FindBOOST.cmake
Labels: High Priority :warning:, Reviewed and ready to merge

#6974 example/step-15: Update indenting and modernize
  examples/step-15/step-15.cc
Labels: 6th deal.II Workshop

#6955 Avoid warning regarding unused variable in SolutionTransfer::unpack_callback
  source/distributed/solution_transfer.cc
Labels: 6th deal.II Workshop

#6971 Improved description compute point locations
  include/deal.II/grid/grid_tools.h
Labels: 6th deal.II Workshop, Reviewed and ready to merge

#5499 Implement driver interface for internally supported AD libraries.
  cmake/configure/configure_adolc.cmake
  cmake/modules/FindADOLC.cmake
  doc/doxygen/headers/automatic_and_symbolic_differentiation.h
  doc/news/changes/minor/20171118Jean-PaulPelteret
  include/deal.II/base/config.h.in
  include/deal.II/differentiation/ad/ad_drivers.h
Labels: 6th deal.II Workshop, Automatic / Symbolic Differentiation, Reviewed and ready to merge

#6960 Prevent warnings introduced in #6936.
  source/distributed/solution_transfer.cc
Labels: Reviewed and ready to merge

#6987 Avoid warning in mpi/attach_data_02
  tests/mpi/attach_data_02.cc
Labels: Reviewed and ready to merge

#6989 Fix reference to step-18 in documentation
  doc/doxygen/headers/geodynamics.h
Labels: 6th deal.II Workshop

#6967 Boost bounding box
  .clang-format
  doc/news/changes/minor/20180724LucaHeltai
  include/deal.II/boost_adaptors/bounding_box.h
  tests/boost/bounding_box_adaptor_01.cc
  tests/boost/bounding_box_adaptor_01.output
  tests/boost/point_adaptor_01.cc
  tests/boost/point_adaptor_01.output
  tests/boost/rtree_01.cc
  tests/boost/rtree_01.output
Labels: 6th deal.II Workshop, Reviewed and ready to merge

#6861 Fix bug in FEFaceEvaluation in 1D
  doc/news/changes/minor/20180704MartinKronbichler
  doc/news/changes/minor/20180704MartinKronbichler-1
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/operators.h
  tests/matrix_free/advect_1d.cc
  tests/matrix_free/advect_1d.output
  tests/matrix_free/advect_1d_system.cc
  tests/matrix_free/advect_1d_system.output
Labels: Matrix-free

#6995 Cleanup 'attach_data_02.output'.
  tests/mpi/attach_data_02.with_p4est=true.mpirun=3.output
  tests/mpi/attach_data_02.with_p4est=true.mpirun=8.output
Labels: Reviewed and ready to merge

#6924 Add shells
  doc/doxygen/images/concentric_hyper_shells_2d.svg
  doc/news/changes/minor/20180715DavidWells
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  source/grid/grid_generator.inst.in
  tests/grid/concentric_hyper_shell_01.cc
  tests/grid/concentric_hyper_shell_01.output
  tests/grid/concentric_hyper_shell_02.cc
  tests/grid/concentric_hyper_shell_02.output
Labels: Triangulation

#6328 Make Subscriptor thread-safe & add general list_subscribers() function.
  doc/news/changes/minor/20180715Jean-PaulPelteret
  include/deal.II/base/subscriptor.h
  source/base/subscriptor.cc
  tests/base/assign_subscriptor.debug.output
  tests/base/assign_subscriptor.with_threads=on.debug.output
  tests/base/reference.debug.output
  tests/base/reference.with_threads=on.debug.output
Labels: Miscellaneous, Reviewed and ready to merge

#6996 Use a C++17 function instead of jn.
  cmake/checks/check_01_cxx_features.cmake
  cmake/checks/check_02_system_features.cmake
  include/deal.II/base/function_bessel.h
  include/deal.II/base/std_cxx17/cmath.h
  source/base/function_lib.cc
  tests/base/bessel_function_values.cc
  tests/base/bessel_function_values.output
  tests/base/functions_01.cc
  tests/base/functions_01.output
Labels: Miscellaneous

#6997 Fix various warnings
  examples/step-17/step-17.cc
  examples/step-18/step-18.cc
  examples/step-36/step-36.cc
  examples/step-55/step-55.cc
  source/grid/grid_generator.cc
Labels: Reviewed and ready to merge

#6994 Add support for high-order VTK output
  doc/news/changes/minor/20180727AlexanderGrayver
  include/deal.II/base/data_out_base.h
  source/base/data_out_base.cc
  tests/data_out/data_out_base_vtk_03.cc
  tests/data_out/data_out_base_vtk_03.output
Labels: Post-processing

#6968 Save the locally owned rows in TrilinosWrappers::SparsityPattern
  include/deal.II/lac/trilinos_sparsity_pattern.h
  source/lac/trilinos_sparsity_pattern.cc
Labels: 6th deal.II Workshop

#7003 Restrict wave_number in constructor of Bessel1 to nonnegative values
  include/deal.II/base/function_bessel.h
  source/base/function_lib.cc
  tests/base/bessel_function_values.cc
  tests/base/bessel_function_values.output
Labels: Reviewed and ready to merge
