Repository dealii/dealii, pull requests merged in 2018-08, with the labels that each got.

#7010 More fixes to AD drivers classes
  include/deal.II/differentiation/ad/ad_drivers.h
Labels: 6th deal.II Workshop, Automatic / Symbolic Differentiation, Reviewed and ready to merge

#7011 Improve documentation of Triangulation
  include/deal.II/grid/tria.h
Labels: Documentation

#6959 Add a script that counts lines of code.
  contrib/utilities/count_lines.sh
Labels: Reviewed and ready to merge

#7004 Document new VTK extensions and restrictions.
  include/deal.II/base/data_out_base.h
  include/deal.II/numerics/data_out.h
Labels: Documentation

#7019 Use common type in AssertIndexRange for the comparison
  include/deal.II/base/exceptions.h
Labels: Reviewed and ready to merge

#7017 fix cell_vectorization_category with MG
  doc/news/changes/minor/20180802DenisDavydov
  include/deal.II/matrix_free/dof_info.templates.h
  include/deal.II/matrix_free/matrix_free.templates.h
  tests/matrix_free/cell_categorization_02.cc
  tests/matrix_free/cell_categorization_02.with_p4est=true.mpirun=1.output
  tests/matrix_free/cell_categorization_02.with_p4est=true.mpirun=3.output
  tests/matrix_free/cell_categorization_02.with_p4est=true.mpirun=7.output
Labels: Geometric multigrid, Matrix-free, Reviewed and ready to merge

#6900 Update step 9
  examples/step-9/doc/intro.dox
  examples/step-9/doc/results.dox
  examples/step-9/step-9.cc
Labels: Enhancement, Reviewed and ready to merge, Tutorials

#7024 Provide test for higher order VTU output
  include/deal.II/base/utilities.h
  tests/data_out/data_out_base_vtu_04.cc
  tests/data_out/data_out_base_vtu_04.with_zlib=off.output
  tests/data_out/data_out_base_vtu_04.with_zlib=on.output
  tests/data_out/data_out_base_vtu_05.cc
  tests/data_out/data_out_base_vtu_05.with_zlib=off.output
  tests/data_out/data_out_base_vtu_05.with_zlib=on.output
Labels: Reviewed and ready to merge

#7012 Allow merging multiple Triangulation objects at once
  doc/news/changes/minor/20180801DanielArndt
  include/deal.II/grid/grid_generator.h
  include/deal.II/grid/grid_tools.h
  source/grid/grid_generator.cc
  source/grid/grid_generator.inst.in
  source/grid/grid_tools.cc
  tests/grid/merge_triangulations_06.cc
  tests/grid/merge_triangulations_06.output
Labels: Triangulation

#7002 Applies variable size transfer to 'ParticleHandler'.
  source/particles/particle_handler.cc
Labels: Reviewed and ready to merge

#7025 Make an argument of GridGenerator::merge_triangulations() a reference.
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  source/grid/grid_generator.inst.in
Labels: Reviewed and ready to merge

#7029 Remove unused variables in LA::d::Vector::import
  include/deal.II/lac/la_parallel_vector.templates.h
Labels: Reviewed and ready to merge

#6241 ScaLAPACKMatrix: copy functions
  include/deal.II/lac/scalapack.h
  include/deal.II/lac/scalapack.templates.h
  source/lac/scalapack.cc
  tests/scalapack/scalapack_17_a.cc
  tests/scalapack/scalapack_17_a.mpirun=1.output
  tests/scalapack/scalapack_17_a.mpirun=11.output
  tests/scalapack/scalapack_17_a.mpirun=9.output
  tests/scalapack/scalapack_17_b.cc
  tests/scalapack/scalapack_17_b.mpirun=1.output
  tests/scalapack/scalapack_17_b.mpirun=11.output
  tests/scalapack/scalapack_17_b.mpirun=9.output
Labels: Linear Algebra, WIP :warning:

#7028 Reduce output of cell_categorization_02
  tests/matrix_free/cell_categorization_02.cc
  tests/matrix_free/cell_categorization_02.with_p4est=true.mpirun=1.output
  tests/matrix_free/cell_categorization_02.with_p4est=true.mpirun=3.output
  tests/matrix_free/cell_categorization_02.with_p4est=true.mpirun=7.output
Labels: Reviewed and ready to merge

#7035 Use CamelCase in namespaces
  doc/doxygen/headers/coding_conventions.h
Labels: Documentation, Reviewed and ready to merge

#7038 Make C++17 support independent of the special math functions.
  cmake/checks/check_01_cxx_features.cmake
  include/deal.II/base/config.h.in
  include/deal.II/base/std_cxx17/cmath.h
Labels: Build system, Reviewed and ready to merge

#7034 Add transformation function between bases in matrix-free
  doc/news/changes/minor/20180806MartinKronbichler-1
  include/deal.II/matrix_free/operators.h
  tests/matrix_free/inverse_mass_01.cc
  tests/matrix_free/inverse_mass_01.output
  tests/matrix_free/inverse_mass_02.cc
  tests/matrix_free/inverse_mass_02.output
  tests/matrix_free/inverse_mass_03.cc
  tests/matrix_free/inverse_mass_03.output
  tests/matrix_free/inverse_mass_04.cc
  tests/matrix_free/inverse_mass_04.output
Labels: Matrix-free, Reviewed and ready to merge

#7031 Add Triangulation::active_face_iterators().
  doc/news/changes/minor/20180805DavidWells
  include/deal.II/grid/tria.h
  source/grid/tria.cc
  tests/dofs/range_based_for_tria_face.cc
  tests/dofs/range_based_for_tria_face.output
  tests/grid/filtered_iterator_06.cc
  tests/grid/filtered_iterator_06.output
Labels: Enhancement

#7043 doc: fix formatting of pre block
  doc/doxygen/headers/main.h
Labels: Documentation, Epic, High Priority :warning:, Reviewed and ready to merge

#7013 Move cuda kernels to their own file and namespace
  include/deal.II/lac/cuda_kernels.h
  include/deal.II/lac/cuda_kernels.templates.h
  include/deal.II/lac/cuda_vector.h
  source/lac/CMakeLists.txt
  source/lac/cuda_kernels.cu
  source/lac/cuda_vector.cu
  tests/all-headers/CMakeLists.txt
Labels: GPU, Reviewed and ready to merge

#7044 ScaLAPACKMatrix: remove small bug in parallel save/load
  doc/news/changes/minor/20180810BenjaminBrands
  source/lac/scalapack.cc
Labels: Reviewed and ready to merge

#7045 Fix build system when using CMake 3.12
  cmake/configure/configure_1_cuda.cmake
  cmake/modules/FindCUDA.cmake
Labels: Reviewed and ready to merge

#7047 Decrement counters in Subscriptor only upon success
  source/base/subscriptor.cc
  tests/base/unsubscribe_subscriptor.cc
  tests/base/unsubscribe_subscriptor.debug.output
Labels: Reviewed and ready to merge

#7054 Fix typo in changelog entry
  doc/news/changes/minor/20180706DenisDavydov
Labels: Documentation

#6277 Fe enriched overlapping domains
  doc/doxygen/images/3source_fe_indices.png
  doc/news/changes/major/20180420NiveshD
  include/deal.II/fe/fe_enriched.h
  source/fe/fe_enriched.cc
  source/fe/fe_enriched.inst.in
  tests/fe/fe_enriched_color_01.cc
  tests/fe/fe_enriched_color_01.output
  tests/fe/fe_enriched_color_02.cc
  tests/fe/fe_enriched_color_02.with_mpi=true.output
  tests/fe/fe_enriched_color_03.cc
  tests/fe/fe_enriched_color_03.with_mpi=true.output
  tests/fe/fe_enriched_color_04.cc
  tests/fe/fe_enriched_color_04.with_mpi=true.output
  tests/fe/fe_enriched_color_05.cc
  tests/fe/fe_enriched_color_05.with_mpi=true.output
  tests/fe/fe_enriched_color_06.cc
  tests/fe/fe_enriched_color_06.with_gsl=true.with_mpi=true.output
  tests/fe/fe_enriched_color_07.cc
  tests/fe/fe_enriched_color_07.with_gsl=true.with_mpi=true.mpirun=2.output
  tests/fe/fe_enriched_color_08.cc
  tests/fe/fe_enriched_color_08.with_mpi=true.output
Labels: Feature, Finite Element

#7058 Fix bug in template instantiations of active_fe_indices_transfer.cc
  source/distributed/active_fe_indices_transfer.cc
Labels: Reviewed and ready to merge

#7049 Add manifold extrusion
  doc/news/changes/major/20180811DavidWells
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  tests/grid/extrude_copy_manifold.cc
  tests/grid/extrude_copy_manifold.output
Labels: Enhancement, Triangulation

#7057 CUDA preprocessor guard
  include/deal.II/base/cuda.h
  include/deal.II/base/numbers.h
  include/deal.II/lac/cuda_atomic.h
  include/deal.II/lac/cuda_kernels.h
  include/deal.II/lac/cuda_kernels.templates.h
  include/deal.II/lac/cuda_solver_direct.h
  include/deal.II/lac/cuda_sparse_matrix.h
  include/deal.II/lac/read_write_vector.templates.h
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  include/deal.II/matrix_free/cuda_hanging_nodes_internal.h
  include/deal.II/matrix_free/cuda_matrix_free.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  include/deal.II/matrix_free/cuda_tensor_product_kernels.h
  source/lac/cuda_vector.cu
  tests/all-headers/CMakeLists.txt
Labels: GPU, Reviewed and ready to merge

#7051 Deprecate MGTools::extract_non_interface_dofs
  include/deal.II/multigrid/mg_tools.h
Labels: Reviewed and ready to merge

#7050 Fix for MGConstrainedDoFs behavior in presence of refinement edges across periodic boundary conditions
  doc/news/changes/minor/20180813AlexanderKnieps
  include/deal.II/multigrid/mg_constrained_dofs.h
  source/multigrid/mg_tools.cc
  tests/multigrid/constrained_dofs_05.cc
  tests/multigrid/constrained_dofs_05.output
Labels: Reviewed and ready to merge

#7065 Restrict a bunch of tests to only run if all requirements are fulfilled
  doc/external-libs/trilinos.html
  tests/base/derivative_forms_01.with_trilinos=true.with_trilinos_with_sacado=true.output
  tests/fe/fe_enriched_color_02.with_mpi=true.with_trilinos=true.with_trilinos_with_zoltan=true.output
  tests/fe/fe_enriched_color_03.with_mpi=true.with_trilinos=true.with_trilinos_with_zoltan=true.output
  tests/fe/fe_enriched_color_04.with_mpi=true.with_trilinos=true.with_trilinos_with_zoltan=true.output
  tests/fe/fe_enriched_color_05.with_mpi=true.with_trilinos=true.with_trilinos_with_zoltan=true.output
  tests/fe/fe_enriched_color_06.with_trilinos=true.with_trilinos_wiith_zoltan=true.with_gsl=true.with_mpi=true.output
  tests/fe/fe_enriched_color_07.cc
  tests/fe/fe_enriched_color_07.with_trilinos=true.with_trilinos_with_zoltan=true.with_petsc=true.with_petsc_with_complex=false.with_gsl=true.with_mpi=true.mpirun=2.output
  tests/fe/fe_enriched_color_08.with_mpi=true.with_trilinos=true.with_trilinos_with_zoltan=true.output
  tests/fe/fe_values_view_get_function_from_local_dof_values_02.with_trilinos=true.with_trilinos_with_sacado=true.output
  tests/hp/solution_transfer_14.cc
  tests/hp/solution_transfer_14.with_trilinos=true.with_trilinos_with_zoltan=true.mpirun=2.output
  tests/hp/solution_transfer_14.with_trilinos=true.with_trilinos_with_zoltan=true.output
  tests/hp/solution_transfer_15.cc
  tests/hp/solution_transfer_15.with_trilinos=true.with_trilinos_with_zoltan=true.mpirun=2.output
  tests/hp/solution_transfer_15.with_trilinos=true.with_trilinos_with_zoltan=true.output
  tests/mpi/solution_transfer_02.cc
  tests/mpi/solution_transfer_02.with_trilinos=true.with_trilinos_with_zoltan=true.mpirun=2.output
  tests/mpi/solution_transfer_02.with_trilinos=true.with_trilinos_with_zoltan=true.output
  tests/mpi/solution_transfer_03.cc
  tests/mpi/solution_transfer_03.with_trilinos=true.with_trilinos_with_zoltan=true.mpirun=2.output
  tests/mpi/solution_transfer_03.with_trilinos=true.with_trilinos_with_zoltan=true.output
Labels: Reviewed and ready to merge

#7066 Avoid warning regarding unused variable in MeshLoop
  include/deal.II/meshworker/mesh_loop.h
Labels: Reviewed and ready to merge

#7069 Fix wrong symbol in CUDAWrappers::Vector::print()
  source/lac/cuda_vector.cu
Labels: GPU

#7061 Enable 'hp::DofHandler' for 'p::d::SolutionTransfer'.
  doc/news/changes/major/20180815Fehling
  include/deal.II/distributed/active_fe_indices_transfer.h
  include/deal.II/distributed/solution_transfer.h
  include/deal.II/dofs/dof_handler.h
  include/deal.II/hp/dof_handler.h
  source/distributed/solution_transfer.cc
  source/distributed/solution_transfer.inst.in
  tests/mpi/p4est_save_06.cc
  tests/mpi/p4est_save_06.with_p4est=true.with_petsc=true.mpirun=5.output
  tests/mpi/solution_transfer_04.cc
  tests/mpi/solution_transfer_04.with_p4est=true.with_trilinos=true.mpirun=2.output
Labels: Parallel distributed, Reviewed and ready to merge, hp

#7068 Fix CUDAWrappers group documentation
  doc/doxygen/options.dox.in
  include/deal.II/base/config.h.in
  include/deal.II/base/cuda.h
  include/deal.II/base/numbers.h
  include/deal.II/base/tensor.h
  include/deal.II/lac/cuda_atomic.h
  include/deal.II/lac/cuda_kernels.h
  include/deal.II/lac/cuda_kernels.templates.h
  include/deal.II/lac/cuda_solver_direct.h
  include/deal.II/lac/cuda_sparse_matrix.h
  include/deal.II/lac/cuda_vector.h
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  include/deal.II/matrix_free/cuda_hanging_nodes_internal.h
  include/deal.II/matrix_free/cuda_matrix_free.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  include/deal.II/matrix_free/cuda_tensor_product_kernels.h
Labels: GPU, Reviewed and ready to merge

#7076 Reference the 'coarse mesh' glossary entry.
  include/deal.II/grid/grid_generator.h
  include/deal.II/grid/tria.h
Labels: Documentation

#7063 Avoid slicing when throwing in Assert
  include/deal.II/base/exceptions.h
  source/base/exceptions.cc
  tests/fe/fe_enriched_color_07.with_petsc=true.with_petsc_with_complex=false.with_gsl=true.with_mpi=true.mpirun=2.output
  tests/parameter_handler/parameter_handler_19.debug.output
  tests/tests.h
Labels: Enhancement

#7080 Ensure initlog() is used in tests/manifold and tests/mappings.
  tests/manifold/polar_manifold_01.cc
  tests/manifold/polar_manifold_06.cc
  tests/manifold/spherical_manifold_02.cc
  tests/mappings/fe_face_values_1d_mapping_cartesian.cc
  tests/mappings/fe_face_values_1d_mapping_q2.cc
  tests/mappings/mapping.cc
  tests/mappings/mapping_c1.cc
  tests/mappings/mapping_fe_field_real_to_unit_b1.cc
  tests/mappings/mapping_fe_field_real_to_unit_b2_curved.cc
  tests/mappings/mapping_fe_field_real_to_unit_b2_mask.cc
  tests/mappings/mapping_fe_field_real_to_unit_b3_curved.cc
  tests/mappings/mapping_fe_field_real_to_unit_b4_curved.cc
  tests/mappings/mapping_fe_field_real_to_unit_b5_curved.cc
  tests/mappings/mapping_fe_field_real_to_unit_q1.cc
  tests/mappings/mapping_fe_field_real_to_unit_q2_curved.cc
  tests/mappings/mapping_fe_field_real_to_unit_q2_mask.cc
  tests/mappings/mapping_fe_field_real_to_unit_q3_curved.cc
  tests/mappings/mapping_fe_field_real_to_unit_q4_curved.cc
  tests/mappings/mapping_fe_field_real_to_unit_q5_curved.cc
  tests/mappings/mapping_manifold_03.cc
  tests/mappings/mapping_manifold_step-3.cc
  tests/mappings/mapping_q1_eulerian.cc
  tests/mappings/mapping_q1_eulerian_01.cc
  tests/mappings/mapping_q_eulerian.cc
  tests/mappings/mapping_q_eulerian_01.cc
  tests/mappings/mapping_q_eulerian_02.cc
  tests/mappings/mapping_q_eulerian_03.cc
  tests/mappings/mapping_q_eulerian_04.cc
  tests/mappings/mapping_q_eulerian_05.cc
  tests/mappings/mapping_q_eulerian_06.cc
  tests/mappings/mapping_q_manifold_01.cc
  tests/mappings/mapping_q_mixed_manifolds_01.cc
  tests/mappings/mapping_q_mixed_manifolds_02.cc
  tests/mappings/mapping_real_to_unit_02.cc
  tests/mappings/mapping_real_to_unit_q1.cc
  tests/mappings/mapping_real_to_unit_q1_singular.cc
  tests/mappings/mapping_real_to_unit_q4_curved.cc
  tests/mappings/mapping_real_to_unit_q4_curved_codim.cc
  tests/mappings/mapping_real_to_unit_q4_sphere_x.cc
  tests/mappings/mapping_real_to_unit_q4_sphere_y.cc
  tests/mappings/mapping_real_to_unit_q4_sphere_z.cc
  tests/mappings/mapping_real_to_unit_q4_straight.cc
Labels: Miscellaneous, Tests

#7079 Fix some duplicated branch warnings.
  include/deal.II/base/symmetric_tensor.templates.h
  include/deal.II/fe/fe_tools.h
  include/deal.II/fe/fe_tools_interpolate.templates.h
Labels: Miscellaneous

#7032 Add interleaved dof storage for DG to MatrixFree
  doc/doxygen/headers/matrixfree.h
  doc/news/changes/minor/20180806MartinKronbichler
  include/deal.II/matrix_free/dof_info.h
  include/deal.II/matrix_free/dof_info.templates.h
  include/deal.II/matrix_free/evaluation_selector.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/matrix_free.templates.h
  source/matrix_free/evaluation_selector.inst.in
Labels: Matrix-free

#7078 Fix some sign comparison warnings.
  include/deal.II/base/table.h
Labels: Miscellaneous

#7085 Avoid deprecated fixed_int_power
  include/deal.II/matrix_free/operators.h
Labels: Reviewed and ready to merge

#6863 Add a grid for the flow past a cylinder benchmark.
  doc/doxygen/images/channel_with_cylinder_2d.png
  doc/doxygen/images/channel_with_cylinder_2d_manifolds.png
  doc/doxygen/images/channel_with_cylinder_3d.png
  doc/news/changes/major/20180704DavidWells
  include/deal.II/grid/grid_generator.h
  include/deal.II/grid/manifold_lib.h
  source/grid/grid_generator.cc
  tests/grid/channel_flow.cc
  tests/grid/channel_flow.output
Labels: Enhancement

#7072 Fix CUDAWrappers::Vector copy assignment
  doc/news/changes/minor/20180816DanielArndt
  include/deal.II/lac/cuda_vector.h
  source/lac/cuda_vector.cu
  tests/cuda/cuda_vector_04.cu
  tests/cuda/cuda_vector_04.output
  tests/cuda/solver_03.cu
  tests/cuda/solver_03.output
Labels: GPU

#7082 Some improvements for CUDAWrappers::SparseMatrix
  doc/news/changes/minor/20180820DanielArndt
  include/deal.II/lac/cuda_sparse_matrix.h
  source/lac/cuda_sparse_matrix.cu
  tests/cuda/sparse_matrix_02.cu
  tests/cuda/sparse_matrix_02.output
Labels: GPU

#7042 Consider periodic neighbors during grid refinement in serial
  doc/news/changes/minor/20180809StefanKaessmairDanielArndt
  source/distributed/tria.cc
  source/grid/tria.cc
  tests/bits/periodic_flux_coupling_01.output
  tests/grid/periodicity_01.cc
  tests/grid/periodicity_01.output
Labels: Reviewed and ready to merge, Triangulation

#7090 ParameterHandler get from subsection
  include/deal.II/base/parameter_handler.h
  source/base/parameter_handler.cc
  tests/parameter_handler/parameter_handler_23.cc
  tests/parameter_handler/parameter_handler_23.output
Labels: Reviewed and ready to merge

#7081 AffineConstraints modernization
  include/deal.II/lac/affine_constraints.h
  include/deal.II/lac/affine_constraints.templates.h
Labels: C++11, Reviewed and ready to merge

#7094 Use unique_ptr in CUDAWrappers::SparseMatrix
  include/deal.II/lac/cuda_sparse_matrix.h
  source/lac/cuda_sparse_matrix.cu
Labels: Reviewed and ready to merge

#7097 Use std::conditional instead of a switch class.
  include/deal.II/lac/block_vector_base.h
Labels: Reviewed and ready to merge

#7089 Add table iterators
  doc/news/changes/minor/20180820DavidWells
  include/deal.II/base/linear_index_iterator.h
  include/deal.II/base/polynomials_abf.h
  include/deal.II/base/polynomials_bdm.h
  include/deal.II/base/polynomials_nedelec.h
  include/deal.II/base/polynomials_p.h
  include/deal.II/base/polynomials_raviart_thomas.h
  include/deal.II/base/polynomials_rt_bubbles.h
  include/deal.II/base/table.h
  include/deal.II/fe/fe.h
  include/deal.II/fe/fe_base.h
  include/deal.II/fe/fe_bdm.h
  include/deal.II/fe/fe_bernardi_raugel.h
  include/deal.II/fe/fe_rt_bubbles.h
  include/deal.II/fe/fe_values.h
  include/deal.II/fe/mapping_cartesian.h
  include/deal.II/fe/mapping_fe_field.h
  include/deal.II/fe/mapping_manifold.h
  include/deal.II/lac/block_sparse_matrix.h
  include/deal.II/lac/full_matrix.h
  include/deal.II/lac/petsc_block_sparse_matrix.h
  include/deal.II/lac/trilinos_block_sparse_matrix.h
  source/base/table_handler.cc
  source/base/tensor_product_polynomials.cc
  source/base/tensor_product_polynomials_bubbles.cc
  source/base/tensor_product_polynomials_const.cc
  source/fe/fe_bdm.cc
  source/fe/fe_bernardi_raugel.cc
  source/fe/fe_raviart_thomas_nodal.cc
  source/fe/fe_rt_bubbles.cc
  source/fe/mapping_q_generic.cc
  source/grid/tria.cc
  tests/full_matrix/full_matrix_iterator_01.cc
Labels: Enhancement, Reviewed and ready to merge

#7075 Fix using the remaining iterative solvers with CUDAWrappers::Vector
  doc/news/changes/minor/20180817DanielArndt
  include/deal.II/lac/cuda_vector.h
  include/deal.II/lac/solver_fire.h
  include/deal.II/lac/solver_minres.h
  include/deal.II/lac/solver_qmrs.h
  source/lac/cuda_vector.cu
  tests/cuda/solver_04.cu
  tests/cuda/solver_04.output
  tests/cuda/solver_05.cu
  tests/cuda/solver_05.output
  tests/cuda/solver_06.cu
  tests/cuda/solver_06.output
  tests/cuda/solver_07.cu
  tests/cuda/solver_07.output
  tests/cuda/solver_08.cu
  tests/cuda/solver_08.output
  tests/cuda/solver_09.cu
  tests/cuda/solver_09.output
  tests/cuda/solver_10.cu
  tests/cuda/solver_10.output
Labels: GPU, Reviewed and ready to merge

#7105 Delete wrong configuration test for fe_enriched_color_07
  tests/fe/fe_enriched_color_07.with_petsc=true.with_petsc_with_complex=false.with_gsl=true.with_mpi=true.mpirun=2.output
Labels: Reviewed and ready to merge

#7106 Don't use math functions not preceded with std::
  include/deal.II/base/derivative_form.h
  include/deal.II/lac/utilities.h
  source/base/data_out_base.cc
  source/base/flow_function.cc
  source/base/function_lib_cutoff.cc
  source/base/function_parser.cc
  source/fe/fe_rt_bubbles.cc
  source/fe/fe_series.cc
  source/fe/mapping_fe_field.cc
  source/fe/mapping_q_generic.cc
  source/grid/grid_generator.cc
  source/grid/grid_out.cc
  source/grid/grid_tools.cc
  source/grid/grid_tools_dof_handlers.cc
  source/grid/manifold_lib.cc
  source/matrix_free/task_info.cc
  source/opencascade/utilities.cc
  tests/petsc/19.cc
Labels: Reviewed and ready to merge

#7104 Const-correctness in lac/vector_operations_internal.h
  include/deal.II/lac/vector_operations_internal.h
Labels: Reviewed and ready to merge

#7111 Remove a reference to FiniteElement::interpolate().
  include/deal.II/fe/fe.h
Labels: Documentation, Reviewed and ready to merge

#7112 Simplify two functions.
  source/grid/tria.cc
Labels: Reviewed and ready to merge, Triangulation

#7110 Avoid loop increment operations with side effects.
  examples/step-10/step-10.cc
  examples/step-11/step-11.cc
Labels: Reviewed and ready to merge, Tutorials

#7114 Fixed bug in member function AffineConstraints<number>::add_entries
  doc/news/changes/minor/20180824DustinKumor
  include/deal.II/lac/affine_constraints.templates.h
Labels: Bug

#7118 Enhancements to AD drivers header
  include/deal.II/differentiation/ad/ad_drivers.h
Labels: Automatic / Symbolic Differentiation

#7119 Don't use a reference for a 'const unsigned int'.
  include/deal.II/fe/fe_enriched.h
  source/fe/fe_enriched.cc
  source/fe/fe_enriched.inst.in
Labels: Reviewed and ready to merge

#7122 Remove an unused array.
  include/deal.II/numerics/vector_tools.templates.h
Labels: Miscellaneous

#6975 AD Helpers: Introduce base class for AD helper classes
  doc/doxygen/headers/automatic_and_symbolic_differentiation.h
  include/deal.II/differentiation/ad/ad_helpers.h
  source/differentiation/ad/CMakeLists.txt
  source/differentiation/ad/ad_helpers.cc
  source/differentiation/ad/ad_helpers.inst1.in
  source/differentiation/ad/ad_helpers.inst2.in
Labels: 6th deal.II Workshop, Automatic / Symbolic Differentiation, RFC

#7088 Add assertions in MatrixFree DoFInfo to avoid invalid memory access
  include/deal.II/matrix_free/dof_info.templates.h
Labels: Bug, Matrix-free

#7124 Fix last remaining instance of passing shared_ptr<Partitioner> by value
  include/deal.II/lac/la_parallel_vector.templates.h
Labels: Reviewed and ready to merge

#7100 Fix bug in mmult for Trilinos matrix
  cmake/configure/configure_2_trilinos.cmake
  doc/external-libs/trilinos.html
  doc/news/changes/minor/20180822BrunoTurcksin
  include/deal.II/base/config.h.in
  source/lac/trilinos_sparse_matrix.cc
  tests/epetraext/CMakeLists.txt
  tests/epetraext/sparse_matrix_mmult_01.cc
  tests/epetraext/sparse_matrix_mmult_01.with_64bit_indices=off.output
  tests/epetraext/sparse_matrix_mmult_02.cc
  tests/epetraext/sparse_matrix_mmult_02.mpirun=2.output
Labels: Bug

#7084 CUDAWrappers::PreconditionIC and CUDAWrappers::PreconditionILU
  doc/news/changes/minor/20180820DanielArndt-2
  include/deal.II/base/numbers.h
  include/deal.II/lac/cuda_precondition.h
  source/lac/CMakeLists.txt
  source/lac/cuda_precondition.cu
  tests/cuda/precondition_01.cu
  tests/cuda/precondition_01.output
  tests/cuda/precondition_02.cu
  tests/cuda/precondition_02.output
Labels: GPU, Reviewed and ready to merge

#7126 Improve documentation of RefinementPossibilities.
  include/deal.II/base/geometry_info.h
Labels: Documentation, Reviewed and ready to merge

#7131 Doc fix: Correct all instances of "Adol-C"
  cmake/config/template-arguments.in
  include/deal.II/base/numbers.h
  include/deal.II/base/symmetric_tensor.templates.h
  include/deal.II/base/tensor.h
  include/deal.II/differentiation/ad.h
  include/deal.II/differentiation/ad/ad_number_traits.h
  include/deal.II/differentiation/ad/ad_number_types.h
  include/deal.II/differentiation/ad/adolc_math.h
  include/deal.II/differentiation/ad/adolc_number_types.h
  include/deal.II/differentiation/ad/adolc_product_types.h
  source/differentiation/ad/adolc_number_types.cc
  tests/adolc/ad_number_traits_01.cc
  tests/adolc/ad_number_traits_02a.cc
  tests/adolc/ad_number_traits_02b.cc
  tests/adolc/ad_number_traits_03.cc
  tests/adolc/basic_function_gradient_tapeless.cc
  tests/adolc/basic_functions_jacobian_tapeless.cc
  tests/quick_tests/adolc.cc
Labels: Automatic / Symbolic Differentiation, Documentation, Reviewed and ready to merge

#7125 follow-up to #7044
  tests/scalapack/scalapack_10_a.cc
  tests/scalapack/scalapack_10_a.with_hdf5=on.mpirun=11.output
  tests/scalapack/scalapack_10_a.with_hdf5=on.mpirun=4.output
Labels: Reviewed and ready to merge

#7102 Extend doc on 'compute_line_dof_identities' and 'get_active_neighbors'.
  include/deal.II/grid/grid_tools.h
  source/dofs/dof_handler_policy.cc
Labels: Documentation

#7132 Fixes a typo in step-16 results.dox
  examples/step-16/doc/results.dox
Labels: Documentation
