Repository dealii/dealii, pull requests merged in 2018-10, with the labels that each got.

#7252 CMake: FindSLEPC.cmake: Fix regex for version number
  cmake/modules/FindSLEPC.cmake
Labels: Build system

#7261 [9.0.1] fix PETSc detection
  cmake/modules/FindPETSC.cmake
  cmake/modules/FindSLEPC.cmake
Labels: Discussion, External libraries, Release

#7269 [9.0] redo 7156
  source/base/mpi.cc
Labels: Release

#7258 Propagate the last year of changes into the documentation.
  doc/doxygen/CMakeLists.txt
  doc/doxygen/scripts/mod_header.pl.in
Labels: Reviewed and ready to merge

#7270 CMake: Uniformly use ADD_FLAGS and LIST(APPEND for CMAKE_REQUIRED
  cmake/checks/check_01_cxx_features.cmake
  cmake/checks/check_02_compiler_features.cmake
  cmake/checks/check_03_compiler_bugs.cmake
  cmake/configure/configure_1_lapack.cmake
  cmake/configure/configure_2_boost.cmake
  cmake/configure/configure_2_trilinos.cmake
  cmake/configure/configure_adolc.cmake
  cmake/macros/macro_push_cmake_required.cmake
  cmake/modules/FindMPI.cmake
  cmake/modules/FindSCALAPACK.cmake
  doc/developers/cmake-internals.html
Labels: Reviewed and ready to merge

#7264 Introduced CellWeights class for load balancing by the number of DoFs.
  doc/news/changes/minor/20181001MarcFehling
  include/deal.II/distributed/cell_weights.h
  source/distributed/CMakeLists.txt
  source/distributed/cell_weights.cc
  source/distributed/cell_weights.inst.in
  tests/mpi/hp_cell_weights_01.cc
  tests/mpi/hp_cell_weights_01.with_p4est=true.mpirun=2.output
  tests/mpi/hp_cell_weights_02.cc
  tests/mpi/hp_cell_weights_02.with_p4est=true.mpirun=3.output
Labels: Reviewed and ready to merge

#7274 Make documentation of hp::FECollection clearer.
  include/deal.II/hp/fe_collection.h
Labels: Documentation

#6754 Fix normal_vector crash for small cells
  doc/news/changes/minor/20181005TimoHeister
  source/grid/manifold.cc
  tests/manifold/flat_manifold_09.cc
  tests/manifold/flat_manifold_09.output
Labels: Miscellaneous, Reviewed and ready to merge

#7275 Add a variadic constructor to hp::QCollection.
  doc/news/changes/minor/20181004Bangerth
  include/deal.II/hp/q_collection.h
Labels: Reviewed and ready to merge

#7289 [9.0.1] Redo #6929
  source/base/data_out_base.cc
  source/base/mpi.cc
  tests/data_out/data_out_filter_02.cc
  tests/data_out/data_out_filter_02.with_hdf5=true.output
Labels: Reviewed and ready to merge

#7280 add inverse_Hilbert_space_filling_curve
  doc/news/changes/minor/20181005DenisDavydov
  include/deal.II/base/utilities.h
  source/base/utilities.cc
  tests/base/utilities_13.cc
  tests/base/utilities_13.output
Labels: Feature, Reviewed and ready to merge

#7268 adapt block size in save_parallel
  source/lac/scalapack.cc
Labels: Reviewed and ready to merge

#6629 Implement VectorizedArray for Altivec/VSX (IBM Power)
  cmake/checks/check_01_cpu_features.cmake
  doc/news/changes/minor/20181005MartinKronbichlerBrunoTurcksinSambitDas
  include/deal.II/base/vectorization.h
  source/base/utilities.cc
Labels: SIMD

#7298 Fix clang-tidy complaints
  examples/step-16/step-16.cc
  include/deal.II/lac/cuda_kernels.h
  include/deal.II/lac/cuda_vector.h
  include/deal.II/matrix_free/cuda_hanging_nodes_internal.h
Labels: Reviewed and ready to merge

#7302 ScaLAPACKMatrix::reinit() and one constructor: pass shared_ptr by value
  include/deal.II/lac/scalapack.h
  source/lac/scalapack.cc
Labels: Reviewed and ready to merge

#7313 Tests: base/utilities_13.cc - workaround for clang
  tests/base/utilities_13.cc
Labels: Reviewed and ready to merge

#7316 Tests: base/reference.cc - avoid "use after scope"
  tests/base/reference.cc
Labels: Reviewed and ready to merge

#7311 Restrict examples that require a working FunctionParser class
  examples/step-33/CMakeLists.txt
  examples/step-60/CMakeLists.txt
Labels: Reviewed and ready to merge

#7322 Tests: Fix race condition between mpi and non-mpi variants
  tests/hp/solution_transfer_14.with_trilinos=true.with_trilinos_with_zoltan=true.mpirun=1.output
  tests/hp/solution_transfer_15.with_trilinos=true.with_trilinos_with_zoltan=true.mpirun=1.output
  tests/mpi/solution_transfer_02.with_trilinos=true.with_trilinos_with_zoltan=true.mpirun=1.output
Labels: Reviewed and ready to merge

#7295 Boost rtree wrapper
  doc/news/changes/minor/20181006LucaHeltai
  include/deal.II/boost_adaptors/segment.h
  include/deal.II/numerics/rtree.h
  tests/boost/rtree_02.cc
  tests/boost/rtree_02.output
Labels: Reviewed and ready to merge

#7310 add DynamicSparsityPattern::compute_Tmmult_pattern() by moving existi…
  include/deal.II/lac/dynamic_sparsity_pattern.h
  include/deal.II/lac/sparse_matrix.templates.h
  include/deal.II/lac/sparsity_pattern.h
  source/lac/dynamic_sparsity_pattern.cc
Labels: Linear Algebra, Reviewed and ready to merge

#7284 Introduced FECollection::find_most_face_dominating_fe_in_subset().
  doc/news/changes/minor/20181005MarcFehling
  doc/news/changes/minor/20181008MarcFehling
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/dofs/dof_accessor.templates.h
  include/deal.II/hp/fe_collection.h
  source/dofs/dof_handler_policy.cc
  source/fe/fe_enriched.cc
  source/hp/fe_collection.cc
Labels: Reviewed and ready to merge

#7277 Add a test for the parallel hp implementation.
  tests/mpi/hp_integrate_difference.cc
  tests/mpi/hp_integrate_difference.with_trilinos=true.mpirun=10.output
  tests/mpi/hp_integrate_difference.with_trilinos=true.mpirun=4.output
Labels: Reviewed and ready to merge

#7325 Minor doc update to class parallel::CellWeights.
  include/deal.II/distributed/cell_weights.h
Labels: Documentation

#7336 Fix step-16
  examples/step-16/step-16.cc
Labels: Reviewed and ready to merge

#6978 AD Helpers: Add helper for residual linearisation (cell-level)
  doc/news/changes/major/20180930Jean-PaulPelteret
  include/deal.II/differentiation/ad/ad_helpers.h
  source/differentiation/ad/ad_helpers.cc
  source/differentiation/ad/ad_helpers.inst1.in
  source/differentiation/ad/ad_helpers.inst2.in
Labels: Automatic / Symbolic Differentiation, Reviewed and ready to merge

#7339 Refactor check for registered tapes
  include/deal.II/differentiation/ad/ad_drivers.h
Labels: Automatic / Symbolic Differentiation, Reviewed and ready to merge

#7343 Use the infinitive form of verbs in the first sentence of doc strings.
  include/deal.II/differentiation/ad/ad_drivers.h
  include/deal.II/differentiation/ad/ad_helpers.h
  include/deal.II/hp/mapping_collection.h
  include/deal.II/hp/q_collection.h
  include/deal.II/multigrid/mg_transfer.h
  include/deal.II/multigrid/mg_transfer_component.h
  include/deal.II/multigrid/mg_transfer_internal.h
  include/deal.II/multigrid/mg_transfer_matrix_free.h
  include/deal.II/non_matching/immersed_surface_quadrature.h
  include/deal.II/sundials/arkode.h
Labels: Documentation

#7342 Americanize the ADHelperResidualLinearization class name
  doc/news/changes/major/20180930Jean-PaulPelteret
  include/deal.II/differentiation/ad/ad_helpers.h
  source/differentiation/ad/ad_helpers.cc
  source/differentiation/ad/ad_helpers.inst1.in
  source/differentiation/ad/ad_helpers.inst2.in
Labels: Automatic / Symbolic Differentiation, Reviewed and ready to merge

#7327 Added cell->is_locally_owned() in project_boundary_values_div_conforming
  doc/news/changes/minor/20181013JonathanMatthews
  include/deal.II/numerics/vector_tools.templates.h
  tests/mpi/project_bv_div_conf.cc
  tests/mpi/project_bv_div_conf.with_p4est=true.mpirun=2.output
  tests/mpi/project_bv_div_conf.with_p4est=true.mpirun=4.output
Labels: Parallel

#7330 ScaLAPACKMatrix: improve documentation
  doc/doxygen/images/scalapack_block_cycling.png
  include/deal.II/lac/scalapack.h
Labels: Documentation

#7354 Update comments of two functions.
  include/deal.II/hp/dof_handler.h
Labels: Documentation

#7358 Refactored FESeries to allow spacedim template for FECollection.
  doc/news/changes/minor/20181017MarcFehling
  include/deal.II/fe/fe_series.h
  source/fe/CMakeLists.txt
  source/fe/fe_series.cc
  source/fe/fe_series_fourier.cc
  source/fe/fe_series_fourier.inst.in
  source/fe/fe_series_legendre.cc
  source/fe/fe_series_legendre.inst.in
Labels: Reviewed and ready to merge, hp

#7359 Add test for SphericalManifold
  tests/manifold/spherical_manifold_13.cc
  tests/manifold/spherical_manifold_13.output
Labels: Reviewed and ready to merge

#7362 fix usage of skip_undefined when reading another file via input statement
  source/base/parameter_handler.cc
Labels: Reviewed and ready to merge

#7366 Use DEAL_II_MPI_CONST_CAST in another place
  include/deal.II/base/mpi.templates.h
Labels: Reviewed and ready to merge

#7361 Tensor product manifold bugfix
  include/deal.II/grid/tensor_product_manifold.h
  tests/manifold/tensor_product_manifold_03.cc
  tests/manifold/tensor_product_manifold_03.output
Labels: Reviewed and ready to merge

#7364 use correct MPI types
  source/particles/particle_handler.cc
Labels: Reviewed and ready to merge

#7371 Update step 27
  doc/doxygen/stylesheet.css
  examples/step-27/doc/intro.dox
  examples/step-27/doc/results.dox
  examples/step-27/doc/tooltip
  examples/step-27/step-27.cc
Labels: Reviewed and ready to merge

#7380 Clarify CUDA C++ version restrictions
  cmake/configure/configure_1_cuda.cmake
Labels: GPU

#7384 Fix a warning about an unused 'using' declaration in release mode.
  source/fe/fe_nedelec_sz.cc
Labels: Reviewed and ready to merge

#7387 add DynamicSparsityPattern::column_index()
  include/deal.II/lac/dynamic_sparsity_pattern.h
  source/lac/dynamic_sparsity_pattern.cc
  tests/sparsity/dynamic_sparsity_pattern_17.cc
  tests/sparsity/dynamic_sparsity_pattern_17.output
Labels: Linear Algebra

#7386 Describe time by real scalar types in Function and friends
  doc/news/changes/incompatibilities/20181026DanielArndt
  include/deal.II/base/function.h
  include/deal.II/base/function.templates.h
  include/deal.II/base/function_time.h
  include/deal.II/base/tensor_function.h
  include/deal.II/base/tensor_function.templates.h
  tests/base/functions_13.cc
Labels: Reviewed and ready to merge

#7367 Make CUDA tests more robust
  tests/cuda/precondition_01.cu
  tests/cuda/precondition_01.output
  tests/cuda/precondition_02.cu
  tests/cuda/precondition_02.output
Labels: GPU, Reviewed and ready to merge, Tests

#7393 Fix a documentation link.
  CMakeLists.txt
Labels: Documentation

#7391 Update step 57
  examples/step-57/doc/intro.dox
  examples/step-57/doc/results.dox
  examples/step-57/step-57.cc
Labels: Documentation

#7392 Deprecate the NetCDF bindings.
  doc/news/changes/incompatibilities/20181027DavidWells
  doc/readme.html
  include/deal.II/base/exceptions.h
  include/deal.II/grid/grid_in.h
Labels: External libraries

#7394 enhanced documentation for DoFTools::Coupling::nonzero
  include/deal.II/dofs/dof_tools.h
Labels: Documentation
