Repository dealii/dealii, pull requests merged in 2018-03, with the labels that each got.

#5974 instantiate Function::Spherical and auxiliary conversion functions fo…
  source/base/CMakeLists.txt
  source/base/function_spherical.cc
  source/base/geometric_utilities.cc
  source/base/geometric_utilities.inst.in
Labels: Miscellaneous, Reviewed and ready to merge

#5975 make p::d::Tria<1> similar to dim>1
  include/deal.II/distributed/tria.h
  source/distributed/tria.cc
  tests/distributed_grids/1d_grid.cc
  tests/distributed_grids/1d_grid.debug.output
Labels: Parallel distributed

#5984 Simplify the creation of filenames in step-12.
  examples/step-12/step-12.cc
Labels: Reviewed and ready to merge

#5987 Fix a wrong link in the documentation.
  include/deal.II/numerics/vector_tools.h
Labels: Documentation

#5941 save/load state and property of ScaLAPACKMatrix
  include/deal.II/lac/scalapack.h
  source/lac/scalapack.cc
  tests/scalapack/scalapack_10.cc
  tests/scalapack/scalapack_10_b.cc
  tests/scalapack/scalapack_10_c.cc
  tests/scalapack/scalapack_10_c.with_hdf5=on.mpirun=1.output
  tests/scalapack/scalapack_10_c.with_hdf5=on.mpirun=11.output
  tests/scalapack/scalapack_10_c.with_hdf5=on.mpirun=4.output
  tests/scalapack/scalapack_10_c.with_hdf5=on.mpirun=5.output
Labels: Linear Algebra

#5996 Guard HDF5 specific ScaLAPACK implementation
  source/lac/scalapack.cc
Labels: Reviewed and ready to merge

#5997 Fix up GridTools::distort_random for p::s::Triangulation
  source/grid/grid_tools.cc
  tests/mpi/distort_random_03.cc
  tests/mpi/distort_random_03.mpirun=3.output
Labels: Reviewed and ready to merge

#5732 Follow-up of #5655: add mmult and Tmmult to petsc sparse matrix and petsc parallel sparse matrix
  include/deal.II/lac/petsc_matrix_base.h
  include/deal.II/lac/petsc_parallel_sparse_matrix.h
  include/deal.II/lac/petsc_sparse_matrix.h
  source/lac/petsc_matrix_base.cc
  source/lac/petsc_parallel_sparse_matrix.cc
  source/lac/petsc_sparse_matrix.cc
  tests/petsc/sparse_matrix_matrix_01.cc
  tests/petsc/sparse_matrix_matrix_01.output
  tests/petsc/sparse_matrix_matrix_02.cc
  tests/petsc/sparse_matrix_matrix_02.output
  tests/petsc/sparse_matrix_matrix_03.cc
  tests/petsc/sparse_matrix_matrix_03.output
  tests/petsc/sparse_matrix_matrix_04.cc
  tests/petsc/sparse_matrix_matrix_04.output
Labels: Linear Algebra, Reviewed and ready to merge, WIP

#6004 Avoid compiler warnings for Function::Spherical
  source/base/function_spherical.cc
Labels: Reviewed and ready to merge

#6013 remove LAPACK warning about uninitialized info variable
  source/lac/lapack_full_matrix.cc
Labels: Reviewed and ready to merge

#6005 Fix Vector::operator=(TrilinosWrappers::MPI::Vector)
  doc/news/changes/minor/20180307Jean-PaulPelteret
  include/deal.II/lac/vector.templates.h
  tests/trilinos/parallel_block_vector_copy_01.cc
  tests/trilinos/parallel_block_vector_copy_01.mpirun=2.output
Labels: Bug, Linear Algebra

#6024 Do not use MPI_COMM_WORLD in MG Transfer
  include/deal.II/lac/constraint_matrix.templates.h
  include/deal.II/multigrid/mg_transfer.h
Labels: Reviewed and ready to merge

#6029 Avoid re-init'ing the same vector twice in step-14.
  examples/step-14/step-14.cc
Labels: Reviewed and ready to merge

#6022 Provide a function that returns the version string.
  doc/news/changes/minor/20180309Bangerth
  include/deal.II/base/utilities.h
  source/base/utilities.cc
Labels: Reviewed and ready to merge

#5998 Update a couple of things on how we generate output in the example steps
  examples/step-6/step-6.cc
  examples/step-8/doc/results.dox
  examples/step-8/step-8.cc
  examples/step-9/doc/results.dox
  examples/step-9/step-9.cc
Labels: Reviewed and ready to merge

#6034 Add a test that works on only a subset of MPI processes.
  tests/mpi/step-40_cuthill_mckee_MPI-subset.cc
  tests/mpi/step-40_cuthill_mckee_MPI-subset.with_petsc_with_hypre=true.mpirun=7.output
Labels: Reviewed and ready to merge

#5993 Add json parser for input files
  include/deal.II/base/parameter_handler.h
  source/base/parameter_handler.cc
  tests/parameter_handler/parameter_handler_read_json.cc
  tests/parameter_handler/parameter_handler_read_json.output
  tests/parameter_handler/prm/parameter_handler_read_json.prm
Labels: Reviewed and ready to merge

#6038 Fix doxygen markup.
  include/deal.II/base/utilities.h
Labels: Reviewed and ready to merge

#6028 Make Hermite-like polynomials represent constant by (1,1,...1)
  include/deal.II/base/polynomial.h
  include/deal.II/fe/fe_dgq.h
  source/base/polynomial.cc
  source/fe/fe_dgq.cc
  tests/base/polynomial_hermite_like.cc
  tests/base/polynomial_hermite_like.with_lapack=true.output
  tests/fe/element_constant_modes.cc
  tests/fe/element_constant_modes.output
Labels: Reviewed and ready to merge

#6031 Don't use SynchronousIterator in step-9, 14
  examples/step-14/step-14.cc
  examples/step-9/step-9.cc
  include/deal.II/base/synchronous_iterator.h
Labels: Reviewed and ready to merge

#6043 Do not use macros in the cuda matrix-free
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
Labels: Reviewed and ready to merge

#6044 Distributed coupling.
  include/deal.II/non_matching/coupling.h
  source/non_matching/coupling.cc
  tests/non_matching/coupling_05.cc
  tests/non_matching/coupling_05.with_trilinos=true,mpirun=2.output
Labels: Reviewed and ready to merge

#6023 Parallelize FETools::compute_projection_matrices()
  include/deal.II/fe/fe_tools.templates.h
Labels: Reviewed and ready to merge

#6053 Really only two micro-cleanups.
  include/deal.II/fe/fe_tools.templates.h
Labels: Reviewed and ready to merge

#6052 Minor cleanups to FETools::get_projection_matrix().
  include/deal.II/fe/fe_tools.templates.h
Labels: Reviewed and ready to merge

#6046 lapack: add set(i,j,value)
  doc/news/changes/minor/20180317DenisDavydov
  include/deal.II/lac/lapack_full_matrix.h
  tests/lapack/full_matrix_35.cc
  tests/lapack/full_matrix_35.output
Labels: Linear Algebra

#6050 extend gitignore
  .gitignore
Labels: Miscellaneous

#6002 Parameter Acceptor Proxy.
  doc/news/changes/minor/20180306LucaHeltai
  include/deal.II/base/parameter_acceptor.h
  tests/parameter_handler/parameter_acceptor_parameters/parameter_acceptor_proxy_01.prm
  tests/parameter_handler/parameter_acceptor_proxy_01.cc
  tests/parameter_handler/parameter_acceptor_proxy_01.with_muparser=true.output
Labels: Miscellaneous

#6060 Convert an Assert into static_assert.
  include/deal.II/base/table_indices.h
Labels: Reviewed and ready to merge

#6051 Minor update to FETools::get_interpolation_difference_matrix().
  doc/news/changes/minor/20180318Bangerth
  include/deal.II/fe/fe_tools.h
  include/deal.II/fe/fe_tools.templates.h
  tests/bits/fe_tools_04_overwrite.cc
  tests/bits/fe_tools_04_overwrite.output
Labels: Miscellaneous, Reviewed and ready to merge

#6069 tests: make distributed_grids/1d_grid robust
  tests/distributed_grids/1d_grid.cc
  tests/distributed_grids/1d_grid.debug.output
Labels: Reviewed and ready to merge

#6067 Bugfix: Set a value to zero with a floating point literal
  source/non_matching/coupling.cc
Labels: Reviewed and ready to merge

#6072 tests: lac/*vector_add_and_dot_complex increase output precision
  tests/lac/la_parallel_vector_add_and_dot_complex.cc
  tests/lac/la_parallel_vector_add_and_dot_complex.output
  tests/lac/la_vector_add_and_dot_complex.cc
  tests/lac/la_vector_add_and_dot_complex.output
  tests/lac/vector_add_and_dot_complex.cc
  tests/lac/vector_add_and_dot_complex.output
Labels: Reviewed and ready to merge

#6068 tests: Increase output precision for fe/rt_bubbles_(14|15)
  tests/fe/rt_bubbles_14.cc
  tests/fe/rt_bubbles_15.cc
Labels: Reviewed and ready to merge

#6049 make Utilities::MPI::sum() support SparseMatrix
  include/deal.II/base/mpi.h
  include/deal.II/base/mpi.templates.h
  include/deal.II/lac/sparse_matrix.h
  source/base/mpi.inst.in
  tests/mpi/collective_sparse_matrix_01.cc
  tests/mpi/collective_sparse_matrix_01.mpirun=1.output
  tests/mpi/collective_sparse_matrix_01.mpirun=3.output
Labels: Parallel

#6075 Mark more basic Tensor operations as always_inline
  include/deal.II/base/tensor.h
Labels: RFC, Tensors

#6064 Avoid deriving from std::iterator
  include/deal.II/base/index_set.h
  include/deal.II/base/iterator_range.h
  include/deal.II/grid/tria_iterator.h
  include/deal.II/lac/block_vector_base.h
  include/deal.II/particles/particle_iterator.h
  source/grid/tria.cc
  tests/bits/iterators_01.cc
  tests/bits/iterators_01.output
Labels: Miscellaneous

#5899 doc: use LaTeX in LAPACKFullMatrix
  include/deal.II/lac/lapack_full_matrix.h
Labels: Documentation

#6077 Fix documentation of Utilities::MPI::MinMaxAvg
  include/deal.II/base/mpi.h
Labels: Documentation

#6083 Do not make a variable in step-35 static.
  examples/step-35/step-35.cc
Labels: Tutorials

#6079 VectorTools: Increase max iterations in project_matrix_free
  include/deal.II/numerics/vector_tools.templates.h
Labels: Tests

#6078 tests: lac/*vector_add_and_dot*
  tests/lac/la_parallel_vector_add_and_dot_complex.output.DEAL_II_MAX_THREADS2
  tests/lac/la_vector_add_and_dot_complex.output.DEAL_II_MAX_THREADS2
  tests/lac/vector_add_and_dot_complex.output.DEAL_II_MAX_THREADS2
Labels: Tests

#6071 tests: sundials/harmonic_oscillator_04 increase precision
  tests/sundials/harmonic_oscillator_04.cc
  tests/sundials/harmonic_oscillator_04.output
  tests/sundials/harmonic_oscillator_04.prm
Labels: Reviewed and ready to merge, Tests

#6093 Tests: Do not print memory consumptions in fe/fe_move_0? tests
  tests/fe/fe_move_01.cc
  tests/fe/fe_move_01.output
  tests/fe/fe_move_01.output.clang9_darwin
  tests/fe/fe_move_02.cc
  tests/fe/fe_move_02.output
  tests/fe/fe_move_02.output.clang9_darwin
Labels: Reviewed and ready to merge

#6091 CMake: Also propagate compiler and linker flags to the boost check
  cmake/configure/configure_boost.cmake
Labels: Build system

#5959 Transpose table iterator
  doc/news/changes/minor/20180225DavidWells
  doc/news/changes/minor/20180301DavidWells
  include/deal.II/base/linear_index_iterator.h
  include/deal.II/base/table.h
  tests/base/transpose_table_iterators_0.cc
  tests/base/transpose_table_iterators_0.output
  tests/base/transpose_table_iterators_1.cc
  tests/base/transpose_table_iterators_1.output
Labels: Enhancement, Feature, Linear Algebra, Reviewed and ready to merge

#6092 Tests: Provide output variants for clang-6 and libc++
  tests/dofs/dof_renumbering_02.output.clang-6.0-libc++
Labels: Tests

#6094 Fix cone_04
  tests/bits/cone_04.cc
Labels: Reviewed and ready to merge

#6098 CMake: Add rpath to example steps
  examples/CMakeLists.txt
Labels: Reviewed and ready to merge

#6090 Fix bug in NormalToMeshProjection
  source/opencascade/boundary_lib.cc
  tests/opencascade/normal_to_mesh_projection_03.cc
  tests/opencascade/normal_to_mesh_projection_03.output
Labels: External libraries, Manifold, Triangulation

#6095 give example of Utilities::MPI::Partitioner
  doc/doxygen/images/partitioner.png
  include/deal.II/base/partitioner.h
  tests/mpi/parallel_partitioner_03b.cc
  tests/mpi/parallel_partitioner_03b.mpirun=4.output
Labels: Documentation, Reviewed and ready to merge

#6099 improve MPI::Partitioner for the case of empty owned DoFs with with non-empty ghosts
  include/deal.II/base/partitioner.templates.h
  tests/mpi/parallel_partitioner_08.cc
  tests/mpi/parallel_partitioner_08.mpirun=2.output
Labels: Parallel

#6088 CMake: Preprocess testsuite parameter files
  cmake/macros/macro_deal_ii_add_test.cmake
  doc/news/changes/minor/20180321MatthiasMaier
  doc/users/testsuite.html
  tests/a-framework/CMakeLists.txt
  tests/a-framework/dummy.cc
  tests/a-framework/parameter_file_1.output
  tests/a-framework/parameter_file_1.prm
  tests/a-framework/parameter_file_2.output
  tests/a-framework/parameter_file_2.prm.in
Labels: Build system

#6104 Let GridTools::minimal/maximal_cell_diameter return global values
  doc/news/changes/minor/20180325DanielArndt
  include/deal.II/grid/grid_tools.h
  source/grid/grid_tools.cc
Labels: Reviewed and ready to merge

#6097 Use TimerOutput::Scope in step-32.
  examples/step-32/step-32.cc
Labels: Tutorials

#6080 ScaLAPACKMatrix::invert for non-symmetric matrices
  include/deal.II/lac/scalapack.h
  include/deal.II/lac/scalapack.templates.h
  source/lac/scalapack.cc
  tests/scalapack/scalapack_03_b.cc
  tests/scalapack/scalapack_03_b.mpirun=1.output
  tests/scalapack/scalapack_03_b.mpirun=10.output
  tests/scalapack/scalapack_03_b.mpirun=4.output
Labels: Linear Algebra

#6107 la::p::Vector: split compress() and update_ghosts() calls into chunks
  include/deal.II/lac/la_parallel_block_vector.h
  include/deal.II/lac/la_parallel_block_vector.templates.h
  tests/mpi/parallel_block_vector_13.cc
  tests/mpi/parallel_block_vector_13.mpirun=10.output
Labels: Linear Algebra, Parallel

#6109 Avoid copies clang-tidy complains about
  source/grid/grid_tools.cc
Labels: Reviewed and ready to merge

#6087 Fix iterating over entries of parallel PETSc matrices.
  doc/news/changes/minor/20180320Bangerth-2
  include/deal.II/lac/petsc_matrix_base.h
  source/lac/petsc_matrix_base.cc
  tests/petsc/iterate_parallel_01.cc
  tests/petsc/iterate_parallel_01.mpirun=2.output
Labels: Linear Algebra, Reviewed and ready to merge

#6105 Tests: Update gla/* test outputs
  tests/gla/block_mat_02.mpirun=1.output
  tests/gla/block_mat_02.mpirun=1.output.complex-output
  tests/gla/block_mat_02.mpirun=2.output
  tests/gla/block_mat_02.mpirun=2.output.complex-output
  tests/gla/block_mat_02.mpirun=4.output
  tests/gla/block_mat_02.mpirun=4.output.complex-output
  tests/gla/block_mat_03.mpirun=1.output
  tests/gla/block_mat_03.mpirun=1.output.complex-output
  tests/gla/block_mat_03.mpirun=2.output
  tests/gla/block_mat_03.mpirun=2.output.complex-output
  tests/gla/extract_subvector_to.mpirun=1.output
  tests/gla/extract_subvector_to_parallel.mpirun=2.output
  tests/gla/mat_03.mpirun=2.output.complex-output
  tests/gla/mat_04.mpirun=2.output
  tests/gla/mat_04.mpirun=2.output.complex-output
Labels: Reviewed and ready to merge, Tests

#6117 Adapt step-12 some further.
  examples/step-12/step-12.cc
Labels: Reviewed and ready to merge

#6116 Remove unnecessary semi-colons in step-12.
  examples/step-12/step-12.cc
Labels: Reviewed and ready to merge

#6123 Make sure is_contiguous() compares addresses, not values, of array objects.
  include/deal.II/base/array_view.h
  tests/base/is_contiguous_nan.cc
  tests/base/is_contiguous_nan.output
Labels: Reviewed and ready to merge

#6122 Tests: update petsc_complex/solver_real_02
  tests/petsc_complex/solver_real_02.cc
  tests/petsc_complex/solver_real_02.output
Labels: Reviewed and ready to merge

#6120 Tests: Slightly change stopping criterion in petsc/solver_02
  tests/petsc/solver_02.cc
Labels: Reviewed and ready to merge

#6110 Avoid using a deprecated SLEPc function.
  source/lac/slepc_solver.cc
Labels: External libraries, Linear Algebra

#6130 petsc/solver_02: Make range more forgiving
  tests/petsc/solver_02.cc
  tests/petsc/solver_02.output
Labels: Tests

#6131 Move some destructor code inside a try block.
  source/base/timer.cc
Labels: Miscellaneous, Reviewed and ready to merge
