Repository dealii/dealii, pull requests merged in 2018-11, with the labels that each got.

#7381 rework DSP::compute_Tmmult_pattern() with iterators
  include/deal.II/lac/dynamic_sparsity_pattern.h
  source/lac/dynamic_sparsity_pattern.cc
  tests/sparsity/dynamic_sparsity_pattern_compute_Tmmult_1.cc
  tests/sparsity/dynamic_sparsity_pattern_compute_Tmmult_1.output
  tests/sparsity/dynamic_sparsity_pattern_compute_Tmmult_2.cc
  tests/sparsity/dynamic_sparsity_pattern_compute_Tmmult_2.output
Labels: Linear Algebra

#7406 doxygen: scale plate_with_hole images
  include/deal.II/grid/grid_generator.h
Labels: Reviewed and ready to merge

#7401 Add more run-time checks to the ABAQUS reader.
  source/grid/grid_in.cc
Labels: Reviewed and ready to merge

#7337 Introduced 'compare_for_cell_domination'. Refactored 'compare_for_face_domination'.
  doc/news/changes/incompatibilities/20181011Fehling
  doc/news/changes/major/20181011Fehling
  include/deal.II/fe/fe.h
  include/deal.II/fe/fe_base.h
  include/deal.II/fe/fe_bernstein.h
  include/deal.II/fe/fe_dgp.h
  include/deal.II/fe/fe_dgp_monomial.h
  include/deal.II/fe/fe_dgp_nonparametric.h
  include/deal.II/fe/fe_dgq.h
  include/deal.II/fe/fe_enriched.h
  include/deal.II/fe/fe_face.h
  include/deal.II/fe/fe_nedelec.h
  include/deal.II/fe/fe_nothing.h
  include/deal.II/fe/fe_q.h
  include/deal.II/fe/fe_q_base.h
  include/deal.II/fe/fe_q_bubbles.h
  include/deal.II/fe/fe_q_dg0.h
  include/deal.II/fe/fe_q_hierarchical.h
  include/deal.II/fe/fe_q_iso_q1.h
  include/deal.II/fe/fe_raviart_thomas.h
  include/deal.II/fe/fe_system.h
  include/deal.II/fe/fe_trace.h
  include/deal.II/hp/fe_collection.h
  source/distributed/active_fe_indices_transfer.cc
  source/distributed/cell_weights.cc
  source/distributed/solution_transfer.cc
  source/dofs/dof_handler_policy.cc
  source/dofs/dof_tools_constraints.cc
  source/fe/fe.cc
  source/fe/fe_bernstein.cc
  source/fe/fe_dgp.cc
  source/fe/fe_dgp_monomial.cc
  source/fe/fe_dgp_nonparametric.cc
  source/fe/fe_dgq.cc
  source/fe/fe_enriched.cc
  source/fe/fe_face.cc
  source/fe/fe_nedelec.cc
  source/fe/fe_nothing.cc
  source/fe/fe_q.cc
  source/fe/fe_q_base.cc
  source/fe/fe_q_bubbles.cc
  source/fe/fe_q_dg0.cc
  source/fe/fe_q_hierarchical.cc
  source/fe/fe_q_iso_q1.cc
  source/fe/fe_raviart_thomas_nodal.cc
  source/fe/fe_system.cc
  source/fe/fe_trace.cc
  source/hp/fe_collection.cc
  tests/fe/fe_enriched_color_08.cc
  tests/fe/fe_enriched_color_08.with_mpi=true.with_trilinos=true.with_trilinos_with_zoltan=true.output
  tests/hp/fe_collection_05.cc
Labels: hp

#7396 add Utilities:: pack_integers() to pack an array of ints
  include/deal.II/base/utilities.h
  source/base/utilities.cc
  tests/base/utilities_14.cc
  tests/base/utilities_14.output
Labels: Feature, Reviewed and ready to merge

#7363 Make SmartPointer+Subscriptor check for dangling pointers
  doc/news/changes/incompatibilities/20181102DanielArndt
  doc/news/changes/minor/20181102DanielArndt
  include/deal.II/base/smartpointer.h
  include/deal.II/base/subscriptor.h
  source/base/subscriptor.cc
  tests/base/assign_subscriptor.cc
  tests/base/assign_subscriptor.debug.output
  tests/base/reference.cc
  tests/base/reference.debug.output
  tests/base/unsubscribe_subscriptor.cc
  tests/base/unsubscribe_subscriptor.debug.output
Labels: Discussion, RFC

#7415 set components correctly in IncrementalFunction
  source/base/incremental_function.cc
  tests/base/functions_incremental_03.cc
  tests/base/functions_incremental_03.output
Labels: Reviewed and ready to merge

#7417 Add missing header in subscriptor.cc
  source/base/subscriptor.cc
Labels: Reviewed and ready to merge

#7422 Only declare PosixThreadBarrier if there is POSIX support
  include/deal.II/base/thread_management.h
Labels: Reviewed and ready to merge, Windows

#7412 MemorySpace template parameter for ArrayView
  doc/news/changes/minor/20181104DanielArndt-1
  include/deal.II/base/array_view.h
  include/deal.II/fe/mapping.h
  tests/cuda/array_view_access_data.cu
  tests/cuda/array_view_access_data.debug.output
  tests/cuda/array_view_wrong_memory.cu
  tests/cuda/array_view_wrong_memory.debug.output
Labels: GPU, Reviewed and ready to merge

#7411 Update GridGenerator::truncated_cone.
  doc/doxygen/images/truncated_cone_2d.png
  doc/doxygen/images/truncated_cone_3d.png
  doc/news/changes/minor/20181103DavidWells
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  tests/bits/cone_01.cc
  tests/bits/cone_01.output
  tests/bits/cone_02.cc
  tests/bits/cone_02.output
  tests/bits/cone_03.output
Labels: Enhancement, Triangulation

#7435 Fix read with FEEvaluation and AVX-512 support
  doc/news/changes/minor/20181110MartinKronbichler
  include/deal.II/matrix_free/dof_info.templates.h
Labels: Reviewed and ready to merge

#7404 Fix some commentary on iterators.
  include/deal.II/grid/tria_iterator.h
Labels: Documentation

#7444 Indent expand_instantiations
  cmake/scripts/expand_instantiations.cc
Labels: Reviewed and ready to merge

#7445 tests: timer_04 and _05 bug
  tests/base/timer_04.cc
  tests/base/timer_05.cc
Labels: Reviewed and ready to merge

#7447 Avoid integer overflow in Utilities::pack_integers
  source/base/utilities.cc
Labels: Reviewed and ready to merge

#7449 Add a comment to GridTools::transform().
  include/deal.II/grid/grid_tools.h
Labels: Documentation

#7212 slight modification of step-30
  examples/step-30/step-30.cc
Labels: Documentation

#7451 FGMRES: deprecate constructor, cleanup documentation
  examples/step-32/step-32.cc
  include/deal.II/lac/solver_gmres.h
  tests/matrix_free/stokes_computation.cc
Labels: Reviewed and ready to merge

#7395 generate pkgconfig files
  cmake/config/CMakeLists.txt
  cmake/config/config_debug.pc.in
  cmake/config/config_release.pc.in
  cmake/setup_deal_ii.cmake
Labels: Build system, Reviewed and ready to merge

#7448 Lazily initialize VectorMemory::Pool
  include/deal.II/lac/vector_memory.h
  include/deal.II/lac/vector_memory.templates.h
  source/base/cuda.cu
  tests/tests.h
Labels: GPU

#7272 Set vertex ownership based on FE domination.
  source/dofs/dof_handler_policy.cc
  tests/fe/fe_nothing.output
  tests/hp/dof_renumbering_04.output
  tests/hp/dof_renumbering_04.output.2
  tests/hp/dof_renumbering_04.output.clang-libc++
  tests/hp/dof_renumbering_05.output
  tests/hp/dof_renumbering_05.output.clang-libc++
  tests/hp/dof_renumbering_06.output
  tests/hp/hp_hanging_nodes_01.output
  tests/hp/renumber_block_wise_01b.output
  tests/hp/renumber_component_wise.output
  tests/mpi/hp_unify_dof_indices_04.mpirun=2.output
  tests/mpi/hp_unify_dof_indices_06.mpirun=2.output
  tests/mpi/hp_unify_dof_indices_08.mpirun=2.output
  tests/mpi/hp_unify_dof_indices_08.mpirun=7.output
Labels: hp

#7458 Add missing functions to TriaAccessor
  doc/news/changes/minor/20181120Bangerth
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_accessor.templates.h
  tests/grid/accessor_01.cc
  tests/grid/accessor_01.output
Labels: Reviewed and ready to merge

#7457 Fix parsed function
  source/base/function_parser.cc
  tests/base/function_parser_11.cc
  tests/base/function_parser_11.with_muparser=true.output
Labels: Reviewed and ready to merge

#7453 Update some of the description in step-30.
  examples/step-30/step-30.cc
Labels: Reviewed and ready to merge

#7469 Use std_cxx14::make_unique in tests
  tests/multigrid/renumbering_06.cc
  tests/multigrid/renumbering_07.cc
Labels: Reviewed and ready to merge

#7472 Avoid C-style cast in numerics
  include/deal.II/numerics/fe_field_function.templates.h
  include/deal.II/numerics/matrix_creator.templates.h
  include/deal.II/numerics/vector_tools.templates.h
  source/numerics/point_value_history.cc
  source/numerics/time_dependent.cc
Labels: Reviewed and ready to merge

#7473 Avoid C-style cast in matrix_free
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/mapping_info.templates.h
  include/deal.II/matrix_free/matrix_free.templates.h
  source/matrix_free/task_info.cc
Labels: Reviewed and ready to merge

#7463 Distributed CUDA matrix-free
  doc/news/changes/minor/20181121BrunoTurcksin
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  include/deal.II/matrix_free/cuda_hanging_nodes_internal.h
  include/deal.II/matrix_free/cuda_matrix_free.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  tests/cuda/matrix_free_matrix_vector_10.cu
  tests/cuda/matrix_free_matrix_vector_10.with_trilinos=true.with_mpi=true.with_p4est=true.mpirun=1.output
  tests/cuda/matrix_free_matrix_vector_10.with_trilinos=true.with_mpi=true.with_p4est=true.mpirun=2.output
  tests/cuda/matrix_free_matrix_vector_19.cu
  tests/cuda/matrix_free_matrix_vector_19.with_trilinos=true.with_trilinos_with_zoltan=true.mpirun=2.output
Labels: GPU

#7477 Make alloc_and_copy safer
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
Labels: GPU

#7441 Add GridTools::get_coarse_mesh_description.
  doc/news/changes/minor/20181111DavidWells
  include/deal.II/grid/grid_tools.h
  source/grid/grid_generator.cc
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
  tests/grid/get_coarse_mesh_description_01.cc
  tests/grid/get_coarse_mesh_description_01.output
Labels: Enhancement, Triangulation

#7478 docs: TableHandler fixes
  include/deal.II/base/table_handler.h
Labels: Reviewed and ready to merge

#7475 Avoid C-style cast in distributed
  source/distributed/p4est_wrappers.cc
  source/distributed/tria.cc
Labels: Reviewed and ready to merge

#7482 Avoid C-style cast in sundials
  source/sundials/arkode.cc
  source/sundials/ida.cc
  source/sundials/kinsol.cc
Labels: Reviewed and ready to merge

#7408 Set the active_fe_index of coarsened cells based on their children.
  doc/news/changes/major/20181015Fehling
  include/deal.II/hp/dof_handler.h
  source/hp/dof_handler.cc
  tests/hp/refinement_01.cc
  tests/hp/refinement_01.output
  tests/mpi/hp_refinement_01.cc
  tests/mpi/hp_refinement_01.with_mpi=true.mpirun=2.output
  tests/mpi/hp_refinement_02.cc
  tests/mpi/hp_refinement_02.with_mpi=true.mpirun=2.output
  tests/serialization/hp_dof_handler_01.with_64bit_indices=off.output
  tests/serialization/hp_dof_handler_01.with_64bit_indices=on.output
Labels: hp

#7488 Fix compiling with older SUNDIALS
  source/sundials/arkode.cc
Labels: External libraries, Reviewed and ready to merge
