Repository dealii/dealii, pull requests merged in 2018-02, with the labels that each got.

#5878 Add another compile-time check to Adol-C CMake module.
  cmake/configure/configure_adolc.cmake
  cmake/modules/FindADOLC.cmake
Labels: Automatic / Symbolic Differentiation, Build system

#5860 Step 49 modernization
  examples/step-49/doc/intro.dox
  examples/step-49/doc/results.dox
  examples/step-49/step-49.cc
Labels: C++11, Manifold, Reviewed and ready to merge, Tutorials

#5868 Fix deficiency in computation of norms for ScaLAPACKMatrix
  include/deal.II/lac/scalapack.h
  include/deal.II/lac/scalapack.templates.h
  source/lac/scalapack.cc
  tests/lapack/create_matrix.h
  tests/scalapack/scalapack_04_b.cc
  tests/scalapack/scalapack_04_b.mpirun=1.output
  tests/scalapack/scalapack_04_b.mpirun=11.output
  tests/scalapack/scalapack_04_b.mpirun=4.output
Labels: Linear Algebra, RFC

#5867 enable chunking for save/load of ScaLAPACKMatrix
  include/deal.II/lac/scalapack.h
  source/lac/scalapack.cc
  tests/scalapack/scalapack_10_b.cc
  tests/scalapack/scalapack_10_b.with_hdf5=on.mpirun=1.output
  tests/scalapack/scalapack_10_b.with_hdf5=on.mpirun=11.output
  tests/scalapack/scalapack_10_b.with_hdf5=on.mpirun=4.output
  tests/scalapack/scalapack_10_b.with_hdf5=on.mpirun=5.output
Labels: Linear Algebra, RFC

#5888 Fix bug in ScaLAPACKMatrix::save
  source/lac/scalapack.cc
Labels: Reviewed and ready to merge

#5884 add BlockVector::multivector_inner_product_with_metric()
  doc/news/changes/minor/20180210DenisDavydov
  include/deal.II/lac/la_parallel_block_vector.h
  include/deal.II/lac/la_parallel_block_vector.templates.h
  source/lac/la_parallel_block_vector.inst.in
  tests/mpi/parallel_block_vector_07.cc
  tests/mpi/parallel_block_vector_07.with_p4est=true.mpirun=1.output
  tests/mpi/parallel_block_vector_07.with_p4est=true.mpirun=4.output
  tests/mpi/parallel_block_vector_08.cc
  tests/mpi/parallel_block_vector_08.with_p4est=true.mpirun=1.output
  tests/mpi/parallel_block_vector_08.with_p4est=true.mpirun=4.output
  tests/mpi/parallel_block_vector_09.cc
  tests/mpi/parallel_block_vector_09.with_p4est=true.mpirun=1.output
  tests/mpi/parallel_block_vector_09.with_p4est=true.mpirun=5.output
  tests/mpi/parallel_block_vector_10.cc
  tests/mpi/parallel_block_vector_10.with_p4est=true.mpirun=1.output
  tests/mpi/parallel_block_vector_10.with_p4est=true.mpirun=4.output
  tests/mpi/parallel_block_vector_11.cc
  tests/mpi/parallel_block_vector_11.with_p4est=true.mpirun=4.output
Labels: Linear Algebra

#3897 CMake: Use -isystem for third party headers
  cmake/macros/macro_deal_ii_insource_setup_target.cmake
  cmake/macros/macro_deal_ii_setup_target.cmake
  examples/step-33/step-33.cc
  examples/step-53/step-53.cc
  include/deal.II/base/utilities.h
  include/deal.II/differentiation/ad/adolc_math.h
  include/deal.II/differentiation/ad/adolc_number_types.h
  include/deal.II/differentiation/ad/adolc_product_types.h
  include/deal.II/differentiation/ad/sacado_number_types.h
  include/deal.II/differentiation/ad/sacado_product_types.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/tria.h
  include/deal.II/lac/precondition.h
  include/deal.II/lac/read_write_vector.h
  include/deal.II/lac/read_write_vector.templates.h
  include/deal.II/lac/solver.h
  include/deal.II/lac/trilinos_epetra_communication_pattern.h
  include/deal.II/lac/trilinos_epetra_vector.h
  include/deal.II/lac/trilinos_precondition.h
  include/deal.II/lac/trilinos_solver.h
  include/deal.II/lac/trilinos_sparse_matrix.h
  include/deal.II/lac/trilinos_sparsity_pattern.h
  include/deal.II/lac/trilinos_vector.h
  include/deal.II/multigrid/mg_coarse.h
  include/deal.II/numerics/kdtree.h
  include/deal.II/opencascade/utilities.h
  source/CMakeLists.txt
  source/base/function_parser.cc
  source/base/mpi.cc
  source/base/parameter_handler.cc
  source/base/patterns.cc
  source/base/polynomials_bernstein.cc
  source/base/symmetric_tensor.cc
  source/base/utilities.cc
  source/dofs/dof_handler_policy.cc
  source/dofs/dof_renumbering.cc
  source/grid/grid_in.cc
  source/lac/sparsity_tools.cc
  source/lac/trilinos_epetra_communication_pattern.cc
  source/lac/trilinos_epetra_vector.cc
  source/lac/trilinos_precondition.cc
  source/lac/trilinos_precondition_ml.cc
  source/lac/trilinos_precondition_muelu.cc
  source/lac/trilinos_solver.cc
  source/lac/trilinos_sparse_matrix.cc
  source/lac/trilinos_sparsity_pattern.cc
  source/lac/trilinos_vector.cc
  source/opencascade/boundary_lib.cc
  source/opencascade/utilities.cc
Labels: Build system

#5883 Make Mapping::clone return a unique_ptr<Mapping>.
  doc/news/changes/incompatibilities/20180208DavidWells
  include/deal.II/fe/mapping.h
  include/deal.II/fe/mapping_c1.h
  include/deal.II/fe/mapping_cartesian.h
  include/deal.II/fe/mapping_fe_field.h
  include/deal.II/fe/mapping_manifold.h
  include/deal.II/fe/mapping_q.h
  include/deal.II/fe/mapping_q1.h
  include/deal.II/fe/mapping_q1_eulerian.h
  include/deal.II/fe/mapping_q_eulerian.h
  include/deal.II/fe/mapping_q_generic.h
  source/fe/mapping_c1.cc
  source/fe/mapping_cartesian.cc
  source/fe/mapping_fe_field.cc
  source/fe/mapping_manifold.cc
  source/fe/mapping_q.cc
  source/fe/mapping_q1.cc
  source/fe/mapping_q1_eulerian.cc
  source/fe/mapping_q_eulerian.cc
  source/fe/mapping_q_generic.cc
  tests/hp/mapping_collection_03.cc
Labels: C++11, Enhancement, Reviewed and ready to merge

#5891 Update documentation on 'deallog' in step-3.
  examples/step-3/step-3.cc
Labels: Documentation

#5893 return immediately if a==0 in p::d::Vector::add(a,V)
  include/deal.II/lac/la_parallel_vector.templates.h
Labels: Linear Algebra, Reviewed and ready to merge

#5890 Move cuda related macros in their own file
  include/deal.II/base/cuda_size.h
  source/lac/cuda_vector.cu
Labels: GPU

#5879 Provide a more stable variant of Hermite polynomials for higher polynomial degrees
  doc/news/changes/incompatibilities/20180209MartinKronbichler
  doc/news/changes/minor/20171227MartinKronbichler
  doc/news/changes/minor/20180209MartinKronbichler
  include/deal.II/base/polynomial.h
  include/deal.II/fe/fe_dgq.h
  source/base/polynomial.cc
  source/fe/fe_dgq.cc
  tests/base/polynomial_hermite_like.cc
  tests/base/polynomial_hermite_like.with_lapack=true.output
  tests/fe/element_constant_modes.cc
  tests/fe/element_constant_modes.output
Labels: Finite Element, Reviewed and ready to merge

#5904 fix grammar in VectorTools::project()
  include/deal.II/numerics/vector_tools.h
Labels: Documentation

#5882 Let FETools::get_fe_by_name return a std::unique_ptr
  doc/news/changes/incompatibilities/20180209DanielArndt
  include/deal.II/fe/fe_tools.h
  include/deal.II/fe/fe_tools.templates.h
  source/fe/fe_tools.inst.in
  tests/bits/fe_tools_09.cc
  tests/bits/fe_tools_10.cc
  tests/bits/fe_tools_11.cc
  tests/fe/fe_tools_01.cc
  tests/fe/get_fe_by_name_01.cc
Labels: Miscellaneous

#5906 Fix issues found by clang-tidy checks=performance*
  examples/step-29/step-29.cc
  examples/step-49/step-49.cc
  examples/step-9/step-9.cc
  source/base/data_out_base.cc
  source/dofs/dof_renumbering.cc
Labels: Reviewed and ready to merge

#5915 scalapack: query lwork from ppocon
  source/lac/scalapack.cc
Labels: Linear Algebra, Reviewed and ready to merge

#5918 Fix get_fe_by_name for MSVC
  include/deal.II/fe/fe_tools.templates.h
Labels: Reviewed and ready to merge

#5911 Fix integer overflow in TensorProductMatrix
  include/deal.II/lac/tensor_product_matrix.h
Labels: Miscellaneous

#5908 Fix a bug in CUDAWrappers::Vector::reinit
  source/lac/cuda_vector.cu
  tests/cuda/cuda_vector_03.cu
  tests/cuda/cuda_vector_03.output
Labels: GPU

#5920 Use SphericalManifold in step-45.
  examples/step-45/step-45.cc
Labels: Manifold, Reviewed and ready to merge

#5923 Fix warning in TBB
  bundled/tbb41_20130401oss/src/tbb/tools_api/ittnotify_static.c
Labels: Reviewed and ready to merge

#5414 New function: distributed compute point locations (and tests)
  doc/news/changes/minor/20180119GiovanniAlzetta
  include/deal.II/grid/grid_tools.h
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
  tests/grid/distributed_compute_point_locations_01.cc
  tests/grid/distributed_compute_point_locations_01.mpirun=1.output
  tests/grid/distributed_compute_point_locations_02.cc
  tests/grid/distributed_compute_point_locations_02.with_mpi=true.with_p4est=true.mpirun=2.output
  tests/grid/distributed_compute_point_locations_02.with_mpi=true.with_p4est=true.mpirun=3.output
Labels: Particles, Triangulation

#5926 Move an implementation to a source file.
  include/deal.II/base/parallel.h
  source/base/parallel.cc
Labels: Miscellaneous, Reviewed and ready to merge

#5869 ScaLAPACKMatrix: add functions to perform addition, multiplication and row/column scaling
  doc/news/changes/minor/20180207BenjaminBrands
  include/deal.II/base/array_view.h
  include/deal.II/lac/scalapack.h
  include/deal.II/lac/scalapack.templates.h
  source/lac/CMakeLists.txt
  source/lac/scalapack.cc
  source/lac/scalapack.inst.in
  tests/scalapack/scalapack_12_a.cc
  tests/scalapack/scalapack_12_a.mpirun=1.output
  tests/scalapack/scalapack_12_a.mpirun=11.output
  tests/scalapack/scalapack_12_a.mpirun=9.output
  tests/scalapack/scalapack_12_b.cc
  tests/scalapack/scalapack_12_b.mpirun=1.output
  tests/scalapack/scalapack_12_b.mpirun=11.output
  tests/scalapack/scalapack_12_b.mpirun=9.output
  tests/scalapack/scalapack_12_c.cc
  tests/scalapack/scalapack_12_c.mpirun=1.output
  tests/scalapack/scalapack_12_c.mpirun=11.output
  tests/scalapack/scalapack_12_c.mpirun=9.output
  tests/scalapack/scalapack_12_d.cc
  tests/scalapack/scalapack_12_d.mpirun=1.output
  tests/scalapack/scalapack_12_d.mpirun=11.output
  tests/scalapack/scalapack_12_d.mpirun=9.output
  tests/scalapack/scalapack_13_a.cc
  tests/scalapack/scalapack_13_a.mpirun=1.output
  tests/scalapack/scalapack_13_a.mpirun=11.output
  tests/scalapack/scalapack_13_a.mpirun=9.output
  tests/scalapack/scalapack_13_b.cc
  tests/scalapack/scalapack_13_b.mpirun=1.output
  tests/scalapack/scalapack_13_b.mpirun=11.output
  tests/scalapack/scalapack_13_b.mpirun=9.output
  tests/scalapack/scalapack_14_a.cc
  tests/scalapack/scalapack_14_a.mpirun=1.output
  tests/scalapack/scalapack_14_a.mpirun=11.output
  tests/scalapack/scalapack_14_a.mpirun=9.output
  tests/scalapack/scalapack_14_b.cc
  tests/scalapack/scalapack_14_b.mpirun=1.output
  tests/scalapack/scalapack_14_b.mpirun=11.output
  tests/scalapack/scalapack_14_b.mpirun=9.output
Labels: Linear Algebra, RFC, Reviewed and ready to merge

#5898 LAPACKFullMatrix - add another Tmmult()
  doc/news/changes/minor/20180214DenisDavydov
  include/deal.II/lac/lapack_full_matrix.h
  include/deal.II/lac/lapack_templates.h
  source/lac/lapack_full_matrix.cc
  tests/lapack/create_matrix.h
  tests/lapack/full_matrix_31.cc
  tests/lapack/full_matrix_31.output
  tests/lapack/full_matrix_32.cc
  tests/lapack/full_matrix_32.output
  tests/lapack/full_matrix_33.cc
  tests/lapack/full_matrix_33.output
  tests/lapack/full_matrix_34.cc
  tests/lapack/full_matrix_34.output
Labels: Linear Algebra

#5929 Fix some odd formatting.
  include/deal.II/base/symmetric_tensor.h
Labels: Reviewed and ready to merge

#5924 Fix references to Boundary
  examples/step-32/doc/intro.dox
  examples/step-38/doc/results.dox
  examples/step-54/doc/intro.dox
  include/deal.II/grid/grid_generator.h
  include/deal.II/grid/manifold.h
  include/deal.II/grid/manifold_lib.h
Labels: Manifold, Miscellaneous

#5922 Change GridOut::write_mesh_per_processor_as_vtu
  doc/news/changes/minor/20180219ConradClevenger
  source/grid/grid_out.cc
  tests/grid/grid_out_per_processor_vtu_03.cc
  tests/grid/grid_out_per_processor_vtu_03.output
Labels: Miscellaneous

#5933 Fix the location of hats on symbols in the documentation.
  examples/step-51/doc/intro.dox
Labels: Documentation

#5925 Fix the memory usage of the /source/fe unity files.
  source/fe/CMakeLists.txt
Labels: Build system, Reviewed and ready to merge

#5870 Integrators for DG face integrals with tests.
  include/deal.II/lac/tensor_product_matrix.h
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/evaluation_selector.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/operators.h
  include/deal.II/matrix_free/tensor_product_kernels.h
  source/fe/mapping_q_generic.cc
  source/matrix_free/evaluation_selector.inst.in
  source/multigrid/mg_transfer_matrix_free.cc
  tests/matrix_free/evaluate_1d_shape_01.cc
  tests/matrix_free/evaluate_1d_shape_01.output
  tests/matrix_free/evaluate_1d_shape_02.cc
  tests/matrix_free/evaluate_1d_shape_02.output
  tests/matrix_free/evaluate_1d_shape_03.cc
  tests/matrix_free/evaluate_1d_shape_03.output
  tests/matrix_free/evaluate_1d_shape_04.cc
  tests/matrix_free/evaluate_1d_shape_04.output
  tests/matrix_free/evaluate_1d_shape_05.cc
  tests/matrix_free/evaluate_1d_shape_05.output
  tests/matrix_free/evaluate_1d_shape_06.cc
  tests/matrix_free/evaluate_1d_shape_06.output
  tests/matrix_free/evaluate_1d_shape_07.cc
  tests/matrix_free/evaluate_1d_shape_07.output
  tests/matrix_free/evaluate_1d_shape_08.cc
  tests/matrix_free/evaluate_1d_shape_08.output
  tests/matrix_free/evaluate_1d_shape_09.cc
  tests/matrix_free/evaluate_1d_shape_09.output
Labels: Matrix-free

#5942 remove some unused exceptions
  include/deal.II/grid/tria_levels.h
  include/deal.II/grid/tria_objects.h
Labels: Reviewed and ready to merge

#5940 Exception fixes and cleanup (clang-tidy)
  include/deal.II/base/exceptions.h
  source/base/exceptions.cc
Labels: Miscellaneous

#5945 Avoid where possible to use std::ostringstream to generate filenames.
  examples/step-13/step-13.cc
  examples/step-14/step-14.cc
  examples/step-16/step-16.cc
  examples/step-17/step-17.cc
  examples/step-21/step-21.cc
  examples/step-22/step-22.cc
  examples/step-31/step-31.cc
  examples/step-37/step-37.cc
  examples/step-44/step-44.cc
  examples/step-45/step-45.cc
  examples/step-46/step-46.cc
  examples/step-5/step-5.cc
  examples/step-56/step-56.cc
  examples/step-57/step-57.cc
Labels: Tutorials

#5944 Fix findings of "modernize-use-emplace"
  cmake/scripts/expand_instantiations.cc
  examples/step-19/step-19.cc
  examples/step-20/step-20.cc
  examples/step-21/step-21.cc
  examples/step-22/step-22.cc
  examples/step-29/step-29.cc
  examples/step-34/step-34.cc
  examples/step-35/step-35.cc
  examples/step-44/step-44.cc
  examples/step-46/step-46.cc
  examples/step-47/step-47.cc
  examples/step-51/step-51.cc
  examples/step-56/step-56.cc
  examples/step-57/step-57.cc
  examples/step-7/step-7.cc
  examples/step-8/step-8.cc
  tests/quick_tests/nanoflann.cc
Labels: Miscellaneous

#5950 Remove now unnecessary #includes.
  examples/step-18/step-18.cc
  examples/step-43/step-43.cc
  examples/step-50/step-50.cc
Labels: Reviewed and ready to merge

#5948 Inline a message text instead of going through contortions.
  examples/step-32/step-32.cc
Labels: Miscellaneous

#5953 Remove some more SVN ID tags.
  include/deal.II/distributed/shared_tria.h
  source/distributed/shared_tria.inst.in
  source/distributed/tria_base.inst.in
  source/fe/fe_bernstein.cc
  tests/lac/filtered_matrix_01.cc
  tests/lac/filtered_matrix_02.cc
  tests/lac/filtered_matrix_03.cc
  tests/lac/filtered_matrix_04.cc
  tests/lac/filtered_matrix_05.cc
Labels: Miscellaneous

#5905 Use std::uint8_t as the underlying data type for CellId.
  include/deal.II/grid/cell_id.h
  source/grid/cell_id.cc
Labels: Miscellaneous

#5949 Simplify some code.
  examples/step-6/step-6.cc
Labels: Miscellaneous, Reviewed and ready to merge

#5919 Deprecate `fixed_int_power`
  include/deal.II/base/utilities.h
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  include/deal.II/matrix_free/cuda_tensor_product_kernels.h
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/operators.h
  include/deal.II/matrix_free/tensor_product_kernels.h
Labels: C++11, Miscellaneous, Reviewed and ready to merge

#5960 Use the correct size type for a column number.
  include/deal.II/lac/full_matrix.h
Labels: Bug, Miscellaneous, Reviewed and ready to merge

#5961 Remove unused typedef
  include/deal.II/matrix_free/evaluation_kernels.h
Labels: Miscellaneous, Reviewed and ready to merge

#5963 fix compilation of kinsol wrappers with complex PETSc
  source/sundials/kinsol.cc
Labels: Bug, External libraries

#5964 fix initializer in tests/manifold/chart_manifold_10
  tests/manifold/chart_manifold_10.cc
Labels: Reviewed and ready to merge

#5967 Minor edits to the documentation of AnisotropicPolynomials.
  include/deal.II/base/tensor_product_polynomials.h
Labels: Documentation

#5966 fix more findings of modernize-use-emplace
  examples/step-17/step-17.cc
  examples/step-18/step-18.cc
  examples/step-31/step-31.cc
  examples/step-32/step-32.cc
  examples/step-33/step-33.cc
  examples/step-43/step-43.cc
  examples/step-45/step-45.cc
  examples/step-55/step-55.cc
Labels: Reviewed and ready to merge

#5927 Cuda sparse matrix
  doc/news/changes/minor/20180218BrunoTurcksin
  include/deal.II/lac/cuda_atomic.h
  include/deal.II/lac/cuda_sparse_matrix.h
  source/lac/CMakeLists.txt
  source/lac/cuda_sparse_matrix.cu
  tests/cuda/sparse_matrix_01.cu
  tests/cuda/sparse_matrix_01.output
Labels: GPU, Reviewed and ready to merge

#5973 make test scalapack_10_b shorter
  tests/scalapack/scalapack_10_b.cc
  tests/scalapack/scalapack_10_b.with_hdf5=on.mpirun=1.output
  tests/scalapack/scalapack_10_b.with_hdf5=on.mpirun=11.output
  tests/scalapack/scalapack_10_b.with_hdf5=on.mpirun=4.output
  tests/scalapack/scalapack_10_b.with_hdf5=on.mpirun=5.output
Labels: Tests

#5976 make KellyErrorEstimator<1> consistent with KellyErrorEstimator<2|3>
  include/deal.II/numerics/error_estimator.h
  source/numerics/error_estimator_1d.cc
  source/numerics/error_estimator_1d.inst.in
Labels: Miscellaneous, Reviewed and ready to merge

#5977 instantiate p::d::GridRefinement and p::d::SolutionTransfer for dim==1
  source/distributed/grid_refinement.inst.in
  source/distributed/solution_transfer.inst.in
Labels: Parallel distributed
