Repository dealii/dealii, pull requests merged in 2019-09, with the labels that each got.

#8679 Update PolynomialsBDM degree and pass the degree to the base class constructor
  doc/news/changes/minor/20190902Harper
  include/deal.II/base/polynomials_bdm.h
  source/base/polynomials_bdm.cc
  tests/base/polynomials_bdm_01.cc
  tests/base/polynomials_bdm_02.cc
Labels: Reviewed and ready to merge, ready to test

#8678 Change polynomial classes to derive from ScalarPolynomialsBase
  include/deal.II/base/polynomial_space.h
  include/deal.II/base/polynomials_rannacher_turek.h
  include/deal.II/base/tensor_product_polynomials.h
  include/deal.II/base/tensor_product_polynomials_bubbles.h
  include/deal.II/base/tensor_product_polynomials_const.h
  include/deal.II/fe/fe_poly.h
  include/deal.II/fe/fe_poly_face.h
  source/base/polynomial_space.cc
  source/base/polynomials_bdm.cc
  source/base/polynomials_rannacher_turek.cc
  source/base/tensor_product_polynomials.cc
  source/base/tensor_product_polynomials_bubbles.cc
  source/base/tensor_product_polynomials_const.cc
  source/fe/fe_bdm.cc
  source/fe/fe_dgp_nonparametric.cc
  source/fe/mapping_q_generic.cc
  tests/base/anisotropic_1.cc
  tests/base/polynomial_test.cc
Labels: ready to test

#8688 BlockVectorBase::equ with 4 arguments removed
  doc/news/changes/incompatibilities/20190903RezaRastak
  include/deal.II/lac/block_vector_base.h
Labels: Reviewed and ready to merge, ready to test

#8680 Fix a bug with cuda and hanging nodes
  doc/news/changes/minor/20190831BrunoTurcksin
  include/deal.II/matrix_free/cuda_hanging_nodes_internal.h
  tests/cuda/matrix_free_matrix_vector_01.output
  tests/cuda/matrix_free_matrix_vector_02.output
  tests/cuda/matrix_free_matrix_vector_03.cu
  tests/cuda/matrix_free_matrix_vector_03.output
  tests/cuda/matrix_free_matrix_vector_03b.cu
  tests/cuda/matrix_free_matrix_vector_03b.output
  tests/cuda/matrix_free_matrix_vector_04.output
  tests/cuda/matrix_free_matrix_vector_05.cu
  tests/cuda/matrix_free_matrix_vector_05.output
  tests/cuda/matrix_vector_common.h
Labels: GPU

#8692 Remove outdated documentation on largest allowed number of dofs.
  doc/doxygen/headers/distributed.h
Labels: Reviewed and ready to merge

#8681 Rename variable
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#8690 remove unused variable in grid_out.cc
  source/grid/grid_out.cc
Labels: Reviewed and ready to merge, ready to test

#8694 Indent a block properly.
  source/numerics/data_out.cc
Labels: ready to test

#8546 Remove diff from testsuite
  cmake/macros/macro_deal_ii_add_test.cmake
  cmake/macros/macro_deal_ii_pickup_tests.cmake
  cmake/scripts/run_test.sh
  doc/developers/testsuite.html
  doc/news/changes/incompatibilities/20190810DavidWells
  doc/users/testsuite.html
  tests/data_out/data_out_base_dx.binary.output
  tests/data_out/data_out_base_dx.cc
  tests/data_out/data_out_base_dx.output
Labels: Build system, Tests, ready to test

#8695 Make hp::FEvaluesBase non-internal.
  include/deal.II/hp/fe_values.h
  source/hp/fe_values.cc
  source/hp/fe_values.inst.in
Labels: Documentation, Enhancement, Reviewed and ready to merge, ready to test

#8700 VectorizedArray: Some minor doxygen markup improvements
  include/deal.II/base/vectorization.h
Labels: Reviewed and ready to merge, ready to test

#8699 GeometryInfo<dim>::unit_normal_vector
  doc/news/changes/minor/20190904RezaRastak
  include/deal.II/base/geometry_info.h
  source/base/geometry_info.cc
  source/fe/mapping_cartesian.cc
  tests/base/geometry_info_9.cc
  tests/base/geometry_info_9.output
Labels: Reviewed and ready to merge, ready to test

#8662 Allow using PreconditionChebyshev for parallel::distributed::Vector with MemorySpace::CUDA
  doc/news/changes/minor/20190903DanielArndt
  include/deal.II/lac/affine_constraints.h
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/precondition.h
  tests/cuda/matrix_vector_mf.h
  tests/cuda/precondition_03.cu
  tests/cuda/precondition_03.with_trilinos=true.with_mpi=true.with_p4est=true.mpirun=1.output
  tests/cuda/precondition_03.with_trilinos=true.with_mpi=true.with_p4est=true.mpirun=2.output
Labels: GPU, Reviewed and ready to merge, ready to test

#8702 list within the documentation of FunctionTime fixed
  include/deal.II/base/function_time.h
Labels: Documentation

#8705 Utilities::fixed_power - use exponentiation by squaring
  include/deal.II/base/utilities.h
  tests/base/utilities_02b.cc
  tests/base/utilities_02b.output
  tests/base/utilities_02b.output.avx
  tests/base/utilities_02b.output.avx512
  tests/base/utilities_02b.output.sse2
Labels: ready for review, ready to test

#8704 Fix undefined references for set_zero_all
  doc/news/changes/minor/20190905DanielArndt
  include/deal.II/lac/la_vector.h
  source/lac/affine_constraints.cu
  source/lac/affine_constraints.inst.in
Labels: ready to test

#8707 VectorizedArrary: add a test for std::pow
  tests/base/vectorization_13.cc
  tests/base/vectorization_13.output
  tests/base/vectorization_13.output.avx
  tests/base/vectorization_13.output.avx512
  tests/base/vectorization_13.output.sse2
Labels: Reviewed and ready to merge, SIMD, ready to test

#8701 VectorizedArray: Implement a compare_and_apply_mask function
  doc/news/changes/minor/20190905MatthiasMaier
  include/deal.II/base/vectorization.h
  tests/base/vectorization_14.cc
  tests/base/vectorization_14.output
  tests/base/vectorization_14.output.avx
  tests/base/vectorization_14.output.avx512
  tests/base/vectorization_14.output.sse
Labels: SIMD, ready for review, ready to test

#8703 Fix compiling with CUDA support
  include/deal.II/base/geometry_info.h
Labels: GPU, ready to test

#8717 Remove an unnecessary friend declaration.
  include/deal.II/distributed/tria.h
Labels: Reviewed and ready to merge, ready to test

#8716 Make a variable 'const'.
  include/deal.II/fe/fe_poly_tensor.h
Labels: Reviewed and ready to merge, ready to test

#8719 fix broken step-56
  examples/step-56/step-56.cc
Labels: Reviewed and ready to merge, ready to test

#8725 Fix doxygen documenation of p:d:t
  include/deal.II/distributed/tria.h
Labels: Documentation

#8724 Generalize an if-statement for all parallel triangulations
  source/dofs/dof_handler.cc
Labels: Parallel distributed, Parallel shared, ready to test

#8720 Clarify the degree of the elements NedelecSZ and Nedelec
  include/deal.II/fe/fe_nedelec.h
  include/deal.II/fe/fe_nedelec_sz.h
  source/fe/fe_nedelec_sz.cc
Labels: Reviewed and ready to merge, ready to test

#8732 Move the call to update_number_cache() after all other calls.
  source/distributed/tria.cc
Labels: Parallel distributed, ready to test

#8648 Make postprocessors work when using complex-valued solutions.
  include/deal.II/numerics/data_out_dof_data.templates.h
  source/numerics/data_out.cc
  tests/data_out/data_out_complex_postprocessor_01.cc
  tests/data_out/data_out_complex_postprocessor_01.with_complex_values=on.output
Labels: ready to test

#8668 Split MappingCartesian::compute_fill into several functions.
  include/deal.II/fe/mapping_cartesian.h
  source/fe/mapping_cartesian.cc
Labels: Enhancement, Mapping, ready to test

#8737 Add CellId::is_parent_of
  doc/news/changes/minor/20190911PeterMunch
  include/deal.II/grid/cell_id.h
  tests/grid/cell_id_06.cc
  tests/grid/cell_id_06.output
Labels: Reviewed and ready to merge, ready to test

#8731 p:d:step-27: Adjusted AdditionalData object for Trilinos.
  tests/mpi/trilinos_step-27.cc
Labels: Linear Algebra, Reviewed and ready to merge, ready to test

#8746 Add Boost serialization function to CellData
  doc/news/changes/minor/20190913PeterMunch
  include/deal.II/grid/tria.h
  tests/serialization/cell_data_1.cc
  tests/serialization/cell_data_1.output
Labels: Parallel distributed, ready to test

#8749 Improve performance of DoFHandler::distribute_mg_dofs
  doc/news/changes/minor/20190913MartinKronbichler
  source/dofs/dof_handler_policy.cc
Labels: Parallel distributed, ready to test

#8747 Change gzip compression level to best_speed
  source/dofs/number_cache.cc
Labels: Parallel, ready to test

#8751 Move operator== from a test to the CellData class itself.
  include/deal.II/grid/tria.h
  source/grid/tria.cc
  tests/serialization/cell_data_1.cc
Labels: ready to test

#8726 Simplify matrix_free/parallel_multigrid_adaptive_03 test
  tests/matrix_free/parallel_multigrid_adaptive_03.cc
  tests/matrix_free/parallel_multigrid_adaptive_03.with_mpi=true.with_p4est=true.with_lapack=true.mpirun=4.output
  tests/matrix_free/parallel_multigrid_adaptive_03.with_mpi=true.with_p4est=true.with_lapack=true.mpirun=7.output
Labels: Matrix-free, Tests, ready to test

#8756 Fix a few typos in changelogs
  doc/news/changes/minor/20190704PeterMunch
  doc/news/changes/minor/20190710PeterMunch
  doc/news/changes/minor/20190808KatherineCosburn
  doc/news/changes/minor/20190809RezaRastakMarcFehlingPeterMunch
Labels: Documentation

#8754 Disable compression in ghost exchange of DoFHandler
  doc/news/changes/minor/20190916MartinKronbichler
  include/deal.II/grid/grid_tools.h
Labels: Parallel distributed, ready to test

#8742 Change TensorProductPolynomialsBubbles from "is-a" to "has-a" TensorProductPolynomials
  include/deal.II/base/tensor_product_polynomials.h
  include/deal.II/base/tensor_product_polynomials_bubbles.h
  source/base/tensor_product_polynomials_bubbles.cc
Labels: ready to test

#8741 Updates to the step-65 documentation.
  examples/step-65/doc/intro.dox
  examples/step-65/doc/results.dox
  examples/step-65/step-65.cc
Labels: Tutorials, ready to test

#8709 Add maxwell singularity test
  tests/fe/fe_nedelec_singularity_01.cc
  tests/fe/fe_nedelec_singularity_01.with_petsc_with_mumps=true.with_petsc_with_complex=true.mpirun=4.output
  tests/fe/fe_nedelec_singularity_02.cc
  tests/fe/fe_nedelec_singularity_02.with_petsc_with_mumps=true.with_petsc_with_complex=false.mpirun=4.output
Labels: Reviewed and ready to merge, ready to test

#8723 Change TensorProductPolynomials and AnisotropicPolynomials to derive from ScalarPolynomialsBase
  include/deal.II/base/tensor_product_polynomials.h
  include/deal.II/base/tensor_product_polynomials_bubbles.h
  include/deal.II/base/tensor_product_polynomials_const.h
  source/base/polynomials_abf.cc
  source/base/polynomials_bernardi_raugel.cc
  source/base/polynomials_nedelec.cc
  source/base/polynomials_raviart_thomas.cc
  source/base/tensor_product_polynomials.cc
  source/base/tensor_product_polynomials_bubbles.cc
  source/base/tensor_product_polynomials_const.cc
  tests/base/anisotropic_1.cc
Labels: Reviewed and ready to merge, ready to test

#8760 fixed inconsistent state in TimestepControl
  source/algorithms/timestep_control.cc
Labels: Reviewed and ready to merge, ready to test

#8767 Remove default constructor for classes derived from Function<dim> if empty.
  examples/step-13/step-13.cc
  examples/step-14/step-14.cc
  examples/step-15/step-15.cc
  examples/step-27/step-27.cc
  examples/step-37/step-37.cc
  examples/step-38/step-38.cc
  examples/step-41/step-41.cc
  examples/step-50/step-50.cc
  examples/step-51/step-51.cc
  examples/step-59/step-59.cc
  examples/step-61/step-61.cc
  examples/step-63/step-63.cc
  examples/step-7/step-7.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#8761 Change TensorProductPolynomialsConst from "is-a" to "has-a" TensorProductPolynomials
  include/deal.II/base/tensor_product_polynomials.h
  include/deal.II/base/tensor_product_polynomials_bubbles.h
  include/deal.II/base/tensor_product_polynomials_const.h
  source/base/tensor_product_polynomials_const.cc
Labels: Reviewed and ready to merge, ready to test

#8753 Add random particle generator
  doc/doxygen/references.bib
  doc/news/changes/minor/20190913ReneGassmoeller
  include/deal.II/particles/generators.h
  source/particles/generators.cc
  source/particles/generators.inst.in
  tests/particles/generators_04.cc
  tests/particles/generators_04.with_p4est=true.output
  tests/particles/generators_05.cc
  tests/particles/generators_05.with_p4est=true.mpirun=2.output
  tests/particles/generators_05.with_p4est=true.output
  tests/particles/generators_06.cc
  tests/particles/generators_06.with_p4est=true.mpirun=2.output
  tests/particles/generators_06.with_p4est=true.output
Labels: Reviewed and ready to merge, ready to test

#8660 introduce FEInterfaceValues
  doc/news/changes/major/20190824Heister
  include/deal.II/fe/fe_interface_values.h
  tests/feinterface/CMakeLists.txt
  tests/feinterface/fe_interface_values_01.cc
  tests/feinterface/fe_interface_values_01.output
  tests/feinterface/fe_interface_values_02.cc
  tests/feinterface/fe_interface_values_02.output
  tests/feinterface/fe_interface_values_03.cc
  tests/feinterface/fe_interface_values_03.output
  tests/feinterface/fe_interface_values_04.cc
  tests/feinterface/fe_interface_values_04.output
  tests/feinterface/fe_interface_values_05.cc
  tests/feinterface/fe_interface_values_05.output
  tests/feinterface/fe_interface_values_06.cc
  tests/feinterface/fe_interface_values_06.output
  tests/feinterface/fe_interface_values_07.cc
  tests/feinterface/fe_interface_values_07.output
  tests/feinterface/step-12.cc
  tests/feinterface/step-12.output
Labels: Reviewed and ready to merge, ready to test

#8730 add interface for user defined GMG constraints
  doc/news/changes/minor/20190913Clevenger
  include/deal.II/multigrid/mg_constrained_dofs.h
  source/lac/affine_constraints.inst.in
  source/multigrid/mg_transfer_matrix_free.cc
  source/multigrid/mg_transfer_prebuilt.cc
  source/multigrid/multigrid.cc
  tests/multigrid/transfer_matrix_free_13.cc
  tests/multigrid/transfer_matrix_free_13.output
Labels: ready to test

#8763 Update small pieces in TimestepControl.
  include/deal.II/algorithms/timestep_control.h
Labels: ready to test

#8765 Avoid warnings as a result of an unused variable.
  include/deal.II/base/tensor_product_polynomials_bubbles.h
  source/base/tensor_product_polynomials_bubbles.cc
Labels: ready to test

#8745 Update the documentation of the MeshWorker::LocalResults class.
  include/deal.II/meshworker/local_results.h
Labels: ready to test

#8622 Introduce new parallel::fullydistributed::Triangulation
  doc/news/changes/major/20190726PeterMunch
  doc/news/changes/minor/20190902PeterMunch
  include/deal.II/distributed/fully_distributed_tria.h
  include/deal.II/distributed/fully_distributed_tria_util.h
  source/distributed/CMakeLists.txt
  source/distributed/fully_distributed_tria.cc
  source/distributed/fully_distributed_tria.inst.in
  source/distributed/fully_distributed_tria_util.cc
  source/distributed/fully_distributed_tria_util.inst.in
  source/grid/grid_tools_dof_handlers.cc
  source/grid/tria.cc
  tests/fullydistributed_grids/CMakeLists.txt
  tests/fullydistributed_grids/copy_distributed_tria_01.cc
  tests/fullydistributed_grids/copy_distributed_tria_01.with_p4est=true.mpirun=1.output
  tests/fullydistributed_grids/copy_distributed_tria_01.with_p4est=true.mpirun=7.output
  tests/fullydistributed_grids/copy_distributed_tria_02.cc
  tests/fullydistributed_grids/copy_distributed_tria_02.with_p4est=true.mpirun=1.output
  tests/fullydistributed_grids/copy_distributed_tria_02.with_p4est=true.mpirun=7.output
  tests/fullydistributed_grids/copy_serial_tria_01.cc
  tests/fullydistributed_grids/copy_serial_tria_01.mpirun=1.output
  tests/fullydistributed_grids/copy_serial_tria_01.mpirun=7.output
  tests/fullydistributed_grids/copy_serial_tria_02.cc
  tests/fullydistributed_grids/copy_serial_tria_02.mpirun=1.output
  tests/fullydistributed_grids/copy_serial_tria_02.mpirun=7.output
  tests/fullydistributed_grids/copy_serial_tria_03.cc
  tests/fullydistributed_grids/copy_serial_tria_03.mpirun=1.output
  tests/fullydistributed_grids/copy_serial_tria_03.mpirun=7.output
  tests/fullydistributed_grids/copy_serial_tria_04.cc
  tests/fullydistributed_grids/copy_serial_tria_04.mpirun=1.output
  tests/fullydistributed_grids/copy_serial_tria_04.mpirun=7.output
  tests/fullydistributed_grids/copy_serial_tria_05.cc
  tests/fullydistributed_grids/copy_serial_tria_05.mpirun=9.output
  tests/fullydistributed_grids/tests.h
Labels: Parallel distributed, ready to test

#8766 Provide some explanation on 'virtual' and 'override'.
  examples/step-4/step-4.cc
Labels: Documentation, Tutorials, ready to test

#8775 Replace set with vector in pft:util
  source/distributed/fully_distributed_tria_util.cc
Labels: Reviewed and ready to merge, ready to test

#8779 Fix compiling with clang
  source/particles/generators.cc
Labels: Reviewed and ready to merge, ready to test

#8773 Add function MappingCartesian::fill_jacobian_derivatives(..)
  include/deal.II/fe/mapping_cartesian.h
  source/fe/mapping_cartesian.cc
Labels: Reviewed and ready to merge, ready to test

#8759 improve check for CAN_CALL_NONCONSTEXPR
  cmake/checks/check_01_cxx_features.cmake
Labels: ready to test

#8784 Remove an auto from a lambda in pft
  source/distributed/fully_distributed_tria.cc
Labels: Parallel distributed, Reviewed and ready to merge, ready to test

#8654 Added GridGenerator::generate_from_name_and_arguments
  doc/news/changes/minor/20190827LucaHeltai
  include/deal.II/base/mutable_bind.h
  include/deal.II/grid/grid_generator.h
  source/grid/CMakeLists.txt
  source/grid/grid_generator_from_name.cc
  source/grid/grid_generator_from_name.inst.in
  source/numerics/vector_tools_project_qpmf.inst.in
  tests/grid_generator_from_name_and_argument_01.cc
  tests/grid_generator_from_name_and_argument_01.output
Labels: ready for review, ready to test

#8790 remove warning in fully_distributed_tria_util
  source/distributed/fully_distributed_tria_util.inst.in
Labels: Reviewed and ready to merge, ready to test

#8792 Remove obsolete global communication from MGTransfer
  source/multigrid/mg_transfer_internal.cc
Labels: Geometric multigrid, Reviewed and ready to merge, ready to test

#8795 Make a char[30] variable into a std::string.
  doc/news/changes/incompatibilities/20190918Bangerth
  include/deal.II/algorithms/timestep_control.h
  source/algorithms/timestep_control.cc
Labels: Bug, Reviewed and ready to merge, ready to test

#8796 fixed the usage of deprecated std::uncaught_exception
  source/base/mpi.cc
  source/base/subscriptor.cc
  source/base/timer.cc
Labels: Reviewed and ready to merge, ready to test

#8787 Allow the two cell iterators given to FEInterfaceValues to be of different type.
  include/deal.II/fe/fe_interface_values.h
Labels: Reviewed and ready to merge, ready to test

#8748 Add boost serialization for ConstructionData
  doc/news/changes/minor/20190913PeterMunch-1
  include/deal.II/distributed/fully_distributed_tria.h
  tests/fullydistributed_grids/tests.h
  tests/serialization/parallel_fullydistributed_construction_data_1.cc
  tests/serialization/parallel_fullydistributed_construction_data_1.output
Labels: Parallel distributed, Reviewed and ready to merge, ready to test

#8798 Fix warning
  source/grid/grid_generator_from_name.cc
Labels: Reviewed and ready to merge, ready to test

#8789 enum Strategy is removed from TimestepControl
  doc/news/changes/incompatibilities/20190918RezaRastak
  include/deal.II/algorithms/timestep_control.h
  source/algorithms/timestep_control.cc
Labels: Reviewed and ready to merge, ready to test

#8794 Avoid dangling pointer in initializer_list
  include/deal.II/base/patterns.h
  include/deal.II/hp/fe_collection.h
  include/deal.II/hp/q_collection.h
  tests/mpi/hp_unify_dof_indices_07.cc
  tests/vector_tools/integrate_difference_04_hp.cc
Labels: Reviewed and ready to merge, ready to test

#8800 Speed up IndexSet::add_indices()
  doc/news/changes/minor/20190919MartinKronbichler-1
  include/deal.II/base/index_set.h
  source/base/index_set.cc
Labels: DoFs, Reviewed and ready to merge, ready to test

#8806 Move comparator of CellData and ConstructionData out of the tests
  include/deal.II/distributed/fully_distributed_tria.h
  tests/fullydistributed_grids/tests.h
Labels: Reviewed and ready to merge, ready to test

#8799 Speed up MGTools::make_boundary_list()
  doc/news/changes/minor/20190919MartinKronbichler-2
  source/multigrid/mg_tools.cc
Labels: Geometric multigrid, ready to test

#8804 Remove TimeStepControl::format altogether.
  doc/news/changes/incompatibilities/20190918Bangerth
  include/deal.II/algorithms/timestep_control.h
  source/algorithms/timestep_control.cc
Labels: ready to test

#8788 Add a test for FEInterfaceValues
  tests/feinterface/face_orientation_01.cc
  tests/feinterface/face_orientation_01.output
Labels: ready to test

#8807 Avoid calling the constructor for emplace_back
  include/deal.II/lac/vector_memory.templates.h
  source/base/parsed_convergence_table.cc
  source/dofs/dof_handler_policy.cc
Labels: ready to test

#8809 Fix data type in p:f:CellData
  include/deal.II/distributed/fully_distributed_tria.h
Labels: Parallel distributed, Reviewed and ready to merge, ready to test

#8752 Augment the documentation of the Particle class.
  include/deal.II/particles/particle.h
Labels: Documentation

#8816 instantiate uninitialized tensor struct
  include/deal.II/base/tensor.h
Labels: Reviewed and ready to merge, ready to test

#8808 Compute number of locally owned active cells per process on-demand
  doc/news/changes/incompatibilities/20190920PeterMunch
  include/deal.II/distributed/tria_base.h
  source/distributed/tria_base.cc
  tests/mpi/cell_weights_01.cc
  tests/mpi/cell_weights_01_back_and_forth_01.cc
  tests/mpi/cell_weights_01_back_and_forth_02.cc
  tests/mpi/cell_weights_02.cc
  tests/mpi/cell_weights_03.cc
  tests/mpi/cell_weights_04.cc
  tests/mpi/cell_weights_05.cc
  tests/mpi/cell_weights_06.cc
  tests/mpi/hp_step-40.cc
  tests/mpi/hp_step-40_variable_01.cc
  tests/mpi/step-40.cc
  tests/mpi/step-40_cuthill_mckee.cc
  tests/mpi/step-40_cuthill_mckee_MPI-subset.cc
  tests/mpi/step-40_direct_solver.cc
Labels: Reviewed and ready to merge, ready to test

#8823 Remove colon after @note.
  include/deal.II/base/function.h
  include/deal.II/distributed/tria_base.h
  include/deal.II/dofs/dof_tools.h
  include/deal.II/lac/read_write_vector.h
  include/deal.II/numerics/vector_tools.h
Labels: Documentation, Reviewed and ready to merge

#8822 Better document parallel::DistributedTriangulationBase.
  include/deal.II/distributed/tria_base.h
Labels: Documentation

#8818 Remove std::bind from hp
  source/hp/dof_handler.cc
Labels: Reviewed and ready to merge, ready to test

#8772 Eliminate MPI all-to-all communication in MPI::Partitioner
  doc/news/changes/minor/20190603PeterMunch-1
  doc/news/changes/minor/20190917PeterMunchMartinKronbichler
  include/deal.II/base/mpi.h
  include/deal.II/base/mpi_compute_index_owner_internal.h
  source/base/mpi.cc
  source/base/partitioner.cc
Labels: Parallel distributed, ready to test

#8750 Create p:f:ConstructionData by a selected group of processes
  doc/news/changes/minor/20190913PeterMunch-2
  include/deal.II/distributed/fully_distributed_tria_util.h
  source/distributed/fully_distributed_tria_util.cc
  source/distributed/fully_distributed_tria_util.inst.in
  tests/fullydistributed_grids/copy_serial_tria_grouped_01.cc
  tests/fullydistributed_grids/copy_serial_tria_grouped_01.mpirun=7.output
Labels: Parallel distributed, ready to test

#8805 Better document parallel::TriangulationBase.
  include/deal.II/distributed/shared_tria.h
  include/deal.II/distributed/tria_base.h
Labels: Documentation

#8815 instantiate TensorProductPolynomials for dim=0
  include/deal.II/base/tensor_product_polynomials.h
  source/base/scalar_polynomials_base.cc
  source/base/tensor_product_polynomials.cc
Labels: ready to test

#8829 add to documentation of get_coarse_mesh_description()
  include/deal.II/grid/grid_tools.h
Labels: Documentation

#8833 Instantiate ConsensusAlgorithmSelector
  source/base/mpi.cc
Labels: Parallel distributed, Reviewed and ready to merge, ready to test

#8728 Embed vector operations in MatrixFree cell loops
  doc/news/changes/minor/20190910MartinKronbichler
  include/deal.II/matrix_free/dof_info.h
  include/deal.II/matrix_free/dof_info.templates.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/task_info.h
  source/matrix_free/task_info.cc
  tests/matrix_free/pre_and_post_loops_01.cc
  tests/matrix_free/pre_and_post_loops_01.with_mpi=true.with_p4est=true.mpirun=1.output
  tests/matrix_free/pre_and_post_loops_01.with_mpi=true.with_p4est=true.mpirun=3.output
  tests/matrix_free/pre_and_post_loops_02.cc
  tests/matrix_free/pre_and_post_loops_02.with_mpi=true.with_p4est=true.mpirun=3.output
  tests/matrix_free/pre_and_post_loops_03.cc
  tests/matrix_free/pre_and_post_loops_03.with_mpi=true.with_p4est=true.mpirun=3.output
  tests/matrix_free/pre_and_post_loops_04.cc
  tests/matrix_free/pre_and_post_loops_04.with_mpi=true.with_p4est=true.mpirun=2.output
  tests/matrix_free/pre_and_post_loops_05.cc
  tests/matrix_free/pre_and_post_loops_05.with_mpi=true.with_p4est=true.mpirun=2.output
Labels: Matrix-free, ready to test

#8739 add functions to access svd u and vt variables
  include/deal.II/lac/lapack_full_matrix.h
Labels: ready to test

#8835 Fix boost problems with MSVC
  bundled/boost-1.70.0/include/boost/config/pragma_message.hpp
  bundled/boost-1.70.0/include/boost/preprocessor/seq/detail/to_list_msvc.hpp
  cmake/configure/configure_2_boost.cmake
Labels: External libraries, ready to test

#8821 Improve coding conventions
  doc/doxygen/headers/coding_conventions.h
Labels: Documentation

#8830 Collate changelog entries
  doc/news/changes/minor/20190708LuelEmishaw
  doc/news/changes/minor/20190806BrunoBlais
  doc/news/changes/minor/20190806KiranaBergstrom
  doc/news/changes/minor/20190806MarieKajan
  doc/news/changes/minor/20190807Gleeson
  doc/news/changes/minor/20190807He
  doc/news/changes/minor/20190807ImbertGerard
  doc/news/changes/minor/20190807JiuhuaHu.txt
  doc/news/changes/minor/20190807Lata
  doc/news/changes/minor/20190807MJayadharan
  doc/news/changes/minor/20190807ManaswineeBezbaruah
  doc/news/changes/minor/20190807NicoleHayes
  doc/news/changes/minor/20190807RebeccaFildes
  doc/news/changes/minor/20190807RebeccaPereira
  doc/news/changes/minor/20190807Sanchez-Vizuet
  doc/news/changes/minor/20190807Tro
  doc/news/changes/minor/20190808AdrianaMoralesMiranda
  doc/news/changes/minor/20190808KatherineCosburn
  doc/news/changes/minor/20190808MatthiasMaier
  doc/news/changes/minor/20190810Workshop
  doc/news/changes/minor/doc/news/changes/minor/20190807AshnaAggarwal
Labels: Documentation

#8827 Improve GridGenerator documentation in a few places.
  doc/news/changes/minor/20190810Workshop
  include/deal.II/grid/grid_generator.h
Labels: Documentation

#8831 Improve some changelog entries.
  doc/news/changes/minor/20190610RolandRichter
  doc/news/changes/minor/20190723GarciaSanchez
  doc/news/changes/minor/20190802GarciaSanchez
  doc/news/changes/minor/20190806AdamLee
  doc/news/changes/minor/20190806JonathanRobey
  doc/news/changes/minor/20190806RezaRastak
  doc/news/changes/minor/20190808LucaHeltaiMatthiasMaier
  doc/news/changes/minor/20190808MJayadharan
  doc/news/changes/minor/20190808WenjuanZhang
  doc/news/changes/minor/20190809RezaRastakMarcFehlingPeterMunch
  doc/news/changes/minor/20190814PeterMunchBangerthDanielArndt
Labels: Documentation

#8841 fix documentation in DerivativeApproximation
  include/deal.II/numerics/derivative_approximation.h
Labels: Documentation

#8713 Put implementation details of FEFaceEvaluation into separate file
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/operators.h
  include/deal.II/matrix_free/vector_access_internal.h
Labels: Matrix-free, ready to test

#8842 Clean up more changelog entries.
  doc/news/changes/minor/20190809RezaRastakMarcFehlingPeterMunch
  doc/news/changes/minor/20190810Workshop
Labels: Documentation, Reviewed and ready to merge

#8836 Inline functions because of bugs in hipcc
  include/deal.II/hp/dof_faces.h
  include/deal.II/hp/dof_handler.h
  source/hp/dof_faces.cc
  source/hp/dof_handler.cc
Labels: GPU, Reviewed and ready to merge, ready to test

#8828 Assertion checks the wrong item size.
  source/fe/mapping_fe_field.cc
  tests/mappings/mapping_fe_field_01.cc
Labels: Reviewed and ready to merge, ready to test

#8769 Make DataPostprocessor work for complex-valued vector-valued problems.
  source/numerics/data_out.cc
  tests/data_out/data_out_complex_postprocessor_02.cc
  tests/data_out/data_out_complex_postprocessor_02.with_complex_values=on.output
  tests/data_out/data_out_postprocessor_vector_complex_01.cc
  tests/data_out/data_out_postprocessor_vector_complex_01.output
Labels: ready to test

#8817 Do not instantiate CellData for dim=0
  include/deal.II/grid/tria.h
  source/grid/grid_tools.cc
Labels: Reviewed and ready to merge, ready to test

#8825 Remove std::bind from source
  source/base/quadrature_lib.cc
  source/distributed/cell_weights.cc
  source/distributed/solution_transfer.cc
  source/dofs/dof_tools_constraints.cc
  source/fe/fe.cc
  source/fe/fe_values.cc
  source/grid/grid_in.cc
  source/grid/tria.cc
  source/grid/tria_objects.cc
  source/lac/sparsity_pattern.cc
  source/multigrid/mg_transfer_block.cc
  source/multigrid/mg_transfer_component.cc
  source/numerics/data_out.cc
  source/numerics/data_out_faces.cc
  source/numerics/data_out_rotation.cc
  source/numerics/derivative_approximation.cc
  source/numerics/point_value_history.cc
  source/numerics/time_dependent.cc
  source/particles/particle_handler.cc
Labels: ready to test

#8832 Remove std::bind from include (apart from documentation)
  include/deal.II/base/parallel.h
  include/deal.II/base/quadrature_point_data.h
  include/deal.II/base/time_stepping.templates.h
  include/deal.II/base/work_stream.h
  include/deal.II/distributed/cell_data_transfer.templates.h
  include/deal.II/lac/chunk_sparse_matrix.templates.h
  include/deal.II/lac/precondition.h
  include/deal.II/lac/relaxation_block.templates.h
  include/deal.II/lac/solver.h
  include/deal.II/lac/sparse_matrix.templates.h
  include/deal.II/matrix_free/dof_info.templates.h
  include/deal.II/matrix_free/matrix_free.templates.h
  include/deal.II/meshworker/loop.h
  include/deal.II/meshworker/mesh_loop.h
  include/deal.II/numerics/error_estimator.templates.h
  include/deal.II/numerics/matrix_creator.templates.h
Labels: ready to test

#8845 intel: disable const initializer warning
  cmake/setup_compiler_flags_intel.cmake
Labels: Reviewed and ready to merge

#8844 Rewrite the introduction to the RT element.
  include/deal.II/fe/fe_raviart_thomas.h
Labels: Documentation

#8837 Update the GPU matrix-free documentation
  include/deal.II/matrix_free/cuda_matrix_free.h
Labels: GPU

#8810 Change the storage type of MG copy indices to table
  doc/news/changes/minor/20190920MartinKronbichler
  include/deal.II/base/table.h
  include/deal.II/multigrid/mg_transfer.h
  include/deal.II/multigrid/mg_transfer.templates.h
  include/deal.II/multigrid/mg_transfer_internal.h
  source/multigrid/mg_level_global_transfer.cc
  source/multigrid/mg_transfer_internal.cc
  source/multigrid/mg_transfer_internal.inst.in
Labels: Geometric multigrid, ready to test

#8848 fix gcc 4.9 warning
  source/grid/grid_tools.cc
Labels: Reviewed and ready to merge, ready to test

#8770 Document DataPostprocessor for the case of complex-valued solutions.
  include/deal.II/numerics/data_postprocessor.h
Labels: Documentation, ready to test

#8783 Clean up compute_vertices_with_ghost_neighbors
  doc/news/changes/minor/20190921PeterMunch
  include/deal.II/distributed/fully_distributed_tria.h
  include/deal.II/distributed/tria.h
  source/distributed/fully_distributed_tria.cc
  source/distributed/tria.cc
  source/distributed/tria_base.cc
  source/dofs/dof_handler_policy.cc
Labels: Parallel distributed, ready to test

#8853 Modify method accessibility in ShapeInfo
  include/deal.II/matrix_free/shape_info.h
  include/deal.II/matrix_free/shape_info.templates.h
Labels: Matrix-free, ready to test

#8846 Avoid dynamic_cast in ghost/artificial cell queries
  include/deal.II/dofs/dof_handler.h
  include/deal.II/fe/mapping.h
  include/deal.II/grid/tria_accessor.templates.h
  include/deal.II/matrix_free/face_setup_internal.h
Labels: Triangulation, ready to test

#8839 Merge computation of values and gradients in the matrixfree CUDA code
  doc/news/changes/minor/20190924PeterMunch-1
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  include/deal.II/matrix_free/cuda_tensor_product_kernels.h
Labels: GPU

#8855 Store 1D quadrature in ShapeInfo
  include/deal.II/matrix_free/shape_info.h
  include/deal.II/matrix_free/shape_info.templates.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#8856 Store Mapping in MatrixFree's MappingInfo
  include/deal.II/matrix_free/mapping_info.h
  include/deal.II/matrix_free/mapping_info.templates.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#8857 Extend TensorProductMatrixSymmetricSum
  include/deal.II/lac/tensor_product_matrix.h
Labels: ready to test

#8863 Add missing test output
  tests/mpi/periodicity_03.with_trilinos=true.mpirun=3.output
Labels: Tests

#8861 Fix Manifold get_new_point()
  source/grid/manifold.cc
Labels: Manifold, ready to test

#8854 Compute shape_gradients/hessians_collocation in ShapeInfo
  include/deal.II/matrix_free/shape_info.h
  include/deal.II/matrix_free/shape_info.templates.h
Labels: Matrix-free, ready to test

#8838 Eliminate q_point from functor and other GPU functions
  doc/news/changes/minor/20190924PeterMunch
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  tests/cuda/matrix_free_no_index_initialize.cu
  tests/cuda/matrix_vector_mf.h
Labels: GPU

#8864 Change 'direction' of make_periodicity_constraint() to 'unsigned int'.
  doc/news/changes/incompatibilities/20190926Bangerth
  include/deal.II/dofs/dof_tools.h
  source/dofs/dof_tools_constraints.cc
  source/dofs/dof_tools_constraints.inst.in
Labels: Reviewed and ready to merge, ready to test

#8868 Enable assert again
  source/dofs/dof_handler_policy.cc
Labels: Reviewed and ready to merge, ready to test

#8860 Fix SolutionTransfer when coarsening from FE_Nothing
  source/dofs/dof_accessor_get.cc
  source/numerics/solution_transfer.cc
  tests/hp/solution_transfer_16.cc
  tests/hp/solution_transfer_16.output
Labels: ready to test

#8874 Fix some clang-tidy 9 findings
  examples/step-63/step-63.cc
  include/deal.II/algorithms/general_data_storage.h
  include/deal.II/base/parameter_acceptor.h
  include/deal.II/lac/la_parallel_vector.templates.h
  source/base/patterns.cc
  source/dofs/dof_tools_constraints.cc
  source/lac/dynamic_sparsity_pattern.cc
Labels: ready to test

#8811 Avoid sorting a large array in MG fill_copy_indices
  source/multigrid/mg_transfer_internal.cc
Labels: Geometric multigrid, ready to test

#8871 Update step-64
  examples/step-64/step-64.cu
Labels: GPU

#8813 Process indices in ComputeIndexOwner by intervals
  include/deal.II/base/mpi_compute_index_owner_internal.h
Labels: Parallel distributed, ready to test

#8847 kinematics.h: fix always_inline
  include/deal.II/physics/elasticity/kinematics.h
Labels: ready to test

#8875 Bypass vector copy in MatrixFree::cell_loop with MPI
  doc/news/changes/minor/20190927MartinKronbichler
  examples/step-64/step-64.cu
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
Labels: GPU, Reviewed and ready to merge, ready to test

#8736 doxygen: rewrite set_canonical_doxygen.py in Perl
  doc/doxygen/CMakeLists.txt
  doc/doxygen/scripts/set_canonical_doxygen.pl
  doc/doxygen/scripts/set_canonical_doxygen.py
Labels: Documentation
