Repository dealii/dealii, pull requests merged in 2019-11, with the labels that each got.

#8971 Add copy assignment to MatrixFree::AdditionalData
  include/deal.II/matrix_free/matrix_free.h
  tests/matrix_free/additional_data_copy.cc
  tests/matrix_free/additional_data_copy.output
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#8973 Fix for fe-degree in VectorTools::project_boundary_values_curl_conforming_l2
  include/deal.II/numerics/vector_tools.templates.h
  source/numerics/vector_tools_integrate_difference.inst.in
  tests/numerics/project_bv_curl_conf_03.cc
  tests/numerics/project_bv_curl_conf_03.output
Labels: ready to test

#8948 Step-50 cleanup
  examples/step-50/step-50.cc
Labels: ready to test

#8712 Major redesign of hp::Refinement.
  include/deal.II/hp/refinement.h
  source/hp/refinement.cc
  source/hp/refinement.inst.in
  tests/hp/error_prediction.cc
  tests/hp/p_adaptivity_flags.cc
  tests/hp/p_adaptivity_flags.output
  tests/mpi/petsc_step-27.cc
  tests/mpi/trilinos_step-27.cc
Labels: Reviewed and ready to merge, ready to test

#8985 Fix templating of some DerivativeForm functions.
  include/deal.II/base/derivative_form.h
Labels: Reviewed and ready to merge, ready to test

#8988 Be consistent with spaces.
  include/deal.II/base/data_out_base.h
Labels: ready to test

#8986 disable intel system includes
  cmake/macros/macro_deal_ii_setup_target.cmake
Labels: Build system, Reviewed and ready to merge, ready to test

#8987 Use identity<...>::type in the right place.
  include/deal.II/hp/refinement.h
  source/hp/refinement.cc
  source/hp/refinement.inst.in
Labels: Reviewed and ready to merge, ready to test

#8984 Update the discussion about broken RT space in step-61.
  examples/step-61/doc/intro.dox
  examples/step-61/step-61.cc
Labels: Documentation, Tutorials, ready for review, ready to test

#8992 fix agrayver username
  .mailmap
Labels: Reviewed and ready to merge, ready to test

#8989 Added changes entry for pull request #8973
  doc/news/changes/minor/20191102Wollner
Labels: Documentation

#8979 Do not transfer the MPI communicator when copying the triangulation
  doc/news/changes/minor/20193110Grayver
  include/deal.II/distributed/tria_base.h
  source/distributed/tria_base.cc
Labels: ready to test

#8982 Fix create_construction_data_from_triangulation for periodic boundaries
  include/deal.II/grid/grid_tools.h
  source/distributed/fully_distributed_tria_util.cc
  source/distributed/tria_base.cc
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
  source/grid/grid_tools_dof_handlers.cc
  tests/fullydistributed_grids/copy_serial_tria_04.cc
  tests/fullydistributed_grids/copy_serial_tria_04.mpirun=1.output
  tests/fullydistributed_grids/copy_serial_tria_04.mpirun=4.output
  tests/fullydistributed_grids/copy_serial_tria_04.mpirun=5.output
Labels: Bug, ready to test

#8983 Fix Matrixfree for periodic faces and hanging nodes
  doc/news/changes/minor/20191103PeterMunch
  include/deal.II/matrix_free/face_setup_internal.h
  source/fe/fe_values.cc
  tests/fe/fe_subface_values_01.cc
  tests/fe/fe_subface_values_01.output
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#8981 Add new read_cell_data to FEEvaluationBase for arbitrary data types
  include/deal.II/matrix_free/fe_evaluation.h
  tests/matrix_free/read_cell_data.cc
  tests/matrix_free/read_cell_data.output
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#8964 implement MPI::CollectiveMutex
  doc/news/changes/minor/20191104TimoHeister
  include/deal.II/base/mpi.h
  source/base/mpi.cc
  tests/mpi/open_requests_01.cc
  tests/mpi/open_requests_01.mpirun=3.output
  tests/mpi/open_requests_02.cc
  tests/mpi/open_requests_02.mpirun=3.output
Labels: Reviewed and ready to merge, ready to test

#8996 Use face_iterators in tutorials
  doc/news/changes/minor/20190814PeterMunchBangerthDanielArndt
  examples/step-10/step-10.cc
  examples/step-14/step-14.cc
  examples/step-18/step-18.cc
  examples/step-20/step-20.cc
  examples/step-21/step-21.cc
  examples/step-22/step-22.cc
  examples/step-24/step-24.cc
  examples/step-29/step-29.cc
  examples/step-42/step-42.cc
  examples/step-43/step-43.cc
  examples/step-44/step-44.cc
  examples/step-46/step-46.cc
  examples/step-49/step-49.cc
  examples/step-51/step-51.cc
  examples/step-52/step-52.cc
  examples/step-53/step-53.cc
  examples/step-54/step-54.cc
  examples/step-61/step-61.cc
  examples/step-65/step-65.cc
  examples/step-7/step-7.cc
  examples/step-9/step-9.cc
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/dofs/dof_accessor.templates.h
  tests/dofs/range_based_for_dof_face.cc
  tests/dofs/range_based_for_dof_face.output
Labels: Reviewed and ready to merge, ready to test

#8933 Avoid empty MPI_Waitall in consensus algorithm
  include/deal.II/base/mpi_compute_index_owner_internal.h
  source/base/mpi.cc
Labels: ready to test

#8998 Fix compilation of gmsh support
  source/gmsh/utilities.cc
Labels: Reviewed and ready to merge, ready to test

#8997 use MPI::CollectiveMutex in several places
  include/deal.II/base/mpi_compute_index_owner_internal.h
  source/base/mpi.cc
Labels: Reviewed and ready to merge, ready to test

#9001 protect more MPI communication with a CollectiveMutex
  include/deal.II/base/mpi.h
  include/deal.II/fe/fe_tools_extrapolate.templates.h
  include/deal.II/grid/grid_tools.h
  source/distributed/tria.cc
  source/dofs/dof_handler_policy.cc
  source/lac/sparsity_tools.cc
  source/multigrid/mg_transfer_internal.cc
Labels: Reviewed and ready to merge, ready to test

#9003 fix 64bit IndexSet::add_indices
  doc/news/changes/minor/20191105TimoHeister
  include/deal.II/base/index_set.h
  source/base/index_set.cc
Labels: Reviewed and ready to merge, ready to test

#8962 Output all faces and edges to vtk
  doc/news/changes/minor/20191011PeterMunch
  include/deal.II/grid/grid_out.h
  source/grid/grid_out.cc
  tests/grid/grid_out_vtk_03.cc
  tests/grid/grid_out_vtk_03.output
Labels: Reviewed and ready to merge, ready to test

#8994 Slightly simplify MPI::ComputeIndexOwner::Dictionary range detection
  include/deal.II/base/mpi_compute_index_owner_internal.h
Labels: Parallel distributed, ready to test

#8976 added stl read/write functions
  doc/news/changes/minor/20191106NicolaGiuliani
  include/deal.II/opencascade/utilities.h
  source/opencascade/utilities.cc
  tests/opencascade/iges_files/DTMB-5415_bulbous_bow.iges
  tests/opencascade/iges_files/wing.iges
  tests/opencascade/stl_creation_single_patch.cc
  tests/opencascade/stl_creation_single_patch.output
  tests/opencascade/stl_creation_watertight.cc
  tests/opencascade/stl_creation_watertight.output
  tests/opencascade/stl_files/coarse_sphere_stl.inp
  tests/opencascade/stl_files/sphere_refined.stl
  tests/opencascade/stl_refinement.cc
  tests/opencascade/stl_refinement.output
  tests/opencascade/stl_write.cc
  tests/opencascade/stl_write.output
Labels: Reviewed and ready to merge, ready to test

#9002 return MPI_Comm by const ref
  include/deal.II/distributed/tria_base.h
  include/deal.II/multigrid/multigrid.h
  source/distributed/tria_base.cc
Labels: Reviewed and ready to merge, ready to test

#9005 Allow change of SIMD type via template argument
  doc/news/changes/minor/20191106DanielJodlbauer
  include/deal.II/matrix_free/operators.h
Labels: ready to test

#8419 Bloch periodic conditions (a.k.a. phase shift periodic conditions)
  doc/news/changes/minor/20191101GarciaSanchez
  include/deal.II/dofs/dof_tools.h
  source/dofs/dof_tools_constraints.cc
  source/dofs/dof_tools_constraints.inst.in
  tests/bits/periodicity_09.cc
  tests/bits/periodicity_09.output
Labels: ready to test

#9017 Minor updates to the documentation of step-20.
  examples/step-20/doc/intro.dox
Labels: Tutorials

#9016 Add missing namespace
  doc/news/changes/minor/20191107HassanMohammedTurckinBruno
  examples/step-54/step-54.cc
Labels: Reviewed and ready to merge, ready to test

#9020 Add missing header
  include/deal.II/hp/refinement.h
Labels: Reviewed and ready to merge, ready to test

#9030 configure trilinos: Ensure that we are linking against MPI for Tpetra configure check
  cmake/configure/configure_2_trilinos.cmake
Labels: Bug, Build system, Reviewed and ready to merge, ready to test

#9022 Do not hardcode the warp size
  include/deal.II/base/cuda_size.h
  include/deal.II/lac/cuda_kernels.h
  include/deal.II/lac/cuda_kernels.templates.h
  include/deal.II/matrix_free/cuda_matrix_free.h
Labels: GPU

#9024 64bit fixes for IndexSets
  include/deal.II/base/index_set.h
  tests/base/index_set_64bit_01.cc
  tests/base/index_set_64bit_01.with_64bit_indices=on.output
Labels: ready to test

#9033 Use ConsensusAlgorithm_NBX in compute_point_to_point_communication_pattern
  source/base/mpi.cc
Labels: ready to test

#9025 remove TimerOutput error spam
  source/base/timer.cc
Labels: ready to test

#9039 Add more choices to QuadratureSelector
  doc/news/changes/minor/20191111DanielJodlbauer
  source/base/quadrature_selector.cc
  tests/base/quadrature_selector.cc
  tests/base/quadrature_selector.output
Labels: Enhancement, Quadrature, ready to test

#9038 Make variable volatile to avoid incorrect optimization
  include/deal.II/lac/cuda_kernels.templates.h
Labels: GPU

#9041 Avoid warning about unused variable
  source/base/mpi.cc
Labels: Parallel distributed, ready to test

#8797 Allow multigrid transfer to use external vector partitioners
  doc/news/changes/minor/20190919MartinKronbichler
  include/deal.II/multigrid/mg_transfer_internal.h
  include/deal.II/multigrid/mg_transfer_matrix_free.h
  source/multigrid/mg_level_global_transfer.cc
  source/multigrid/mg_transfer_internal.cc
  source/multigrid/mg_transfer_internal.inst.in
  source/multigrid/mg_transfer_matrix_free.cc
  tests/matrix_free/parallel_multigrid_mf_02.cc
  tests/matrix_free/parallel_multigrid_mf_02.with_mpi=true.with_p4est=true.with_lapack=true.mpirun=3.output
Labels: Geometric multigrid, Parallel distributed, ready to test

#9042 Fix timer_07 test
  tests/base/timer_07.with_mpi=true.output
Labels: Reviewed and ready to merge, Tests, ready to test

#9018 Add a discussion about Schur complements to step-22.
  examples/step-22/doc/intro.dox
Labels: Documentation, Tutorials

#9010 use global list of MPI tags for collective communication
  include/deal.II/base/mpi.h
  include/deal.II/base/mpi_compute_index_owner_internal.h
  include/deal.II/base/mpi_tags.h
  include/deal.II/fe/fe_tools_extrapolate.templates.h
  include/deal.II/grid/grid_tools.h
  source/base/mpi.cc
  source/base/process_grid.cc
  source/distributed/fully_distributed_tria_util.cc
  source/distributed/tria.cc
  source/distributed/tria_base.cc
  source/dofs/dof_handler_policy.cc
  source/grid/grid_tools.cc
  source/lac/scalapack.cc
  source/lac/sparsity_tools.cc
  source/multigrid/mg_transfer_internal.cc
  source/particles/particle_handler.cc
Labels: Parallel distributed, ready to test

#9040 added stl read/write functions with compatibility
  doc/news/changes/minor/20191113NicolaGiuliani
  include/deal.II/opencascade/utilities.h
  source/opencascade/utilities.cc
  tests/opencascade/iges_files/DTMB-5415_bulbous_bow.iges
  tests/opencascade/iges_files/wing.iges
  tests/opencascade/stl_creation_single_patch.cc
  tests/opencascade/stl_creation_single_patch.output
  tests/opencascade/stl_creation_watertight.cc
  tests/opencascade/stl_creation_watertight.output
  tests/opencascade/stl_files/coarse_sphere_stl.inp
  tests/opencascade/stl_files/sphere_refined.stl
  tests/opencascade/stl_refinement.cc
  tests/opencascade/stl_refinement.output
  tests/opencascade/stl_write.cc
  tests/opencascade/stl_write.output
Labels: ready to test

#9048 fix compilation with opencascade version 6.8.0 and older
  source/opencascade/utilities.cc
Labels: Reviewed and ready to merge, ready to test

#9034 unify MPI tags for Partitioner/parallel Vector
  include/deal.II/base/mpi_tags.h
  include/deal.II/base/partitioner.h
  include/deal.II/base/partitioner.templates.h
  include/deal.II/lac/la_parallel_block_vector.templates.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/la_parallel_vector.templates.h
Labels: ready to test

#9023 Extend cell python wrappers and add face wrappers
  contrib/python-bindings/include/cell_accessor_wrapper.h
  contrib/python-bindings/include/tria_accessor_wrapper.h
  contrib/python-bindings/source/CMakeLists.txt
  contrib/python-bindings/source/cell_accessor_wrapper.cc
  contrib/python-bindings/source/export_cell_accessor.cc
  contrib/python-bindings/source/export_tria_accessor.cc
  contrib/python-bindings/source/tria_accessor_wrapper.cc
  contrib/python-bindings/source/wrappers.cc
  contrib/python-bindings/tests/cell_accessor_wrapper.py
  doc/news/changes/minor/20191114Grayver
Labels: Enhancement, Python

#9049 Allow initialization of MappingQCache by lambda
  doc/news/changes/minor/20191114MartinKronbichler
  include/deal.II/fe/mapping_q_cache.h
  source/fe/mapping_q_cache.cc
  source/fe/mapping_q_generic.cc
  tests/mappings/mapping_q_cache_04.cc
  tests/mappings/mapping_q_cache_04.output
Labels: Mapping, ready to test

#9052 Mark HangingNode member functions as 'inline'
  include/deal.II/matrix_free/cuda_hanging_nodes_internal.h
Labels: GPU, Reviewed and ready to merge, ready to test

#9050 Fix two places where we used too large numbers in communication channel
  include/deal.II/lac/la_parallel_block_vector.templates.h
  include/deal.II/matrix_free/matrix_free.h
Labels: Parallel distributed, ready to test

#9054 Defaulted copy constructor for Function
  include/deal.II/base/function.h
Labels: ready to test

#9059 Fix hp_cell_weights_03/04
  tests/mpi/hp_cell_weights_03.cc
  tests/mpi/hp_cell_weights_04.cc
Labels: Reviewed and ready to merge, Tests, ready to test

#9061 Doc: Minor changes to hp::Refinement.
  include/deal.II/hp/refinement.h
Labels: Documentation

#9051 Fix compiling with clang-3.7.1
  examples/step-13/step-13.cc
  examples/step-27/step-27.cc
  examples/step-38/step-38.cc
  examples/step-4/step-4.cc
  examples/step-41/step-41.cc
  examples/step-51/step-51.cc
  examples/step-61/step-61.cc
  examples/step-63/step-63.cc
  examples/step-7/step-7.cc
  source/grid/manifold_lib.cc
Labels: Discussion, ready to test

#9062 Avoid ambiguous unrolled_to_component_indices call
  include/deal.II/base/symmetric_tensor.h
Labels: Reviewed and ready to merge, ready to test

#9058 Fix compiling python-bindings
  contrib/python-bindings/include/cell_accessor_wrapper.h
Labels: Reviewed and ready to merge, ready to test

#9057 Fix ADOL-C warnings
  include/deal.II/base/symmetric_tensor.templates.h
  source/base/symmetric_tensor.cc
  source/base/symmetric_tensor.inst.in
Labels: ready to test

#9063 Avoid workaround for zero-dimensional C-style arrays
  include/deal.II/base/tensor_product_polynomials.h
  source/base/tensor_product_polynomials.cc
  source/base/tensor_product_polynomials_bubbles.cc
  source/base/tensor_product_polynomials_const.cc
Labels: Reviewed and ready to merge, ready to test

#9066 Fix ADOL-C tests
  include/deal.II/base/symmetric_tensor.templates.h
  source/differentiation/ad/adolc_number_types.cc
Labels: Reviewed and ready to merge, ready to test

#9079 Avoid warnings in python-bindings
  contrib/python-bindings/source/cell_accessor_wrapper.cc
  contrib/python-bindings/source/tria_accessor_wrapper.cc
  contrib/python-bindings/source/triangulation_wrapper.cc
Labels: Reviewed and ready to merge, ready to test

#9080 Fix compiling with MSVC
  cmake/checks/check_01_cxx_features.cmake
  contrib/ci/appveyor.yml
  include/deal.II/base/tensor.h
  include/deal.II/physics/elasticity/standard_tensors.h
Labels: ready to test

#9082 typedef LinearAlgebraDealII::BlockSparseMatrix is defined
  include/deal.II/lac/generic_linear_algebra.h
Labels: ready to test

#9085 Avoid C-style workaround in DataOutBase
  include/deal.II/base/data_out_base.h
Labels: ready to test

#9032 Generalize ComputeIndexOwner::Dictionary
  include/deal.II/base/mpi_compute_index_owner_internal.h
  source/base/partitioner.cc
  tests/mpi/compute_index_owner_01.cc
  tests/mpi/compute_index_owner_01.mpirun=2.output
  tests/mpi/parallel_partitioner_09.cc
  tests/mpi/parallel_partitioner_09.mpirun=3.output
Labels: Parallel distributed, ready to test

#9087 Restrict some MPI tests requiring p4est
  tests/dofs/dof_tools_12a.with_p4est=true.mpirun=1.output
  tests/dofs/dof_tools_12a.with_p4est=true.mpirun=3.output
  tests/fullydistributed_grids/copy_serial_tria_01.with_p4est=true.mpirun=1.output
  tests/fullydistributed_grids/copy_serial_tria_01.with_p4est=true.mpirun=5.output
  tests/fullydistributed_grids/copy_serial_tria_02.with_p4est=true.mpirun=1.output
  tests/fullydistributed_grids/copy_serial_tria_02.with_p4est=true.mpirun=5.output
  tests/fullydistributed_grids/copy_serial_tria_03.with_p4est=true.mpirun=1.output
  tests/fullydistributed_grids/copy_serial_tria_03.with_p4est=true.mpirun=5.output
  tests/fullydistributed_grids/copy_serial_tria_04.with_p4est=true.mpirun=1.output
  tests/fullydistributed_grids/copy_serial_tria_04.with_p4est=true.mpirun=4.output
  tests/fullydistributed_grids/copy_serial_tria_04.with_p4est=true.mpirun=5.output
  tests/fullydistributed_grids/copy_serial_tria_05.with_p4est=true.mpirun=9.output
  tests/fullydistributed_grids/copy_serial_tria_06.with_p4est=true.mpirun=5.output
Labels: Reviewed and ready to merge, ready to test

#9086 Minor consistency improvements in tensor.h
  include/deal.II/base/tensor.h
Labels: ready to test

#8999 Step-61 Use FE_DGRT instead of FE_RT
  examples/step-61/step-61.cc
Labels: Reviewed and ready to merge, ready to test

#9089 step-55: doc update, add citation
  doc/doxygen/references.bib
  examples/step-55/doc/intro.dox
Labels: Documentation

#9092 Fix typo (Genreal -> General)
  LICENSE.md
Labels: Documentation, Miscellaneous

#9090 make target documentation report location
  doc/doxygen/CMakeLists.txt
Labels: Build system, Documentation, ready to test

#9095 jenkins: allow testing master
  Jenkinsfile
Labels: Reviewed and ready to merge, ready to test

#9094 Relax default tolerance for find_all_active_cells_around_point
  include/deal.II/grid/grid_tools.h
  tests/grid/find_all_active_cells_around_point_03.cc
  tests/grid/find_all_active_cells_around_point_03.output
Labels: Triangulation, ready to test

#9091 README.md: display build status
  README.md
Labels: Reviewed and ready to merge, ready to test

#9088 Suppress warning in python-bindings
  contrib/python-bindings/source/export_point.cc
Labels: ready to test

#9055 Add python wrappers for MappingQGeneric
  contrib/python-bindings/include/cell_accessor_wrapper.h
  contrib/python-bindings/include/mapping_wrapper.h
  contrib/python-bindings/include/point_wrapper.h
  contrib/python-bindings/source/CMakeLists.txt
  contrib/python-bindings/source/cell_accessor_wrapper.cc
  contrib/python-bindings/source/export_mapping.cc
  contrib/python-bindings/source/mapping_wrapper.cc
  contrib/python-bindings/source/tria_accessor_wrapper.cc
  contrib/python-bindings/source/wrappers.cc
  contrib/python-bindings/tests/mapping_wrapper.py
  doc/news/changes/minor/20191118Grayver
Labels: Reviewed and ready to merge, ready to test

#9101 Only allocate some MappingQGeneric internal data if necessary
  doc/news/changes/minor/20191126MartinKronbichler-b
  source/fe/mapping_q_generic.cc
Labels: Mapping, ready to test

#9105 Simplify CUDAWrappers::MatrixFree::free
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
Labels: GPU

#9103 Relax assumpitions in GridTools::partition_triangulation_zorder
  include/deal.II/grid/grid_tools.h
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
  tests/grid/partition_triangulation_zorder_01.cc
  tests/grid/partition_triangulation_zorder_01.output
Labels: ready to test

#8774 Hdf5 documentation
  examples/step-3/doc/results.dox
Labels: Documentation, Tutorials

#9113 explicit instanciation is provided for Utilities::MPI::min
  source/base/mpi.inst.in
Labels: Reviewed and ready to merge, ready to test

#9097 Fix MatrixFree::reinit() with FE_Q with face integration facilities
  doc/news/changes/minor/20191126MartinKronbichler
  include/deal.II/matrix_free/matrix_free.templates.h
  tests/matrix_free/face_setup_01.cc
  tests/matrix_free/face_setup_01.with_mpi=true.with_p4est=true.mpirun=1.output
  tests/matrix_free/face_setup_01.with_mpi=true.with_p4est=true.mpirun=2.output
Labels: Matrix-free, ready to test
