Repository dealii/dealii, pull requests merged in 2019-05, with the labels that each got.

#7966 Clean up CUDAWrappers::MatrixFree::reinit interface
  include/deal.II/matrix_free/cuda_matrix_free.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  tests/cuda/matrix_free_matrix_vector_10.cu
  tests/cuda/matrix_free_matrix_vector_10a.cu
  tests/cuda/matrix_free_matrix_vector_19.cu
Labels: GPU

#7983 newline bug in grid_in_abaqus fixed
  source/grid/grid_in.cc
  tests/grid/grid_in_abaqus_01.cc
  tests/grid/grid_in_abaqus_01.output
  tests/grid/grids/abaqus/2d/2d_short_handwritten.inp
Labels: Reviewed and ready to merge, ready to test

#7985 Update module on user interfaces to AD libraries
  doc/doxygen/headers/automatic_and_symbolic_differentiation.h
Labels: Automatic differentiation, Documentation, ready for review

#7954 Edit the results section of step-61.
  examples/step-61/doc/intro.dox
  examples/step-61/doc/results.dox
Labels: Documentation, Tutorials

#7984 Enable doxygen to build SD documentation
  doc/doxygen/headers/automatic_and_symbolic_differentiation.h
  doc/doxygen/options.dox.in
Labels: Documentation, Symbolic differentiation, ready for review

#7987 Fix a couple of typos.
  source/fe/fe_poly_tensor.cc
Labels: Documentation, Reviewed and ready to merge

#7986 Align a set of equations.
  examples/step-61/doc/intro.dox
Labels: Reviewed and ready to merge

#7913 Mapping::get_center()
  doc/news/changes/minor/20190411LucaHeltai
  include/deal.II/fe/mapping.h
  source/fe/mapping.cc
  tests/mappings/mapping_q_eulerian_12.cc
  tests/mappings/mapping_q_eulerian_12.output
Labels: ready for review, ready to test

#7738 Step-63
  examples/step-63/block_jacobi.prm
  examples/step-63/block_sor.prm
  examples/step-63/doc/intro.dox
  examples/step-63/jacobi.prm
  examples/step-63/sor.prm
  examples/step-63/step-63.cc
Labels: ready to test

#7974 SD scalar operations: Creation of substitution maps
  include/deal.II/differentiation/sd/symengine_scalar_operations.h
  source/differentiation/sd/symengine_scalar_operations.cc
  tests/symengine/substitution_maps_scalar_03.cc
  tests/symengine/substitution_maps_scalar_03.output
Labels: Reviewed and ready to merge, Symbolic differentiation, ready to test

#6747 Add phononic cavity tutorial
  contrib/python-bindings/notebooks/index.ipynb
  contrib/python-bindings/notebooks/step-62.ipynb
  examples/CMakeLists.txt
  examples/step-62/CMakeLists.txt
  examples/step-62/doc/builds-on
  examples/step-62/doc/intro.dox
  examples/step-62/doc/kind
  examples/step-62/doc/results.dox
  examples/step-62/doc/tooltip
  examples/step-62/step-62.cc
  examples/step-62/step-62.ipynb
Labels: Reviewed and ready to merge, Tutorials, ready to test

#7973 SD tensor operations: Creation of, and addition to, substitution maps
  include/deal.II/differentiation/sd/symengine_tensor_operations.h
  source/differentiation/sd/symengine_tensor_operations.cc
  tests/symengine/substitution_maps_tensor_01.cc
  tests/symengine/substitution_maps_tensor_01.output
  tests/symengine/substitution_maps_tensor_02.cc
  tests/symengine/substitution_maps_tensor_02.output
Labels: Reviewed and ready to merge, Symbolic differentiation, ready to test

#7993 Add some missing override annotations to step-63.
  examples/step-63/step-63.cc
Labels: High Priority :warning:, Reviewed and ready to merge, Tutorials, ready to test

#7905 Parsed convergence table
  doc/news/changes/major/20190410LucaHeltai
  include/deal.II/base/parsed_convergence_table.h
  include/deal.II/base/patterns.h
  include/deal.II/numerics/vector_tools.h
  source/base/CMakeLists.txt
  source/base/parsed_convergence_table.cc
  tests/base/parsed_convergence_table_01.cc
  tests/base/parsed_convergence_table_01.output
  tests/base/parsed_convergence_table_02.cc
  tests/base/parsed_convergence_table_02.output
  tests/base/parsed_convergence_table_03.cc
  tests/base/parsed_convergence_table_03.output
  tests/base/parsed_convergence_table_04.cc
  tests/base/parsed_convergence_table_04.output
  tests/base/parsed_convergence_table_05.cc
  tests/base/parsed_convergence_table_05.output
  tests/base/parsed_convergence_table_06.cc
  tests/base/parsed_convergence_table_06.output
  tests/base/parsed_convergence_table_07.cc
  tests/base/parsed_convergence_table_07.output
  tests/base/parsed_convergence_table_08.cc
  tests/base/parsed_convergence_table_08.output
  tests/base/parsed_convergence_table_09.cc
  tests/base/parsed_convergence_table_09.output
  tests/base/parsed_convergence_table_10.cc
  tests/base/parsed_convergence_table_10.output
Labels: ready for review, ready to test

#7990 Rename a local variable, make one 'const'.
  include/deal.II/grid/grid_tools.h
  source/grid/grid_tools.cc
Labels: Reviewed and ready to merge, ready to test

#7995 Remove namespace aliases in SymEngine headers
  include/deal.II/differentiation/sd/symengine_math.h
  include/deal.II/differentiation/sd/symengine_number_types.h
  include/deal.II/differentiation/sd/symengine_scalar_operations.h
  include/deal.II/differentiation/sd/symengine_types.h
  include/deal.II/differentiation/sd/symengine_utilities.h
  source/differentiation/sd/symengine_scalar_operations.cc
Labels: Reviewed and ready to merge, Symbolic differentiation, ready to test

#7971 Updating Ginkgo wrapper after Ginkgo's release 1.0.0
  doc/external-libs/ginkgo.html
  include/deal.II/lac/ginkgo_solver.h
  source/lac/ginkgo_solver.cc
  tests/ginkgo/solver.cc
  tests/ginkgo/solver.output
Labels: Enhancement, External libraries, Reviewed and ready to merge, ready to test

#8005 Modernize step-23.
  examples/step-23/doc/results.dox
  examples/step-23/step-23.cc
Labels: Tutorials, ready to test

#8006 Modernize step-24.
  examples/step-24/doc/intro.dox
  examples/step-24/doc/results.dox
  examples/step-24/step-24.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#8007 Modernize step-25.
  examples/step-25/doc/intro.dox
  examples/step-25/step-25.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#8010 Add some documentation on chunk sizes.
  include/deal.II/lac/vector_operations_internal.h
Labels: Documentation

#8014 step-55 disable logic with complex PETSc
  examples/step-55/CMakeLists.txt
  examples/step-55/step-55.cc
Labels: Build system, ready to test

#8017 Fix Sacado tests
  tests/ad_common_tests/helper_scalar_coupled_4_components_01.h
  tests/sacado/helper_scalar_coupled_3_components_01_4.with_mpi=true.mpirun=2.output
Labels: ready to test

#8022 Fix a comment that had the wrong boundary id type.
  include/deal.II/numerics/matrix_tools.h
Labels: Documentation

#8016 Modernize step-63
  examples/step-63/step-63.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#8018 Fix some failing AD tests.
  tests/ad_common_tests/physics_functions_03.h
  tests/ad_common_tests/step-44-helper_res_lin_01.h
  tests/ad_common_tests/step-44-helper_scalar_01.h
  tests/ad_common_tests/step-44-helper_var_form_01.h
  tests/ad_common_tests/step-44-helper_vector_01.h
  tests/ad_common_tests/symmetric_tensor_functions_01.h
  tests/ad_common_tests/tensor_functions_01.h
  tests/adolc/prm/parameters-step-44.prm
  tests/sacado/prm/parameters-step-44.prm
Labels: Automatic differentiation, ready to test

#8023 Rewrite some code in step-61.
  examples/step-61/step-61.cc
Labels: Reviewed and ready to merge, ready to test

#8011 Sprinkling c++11-compliant constexpr onto tensor.h and numbers.h
  include/deal.II/base/numbers.h
  include/deal.II/base/tensor.h
  source/base/numbers.cc
  source/base/tensor.cc
Labels: Reviewed and ready to merge, ready to test

#8025 Modernize step-59
  examples/step-59/step-59.cc
Labels: Tutorials, ready to test

#8019 Modernize step-62
  examples/step-62/step-62.cc
Labels: Reviewed and ready to merge, ready to test

#8024 Modernize step 28
  examples/step-28/doc/intro.dox
  examples/step-28/doc/results.dox
  examples/step-28/step-28.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#8031 Rename a couple of functions in step-61.
  examples/step-61/step-61.cc
Labels: Reviewed and ready to merge, ready to test

#8035 Rewrite parts of step-61.
  examples/step-61/doc/intro.dox
  examples/step-61/step-61.cc
Labels: Reviewed and ready to merge, ready for review, ready to test

#8040 Adding inline in header file
  include/deal.II/base/tensor.h
Labels: Reviewed and ready to merge, ready to test

#8036 Modernize step-29.
  examples/step-29/doc/intro.dox
  examples/step-29/doc/results.dox
  examples/step-29/step-29.cc
Labels: Tutorials, ready to test

#8043 Modernize step-56
  examples/step-56/step-56.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#8027 Disable floating point exceptions in some scalapack tests.
  tests/scalapack/scalapack_10.cc
  tests/scalapack/scalapack_10_a.cc
  tests/scalapack/scalapack_10_b.cc
  tests/scalapack/scalapack_10_c.cc
  tests/scalapack/scalapack_10_d.cc
Labels: Reviewed and ready to merge, Tests, ready to test

#7822 Perform p-refinement during 'execute_coarsening_and_refinement()'.
  doc/news/changes/major/20190318Fehling
  doc/news/changes/minor/20190318Fehling
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/dofs/dof_accessor.templates.h
  include/deal.II/hp/dof_handler.h
  source/hp/dof_handler.cc
  tests/hp/p_refinement_and_coarsening.cc
  tests/hp/p_refinement_and_coarsening.output
  tests/mpi/p_refinement_and_coarsening.cc
  tests/mpi/p_refinement_and_coarsening.with_p4est=true.mpirun=1.output
  tests/mpi/p_refinement_and_coarsening.with_p4est=true.mpirun=3.output
  tests/mpi/p_refinement_and_coarsening.with_p4est=true.mpirun=8.output
Labels: Parallel distributed, Reviewed and ready to merge, hp, ready to test

#8039 Modernize step-51
  examples/step-51/doc/intro.dox
  examples/step-51/doc/results.dox
  examples/step-51/step-51.cc
Labels: Tutorials, ready to test

#8052 step-62: Fix adding real and complex numbers
  examples/step-62/step-62.cc
Labels: Reviewed and ready to merge, ready to test

#8050 Add some missing braces to fix step-62.
  examples/step-62/step-62.cc
Labels: Reviewed and ready to merge, ready to test

#8038 Modernize step-48
  examples/step-48/doc/intro.dox
  examples/step-48/doc/results.dox
  examples/step-48/step-48.cc
Labels: Tutorials, ready to test

#8046 Modernize step-52
  examples/step-52/step-52.cc
Labels: ready to test

#8055 Make the polynomial degrees in step-61 selectable.
  examples/step-61/doc/results.dox
  examples/step-61/step-61.cc
Labels: Reviewed and ready to merge, ready for review, ready to test

#8044 Modernize step 30
  examples/step-30/doc/intro.dox
  examples/step-30/doc/results.dox
  examples/step-30/step-30.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#8051 Fix gcc-9 warnings
  include/deal.II/base/thread_management.h
  include/deal.II/lac/full_matrix.templates.h
  include/deal.II/lac/sparse_matrix.h
  include/deal.II/particles/particle_iterator.h
  source/particles/particle_iterator.cc
Labels: ready to test

#8056 Simplify the code that partitions shared triangulations.
  source/grid/grid_tools.cc
Labels: Reviewed and ready to merge, ready for review, ready to test

#8061 Add some more information on the BR element.
  include/deal.II/fe/fe_bernardi_raugel.h
Labels: Reviewed and ready to merge

#8057 Clean up various loops in grid_tools.cc.
  source/grid/grid_tools.cc
Labels: Reviewed and ready to merge, ready to test

#8059 Modernize step 31
  examples/step-31/doc/intro.dox
  examples/step-31/step-31.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#8053 Add some examples to the mesh loop documentation
  include/deal.II/meshworker/mesh_loop.h
Labels: Documentation

#8048 add Utilities::MPI::mean_and_standard_deviation()
  doc/news/changes/minor/20190509DenisDavydov
  include/deal.II/base/mpi.h
  tests/mpi/collective_mean_std.cc
  tests/mpi/collective_mean_std.mpirun=2.output
Labels: Parallel distributed, ready to test

#8032 Improve inverse_Hilbert_space_filling_curve to handle degenerate cases
  doc/news/changes/minor/20190507DenisDavydov
  include/deal.II/base/utilities.h
  source/base/utilities.cc
  tests/base/utilities_16.cc
  tests/base/utilities_16.output
  tests/base/utilities_17.cc
  tests/base/utilities_17.output
  tests/base/utilities_18.cc
  tests/base/utilities_18.output
  tests/base/utilities_19.cc
  tests/base/utilities_19.output
Labels: Feature, ready to test

#8030 Fix compatibility with nanoflann 1.3.
  source/numerics/kdtree.cc
  tests/numerics/kdtree_01.cc
Labels: External libraries

#8021 provide access to p4est_t
  include/deal.II/distributed/tria.h
  source/distributed/tria.cc
Labels: Reviewed and ready to merge, ready to test

#8066 Make step-31 compile again
  examples/step-31/step-31.cc
Labels: High Priority :warning:, Tutorials, ready to test

#8047 Add DynamicSparsityPattern::get_view()
  doc/news/changes/minor/20190508DenisDavydov
  include/deal.II/lac/dynamic_sparsity_pattern.h
  source/lac/dynamic_sparsity_pattern.cc
  tests/sparsity/dynamic_sparsity_pattern_22.cc
  tests/sparsity/dynamic_sparsity_pattern_22.output
Labels: Linear Algebra, ready to test

#8020 tutorials: add keywords
  doc/doxygen/tutorial/tutorial.h.in
Labels: Documentation

#8063 Fix clang-4 warnings
  examples/step-24/step-24.cc
  examples/step-53/step-53.cc
  source/distributed/cell_weights.cc
Labels: Reviewed and ready to merge, ready to test

#8034 Remove some unnecessary std::moves.
  include/deal.II/fe/fe_face.h
  include/deal.II/fe/fe_poly.h
  include/deal.II/fe/fe_poly_face.h
  include/deal.II/fe/fe_poly_tensor.h
  source/fe/fe_dgp_nonparametric.cc
  source/fe/fe_enriched.cc
  source/fe/fe_nedelec_sz.cc
  source/fe/fe_p1nc.cc
  source/fe/fe_system.cc
  source/fe/mapping_cartesian.cc
  source/fe/mapping_fe_field.cc
  source/fe/mapping_manifold.cc
  source/fe/mapping_q.cc
  source/fe/mapping_q_generic.cc
Labels: Miscellaneous, ready to test

#7743 Using rtrees in GridTools::compute_point_locations_try_all for cell search
  include/deal.II/grid/grid_tools.h
  source/grid/grid_tools.cc
Labels: ready to test

#8078 step-61 announcement.
  doc/news/changes/major/20190502Wang
Labels: Reviewed and ready to merge

#7933 Minor cleanup of hp::DoFHandler.
  include/deal.II/hp/dof_handler.h
  source/dofs/dof_handler_policy.cc
  source/hp/dof_handler.cc
  tests/mpi/hp_cell_weights_04.cc
  tests/mpi/hp_cell_weights_04.with_mpi=true.with_metis=true.mpirun=2.output
  tests/mpi/hp_cell_weights_04.with_mpi=true.with_metis=true.mpirun=2.output.1
  tests/mpi/hp_refinement_01.cc
  tests/mpi/hp_refinement_02.cc
Labels: Reviewed and ready to merge, ready to test

#8069 Modernize step 32
  examples/step-32/doc/intro.dox
  examples/step-32/step-32.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#7628 Use canonical webpages
  contrib/utilities/check_encoding.py
  doc/doxygen/CMakeLists.txt
  doc/doxygen/scripts/set_canonical_doxygen.py
Labels: ready to test

#7978 Refactor configuration option into DEAL_II_MPI_WITH_CUDA_SUPPORT
  cmake/configure/configure_1_mpi.cmake
  cmake/configure/configure_2_cuda_aware_mpi.cmake
  cmake/setup_cached_variables.cmake
  doc/external-libs/cuda.html
  doc/news/changes/minor/20190104ArndtTurcksin
  include/deal.II/base/config.h.in
  include/deal.II/base/partitioner.templates.h
  include/deal.II/lac/la_parallel_vector.templates.h
Labels: Reviewed and ready to merge, ready for review, ready to test

#8074 Deprecate FEEvaluation::fill_JxW_values
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/operators.h
  tests/matrix_free/jxw_values.cc
  tests/matrix_free/jxw_values.output
Labels: Matrix-free, ready to test

#8071 Fix an array initialization.
  source/grid/manifold_lib.cc
Labels: Miscellaneous, Reviewed and ready to merge, ready to test

#8087 Update documentation relative to other changes.
  examples/step-22/step-22.cc
  examples/step-31/step-31.cc
  examples/step-55/step-55.cc
Labels: Tutorials

#8081 Deprecate nanoflann.
  doc/news/changes/major/20190510DavidWells
  include/deal.II/numerics/kdtree.h
Labels: External libraries, Reviewed and ready to merge, ready to test

#8065 DoFHandlerPolicy::renumber_dofs: skip unnecessary index set computation
  doc/news/changes/minor/20190510MartinKronbichler
  source/dofs/dof_handler_policy.cc
Labels: Parallel distributed, ready to test

#7638 Add AD::NumberType::none
  doc/news/changes/minor/20190125Jean-PaulPelteret
  include/deal.II/differentiation/ad/ad_number_traits.h
  include/deal.II/differentiation/ad/ad_number_types.h
  source/differentiation/ad/CMakeLists.txt
  source/differentiation/ad/ad_drivers.cc
  source/differentiation/ad/ad_drivers.inst.in
  source/differentiation/ad/ad_helpers.cc
  source/differentiation/ad/ad_helpers.inst.in
  tests/adolc/ad_number_traits_02a.output
  tests/adolc/ad_number_traits_02b.output
  tests/adolc/step-44.cc
  tests/adolc/tensor_ops_01.cc
  tests/sacado/ad_number_traits_02_none.cc
  tests/sacado/ad_number_traits_02_none.output
  tests/sacado/ad_number_traits_02a.output
  tests/sacado/ad_number_traits_02b.output
  tests/sacado/ad_number_traits_02c.output
  tests/sacado/ad_number_traits_02c.output.1
  tests/sacado/ad_number_traits_02c.output.cmplx_rad_advar_error
  tests/sacado/ad_number_traits_02d.output
  tests/sacado/ad_number_traits_02d.output.1
  tests/sacado/ad_number_traits_02d.output.cmplx_rad_advar_error
Labels: Automatic differentiation, Reviewed and ready to merge, ready to test

#8009 SD map operations: Add function to resolve explicit and cyclic dependencies
  doc/news/changes/minor/20190505Jean-PaulPelteret-1
  include/deal.II/differentiation/sd/symengine_scalar_operations.h
  source/differentiation/sd/symengine_scalar_operations.cc
  tests/symengine/substitution_maps_cyclic_dependencies_01.cc
  tests/symengine/substitution_maps_cyclic_dependencies_01.output
  tests/symengine/substitution_maps_cyclic_dependencies_02.cc
  tests/symengine/substitution_maps_cyclic_dependencies_02.output
Labels: Reviewed and ready to merge, Symbolic differentiation, ready for review, ready to test

#8002 Mapping::get_bounding_box()
  doc/news/changes/minor/20190503LucaHeltai
  include/deal.II/base/bounding_box.h
  include/deal.II/boost_adaptors/bounding_box.h
  include/deal.II/fe/mapping.h
  include/deal.II/grid/tria_accessor.h
  source/base/bounding_box.cc
  source/fe/mapping.cc
  source/grid/grid_tools_cache.cc
  tests/mappings/mapping_q_eulerian_13.cc
  tests/mappings/mapping_q_eulerian_13.output
Labels: ready for review, ready to test

#8008 SD scalar and tensor operations: Make, add to, and set value in symbol map
  doc/news/changes/minor/20190505Jean-PaulPelteret
  include/deal.II/differentiation/sd/symengine_scalar_operations.h
  include/deal.II/differentiation/sd/symengine_tensor_operations.h
  source/differentiation/sd/symengine_scalar_operations.cc
  tests/symengine/substitution_maps_scalar_04.cc
  tests/symengine/substitution_maps_scalar_04.output
  tests/symengine/substitution_maps_scalar_05.cc
  tests/symengine/substitution_maps_scalar_05.output
  tests/symengine/substitution_maps_tensor_03.cc
  tests/symengine/substitution_maps_tensor_03.output
  tests/symengine/substitution_maps_tensor_04.cc
  tests/symengine/substitution_maps_tensor_04.output
Labels: Reviewed and ready to merge, Symbolic differentiation, ready for review, ready to test

#8082 duplicated documentation in SymmetricTensor removed
  include/deal.II/base/symmetric_tensor.h
Labels: Reviewed and ready to merge, ready to test

#8088 Modernize step-21.
  examples/step-21/doc/intro.dox
  examples/step-21/doc/results.dox
  examples/step-21/step-21.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#8090 step-31: Fix compilation with clang
  examples/step-31/step-31.cc
Labels: High Priority :warning:, Reviewed and ready to merge, Tutorials, ready to test

#8093 Fix warnings in step-62
  examples/step-62/step-62.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#8104 Fix a changelog entry
  doc/news/changes/minor/20190505Jean-PaulPelteret
Labels: Documentation

#8096 Modernize step 43
  examples/step-43/step-43.cc
Labels: Reviewed and ready to merge, ready to test

#8099 Modernize step-26
  examples/step-26/step-26.cc
Labels: Reviewed and ready to merge, ready to test

#8094 Modernize step-46
  examples/step-46/step-46.cc
Labels: Reviewed and ready to merge, ready to test

#8100 Update step 34 38 41
  examples/step-34/doc/builds-on
  examples/step-34/doc/results.dox
  examples/step-34/step-34.cc
  examples/step-38/doc/intro.dox
  examples/step-38/doc/results.dox
  examples/step-38/step-38.cc
  examples/step-41/step-41.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#8097 Modernize step-42
  examples/step-42/step-42.cc
Labels: Reviewed and ready to merge, ready to test

#8095 Modernise step-44
  doc/doxygen/tutorial/tutorial.h.in
  examples/step-44/parameters.prm
  examples/step-44/step-44.cc
  include/deal.II/base/iterator_range.h
Labels: Reviewed and ready to merge, Tutorials, ready to test

#8105 Modernize/Fix step-55
  examples/step-55/doc/results.dox
  examples/step-55/step-55.cc
Labels: Reviewed and ready to merge, ready to test

#8103 SD: Better document and homogenise naming of template parameters
  include/deal.II/differentiation/sd/symengine_scalar_operations.h
  include/deal.II/differentiation/sd/symengine_tensor_operations.h
Labels: Reviewed and ready to merge, Symbolic differentiation, ready to test

#8109 Make step-55 compile again
  examples/step-55/step-55.cc
Labels: High Priority :warning:, Reviewed and ready to merge, Tutorials

#8092 Add comments to DoFHandlerPolicy changes
  source/dofs/dof_handler_policy.cc
Labels: DoFs, Documentation, Parallel distributed, Reviewed and ready to merge, ready to test

#8110 Modernise step-44 (part 2)
  examples/step-44/step-44.cc
Labels: Tutorials, ready to test

#8086 Fix python compatibility
  contrib/utilities/check_encoding.py
  doc/doxygen/scripts/set_canonical_doxygen.py
Labels: Build system, Documentation, High Priority :warning:

#8102 modernize step 6
  examples/step-6/step-6.cc
Labels: Reviewed and ready to merge, ready for review, ready to test

#8101 Modernize step-17
  examples/step-17/step-17.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#8072 Introduced future finite element indices.
  doc/news/changes/minor/20190224MarcFehling
  doc/news/changes/minor/20190318Fehling
  doc/news/changes/minor/20190510MarcFehling
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/dofs/dof_accessor.templates.h
  include/deal.II/grid/tria.h
  include/deal.II/hp/dof_handler.h
  include/deal.II/hp/dof_level.h
  source/distributed/cell_weights.cc
  source/distributed/solution_transfer.cc
  source/grid/grid_tools.cc
  source/hp/dof_handler.cc
  source/hp/dof_level.cc
  source/numerics/solution_transfer.cc
  tests/hp/future_fe_indices.cc
  tests/hp/future_fe_indices.output
  tests/hp/p_refinement_and_coarsening.cc
  tests/hp/p_refinement_and_coarsening.output
  tests/hp/refine_and_coarsen_flags.output
  tests/mpi/p_refinement_and_coarsening.cc
  tests/mpi/p_refinement_and_coarsening.with_p4est=true.mpirun=1.output
  tests/mpi/p_refinement_and_coarsening.with_p4est=true.mpirun=3.output
  tests/mpi/p_refinement_and_coarsening.with_p4est=true.mpirun=8.output
  tests/serialization/hp_dof_handler_01.cc
  tests/serialization/hp_dof_handler_01.with_64bit_indices=off.output
  tests/serialization/hp_dof_handler_01.with_64bit_indices=on.output
Labels: Parallel distributed, Reviewed and ready to merge, hp, ready to test

#8085 Run setting canonical pages as part of the doxygen generation process.
  doc/doxygen/CMakeLists.txt
Labels: Documentation

#8118 Add a missing newline.
  source/fe/fe_values_extractors.cc
Labels: Miscellaneous

#8119 Fix some double-word typos.
  examples/step-6/doc/intro.dox
  examples/step-61/doc/intro.dox
  examples/step-7/step-7.cc
  include/deal.II/base/function_lib.h
  include/deal.II/base/hdf5.h
  include/deal.II/differentiation/ad/ad_helpers.h
  include/deal.II/differentiation/sd/symengine_scalar_operations.h
  include/deal.II/differentiation/sd/symengine_tensor_operations.h
  include/deal.II/fe/fe_tools.h
  include/deal.II/fe/mapping_q_generic.h
  include/deal.II/grid/grid_generator.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/hp/fe_collection.h
  include/deal.II/integrators/l2.h
  include/deal.II/lac/affine_constraints.h
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/meshworker/scratch_data.h
  include/deal.II/meshworker/simple.h
Labels: Documentation

#8116 fix tables in tutorials
  examples/step-20/doc/results.dox
  examples/step-56/doc/results.dox
Labels: Documentation, Reviewed and ready to merge

#8115 doxygen fixes
  examples/.clang-format
  examples/step-42/step-42.cc
  examples/step-49/step-49.cc
  examples/step-59/step-59.cc
  include/deal.II/algorithms/general_data_storage.h
  include/deal.II/base/parsed_convergence_table.h
  include/deal.II/differentiation/sd/symengine_number_types.h
  include/deal.II/differentiation/sd/symengine_scalar_operations.h
  include/deal.II/meshworker/scratch_data.h
Labels: Documentation, ready for review

#8117 Fix a clang warning about an uninitialized read.
  source/grid/grid_in.cc
Labels: Miscellaneous, Reviewed and ready to merge, ready to test

#8120 Add documentation module for symbolic differentiation
  doc/doxygen/headers/automatic_and_symbolic_differentiation.h
Labels: Documentation, Symbolic differentiation, ready for review

#8121 Super small doc fixes for SD math functions
  include/deal.II/differentiation/sd/symengine_math.h
Labels: Documentation, Reviewed and ready to merge, Symbolic differentiation

#8033 SD scalar and tensor operations: Substitution and evaluation
  doc/news/changes/minor/20190507Jean-PaulPelteret
  include/deal.II/differentiation/sd/symengine_scalar_operations.h
  include/deal.II/differentiation/sd/symengine_tensor_operations.h
  source/differentiation/sd/symengine_scalar_operations.cc
  source/differentiation/sd/symengine_tensor_operations.cc
  tests/symengine/symengine_scalar_operations_03.cc
  tests/symengine/symengine_scalar_operations_03.output
  tests/symengine/symengine_tensor_operations_04.cc
  tests/symengine/symengine_tensor_operations_04.output
Labels: Reviewed and ready to merge, Symbolic differentiation, ready for review, ready to test

#8124 Fix codespell findings
  doc/news/8.4.2-vs-8.5.0.h
  examples/step-62/step-62.cc
  include/deal.II/differentiation/sd/symengine_math.h
  include/deal.II/meshworker/scratch_data.h
  include/deal.II/opencascade/manifold_lib.h
  source/algorithms/timestep_control.cc
  source/differentiation/sd/symengine_scalar_operations.cc
  source/distributed/tria.cc
  source/particles/particle_handler.cc
  tests/fe/fe_enriched_color_07.cc
  tests/hp/crash_21.cc
Labels: Reviewed and ready to merge, ready to test

#8012 Step-64 : matrix-free CUDA
  doc/doxygen/scripts/make_step.pl
  doc/doxygen/scripts/program2doxygen
  doc/doxygen/tutorial/CMakeLists.txt
  doc/news/changes/major/20190510ArndtTurcksin
  examples/CMakeLists.txt
  examples/step-64/CMakeLists.txt
  examples/step-64/doc/builds-on
  examples/step-64/doc/intro.dox
  examples/step-64/doc/kind
  examples/step-64/doc/results.dox
  examples/step-64/doc/tooltip
  examples/step-64/step-64.cu
  include/deal.II/lac/vector_operations_internal.h
Labels: GPU, Tutorials, ready to test

#8123 Use 'Tensor objects' instead of 'Tensors'.
  include/deal.II/base/quadrature_point_data.h
  include/deal.II/base/symmetric_tensor.h
Labels: Documentation

#8129 Provide a much nicer way to format a table in step-56.
  examples/step-56/doc/results.dox
Labels: Documentation, Reviewed and ready to merge, Tutorials

#8130 Fix the two comments from #8127.
  include/deal.II/base/linear_index_iterator.h
  include/deal.II/optimization/rol/vector_adaptor.h
Labels: Documentation, Reviewed and ready to merge

#8138 Update Trilinos version.
  doc/external-libs/trilinos.html
Labels: ready for review

#8128 Disable intrinsics includes if DEAL_II_VECTORIZATION_LEVEL=0
  cmake/checks/check_01_cpu_features.cmake
  include/deal.II/base/config.h.in
  include/deal.II/base/vectorization.h
Labels: SIMD, ready to test

#8141 cppcheck: avoid an unused variable
  source/base/table_handler.cc
Labels: Reviewed and ready to merge, ready to test

#8145 Warn about using CUDA+Threads+march=native
  doc/external-libs/cuda.html
Labels: Reviewed and ready to merge

#8139 Ignore -Wdeprecated-copy in external headers
  include/deal.II/base/config.h.in
  include/deal.II/base/graph_coloring.h
  include/deal.II/base/patterns.h
  include/deal.II/base/point.h
  include/deal.II/base/thread_local_storage.h
  include/deal.II/base/thread_management.h
  include/deal.II/base/utilities.h
  include/deal.II/matrix_free/matrix_free.templates.h
Labels: Compiler, External libraries, Reviewed and ready to merge, ready to test

#8149 Add a changelog entry for 6774.
  doc/news/changes/major/20180704DavidWells
  doc/news/changes/major/20190510DavidWells
  doc/news/changes/major/20190513Many
Labels: ready for review

#8142 Cppcheck 9.1
  include/deal.II/base/aligned_vector.h
  include/deal.II/lac/sparse_matrix.templates.h
  include/deal.II/lac/sparsity_pattern.h
  include/deal.II/lac/trilinos_vector.h
  source/base/hdf5.cc
  source/lac/sparsity_pattern.cc
  source/lac/sparsity_tools.cc
  source/lac/trilinos_solver.cc
  source/lac/trilinos_sparse_matrix.cc
  source/lac/trilinos_vector.cc
Labels: Reviewed and ready to merge, ready to test

#8147 Make two tests more stable
  tests/grid/extrude_copy_manifold.cc
  tests/grid/extrude_copy_manifold.output
  tests/trilinos/precondition.output
Labels: Reviewed and ready to merge, Tests, ready to test

#8148 Disable floating point exceptions in two HDF5 tests.
  tests/base/hdf5_03.cc
  tests/base/hdf5_05.cc
Labels: Reviewed and ready to merge, Tests, ready to test

#8155 improve tutorial layouts
  examples/step-16/step-16.cc
  examples/step-20/doc/results.dox
  examples/step-3/doc/results.dox
  examples/step-31/doc/intro.dox
  examples/step-31/doc/results.dox
  examples/step-32/doc/intro.dox
  examples/step-32/doc/results.dox
  examples/step-45/doc/intro.dox
  examples/step-53/doc/intro.dox
  examples/step-56/doc/intro.dox
  examples/step-56/step-56.cc
  examples/step-59/doc/results.dox
Labels: Documentation

#8140 cppcheck: Fix include/deal.II/algorithms/general_data_storage.h
  include/deal.II/algorithms/general_data_storage.h
Labels: Reviewed and ready to merge, ready to test

#8135 gcc9 warning: Provide copy constructor for class with operator=
  examples/step-32/step-32.cc
  include/deal.II/lac/petsc_vector.h
  source/lac/petsc_parallel_vector.cc
Labels: Compiler, Reviewed and ready to merge, ready to test

#8151 Avoid ICC-19 warning
  examples/step-61/step-61.cc
Labels: Reviewed and ready to merge, ready to test

#8154 deuglify step-42
  examples/step-42/step-42.cc
Labels: Reviewed and ready to merge, ready to test

#8157 Fix some typos in results of step-59
  examples/step-59/doc/results.dox
Labels: Documentation

#8160 Band-aid for a failing AD test
  tests/ad_common_tests/helper_scalar_coupled_4_components_01.h
Labels: Automatic differentiation, Reviewed and ready to merge, Tests, but definitely not our fault :rage:

#8159 Correct memory access in grid_tools_guess_pt_owner_02
  tests/grid/grid_tools_guess_pt_owner_02.cc
  tests/grid/grid_tools_guess_pt_owner_02.output
Labels: Tests, ready to test

#8158 Adapt test file for Trilinos IC precondition
  tests/trilinos/precondition.cc
  tests/trilinos/precondition.output
Labels: Tests

#8173 Fix general_data_storage test
  include/deal.II/algorithms/general_data_storage.h
  tests/algorithms/general_data_storage_01.output
  tests/algorithms/general_data_storage_01.output.2
  tests/algorithms/general_data_storage_01.release.output
Labels: ready to test

#8079 Step-63 Documentation
  doc/doxygen/tutorial/tutorial.h.in
  doc/news/changes/major/20190510Clevenger
  examples/step-63/block_jacobi.prm
  examples/step-63/block_sor.prm
  examples/step-63/doc/intro.dox
  examples/step-63/doc/kind
  examples/step-63/doc/results.dox
  examples/step-63/jacobi.prm
  examples/step-63/sor.prm
  examples/step-63/step-63.cc
Labels: Tutorials, ready to test

#8195 Fix documentation in ScratchData
  include/deal.II/meshworker/scratch_data.h
Labels: Documentation

#8201 clang-format: do not break @name lines
  .clang-format
  include/deal.II/meshworker/scratch_data.h
Labels: Documentation

#8202 fix doxygen @name tags
  include/deal.II/base/point.h
  include/deal.II/dofs/dof_tools.h
  include/deal.II/fe/fe_values.h
  include/deal.II/grid/grid_generator.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/tria_iterator.h
  include/deal.II/lac/sparsity_pattern.h
  include/deal.II/lac/tridiagonal_matrix.h
  include/deal.II/lac/trilinos_sparsity_pattern.h
  include/deal.II/matrix_free/matrix_free.h
Labels: Documentation

#8205 Remove doxygen format from a comment block
  include/deal.II/differentiation/sd/symengine_math.h
Labels: Documentation

#8200 CMake: Add a safeguard that disables ADOL-C in case SEACASChaco is enabled
  cmake/configure/configure_adolc.cmake
Labels: Build system

#8191 Make TransfiniteInterpolationManifold more robust
  doc/news/changes/minor/20190516MartinKronbichler
  source/grid/manifold_lib.cc
  tests/manifold/transfinite_manifold_08.cc
  tests/manifold/transfinite_manifold_08.output
  tests/manifold/transfinite_manifold_09.cc
  tests/manifold/transfinite_manifold_09.output
  tests/manifold/transfinite_manifold_10.cc
  tests/manifold/transfinite_manifold_10.output
Labels: Manifold, ready to test

#8212 doxygen: use coloneq in tutorials
  examples/step-61/doc/intro.dox
  examples/step-63/doc/intro.dox
Labels: Documentation

#8189 Updated boost::unordered_map/set to std library
  include/deal.II/base/graph_coloring.h
Labels: C++11, Enhancement, ready to test

#8204 Minor updates to the AD page.
  doc/doxygen/headers/automatic_and_symbolic_differentiation.h
Labels: Documentation

#8234 clarify a comment
  source/numerics/data_out.cc
Labels: Documentation

#8246 Change CUDAWrappers::MatrixFree::point_type to Point
  examples/step-64/step-64.cu
  include/deal.II/matrix_free/cuda_matrix_free.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
Labels: Reviewed and ready to merge, ready to test

#8237 Update the introduction to step-64.
  examples/step-64/doc/builds-on
  examples/step-64/doc/intro.dox
Labels: Tutorials

#8242 Rework the first part of step-64.
  examples/step-64/step-64.cu
Labels: Reviewed and ready to merge, Tutorials, ready to test

#8230 Disable two ADOL-C tests in release configuration
  tests/adolc/helper_scalar_failure_04.debug.output
  tests/adolc/helper_tape_index_01.debug.output
Labels: ready for review, ready to test

#8256 Update 9.1 changes
  doc/news/9.0.1-vs-9.1.0.h
Labels: Documentation, Release

#8259 [9.1] Take over #8256
  doc/news/9.0.1-vs-9.1.0.h
Labels: Documentation, Release

#8257 Add two brief class descriptions.
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/particles/particle_accessor.h
Labels: Documentation

#8258 [9.1] Take over #8257
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/particles/particle_accessor.h
Labels: Documentation, Release

#8260 [9.1] Cleanup documentation: find_common_subspace()
  include/deal.II/hp/dof_handler.h
  source/fe/fe_enriched.cc
  source/hp/dof_handler.cc
Labels: Documentation

#8265 Allow for gmsh mesh format 4.1
  doc/news/9.0.1-vs-9.1.0.h
  source/grid/grid_in.cc
  tests/gmsh/create_tria_01.output.gmsh-4.3
Labels: Reviewed and ready to merge, ready to test

#8279 Fix GridIn::read_msh
  source/grid/grid_in.cc
Labels: Reviewed and ready to merge, ready to test
