Repository dealii/dealii, pull requests merged in 2019-06, with the labels that each got.

#8277 Fix compressing TrilinosWrappers::SparsityPattern with empty column map
  doc/news/changes/minor/20190522ArndtAnselmann
  source/lac/trilinos_sparsity_pattern.cc
  tests/trilinos/sparsity_pattern_07.cc
  tests/trilinos/sparsity_pattern_07.mpirun=1.output
  tests/trilinos/sparsity_pattern_07.mpirun=2.output
Labels: ready to test

#8294 Add InterpolatedUniformGridData::gradient().
  doc/news/changes/minor/20180528_BobMyhill
  include/deal.II/base/function_lib.h
  source/base/function_lib.cc
  tests/base/functions_11_gradient.cc
  tests/base/functions_11_gradient.output
Labels: Infrastructure, Reviewed and ready to merge, ready to test

#8301 Fix typo in link for the step-17 introduction
  examples/step-17/doc/intro.dox
Labels: Documentation, Tutorials

#8197 Improve GridGenerator::torus, volume case (dim=3)
  doc/doxygen/images/torus_manifold_ids.png
  doc/news/changes/minor/20190516NiklasFehnMartinKronbichler
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  tests/grid/torus_01.cc
  tests/grid/torus_01.output
Labels: Manifold, Triangulation, ready to test

#8304 Apply FEDomination algorithm on non-distributed SolutionTransfer.
  source/numerics/solution_transfer.cc
Labels: hp, ready to test

#8310 Use std::shuffle
  examples/step-63/step-63.cc
Labels: Tutorials, ready to test

#8311 Avoid unused variable in dof_handler_policy.cc
  doc/news/changes/incompatibilities/20190603MartinKronbichler
  source/dofs/dof_handler_policy.cc
Labels: Parallel distributed, ready to test

#8315 Fix typo and language inaccuracy in 9.1 changelog
  doc/news/9.0.1-vs-9.1.0.h
Labels: Documentation

#8308 Correct reading in MPIEXEC_PREFLAGS containing spaces
  cmake/configure/configure_1_mpi.cmake
Labels: Build system, Reviewed and ready to merge, Tests, ready to test

#8318 Remove deprecated tria_boundary*.h
  doc/news/changes/incompatibilities/20190613MartinKronbichler
  include/deal.II/grid/tria_boundary.h
  include/deal.II/grid/tria_boundary_lib.h
  tests/ad_common_tests/step-44-helper_scalar_01.h
  tests/ad_common_tests/step-44-helper_vector_01.h
  tests/adolc/step-44.cc
Labels: Manifold, Reviewed and ready to merge, ready to test

#8144 update python tools scripts
  contrib/utilities/checkdoxygen.py
  contrib/utilities/wrapcomments.py
Labels: Infrastructure

#8305 Unify coarsening properties for cell characteristics.
  doc/news/changes/incompatibilities/20190606Fehling
  include/deal.II/distributed/solution_transfer.h
  include/deal.II/hp/dof_handler.h
  include/deal.II/numerics/solution_transfer.h
  source/distributed/cell_weights.cc
  source/distributed/solution_transfer.cc
  source/dofs/dof_tools_constraints.cc
  source/hp/dof_handler.cc
  tests/hp/refinement_01.output
  tests/mpi/hp_active_fe_indices_transfer_01.with_p4est=true.mpirun=2.output
  tests/mpi/hp_active_fe_indices_transfer_01.with_p4est=true.mpirun=8.output
  tests/mpi/hp_refinement_01.with_mpi=true.with_trilinos=true.with_trilinos_with_zoltan=true.mpirun=2.output
  tests/mpi/hp_refinement_02.with_mpi=true.with_trilinos=true.with_trilinos_with_zoltan=true.mpirun=2.output
Labels: Parallel distributed, ready to test

#8320 Fix compilation on MSVS 2017
  include/deal.II/fe/fe_values.h
Labels: Reviewed and ready to merge, Windows, ready to test

#8058 Step-65: Handling expensive manifolds
  doc/doxygen/images/circular_mesh_boundary_cells.png
  doc/doxygen/images/torus_cylindrical_inner_manifold.png
  doc/doxygen/images/torus_no_inner_manifold.png
  doc/doxygen/images/torus_transfinite_manifold.png
  doc/doxygen/tutorial/tutorial.h.in
  doc/news/changes/major/20190606MartinKronbichler
  doc/news/changes/minor/20190606MartinKronbichler
  examples/step-65/CMakeLists.txt
  examples/step-65/doc/builds-on
  examples/step-65/doc/intro.dox
  examples/step-65/doc/kind
  examples/step-65/doc/results.dox
  examples/step-65/doc/tooltip
  examples/step-65/step-65.cc
  include/deal.II/fe/mapping_q_cache.h
  include/deal.II/fe/mapping_q_generic.h
  source/fe/CMakeLists.txt
  source/fe/mapping_q_cache.cc
  source/fe/mapping_q_cache.inst.in
  tests/mappings/mapping_q_cache_01.cc
  tests/mappings/mapping_q_cache_01.output
  tests/mappings/mapping_q_cache_02.cc
  tests/mappings/mapping_q_cache_02.with_p4est=true.with_mpi=true.mpirun=2.output
  tests/mappings/mapping_q_cache_03.cc
  tests/mappings/mapping_q_cache_03.output
Labels: Manifold, Mapping, Reviewed and ready to merge, Tutorials, ready to test

#8324 Remove unused variables in the SymmetricTensor headers
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/base/symmetric_tensor.templates.h
Labels: Reviewed and ready to merge, ready to test

#8322 Complex project_boundary_values_curl
  doc/news/changes/minor/20190622GarciaSanchez
  include/deal.II/base/tensor.h
  include/deal.II/numerics/vector_tools.h
  include/deal.II/numerics/vector_tools.templates.h
  source/numerics/vector_tools_boundary.inst.in
  tests/numerics/project_bv_curl_conf_complex.cc
  tests/numerics/project_bv_curl_conf_complex.with_complex_values=on.output
  tests/tensors/tensor_complex_02.cc
  tests/tensors/tensor_complex_02.with_complex_values=on.output
Labels: ready to test

#8330 Minor changes to step-65.
  examples/step-65/step-65.cc
Labels: ready for review, ready to test

#8299 Python print
  doc/news/changes/minor/20180602BrunoTurcksin
  include/deal.II/lac/la_vector.h
  include/deal.II/lac/la_vector.templates.h
  include/deal.II/lac/sparse_matrix.h
  include/deal.II/lac/sparse_matrix.templates.h
  tests/lac/la_vector_print.cc
  tests/lac/la_vector_print.output
  tests/lac/sparse_matrix_print.cc
  tests/lac/sparse_matrix_print.output
Labels: Python, ready to test

#8328 Improve vectorized transpose with AVX-512
  doc/news/changes/minor/20190624MartinKronbichler
  include/deal.II/base/vectorization.h
Labels: SIMD, ready to test

#8332 Revert #8312: Replace boost random
  doc/news/changes/minor/20190609DanielArndt
  source/base/function_parser.cc
  source/base/utilities.cc
  source/dofs/dof_renumbering.cc
  source/grid/grid_tools.cc
  tests/base/function_parser_09.with_muparser=true.output
  tests/base/function_parser_10.with_muparser=true.output
  tests/base/generate_normal_random_number_01.with_threads=on.output
  tests/base/utilities_01.output
  tests/bits/rt_2.output
  tests/dofs/dof_renumbering_08.output
  tests/dofs/dof_renumbering_08.output.gcc-5
  tests/dofs/dof_renumbering_09.output
  tests/dofs/dof_renumbering_09.output.gcc-5
  tests/fe/fe_nedelec_sz_non_rect_2d.output
  tests/fe/fe_nedelec_sz_non_rect_face.with_umfpack=on.output
  tests/fe/nedelec_non_rect_2d.with_umfpack=on.output
  tests/fe/nedelec_non_rect_face.with_umfpack=on.output
  tests/fe/rt_normal_02.output
  tests/grid/build_triangulation_from_patch_03.output
  tests/grid/build_triangulation_from_patch_04.output
  tests/grid/distort_random.output
  tests/grid/grid_tools_cache_04.with_mpi=true.with_p4est=true.mpirun=4.output
  tests/mpi/distort_random_01.mpirun=2.output
  tests/mpi/distort_random_01.mpirun=4.output
  tests/mpi/distort_random_01.mpirun=8.output
  tests/mpi/distort_random_02.mpirun=2.output
  tests/mpi/distort_random_02.mpirun=4.output
  tests/mpi/distort_random_02.mpirun=8.output
  tests/mpi/distort_random_03.mpirun=3.output
  tests/serialization/hp_dof_handler_01.with_64bit_indices=off.output
  tests/serialization/hp_dof_handler_01.with_64bit_indices=off.output-gcc5
  tests/serialization/hp_dof_handler_01.with_64bit_indices=on.output
  tests/serialization/hp_dof_handler_01.with_64bit_indices=on.output-gcc5
Labels: ready to test

#8333 Fix three typos in documentation of PreconditionChebyshev
  include/deal.II/lac/precondition.h
Labels: Documentation

#8334 Fix a template instantiation.
  source/numerics/vector_tools_boundary.inst.in
Labels: Reviewed and ready to merge, ready to test
