Repository dealii/dealii, pull requests merged in 2019-04, with the labels that each got.

#7878 Use a range-based for loop in a couple of places.
  source/hp/dof_handler.cc
Labels: ready to test

#7875 CI: archive detailed.log
  Jenkinsfile
  contrib/ci/Jenkinsfile.osx
Labels: ready to test

#7879 several doxygen errors and warnings
  doc/doxygen/options.dox.in
  examples/step-28/step-28.cc
  examples/step-43/step-43.cc
  examples/step-57/step-57.cc
  include/deal.II/base/logstream.h
  include/deal.II/differentiation/ad/ad_helpers.h
  include/deal.II/lac/lapack_full_matrix.h
  include/deal.II/matrix_free/task_info.h
  include/deal.II/particles/particle.h
Labels: ready to test

#7881 Unify intrinsics headers
  include/deal.II/base/vectorization.h
Labels: SIMD, ready to test

#7884 set LAPACK_INCLUDE_DIRS and LAPACK_USER_INCLUDE_DIRS
  cmake/modules/FindLAPACK.cmake
Labels: ready to test

#7885 add default constructor for ArrayView and a reinit() method
  doc/news/changes/minor/20190402DenisDavydov
  include/deal.II/base/array_view.h
  tests/base/array_view_14.cc
  tests/base/array_view_14.output
Labels: Reviewed and ready to merge, ready to test

#7886 Test SCALAPACK with -Werror
  tests/scalapack/scalapack_06.cc
  tests/scalapack/scalapack_06a.cc
  tests/scalapack/scalapack_06b.cc
  tests/scalapack/scalapack_06c.cc
  tests/scalapack/scalapack_12_a.cc
  tests/scalapack/scalapack_12_b.cc
  tests/scalapack/scalapack_12_c.cc
  tests/scalapack/scalapack_12_d.cc
  tests/scalapack/scalapack_13_a.cc
  tests/scalapack/scalapack_13_b.cc
  tests/scalapack/scalapack_14_a.cc
  tests/scalapack/scalapack_14_b.cc
  tests/scalapack/scalapack_15.cc
  tests/scalapack/scalapack_15_a.cc
Labels: Reviewed and ready to merge, ready to test

#7890 Fix space in error message
  include/deal.II/lac/sparse_direct.h
Labels: Reviewed and ready to merge, ready to test

#7746 More edits in the introduction of step-61.
  examples/step-61/doc/intro.dox
Labels: Tutorials

#7893 Fix a misspelled word.
  include/deal.II/multigrid/mg_matrix.h
Labels: ready to test

#7889 fix hdf5 in serial
  source/base/hdf5.cc
Labels: ready to test

#7844 SD: Types, traits, and expression class
  doc/news/changes/major/20190329Jean-PaulPelteret
  include/deal.II/base/config.h.in
  include/deal.II/differentiation/sd.h
  include/deal.II/differentiation/sd/symengine_number_traits.h
  include/deal.II/differentiation/sd/symengine_number_types.h
  include/deal.II/differentiation/sd/symengine_types.h
  include/deal.II/differentiation/sd/symengine_utilities.h
  source/differentiation/CMakeLists.txt
  source/differentiation/sd/CMakeLists.txt
  source/differentiation/sd/symengine_number_types.cc
  source/differentiation/sd/symengine_types.cc
  source/differentiation/sd/symengine_utilities.cc
  tests/symengine/symengine_number_type_01.cc
  tests/symengine/symengine_number_type_01.output
Labels: Symbolic differentiation, ready for review, ready to test

#7894 Silence an unused variable warning.
  source/base/hdf5.cc
Labels: Miscellaneous, ready to test

#7896 Require SymEngine version 0.4
  cmake/configure/configure_symengine.cmake
  cmake/modules/FindSYMENGINE.cmake
Labels: ready to test

#7897 MPI quicktests failing
  tests/quick_tests/CMakeLists.txt
Labels: Reviewed and ready to merge, ready to test

#7880 Add a class to perform GeneralDataStorage
  doc/news/changes/minor/20190402LucaHeltaiJean-PaulPelteret
  include/deal.II/algorithms/general_data_storage.h
  source/algorithms/CMakeLists.txt
  source/algorithms/general_data_storage.cc
  tests/algorithms/general_data_storage_01.cc
  tests/algorithms/general_data_storage_01.debug.output
  tests/algorithms/general_data_storage_01.debug.output.2
  tests/algorithms/general_data_storage_01.release.output
Labels: Enhancement, ready to test

#7898 [CI]: catch failures and run quicktests
  Jenkinsfile
  contrib/ci/Jenkinsfile.osx
Labels: ready to test

#7906 Fixed documentation error in filtered_iterator.h
  include/deal.II/grid/filtered_iterator.h
Labels: Documentation

#7806 "Reasonable" ScratchData and CopyData
  doc/news/changes/minor/20190313LucaHeltai
  include/deal.II/meshworker/copy_data.h
  include/deal.II/meshworker/scratch_data.h
  source/meshworker/CMakeLists.txt
  source/meshworker/scratch_data.cc
  source/meshworker/scratch_data.inst.in
  tests/meshworker/scratch_data_01.cc
  tests/meshworker/scratch_data_01.output
  tests/meshworker/scratch_data_02.cc
  tests/meshworker/scratch_data_02.with_muparser=on.with_umfpack=on.output
  tests/meshworker/scratch_data_03.cc
  tests/meshworker/scratch_data_03.with_muparser=on.with_umfpack=on.output
  tests/meshworker/scratch_data_04.cc
  tests/meshworker/scratch_data_04.with_muparser=on.output
  tests/meshworker/scratch_data_05.cc
  tests/meshworker/scratch_data_05.with_trilinos=on.with_muparser=on.with_umfpack=on.output
  tests/meshworker/scratch_data_06.cc
  tests/meshworker/scratch_data_06.with_trilinos=on.with_muparser=on.with_umfpack=on.output
  tests/meshworker/scratch_data_07.cc
  tests/meshworker/scratch_data_07.with_trilinos=on.with_muparser=on.with_umfpack=on.output
Labels: Parallel shared, ready for review, ready to test

#7910 Replace std::make_unique by std_cxx14::make_unique
  source/meshworker/scratch_data.cc
Labels: Reviewed and ready to merge, ready to test

#7901 Use std::string in SmartPointer and Subscriptor interface
  doc/news/changes/minor/20190408Arndt
  include/deal.II/base/smartpointer.h
  include/deal.II/base/subscriptor.h
  include/deal.II/lac/block_matrix_array.h
  include/deal.II/lac/swappable_vector.templates.h
  source/base/data_out_base.cc
  source/base/exceptions.cc
  source/base/parameter_acceptor.cc
  source/base/parameter_handler.cc
  source/base/path_search.cc
  source/base/subscriptor.cc
  source/base/table_handler.cc
  source/base/timer.cc
  source/gmsh/utilities.cc
  source/grid/grid_in.cc
  tests/base/unsubscribe_subscriptor.debug.output
  tests/base/unsubscribe_subscriptor.debug.output.clang-6
  tests/base/unsubscribe_subscriptor.debug.output.intel
Labels: Reviewed and ready to merge, ready to test

#7916 clang-tidy: only debug mode
  contrib/utilities/run_clang_tidy.sh
Labels: Reviewed and ready to merge, ready to test

#7876 SD: Logical operators + math operations for expression class
  doc/news/changes/minor/20190330Jean-PaulPelteret
  include/deal.II/differentiation/sd.h
  include/deal.II/differentiation/sd/symengine_math.h
  source/differentiation/sd/CMakeLists.txt
  source/differentiation/sd/symengine_math.cc
  tests/symengine/symengine_number_type_02.cc
  tests/symengine/symengine_number_type_02.output
Labels: Reviewed and ready to merge, Symbolic differentiation, ready for review, ready to test

#7919 Add missing '@ingroup functions' annotations.
  include/deal.II/base/function.h
  include/deal.II/base/function_bessel.h
  include/deal.II/base/function_cspline.h
  include/deal.II/base/function_lib.h
  include/deal.II/base/function_spherical.h
Labels: Documentation

#7917 Avoid floating point exception in symengine_number_type_01
  tests/symengine/symengine_number_type_01.cc
Labels: ready to test

#7924 Update requirements for step-61.
  examples/step-61/CMakeLists.txt
Labels: Reviewed and ready to merge

#7925 Fix symengine_number_type_01 in Release mode
  tests/symengine/symengine_number_type_01.cc
Labels: ready to test

#7923 Enclose everything in step-61 into its own namespace.
  examples/step-61/step-61.cc
Labels: ready to test

#7927 Cuda: small fixes
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  source/lac/read_write_vector.cc
Labels: GPU, ready to test

#7915 Make sure rtree works with mappings that do not preserve vertices.
  doc/news/changes/minor/20190411LucaHeltai-c
  source/grid/grid_tools_cache.cc
  tests/grid/grid_tools_cache_05.cc
  tests/grid/grid_tools_cache_05.output
Labels: ready for review, ready to test

#7914 BoundingBox::extend()
  doc/news/changes/minor/20190411LucaHeltai-b
  include/deal.II/base/bounding_box.h
  tests/base/bounding_box_5.cc
  tests/base/bounding_box_5.output
Labels: ready for review, ready to test

#7935 Fix configuring with external Boost-1.70.0
  cmake/modules/FindBOOST.cmake
Labels: Reviewed and ready to merge, ready to test

#7938 CMake: Clear CMAKE_REQUIRED_FLAGS before calling FindLAPACK
  cmake/configure/configure_1_lapack.cmake
Labels: Reviewed and ready to merge, ready to test

#7945 Clarify a piece of documentation.
  include/deal.II/numerics/error_estimator.h
Labels: Documentation

#7936 add explicit instantiations for shared::Triangulation
  source/grid/grid_tools_dof_handlers.inst.in
Labels: Reviewed and ready to merge, ready to test

#7926 SparsityPattern: Fix copy_from a DynamicSparsityPattern
  source/lac/dynamic_sparsity_pattern.cc
  source/lac/sparsity_pattern.cc
  tests/sparsity/dynamic_sparsity_pattern_21.cc
  tests/sparsity/dynamic_sparsity_pattern_21.output
Labels: ready for review, ready to test

#7947 Fix documentation of extend + spelling.
  include/deal.II/base/bounding_box.h
Labels: Documentation, Reviewed and ready to merge, ready to test

#7948 Fix SymEngine test
  include/deal.II/differentiation/sd/symengine_utilities.h
Labels: ready to test

#7944 SD tensor operations: Add functions to perform symbolic tensor differentation
  doc/news/changes/minor/20190422Jean-PaulPelteret
  doc/news/changes/minor/20190423Jean-PaulPelteret
  include/deal.II/differentiation/sd/symengine_scalar_operations.h
  include/deal.II/differentiation/sd/symengine_tensor_operations.h
  tests/ad_common_tests/helper_scalar_coupled_4_components_01.h
  tests/adolc/helper_scalar_coupled_4_components_01_1.cc
  tests/adolc/helper_scalar_coupled_4_components_01_1.output
  tests/adolc/helper_scalar_coupled_4_components_01_2.cc
  tests/adolc/helper_scalar_coupled_4_components_01_2.output
  tests/sacado/helper_scalar_coupled_4_components_01_1.cc
  tests/sacado/helper_scalar_coupled_4_components_01_1.output
  tests/sacado/helper_scalar_coupled_4_components_01_2.cc
  tests/sacado/helper_scalar_coupled_4_components_01_2.output
  tests/sacado/helper_scalar_coupled_4_components_01_3.cc
  tests/sacado/helper_scalar_coupled_4_components_01_3.output
  tests/sacado/helper_scalar_coupled_4_components_01_4.cc
  tests/sacado/helper_scalar_coupled_4_components_01_4.output
  tests/symengine/symengine_tensor_operations_03.cc
  tests/symengine/symengine_tensor_operations_03.output
Labels: Symbolic differentiation, ready to test

#7955 Reduce chunk_size used in CUDA kernels from 8 to 1
  doc/news/changes/minor/20190423BrunoTurcksin
  include/deal.II/base/cuda_size.h
Labels: GPU

#7956 step-40 disable logic with complex PETSc
  examples/step-40/CMakeLists.txt
  examples/step-40/step-40.cc
Labels: Reviewed and ready to merge, ready to test

#7932 Enrich CutOffFunctionBase, and provide also CutOffFunctionC1
  doc/news/changes/minor/20190418LucaHeltai
  include/deal.II/base/function_lib.h
  source/base/function_lib_cutoff.cc
  tests/base/function_cutoff_01.cc
  tests/base/function_cutoff_01.output
  tests/base/function_cutoff_02.cc
  tests/base/function_cutoff_02.output
Labels: ready for review, ready to test

#7918 FunctionFromFunctionObjects class: wraps a vector of std::function objects into a Function object
  doc/news/changes/minor/20190412LucaHeltai
  include/deal.II/base/function.h
  include/deal.II/base/function.templates.h
  source/base/function.inst.in
  tests/base/function_from_function_objects_01.cc
  tests/base/function_from_function_objects_01.output
Labels: ready for review, ready to test

#7959 Documentation fix Physics::Transformations::Rotations::rotation_matrix_2d
  include/deal.II/physics/transformations.h
Labels: Documentation

#7960 Fix a mistaken assertion that only succeeds by accident.
  examples/step-18/step-18.cc
Labels: Reviewed and ready to merge, ready to test

#7965 Exchange vectors of std::vector::swap() in step-18
  examples/step-18/step-18.cc
Labels: Reviewed and ready to merge, ready to test

#7964 Remove destructor in step40
  examples/step-40/step-40.cc
Labels: Reviewed and ready to merge, ready to test

#7957 Mathematical notation of DerivativeForm
  include/deal.II/base/derivative_form.h
Labels: Reviewed and ready to merge, ready to test

#7958 Augment documentation in class IteratorRange.
  include/deal.II/base/iterator_range.h
Labels: Documentation

#7972 Use the function n_locally_owned_active_cells() in step-18
  examples/step-18/step-18.cc
Labels: Reviewed and ready to merge, ready to test

#7969 Use integers in cudaMemset
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/lac/vector_operations_internal.h
  source/lac/cuda_vector.cu
Labels: GPU, Reviewed and ready to merge, ready to test

#7975 Improve the documentation of parallel builds.
  doc/readme.html
Labels: Documentation

#7961 SD scalar operations: Addition to substitution maps and map merging
  include/deal.II/differentiation/sd/symengine_scalar_operations.h
  source/differentiation/sd/symengine_scalar_operations.cc
  tests/symengine/substitution_maps_scalar_01.cc
  tests/symengine/substitution_maps_scalar_01.output
  tests/symengine/substitution_maps_scalar_02.cc
  tests/symengine/substitution_maps_scalar_02.output
Labels: Reviewed and ready to merge, Symbolic differentiation

#7968 Deal with empty ranges in CUDAWrappers::MatrixFree::internal_reinit
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  tests/cuda/matrix_free_reinit_01.cu
  tests/cuda/matrix_free_reinit_01.with_mpi=on.with_p4est=on.mpirun=2.output
Labels: GPU

#7977 Improve doxygen documentation for ReadWriteVector
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/read_write_vector.h
Labels: ready to test

#7976 Export DEAL_II_PETSC_WITH_COMPLEX variable
  include/deal.II/base/config.h.in
Labels: ready to test

#7943 Degree of quadrature based on degree of the fe-variable
  doc/news/changes/major/20190425RolandRichter
  examples/step-13/step-13.cc
  examples/step-14/step-14.cc
  examples/step-15/step-15.cc
  examples/step-16b/doc/results.dox
  examples/step-16b/step-16b.cc
  examples/step-17/step-17.cc
  examples/step-18/step-18.cc
  examples/step-23/step-23.cc
  examples/step-24/step-24.cc
  examples/step-25/step-25.cc
  examples/step-29/step-29.cc
  examples/step-3/doc/results.dox
  examples/step-3/step-3.cc
  examples/step-33/step-33.cc
  examples/step-36/step-36.cc
  examples/step-4/step-4.cc
  examples/step-40/step-40.cc
  examples/step-5/step-5.cc
  examples/step-51/step-51.cc
  examples/step-55/step-55.cc
  examples/step-6/step-6.cc
  examples/step-7/doc/results.dox
  examples/step-7/step-7.cc
  examples/step-8/step-8.cc
Labels: Enhancement, Quadrature, Reviewed and ready to merge, ready to test

#7979 Misc. typos
  contrib/utilities/generate_lapack_templates
  contrib/utilities/indent
  contrib/utilities/indent.py
  doc/doxygen/headers/automatic_and_symbolic_differentiation.h
  doc/doxygen/headers/manifold.h
  doc/news/changes/minor/20181006LucaHeltai
  examples/step-44/step-44.cc
  examples/step-53/doc/intro.dox
  examples/step-61/doc/intro.dox
  examples/step-61/doc/results.dox
  examples/step-7/step-7.cc
  include/deal.II/algorithms/general_data_storage.h
  include/deal.II/base/function_lib.h
  include/deal.II/base/hdf5.h
  include/deal.II/base/symmetric_tensor.templates.h
  include/deal.II/differentiation/ad/ad_drivers.h
  include/deal.II/differentiation/ad/ad_helpers.h
  include/deal.II/differentiation/sd/symengine_number_types.h
  include/deal.II/differentiation/sd/symengine_scalar_operations.h
  include/deal.II/differentiation/sd/symengine_tensor_operations.h
  include/deal.II/differentiation/sd/symengine_utilities.h
  include/deal.II/dofs/dof_objects.h
  include/deal.II/dofs/dof_tools.h
  include/deal.II/fe/fe_tools.templates.h
  include/deal.II/grid/manifold_lib.h
  include/deal.II/hp/fe_collection.h
  include/deal.II/integrators/advection.h
  include/deal.II/lac/affine_constraints.h
  include/deal.II/lac/cuda_solver_direct.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  include/deal.II/matrix_free/cuda_hanging_nodes_internal.h
  include/deal.II/meshworker/scratch_data.h
  source/differentiation/ad/ad_drivers.cc
  source/fe/fe_enriched.cc
  source/grid/grid_tools.cc
  source/lac/cuda_sparse_matrix.cu
  source/non_matching/coupling.cc
  tests/base/assign_subscriptor.cc
  tests/base/assign_subscriptor.debug.output
  tests/base/hdf5_03.cc
  tests/base/hdf5_04.cc
  tests/base/hdf5_05.cc
  tests/base/hdf5_06.cc
  tests/cuda/array_view_wrong_memory.cu
  tests/grid/grid_in_ucd_01.cc
  tests/lac/linear_operator_13.cc
  tests/lac/linear_operator_14.cc
  tests/manifold/tensor_product_manifold_03.cc
  tests/mpi/hp_refinement_02.cc
  tests/mpi/p4est_3d_refine_01.cc
  tests/optimization/step-44.h
  tests/petsc/full_matrix_00.cc
  tests/tests.h
Labels: Documentation, Reviewed and ready to merge, ready to test

#7967 Deal with empty empty sizes in CUDA kernels
  include/deal.II/base/partitioner.templates.h
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/lac/vector_operations_internal.h
Labels: GPU

#7981 Restrict SymEngine test
  tests/symengine/substitution_maps_scalar_01.cc
  tests/symengine/substitution_maps_scalar_02.cc
Labels: Reviewed and ready to merge, ready to test
