Repository dealii/dealii, pull requests merged in 2019-07, with the labels that each got.

#8336 Add a couple of comments to functions in utilities.cc.
  source/base/utilities.cc
Labels: ready for review, ready to test

#8339 Fix a bug in print_as_numpy_arrays
  include/deal.II/lac/sparse_matrix.templates.h
  tests/lac/sparse_matrix_print.cc
  tests/lac/sparse_matrix_print.output
Labels: Reviewed and ready to merge, ready to test

#8340 Fix include to intrinsics
  cmake/checks/check_02_compiler_features.cmake
Labels: Build system, ready to test

#8343 Fix compilation of loop.h with some versions of clang.
  include/deal.II/meshworker/loop.h
Labels: Reviewed and ready to merge, ready for review, ready to test

#8344 CMake: Update CTest configuration
  CTestConfig.cmake
  tests/run_testsuite.cmake
Labels: Build system, High Priority :warning:, Infrastructure

#8350 Remove int2type and bool2type.
  include/deal.II/base/template_constraints.h
Labels: Miscellaneous, ready to test

#8337 Fix a bug in CUDA matrix-free with adapted mesh when using Volta
  doc/news/changes/minor/20190602BrunoTurcksin
  doc/news/changes/minor/20190702BrunoTurcksin
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  include/deal.II/matrix_free/cuda_hanging_nodes_internal.h
Labels: GPU

#8325 Introduced hp::Refinement namespace.
  doc/news/changes/minor/20190607Fehling
  include/deal.II/hp/refinement.h
  source/hp/CMakeLists.txt
  source/hp/refinement.cc
  source/hp/refinement.inst.in
  tests/hp/hp_coarsening.cc
  tests/hp/hp_coarsening.output
  tests/hp/p_adaptivity_flags.cc
  tests/hp/p_adaptivity_flags.output
Labels: hp, ready to test

#8356 std::strings stores the filename, not the file handler
  examples/step-29/step-29.cc
  examples/step-29/step-29.prm
Labels: Reviewed and ready to merge, ready to test

#8355 Fix documentation of HermiteLikeInterpolation
  include/deal.II/base/polynomial.h
Labels: Documentation

#8300 Mpi compute index owner
  doc/news/changes/minor/20190603PeterMunch
  doc/news/changes/minor/20190603PeterMunch-1
  include/deal.II/base/mpi.h
  source/base/mpi.cc
  source/base/partitioner.cc
  source/multigrid/mg_transfer_internal.cc
  tests/multigrid/transfer_matrix_free_06.with_mpi=true.with_p4est=true.with_trilinos=true.mpirun=15.output
Labels: Parallel distributed, ready to test

#8346 Annotate Point members usable in CUDA kernels
  doc/news/changes/minor/20190705DanielArndt
  include/deal.II/base/point.h
  tests/cuda/cuda_point.cu
  tests/cuda/cuda_point.output
Labels: GPU

#8064 Constexpr Tensor
  cmake/checks/check_01_cxx_features.cmake
  doc/news/changes/minor/20190526RezaRastak
  include/deal.II/base/config.h.in
  include/deal.II/base/tensor.h
  include/deal.II/base/tensor_accessors.h
  source/base/vectorization.cc
  tests/base/vectorization_07.cc
  tests/base/vectorization_07.output
  tests/tensors/constexpr_tensor.cc
  tests/tensors/constexpr_tensor.output
Labels: C++11, Reviewed and ready to merge, Tensors, ready to test

#8357 Always test the layout of the VectorizedArray class
  source/base/vectorization.cc
Labels: ready to test

#8341 hp::Refinement: Error prediction.
  include/deal.II/hp/refinement.h
  source/hp/refinement.cc
  source/hp/refinement.inst.in
  tests/hp/error_prediction.cc
  tests/hp/error_prediction.output
Labels: hp, ready to test

#8360 fixed misrepresentation of "*" in documentation of tutorials
  examples/step-18/doc/intro.dox
  examples/step-20/doc/intro.dox
Labels: Documentation

#8342 Extend VectorizedArray with a second template argument to control vector length
  doc/news/changes/minor/20190704PeterMunch
  include/deal.II/base/memory_consumption.h
  include/deal.II/base/numbers.h
  include/deal.II/base/tensor.h
  include/deal.II/base/vectorization.h
  include/deal.II/lac/tensor_product_matrix.h
  source/base/vectorization.cc
  tests/base/vectorization_10.cc
  tests/base/vectorization_10.output
Labels: SIMD, ready to test

#8358 Remove unused code in CUDAWrappers::internal::HangingNodes
  include/deal.II/matrix_free/cuda_hanging_nodes_internal.h
Labels: GPU, Reviewed and ready to merge, ready to test

#8361 Fix refinement.h include
  include/deal.II/hp/refinement.h
Labels: Reviewed and ready to merge, ready to test

#8362 Fix a few gcc-9 warninigs in tests
  tests/mpi/periodicity_06.cc
  tests/mpi/periodicity_07.cc
Labels: Tests

#8338 CUDA device annotations for Tensor
  doc/news/changes/minor/20190703DanielArndt
  include/deal.II/base/tensor.h
  tests/cuda/cuda_tensor_01.cu
  tests/cuda/cuda_tensor_01.output
  tests/cuda/cuda_tensor_02.cu
  tests/cuda/cuda_tensor_02.output
Labels: GPU, ready to test

#8368 fix compile error typo in intel ifdef
  include/deal.II/base/tensor.h
Labels: Reviewed and ready to merge

#8307 Elementwise multiplication for Tensor<rank, dim>
  doc/news/changes/minor/20190610RolandRichter
  include/deal.II/base/tensor.h
  tests/tensors/tensor_10.cc
  tests/tensors/tensor_10.output
Labels: Tensors, ready to test

#8373 Fix VectorizedArray::vectorized_load_and_transpose specialization
  include/deal.II/base/vectorization.h
Labels: SIMD

#8363 Implement CUDAWrappers::FEEvaluation::get_dof_values/submit_dof_values
  doc/news/changes/minor/20190709DanielArndt
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  tests/cuda/matrix_free_no_index_initialize.cu
  tests/cuda/matrix_free_no_index_initialize.output
Labels: GPU, Matrix-free

#8372 Add missing epetra headers.
  include/deal.II/fe/fe_tools_interpolate.templates.h
  source/dofs/dof_accessor_get.cc
  source/dofs/dof_accessor_set.cc
  source/fe/fe_values.cc
  source/fe/mapping_fe_field.cc
  source/lac/solver.cc
  source/lac/vector_memory.cc
  source/multigrid/mg_base.cc
  source/numerics/derivative_approximation.cc
Labels: Reviewed and ready to merge, ready to test

#8375 update URLs to 43-1.org and use https instead of http
  CTestConfig.cmake
  contrib/utilities/query_testsuite
  doc/developers/testsuite.html
Labels: Documentation

#8365 Hanging nodes: Loosen assertion for artificial cells.
  source/dofs/dof_tools_constraints.cc
  tests/mpi/hp_hanging_node_constraints.cc
  tests/mpi/hp_hanging_node_constraints.with_p4est=true.mpirun=2.output
Labels: Reviewed and ready to merge, ready to test

#8370 intel: ignore simd warning
  cmake/setup_compiler_flags_intel.cmake
Labels: SIMD, ready to test

#8369 fix wrong variable assignment
  source/hp/refinement.cc
Labels: ready to test

#8379 Fix documentation of Chebyshev iteration
  include/deal.II/lac/precondition.h
Labels: Documentation

#8378 Epetra: fix SparsityPattern::compress() with 64 bit
  include/deal.II/lac/trilinos_sparse_matrix.h
  source/lac/trilinos_sparsity_pattern.cc
Labels: Reviewed and ready to merge, ready to test

#8380 Remove deprecated PreconditionChebyshev::AdditionalData members
  doc/news/changes/incompatibilities/20190711DanielArndt
  include/deal.II/lac/precondition.h
  tests/lac/precondition_chebyshev_01.cc
  tests/matrix_free/multigrid_dg_periodic.cc
  tests/matrix_free/multigrid_dg_sip_01.cc
  tests/matrix_free/multigrid_dg_sip_02.cc
  tests/matrix_free/parallel_multigrid_mf.cc
Labels: ready to test

#8352 Add functionality to support multiple mappings per element in FE_PolyTensor
  doc/news/changes/minor/20190712GrahamHarper
  include/deal.II/fe/fe_dg_vector.templates.h
  include/deal.II/fe/fe_poly_tensor.h
  source/fe/fe_abf.cc
  source/fe/fe_bdm.cc
  source/fe/fe_bernardi_raugel.cc
  source/fe/fe_dg_vector.cc
  source/fe/fe_nedelec.cc
  source/fe/fe_poly_tensor.cc
  source/fe/fe_raviart_thomas.cc
  source/fe/fe_raviart_thomas_nodal.cc
  source/fe/fe_rt_bubbles.cc
Labels: Finite Element, Mapping, ready to test

#8348 Extend MatrixFree with a second template argument to control vectorization
  doc/news/changes/minor/20190706PeterMunch
  doc/news/changes/minor/20190710PeterMunch
  include/deal.II/base/vectorization.h
  include/deal.II/matrix_free/dof_info.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/mapping_data_on_the_fly.h
  include/deal.II/matrix_free/mapping_info.h
  include/deal.II/matrix_free/mapping_info.templates.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
  include/deal.II/matrix_free/operators.h
  include/deal.II/matrix_free/shape_info.templates.h
  include/deal.II/numerics/vector_tools.h
  include/deal.II/numerics/vector_tools.templates.h
  source/matrix_free/mapping_info.cc
  source/matrix_free/mapping_info.inst.in
  source/matrix_free/matrix_free.inst.in
  source/numerics/vector_tools_project_qpmf.inst.in
  tests/matrix_free/matrix_vector_faces_26.cc
  tests/matrix_free/matrix_vector_faces_26.output
  tests/matrix_free/matrix_vector_faces_26.output.avx
  tests/matrix_free/matrix_vector_faces_26.output.avx512
  tests/matrix_free/matrix_vector_faces_26.output.sse2
  tests/matrix_free/matrix_vector_faces_common.h
Labels: Matrix-free, SIMD, ready to test

#8381 Improve hermite like interpolation
  doc/news/changes/minor/20190712MartinKronbichler
  include/deal.II/base/polynomial.h
  source/base/polynomial.cc
  tests/base/polynomial_hermite_like.output
  tests/base/polynomial_hermite_like_mass_1d.cc
  tests/base/polynomial_hermite_like_mass_1d.output
Labels: Finite Element, ready to test

#8388 fix compilation error in tensor.h
  include/deal.II/base/tensor.h
Labels: ready to test

#8390 Be more conservative in clearing the cache of MappingQCache
  source/fe/mapping_q_cache.cc
Labels: Mapping, ready to test

#8392 Test robustness: avoid points directly at the periodicity boundary
  tests/manifold/elliptical_manifold_02.cc
  tests/manifold/elliptical_manifold_02.output
Labels: Manifold, Reviewed and ready to merge, ready to test

#8393 Provide AVX-512 output for four additional tests
  tests/base/point_03.cc
  tests/data_out/data_out_base_vtu_04.with_zlib=on.output.avx512
  tests/dofs/dof_renumbering_02.output.avx512
  tests/grid/grid_generator_09.output.avx512
  tests/grid/grid_out_svg_02.output.avx512
Labels: Reviewed and ready to merge, Tests, ready to test

#8385 Constexpr SymmetricTensor and TableIndices
  doc/news/changes/minor/20190713RezaRastak
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/base/table_indices.h
  include/deal.II/physics/elasticity/standard_tensors.h
  source/physics/elasticity/standard_tensors.cc
  tests/tensors/constexpr_symmetric_tensor.cc
  tests/tensors/constexpr_symmetric_tensor.output
Labels: ready to test

#8394 Avoid initializing a numbered list in step-28 documentation
  examples/step-28/doc/intro.dox
Labels: Documentation

#8397 Add assert to Utilities::MPI::compute_index_owner
  source/base/mpi.cc
Labels: Parallel distributed, Reviewed and ready to merge, ready to test

#8398 improve CellDataStorage documentation
  include/deal.II/base/quadrature_point_data.h
Labels: Documentation

#8399 Fix EnableIfScalar for VectorizedArray
  include/deal.II/base/vectorization.h
Labels: Reviewed and ready to merge, SIMD, ready to test

#8401 Fixing the linker error of StandardTensors with clang 4.0.1
  source/physics/elasticity/standard_tensors.cc
Labels: Reviewed and ready to merge, ready to test

#8404 Fix CellDataTransfer tests for complex Petsc complex scalar type
  tests/sharedtria/cell_data_transfer_01.cc
  tests/sharedtria/cell_data_transfer_02.cc
Labels: Reviewed and ready to merge, Tests, ready to test

#8395 Implement CUDAWrappers::MatrixFree::initialize_dof_vector
  doc/news/changes/minor/20190719DanielArndt
  include/deal.II/matrix_free/cuda_matrix_free.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  tests/cuda/matrix_free_initialize_vector.cu
  tests/cuda/matrix_free_initialize_vector.with_mpi=on.with_p4est=on.mpirun=1.output
  tests/cuda/matrix_free_initialize_vector.with_mpi=on.with_p4est=on.mpirun=2.output
Labels: GPU

#8405 Fix a bug in LA::d::Vector::compress on the host
  doc/news/changes/minor/20190723BrunoTurcksin
  include/deal.II/lac/la_parallel_vector.templates.h
  tests/cuda/parallel_vector_26.cu
  tests/cuda/parallel_vector_26.mpirun=2.output
Labels: GPU, ready to test

#8408 doc: correct friend markup in tensor
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/base/tensor.h
Labels: Documentation

#8402 Choose a more appropriate tolerance for vector add_and_dot
  tests/lac/la_parallel_vector_add_and_dot_complex.cc
  tests/lac/la_vector_add_and_dot_complex.cc
  tests/lac/vector_add_and_dot_complex.cc
Labels: Tests, ready to test

#8409 doc: no doxygen for friend declarations
  include/deal.II/base/process_grid.h
  include/deal.II/base/table.h
  include/deal.II/base/vectorization.h
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/dofs/dof_handler.h
  include/deal.II/dofs/dof_objects.h
  include/deal.II/fe/fe_abf.h
  include/deal.II/fe/fe_dgp_nonparametric.h
  include/deal.II/fe/fe_dgq.h
  include/deal.II/fe/fe_nedelec.h
  include/deal.II/fe/fe_q_base.h
  include/deal.II/fe/fe_q_hierarchical.h
  include/deal.II/fe/fe_raviart_thomas.h
  include/deal.II/fe/fe_system.h
  include/deal.II/fe/fe_values.h
  include/deal.II/fe/mapping.h
  include/deal.II/fe/mapping_fe_field.h
  include/deal.II/fe/mapping_q_generic.h
  include/deal.II/grid/tria_iterator.h
  include/deal.II/hp/dof_handler.h
  include/deal.II/hp/dof_level.h
  include/deal.II/lac/block_matrix_base.h
  include/deal.II/lac/block_sparsity_pattern.h
  include/deal.II/lac/block_vector_base.h
  include/deal.II/lac/chunk_sparse_matrix.h
  include/deal.II/lac/chunk_sparsity_pattern.h
  include/deal.II/lac/dynamic_sparsity_pattern.h
  include/deal.II/lac/filtered_matrix.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/la_vector.h
  include/deal.II/lac/matrix_iterator.h
  include/deal.II/lac/petsc_matrix_base.h
  include/deal.II/lac/petsc_precondition.h
  include/deal.II/lac/petsc_solver.h
  include/deal.II/lac/petsc_sparse_matrix.h
  include/deal.II/lac/petsc_vector_base.h
  include/deal.II/lac/precondition_block.h
  include/deal.II/lac/read_write_vector.h
  include/deal.II/lac/slepc_spectral_transformation.h
  include/deal.II/lac/sparse_matrix.h
  include/deal.II/lac/sparse_matrix_ez.h
  include/deal.II/lac/sparse_vanka.h
  include/deal.II/lac/sparsity_pattern.h
  include/deal.II/lac/trilinos_sparse_matrix.h
  include/deal.II/lac/trilinos_sparsity_pattern.h
  include/deal.II/lac/trilinos_vector.h
  include/deal.II/lac/vector.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/numerics/data_out_dof_data.h
  include/deal.II/particles/particle_accessor.h
Labels: Documentation, Reviewed and ready to merge, ready to test

#8349 Add notes on packaging for distributions.
  doc/developers/packaging.html
  doc/index.html
  doc/news/changes/minor/20190707DavidWells
Labels: Documentation

#8407 Point assignment operator
  doc/news/changes/minor/20190723GarciaSanchez
  include/deal.II/base/point.h
  tests/base/point_05.cc
  tests/base/point_05.output
Labels: Reviewed and ready to merge, ready to test

#8400 Add new make_vectorized_array function
  include/deal.II/base/vectorization.h
  tests/base/vectorization_make_vectorized_array_01.cc
  tests/base/vectorization_make_vectorized_array_01.output
  tests/base/vectorization_make_vectorized_array_01.output.avx
  tests/base/vectorization_make_vectorized_array_01.output.avx512
  tests/base/vectorization_make_vectorized_array_01.output.sse2
Labels: SIMD, ready to test

#8413 Disable __builtin_expect for Intel compiler with DEAL_II_CONSTEXPR
  cmake/checks/check_02_compiler_features.cmake
Labels: Build system, ready to test

#8411 Link to more resources on learning how to program.
  examples/step-1/doc/intro.dox
Labels: Documentation

#8314 Use LaTeX bibliography in step-14
  doc/doxygen/options.dox.in
  doc/doxygen/references.bib
  examples/step-14/doc/intro.dox
Labels: Documentation

#8414 Minor clean-ups.
  include/deal.II/fe/fe_poly_tensor.h
  source/fe/fe_poly_tensor.cc
Labels: Reviewed and ready to merge, ready to test

#8412 LA::d::Vector import
  doc/news/changes/minor/20190724BrunoTurcksin
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/lac/vector_operations_internal.h
  source/lac/la_parallel_vector.cu
  source/lac/la_parallel_vector.inst.in
  tests/cuda/parallel_vector_25.cu
  tests/cuda/parallel_vector_25.mpirun=2.output
Labels: GPU, ready to test

#8420 Fix spaces in error messages
  include/deal.II/differentiation/ad/adolc_number_types.h
  include/deal.II/fe/fe_series.h
  include/deal.II/lac/chunk_sparse_matrix.h
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/matrix_free/operators.h
  source/base/partitioner.cc
  source/differentiation/ad/ad_helpers.cc
  source/distributed/shared_tria.cc
  source/distributed/solution_transfer.cc
  source/dofs/dof_tools.cc
  source/dofs/dof_tools_constraints.cc
  source/fe/fe_series_legendre.cc
  source/grid/grid_out.cc
  source/grid/grid_tools_dof_handlers.cc
  source/lac/dynamic_sparsity_pattern.cc
  source/lac/petsc_solver.cc
  source/lac/slepc_spectral_transformation.cc
  source/lac/trilinos_sparse_matrix.cc
Labels: Reviewed and ready to merge, ready to test

#8425 Add CHANGELOG.md and SUPPORT.md files.
  CHANGELOG.md
  SUPPORT.md
Labels: Documentation

#8383 Automated template instantiation for VectorizedArray
  cmake/config/template-arguments.in
  cmake/configure/configure_vectorization.cmake
  doc/news/changes/minor/20190713PeterMunch
  source/matrix_free/mapping_info.inst.in
  source/matrix_free/matrix_free.inst.in
Labels: Build system, SIMD, ready to test

#8422 Parallel distributed: Communicate active_fe_indices after refinement.
  source/hp/dof_handler.cc
Labels: Parallel distributed, Reviewed and ready to merge, hp, ready to test

#8421 New tests: Parallel distributed version of step-27.
  tests/mpi/petsc_step-27.cc
  tests/mpi/petsc_step-27.with_p4est=true.with_petsc=true.mpirun=1.output
  tests/mpi/petsc_step-27.with_p4est=true.with_petsc=true.mpirun=2.output
  tests/mpi/trilinos_step-27.cc
  tests/mpi/trilinos_step-27.with_p4est=true.with_trilinos=true.mpirun=1.output
  tests/mpi/trilinos_step-27.with_p4est=true.with_trilinos=true.mpirun=2.output
Labels: Parallel distributed, Reviewed and ready to merge, Tests, hp, ready to test

#8426 Add two new methods to VectorizedArray
  doc/news/changes/minor/20190729PeterMunch
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/base/vectorization.h
  tests/base/vectorization_11.cc
  tests/base/vectorization_11.output
  tests/base/vectorization_11.output.avx
  tests/base/vectorization_11.output.avx512
  tests/base/vectorization_11.output.sse2
Labels: Reviewed and ready to merge, SIMD, ready to test

#8427 Add AffineConstraints::set_zero for MemorySpace::CUDA
  doc/news/changes/minor/20190728DanielArndt
  include/deal.II/lac/affine_constraints.templates.h
  source/lac/CMakeLists.txt
  source/lac/affine_constraints.cu
  tests/cuda/affine_constraints_set_zero.cu
  tests/cuda/affine_constraints_set_zero.mpirun=2.output
Labels: GPU, Reviewed and ready to merge, ready to test

#8433 Bug in CellDataStorage::erase() fixed
  include/deal.II/base/quadrature_point_data.h
  tests/base/cell_data_storage_02.cc
Labels: ready to test

#8416 Update some commentary.
  include/deal.II/hp/refinement.h
Labels: Documentation

#8423 Enable periodicity for 1D
  doc/news/changes/minor/20190727PeterMunch
  include/deal.II/dofs/dof_accessor.templates.h
  source/dofs/dof_tools_constraints.inst.in
  source/grid/tria.cc
  tests/bits/periodicity_01.cc
  tests/bits/periodicity_01.output
  tests/grid/periodicity_01.cc
  tests/grid/periodicity_01.output
Labels: Triangulation, ready to test

#8424 Follow-up to PR #8342
  include/deal.II/base/numbers.h
Labels: SIMD, ready to test

#8435 Restrict mpi/petsc_step-27 to only be run with non-complex PETSc scalar type
  tests/mpi/petsc_step-27.with_p4est=true.with_petsc=true.with_petsc_with_complex=false.mpirun=1.output
  tests/mpi/petsc_step-27.with_p4est=true.with_petsc=true.with_petsc_with_complex=false.mpirun=2.output
Labels: Reviewed and ready to merge, ready to test

#8431 Fix compiling with CUDA
  cmake/checks/check_01_cpu_features.cmake
  include/deal.II/base/config.h.in
Labels: GPU, SIMD, ready to test

#8432 Implement output operator for VectorizedArray
  doc/news/changes/minor/20190729DanielArndt
  include/deal.II/base/vectorization.h
  tests/base/vectorization_12.cc
  tests/base/vectorization_12.output
Labels: SIMD, ready to test
