Repository dealii/dealii, pull requests merged in 2019-08, with the labels that each got.

#8403 Enable MappingFEField on multigrid levels
  doc/news/changes/minor/20190722MartinKronbichlerJohannesHeinz
  include/deal.II/fe/mapping_fe_field.h
  source/fe/mapping_fe_field.cc
  tests/mappings/mapping_fe_field_04.cc
  tests/mappings/mapping_fe_field_04.output
  tests/mappings/mapping_fe_field_05.cc
  tests/mappings/mapping_fe_field_05.output
  tests/mappings/mapping_fe_field_06.cc
  tests/mappings/mapping_fe_field_06.with_mpi=true.with_p4est=true.mpirun=3.output
Labels: Mapping, Reviewed and ready to merge, ready to test

#8441 Add boost files
  bundled/boost-1.70.0/include/boost/type_traits/detail/is_function_cxx_03.hpp
  bundled/boost-1.70.0/include/boost/type_traits/detail/is_member_function_pointer_cxx_03.hpp
Labels: ready to test

#8428 Enforce inlining in simple tensor functions
  include/deal.II/base/numbers.h
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/base/tensor.h
  include/deal.II/base/tensor_accessors.h
  include/deal.II/physics/elasticity/kinematics.h
Labels: Tensors, ready to test

#8442 Augment documentation of VectorizedArray
  include/deal.II/base/vectorization.h
Labels: Documentation, Reviewed and ready to merge, SIMD, ready to test

#8443 Cleanup workarounds for VectorizedArray
  include/deal.II/base/numbers.h
  include/deal.II/base/tensor.h
  include/deal.II/base/vectorization.h
Labels: SIMD, ready to test

#8450 Added 'boost/type_traits/detail/is_likely_lambda.hpp'.
  bundled/boost-1.70.0/include/boost/type_traits/detail/is_likely_lambda.hpp
Labels: Reviewed and ready to merge, ready to test

#8452 mpi/step-27: Check consistency of AffineConstraints.
  tests/mpi/petsc_step-27.cc
  tests/mpi/trilinos_step-27.cc
Labels: Reviewed and ready to merge, ready to test

#8451 Slight restructure the SVG grid output.
  include/deal.II/grid/grid_out.h
  source/grid/grid_out.cc
  tests/grid/grid_out_svg_01.output
  tests/grid/grid_out_svg_02.output
Labels: Reviewed and ready to merge, ready to test

#8449 Instantiate for all dimensions GridOut::write_svg
  source/grid/grid_out.inst.in
Labels: Reviewed and ready to merge, ready to test

#8448 Use VTU format in step-5.
  doc/news/changes/minor/20190803Bangerth-2
  examples/step-5/doc/results.dox
  examples/step-5/step-5.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#8454 Mark DEAL_II_ALWAYS_INLINE function as inline
  include/deal.II/base/symmetric_tensor.h
Labels: Reviewed and ready to merge, Tensors, ready to test

#8455 Avoid explicit template arguments in std::make_pair
  include/deal.II/fe/fe_system.h
  source/particles/particle_handler.cc
Labels: Reviewed and ready to merge, ready to test

#8459 Avoid more boost warnings
  bundled/boost-1.70.0/include/boost/archive/impl/basic_binary_iarchive.ipp
  bundled/boost-1.70.0/include/boost/detail/endian.hpp
Labels: External libraries, Reviewed and ready to merge, ready to test

#8447 Let step-1 output SVG instead of EPS.
  doc/news/changes/minor/20190803Bangerth-1
  examples/step-1/doc/results.dox
  examples/step-1/step-1.cc
Labels: Tutorials

#8456 Further cleanups of the SVG GridOut code.
  source/grid/grid_out.cc
Labels: Reviewed and ready to merge, ready to test

#8462 Fix evenb typo.
  include/deal.II/base/utilities.h
Labels: Reviewed and ready to merge, ready to test

#8471 Null pointer check added to CellDagaStorage::get_data()
  doc/news/changes/minor/20190806RezaRastak
  include/deal.II/base/quadrature_point_data.h
Labels: ready to test

#8473 Avoid deprecated features in step-54.
  examples/step-54/step-54.cc
Labels: Enhancement, Reviewed and ready to merge, ready to test

#8475 Simplify SymmetricTensor constructor
  include/deal.II/base/symmetric_tensor.h
Labels: Reviewed and ready to merge, ready to test

#8444 Add workload imbalance function
  include/deal.II/multigrid/mg_tools.h
  source/multigrid/mg_tools.cc
  source/multigrid/mg_tools.inst.in
  tests/multigrid/workload_imbalance.cc
  tests/multigrid/workload_imbalance.with_mpi=true.with_p4est=true.mpirun=3.output
Labels: ready to test

#8481 Rearrange measure
  include/deal.II/grid/grid_tools.h
  source/grid/tria_accessor.cc
Labels: Reviewed and ready to merge, ready to test

#8489 Added entry to minor changes log.
  doc/news/changes/minor/20190806MarieKajan
Labels: Documentation

#8490 Changes to enclosed_hyper_cube and moebius documentation
  doc/news/changes/minor/20190807ManaswineeBezbaruah
  include/deal.II/grid/grid_generator.h
Labels: Documentation, Triangulation

#8483 step-50: use ranged-for
  examples/step-50/step-50.cc
Labels: Reviewed and ready to merge, ready to test

#8491 Mark-up fixes in the BR element.
  include/deal.II/base/polynomials_bernardi_raugel.h
Labels: Documentation, Reviewed and ready to merge

#8384 Complex periodic constraints
  doc/news/changes/minor/20190802GarciaSanchez
  include/deal.II/dofs/dof_tools.h
  source/dofs/dof_tools_constraints.cc
  source/dofs/dof_tools_constraints.inst.in
  tests/bits/periodicity_08.cc
  tests/bits/periodicity_08.output
  tests/dofs/dof_tools_23.cc
  tests/dofs/dof_tools_23.output
Labels: ready to test

#8468 Edits to step-4 commented program pertaining to right-hand-side and dim
  doc/news/changes/minor/20190807Gleeson
  examples/step-4/step-4.cc
Labels: Documentation

#8493 step-49: do not use "untitled" as a filename
  examples/step-49/doc/intro.dox
  examples/step-49/example.geo
  examples/step-49/example.msh
  examples/step-49/step-49.cc
Labels: Enhancement, Reviewed and ready to merge, Tutorials, ready to test

#8472 Change all uses of MappingType and mapping_type
  doc/news/changes/incompatibilities/20190806GrahamHarper
  include/deal.II/fe/fe.h
  include/deal.II/fe/fe_dg_vector.h
  include/deal.II/fe/fe_dg_vector.templates.h
  include/deal.II/fe/fe_nedelec_sz.h
  include/deal.II/fe/fe_poly_tensor.h
  include/deal.II/fe/mapping.h
  include/deal.II/fe/mapping_cartesian.h
  include/deal.II/fe/mapping_fe_field.h
  include/deal.II/fe/mapping_manifold.h
  include/deal.II/fe/mapping_q.h
  include/deal.II/fe/mapping_q_generic.h
  include/deal.II/numerics/vector_tools.templates.h
  source/fe/fe_abf.cc
  source/fe/fe_bdm.cc
  source/fe/fe_bernardi_raugel.cc
  source/fe/fe_nedelec.cc
  source/fe/fe_nedelec_sz.cc
  source/fe/fe_poly_tensor.cc
  source/fe/fe_raviart_thomas.cc
  source/fe/fe_raviart_thomas_nodal.cc
  source/fe/fe_rt_bubbles.cc
  source/fe/mapping_cartesian.cc
  source/fe/mapping_fe_field.cc
  source/fe/mapping_manifold.cc
  source/fe/mapping_q.cc
  source/fe/mapping_q_generic.cc
Labels: Reviewed and ready to merge, ready to test

#8480 Fixed typos and wording in step-20
  doc/news/changes/minor/20190807NicoleHayes
  examples/step-20/step-20.cc
Labels: Documentation, Reviewed and ready to merge

#8507 Add an entry to doc/news/changes/minor to summarize change for step-51
  doc/news/changes/minor/20190807JiuhuaHu.txt
Labels: Documentation, Reviewed and ready to merge

#8503 ignore .DS_Store files
  .gitignore
Labels: Infrastructure

#8465 Add frobenius_norm method to BlockMatrixBase
  doc/news/changes/minor/20190806JonathanRobey
  include/deal.II/lac/block_matrix_base.h
  tests/lac/block_matrices_05.cc
  tests/lac/block_matrices_05.output
Labels: Enhancement, Linear Algebra, ready to test

#8515 add entry to doc/news/changes/minor
  doc/news/changes/minor/20190807RebeccaFildes
Labels: Reviewed and ready to merge

#8512 Added std_cxx17::apply() method.
  doc/news/changes/minor/20190808LucaHeltai
  include/deal.II/base/std_cxx17/tuple.h
  tests/base/stdcxx17_apply.cc
  tests/base/stdcxx17_apply.output
Labels: Infrastructure, Reviewed and ready to merge, ready for review, ready to test

#8529 Remove match_dimension
  include/deal.II/fe/fe_tools.templates.h
Labels: Reviewed and ready to merge, ready to test

#8484 Cell id is the key
  doc/news/changes/incompatibilities/20190808RezaRastak
  doc/news/changes/minor/20190807RezaRastakPeterMunch
  include/deal.II/base/quadrature_point_data.h
  tests/base/cell_data_storage_03.cc
  tests/base/cell_data_storage_03.output
Labels: Bug, ready to test

#8523 Step-3 possible extensions to label boundaries using x, y, z coordinates
  examples/step-3/doc/results.dox
Labels: Tutorials

#8501 Describing parameters
  doc/news/changes/minor/20190708LuelEmishaw
  include/deal.II/grid/grid_generator.h
Labels: Documentation, Reviewed and ready to merge

#8536 Make particle iterators const references in range-based for loops.
  tests/particles/particle_handler_01.cc
  tests/particles/particle_handler_02.cc
  tests/particles/particle_handler_03.cc
  tests/particles/particle_handler_04.cc
  tests/particles/particle_handler_05.cc
Labels: ready to test

#8500 Fix typos
  doc/news/changes/minor/20190808AdrianaMoralesMiranda
  examples/step-11/step-11.cc
  examples/step-33/doc/intro.dox
Labels: Documentation

#8467 Clear up confusion about what kind of refinement is to be explored
  doc/news/changes/minor/20190808KatherineCosburn
  examples/step-2/doc/results.dox
Labels: Documentation

#8537 Initialize particle locations with invalid numbers.
  source/particles/particle.cc
  tests/particles/particle_01.cc
  tests/particles/particle_01.output
Labels: ready to test

#8502 Clarified instructions for install directory
  doc/readme.html
Labels: Build system, Documentation

#8499 Grammar mistake in step 2
  examples/step-2/step-2.cc
Labels: Documentation

#8532 step-12: increase depth_console
  examples/step-12/step-12.cc
Labels: Reviewed and ready to merge, ready to test

#8538 improved documentation for grid generator
  doc/news/changes/minor/20190807MJayadharan
  include/deal.II/grid/grid_generator.h
Labels: Documentation

#8521 Matrix free atomic
  doc/news/changes/minor/20190808BrunoTurcksin
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  include/deal.II/matrix_free/cuda_matrix_free.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  tests/cuda/matrix_free_matrix_vector_03b.cu
  tests/cuda/matrix_free_matrix_vector_03b.output
  tests/cuda/matrix_vector_common.h
Labels: GPU, Reviewed and ready to merge, ready to test

#8549 Add more citations to step-51.
  doc/doxygen/references.bib
  doc/news/changes/minor/20190807Sanchez-Vizuet
  examples/step-51/doc/intro.dox
Labels: Documentation

#8531 Avoid CUDA warnings related to DEAL_II_ALWAYS_INLINE
  include/deal.II/base/symmetric_tensor.h
Labels: Reviewed and ready to merge, Tensors, ready to test

#8479 step 4: minor documentation edits
  doc/news/changes/minor/doc/news/changes/minor/20190807AshnaAggarwal
  examples/step-4/doc/intro.dox
  examples/step-4/doc/results.dox
Labels: Tutorials

#8551 Update some documentation pieces.
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_levels.h
  source/grid/tria_accessor.cc
Labels: Documentation

#8547 Fix bug in MatrixFree ghost exchange with faces and FE_Q
  doc/news/changes/minor/20190811MartinKronbichlerFabianCastelli
  include/deal.II/matrix_free/matrix_free.templates.h
  tests/matrix_free/loop_boundary.cc
  tests/matrix_free/loop_boundary.with_p4est=true.with_mpi=true.mpirun=1.output
  tests/matrix_free/loop_boundary.with_p4est=true.with_mpi=true.mpirun=2.output
Labels: Matrix-free, ready to test

#8514 Add extension to step2
  doc/news/changes/minor/20190808WenjuanZhang
  examples/step-2/doc/results.dox
Labels: Tutorials

#8429 Parallel distributed: Communicate active_fe_indices after deserializa…
  source/hp/dof_handler.cc
  tests/mpi/hp_active_fe_indices_transfer_01.cc
  tests/mpi/hp_active_fe_indices_transfer_01.with_p4est=true.mpirun=2.output
  tests/mpi/hp_active_fe_indices_transfer_01.with_p4est=true.mpirun=8.output
  tests/mpi/hp_active_fe_indices_transfer_02.cc
  tests/mpi/hp_active_fe_indices_transfer_02.with_p4est=true.mpirun=2.output
  tests/mpi/hp_active_fe_indices_transfer_02.with_p4est=true.mpirun=8.output
  tests/mpi/hp_active_fe_indices_transfer_03.cc
  tests/mpi/hp_active_fe_indices_transfer_03.with_p4est=true.mpirun=2.output
  tests/mpi/hp_active_fe_indices_transfer_03.with_p4est=true.mpirun=8.output
Labels: ready to test

#8519 Grid tools debug
  doc/news/changes/minor/20190808MJayadharan
  source/grid/grid_tools_cache.cc
Labels: Bug, Reviewed and ready to merge, ready to test

#8539 Improve resolution in step 8.
  examples/step-8/step-8.cc
Labels: Tutorials

#8560 Fix an assertion that was missing a semicolon.
  source/grid/grid_in.cc
Labels: Reviewed and ready to merge, ready to test

#8382 Checking if MPI is enabled to allow both Trilinos and PETSc.
  cmake/configure/configure_2_trilinos.cmake
Labels: Build system, ready to test

#8566 Fix doxygen documentation
  source/lac/full_matrix.cc
Labels: Reviewed and ready to merge, ready to test

#8526 Eccentric hyper shell
  doc/doxygen/images/eccentric_hyper_shell_2D.png
  doc/doxygen/images/eccentric_hyper_shell_3D.png
  doc/news/changes/minor/20190808MelanieGerault
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  source/grid/grid_generator.inst.in
  tests/grid/grid_generator_eccentric_hyper_shell.cc
  tests/grid/grid_generator_eccentric_hyper_shell.output
Labels: Enhancement, Triangulation, ready to test

#8430 Reduce floating-point division in operator/
  include/deal.II/base/complex_overloads.h
  include/deal.II/base/point.h
  include/deal.II/base/tensor.h
  include/deal.II/lac/block_vector_base.h
  tests/data_out/data_out_base_vtu_04.with_zlib=on.output
  tests/tensors/tensor_11.cc
  tests/tensors/tensor_11.output
Labels: Tensors, ready to test

#8528 Implement the PolynomialsBase classes
  include/deal.II/base/tensor_polynomials_base.h
  source/base/CMakeLists.txt
  source/base/tensor_polynomials_base.cc
Labels: Reviewed and ready to merge, ready to test

#8522 Implement pack_particles functions
  source/particles/particle_handler.cc
Labels: Enhancement, Particles, Reviewed and ready to merge, ready to test

#8513 Add compression options to pack and use default parameters
  include/deal.II/base/utilities.h
  tests/base/utilities_pack_unpack_07.cc
  tests/base/utilities_pack_unpack_07.with_zlib=off.output
  tests/base/utilities_pack_unpack_07.with_zlib=on.debug.output
  tests/base/utilities_pack_unpack_07.with_zlib=on.release.output
Labels: Enhancement, Reviewed and ready to merge, ready to test

#8576 Correct variable type in test grid/accessor_01
  tests/grid/accessor_01.cc
  tests/grid/accessor_01.output
Labels: Reviewed and ready to merge, ready to test

#8580 Pass MatrixFree::AdditionalData by reference
  include/deal.II/matrix_free/cuda_matrix_free.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  include/deal.II/matrix_free/matrix_free.h
Labels: Reviewed and ready to merge, ready to test

#8584 Fix clang-tidy complaints for Symengine
  include/deal.II/differentiation/sd/symengine_number_types.h
  include/deal.II/differentiation/sd/symengine_product_types.h
  source/differentiation/sd/symengine_number_types.cc
  source/differentiation/sd/symengine_scalar_operations.cc
  source/differentiation/sd/symengine_utilities.cc
Labels: Reviewed and ready to merge, ready to test

#8573 Exclude MacOS self-generated files from untracked files
  .gitignore
Labels: Infrastructure

#8570 Add the links to the figures in the documentation of GridGenerator::eccentric_hyper_shell()
  doc/doxygen/images/eccentric_hyper_shell_2D.png
  doc/doxygen/images/eccentric_hyper_shell_3D.png
  include/deal.II/grid/grid_generator.h
Labels: Documentation

#8569 Add cell->face_iterators()
  doc/news/changes/minor/20190814PeterMunchBangerthDanielArndt
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_accessor.templates.h
  tests/grid/accessor_02.cc
  tests/grid/accessor_02.output
Labels: ready to test

#8572 Make a few variables 'const'.
  source/fe/mapping_q_generic.cc
Labels: Enhancement, Reviewed and ready to merge, ready to test

#8555 New test: Chains of constraints on parallel hp-adaptive applications.
  tests/mpi/hp_constraints_consistent_01.cc
  tests/mpi/hp_constraints_consistent_01.with_p4est=true.mpirun=1.output
  tests/mpi/hp_constraints_consistent_01.with_p4est=true.mpirun=4.output
  tests/mpi/hp_constraints_consistent_02.cc
  tests/mpi/hp_constraints_consistent_02.with_p4est=true.mpirun=1.output
  tests/mpi/hp_constraints_consistent_02.with_p4est=true.mpirun=4.output
  tests/mpi/hp_constraints_consistent_03.cc
  tests/mpi/hp_constraints_consistent_03.with_p4est=true.mpirun=1.output
  tests/mpi/hp_constraints_consistent_03.with_p4est=true.mpirun=4.output
Labels: Reviewed and ready to merge, ready to test

#8588 Change Polynomial Classes to Derive from TensorPolynomialsBase
  include/deal.II/base/polynomials_abf.h
  include/deal.II/base/polynomials_bdm.h
  include/deal.II/base/polynomials_bernardi_raugel.h
  include/deal.II/base/polynomials_nedelec.h
  include/deal.II/base/polynomials_raviart_thomas.h
  include/deal.II/base/polynomials_rt_bubbles.h
  source/base/polynomials_abf.cc
  source/base/polynomials_bdm.cc
  source/base/polynomials_bernardi_raugel.cc
  source/base/polynomials_nedelec.cc
  source/base/polynomials_raviart_thomas.cc
  source/base/polynomials_rt_bubbles.cc
Labels: Reviewed and ready to merge, ready to test

#8593 Implement DoFAccessor::set/get_mg_dof_indices for 1D
  doc/news/changes/minor/20190818PeterMunch
  include/deal.II/dofs/dof_accessor.templates.h
Labels: Reviewed and ready to merge, ready to test

#8596 Use MPI_Exscan instead of MPI_Scan.
  source/base/data_out_base.cc
Labels: Reviewed and ready to merge, ready to test

#8595 added inlined keyword to function definitions in quadrature_point_data.h
  include/deal.II/base/quadrature_point_data.h
Labels: Reviewed and ready to merge, ready to test

#8594 Replace boost::optional by std_cxx17::optional.
  doc/news/changes/incompatibilities/20190817DanielArndt
  include/deal.II/base/std_cxx17/optional.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/numerics/fe_field_function.h
  include/deal.II/numerics/fe_field_function.templates.h
  include/deal.II/optimization/line_minimization.h
  source/dofs/dof_handler_policy.cc
  tests/distributed_grids/grid_tools_exchange_cell_data_04.cc
Labels: Reviewed and ready to merge, ready to test

#8542 Added the function GridGenerator::subdivided_hyper_L().
  doc/doxygen/images/subdivided_hyper_L_2d.png
  doc/doxygen/images/subdivided_hyper_L_3d.png
  doc/news/changes/minor/20190810MaeMarkowski
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  source/grid/grid_generator.inst.in
  tests/grid/grid_generator_01.cc
  tests/grid/grid_generator_01.output
Labels: Documentation, Enhancement, ready to test

#8470 Fix for Saturation Equation
  doc/news/changes/minor/20190807Omosebi
  examples/step-21/doc/intro.dox
Labels: Documentation

#8574 Avoid a couple FP subtractions.
  include/deal.II/fe/fe_poly.templates.h
Labels: Reviewed and ready to merge, ready to test

#8600 Rename parallel::Triangulation to parallel::TriangulationBase
  doc/news/changes/incompatibilities/20190819PeterMunch
  include/deal.II/distributed/cell_weights.h
  include/deal.II/distributed/shared_tria.h
  include/deal.II/distributed/tria.h
  include/deal.II/distributed/tria_base.h
  include/deal.II/dofs/dof_handler.h
  include/deal.II/dofs/dof_renumbering.h
  include/deal.II/dofs/dof_tools.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/grid_tools_cache.h
  include/deal.II/grid/tria_accessor.templates.h
  include/deal.II/hp/dof_handler.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  include/deal.II/matrix_free/face_setup_internal.h
  include/deal.II/matrix_free/matrix_free.templates.h
  include/deal.II/multigrid/mg_transfer.h
  include/deal.II/multigrid/mg_transfer.templates.h
  include/deal.II/multigrid/mg_transfer_matrix_free.h
  include/deal.II/numerics/vector_tools.h
  include/deal.II/numerics/vector_tools.templates.h
  source/distributed/cell_weights.cc
  source/distributed/shared_tria.cc
  source/distributed/tria.cc
  source/distributed/tria_base.cc
  source/distributed/tria_base.inst.in
  source/dofs/dof_handler_policy.cc
  source/dofs/dof_renumbering.cc
  source/dofs/dof_tools.cc
  source/dofs/dof_tools_constraints.cc
  source/dofs/dof_tools_sparsity.cc
  source/grid/grid_out.cc
  source/grid/grid_tools.cc
  source/grid/grid_tools_cache.cc
  source/hp/dof_handler.cc
  source/hp/refinement.cc
  source/multigrid/mg_level_global_transfer.cc
  source/multigrid/mg_tools.cc
  source/multigrid/mg_transfer_internal.cc
  source/multigrid/mg_transfer_prebuilt.cc
  source/non_matching/coupling.cc
Labels: Reviewed and ready to merge, ready to test

#8586 Return coarse-cell id by CellId
  doc/news/changes/minor/20190815PeterMunch
  include/deal.II/base/types.h
  include/deal.II/grid/cell_id.h
  include/deal.II/grid/tria.h
  source/grid/cell_id.cc
Labels: Reviewed and ready to merge, ready to test

#8597 Remove PolynomialType Template Argument from FE_PolyTensor
  include/deal.II/fe/fe_abf.h
  include/deal.II/fe/fe_bdm.h
  include/deal.II/fe/fe_bernardi_raugel.h
  include/deal.II/fe/fe_dg_vector.h
  include/deal.II/fe/fe_dg_vector.templates.h
  include/deal.II/fe/fe_nedelec.h
  include/deal.II/fe/fe_poly_tensor.h
  include/deal.II/fe/fe_raviart_thomas.h
  include/deal.II/fe/fe_rt_bubbles.h
  source/fe/fe_abf.cc
  source/fe/fe_bdm.cc
  source/fe/fe_bernardi_raugel.cc
  source/fe/fe_nedelec.cc
  source/fe/fe_poly_tensor.cc
  source/fe/fe_poly_tensor.inst.in
  source/fe/fe_raviart_thomas.cc
  source/fe/fe_raviart_thomas_nodal.cc
  source/fe/fe_rt_bubbles.cc
Labels: Reviewed and ready to merge, ready to test

#8605 Replace boost::none by the std::optional default constructor
  include/deal.II/optimization/line_minimization.h
Labels: Reviewed and ready to merge, ready to test

#8608 Fix tuple.h
  include/deal.II/base/std_cxx17/tuple.h
Labels: ready to test

#8567 Modify the definition of CellId
  doc/news/changes/minor/20190813PeterMunch
  include/deal.II/grid/tria.h
  source/grid/cell_id.cc
  source/grid/tria_accessor.cc
Labels: Triangulation, ready to test

#8579 Generalize DoFHandlerPolicy of p:d:t
  doc/news/changes/minor/20190814PeterMunch-1
  include/deal.II/distributed/tria.h
  source/distributed/tria.cc
  source/dofs/dof_handler_policy.cc
  tests/mpi/mg_ghost_dofs_periodic_06.mpirun=7.output
  tests/sharedtria/dof_05.cc
Labels: Do not merge :skull_and_crossbones:, Reviewed and ready to merge, ready to test

#8599 Add a test.
  tests/tensors/tensor_30.cc
  tests/tensors/tensor_30.output
Labels: ready to test

#8611 Documentation typos fixed in theta_timestepping.h and newton.h
  include/deal.II/algorithms/newton.h
  include/deal.II/algorithms/theta_timestepping.h
Labels: Documentation

#8577 Add particle generators namespace
  doc/news/changes/minor/20190814ReneGassmoeller
  include/deal.II/particles/generators.h
  source/particles/CMakeLists.txt
  source/particles/generators.cc
  source/particles/generators.inst.in
  tests/particles/generators_01.cc
  tests/particles/generators_01.with_p4est=true.output
  tests/particles/generators_02.cc
  tests/particles/generators_02.with_p4est=true.output
  tests/particles/generators_03.cc
  tests/particles/generators_03.with_p4est=true.debug.output
  tests/particles/generators_03.with_p4est=true.release.output
Labels: Reviewed and ready to merge, ready to test

#8564 Change GridOut::write_svg() defaults
  doc/news/changes/incompatibilities/20190805Bangerth
  include/deal.II/grid/grid_out.h
  tests/grid/get_finest_common_cells_04.cc
  tests/grid/grid_out_svg_01.cc
  tests/grid/grid_out_svg_02.cc
Labels: Reviewed and ready to merge, ready to test

#8474 Cleanup use of DEAL_II_CONSTEXPR
  include/deal.II/base/numbers.h
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/base/tensor.h
  tests/tensors/constexpr_symmetric_tensor.cc
  tests/tensors/constexpr_tensor.cc
  tests/tensors/constexpr_tensor.output
Labels: C++11, ready to test

#8614 Only allow floating point types in complex_overloads.h
  doc/news/changes/incompatibilities/20190821DanielArndt
  include/deal.II/base/complex_overloads.h
Labels: Reviewed and ready to merge, ready to test

#8613 Fixed small bug in OCC::interpolation_curve.
  doc/news/changes/minor/20190821LucaHeltai
  source/opencascade/utilities.cc
  tests/opencascade/interpolation_curve_boundary_02.cc
  tests/opencascade/interpolation_curve_boundary_02.output
Labels: Reviewed and ready to merge, ready to test

#8587 Enable DoFHandlerPolicy of p:d:t for 1D
  doc/news/changes/minor/20190816PeterMunch
  include/deal.II/distributed/p4est_wrappers.h
  source/distributed/p4est_wrappers.cc
Labels: Reviewed and ready to merge, ready to test

#8610 Document the concept of 'coarse cell id' in the glossary.
  doc/doxygen/headers/glossary.h
  include/deal.II/base/types.h
  include/deal.II/grid/cell_id.h
  include/deal.II/grid/tria.h
Labels: ready to test

#8609 Avoid warning regarding VectorizedArray: no-user provided constructor
  include/deal.II/base/tensor_accessors.h
Labels: Reviewed and ready to merge, Tensors, ready to test

#8601 Add assertion to PETScWrappers::MatrixBase::begin() and end().
  doc/news/changes/minor/20190819SebastianStark
  include/deal.II/lac/petsc_matrix_base.h
  tests/petsc/matrix_base_iterator_01.cc
  tests/petsc/matrix_base_iterator_01.output
Labels: Reviewed and ready to merge, ready to test

#8620 Use std::free instead of free to avoid name collision when using hipcc
  include/deal.II/base/memory_space.h
  include/deal.II/lac/read_write_vector.h
Labels: GPU, Reviewed and ready to merge, ready to test

#8592 Introduce parallel::DistributedTriangulationBase
  doc/news/changes/minor/20190817PeterMunch
  include/deal.II/distributed/tria.h
  include/deal.II/distributed/tria_base.h
  include/deal.II/dofs/dof_handler_policy.h
  source/distributed/tria.cc
  source/distributed/tria_base.cc
  source/distributed/tria_base.inst.in
  source/dofs/dof_handler_policy.cc
Labels: Reviewed and ready to merge, ready to test

#8602 Fix Symengine test
  include/deal.II/base/tensor.h
  tests/symengine/symengine_scalar_operations_04.cc
  tests/symengine/symengine_scalar_operations_04.output
Labels: ready to test

#8624 Augment documentation in one place.
  include/deal.II/fe/fe_poly_tensor.h
Labels: Documentation

#8598 Update a documentation string.
  include/deal.II/fe/fe_dg_vector.h
Labels: Documentation

#8618 Update documentation of FE_PolyTensor.
  include/deal.II/base/tensor_polynomials_base.h
  include/deal.II/fe/fe_poly.h
  include/deal.II/fe/fe_poly_tensor.h
Labels: Documentation

#8619 Rename TensorPolynomials::compute() to ::evaluate().
  doc/news/changes/incompatibilities/20190821Bangerth
  include/deal.II/base/polynomials_abf.h
  include/deal.II/base/polynomials_bdm.h
  include/deal.II/base/polynomials_bernardi_raugel.h
  include/deal.II/base/polynomials_nedelec.h
  include/deal.II/base/polynomials_raviart_thomas.h
  include/deal.II/base/polynomials_rt_bubbles.h
  include/deal.II/base/tensor_polynomials_base.h
  include/deal.II/fe/fe_poly_tensor.h
  source/base/polynomials_abf.cc
  source/base/polynomials_bdm.cc
  source/base/polynomials_bernardi_raugel.cc
  source/base/polynomials_nedelec.cc
  source/base/polynomials_raviart_thomas.cc
  source/base/polynomials_rt_bubbles.cc
  source/fe/fe_poly_tensor.cc
  tests/base/polynomials_bdm_01.cc
  tests/base/polynomials_bdm_02.cc
  tests/base/polynomials_br.cc
  tests/base/polynomials_rt.cc
  tests/base/polynomials_rt_bubbles.cc
  tests/base/polynomials_tensor.cc
Labels: ready to test

#8627 Rename settings_ to settings in distributed/tria.cc
  source/distributed/tria.cc
Labels: Parallel distributed, Reviewed and ready to merge, ready to test

#8629 Make constructor of p:d:t explicit
  include/deal.II/distributed/tria.h
Labels: Reviewed and ready to merge, ready to test

#8626 Clarify something in the readme file that seems to perpetually perplex people
  doc/readme.html
Labels: Documentation

#8632 Clarify the use of the adjective 'integral'.
  examples/step-3/doc/intro.dox
Labels: Documentation

#8631 Use VTK as the file format for step-3
  doc/news/changes/minor/20190823Bangerth
  examples/step-3/doc/results.dox
  examples/step-3/step-3.cc
Labels: Tutorials, ready to test

#8630 Fix PETScWrappers::MatrixBase::end(row)
  include/deal.II/lac/petsc_matrix_base.h
Labels: Reviewed and ready to merge, ready to test

#8359 Remove deprecated Tensor functions.
  include/deal.II/base/tensor.h
  include/deal.II/base/tensor_deprecated.h
  tests/ad_common_tests/helper_scalar_coupled_2_components_03.h
  tests/ad_common_tests/tensor_functions_01.h
  tests/adolc/tensor_ops_01.cc
  tests/base/full_tensor_06.cc
  tests/fe/fe_project_3d.cc
  tests/tensors/tensor_09.cc
  tests/tensors/tensor_09.output
Labels: Miscellaneous, ready to test

#8623 Rename the Poly*::compute_n_pols() function to ::n_polynomials().
  doc/news/changes/incompatibilities/20190822Bangerth
  include/deal.II/base/polynomial_space.h
  include/deal.II/base/polynomials_abf.h
  include/deal.II/base/polynomials_bdm.h
  include/deal.II/base/polynomials_bernardi_raugel.h
  include/deal.II/base/polynomials_nedelec.h
  include/deal.II/base/polynomials_raviart_thomas.h
  include/deal.II/base/polynomials_rt_bubbles.h
  include/deal.II/fe/fe_dg_vector.templates.h
  source/base/polynomial_space.cc
  source/base/polynomials_abf.cc
  source/base/polynomials_bdm.cc
  source/base/polynomials_bernardi_raugel.cc
  source/base/polynomials_nedelec.cc
  source/base/polynomials_raviart_thomas.cc
  source/base/polynomials_rt_bubbles.cc
  source/fe/fe_abf.cc
  source/fe/fe_bdm.cc
  source/fe/fe_bernardi_raugel.cc
  source/fe/fe_nedelec.cc
  source/fe/fe_raviart_thomas.cc
  source/fe/fe_raviart_thomas_nodal.cc
  source/fe/fe_rt_bubbles.cc
Labels: ready to test

#8633 Add initializing constructor to DiagonalMatrix
  doc/news/changes/minor/20190823DanielArndt
  include/deal.II/lac/diagonal_matrix.h
  tests/lac/diagonal_matrix_02.cc
Labels: ready to test

#8640 Make a destructor virtual.
  include/deal.II/base/mpi.h
Labels: Miscellaneous, Reviewed and ready to merge, ready to test

#8642 Workshop 1
  examples/step-33/step-33.cc
  examples/step-4/step-4.cc
Labels: Enhancement, Miscellaneous, Reviewed and ready to merge, ready to test

#8649 fixed the representation of the decrement operator -- in doxygen
  include/deal.II/base/vectorization.h
  include/deal.II/dofs/dof_handler.h
  include/deal.II/grid/filtered_iterator.h
  include/deal.II/grid/tria_iterator.h
  include/deal.II/lac/petsc_precondition.h
  include/deal.II/particles/particle_iterator.h
Labels: Reviewed and ready to merge, ready to test

#8530 Mutable bind implementation.
  doc/news/changes/minor/20190808LucaHeltaiMatthiasMaier
  include/deal.II/base/mutable_bind.h
  tests/base/mutable_bind_01.cc
  tests/base/mutable_bind_01.output
  tests/base/mutable_bind_02.cc
  tests/base/mutable_bind_02.output
  tests/base/mutable_bind_03.cc
  tests/base/mutable_bind_03.output
  tests/base/mutable_bind_04.cc
  tests/base/mutable_bind_04.output
Labels: Reviewed and ready to merge, ready to test

#8667 Doc updates in a variety of places.
  doc/doxygen/references.bib
  include/deal.II/fe/fe_nothing.h
  include/deal.II/fe/fe_p1nc.h
  include/deal.II/fe/mapping_cartesian.h
Labels: Documentation

#8665 Speed parallel::distributed::Triangulation::add_periodicity up
  source/distributed/tria.cc
Labels: Reviewed and ready to merge, ready to test

#8672 Introduced DoFCellAccessor:get_future_fe().
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/dofs/dof_accessor.templates.h
  tests/hp/future_fe_indices.cc
  tests/hp/future_fe_indices.output
Labels: Reviewed and ready to merge, ready to test

#8671 parameter handling for a couple of classes improved
  include/deal.II/algorithms/newton.templates.h
  include/deal.II/algorithms/theta_timestepping.templates.h
  source/algorithms/timestep_control.cc
Labels: Reviewed and ready to merge, ready to test

#8509 hyper_L documentation fix
  doc/news/changes/minor/20190807ImbertGerard
  include/deal.II/grid/grid_generator.h
Labels: Documentation
