Repository dealii/dealii, pull requests merged in 2019-10, with the labels that each got.

#8879 Fix using MemorySpace::Host with la_parallel_vector.templates.h and CUDA-aware MPI
  include/deal.II/lac/la_parallel_vector.templates.h
Labels: Reviewed and ready to merge, ready to test

#8880 Synchronize CUDA device in MPI ghost exchange
  include/deal.II/base/partitioner.templates.h
Labels: GPU

#8887 Avoid including thread_management.h
  include/deal.II/base/polynomials_integrated_legendre_sz.h
  include/deal.II/fe/fe_tools_interpolate.templates.h
  include/deal.II/grid/composition_manifold.h
  include/deal.II/grid/manifold.h
  include/deal.II/lac/chunk_sparse_matrix.templates.h
  include/deal.II/lac/read_write_vector.h
  include/deal.II/lac/sparse_direct.h
  include/deal.II/lac/sparse_matrix.templates.h
  include/deal.II/lac/vector_operations_internal.h
  include/deal.II/numerics/error_estimator.templates.h
  include/deal.II/numerics/matrix_tools.h
  source/base/multithread_info.cc
  source/base/scalar_polynomials_base.cc
  source/base/subscriptor.cc
  source/base/tensor_polynomials_base.cc
  source/base/timer.cc
  source/dofs/dof_renumbering.cc
  source/dofs/dof_tools.cc
  source/dofs/dof_tools_constraints.cc
  source/dofs/dof_tools_sparsity.cc
  source/fe/mapping_fe_field.cc
  source/lac/sparse_direct.cc
  source/numerics/error_estimator_1d.cc
  source/numerics/time_dependent.cc
Labels: Reviewed and ready to merge, ready to test

#8888 Remove some uses of std::bind from thread_management.h
  include/deal.II/base/thread_management.h
Labels: C++11, Reviewed and ready to merge, ready to test

#8893 Add VectorizedArray::size() member function
  doc/news/changes/minor/20191008MartinKronbichler
  include/deal.II/base/vectorization.h
  tests/base/vectorization_01.cc
Labels: SIMD, ready to test

#8895 Fix a bug in merge triangulations()
  doc/news/changes/minor/20191008SebastianStark
  source/grid/tria.cc
  tests/grid/merge_triangulations_07.cc
  tests/grid/merge_triangulations_07.output
Labels: ready to test

#8894 New functionality to compute maximum aspect ratio of a mesh
  doc/news/changes/minor/20191009NiklasFehn
  include/deal.II/grid/grid_tools.h
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
  tests/grid/grid_tools_aspect_ratio.cc
  tests/grid/grid_tools_aspect_ratio.output
Labels: Triangulation, ready to test

#8900 Introduce VectorizedArrayBase and VectorizedArrayIterator
  doc/news/changes/minor/20191008MartinKronbichler
  doc/news/changes/minor/20191012MartinKronbichlerPeterMunchDanielArndt
  include/deal.II/base/vectorization.h
  tests/base/vectorization_iterator_01.cc
  tests/base/vectorization_iterator_01.output
Labels: SIMD, ready to test

#8903 VectorizedArray: Update documentation POD -> StandardLayoutType
  include/deal.II/base/vectorization.h
Labels: Documentation, SIMD

#8908 Fix another typo in tensor.h
  include/deal.II/base/tensor.h
Labels: Documentation

#8901 Fix DoFHandler>::n_boundary_dofs() in issue #8897
  doc/news/changes/minor/20191011DougShiDong
  include/deal.II/dofs/dof_handler.h
  include/deal.II/hp/dof_handler.h
  source/dofs/dof_handler.cc
  source/hp/dof_handler.cc
  tests/dofs/n_boundary_dofs_01.cc
  tests/dofs/n_boundary_dofs_01.with_p4est=true.mpirun=1.output
  tests/dofs/n_boundary_dofs_01.with_p4est=true.mpirun=2.output
  tests/hp/n_boundary_dofs_01.cc
  tests/hp/n_boundary_dofs_01.with_p4est=true.mpirun=1.output
  tests/hp/n_boundary_dofs_01.with_p4est=true.mpirun=2.output
Labels: ready to test

#8913 fix bug in GridGenerator::torus<3,3>()
  source/grid/grid_generator.cc
  tests/grid/torus_01.output
Labels: Triangulation, ready to test

#8915 Save level_mg_handler inside of MatrixFree
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
Labels: Matrix-free, ready to test

#8917 Use positive form for comments.
  source/grid/tria.cc
Labels: Documentation

#8919 Replace level_mg_handler by mg_level
  doc/news/changes/incompatibilities/20191017PeterMunch
  examples/step-37/step-37.cc
  examples/step-59/step-59.cc
  include/deal.II/matrix_free/face_setup_internal.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
  tests/mappings/mapping_q_eulerian_08.cc
  tests/matrix_free/cell_categorization_02.cc
  tests/matrix_free/cell_level_and_index.cc
  tests/matrix_free/compare_faces_by_cells.cc
  tests/matrix_free/dg_pbc_02.cc
  tests/matrix_free/matrix_vector_mg.cc
  tests/matrix_free/multigrid_dg_periodic.cc
  tests/matrix_free/multigrid_dg_sip_01.cc
  tests/matrix_free/multigrid_dg_sip_02.cc
  tests/matrix_free/parallel_multigrid.cc
  tests/matrix_free/parallel_multigrid_02.cc
  tests/matrix_free/parallel_multigrid_adaptive_01.cc
  tests/matrix_free/parallel_multigrid_adaptive_02.cc
  tests/matrix_free/parallel_multigrid_adaptive_03.cc
  tests/matrix_free/parallel_multigrid_adaptive_04.cc
  tests/matrix_free/parallel_multigrid_adaptive_05.cc
  tests/matrix_free/parallel_multigrid_adaptive_06.cc
  tests/matrix_free/parallel_multigrid_adaptive_06ref.cc
  tests/matrix_free/parallel_multigrid_adaptive_07.cc
  tests/matrix_free/parallel_multigrid_adaptive_08.cc
  tests/matrix_free/parallel_multigrid_fullydistributed.cc
  tests/matrix_free/parallel_multigrid_mf.cc
  tests/matrix_free/step-37-inhomogeneous-1.cc
  tests/matrix_free/step-37.cc
  tests/matrix_free/stokes_computation.cc
  tests/mpi/step-37.cc
Labels: ready to test

#8910 Document unsupported MG refinement edges for matrix-free DG
  include/deal.II/matrix_free/face_setup_internal.h
Labels: Matrix-free, ready to test

#8916 Extend GridGenerator::torus<3,3>() so that one can generate a torus segment
  doc/news/changes/minor/20191016NiklasFehn
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  source/grid/grid_generator_from_name.cc
  tests/grid/grid_generator_open_torus.cc
  tests/grid/grid_generator_open_torus.output
Labels: Triangulation, ready to test

#8904 Simplify code for writing vtu/pvtu output files in application programs
  doc/news/changes/minor/20191014NiklasFehn
  include/deal.II/base/data_out_base.h
  source/base/data_out_base.cc
Labels: Post-processing, ready to test

#8923 More minor updates.
  source/grid/grid_tools.cc
Labels: Reviewed and ready to merge, Triangulation, ready to test

#8922 Minor code and documentation updates.
  include/deal.II/base/vectorization.h
Labels: Reviewed and ready to merge, SIMD, ready to test

#8909 Add get_face_iterator to MatrixFree
  doc/news/changes/minor/20191016MartinKronbichlerPeterMunchMichalWichrowski
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#8926 Replace std::shared_ptr in WorkStream
  include/deal.II/base/work_stream.h
Labels: Reviewed and ready to merge, ready to test

#8924 Refactoring of Utilities::needed_digits()
  doc/news/changes/minor/20191018NiklasFehn
  source/base/data_out_base.cc
  source/base/utilities.cc
  tests/base/utilities_01.cc
  tests/base/utilities_01.output
Labels: Enhancement, Reviewed and ready to merge, ready to test

#8891 Remove std::bind from examples
  examples/step-12/step-12.cc
  examples/step-13/step-13.cc
  examples/step-14/step-14.cc
  examples/step-27/step-27.cc
  examples/step-32/step-32.cc
  examples/step-44/step-44.cc
  examples/step-49/step-49.cc
  examples/step-51/step-51.cc
  examples/step-9/step-9.cc
Labels: Reviewed and ready to merge, ready to test

#8930 Fix ConsensusAlgorithm_NBX
  include/deal.II/base/mpi.h
  source/base/mpi.cc
Labels: Reviewed and ready to merge, ready to test

#8936 avoid 64bit overflow in Partiioner::set_ghost_indices
  source/base/partitioner.cc
Labels: Reviewed and ready to merge, ready to test

#8935 add a barrier to avoid MPI race in ConsensusAlgorithm
  include/deal.II/base/mpi_compute_index_owner_internal.h
Labels: ready to test

#8940 Improve and fix some doxygen things in step-3.
  examples/step-3/doc/results.dox
Labels: Documentation

#8939 Fix missing MPI_Wait in compute_point_to_point_communication_pattern
  source/base/mpi.cc
Labels: ready to test

#8492 step-49: switch to vtu and add possible extensions
  examples/step-49/doc/intro.dox
  examples/step-49/doc/results.dox
  examples/step-49/step-49.cc
Labels: Tutorials

#8942 Update the results section of step-49.
  examples/step-49/doc/results.dox
Labels: Documentation

#8949 doc: improve write_vtu_with_pvtu_record
  include/deal.II/base/data_out_base.h
Labels: Documentation

#8947 new MPI::free_communicator and DuplicatedCommunicator helper
  doc/news/changes/minor/20191022TimoHeister
  include/deal.II/base/mpi.h
  source/base/mpi.cc
  tests/mpi/communicator_duplicated.cc
  tests/mpi/communicator_duplicated.mpirun=2.output
Labels: ready to test

#8902 Make output cells, faces and co-faces optional in GridOut::write_vtk
  doc/news/changes/minor/20191011PeterMunch
  include/deal.II/grid/grid_out.h
  source/grid/grid_out.cc
  tests/grid/grid_out_vtk_03.cc
  tests/grid/grid_out_vtk_03.output
Labels: Post-processing, ready to test

#8946 Make VectorTools::interpolate() working in parallel
  doc/news/changes/minor/20191022PasqualeClaudioAfrica
  include/deal.II/numerics/vector_tools.h
  include/deal.II/numerics/vector_tools.templates.h
  tests/vector_tools/interpolate.cc
  tests/vector_tools/interpolate.with_p4est=true.mpirun=1.output
  tests/vector_tools/interpolate.with_p4est=true.mpirun=2.output
Labels: Reviewed and ready to merge, ready to test

#8952 Delete FunctionParse copy constructor.
  include/deal.II/base/function_parser.h
Labels: Reviewed and ready to merge, ready to test

#8898 Step-61 Use FE_DGRT for Darcy velocity
  examples/step-61/step-61.cc
Labels: Reviewed and ready to merge, ready to test

#8927 new function Utilities::cutoff_digits()
  doc/news/changes/minor/20191018NiklasFehn-2
  include/deal.II/base/utilities.h
  source/base/utilities.cc
  tests/base/utilities_20.cc
  tests/base/utilities_20.output
Labels: Miscellaneous, Reviewed and ready to merge, ready to test

#8885 FEInterfaceValues: gradients and hessians
  include/deal.II/fe/fe_interface_values.h
  tests/feinterface/fe_interface_values_08.cc
  tests/feinterface/fe_interface_values_08.output
Labels: ready to test

#8959 Report how much memory was requested when we fail allocating that much.
  include/deal.II/base/exceptions.h
  source/base/utilities.cc
Labels: ready to test

#8944 Fix bug in MatrixFree::get_face_iterator
  include/deal.II/matrix_free/matrix_free.templates.h
  tests/matrix_free/iterators.cc
  tests/matrix_free/iterators.output
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#8965 Add copy constuctor to MatrixFree::AdditionalData
  include/deal.II/matrix_free/matrix_free.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#8941 Fix an error check with MathJax.
  doc/doxygen/CMakeLists.txt
Labels: Build system

#8970 Fix docu of GridOutFlags::Svg
  include/deal.II/grid/grid_out.h
Labels: Documentation

#8676 Permit reinitialization with iterators instead of (sub)face numbers.
  doc/news/changes/minor/20191027DavidWells
  doc/news/changes/minor/20191027DavidWells-2
  include/deal.II/fe/fe_values.h
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_accessor.templates.h
  source/fe/fe_values.cc
  source/fe/fe_values.inst.in
  tests/fe/shapes.h
Labels: Enhancement, ready to test

#8687 Refactored parallel::CellWeights.
  doc/news/changes/incompatibilities/20190903Fehling
  include/deal.II/distributed/cell_weights.h
  source/distributed/cell_weights.cc
  source/hp/dof_handler.cc
  tests/mpi/hp_active_fe_indices_transfer_03.cc
  tests/mpi/hp_cell_weights_01.cc
  tests/mpi/hp_cell_weights_01.with_p4est=true.mpirun=2.output
  tests/mpi/hp_cell_weights_02.cc
  tests/mpi/hp_cell_weights_02.with_p4est=true.mpirun=3.output
  tests/mpi/hp_cell_weights_03.cc
  tests/mpi/hp_cell_weights_03.with_mpi=true.with_metis=true.mpirun=2.output
  tests/mpi/hp_cell_weights_03.with_mpi=true.with_metis=true.mpirun=2.output.1
  tests/mpi/hp_cell_weights_04.cc
  tests/mpi/hp_cell_weights_04.with_mpi=true.with_metis=true.mpirun=2.output
  tests/mpi/hp_cell_weights_04.with_mpi=true.with_metis=true.mpirun=2.output.1
Labels: Reviewed and ready to merge, ready to test
