Repository dealii/dealii, pull requests merged in 2020-02, with the labels that each got.

#9458 Fix a broken Trilinos Sacado CMake test
  cmake/configure/configure_2_trilinos.cmake
Labels: Bug, Build system, Reviewed and ready to merge, ready to test

#9456 Fix SymmetricTensor and Tensor ProductType
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/base/tensor.h
Labels: ready for review, ready to test

#9464 doxygen documentation fixes
  examples/step-46/doc/results.dox
  include/deal.II/dofs/dof_tools.h
  include/deal.II/grid/grid_generator.h
  include/deal.II/particles/data_out.h
  include/deal.II/particles/generators.h
  include/deal.II/particles/particle_handler.h
  source/particles/generators.cc
Labels: Reviewed and ready to merge, ready to test

#9465 Fix types in ConsensusAlgorithmProcess
  include/deal.II/base/mpi.h
  include/deal.II/base/mpi_compute_index_owner_internal.h
  source/base/mpi.cc
Labels: Reviewed and ready to merge, ready to test

#9469 CMake: Make TEST_PICKUP_REGEX stricter
  cmake/macros/macro_deal_ii_pickup_tests.cmake
Labels: Build system, Reviewed and ready to merge, Tests, ready to test

#9468 Update documentation of NeighborType.
  include/deal.II/base/bounding_box.h
Labels: Documentation, Reviewed and ready to merge, ready to test

#9466 Fix an overzealous assertion related to Dataout
  doc/news/changes/minor/20200202Bangerth
  include/deal.II/numerics/data_out_dof_data.h
  tests/data_out/merge_01.cc
  tests/data_out/merge_01.inp
  tests/data_out/merge_01.output
Labels: Bug, ready to test

#9471 Move implementation of ConsenusAlgorithm into mpi.templates.h
  include/deal.II/base/mpi.templates.h
  source/base/mpi.cc
Labels: Parallel distributed, Reviewed and ready to merge, ready to test

#9467 Use cell->face_iterators() or GeometryInfo::face_indices() in the tutorials.
  examples/step-14/step-14.cc
  examples/step-20/doc/intro.dox
  examples/step-21/step-21.cc
  examples/step-29/step-29.cc
  examples/step-30/step-30.cc
  examples/step-33/step-33.cc
  examples/step-46/doc/intro.dox
  examples/step-46/step-46.cc
  examples/step-49/doc/results.dox
  examples/step-51/step-51.cc
  examples/step-60/step-60.cc
  examples/step-61/step-61.cc
  examples/step-9/step-9.cc
Labels: Tutorials, ready to test

#9428 Add python wrappers for Quadrature
  contrib/python-bindings/include/quadrature_wrapper.h
  contrib/python-bindings/source/CMakeLists.txt
  contrib/python-bindings/source/export_quadrature.cc
  contrib/python-bindings/source/quadrature_wrapper.cc
  contrib/python-bindings/source/wrappers.cc
  contrib/python-bindings/tests/quadrature_wrapper.py
  doc/news/changes/minor/20200124AlexanderGrayver
Labels: Reviewed and ready to merge, ready to test

#9470 Address a question on the mailing list about step-20.
  examples/step-20/doc/intro.dox
Labels: Documentation, Tutorials

#9477 Convert one more place for GeometryInfo::face_indices().
  source/grid/grid_out.cc
Labels: ready to test

#9476 Convert more places to use GeometryInfo::face_indices().
  include/deal.II/base/geometry_info.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/tria_accessor.templates.h
  include/deal.II/matrix_free/cuda_hanging_nodes_internal.h
  include/deal.II/matrix_free/face_setup_internal.h
  include/deal.II/matrix_free/mapping_info.templates.h
  include/deal.II/matrix_free/matrix_free.templates.h
  include/deal.II/numerics/error_estimator.templates.h
  include/deal.II/numerics/matrix_creator.templates.h
  source/dofs/dof_tools_constraints.cc
  source/dofs/dof_tools_sparsity.cc
  source/fe/fe_enriched.cc
  source/fe/fe_nedelec.cc
  source/fe/mapping_fe_field.cc
  source/grid/grid_generator.cc
  source/grid/grid_out.cc
  source/grid/grid_tools.cc
  source/grid/tria.cc
  source/grid/tria_description.cc
  source/multigrid/mg_tools.cc
Labels: Reviewed and ready to merge, ready to test

#9457 Improve some operations in symmetric tensor and tensor
  include/deal.II/base/symmetric_tensor.h
Labels: Linear Algebra, ready to test

#9480 improve FunctionMap deprecation message
  include/deal.II/dofs/deprecated_function_map.h
  include/deal.II/hp/refinement.h
Labels: Reviewed and ready to merge, ready to test

#9481 Revert introduction of deprecated functions.
  doc/news/changes/minor/20200205Bangerth
  include/deal.II/base/data_out_base.h
  source/base/data_out_base.cc
  source/base/data_out_base.inst.in
Labels: ready to test

#9484 Add an assert on row index in SparseMatrix::add(..)
  include/deal.II/lac/sparse_matrix.templates.h
Labels: Linear Algebra, ready to test

#9482 Fix subscript in step-12 intro
  examples/step-12/doc/intro.dox
Labels: Reviewed and ready to merge, ready to test

#9220 Test python bindings
  CMakeLists.txt
  contrib/python-bindings/CMakeLists.txt
  contrib/python-bindings/source/CMakeLists.txt
  contrib/python-bindings/tests/CMakeLists.txt
  tests/CMakeLists.txt
Labels: Build system, Python

#9488 Add missing instantiations for DoFTools::extract_hanging_node_dofs
  source/dofs/dof_tools.inst.in
Labels: Reviewed and ready to merge, ready to test

#9216 Extend MatrixFree::get_dof_handler
  doc/news/changes/minor/20200102BrunoTurcksin
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
  source/matrix_free/matrix_free.inst.in
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#9472 Add function to print statistics over MPI for TimerOutput
  include/deal.II/base/timer.h
  source/base/mpi.cc
  source/base/timer.cc
  tests/base/timer_09.cc
  tests/base/timer_09.with_mpi=true.mpirun=2.output
  tests/base/timer_10.cc
  tests/base/timer_10.with_mpi=true.mpirun=2.output
Labels: Miscellaneous, Parallel distributed, ready to test

#9429 Add python bind for compute_aspect_ratio_of_cells
  contrib/python-bindings/include/mapping_wrapper.h
  contrib/python-bindings/include/triangulation_wrapper.h
  contrib/python-bindings/source/export_triangulation.cc
  contrib/python-bindings/source/mapping_wrapper.cc
  contrib/python-bindings/source/triangulation_wrapper.cc
Labels: Python, Reviewed and ready to merge, ready to test

#9492 Add new constructor to ArrayView
  doc/news/changes/minor/20200207PeterMunch
  include/deal.II/base/array_view.h
  tests/base/array_view_15.cc
  tests/base/array_view_15.output
Labels: Reviewed and ready to merge, ready to test

#9494 Matrixfree hold all faces to owned cells fix
  include/deal.II/matrix_free/dof_info.h
  include/deal.II/matrix_free/matrix_free.templates.h
  tests/matrix_free/face_setup_01.with_mpi=true.with_p4est=true.mpirun=1.output
  tests/matrix_free/face_setup_01.with_mpi=true.with_p4est=true.mpirun=2.output
Labels: Bug, Matrix-free, Reviewed and ready to merge, ready to test

#9160 ECL: add loop_cell_centric
  include/deal.II/matrix_free/matrix_free.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#9004 Add a check on whether LLD links shared object
  cmake/checks/check_02_compiler_features.cmake
Labels: Build system, ready to test

#9499 Remove most new in folder include/deal.II/matrix_free/
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/mapping_info.templates.h
  include/deal.II/matrix_free/matrix_free.templates.h
  include/deal.II/matrix_free/operators.h
Labels: Reviewed and ready to merge, ready to test

#9278 test DataOut set_cell_selection for multilevel cells
  include/deal.II/numerics/data_out.h
  source/numerics/data_out.cc
  tests/multigrid/mg_data_out_01.cc
  tests/multigrid/mg_data_out_01.output
  tests/multigrid/mg_data_out_02.cc
  tests/multigrid/mg_data_out_02.with_p4est=true.mpirun=2.output
  tests/multigrid/mg_data_out_02.with_p4est=true.mpirun=3.output
Labels: Reviewed and ready to merge, ready to test

#9237 make MueLu optional in Trilinos
  cmake/configure/configure_2_trilinos.cmake
  doc/external-libs/trilinos.html
  include/deal.II/base/config.h.in
  include/deal.II/lac/trilinos_precondition.h
  source/lac/trilinos_precondition_muelu.cc
  tests/lac/linear_operator_10.cc
  tests/lac/linear_operator_10.with_trilinos=on.with_64bit_indices=off.output.nomuelu
  tests/lac/linear_operator_10a.cc
  tests/lac/linear_operator_10a.with_trilinos=on.with_64bit_indices=off.output.nomuelu
  tests/mpi/muelu_periodicity.with_trilinos_with_muelu=on.with_64bit_indices=off.mpirun=3.output
  tests/mpi/muelu_periodicity.with_trilinos_with_muelu=on.with_64bit_indices=off.mpirun=5.output
  tests/mpi/muelu_periodicity.with_trilinos_with_muelu=on.with_64bit_indices=off.mpirun=7.output
  tests/trilinos/precondition_muelu_dgp.with_trilinos_with_muelu=on.with_64bit_indices=off.output
  tests/trilinos/precondition_muelu_q_iso_q1.with_trilinos_with_muelu=on.with_64bit_indices=off.output
  tests/trilinos/precondition_muelu_smoother.with_trilinos_with_muelu=on.with_64bit_indices=off.output
Labels: Reviewed and ready to merge, ready to test

#9500 Remove eps step 6
  examples/step-6/doc/results.dox
  examples/step-6/step-6.cc
Labels: Tutorials, ready to test

#9501 Correct the printed message output from ExcInvalidBoundaryFunction()
  doc/news/changes/minor/20200209JihuanTian
  include/deal.II/numerics/error_estimator.h
Labels: ready to test

#9473 Add Utilities::MPI::min_max_avg() for vectors
  doc/news/changes/minor/20200203PeterMunch
  include/deal.II/base/mpi.h
  source/base/mpi.cc
  tests/mpi/minmaxavg_vector_01.cc
  tests/mpi/minmaxavg_vector_01.mpirun=4.output
Labels: Parallel distributed, ready to test

#9507 Minor edit to step-6's results section.
  examples/step-6/doc/results.dox
Labels: Tutorials

#9512 Fix MueLu periodicity test
  tests/mpi/muelu_periodicity.cc
  tests/mpi/muelu_periodicity.with_trilinos_with_muelu=on.with_64bit_indices=off.mpirun=3.output
  tests/mpi/muelu_periodicity.with_trilinos_with_muelu=on.with_64bit_indices=off.mpirun=5.output
  tests/mpi/muelu_periodicity.with_trilinos_with_muelu=on.with_64bit_indices=off.mpirun=7.output
Labels: Tests

#9474 Add boundary id functionality to write_svg
  doc/doxygen/images/svg_flags.png
  doc/news/changes/minor/20200202Harper
  include/deal.II/grid/grid_out.h
  source/grid/grid_out.cc
  tests/grid/grid_out_svg_01.output
  tests/grid/grid_out_svg_02.output
  tests/grid/grid_out_svg_02.output.2
  tests/grid/grid_out_svg_02.output.avx512
  tests/grid/grid_out_svg_03.cc
  tests/grid/grid_out_svg_03.output
Labels: Miscellaneous, Post-processing, ready to test

#9451 step-47: switch the jump and average in one term of the scheme.
  examples/step-47/doc/intro.dox
  examples/step-47/step-47.cc
Labels: Tutorials

#9516 parallel::CellWeights: Capture values, not references.
  source/distributed/cell_weights.cc
Labels: Bug, Reviewed and ready to merge, ready to test

#9515 Remove some unused variable warnings in vectorization.h
  include/deal.II/base/vectorization.h
Labels: Reviewed and ready to merge, SIMD, ready to test

#9514 Remove MPI_COMM_WORLD as default argument in write_vtu_with_pvtu_record
  examples/step-18/step-18.cc
  examples/step-32/step-32.cc
  examples/step-37/step-37.cc
  examples/step-40/step-40.cc
  examples/step-42/step-42.cc
  examples/step-45/step-45.cc
  examples/step-48/step-48.cc
  examples/step-50/step-50.cc
  examples/step-55/step-55.cc
  examples/step-64/step-64.cu
  include/deal.II/base/data_out_base.h
  source/base/data_out_base.cc
Labels: Reviewed and ready to merge, ready to test

#9495 Convert step-14 from using eps/gnuplot to svg/vtu.
  examples/step-14/doc/results.dox
  examples/step-14/step-14.cc
Labels: Reviewed and ready to merge, ready to test

#9493 Convert step-30 from using eps/gnuplot to svg/vtu.
  examples/step-30/doc/results.dox
  examples/step-30/step-30.cc
Labels: Reviewed and ready to merge, ready to test

#9518 Use value semantics for const parameters with trivial small types
  include/deal.II/base/parsed_convergence_table.h
  include/deal.II/differentiation/ad/ad_helpers.h
  include/deal.II/differentiation/sd/symengine_number_types.h
  include/deal.II/differentiation/sd/symengine_tensor_operations.h
  include/deal.II/fe/fe_interface_values.h
  include/deal.II/meshworker/copy_data.h
  source/base/parsed_convergence_table.cc
  source/differentiation/sd/symengine_number_types.cc
  source/particles/particle_handler.cc
Labels: Reviewed and ready to merge, ready to test

#9523 Replace eps-generated figure by vtu-generated one in step-6.
  examples/step-6/doc/results.dox
Labels: Tutorials

#9519 Avoid calling into MPI functions with MinMaxAvg in serial
  source/base/mpi.cc
Labels: Miscellaneous, Reviewed and ready to merge, ready to test

#9524 FEEvaluation: Place exception about no block vector correctly
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#9525 Ensure to have valid quadrature point data for all SIMD lanes
  include/deal.II/matrix_free/mapping_info.templates.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#9522 Scale a graphic in the results section of step-14.
  examples/step-14/doc/results.dox
Labels: Tutorials

#9511 Indent script: Do not use --diff-filter=d
  contrib/utilities/indent_common.sh
Labels: Infrastructure

#9510 Add more python bindings
  contrib/python-bindings/include/manifold_wrapper.h
  contrib/python-bindings/include/tria_accessor_wrapper.h
  contrib/python-bindings/include/triangulation_wrapper.h
  contrib/python-bindings/source/export_manifold.cc
  contrib/python-bindings/source/export_tria_accessor.cc
  contrib/python-bindings/source/export_triangulation.cc
  contrib/python-bindings/source/manifold_wrapper.cc
  contrib/python-bindings/source/tria_accessor_wrapper.cc
  contrib/python-bindings/source/triangulation_wrapper.cc
  contrib/python-bindings/tests/triangulation_wrapper.py
  doc/news/changes/minor/20200211Grayver
Labels: ready to test

#9528 Use types::global_dof_index rather than unsigned int in MGTransfer
  source/multigrid/mg_transfer_internal.cc
Labels: Geometric multigrid, Parallel distributed, ready to test

#9536 Avoid nonlocal control flow since it's so hard to read.
  source/multigrid/mg_transfer_internal.cc
Labels: Reviewed and ready to merge, ready to test

#9534 Use a 64bit type in one other MGTransfer location
  source/multigrid/mg_transfer_internal.cc
Labels: Reviewed and ready to merge, ready to test

#9533 Use AssertThrow when LAPACK or other dependencies are not installed
  source/base/function_parser.cc
  source/base/tensor_function_parser.cc
  source/grid/grid_in.cc
  source/lac/tridiagonal_matrix.cc
Labels: ready to test

#9540 Fix overflow in tria.n_global_active_cells()
  source/distributed/tria_base.cc
Labels: Reviewed and ready to merge, ready to test

#9529 Add split_by_block() into IndexSet
  doc/news/changes/minor/20200214KatrinMang
  include/deal.II/base/index_set.h
  source/base/index_set.cc
  tests/base/index_set_31.cc
  tests/base/index_set_31.output
Labels: Reviewed and ready to merge, ready to test

#9548 Fix 64bit GridRefinement overflow
  include/deal.II/distributed/grid_refinement.h
  source/distributed/grid_refinement.cc
  source/distributed/grid_refinement.inst.in
Labels: ready to test

#9526 Add python version of step-49
  contrib/python-bindings/notebooks/index.ipynb
  contrib/python-bindings/notebooks/step-49.ipynb
  doc/news/changes/major/20200212Grayver
  examples/step-49/doc/intro.dox
  examples/step-49/step-49.ipynb
Labels: Reviewed and ready to merge, ready to test

#9561 Avoid using std::endl over '\n'.
  source/base/table_handler.cc
Labels: Reviewed and ready to merge, ready to test

#9559 Update documentation of SphericalManifold::normal_vector.
  source/grid/manifold_lib.cc
Labels: Documentation, ready to test

#9564 Make assertions to track state in FEEvaluation debug-only
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, Tests, ready to test

#9568 fix 64bit overflow in refine_and_coarsen_fixed_number
  include/deal.II/distributed/grid_refinement.h
  include/deal.II/grid/grid_refinement.h
  source/distributed/grid_refinement.cc
  source/distributed/grid_refinement.inst.in
  source/grid/grid_refinement.cc
  source/grid/grid_refinement.inst.in
Labels: ready to test

#9570 doxygen: do not remove multiline code comments
  doc/doxygen/scripts/program2doxygen
Labels: Documentation, Reviewed and ready to merge, ready to test

#9521 Remove one newline at beginning of timer statistics
  source/base/timer.cc
  tests/base/timer_09.with_mpi=true.mpirun=2.output
  tests/base/timer_10.with_mpi=true.mpirun=2.output
Labels: Miscellaneous, ready to test

#9572 improve documentation of MGTransferMatrixFree::interpolate_to_mg()
  include/deal.II/multigrid/mg_transfer_matrix_free.h
Labels: Documentation

#9567 CI: run matrix_free tests
  Jenkinsfile
Labels: ready to test

#9578 doxygen: replace DEAL_II_CONSTEXPR
  doc/doxygen/options.dox.in
Labels: Documentation

#9579 Add GeometryInfo::unit_tangential_vectors
  doc/news/changes/minor/20200228MartinKronbichler
  include/deal.II/base/geometry_info.h
  source/base/geometry_info.cc
  source/fe/mapping_fe_field.cc
  source/fe/mapping_manifold.cc
  source/fe/mapping_q_generic.cc
  tests/base/geometry_info_10.cc
  tests/base/geometry_info_10.output
Labels: Reviewed and ready to merge, Triangulation, ready to test
