Repository dealii/dealii, pull requests merged in 2020-01, with the labels that each got.

#9205 Use a range-based for loop.
  include/deal.II/base/thread_management.h
Labels: ready to test

#9208 Fix our TBB version check.
  cmake/configure/configure_1_threads.cmake
  cmake/modules/FindTBB.cmake
Labels: Build system, ready to test

#9209 Keep the 'dealii::' in 'using namespace dealii::'.
  doc/doxygen/scripts/filter
Labels: Documentation

#9211 Instantiate DoFTools::map_dofs_to_support_points() also for <1,3>.
  source/dofs/dof_tools.inst.in
Labels: ready to test

#9214 Add CellId::is_ancestor_of
  doc/news/changes/minor/20200102PeterMunch
  include/deal.II/grid/cell_id.h
  tests/grid/cell_id_06.cc
  tests/grid/cell_id_06.output
Labels: Triangulation, ready to test

#9155 ECL: make mapping of neighbor available
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/mapping_info.templates.h
Labels: Matrix-free, ready to test

#9215 Make DoFHandlerPolicy independent of p4est
  source/dofs/dof_handler_policy.cc
Labels: Parallel distributed, ready to test

#9218 Instantiate FETools::get_projection_matrix for float
  source/fe/fe_tools.inst.in
Labels: Finite Element, Reviewed and ready to merge, ready to test

#9223 Bug fix in PR #9155
  include/deal.II/matrix_free/mapping_info.templates.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#9224 Replace some DEAL_II_WITH_P4EST with DEAL_II_WITH_MPI
  source/dofs/dof_handler_policy.cc
Labels: Parallel distributed, Reviewed and ready to merge, ready to test

#9219 deprecate members in TimerOutput
  include/deal.II/base/timer.h
  tests/base/timer_03.cc
  tests/base/timer_07.cc
Labels: ready to test

#9230 Fix two bugs in matrix-free code
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/mapping_info.templates.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#9106 Make pft independent of p4est
  tests/fullydistributed_grids/copy_serial_tria_01.mpirun=1.output
  tests/fullydistributed_grids/copy_serial_tria_01.mpirun=5.output
  tests/fullydistributed_grids/copy_serial_tria_02.mpirun=1.output
  tests/fullydistributed_grids/copy_serial_tria_02.mpirun=5.output
  tests/fullydistributed_grids/copy_serial_tria_03.mpirun=1.output
  tests/fullydistributed_grids/copy_serial_tria_03.mpirun=5.output
  tests/fullydistributed_grids/copy_serial_tria_04.mpirun=1.output
  tests/fullydistributed_grids/copy_serial_tria_04.mpirun=4.output
  tests/fullydistributed_grids/copy_serial_tria_04.mpirun=5.output
  tests/fullydistributed_grids/copy_serial_tria_05.mpirun=9.output
  tests/fullydistributed_grids/copy_serial_tria_06.mpirun=5.output
Labels: Parallel distributed

#9234 doc: minor GridGenerator changes
  include/deal.II/grid/grid_generator.h
Labels: Documentation

#9236 Augment the documentation of GridGenerator::simplex().
  include/deal.II/grid/grid_generator.h
Labels: Documentation

#9204 mu_parser functions modified to use std random number generators
  doc/news/changes/minor/20191230RezaRastak
  source/base/function_parser.cc
  source/base/mu_parser_internal.cc
  source/base/tensor_function_parser.cc
  tests/base/function_parser_09.cc
  tests/base/function_parser_09.with_muparser=true.output
  tests/base/function_parser_10.cc
  tests/base/function_parser_10.with_muparser=true.output
Labels: ready to test

#9241 Mark some input arguments as 'const'.
  include/deal.II/dofs/dof_tools.h
  source/dofs/dof_tools.cc
  source/dofs/dof_tools.inst.in
Labels: ready to test

#9239 config.h: remove old p4est version logic
  include/deal.II/base/config.h.in
Labels: Reviewed and ready to merge, ready to test

#9244 jenkins: increase OSX timeout
  contrib/ci/Jenkinsfile.osx
Labels: Reviewed and ready to merge

#9245 Document out of memory issues with 'make -jN'.
  doc/readme.html
Labels: Documentation

#9206 Provide TaskGroup::size().
  doc/news/changes/minor/20191231Bangerth
  include/deal.II/base/thread_management.h
  tests/base/task_group_size.cc
  tests/base/task_group_size.with_threads=on.output
Labels: ready to test

#9073 Generate particles on support or quadrature points on other grid
  include/deal.II/particles/generators.h
  source/particles/generators.cc
  source/particles/generators.inst.in
  tests/particles/generators_07.cc
  tests/particles/generators_07.with_p4est=true.mpirun=1.output
  tests/particles/generators_07.with_p4est=true.mpirun=3.output
  tests/particles/generators_08.cc
  tests/particles/generators_08.with_p4est=true.mpirun=1.output
  tests/particles/generators_08.with_p4est=true.mpirun=3.output
Labels: Particles, Reviewed and ready to merge, ready to test

#9248 Mark 'Possibilities for extensions' as <h3>.
  examples/step-3/doc/results.dox
  examples/step-36/doc/results.dox
Labels: Tutorials

#9251 fixes a typo in step-4 incorrectly quoting the tutorial wherein the ZeroFunction as first introduced
  .mailmap
  examples/step-4/step-4.cc
Labels: Reviewed and ready to merge

#9256 fixes a redundant paragraph in Step-4 tutorial (since vtk format was already introduced in step-3)
  examples/step-4/step-4.cc
Labels: Reviewed and ready to merge, ready to test

#9235 Augment the UMFPACK error message.
  include/deal.II/lac/sparse_direct.h
Labels: Documentation, Reviewed and ready to merge, ready to test

#9242 replace some instances of Threads::Mutex with std::mutex
  include/deal.II/fe/fe_tools.templates.h
  source/base/logstream.cc
  source/base/polynomial.cc
  source/base/polynomials_raviart_thomas.cc
  source/base/polynomials_rt_bubbles.cc
Labels: Reviewed and ready to merge, ready to test

#9253 Adjust precision with which we output results in hp/crash_17.
  tests/hp/crash_17.cc
  tests/hp/crash_17.output
Labels: Reviewed and ready to merge, ready to test

#9257 Simplify dof_tools.inst.in
  source/dofs/dof_tools.inst.in
Labels: Reviewed and ready to merge, ready to test

#9262 In Step-5 tutorial, updates name of function being removed (make_grid _and_dofs -> make_grid)
  examples/step-5/step-5.cc
Labels: Reviewed and ready to merge

#9265 Move some code.
  source/base/data_out_base.cc
Labels: Post-processing, Reviewed and ready to merge, ready to test

#9258 shape_3rd_derivative* checks for update_3rd_derivatives
  include/deal.II/fe/fe_values.h
Labels: Reviewed and ready to merge, ready to test

#9254 Convert step-61 to use face loops with cell->face_iterators().
  examples/step-61/step-61.cc
Labels: Reviewed and ready to merge, ready to test

#9179 Add python interface for FunctionManifold
  contrib/python-bindings/include/function_wrapper.h
  contrib/python-bindings/include/manifold_wrapper.h
  contrib/python-bindings/source/export_manifold.cc
  contrib/python-bindings/source/manifold_wrapper.cc
  contrib/python-bindings/tests/manifold_wrapper.py
  contrib/python-bindings/tests/manifold_wrapper.vtk
  doc/news/changes/minor/20191217Grayver-2
  include/deal.II/grid/manifold_lib.h
  source/grid/manifold_lib.cc
Labels: ready to test

#9250 Update the discussion of HDF5 and R scripting in step-3.
  examples/step-3/doc/results.dox
Labels: Tutorials

#9277 Fix the dealcoloneq command.
  doc/doxygen/extra.sty
  doc/doxygen/scripts/mod_header.pl.in
Labels: Documentation

#9266 CMake: Check whether Trilinos has been configured with third-party libraries.
  cmake/configure/configure_2_trilinos.cmake
  tests/mpi/hp_step-4.with_trilinos=true.with_trilinos_with_mumps=true.mpirun=1.output
  tests/mpi/hp_step-4.with_trilinos=true.with_trilinos_with_mumps=true.mpirun=2.output
  tests/mpi/hp_step-4.with_trilinos=true.with_trilinos_with_mumps=true.mpirun=4.output
Labels: Build system, Reviewed and ready to merge, ready to test

#9240 Turn all for loops using "begin_active" into ranged-based ones
  include/deal.II/fe/fe_values.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/numerics/vector_tools.templates.h
  source/dofs/dof_tools.cc
  source/grid/grid_generator.cc
  source/grid/grid_out.cc
  source/grid/grid_tools.cc
  source/grid/grid_tools_dof_handlers.cc
  source/grid/tria.cc
  source/hp/dof_handler.cc
  source/multigrid/mg_tools.cc
  source/numerics/time_dependent.cc
Labels: Reviewed and ready to merge, ready to test

#9283 Remove tensor.cc
  source/base/CMakeLists.txt
  source/base/tensor.cc
  source/base/tensor.inst.in
Labels: ready to test

#9285 Avoid gcc-4.9.4 error
  source/grid/manifold_lib.cc
Labels: Manifold, ready to test

#9284 Fix \coloneq again.
  doc/doxygen/extra.sty
  doc/doxygen/scripts/mod_header.pl.in
Labels: Documentation

#9295 fixes stale documentation about boundary_object for hyper_ball function
  examples/step-6/step-6.cc
Labels: Documentation

#9290 fix write_vtu_in_parallel invalid file if partly empty
  doc/news/changes/minor/20200112TimoHeister
  source/base/data_out_base.cc
  tests/mpi/parallel_vtu_01.with_trilinos=true.mpirun=3.with_zlib=on.with_p4est=true.output
Labels: ready to test

#9289 Remove filtered_iterator include in step-18
  examples/step-18/step-18.cc
  include/deal.II/grid/filtered_iterator.h
Labels: ready to test

#9286 Introduce \jump and \average commands to be used in the documentation.
  doc/doxygen/extra.sty
  doc/doxygen/scripts/mod_header.pl.in
  examples/step-39/doc/intro.dox
  examples/step-39/step-39.cc
  examples/step-59/doc/intro.dox
  include/deal.II/fe/fe_interface_values.h
Labels: Documentation

#9310 Disentangle the dependency graph some more.
  examples/step-18/doc/builds-on
  examples/step-62/doc/builds-on
Labels: Tutorials

#9315 In step 6, removes the documentation sentences relating to quadrature formula degree since already done in Step-5
  examples/step-6/step-6.cc
Labels: Documentation

#9259 Implement jump_hessian and jump_3rd_derivative on FEInterfaceValues.
  include/deal.II/fe/fe_interface_values.h
  tests/feinterface/fe_interface_values_09.cc
  tests/feinterface/fe_interface_values_09.output
Labels: Finite Element, ready to test

#9318 converts l_2 to LaTeX code
  include/deal.II/base/point.h
Labels: Reviewed and ready to merge, ready to test

#9301 GridGenerator::half_hyper_shell warning
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
Labels: ready to test

#9111 step-71: the biharmonic equation.
  doc/doxygen/references.bib
  doc/doxygen/tutorial/tutorial.h.in
  examples/step-71/CMakeLists.txt
  examples/step-71/doc/builds-on
  examples/step-71/doc/intro.dox
  examples/step-71/doc/kind
  examples/step-71/doc/results.dox
  examples/step-71/doc/tooltip
  examples/step-71/step-71.cc
Labels: Reviewed and ready to merge, ready to test

#9297 Make GridTools::delete_duplicate_vertices() faster.
  doc/news/changes/minor/20200112DavidWells
  include/deal.II/grid/grid_tools.h
  source/grid/grid_tools.cc
Labels: Enhancement, Reviewed and ready to merge, ready to test

#9329 Better document an issue with curved boundaries.
  include/deal.II/grid/grid_generator.h
  include/deal.II/grid/grid_out.h
Labels: Documentation

#9178 Add a set of new python wrappers
  contrib/python-bindings/include/cell_accessor_wrapper.h
  contrib/python-bindings/include/mapping_wrapper.h
  contrib/python-bindings/include/point_wrapper.h
  contrib/python-bindings/include/triangulation_wrapper.h
  contrib/python-bindings/source/cell_accessor_wrapper.cc
  contrib/python-bindings/source/export_cell_accessor.cc
  contrib/python-bindings/source/export_mapping.cc
  contrib/python-bindings/source/export_point.cc
  contrib/python-bindings/source/export_triangulation.cc
  contrib/python-bindings/source/mapping_wrapper.cc
  contrib/python-bindings/source/point_wrapper.cc
  contrib/python-bindings/source/triangulation_wrapper.cc
  doc/news/changes/minor/20191217Grayver
Labels: Python, Reviewed and ready to merge, ready to test

#9333 Use @pre instead of @note in a number of places.
  include/deal.II/grid/grid_generator.h
Labels: Documentation

#9272 Make DoFTools::count_dofs_per_{component,block} return its data.
  doc/news/changes/minor/20200109Bangerth
  include/deal.II/dofs/dof_tools.h
  source/dofs/dof_tools.cc
Labels: ready to test

#9340 Lots of documentation fixes to Step-49 tutorial
  examples/step-49/doc/intro.dox
  examples/step-49/doc/results.dox
  examples/step-49/step-49.cc
Labels: Documentation

#9328 Fix the instantiations of GridOut::write_svg().
  doc/news/changes/minor/20200114Bangerth
  source/grid/grid_out.inst.in
Labels: Reviewed and ready to merge, ready to test

#9337 Fix some coverity complains
  contrib/python-bindings/source/manifold_wrapper.cc
  include/deal.II/base/mpi.h
  source/grid/grid_generator.cc
  source/lac/sparsity_pattern.cc
  source/lac/trilinos_sparse_matrix.cc
Labels: Reviewed and ready to merge, ready to test

#9288 Update constraints documentation module to reflect recent updates to step-6
  doc/doxygen/headers/constraints.h
Labels: Documentation

#9327 Better document gmsh's features.
  examples/step-49/doc/intro.dox
  include/deal.II/gmsh/utilities.h
Labels: Tutorials

#9345 Clarify comments about distort_random() in step-49.
  examples/step-49/doc/intro.dox
  examples/step-49/step-49.cc
Labels: Tutorials

#9344 Talk about mesh quality in step-6.
  examples/step-6/doc/results.dox
Labels: Tutorials

#9249 Replace Threads::mutex by std::mutex
  include/deal.II/base/parallel.h
  include/deal.II/fe/fe_poly_tensor.h
  include/deal.II/fe/fe_system.h
  include/deal.II/fe/mapping_fe_field.h
  include/deal.II/lac/block_matrix_base.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/lapack_full_matrix.h
  include/deal.II/lac/swappable_vector.h
  include/deal.II/matrix_free/dof_info.templates.h
Labels: ready to test

#9335 Simplify description in step-49.
  examples/step-49/step-49.cc
Labels: Tutorials, ready to test

#9348 Fix typo in step-49 doc about gmsh
  examples/step-49/doc/intro.dox
Labels: Documentation

#9096 cleanup typedefs in DataOut
  doc/news/changes/incompatibilities/20191125MatthiasMaier
  include/deal.II/numerics/data_out.h
  include/deal.II/numerics/data_out_dof_data.h
  include/deal.II/numerics/data_out_dof_data.templates.h
  source/numerics/data_out.cc
  tests/data_out/data_out_08.cc
Labels: Post-processing, Reviewed and ready to merge, ready to test

#9231 Simpler CellwiseInverseMassMatrix::apply() function
  doc/news/changes/minor/20200105MartinKronbichler
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/operators.h
  tests/matrix_free/inverse_mass_06.cc
  tests/matrix_free/inverse_mass_06.output
  tests/matrix_free/inverse_mass_07.cc
  tests/matrix_free/inverse_mass_07.output
Labels: Matrix-free, ready to test

#9359 Work around a doxygen bug that triggers in step-10.
  doc/doxygen/scripts/make_step.pl
Labels: Tutorials

#9342 Use the same color edges as for nodes in the tutorial graph.
  doc/doxygen/scripts/steps.pl
Labels: Tutorials

#9370 More work on the tutorial graph
  doc/doxygen/scripts/steps.pl
Labels: Tutorials

#9382 Don't print lines connecting different parts of the legend.
  doc/doxygen/scripts/steps.pl
Labels: Tutorials

#9381 Fix the fill color for the tutorial graph legend.
  doc/doxygen/scripts/steps.pl
Labels: Tutorials

#9373 remove unnecessary tutorial DAG edges
  examples/step-38/doc/builds-on
  examples/step-39/doc/builds-on
  examples/step-43/doc/builds-on
  examples/step-54/doc/builds-on
Labels: Documentation

#9385 Fix tests using DataOut::active_cell_iterator
  tests/data_out/data_out_08.cc
  tests/mpi/p4est_2d_constraintmatrix_04.cc
  tests/mpi/p4est_3d_constraintmatrix_03.cc
Labels: Reviewed and ready to merge, ready to test

#9007 Add copy_triangulation to parallel::fullydistributed::Triangulation
  include/deal.II/distributed/fully_distributed_tria.h
  source/distributed/fully_distributed_tria.cc
  source/distributed/fully_distributed_tria_util.inst.in
  tests/fullydistributed_grids/copy_serial_tria_07.cc
  tests/fullydistributed_grids/copy_serial_tria_07.mpirun=1.output
  tests/fullydistributed_grids/copy_serial_tria_07.mpirun=5.output
Labels: Parallel distributed, Reviewed and ready to merge, ready to test

#9380 Replace !has_children() by is_active().
  examples/step-33/step-33.cc
  include/deal.II/dofs/dof_accessor.templates.h
  include/deal.II/fe/fe_tools_extrapolate.templates.h
  include/deal.II/grid/filtered_iterator.h
  include/deal.II/matrix_free/face_setup_internal.h
  include/deal.II/meshworker/loop.h
  include/deal.II/meshworker/mesh_loop.h
  include/deal.II/multigrid/mg_transfer_matrix_free.h
  include/deal.II/numerics/data_out.h
  include/deal.II/numerics/error_estimator.templates.h
  source/distributed/shared_tria.cc
  source/distributed/tria.cc
  source/dofs/dof_accessor_get.cc
  source/dofs/dof_accessor_set.cc
  source/dofs/dof_handler_policy.cc
  source/dofs/dof_tools.cc
  source/dofs/dof_tools_sparsity.cc
  source/fe/fe_values.cc
  source/grid/grid_out.cc
  source/grid/grid_tools.cc
  source/grid/tria.cc
  source/grid/tria_accessor.cc
  source/hp/dof_handler.cc
  source/numerics/data_out.cc
Labels: Reviewed and ready to merge, ready to test

#9364 Rename methods in ConsensusAlgorithmProcess
  include/deal.II/base/mpi.h
  include/deal.II/base/mpi_compute_index_owner_internal.h
  include/deal.II/base/mpi_tags.h
  source/base/mpi.cc
Labels: Parallel distributed, Reviewed and ready to merge, ready to test

#9371 New compress/decompress using gzip.
  doc/news/changes/minor/20200117LucaHeltai
  include/deal.II/base/utilities.h
  source/base/utilities.cc
  tests/base/utilities_compress_decompress_01.cc
  tests/base/utilities_compress_decompress_01.with_zlib=true.output
Labels: Reviewed and ready to merge, ready for review, ready to test

#9389 Add assert to prevent floating point exception
  include/deal.II/base/mpi_compute_index_owner_internal.h
Labels: Parallel distributed, Reviewed and ready to merge, ready to test

#9075 Get set particle positions
  doc/news/changes/minor/20200110LucaHeltai
  include/deal.II/particles/particle_handler.h
  source/particles/particle_handler.cc
  tests/particles/set_particle_positions_01.cc
  tests/particles/set_particle_positions_01.with_p4est=true.with_trilinos=true.mpirun=1.output
  tests/particles/set_particle_positions_01.with_p4est=true.with_trilinos=true.mpirun=2.output
  tests/particles/set_particle_positions_02.cc
  tests/particles/set_particle_positions_02.with_p4est=true.mpirun=1.output
Labels: Particles, Reviewed and ready to merge, ready to test

#9399 Fix compiling for C++11
  source/distributed/fully_distributed_tria.cc
Labels: Reviewed and ready to merge, ready to test

#9404 CI: disable cxx14 for the serial linux build
  Jenkinsfile
Labels: Infrastructure, ready to test

#9400 Utilities::to_string -> std::to_string
  examples/step-10/step-10.cc
  include/deal.II/lac/block_indices.h
  include/deal.II/lac/read_write_vector.templates.h
  include/deal.II/lac/sparse_matrix.templates.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/numerics/data_out_dof_data.templates.h
  source/base/index_set.cc
  source/differentiation/ad/ad_drivers.cc
  source/differentiation/sd/symengine_tensor_operations.cc
  source/dofs/dof_renumbering.cc
  source/grid/grid_reordering.cc
  source/grid/manifold_lib.cc
  source/lac/petsc_parallel_sparse_matrix.cc
  source/lac/petsc_precondition.cc
  source/particles/particle.cc
Labels: C++11, Miscellaneous, Reviewed and ready to merge, ready to test

#9398 Fix 1D-bug in one version of make_flux_sparsity_pattern
  source/dofs/dof_tools_sparsity.cc
  source/dofs/dof_tools_sparsity.inst.in
  tests/dofs/dof_tools_24.cc
  tests/dofs/dof_tools_24.output
Labels: ready to test

#9401 Make channel limits consistent.
  include/deal.II/lac/la_parallel_vector.templates.h
Labels: ready to test

#9408 Clarify a channel limit.
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/la_parallel_vector.templates.h
Labels: Bug

#9195 Create new dealii::Triangulation::create_triangulation()
  include/deal.II/distributed/fully_distributed_tria.h
  include/deal.II/distributed/fully_distributed_tria_util.h
  include/deal.II/distributed/shared_tria.h
  include/deal.II/distributed/tria.h
  include/deal.II/grid/persistent_tria.h
  include/deal.II/grid/tria.h
  include/deal.II/grid/tria_description.h
  source/distributed/CMakeLists.txt
  source/distributed/fully_distributed_tria.cc
  source/distributed/shared_tria.cc
  source/distributed/tria.cc
  source/grid/CMakeLists.txt
  source/grid/persistent_tria.cc
  source/grid/tria.cc
  source/grid/tria_description.cc
  source/grid/tria_description.inst.in
  tests/fullydistributed_grids/copy_distributed_tria_01.cc
  tests/fullydistributed_grids/copy_distributed_tria_02.cc
  tests/fullydistributed_grids/copy_serial_tria_01.cc
  tests/fullydistributed_grids/copy_serial_tria_02.cc
  tests/fullydistributed_grids/copy_serial_tria_03.cc
  tests/fullydistributed_grids/copy_serial_tria_04.cc
  tests/fullydistributed_grids/copy_serial_tria_05.cc
  tests/fullydistributed_grids/copy_serial_tria_06.cc
  tests/fullydistributed_grids/copy_serial_tria_07.cc
  tests/fullydistributed_grids/copy_serial_tria_grouped_01.cc
  tests/matrix_free/parallel_multigrid_fullydistributed.cc
  tests/serialization/parallel_fullydistributed_construction_data_1.cc
Labels: Reviewed and ready to merge, ready to test

#9412 remove unused variable in step-12
  examples/step-12/step-12.cc
Labels: Reviewed and ready to merge, ready to test

#9309 FESeries: Added features to precalculate all matrices and serialize them.
  doc/news/changes/minor/20200116Fehling-1
  doc/news/changes/minor/20200116Fehling-2
  include/deal.II/fe/fe_series.h
  include/deal.II/hp/q_collection.h
  source/fe/fe_series_fourier.cc
  source/fe/fe_series_legendre.cc
  tests/serialization/fe_series_01.cc
  tests/serialization/fe_series_01.output
  tests/serialization/fe_series_02.cc
  tests/serialization/fe_series_02.output
Labels: Reviewed and ready to merge, ready to test

#9417 Clarify what the graph represents.
  doc/doxygen/tutorial/tutorial.h.in
Labels: Tutorials

#9416 Mention namespaces in step-20.
  examples/step-20/step-20.cc
Labels: Tutorials, ready to test

#9402 Rename step-71 to step-47.
  doc/doxygen/tutorial/tutorial.h.in
  doc/news/changes/major/20200115step47
  examples/step-47/CMakeLists.txt
  examples/step-47/doc/builds-on
  examples/step-47/doc/intro.dox
  examples/step-47/doc/kind
  examples/step-47/doc/results.dox
  examples/step-47/doc/tooltip
  examples/step-47/step-47.cc
Labels: Tutorials, ready to test

#9414 step-12: use add_data_vector with DoFHandler
  examples/step-12/step-12.cc
Labels: ready to test

#9423 removes an unwanted include file manifold_lib.h from step-2
  examples/step-2/step-2.cc
Labels: ready to test

#9421 Improve an error message.
  include/deal.II/numerics/derivative_approximation.h
Labels: ready to test

#9415 Introduce GeometryInfo::face_indices()
  include/deal.II/base/geometry_info.h
  include/deal.II/dofs/dof_accessor.templates.h
  include/deal.II/grid/tria_accessor.templates.h
  include/deal.II/matrix_free/face_setup_internal.h
  include/deal.II/matrix_free/matrix_free.templates.h
  include/deal.II/matrix_free/shape_info.templates.h
  include/deal.II/meshworker/dof_info.h
  include/deal.II/meshworker/loop.h
  include/deal.II/multigrid/mg_constrained_dofs.h
  include/deal.II/numerics/vector_tools.templates.h
  source/base/data_out_base.cc
  source/base/polynomials_bernardi_raugel.cc
  source/base/quadrature_lib.cc
  source/distributed/tria.cc
  source/dofs/dof_tools.cc
  source/fe/fe_abf.cc
  source/fe/fe_bdm.cc
  source/fe/fe_bernardi_raugel.cc
  source/fe/fe_face.cc
  source/fe/fe_raviart_thomas.cc
  source/fe/mapping_q_generic.cc
  source/grid/grid_generator.cc
  source/grid/grid_in.cc
  source/grid/grid_out.cc
  source/grid/grid_tools.cc
  source/grid/grid_tools_dof_handlers.cc
  source/grid/tria.cc
  source/hp/dof_handler.cc
  source/multigrid/mg_tools.cc
  source/opencascade/utilities.cc
Labels: ready to test

#9410 Use std::to_string() instead of boost lexical_cast.
  source/base/utilities.cc
Labels: Reviewed and ready to merge, ready to test

#9419 Remove seemingly unused code in fe_poly.cc
  source/fe/fe_poly.cc
Labels: ready to test

#9413 Add a note to two .h files about the design pattern used there.
  include/deal.II/fe/fe_values.h
  include/deal.II/numerics/data_out_dof_data.h
Labels: Documentation

#9388 Implement GridGenerator::replicate_triangulation().
  doc/doxygen/images/replicated_tria_2d.png
  doc/doxygen/images/replicated_tria_3d.png
  doc/news/changes/minor/20200113DavidWellsVictorZheng
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  source/grid/grid_generator.inst.in
  tests/grid/replicate_triangulation_01.cc
  tests/grid/replicate_triangulation_01.output
  tests/grid/replicate_triangulation_02.cc
  tests/grid/replicate_triangulation_02.output
Labels: Enhancement, Reviewed and ready to merge, ready to test

#9433 Fix gcc 4.9.4 warning
  include/deal.II/base/geometry_info.h
Labels: Reviewed and ready to merge, ready to test

#9431 Fix particle probability density mpi problem
  .mailmap
  source/particles/generators.cc
  tests/particles/generators_09.cc
  tests/particles/generators_09.with_p4est=true.mpirun=3.output
  tests/particles/generators_10.cc
  tests/particles/generators_10.with_p4est=true.mpirun=3.output
  tests/particles/generators_11.cc
  tests/particles/generators_11.with_p4est=true.mpirun=3.output
  tests/particles/generators_12.cc
  tests/particles/generators_12.with_p4est=true.mpirun=3.output
Labels: Reviewed and ready to merge, ready to test

#9436 Remove unused included file from step-6
  examples/step-6/step-6.cc
Labels: Reviewed and ready to merge, ready to test

#9432 Fix remaining issues for #9195
  include/deal.II/grid/tria.h
  include/deal.II/grid/tria_description.h
  source/grid/tria_description.cc
Labels: Parallel distributed, Reviewed and ready to merge, ready to test

#9430 Fix ParameterHandler::read_xml_recursively for actions
  include/deal.II/base/parameter_handler.h
  source/base/parameter_handler.cc
  tests/parameter_handler/parameter_handler_read_json.cc
  tests/parameter_handler/parameter_handler_read_json.output
  tests/parameter_handler/parameter_handler_read_xml_error_01.output
  tests/parameter_handler/parameter_handler_read_xml_error_02.cc
  tests/parameter_handler/parameter_handler_read_xml_error_02.output
  tests/parameter_handler/parameter_handler_read_xml_error_04.cc
  tests/parameter_handler/parameter_handler_read_xml_error_04.output
Labels: Reviewed and ready to merge, ready to test

#9437 Update uses of compute() to evaluate()
  include/deal.II/base/polynomial_space.h
  include/deal.II/base/polynomials_adini.h
  include/deal.II/base/polynomials_rannacher_turek.h
  include/deal.II/base/tensor_product_polynomials.h
  include/deal.II/base/tensor_product_polynomials_bubbles.h
  include/deal.II/base/tensor_product_polynomials_const.h
  source/base/polynomials_adini.cc
Labels: Reviewed and ready to merge, ready to test

#9263 ParameterHandler in unsorted order
  doc/news/changes/minor/20200128PasqualeClaudioAfrica
  include/deal.II/base/parameter_handler.h
  source/base/parameter_handler.cc
  tests/parameter_handler/multiple_parameter_loop_01.output
  tests/parameter_handler/multiple_parameter_loop_02.output
  tests/parameter_handler/parameter_acceptor_02.output
  tests/parameter_handler/parameter_acceptor_05.output
  tests/parameter_handler/parameter_handler_3_with_sorting_01.cc
  tests/parameter_handler/parameter_handler_3_with_sorting_01.output
  tests/parameter_handler/parameter_handler_read_json.output
  tests/parameter_handler/parameter_handler_read_xml.output
  tests/parameter_handler/parameter_handler_write_json.output
  tests/parameter_handler/parameter_handler_write_section_xml.output
  tests/parameter_handler/parameter_handler_write_xml.output
  tests/parameter_handler/patterns_06.output
Labels: Reviewed and ready to merge, ready to test

#9443 make two ParameterHandler members local to .cc
  include/deal.II/base/parameter_handler.h
  source/base/parameter_handler.cc
Labels: Reviewed and ready to merge, ready to test

#9171 Symbolic function.
  doc/news/changes/major/20191214LucaHeltai
  include/deal.II/base/function_parser.h
  include/deal.II/base/symbolic_function.h
  include/deal.II/base/symbolic_function.templates.h
  source/base/CMakeLists.txt
  source/base/symbolic_function.cc
  source/base/symbolic_function.inst.in
  tests/base/symbolic_function_01.cc
  tests/base/symbolic_function_01.with_symengine=true.output
  tests/base/symbolic_function_02.cc
  tests/base/symbolic_function_02.with_symengine=true.output
  tests/base/symbolic_function_03.cc
  tests/base/symbolic_function_03.with_symengine=true.output
  tests/base/symbolic_function_04.cc
  tests/base/symbolic_function_04.with_symengine=true.output
Labels: Reviewed and ready to merge, Symbolic differentiation

#9407 make_flux_sparsity_pattern with flux couplings on a subset of the faces
  doc/news/changes/minor/20200128SimonSticko
  include/deal.II/dofs/dof_tools.h
  source/dofs/dof_tools_sparsity.cc
  source/dofs/dof_tools_sparsity.inst.in
  tests/dofs/dof_tools_25.cc
  tests/dofs/dof_tools_25.output
Labels: ready to test

#9156 ECL: add partitioners
  include/deal.II/matrix_free/dof_info.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
  tests/matrix_free/partitioner_01.cc
  tests/matrix_free/partitioner_01.with_mpi=true.with_p4est=true.mpirun=2.output
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#9447 Update PolynomialsAdini to derive from ScalarPolynomialsBase
  include/deal.II/base/polynomials_adini.h
  include/deal.II/base/scalar_polynomials_base.h
  source/base/polynomials_adini.cc
  tests/base/polynomials_adini_01.cc
  tests/base/polynomials_adini_01.output
Labels: Reviewed and ready to merge, ready to test

#9445 Add ParameterHandler::subsection_path_exists
  doc/news/changes/minor/20200129PasqualeClaudioAfrica
  include/deal.II/base/parameter_handler.h
  source/base/parameter_handler.cc
  tests/parameter_handler/parameter_handler_subsection_exists.cc
  tests/parameter_handler/parameter_handler_subsection_exists.output
Labels: Reviewed and ready to merge, ready to test

#9434 Further changes to ParameterHandler::parse_input_from_json
  doc/news/changes/minor/20200127PeterMunch-1
  doc/news/changes/minor/20200127PeterMunch-2
  include/deal.II/base/parameter_handler.h
  source/base/parameter_handler.cc
  tests/parameter_handler/parameter_handler_read_json_02.cc
  tests/parameter_handler/parameter_handler_read_json_02.output
  tests/parameter_handler/prm/parameter_handler_read_json_02.prm
Labels: ready to test

#9448 Update GridGenerator::half_hyper_shell documentation for correctness
  include/deal.II/grid/grid_generator.h
  tests/grid/grid_generator_half_hyper_shell.cc
  tests/grid/grid_generator_half_hyper_shell.output
Labels: Reviewed and ready to merge, ready to test

#9449 Avoid an internal compiler error in gcc 7.4.0.
  include/deal.II/matrix_free/matrix_free.templates.h
Labels: Reviewed and ready to merge, ready to test

#9450 Avoid a few warnings about unused variables.
  source/base/polynomials_adini.cc
Labels: Reviewed and ready to merge, ready to test

#9454 check MPI return value in one location
  source/base/mpi.cc
Labels: Reviewed and ready to merge, ready to test
