Repository dealii/dealii, pull requests merged in 2020-08, with the labels that each got.

#10757 CI: add tester for simplex tests
  .github/workflows/linux.yml
Labels: Reviewed and ready to merge, Tests

#10779 Add face_no to methods of FiniteElements
  include/deal.II/dofs/dof_accessor.templates.h
  include/deal.II/fe/fe.h
  include/deal.II/fe/fe_bernstein.h
  include/deal.II/fe/fe_dgp.h
  include/deal.II/fe/fe_dgp_monomial.h
  include/deal.II/fe/fe_dgp_nonparametric.h
  include/deal.II/fe/fe_dgq.h
  include/deal.II/fe/fe_enriched.h
  include/deal.II/fe/fe_face.h
  include/deal.II/fe/fe_nedelec.h
  include/deal.II/fe/fe_nothing.h
  include/deal.II/fe/fe_q_base.h
  include/deal.II/fe/fe_q_hierarchical.h
  include/deal.II/fe/fe_raviart_thomas.h
  include/deal.II/fe/fe_system.h
  include/deal.II/fe/fe_trace.h
  source/fe/fe.cc
  source/fe/fe_bernstein.cc
  source/fe/fe_dgp.cc
  source/fe/fe_dgp_monomial.cc
  source/fe/fe_dgp_nonparametric.cc
  source/fe/fe_dgq.cc
  source/fe/fe_enriched.cc
  source/fe/fe_face.cc
  source/fe/fe_nedelec.cc
  source/fe/fe_nothing.cc
  source/fe/fe_q_base.cc
  source/fe/fe_q_hierarchical.cc
  source/fe/fe_raviart_thomas_nodal.cc
  source/fe/fe_system.cc
  source/fe/fe_trace.cc
Labels: Finite Element, ready to test

#10780 Convert all face-related data structures of FiniteElement to vectors
  include/deal.II/fe/fe.h
  source/fe/fe.cc
  source/fe/fe_abf.cc
  source/fe/fe_bdm.cc
  source/fe/fe_enriched.cc
  source/fe/fe_face.cc
  source/fe/fe_nedelec.cc
  source/fe/fe_p1nc.cc
  source/fe/fe_q_base.cc
  source/fe/fe_q_hierarchical.cc
  source/fe/fe_raviart_thomas.cc
  source/fe/fe_raviart_thomas_nodal.cc
  source/fe/fe_rt_bubbles.cc
  source/fe/fe_system.cc
  source/fe/fe_trace.cc
  source/simplex/fe_lib.cc
Labels: Finite Element, ready to test

#10773 CI: change git depth for indent worker
  .github/workflows/indent.yml
Labels: Reviewed and ready to merge

#10752 Improve memory behavior of the BiCGStab solver.
  include/deal.II/lac/solver_bicgstab.h
Labels: Reviewed and ready to merge, ready to test

#10776 Refactor DoFHandlerImplementation::reserve_space for 3D
  source/dofs/dof_handler.cc
Labels: DoFs, ready to test

#10787 Jenkinsfile: convert tabs to spaces
  Jenkinsfile
Labels: ready to test

#10785 Fix MPIEXEC detection again.
  cmake/macros/macro_deal_ii_pickup_tests.cmake
Labels: Build system, Reviewed and ready to merge, ready to test

#9973 make ARKode ODE solver use DiscreteTime internally
  include/deal.II/sundials/arkode.h
  source/sundials/arkode.cc
  tests/sundials/harmonic_oscillator_05.output
  tests/sundials/harmonic_oscillator_06.output
Labels: Reviewed and ready to merge, ready to test

#10788 fix dof_accessor warning
  include/deal.II/dofs/dof_accessor.templates.h
Labels: Reviewed and ready to merge, ready to test

#10789 Simplex action: load metis and be verbose on failure
  .github/workflows/linux.yml
Labels: Tests

#10782 Fix step-18.
  source/grid/grid_refinement.cc
  tests/sharedtria/refine_and_coarsen_01.cc
  tests/sharedtria/refine_and_coarsen_01.mpirun=3.output
Labels: Bug, Parallel shared, ready to test

#10775 Simplify the usage of ensure_existence_of_dof_identities
  source/dofs/dof_handler_policy.cc
Labels: DoFs, Reviewed and ready to merge, hp, ready to test

#10701 Generalize DataOut::write_vtk for simplex mesh
  include/deal.II/base/data_out_base.h
  include/deal.II/numerics/data_out_dof_data.templates.h
  source/base/data_out_base.cc
  source/numerics/data_out.cc
  source/simplex/fe_lib.cc
  tests/simplex/data_out_write_vtk_01.cc
  tests/simplex/data_out_write_vtk_01.with_simplex_support=on.output
Labels: Post-processing, ready to test

#10777 Introduce FiniteElementData::max_dofs_per_quad()
  include/deal.II/fe/fe_base.h
  include/deal.II/hp/fe_collection.h
  source/dofs/dof_handler_policy.cc
  source/fe/fe_data.cc
Labels: Finite Element, ready to test

#10792 fix tests/simplex/data_out_write_vtk_01
  tests/simplex/data_out_write_vtk_01.cc
Labels: Reviewed and ready to merge

#10778 Generalize FiniteElementData s.t. faces can different nr. of dofs
  include/deal.II/fe/fe_base.h
  source/fe/fe_data.cc
Labels: Finite Element, ready to test

#10795 Fix typo in VectorTools::interpolate
  include/deal.II/numerics/vector_tools_interpolate.h
Labels: Documentation

#10796 Fix Warray-bounds warnings
  source/fe/mapping_fe.cc
Labels: ready to test

#10800 Simplify some string handling in an error message.
  source/particles/particle.cc
Labels: Reviewed and ready to merge, ready to test

#10802 Avoid a couple of places where we explicitly use 'new'.
  include/deal.II/lac/la_parallel_vector.templates.h
Labels: Reviewed and ready to merge, ready to test

#10803 Fix bug in DataPostprocessorTensor.
  doc/news/changes/minor/20200806Bangerth
  source/numerics/data_postprocessor.cc
  tests/data_out/data_out_postprocessor_tensor_02.cc
  tests/data_out/data_out_postprocessor_tensor_02.output
Labels: Reviewed and ready to merge, ready to test

#10805 Shrink the output of a test drastically.
  tests/data_out/data_out_postprocessor_tensor_01.cc
  tests/data_out/data_out_postprocessor_tensor_01.output
Labels: Reviewed and ready to merge, ready to test

#10799 Drop cuda 9
  cmake/configure/configure_1_cuda.cmake
  doc/external-libs/cuda.html
  doc/news/changes/incompatibilities/20200805Turcksin
Labels: Reviewed and ready to merge, ready to test

#10793 Fix CUDA 11 build
  include/deal.II/base/array_view.h
  include/deal.II/lac/cuda_sparse_matrix.h
  source/lac/cuda_sparse_matrix.cu
  tests/cuda/sparse_matrix_01.cu
Labels: GPU, Reviewed and ready to merge, ready to test

#10808 Rename two variables in MF
  include/deal.II/matrix_free/face_setup_internal.h
Labels: Matrix-free, ready to test

#10806 Fix another bug with DataPostprocessorTensor
  source/numerics/data_postprocessor.cc
  tests/data_out/data_out_postprocessor_tensor_01.output
  tests/data_out/data_out_postprocessor_tensor_02.output
Labels: Reviewed and ready to merge, ready to test

#10810 Work on MatrixFreeFunctions::FaceToCellTopology::face_orientation
  include/deal.II/matrix_free/face_info.h
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#10811 Merge implementation of gather_evaluate and integrate_scatter
  include/deal.II/matrix_free/evaluation_kernels.h
Labels: Matrix-free, ready to test

#10794 Save face type in quad_dof_identities
  source/dofs/dof_handler_policy.cc
Labels: ready to test

#10809 ECL: Merge gather and adjust_for_face_orientation
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/shape_info.h
  include/deal.II/matrix_free/shape_info.templates.h
Labels: Matrix-free, ready to test

#10762 MF mapping info: Avoid invalid access of some face-data-by-cells
  include/deal.II/matrix_free/mapping_info.templates.h
Labels: Matrix-free, ready to test

#10801 Add CUDA 10.2 CI build check
  .github/workflows/linux.yml
  examples/step-64/step-64.cu
  source/particles/generators.cc
  source/particles/particle_handler.cc
Labels: GPU, ready to test

#10815 Fix a few typos
  include/deal.II/distributed/shared_tria.h
  include/deal.II/distributed/tria.h
  include/deal.II/grid/persistent_tria.h
Labels: Documentation, Reviewed and ready to merge

#10813 Fix installation of files of step-49
  examples/CMakeLists.txt
Labels: Reviewed and ready to merge, Tutorials, ready to test

#10814 Allow AffineConstraints argument to MGTools::make_sparsity_pattern
  doc/news/changes/minor/20200811MartinKronbichler
  include/deal.II/multigrid/mg_tools.h
  source/multigrid/mg_tools.cc
  source/multigrid/mg_tools.inst.in
  tests/multigrid/step-16-08.cc
  tests/multigrid/step-16-08.output
Labels: Geometric multigrid, ready to test

#10817 Add back asserts in create_triangulation
  source/grid/tria.cc
Labels: Reviewed and ready to merge, Triangulation, ready to test

#10816 ECL: Generalize process_and_io
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, ready to test

#10784 Use face_no in FE
  include/deal.II/fe/fe.h
  include/deal.II/fe/fe_poly_face.templates.h
  include/deal.II/fe/fe_system.h
  include/deal.II/fe/fe_tools.h
  include/deal.II/fe/fe_tools.templates.h
  include/deal.II/fe/fe_tools_extrapolate.templates.h
  source/fe/fe.cc
  source/fe/fe_abf.cc
  source/fe/fe_bdm.cc
  source/fe/fe_bernstein.cc
  source/fe/fe_enriched.cc
  source/fe/fe_face.cc
  source/fe/fe_nedelec.cc
  source/fe/fe_nedelec_sz.cc
  source/fe/fe_poly_tensor.cc
  source/fe/fe_q_base.cc
  source/fe/fe_q_hierarchical.cc
  source/fe/fe_raviart_thomas.cc
  source/fe/fe_raviart_thomas_nodal.cc
  source/fe/fe_rt_bubbles.cc
  source/fe/fe_system.cc
  source/fe/fe_tools.inst.in
  source/fe/fe_trace.cc
Labels: Finite Element, ready to test

#10824 Fix typo
  include/deal.II/grid/grid_generator.h
Labels: Documentation, Reviewed and ready to merge

#10093 Fix if-statements with check_for_distorted_cells.
  source/grid/tria.cc
  tests/bits/distorted_cells_01.cc
  tests/bits/distorted_cells_01.debug.output
  tests/bits/distorted_cells_02.cc
  tests/bits/distorted_cells_02.debug.output
  tests/bits/distorted_cells_07.cc
  tests/bits/distorted_cells_07.debug.output
Labels: Reviewed and ready to merge, ready to test

#10818 Inform memory leak of sacado_rad_fad in doc.
  doc/doxygen/headers/automatic_and_symbolic_differentiation.h
  include/deal.II/differentiation/ad/ad_number_types.h
Labels: Automatic differentiation, Documentation

#10825 Avoid trailing whitespace check to modify timestamps unnecessarily
  contrib/utilities/indent_common.sh
Labels: ready to test

#10828 Improve performance of ReferenceCell::Info::get_cell
  include/deal.II/grid/reference_cell.h
Labels: Triangulation, ready to test

#10827 MF: Fix PBC in the case of non-standard orientation
  include/deal.II/matrix_free/face_setup_internal.h
  tests/matrix_free/pbc_orientation_01.cc
  tests/matrix_free/pbc_orientation_01.output
Labels: Bug, Matrix-free, Reviewed and ready to merge, ready to test

#10829 Add changelog on EvaluationFlags
  doc/news/changes/minor/20200605Heister
Labels: Documentation, Matrix-free

#10821 ECL: enable contiguous data access
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/fe_evaluation.h
  tests/matrix_free/ecl_02.cc
  tests/matrix_free/ecl_02.output
Labels: Matrix-free, ready for review, ready to test

#10402 Remove pointers of pointers in FEEvaluation
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, ready to test

#10831 Fix bug in FEFaceEvaluationSelector::process_and_io
  include/deal.II/matrix_free/evaluation_kernels.h
Labels: Bug, Matrix-free, ready to test

#10836 DataOut::write_vtu_with_pvtu_record(): prints the path name if file cannot be opened
  source/base/data_out_base.cc
  tests/data_out/write_vtu_with_pvtu_record_no_folder_01.cc
  tests/data_out/write_vtu_with_pvtu_record_no_folder_01.mpirun=1.output
  tests/data_out/write_vtu_with_pvtu_record_no_folder_01.mpirun=2.output
Labels: ready to test

#10837 Ignore differences in line endings on Windows and Linux.
  cmake/scripts/run_test.sh
Labels: Reviewed and ready to merge, ready to test

#10781 Simplify some code.
  include/deal.II/dofs/dof_accessor.templates.h
Labels: Reviewed and ready to merge, ready to test

#10839 Move line
  include/deal.II/base/memory_space.h
Labels: Reviewed and ready to merge, ready to test

#10841 Add some brackets
  source/multigrid/mg_transfer_matrix_free.cc
Labels: Reviewed and ready to merge, ready to test

#10838 Destroy tmp matrix in mmult.
  source/lac/petsc_matrix_base.cc
Labels: ready to test

#10842 Added docker file for master.
  .github/workflows/docker.yml
  contrib/docker/Dockerfile
Labels: Infrastructure

#10846 Update GridTools::transform for use with simplex meshes
  doc/news/changes/minor/20200826PasqualeAfrica
  include/deal.II/grid/grid_tools.h
Labels: ready to test

#10364 Move template definitions from hdf5.cc to hdf5.h
  doc/news/changes/minor/20200814GarciaSanchez
  include/deal.II/base/hdf5.h
  source/base/CMakeLists.txt
  source/base/hdf5.cc
  source/base/hdf5.inst.in
Labels: ready to test

#10851 Fix converted type rank when a SymmetricTensor is contracted with a Tensor
  include/deal.II/base/symmetric_tensor.h
  tests/tensors/symmetric_tensor_45.cc
  tests/tensors/symmetric_tensor_45.output
Labels: Bug, ready to test

#10820 Remove n_components template argument from FEEvaluationImpl
  include/deal.II/matrix_free/evaluation_flags.h
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/evaluation_selector.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/mapping_info.templates.h
  include/deal.II/matrix_free/operators.h
  source/fe/mapping_q_generic.cc
  source/matrix_free/evaluation_selector.inst.in
  source/multigrid/mg_transfer_matrix_free.cc
Labels: Matrix-free, ready to test

#10854 Fix some type limit warnings in TensorProductPolynomials.
  include/deal.II/base/tensor_product_polynomials.h
  source/base/tensor_product_polynomials.cc
Labels: Miscellaneous, ready to test

#10857 Fix warnings when compiling with CUDA
  include/deal.II/base/tensor.h
  include/deal.II/grid/tria_objects.h
Labels: GPU, ready to test

#10845 Do not forget to set the property pool of a particle 2
  source/particles/particle_handler.cc
  tests/particles/properties_03.cc
  tests/particles/properties_03.output
Labels: Reviewed and ready to merge, ready to test

#10855 Fix some warnings in BoundingBox.
  include/deal.II/base/bounding_box.h
  source/base/bounding_box.cc
Labels: Miscellaneous, Reviewed and ready to merge, ready to test

#10853 Use contiguous arrays for some polynomial classes.
  source/base/tensor_product_polynomials.cc
Labels: Miscellaneous, ready to test

#10861 Attempt to work around a compiler warning.
  include/deal.II/lac/affine_constraints.templates.h
Labels: Reviewed and ready to merge, ready to test

#10786 jenkins: use Og on tester
  Jenkinsfile
  bundled/boost-1.70.0/include/boost/archive/iterators/istream_iterator.hpp
Labels: Do not merge :skull_and_crossbones:, WIP :warning:, ready to test
