Repository dealii/dealii, pull requests merged in 2020-12, with the labels that each got.

#11271 Enable TriaAccessor::diameter() for wedges
  include/deal.II/grid/tria_accessor.templates.h
Labels: ready to test

#11285 Better document TriaAccessor::diagonal().
  include/deal.II/grid/tria_accessor.h
Labels: Documentation, Reviewed and ready to merge, ready to test

#11284 Simplify the computation of the diagonal.
  include/deal.II/grid/tria_accessor.templates.h
Labels: Reviewed and ready to merge, ready to test

#11286 Mark some variables as constexpr.
  include/deal.II/base/std_cxx17/cmath.h
Labels: Reviewed and ready to merge, ready to test

#11274 Move two classes into an internal namespace.
  doc/news/changes/incompatibilities/20201129Bangerth
  include/deal.II/lac/affine_constraints.h
  tests/lac/is_block_matrix.cc
Labels: ready to test

#11235 Add Poisson test: MatrixFree + DG + simplex mesh
  tests/simplex/matrix_free_03.cc
  tests/simplex/matrix_free_03.with_simplex_support=on.output
Labels: ready for review, ready to test

#11287 Enable TriaAccessor::diameter() for wedges
  include/deal.II/grid/tria_accessor.templates.h
Labels: ready for review, ready to test

#11289 Add missing override
  include/deal.II/multigrid/mg_transfer_global_coarsening.h
Labels: Geometric multigrid, Reviewed and ready to merge, ready to test

#11279 Expand on an explanation in step-40.
  examples/step-40/step-40.cc
Labels: ready to test

#11220 Created Legacy namespaces with copies of ...
  doc/news/changes/incompatibilities/20201120Fehling
  include/deal.II/distributed/solution_transfer.h
  include/deal.II/numerics/data_out.h
  include/deal.II/numerics/data_out_dof_data.h
  include/deal.II/numerics/data_out_faces.h
  include/deal.II/numerics/data_out_rotation.h
  include/deal.II/numerics/fe_field_function.h
  include/deal.II/numerics/solution_transfer.h
  source/numerics/fe_field_function.cc
  source/numerics/fe_field_function.inst.in
Labels: Reviewed and ready to merge, ready to test

#11293 Use inline functions instead of constexpr variables.
  include/deal.II/base/std_cxx17/cmath.h
Labels: Reviewed and ready to merge, ready to test

#11290 MatrixFree: accept shmem communicator neq MPI_COMM_SELF
  include/deal.II/matrix_free/matrix_free.templates.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#11291 Fix lexicographic_numbering for vector-valued Simplex::FE_Q and FE_DGQ
  include/deal.II/matrix_free/shape_info.templates.h
Labels: Matrix-free, ready to test

#11267 Introduce FE_Wedge
  include/deal.II/grid/reference_cell.h
  include/deal.II/simplex/fe_lib.h
  include/deal.II/simplex/polynomials.h
  source/simplex/fe_lib.cc
  source/simplex/fe_lib.inst.in
  source/simplex/polynomials.cc
  tests/simplex/wedge_01.cc
  tests/simplex/wedge_01.with_simplex_support=on.output
Labels: Discussion, Finite Element, ready to test

#11268 Introduce QGaussWedge
  include/deal.II/simplex/quadrature_lib.h
  source/simplex/quadrature_lib.cc
Labels: Quadrature, ready to test

#11283 Use boost implementation of legendre polynomials instead of gsl.
  cmake/checks/check_01_cxx_features.cmake
  include/deal.II/base/std_cxx17/cmath.h
  source/fe/fe_series_legendre.cc
Labels: ready to test

#11260 MatrixFree: split up ranges according to active_fe_indices
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
  tests/simplex/matrix_free_02.cc
  tests/simplex/matrix_free_range_iteration_01.cc
  tests/simplex/matrix_free_range_iteration_01.output
Labels: Matrix-free, Reviewed and ready to merge, hp, ready to test

#11296 Fix namespace
  include/deal.II/matrix_free/shape_info.templates.h
Labels: High Priority :warning:, Reviewed and ready to merge, ready to test

#11295 Enable GridTools:min/max_diameter() for wedges
  source/grid/grid_tools.cc
Labels: Reviewed and ready to merge, ready for review, ready to test

#11299 Minor augmentation of the documentation.
  include/deal.II/fe/fe_base.h
Labels: Documentation, ready to test

#11266 Add new constructors to FE(Face)Evaluation
  include/deal.II/matrix_free/fe_evaluation.h
  tests/simplex/matrix_free_02.cc
Labels: Matrix-free, Reviewed and ready to merge, hp, ready to test

#11269 Add a poisson test on wedge grid
  tests/simplex/poisson_01.cc
  tests/simplex/poisson_01.mpirun=1.with_trilinos=true.with_simplex_support=on.output
  tests/simplex/poisson_01.mpirun=4.with_trilinos=true.with_simplex_support=on.output
  tests/simplex/simplex_grids.h
Labels: ready to test

#11311 Fixed a typo in tria_levels.h
  include/deal.II/grid/tria_levels.h
Labels: Reviewed and ready to merge

#11309 mark constructors in Function*<dim> as explicit
  include/deal.II/base/function.h
Labels: ready to test

#11312 Make clear that 'throw' is not a function.
  include/deal.II/fe/fe_tools.templates.h
Labels: Reviewed and ready to merge, ready to test

#11315 Fix step-46.
  doc/news/changes/minor/20201203Bangerth
  examples/step-46/step-46.cc
Labels: ready to test

#11298 MatrixFree: enable wedges (excluding faces integrals)
  include/deal.II/matrix_free/mapping_info.templates.h
  include/deal.II/matrix_free/shape_info.templates.h
Labels: ready for review, ready to test

#11273 Add Poisson test: MatrixFree + DG + mixed mesh
  tests/simplex/matrix_free_04.cc
  tests/simplex/matrix_free_04.with_simplex_support=on.output
Labels: ready for review, ready to test

#11178 Simplex mesh (2D): implement refinement
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_accessor.templates.h
  source/grid/tria.cc
  source/grid/tria_accessor.cc
  tests/simplex/refinement_01.cc
  tests/simplex/refinement_01.with_simplex_support=on.output
Labels: ready to test

#11301 Unify diameter implementations
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_accessor.templates.h
  source/grid/grid_tools.cc
Labels: ready to test

#11331 CMake: Bugfix: set C++14 flag in CXX_FLAGS_SAVED
  cmake/checks/check_01_cxx_features.cmake
Labels: Build system, Reviewed and ready to merge, ready to test

#11334 Move a function into the appropriate namespace.
  include/deal.II/grid/tria_accessor.templates.h
Labels: Reviewed and ready to merge, ready to test

#11332 Remove an internal function.
  source/grid/grid_tools.cc
Labels: Reviewed and ready to merge, ready to test

#11333 Housekeeping.
  source/lac/slepc_solver.cc
Labels: Reviewed and ready to merge, ready to test

#11322 Add assert to extract_vtk_patch_info
  source/base/data_out_base.cc
Labels: Reviewed and ready to merge, ready to test

#11324 Fix base of Tet, Pyramid and Wedge
  include/deal.II/grid/reference_cell.h
Labels: Triangulation, ready to test

#11149 Clean up distribute_dofs().
  source/dofs/dof_handler.cc
Labels: Reviewed and ready to merge, ready to test

#11319 step-67: disable SIMD pragma
  examples/step-67/step-67.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#11336 Fix a data type issue.
  source/lac/slepc_solver.cc
Labels: Reviewed and ready to merge, ready to test

#11337 Guard matrix_free/cuda_matrix_free.h again
  include/deal.II/matrix_free/cuda_matrix_free.h
Labels: ready to test

#11321 ScalarWedgePolynomial: Make polynomials for triangle and line class field
  include/deal.II/simplex/polynomials.h
  source/simplex/polynomials.cc
Labels: Finite Element, ready to test

#11313 Avoid pointers, use references instead
  include/deal.II/matrix_free/shape_info.templates.h
Labels: ready to test

#11306 Implement TriaAccessor::measure() for wedges
  source/grid/grid_tools_nontemplates.cc
Labels: ready to test

#11346 Check reference-cell type of cell and FE
  include/deal.II/dofs/dof_accessor.templates.h
Labels: ready to test

#11344 Implement TriaAccessor::diameter() for pyramid
  include/deal.II/grid/tria_accessor.templates.h
Labels: ready to test

#11345 Fix conformity of Simplex::FE_P and Simplex::FE_WedgeP
  include/deal.II/simplex/fe_lib.h
  source/simplex/fe_lib.cc
Labels: Finite Element, ready to test

#11326 Implement ScalarPyramidPolynomial and FE_PyramidP
  include/deal.II/simplex/fe_lib.h
  include/deal.II/simplex/polynomials.h
  source/simplex/fe_lib.cc
  source/simplex/fe_lib.inst.in
  source/simplex/polynomials.cc
Labels: Finite Element, ready to test

#11348 Fix documentation of two SparseDirectMUMPS functions
  source/lac/petsc_solver.cc
Labels: Reviewed and ready to merge, ready to test

#11340 Better document step-22 solvers.
  doc/doxygen/references.bib
  examples/step-22/doc/intro.dox
  examples/step-22/doc/results.dox
Labels: Reviewed and ready to merge, ready to test

#11297 Add Poisson/Helmholtz test: MatrixFree + wedge mesh
  tests/simplex/matrix_free_01.cc
  tests/simplex/matrix_free_01.with_simplex_support=on.output
  tests/simplex/simplex_grids.h
Labels: ready for review, ready to test

#11343 Implement Simplex::FE_Poly::get_constant_modes
  include/deal.II/simplex/fe_lib.h
  source/simplex/fe_lib.cc
Labels: Finite Element, ready to test

#11327 Add QGaussPyramid
  include/deal.II/simplex/quadrature_lib.h
  source/simplex/quadrature_lib.cc
Labels: Quadrature, ready to test

#11270 Enable DataOut for Wedges
  include/deal.II/numerics/data_out_dof_data.templates.h
  source/base/data_out_base.cc
Labels: ready for review, ready to test

#11292 Test different measures for Wedges
  tests/simplex/cell_measure_01.cc
  tests/simplex/cell_measure_01.with_simplex_support=on.output
Labels: ready to test

#11323 Implement ReferenceCell::internal::Info::Pyramid::standard_to_real_face_line
  include/deal.II/grid/reference_cell.h
Labels: ready to test

#11328 Enable GridOut::write_vtk() for pyramids
  source/grid/grid_out.cc
Labels: ready to test

#11355 Jenkins: use -Og
  Jenkinsfile
Labels: ready to test

#11347 Implement MatrixFreeTools::compute_matrix()
  include/deal.II/matrix_free/tools.h
  tests/matrix_free/compute_diagonal_01.cc
  tests/matrix_free/compute_diagonal_02.cc
  tests/matrix_free/compute_diagonal_03.cc
  tests/matrix_free/compute_diagonal_util.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#11325 Enable DataOut for Pyramids
  include/deal.II/numerics/data_out_dof_data.templates.h
  source/base/data_out_base.cc
Labels: ready to test

#11307 MatrixFreeTools::compute_diagonal: accept class and function pointer
  include/deal.II/matrix_free/tools.h
  tests/matrix_free/compute_diagonal_01.with_mpi=true.with_p4est=true.mpirun=1.output
  tests/matrix_free/compute_diagonal_01.with_mpi=true.with_p4est=true.mpirun=3.output
  tests/matrix_free/compute_diagonal_02.output
  tests/matrix_free/compute_diagonal_03.with_mpi=true.with_p4est=true.mpirun=1.output
  tests/matrix_free/compute_diagonal_util.h
Labels: Matrix-free, ready to test

#11353 Add comment to FE_Poly::get_poly_space_numbering()
  include/deal.II/fe/fe_poly.h
Labels: Documentation

#11308 MatrixFreeTools::compute_diagonal: enable for hp
  include/deal.II/matrix_free/tools.h
  tests/matrix_free/compute_diagonal_04.cc
  tests/matrix_free/compute_diagonal_04.with_mpi=true.with_p4est=true.mpirun=1.output
  tests/matrix_free/compute_diagonal_util.h
Labels: Matrix-free, Reviewed and ready to merge, hp, ready to test

#11282 Timestepping: add low-storage rk and update step-67
  doc/news/changes/minor/20201118JiaqiZhang
  examples/step-67/step-67.cc
  include/deal.II/base/time_stepping.h
  include/deal.II/base/time_stepping.templates.h
  source/base/time_stepping.inst.in
  tests/base/time_stepping_01.cc
  tests/base/time_stepping_01.output
  tests/base/time_stepping_03.cc
  tests/base/time_stepping_03.output
Labels: Feature, Reviewed and ready to merge, ready to test

#11046 FEPointEvaluation: Evaluating shape functions on arbitrary points of a cell
  include/deal.II/base/derivative_form.h
  include/deal.II/fe/fe_point_evaluation.h
  include/deal.II/fe/mapping_q_generic.h
  tests/fe/point_evaluation_01.cc
  tests/fe/point_evaluation_01.output
  tests/fe/point_evaluation_02.cc
  tests/fe/point_evaluation_02.output
  tests/fe/point_evaluation_03.cc
  tests/fe/point_evaluation_03.output
  tests/fe/point_evaluation_04.cc
  tests/fe/point_evaluation_04.output
  tests/fe/point_evaluation_05.cc
  tests/fe/point_evaluation_05.output
  tests/fe/point_evaluation_06.cc
  tests/fe/point_evaluation_06.output
  tests/fe/point_evaluation_07.cc
  tests/fe/point_evaluation_07.output
  tests/fe/point_evaluation_08.cc
  tests/fe/point_evaluation_08.output
  tests/fe/point_evaluation_09.cc
  tests/fe/point_evaluation_09.output
Labels: Finite Element, ready to test

#11314 Particle property pool improvements
  include/deal.II/particles/particle.h
  include/deal.II/particles/property_pool.h
  source/particles/particle.cc
  source/particles/particle_handler.cc
  source/particles/property_pool.cc
  tests/particles/particle_handler_18.cc
  tests/serialization/particle_01.cc
  tests/serialization/particle_01.with_p4est=true.mpirun=1.output
Labels: Particles, Reviewed and ready to merge, ready to test

#11357 step-47: misc cleanup
  examples/step-47/step-47.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#11354 Disable quick tests for windows-2016
  .github/workflows/windows.yml
Labels: Reviewed and ready to merge

#11360 Make Particles::Property pool a template <dim,spacedim>.
  include/deal.II/particles/particle.h
  include/deal.II/particles/particle_accessor.h
  include/deal.II/particles/particle_handler.h
  include/deal.II/particles/property_pool.h
  source/particles/particle.cc
  source/particles/particle_handler.cc
  source/particles/property_pool.cc
  tests/particles/particle_03.cc
  tests/particles/particle_06.cc
  tests/particles/particle_07.cc
  tests/particles/particle_iterator_01.cc
  tests/particles/property_pool_01.cc
  tests/particles/property_pool_02.cc
  tests/serialization/particle_01.cc
Labels: Particles, ready to test

#11317 Add a Poisson test on pyramid grid
  tests/simplex/poisson_01.cc
  tests/simplex/poisson_01.mpirun=1.with_trilinos=true.with_simplex_support=on.output
  tests/simplex/poisson_01.mpirun=4.with_trilinos=true.with_simplex_support=on.output
  tests/simplex/simplex_grids.h
Labels: ready for review, ready to test

#11359 Fix FlatManifold::normal_vector for triangular faces
  include/deal.II/grid/reference_cell.h
  source/grid/manifold.cc
Labels: Manifold, Reviewed and ready to merge, ready to test

#11369 MatrixFree: support FE_PyramidP
  include/deal.II/matrix_free/shape_info.templates.h
  tests/simplex/matrix_free_01.cc
  tests/simplex/matrix_free_01.with_simplex_support=on.output
  tests/simplex/simplex_grids.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#11367 Add missing versions of VectorTools::interpolate_boundary_values for hp::MappingCollection
  include/deal.II/numerics/vector_tools_boundary.h
  include/deal.II/numerics/vector_tools_boundary.templates.h
  source/numerics/vector_tools_boundary.inst.in
Labels: Reviewed and ready to merge, hp, ready to test

#11370 Use function from simplex_grids.h
  tests/simplex/matrix_free_02.cc
Labels: Reviewed and ready to merge, ready to test

#11363 Rename some member functions of PropertyPool, also member variables of Particle
  include/deal.II/particles/particle.h
  include/deal.II/particles/property_pool.h
  source/particles/particle.cc
  source/particles/property_pool.cc
  tests/particles/property_pool_01.cc
  tests/particles/property_pool_02.cc
Labels: Particles, ready to test

#11201 Add GridGenerator::convert_hypercube_to_simplex_mesh
  doc/doxygen/images/convert_hypercube_to_simplex_mesh_visualization.png
  doc/news/changes/minor/20201123DejeneMunch
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  source/grid/grid_generator.inst.in
  tests/simplex/conv_hex_to_simplex.cc
  tests/simplex/conv_hex_to_simplex.with_simplex_support=on.output
Labels: ready to test

#11377 Fix some typos regarding 'hexahedra'
  doc/doxygen/headers/simplex.h
  doc/news/changes/minor/20201123DejeneMunch
  include/deal.II/grid/connectivity.h
  include/deal.II/grid/grid_generator.h
  include/deal.II/grid/tria.h
Labels: Documentation, Reviewed and ready to merge

#11376 Clean up std::map usage in interpolate_boundary_values
  include/deal.II/numerics/vector_tools_boundary.templates.h
Labels: Miscellaneous, Reviewed and ready to merge, ready to test

#11385 CI: fix OSX cmake version 3.18
  .github/workflows/osx.yml
Labels: Reviewed and ready to merge

#11384 CMake-3.19 fixes
  .github/workflows/osx.yml
  cmake/macros/macro_enable_if_links.cmake
  cmake/macros/macro_enable_if_supported.cmake
  cmake/macros/macro_find_system_library.cmake
Labels: Build system, ready for review, ready to test

#11386 Added missing header for boost 1.75.0.
  include/deal.II/base/bounding_box.h
  include/deal.II/base/config.h.in
Labels: Reviewed and ready to merge, ready to test

#11374 Add a particle test.
  tests/particles/step-19.cc
  tests/particles/step-19.output
Labels: ready to test

#11394 Simplify constructor of FEEvaluationBaseData
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, ready to test

#11391 Prepare for storing particle locations in the PropertyPool.
  include/deal.II/particles/particle.h
  source/particles/particle.cc
Labels: Particles, ready to test

#11396 Store reference to QuadratureDescriptor in FEEvaluationBaseData
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#11368 Remove temporary string objects in Utilities::(un)pack.
  include/deal.II/base/utilities.h
  source/base/utilities.cc
  tests/base/utilities_pack_unpack_06.cc
Labels: ready to test

#10764 Assign faces different quadrature rules
  doc/news/changes/incompatibilities/20201212Munch
  include/deal.II/base/qprojector.h
  include/deal.II/fe/fe.h
  include/deal.II/fe/fe_dgp_nonparametric.h
  include/deal.II/fe/fe_enriched.h
  include/deal.II/fe/fe_face.h
  include/deal.II/fe/fe_nedelec_sz.h
  include/deal.II/fe/fe_nothing.h
  include/deal.II/fe/fe_p1nc.h
  include/deal.II/fe/fe_poly.h
  include/deal.II/fe/fe_poly.templates.h
  include/deal.II/fe/fe_poly_face.h
  include/deal.II/fe/fe_poly_face.templates.h
  include/deal.II/fe/fe_poly_tensor.h
  include/deal.II/fe/fe_system.h
  include/deal.II/fe/fe_values.h
  include/deal.II/fe/mapping.h
  include/deal.II/fe/mapping_cartesian.h
  include/deal.II/fe/mapping_fe.h
  include/deal.II/fe/mapping_fe_field.h
  include/deal.II/fe/mapping_manifold.h
  include/deal.II/fe/mapping_q.h
  include/deal.II/fe/mapping_q_generic.h
  include/deal.II/hp/fe_values.h
  include/deal.II/hp/q_collection.h
  source/base/qprojector.cc
  source/fe/fe.cc
  source/fe/fe_dgp_nonparametric.cc
  source/fe/fe_enriched.cc
  source/fe/fe_face.cc
  source/fe/fe_nedelec_sz.cc
  source/fe/fe_nothing.cc
  source/fe/fe_p1nc.cc
  source/fe/fe_poly_tensor.cc
  source/fe/fe_system.cc
  source/fe/fe_values.cc
  source/fe/mapping.cc
  source/fe/mapping_cartesian.cc
  source/fe/mapping_fe.cc
  source/fe/mapping_fe_field.cc
  source/fe/mapping_manifold.cc
  source/fe/mapping_q.cc
  source/fe/mapping_q_generic.cc
  source/hp/fe_values.cc
  tests/simplex/variable_face_quadratures_01.cc
  tests/simplex/variable_face_quadratures_01.output
  tests/simplex/variable_face_quadratures_02.cc
  tests/simplex/variable_face_quadratures_02.output
  tests/simplex/variable_face_quadratures_03.cc
  tests/simplex/variable_face_quadratures_03.with_simplex_support=on.output
Labels: Finite Element, Mapping, hp, ready for review, ready to test

#11398 Clarify a comment in class Particle.
  include/deal.II/particles/particle.h
Labels: Documentation, Particles

#11397 Do not inspect an object that has been moved from.
  tests/particles/particle_03.cc
  tests/particles/particle_03.output
Labels: Particles, ready to test

#11373 Add to the documentation of numbers::signaling_nan().
  include/deal.II/base/signaling_nan.h
Labels: Documentation

#11381 provide memory_consumption() for some Function* classes
  include/deal.II/base/flow_function.h
  include/deal.II/base/function.h
  include/deal.II/base/function_cspline.h
  include/deal.II/base/function_derivative.h
  include/deal.II/base/function_lib.h
  include/deal.II/base/function_spherical.h
  source/base/function_lib.cc
Labels: Miscellaneous, ready to test

#11364 Added getter function for child_indices of CellId + CellId benchmark testcase
  include/deal.II/grid/cell_id.h
  tests/grid/cell_id_08.cc
  tests/grid/cell_id_08.output
  tests/grid/cell_id_09.cc
  tests/grid/cell_id_09.output
Labels: Triangulation, ready to test

#11399 Remove compatibility code for GCC versions prior to 5.0.
  include/deal.II/base/utilities.h
Labels: ready to test

#11365 Added Triangulation::create_cell_iterator().
  doc/news/changes/incompatibilities/20201212Fehling
  include/deal.II/grid/cell_id.h
  include/deal.II/grid/tria.h
  source/grid/cell_id.cc
  source/grid/tria.cc
  tests/fe/fe_subface_values_01.cc
  tests/fullydistributed_grids/copy_distributed_tria_03.cc
  tests/fullydistributed_grids/copy_serial_tria_08.cc
  tests/fullydistributed_grids/copy_serial_tria_09.cc
  tests/grid/cell_id_03.cc
  tests/grid/cell_id_04.cc
  tests/sharedtria/mg_dof_01.cc
Labels: ready to test

#11407 Remove n_q_points_face from fe_evaluation.h
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, ready to test

#11409 Work on MatrixFreeTools::compute_matrix
  include/deal.II/matrix_free/tools.h
Labels: Matrix-free, ready to test

#11402 Update Ginkgo cmake detection and tests.
  cmake/configure/configure_2_ginkgo.cmake
  cmake/modules/FindGINKGO.cmake
  tests/ginkgo/solver.cc
  tests/ginkgo/solver.output
Labels: Reviewed and ready to merge, ready to test

#11403 FE_Nothing: pass reference-cell type to constructor
  include/deal.II/fe/fe_nothing.h
  source/fe/fe_nothing.cc
Labels: ready to test

#11406 FEFaceValues: use face_no to select quadrature rule
  include/deal.II/fe/fe_values.h
  source/fe/fe_values.cc
Labels: ready to test

#11361 Enable FEFaceValues for wedges and pyramids
  source/base/qprojector.cc
  source/fe/mapping_fe.cc
  tests/simplex/poisson_01.cc
  tests/simplex/poisson_01.mpirun=1.with_trilinos=true.with_simplex_support=on.output
  tests/simplex/poisson_01.mpirun=4.with_trilinos=true.with_simplex_support=on.output
Labels: ready for review, ready to test

#11410 Revert "Merge pull request #11402 from pratikvn/fix-ginkgo-cmake"
  cmake/configure/configure_2_ginkgo.cmake
  cmake/modules/FindGINKGO.cmake
  tests/ginkgo/solver.cc
  tests/ginkgo/solver.output
Labels: ready to test

#11412 Silence unused parameter warning when building with C++17
  include/deal.II/base/utilities.h
Labels: Reviewed and ready to merge, ready to test

#11411 make constructors of Table and AlignedVector explicit
  include/deal.II/base/aligned_vector.h
  include/deal.II/base/table.h
Labels: Reviewed and ready to merge, ready to test

#11339 Avoid MPI calls in the HDF5 destructors when there is an exception
  doc/news/changes/minor/20201223GarciaSanchez
  include/deal.II/base/hdf5.h
  source/base/hdf5.cc
Labels: Reviewed and ready to merge, ready to test

#11405 Implement FE_WedgeDGP and FE_PyramidDGP
  include/deal.II/fe/fe_base.h
  include/deal.II/simplex/fe_lib.h
  source/fe/fe_data.cc
  source/simplex/fe_lib.cc
  source/simplex/fe_lib.inst.in
  tests/simplex/fe_lib_01.cc
  tests/simplex/fe_lib_01.output
Labels: Finite Element, ready to test

#11421 Fix formatting
  include/deal.II/fe/fe_tools.templates.h
Labels: Reviewed and ready to merge, ready to test

#11259 Added instantiation for cases when dim < spacedim
  doc/news/changes/minor/20201223MalharTidke
  source/dofs/dof_tools_constraints.inst.in
  tests/dofs/dof_tools_21.cc
  tests/dofs/dof_tools_21_b.cc
  tests/dofs/dof_tools_21_b.output
  tests/dofs/dof_tools_21_b_x.cc
  tests/dofs/dof_tools_21_b_x.output
  tests/dofs/dof_tools_21_b_x_q3.cc
  tests/dofs/dof_tools_21_b_x_q3.output
  tests/dofs/dof_tools_21_b_y.cc
  tests/dofs/dof_tools_21_b_y.output
  tests/dofs/dof_tools_21_c.cc
  tests/dofs/dof_tools_21_c.output
  tests/dofs/dof_tools_23.cc
  tests/dofs/dof_tools_periodic.h
Labels: WIP :warning:, ready to test

#11427 Fix tests with output files with same name
  cmake/macros/macro_deal_ii_add_test.cmake
Labels: Build system, ready to test

#11432 MatrixFreeTools::compute_diagonal() make class const
  include/deal.II/matrix_free/tools.h
Labels: ready to test

#11278 SUNDIALS: update ARKode to version 5.4.0
  cmake/configure/configure_sundials.cmake
  doc/news/changes/major/20201211Proell
  include/deal.II/sundials/arkode.h
  include/deal.II/sundials/ida.h
  include/deal.II/sundials/kinsol.h
  include/deal.II/sundials/sunlinsol_newempty.h
  source/sundials/arkode.cc
  source/sundials/ida.cc
  source/sundials/kinsol.cc
  tests/sundials/arkode_01.cc
  tests/sundials/arkode_01.prm
  tests/sundials/arkode_01.with_sundials.geq.5.4.0.output
  tests/sundials/arkode_01.with_sundials.le.5.4.0.output
  tests/sundials/arkode_02.cc
  tests/sundials/arkode_02.with_sundials.geq.5.4.0.output
  tests/sundials/arkode_02.with_sundials.le.4.0.0.output
  tests/sundials/arkode_02.with_sundials=4.0.0.output
  tests/sundials/arkode_03.cc
  tests/sundials/arkode_03.prm
  tests/sundials/arkode_03.with_sundials.geq.5.4.0.output
  tests/sundials/arkode_03.with_sundials.le.5.4.0.output
  tests/sundials/arkode_04.cc
  tests/sundials/arkode_04.prm
  tests/sundials/arkode_04.with_sundials.le.4.0.0.output
  tests/sundials/arkode_05.cc
  tests/sundials/arkode_05.prm
  tests/sundials/arkode_05.with_sundials.le.4.0.0.output
  tests/sundials/arkode_06.cc
  tests/sundials/arkode_06.prm
  tests/sundials/arkode_06.with_sundials.geq.5.4.0.output
  tests/sundials/arkode_06.with_sundials=4.0.0.output
  tests/sundials/arkode_07.cc
  tests/sundials/arkode_07.prm
  tests/sundials/arkode_07.with_sundials.geq.5.4.0.output
  tests/sundials/arkode_07.with_sundials=4.0.0.output
  tests/sundials/arkode_08.cc
  tests/sundials/arkode_08.prm
  tests/sundials/arkode_08.with_sundials.geq.5.4.0.output
  tests/sundials/arkode_08.with_sundials=4.0.0.output
  tests/sundials/harmonic_oscillator_02.output
  tests/sundials/harmonic_oscillator_03.output
  tests/sundials/harmonic_oscillator_04.output
  tests/sundials/harmonic_oscillator_05.output
  tests/sundials/harmonic_oscillator_06.output
  tests/sundials/ida_01.cc
  tests/sundials/ida_01.prm
  tests/sundials/ida_01.with_sundials.le.4.0.0.output
  tests/sundials/kinsol_01.with_sundials.le.4.0.0.output
  tests/sundials/serial_sundials.cc
  tests/sundials/serial_sundials.with_sundials.geq.4.0.0.output
  tests/sundials/serial_sundials.with_sundials.le.4.0.0.output
Labels: External libraries, ready to test

#11434 Rename file in test folder
  tests/multigrid-global-coarsening/mg_transfer_a_01.cc
  tests/multigrid-global-coarsening/mg_transfer_a_02.cc
  tests/multigrid-global-coarsening/mg_transfer_p_01.cc
  tests/multigrid-global-coarsening/mg_transfer_p_02.cc
  tests/multigrid-global-coarsening/mg_transfer_p_03.cc
  tests/multigrid-global-coarsening/mg_transfer_util.h
Labels: ready to test

#11430 Better document FE_Nothing.
  include/deal.II/fe/fe_nothing.h
  source/fe/fe_nothing.cc
Labels: Reviewed and ready to merge, ready to test

#11419 Pyramid/wedge: diverse fixes
  include/deal.II/grid/reference_cell.h
  source/base/qprojector.cc
  source/fe/mapping_fe.cc
  source/simplex/fe_lib.cc
  tests/simplex/poisson_01.mpirun=1.with_trilinos=true.with_simplex_support=on.output
  tests/simplex/poisson_01.mpirun=4.with_trilinos=true.with_simplex_support=on.output
Labels: ready for review, ready to test

#11424 Introduce ReferenceCell::compute_orientation and ::permute_according_orientation
  include/deal.II/grid/connectivity.h
  include/deal.II/grid/reference_cell.h
  source/base/qprojector.cc
Labels: ready to test

#11423 Introduce ReferenceCell::unit_tangential_vectors()
  include/deal.II/grid/reference_cell.h
  source/fe/mapping_fe.cc
  tests/simplex/unit_tangential_vectors_01.cc
  tests/simplex/unit_tangential_vectors_01.output
Labels: ready to test

#11436 Add test for geometric global-coarsening multigrid
  tests/multigrid-global-coarsening/multigrid_a_01.cc
  tests/multigrid-global-coarsening/multigrid_a_01.mpirun=1.with_trilinos=true.with_simplex_support=on.output
Labels: Geometric multigrid, ready to test

#11408 MatrixFreeTools::compute_diagonal() for simplex grid
  tests/matrix_free/compute_diagonal_05.cc
  tests/matrix_free/compute_diagonal_05.with_mpi=true.with_simplex_support=on.mpirun=1.output
Labels: Matrix-free, Tests, ready to test

#11438 Fix boost include file.
  source/fe/mapping.cc
Labels: Reviewed and ready to merge, ready for review, ready to test

#11439 Fix warning due to boost
  source/fe/mapping.cc
Labels: ready to test

#11425 Fix output of grid/cell_id_08
  tests/grid/cell_id_08.cc
  tests/grid/cell_id_08.output
Labels: ready to test

#11426 Add utility functions to ReferenceCell namespace
  include/deal.II/grid/reference_cell.h
  source/grid/CMakeLists.txt
  source/grid/reference_cell.cc
  source/grid/reference_cell.inst.in
Labels: ready to test

#11440 Avoid MPI calls in the HDF5 destructors when there is an exception - DataSet
  source/base/hdf5.cc
Labels: Reviewed and ready to merge, ready to test

#11441 Avoid warning about unused variable in particle.h
  include/deal.II/particles/particle.h
Labels: Reviewed and ready to merge, ready to test

#11437 Clean up FE_Nothing::get_name().
  include/deal.II/fe/fe_nothing.h
  include/deal.II/grid/reference_cell.h
  source/fe/fe_nothing.cc
  tests/fe/get_fe_by_name_01.output
  tests/hp/fe_nothing_22.cc
  tests/hp/fe_nothing_22.output
Labels: Finite Element, Miscellaneous, Reviewed and ready to merge, ready to test

#11442 Make a test more verbose.
  tests/particles/step-19.cc
  tests/particles/step-19.output
Labels: Reviewed and ready to merge, Tests, ready to test

#11318 Reshuffle code in SolverCG
  include/deal.II/lac/solver_cg.h
Labels: ready to test

#11371 FEInterfaceValues: pass to the constructor hp::QCollection
  include/deal.II/fe/fe_interface_values.h
Labels: ready to test

#11428 FETools::get_projection_matrix for simplices
  include/deal.II/fe/fe_tools.templates.h
  tests/simplex/get_projection_matrix_01.cc
  tests/simplex/get_projection_matrix_01.with_simplex_support=on.output
Labels: Finite Element, Geometric multigrid, ready to test

#11447 Utility grid generator function `hyper_line` for tests.
  tests/hp/error_prediction_01.cc
  tests/mpi/error_predictor_01.cc
  tests/mpi/error_predictor_02.cc
  tests/particles/particle_handler_14.cc
  tests/sharedtria/hp_choose_p_over_h.cc
  tests/test_grids.h
  tests/tests.h
Labels: ready to test

#11444 Refactor the HDF5 abort code.
  source/base/hdf5.cc
Labels: Miscellaneous, ready to test

#11452 Fix redefinition of default argument in test
  tests/dofs/dof_tools_21.cc
  tests/dofs/dof_tools_21_b.cc
  tests/dofs/dof_tools_21_b_x.cc
  tests/dofs/dof_tools_21_b_x_q3.cc
  tests/dofs/dof_tools_21_b_y.cc
  tests/dofs/dof_tools_21_c.cc
  tests/dofs/dof_tools_23.cc
  tests/dofs/dof_tools_periodic.h
Labels: Reviewed and ready to merge, ready to test
