Repository dealii/dealii, pull requests merged in 2020-04, with the labels that each got.

#9784 Implement default initializer for EigenvalueInformation
  include/deal.II/lac/precondition.h
Labels: Reviewed and ready to merge, ready to test

#9767 Add output variants for new MF::MappingInfo test
  tests/matrix_free/compress_mapping.output.avx512
  tests/matrix_free/compress_mapping.output.novec
Labels: Tests, ready to test

#9785 Remove SwappableVector
  doc/news/changes/incompatibilities/20200331DanielArndt
  include/deal.II/lac/swappable_vector.h
  include/deal.II/lac/swappable_vector.templates.h
  source/lac/CMakeLists.txt
  source/lac/swappable_vector.cc
Labels: Reviewed and ready to merge, ready to test

#9783 Pass ExcNoMatch the description directly
  include/deal.II/base/patterns.h
Labels: Reviewed and ready to merge, ready to test

#9789 remove boost/geometry.hpp from Point
  include/deal.II/base/bounding_box.h
  include/deal.II/base/point.h
  source/base/utilities.cc
Labels: Reviewed and ready to merge, ready to test

#9791 Simplify DoFCellAccessor::distribute_local_to_global()
  include/deal.II/dofs/dof_accessor.templates.h
Labels: DoFs, ready to test

#9786 Remove deprecated class FilteredMatrix
  doc/news/changes/incompatibilities/20200401DanielArndt
  include/deal.II/lac/filtered_matrix.h
  include/deal.II/numerics/matrix_tools.h
  include/deal.II/numerics/vector_tools.templates.h
  source/grid/grid_tools.cc
  tests/data_out/data_out_curved_cells.cc
  tests/grid/grid_transform_02.output
  tests/lac/filtered_matrix.cc
  tests/lac/filtered_matrix.output
  tests/lac/filtered_matrix_01.cc
  tests/lac/filtered_matrix_01.output
  tests/lac/filtered_matrix_02.cc
  tests/lac/filtered_matrix_02.output
  tests/lac/filtered_matrix_03.cc
  tests/lac/filtered_matrix_03.output
  tests/lac/filtered_matrix_04.cc
  tests/lac/filtered_matrix_04.output
  tests/lac/filtered_matrix_05.cc
  tests/lac/filtered_matrix_05.output
  tests/lac/filtered_matrix_06.cc
  tests/lac/filtered_matrix_06.output
  tests/mappings/mapping_q1_eulerian_01.cc
  tests/mappings/mapping_q_eulerian_01.cc
  tests/mappings/mapping_q_eulerian_02.cc
  tests/mappings/mapping_q_eulerian_03.cc
  tests/mappings/mapping_q_eulerian_07.cc
  tests/mappings/mapping_q_eulerian_08.cc
  tests/mappings/mapping_q_eulerian_11.cc
  tests/matrix_free/interpolate_to_mg.cc
Labels: ready to test

#9800 Minimize boost/geometry.h includes
  include/deal.II/boost_adaptors/bounding_box.h
  include/deal.II/boost_adaptors/point.h
  include/deal.II/boost_adaptors/segment.h
  include/deal.II/numerics/rtree.h
  source/grid/grid_tools_cache.cc
  tests/base/point_04.cc
  tests/boost/bounding_box_adaptor_01.cc
  tests/boost/point_adaptor_01.cc
  tests/boost/rtree_01.cc
Labels: Reviewed and ready to merge, ready to test

#9758 Explicitly spell dealii::parallel in multiple places
  include/deal.II/matrix_free/dof_info.templates.h
  include/deal.II/matrix_free/face_setup_internal.h
  include/deal.II/multigrid/mg_transfer.templates.h
  source/dofs/dof_handler_policy.cc
  source/multigrid/mg_transfer_internal.cc
Labels: DoFs, Reviewed and ready to merge, ready to test

#9801 Remove PointerMatrix*
  doc/doxygen/headers/concepts.h
  doc/news/changes/incompatibilities/20200402DanielArndt
  include/deal.II/lac/pointer_matrix.h
  tests/bits/block_sparse_matrix_1.cc
  tests/lac/pointer_matrix.cc
  tests/lac/pointer_matrix.output
  tests/lac/pointer_matrix_01.cc
  tests/lac/pointer_matrix_01.output
  tests/lac/pointer_matrix_02.cc
  tests/lac/pointer_matrix_02.output
  tests/lac/pointer_matrix_03.cc
  tests/lac/pointer_matrix_03.output
  tests/lac/pointer_matrix_04.cc
  tests/lac/pointer_matrix_04.output
  tests/lac/pointer_matrix_05.cc
  tests/lac/pointer_matrix_05.output
  tests/lac/pointer_matrix_06.cc
  tests/lac/pointer_matrix_06.output
  tests/lac/pointer_matrix_07.cc
  tests/lac/pointer_matrix_07.output
  tests/lac/pointer_matrix_08.cc
  tests/lac/pointer_matrix_08.output
  tests/lac/pointer_matrix_09.cc
  tests/lac/pointer_matrix_09.output
  tests/lac/pointer_matrix_10.cc
  tests/lac/pointer_matrix_10.output
  tests/lac/pointer_matrix_vector.cc
  tests/lac/pointer_matrix_vector.output
Labels: Reviewed and ready to merge, ready to test

#9796 Improve mesh quality of quarter hyper ball
  doc/doxygen/images/quarter_hyper_ball_2d.png
  doc/doxygen/images/quarter_hyper_ball_3d.png
  doc/news/changes/minor/20200402MartinKronbichler
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  tests/grid/grid_generator_01.output
  tests/grid/grid_generator_01b.output
Labels: Reviewed and ready to merge, Triangulation, ready to test

#9810 Add functions accepting hp::DoFHandler to BlockInfo
  include/deal.II/dofs/block_info.h
  source/dofs/block_info.cc
  source/dofs/block_info.inst.in
Labels: Reviewed and ready to merge, ready to test

#9806 Use AE spelling 'disk' instead of BE spelling 'disc'.
  examples/step-69/step-69.cc
Labels: Reviewed and ready to merge, ready to test

#9814 Add a missing assertion.
  source/base/data_out_base.cc
Labels: Post-processing, Reviewed and ready to merge, ready to test

#9636 Step-69: Introduce asynchronous IO mechanism
  examples/step-69/step-69.cc
  examples/step-69/step-69.prm
Labels: Documentation, Reviewed and ready to merge, Tutorials, ready to test

#9813 Simplify some code by using a range-based for loop.
  source/numerics/data_out.cc
Labels: Reviewed and ready to merge, ready for review, ready to test

#9793 MappingQGeneric: Copy mapping support points to quadrature points
  source/fe/mapping_q_generic.cc
  tests/mappings/mapping_q_quadrature_points.cc
  tests/mappings/mapping_q_quadrature_points.output
Labels: Mapping, ready to test

#9811 Simplify instantiation of DoFHandler and hp::DoFHandler
  source/dofs/dof_handler.inst.in
  source/hp/dof_handler.inst.in
Labels: DoFs, Reviewed and ready to merge, ready to test

#8824 The class DiscreteTime implemented.
  doc/news/changes/minor/20190920RezaRastak
  include/deal.II/base/discrete_time.h
  source/base/CMakeLists.txt
  source/base/discrete_time.cc
  tests/base/discrete_time_1.cc
  tests/base/discrete_time_1.output
Labels: Reviewed and ready to merge, ready to test

#9816 more boost warning guards
  include/deal.II/boost_adaptors/bounding_box.h
  include/deal.II/boost_adaptors/segment.h
  include/deal.II/grid/grid_tools.h
Labels: Reviewed and ready to merge, ready to test

#9805 Make the spelling of 'add_parameter()' arguments consistent.
  examples/step-69/step-69.cc
  examples/step-69/step-69.prm
Labels: Reviewed and ready to merge, ready to test

#9808 Simplify DoFCellAccessorImplementation::update_cell_dof_indices_cache()
  include/deal.II/dofs/dof_accessor.templates.h
Labels: DoFs, Reviewed and ready to merge, ready to test

#9799 Minor cleanups.
  source/grid/grid_in.cc
Labels: Reviewed and ready to merge, ready to test

#9739 GridTools/GridGenerator: add some functions to support dim-independent programming
  include/deal.II/grid/grid_generator.h
  include/deal.II/grid/grid_tools.h
  source/grid/grid_generator.cc
  source/grid/grid_tools.cc
Labels: Reviewed and ready to merge, ready to test

#9707 Print a reduced parameter tree for XML and JSON
  doc/news/changes/minor/20200322PeterMunch
  include/deal.II/base/parameter_handler.h
  source/base/parameter_handler.cc
  tests/parameter_handler/parameter_handler_write_json.cc
  tests/parameter_handler/parameter_handler_write_json.output
  tests/parameter_handler/parameter_handler_write_xml.cc
  tests/parameter_handler/parameter_handler_write_xml.output
Labels: Reviewed and ready to merge, ready to test

#9797 Remove unused functions
  include/deal.II/dofs/dof_accessor.templates.h
Labels: Reviewed and ready to merge, ready to test

#9795 Fix GridIn::read_vtk
  source/grid/grid_in.cc
  tests/grid/grid_in_vtk_2d/mesh
  tests/grid/grid_in_vtk_3d/mesh
  tests/grid/grid_in_vtk_3d_03.vtk
  tests/grid/grid_in_vtk_3d_04.vtk
Labels: Reviewed and ready to merge, Triangulation, ready to test

#9825 Fix warning in Utilities::MPI for serial release build
  include/deal.II/base/mpi.templates.h
Labels: Reviewed and ready to merge, ready to test

#9803 Fix oversight in GridGenerator::hyper_ball in 2d
  source/grid/grid_generator.cc
  tests/grid/get_coarse_mesh_description_01.output
Labels: Triangulation, ready to test

#9837 Update Epetra link
  include/deal.II/lac/trilinos_epetra_vector.h
Labels: Documentation, Reviewed and ready to merge

#9836 Make TpetraWrappers appear in Doxygen
  doc/doxygen/options.dox.in
  include/deal.II/lac/trilinos_tpetra_vector.h
Labels: Documentation, Reviewed and ready to merge

#9792 Allow vector_adaptor to work on ghosted vectors.
  include/deal.II/lac/vector.h
  include/deal.II/optimization/rol/vector_adaptor.h
  tests/rol/vector_adaptor_with_ghost_01.cc
Labels: ready to test

#9822 Place figures for 2d/3d quarter hyper ball in same line
  include/deal.II/grid/grid_generator.h
Labels: Documentation

#9827 Fix bug in VectorTools::get_position_vector for high order mappings
  doc/news/changes/minor/20200405MartinKronbichler
  include/deal.II/numerics/vector_tools.templates.h
  tests/mappings/mapping_fe_field_07.cc
  tests/mappings/mapping_fe_field_07.output
  tests/mappings/mapping_fe_field_08.cc
  tests/mappings/mapping_fe_field_08.output
Labels: Mapping, ready to test

#9842 Output step-62 results as a complex-valued vector
  examples/step-62/step-62.cc
Labels: Reviewed and ready to merge, ready to test

#9841 Use more range-based for loops.
  include/deal.II/differentiation/ad/ad_helpers.h
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/lac/relaxation_block.templates.h
  include/deal.II/lac/sparse_vanka.templates.h
  include/deal.II/matrix_free/face_setup_internal.h
  include/deal.II/matrix_free/matrix_free.templates.h
  include/deal.II/matrix_free/operators.h
  include/deal.II/meshworker/integration_info.templates.h
  include/deal.II/multigrid/mg_transfer.templates.h
  include/deal.II/numerics/data_out_dof_data.templates.h
  source/differentiation/ad/ad_helpers.cc
  source/grid/grid_in.cc
  source/hp/dof_handler.cc
  source/multigrid/mg_level_global_transfer.cc
  source/numerics/point_value_history.cc
Labels: ready to test

#9821 Remove deprecated class PArpackSolver::Shift
  doc/news/changes/incompatibilities/20200404DanielArndt
  include/deal.II/lac/parpack_solver.h
Labels: ready to test

#9844 Build debug and release with Actions
  .github/workflows/main.yml
Labels: Infrastructure, ready to test

#9831 Implement functionality from Hypercube on BoundingBox
  include/deal.II/base/bounding_box.h
  include/deal.II/non_matching/quadrature_generator.h
  source/base/bounding_box.cc
  source/base/bounding_box.inst.in
  source/non_matching/CMakeLists.txt
  source/non_matching/quadrature_generator.cc
  tests/base/bounding_box_6.cc
  tests/base/bounding_box_6.output
  tests/base/coordinate_to_one_dim_higher.cc
  tests/base/coordinate_to_one_dim_higher.output
  tests/non_matching/hypercube.cc
  tests/non_matching/hypercube.output
Labels: Quadrature, Reviewed and ready to merge, ready to test

#9845 Fix some Doxygen warnings
  include/deal.II/base/discrete_time.h
  include/deal.II/base/quadrature_lib.h
  include/deal.II/base/tensor.h
  include/deal.II/distributed/cell_weights.h
  include/deal.II/grid/grid_out.h
  include/deal.II/hp/fe_values.h
  include/deal.II/opencascade/manifold_lib.h
  source/base/polynomial.cc
  source/differentiation/sd/symengine_number_types.cc
  source/distributed/cell_weights.cc
  source/grid/grid_out.cc
  source/hp/fe_values.cc
  source/lac/block_vector.cc
  source/lac/chunk_sparsity_pattern.cc
Labels: ready to test

#9718 improve robustness and usability of ParameterHandler
  doc/news/changes/minor/20200323NiklasFehn
  include/deal.II/base/parameter_handler.h
  source/base/parameter_handler.cc
  tests/parameter_handler/parameter_handler_25.cc
  tests/parameter_handler/parameter_handler_25.output
Labels: Reviewed and ready to merge, ready to test

#9819 Add Utilities::MPI::compute_set_union
  doc/news/changes/minor/20200404PeterMunch
  include/deal.II/base/mpi.h
  include/deal.II/base/mpi.templates.h
  include/deal.II/base/mpi_tags.h
  source/base/mpi.cc
  tests/mpi/union_01.cc
  tests/mpi/union_01.mpirun=2.output
Labels: Parallel distributed, ready to test

#9815 Allow outputting complex-valued vector and tensor fields
  include/deal.II/numerics/data_out_dof_data.templates.h
  source/numerics/data_out.cc
  tests/data_out/data_out_complex_05.cc
  tests/data_out/data_out_complex_05.output
  tests/data_out/data_out_complex_05_tensor.cc
  tests/data_out/data_out_complex_05_tensor.output
  tests/data_out/data_out_complex_06.cc
  tests/data_out/data_out_complex_06.output
Labels: ready for review, ready to test

#9846 Update documentation of NoncontiguousPartitioner
  include/deal.II/base/mpi_noncontiguous_partitioner.h
Labels: Documentation

#9849 Fix some warnings in tests with clang-10
  include/deal.II/numerics/data_out_dof_data.templates.h
  tests/base/mpi_noncontiguous_partitioner_02.cc
  tests/base/transpose_table_iterators_1.cc
  tests/data_out/data_out_12.cc
  tests/data_out/data_out_13.cc
  tests/distributed_grids/intergrid_transfer_representation_parallel.cc
  tests/grid/mesh_3d_17.cc
  tests/grid/user_data_01.cc
  tests/matrix_free/iterators.cc
  tests/matrix_free/mapping_info_01.cc
  tests/mpi/parallel_partitioner_09.cc
  tests/numerics/project_bv_curl_conf_04.cc
Labels: Reviewed and ready to merge, ready to test

#9777 Add Python version of step-53
  contrib/python-bindings/notebooks/index.ipynb
  contrib/python-bindings/notebooks/step-53.ipynb
  doc/news/changes/major/20200330Grayver
  examples/step-53/doc/intro.dox
  examples/step-53/step-53.ipynb
Labels: ready to test

#9851 do not build release on github actions OSX
  .github/workflows/main.yml
Labels: ready to test

#9848 [CI]: add GitHub actions linux release build
  .github/workflows/main.yml
Labels: ready to test

#9817 Require gcc 4.9 and clang 4.0.
  cmake/setup_compiler_flags_gnu.cmake
  doc/readme.html
Labels: ready to test

#9683 MF: No special treatment of cells close to proc interface
  include/deal.II/matrix_free/face_setup_internal.h
  include/deal.II/matrix_free/matrix_free.templates.h
  include/deal.II/matrix_free/task_info.h
  source/matrix_free/task_info.cc
  tests/matrix_free/cell_categorization.with_p4est=true.mpirun=7.output
  tests/matrix_free/cell_categorization.with_p4est=true.mpirun=7.output.avx
  tests/matrix_free/cell_categorization.with_p4est=true.mpirun=7.output.avx512
  tests/matrix_free/cell_categorization.with_p4est=true.mpirun=7.output.novec
  tests/matrix_free/dg_pbc_02.with_mpi=true.with_p4est=true.mpirun=7.output
  tests/matrix_free/dg_pbc_02.with_mpi=true.with_p4est=true.mpirun=7.output.avx
  tests/matrix_free/dg_pbc_02.with_mpi=true.with_p4est=true.mpirun=7.output.avx512
Labels: Matrix-free, ready to test

#9850 Document the mental model of DiscreteTime.
  include/deal.II/base/discrete_time.h
Labels: Documentation, Reviewed and ready to merge

#9857 Output more digits for test grid/grid_generator_01b
  tests/grid/grid_generator_01b.cc
  tests/grid/grid_generator_01b.output
Labels: Tests, ready to test

#9376 Read and write vtu files
  doc/news/changes/minor/20200117LucaHeltaiNicolaGiuliani_bis
  include/deal.II/grid/grid_in.h
  include/deal.II/grid/grid_out.h
  source/grid/grid_in.cc
  source/grid/grid_out.cc
  tests/grid/grid_in_out_vtu_01.cc
  tests/grid/grid_in_out_vtu_01.output
Labels: ready for review, ready to test

#9858 Fix two tests with roundoff problems
  tests/bits/fe_field_function_04_vector.cc
  tests/bits/fe_field_function_04_vector.output
  tests/tensors/symmetric_tensor_40.cc
Labels: Tests, ready to test

#9859 Some doxygen fixes
  doc/doxygen/headers/manifold.h
  include/deal.II/base/tensor.h
  include/deal.II/base/thread_local_storage.h
  include/deal.II/fe/block_mask.h
  include/deal.II/fe/component_mask.h
  include/deal.II/grid/manifold.h
  include/deal.II/grid/tria_description.h
  include/deal.II/integrators/l2.h
  source/lac/trilinos_sparse_matrix.cc
Labels: Reviewed and ready to merge, ready to test

#9852 Minor fixes to BoundingBox
  include/deal.II/base/bounding_box.h
  source/base/bounding_box.cc
  source/base/bounding_box.inst.in
  tests/base/bounding_box_6.cc
  tests/base/bounding_box_6.output
  tests/base/coordinate_to_one_dim_higher.cc
Labels: ready to test

#9860 Remove more deprecations
  doc/news/changes/incompatibilities/20200408DanielArndt
  include/deal.II/base/utilities.h
  include/deal.II/dofs/dof_handler.h
  include/deal.II/hp/dof_handler.h
  include/deal.II/lac/la_parallel_block_vector.h
  include/deal.II/lac/la_parallel_block_vector.templates.h
  include/deal.II/matrix_free/fe_evaluation.h
  source/dofs/dof_handler.cc
  source/hp/dof_handler.cc
Labels: ready to test

#9864 CI: github actions: checkout@v2
  .github/workflows/main.yml
Labels: Infrastructure, Reviewed and ready to merge, ready to test

#9856 Added windows build to github-ci
  .github/workflows/main.yml
Labels: ready for review

#9869 Fix a doxygen table.
  include/deal.II/base/bounding_box.h
Labels: Documentation

#9855 doxygen: extract everything
  doc/doxygen/options.dox.in
Labels: Documentation

#9812 Fix get_boundary_ids() and get_manifold_ids() for parallel triangulations
  include/deal.II/distributed/tria_base.h
  include/deal.II/grid/tria.h
  source/distributed/tria_base.cc
  source/grid/tria.cc
  tests/distributed_grids/get_boundary_ids_01.cc
  tests/distributed_grids/get_boundary_ids_01.mpirun=2.output
Labels: Reviewed and ready to merge, ready to test

#9866 Fix gcc warning in TBB
  bundled/tbb-2018_U2/include/tbb/internal/_concurrent_unordered_impl.h
Labels: ready to test

#9830 Doc of Tensor and SymmetricTensor improved.
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/base/tensor.h
Labels: Documentation, Reviewed and ready to merge, ready to test

#9863 Use #ifdef to guard std::async in step-69
  examples/step-69/step-69.cc
Labels: Tutorials, ready to test

#9870 Fix three tests
  tests/data_out/data_out_base_vtu_04.with_zlib=on.output.fma
  tests/grid/grid_out_svg_02.output.fma
  tests/matrix_free/dg_pbc_02.with_mpi=true.with_p4est=true.mpirun=7.output.novec
Labels: Tests, ready to test

#9875 Remove MatrixFree::DoFHandlers::level
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
Labels: Matrix-free, ready to test

#9874 Merge MatrixFree::internal_reinit for DoFHandler and hp::DoFHandler
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
Labels: Matrix-free, ready to test

#9879 Center comment
  doc/users/config.sample
Labels: High Priority :warning:

#9877 update included std headers in number.h and types.h
  include/deal.II/base/numbers.h
  include/deal.II/base/types.h
Labels: Reviewed and ready to merge, ready to test

#9710 SparsityTools::distribute_sparsity_pattern with compute_index_owner
  doc/news/changes/incompatibilities/20200322MartinKronbichler
  doc/news/changes/minor/20200322MartinKronbichler
  examples/step-18/step-18.cc
  examples/step-40/step-40.cc
  examples/step-55/step-55.cc
  examples/step-62/step-62.cc
  include/deal.II/lac/sparsity_tools.h
  source/lac/sparsity_tools.cc
  source/multigrid/mg_transfer_prebuilt.cc
  tests/dofs/dof_tools_22a.cc
  tests/dofs/sparsity_pattern_06.cc
  tests/dofs/sparsity_pattern_07.cc
  tests/fe/fe_nedelec_singularity_01.cc
  tests/fe/fe_nedelec_singularity_02.cc
  tests/gla/block_mat_02.cc
  tests/gla/block_mat_03.cc
  tests/gla/mat_03.cc
  tests/lac/linear_operator_12.cc
  tests/lac/linear_operator_12a.cc
  tests/mpi/distribute_flux_sparsity_pattern.cc
  tests/mpi/distribute_sp_01.cc
  tests/mpi/distribute_sp_02.cc
  tests/mpi/hp_step-4.cc
  tests/mpi/hp_step-40.cc
  tests/mpi/hp_step-40_variable_01.cc
  tests/mpi/interpolate_to_different_mesh_02.cc
  tests/mpi/periodicity_01.cc
  tests/mpi/petsc_step-27.cc
  tests/mpi/step-40.cc
  tests/mpi/step-40_cuthill_mckee.cc
  tests/mpi/step-40_cuthill_mckee_MPI-subset.cc
  tests/mpi/step-40_direct_solver.cc
  tests/mpi/trilinos_step-27.cc
  tests/petsc_complex/parallel_sparse_matrix_01.cc
  tests/physics/step-18-rotation_matrix.cc
  tests/physics/step-18.cc
  tests/sparsity/dynamic_sparsity_pattern_19.cc
  tests/trilinos/direct_solver_2.cc
  tests/trilinos/direct_solver_3.cc
  tests/trilinos/elide_zeros.cc
  tests/trilinos/renumbering_01.cc
  tests/trilinos/solver_control_06.cc
Labels: Linear Algebra, Parallel distributed, ready to test

#9829 FETools: Add additional lexicographic_to_hierarchic_numbering functions
  doc/news/changes/incompatibilities/20200407MartinKronbichler
  include/deal.II/fe/fe_tools.h
  include/deal.II/fe/fe_tools.templates.h
  include/deal.II/matrix_free/cuda_hanging_nodes_internal.h
  source/fe/fe_bernstein.cc
  source/fe/fe_q_base.cc
  source/fe/fe_tools.cc
  source/fe/fe_tools.inst.in
  source/fe/fe_trace.cc
  source/fe/mapping_q_eulerian.cc
  tests/bits/fe_tools_01a.cc
  tests/bits/fe_tools_01b.cc
  tests/bits/fe_tools_01c.cc
  tests/fe/numbering.cc
Labels: Finite Element, ready to test

#9884 Fix an indexing bug with multiple postprocessors
  source/numerics/data_out.cc
  tests/data_out/data_out_complex_postprocessor_03.cc
  tests/data_out/data_out_complex_postprocessor_03.with_complex_values=on.output
Labels: Bug, Reviewed and ready to merge, ready to test

#9886 Remove deprecated LinearAlgebra::distributed::Vector member functions
  doc/news/changes/incompatibilities/20200414DanielArndt
  include/deal.II/lac/la_parallel_block_vector.templates.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/la_parallel_vector.templates.h
  tests/mpi/parallel_vector_09.cc
  tests/mpi/parallel_vector_11.cc
  tests/mpi/parallel_vector_interpolate.cc
  tests/petsc/copy_to_dealvec.cc
  tests/petsc/copy_to_dealvec.with_mpi=true.mpirun=4.output
  tests/trilinos/copy_to_dealvec.cc
  tests/trilinos/copy_to_dealvec.with_mpi=true.mpirun=4.output
Labels: Linear Algebra, Reviewed and ready to merge, ready to test

#9833 fixes issue 9722 by correctly writing time data into a aggregate pvd …
  examples/step-52/step-52.cc
Labels: ready to test

#9887 Add Tvmult to Petsc PreconditionJacobi
  include/deal.II/lac/petsc_precondition.h
  source/lac/petsc_precondition.cc
  tests/petsc/preconditioner_tvmult_01.cc
  tests/petsc/preconditioner_tvmult_01.with_petsc_with_hypre=true.with_petsc_with_complex=false.mpirun=3.output
Labels: ready to test

#9882 Remove FiniteElement::[has|get]_generalized_face_support_points
  doc/news/changes/incompatibilities/20200413DanielArndt
  include/deal.II/fe/fe.h
  source/fe/fe.cc
  source/fe/fe_raviart_thomas_nodal.cc
  tests/fe/fe_data_test.cc
  tests/fe/fe_data_test.output
  tests/fe/fe_support_points_bdm.output
  tests/fe/fe_support_points_common.h
  tests/fe/fe_support_points_nedelec.output
  tests/fe/fe_support_points_q.output
  tests/fe/fe_support_points_q_bubbles.output
  tests/fe/fe_support_points_q_dg0.output
  tests/fe/fe_support_points_q_hierarchical.output
  tests/fe/fe_support_points_q_iso_q1.output
  tests/fe/fe_support_points_rt.output
  tests/fe/fe_support_points_sys_01.output
  tests/fe/fe_support_points_sys_02.output
  tests/fe/fe_support_points_sys_03.output
  tests/fe/fe_support_points_sys_04.output
  tests/fe/fe_support_points_sys_05.output
  tests/fe/fe_support_points_sys_06.output
  tests/fe/fe_support_points_sys_07.output
  tests/fe/fe_support_points_sys_08.output
  tests/fe/fe_support_points_sys_09.output
  tests/fe/fe_support_points_sys_10.output
  tests/fe/rtn_1.cc
  tests/fe/rtn_1.output
Labels: ready to test

#9826 Do not use FE_Q in MappingQGeneric
  include/deal.II/fe/mapping_q_generic.h
  source/fe/mapping_q_generic.cc
  tests/data_out/data_out_base_vtu_04.cc
  tests/data_out/data_out_base_vtu_04.with_zlib=off.output
  tests/data_out/data_out_base_vtu_04.with_zlib=on.output
  tests/data_out/data_out_base_vtu_04.with_zlib=on.output.avx512
  tests/data_out/data_out_base_vtu_04.with_zlib=on.output.fma
Labels: Mapping, ready to test

#9890 Fix set particle positions from Function<spacedim>
  include/deal.II/particles/particle_handler.h
  tests/particles/set_particle_positions_03.cc
  tests/particles/set_particle_positions_03.with_p4est=true.mpirun=1.output
Labels: ready for review, ready to test

#9893 Fix a couple of things in step-52.
  examples/step-52/step-52.cc
Labels: Reviewed and ready to merge, ready for review, ready to test

#9900 Correct the spelling of the VisIt program.
  doc/doxygen/headers/vector_valued.h
  doc/readme.html
  examples/step-18/doc/intro.dox
  examples/step-3/doc/results.dox
  examples/step-4/doc/results.dox
  examples/step-42/step-42.cc
  examples/step-44/step-44.cc
  examples/step-6/doc/results.dox
  examples/step-62/doc/results.dox
  examples/step-8/doc/results.dox
  include/deal.II/base/data_out_base.h
  include/deal.II/grid/grid_out.h
  include/deal.II/numerics/data_postprocessor.h
Labels: Documentation

#9894 Use std::ifstream instead of the detour via std::filebuf.
  source/base/parameter_handler.cc
Labels: Reviewed and ready to merge, ready for review, ready to test

#9895 Use std::enable_if instead of boost::disable_if.
  include/deal.II/particles/particle_handler.h
Labels: ready for review, ready to test

#9885 Add incompatibility entry regrading ParameterHandler::parse_input()
  doc/news/changes/incompatibilities/20200326NiklasFehn
  doc/news/changes/minor/20200326NiklasFehn
Labels: ready to test

#9899 Make the output of step-52 a bit easier to read.
  examples/step-52/step-52.cc
Labels: Tutorials, ready for review, ready to test

#9896 TrilinosML constant modes bug fix
  source/dofs/dof_tools.cc
Labels: ready to test

#9897 Use the same variable name in all output files in step-52.
  examples/step-52/step-52.cc
Labels: Tutorials, ready for review, ready to test

#9904 Move an object to the stack.
  source/grid/grid_out.cc
Labels: Miscellaneous, Reviewed and ready to merge, ready to test

#9902 Minor latex fixes in step-67 and step-69
  examples/step-67/step-67.cc
  examples/step-69/doc/intro.dox
Labels: Documentation, ready to test

#9873 Document time stepping methods to tutorial summary.
  doc/doxygen/tutorial/tutorial.h.in
Labels: Documentation

#9908 Fix type in GridOut::write_vtk
  source/grid/grid_out.cc
Labels: Reviewed and ready to merge, ready to test

#9909 GridTools::exchange_cell_data_to_ghosts replace cast
  include/deal.II/grid/grid_tools.h
Labels: Reviewed and ready to merge, ready to test

#9905 Remove some unneeded static casts.
  source/grid/grid_in.cc
  source/grid/grid_out.cc
Labels: Miscellaneous, Reviewed and ready to merge, ready to test

#9907 Do not include fe_q.h in mapping_q_generic.h
  doc/news/changes/incompatibilities/20200416MartinKronbichler
  examples/step-10/step-10.cc
  examples/step-38/step-38.cc
  examples/step-69/step-69.cc
  include/deal.II/fe/mapping_q_generic.h
  source/meshworker/scratch_data.cc
  tests/algorithms/newton_02.cc
  tests/base/cell_data_storage_01.cc
  tests/base/cell_data_storage_02.cc
  tests/base/function_cutoff_01.cc
  tests/base/function_cutoff_02.cc
  tests/base/quadrature_point_data.cc
  tests/base/quadrature_point_data_02.cc
  tests/base/quadrature_point_data_03.cc
  tests/codim_one/extract_boundary_mesh_07.cc
  tests/fe/fe_subface_values_01.cc
  tests/fe/fe_values_view_28.cc
  tests/feinterface/face_orientation_01.cc
  tests/feinterface/fe_interface_values_06.cc
  tests/feinterface/fe_interface_values_07.cc
  tests/feinterface/fe_interface_values_08.cc
  tests/feinterface/fe_interface_values_09.cc
  tests/grid/get_dof_to_support_patch_map_01.cc
  tests/lac/inhomogeneous_constraints_block.cc
  tests/manifold/spherical_manifold_02.cc
  tests/mappings/mapping_fe_field_08.cc
  tests/mappings/mapping_manifold_06.cc
  tests/mappings/mapping_manifold_07.cc
  tests/mappings/mapping_q_manifold_01.cc
  tests/matrix_free/cell_categorization_02.cc
  tests/matrix_free/face_setup_01.cc
  tests/matrix_free/matrix_vector_large_degree_01.cc
  tests/matrix_free/matrix_vector_large_degree_03.cc
  tests/meshworker/mesh_loop_04.cc
  tests/meshworker/mesh_loop_05.cc
  tests/meshworker/mesh_loop_06.cc
  tests/meshworker/scratch_data_01.cc
  tests/meshworker/scratch_data_02.cc
  tests/mpi/interpolate_to_different_mesh_02.cc
  tests/mpi/periodicity_05.cc
  tests/mpi/solution_transfer_05.cc
  tests/multigrid/constrained_dofs_05.cc
  tests/multigrid/mg_data_out_04.cc
  tests/numerics/no_flux_08.cc
  tests/numerics/no_flux_09.cc
  tests/numerics/no_flux_10.cc
  tests/numerics/no_flux_11.cc
  tests/numerics/no_flux_12.cc
  tests/numerics/no_flux_14.cc
  tests/numerics/no_flux_15.cc
  tests/numerics/project_bv_div_conf_03.cc
  tests/vector_tools/integrate_difference_05.cc
  tests/vector_tools/interpolate_with_material_id_02.cc
Labels: Finite Element, ready to test

#9910 Fix petsc/copy_to_dealvec_block
  include/deal.II/lac/la_parallel_block_vector.templates.h
  include/deal.II/lac/la_parallel_vector.templates.h
Labels: External libraries, Reviewed and ready to merge, ready to test

#9916 Improve step 8
  examples/step-6/step-6.cc
  examples/step-8/step-8.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#9918 Remove deprecated ratio member functions
  doc/news/changes/incompatibilities/20200417DanielArndt
  include/deal.II/lac/petsc_vector_base.h
  include/deal.II/lac/vector.h
  include/deal.II/lac/vector.templates.h
  source/lac/petsc_vector_base.cc
  tests/lac/vector-vector.cc
  tests/lac/vector-vector.output
  tests/petsc/48.cc
  tests/petsc/48.output
  tests/vector/complex_vector_48.cc
  tests/vector/complex_vector_48.with_complex_values=on.output
  tests/vector/vector_48.cc
  tests/vector/vector_48.output
Labels: Linear Algebra, ready to test

#9921 Fix test mpi/parallel_vector_16
  tests/mpi/parallel_vector_16.cc
Labels: Tests, ready to test

#9915 move Tria is_multilevel_hierarchy_constructed() up
  include/deal.II/distributed/shared_tria.h
  include/deal.II/distributed/tria_base.h
  source/distributed/shared_tria.cc
Labels: Reviewed and ready to merge, ready to test

#9922 Build and check documentation in CI
  .travis.yml
Labels: Build system, Documentation, Web site

#9926 Remove most <> from tutorials
  examples/step-11/step-11.cc
  examples/step-12/step-12.cc
  examples/step-12b/step-12b.cc
  examples/step-13/step-13.cc
  examples/step-14/step-14.cc
  examples/step-15/step-15.cc
  examples/step-16/step-16.cc
  examples/step-16b/step-16b.cc
  examples/step-20/doc/intro.dox
  examples/step-20/step-20.cc
  examples/step-21/step-21.cc
  examples/step-22/step-22.cc
  examples/step-23/step-23.cc
  examples/step-24/step-24.cc
  examples/step-25/step-25.cc
  examples/step-26/step-26.cc
  examples/step-27/step-27.cc
  examples/step-28/step-28.cc
  examples/step-3/step-3.cc
  examples/step-30/step-30.cc
  examples/step-35/step-35.cc
  examples/step-38/step-38.cc
  examples/step-4/step-4.cc
  examples/step-5/step-5.cc
  examples/step-51/step-51.cc
  examples/step-56/step-56.cc
  examples/step-57/step-57.cc
  examples/step-6/doc/results.dox
  examples/step-6/step-6.cc
  examples/step-61/step-61.cc
  examples/step-63/step-63.cc
  examples/step-65/step-65.cc
  examples/step-7/step-7.cc
  examples/step-8/step-8.cc
  examples/step-9/step-9.cc
Labels: Reviewed and ready to merge, ready to test

#9912 documentation: workload_imbalance
  include/deal.II/multigrid/mg_tools.h
  source/multigrid/mg_tools.cc
Labels: Documentation, ready to test

#9927 Clang tidy 9.0 fixes
  .clang-tidy
  examples/step-69/step-69.cc
  include/deal.II/lac/qr.h
  include/deal.II/optimization/solver_bfgs.h
  source/base/parameter_handler.cc
  source/lac/trilinos_precondition_ml.cc
  source/opencascade/utilities.cc
Labels: ready to test

#9924 Improve compilation times
  include/deal.II/grid/grid_tools.h
  source/fe/CMakeLists.txt
  source/grid/CMakeLists.txt
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
  source/grid/grid_tools_2.cc
  source/grid/grid_tools_nontemplates.cc
Labels: Build system, ready to test

#9932 small clang-tidy fix
  source/particles/data_out.cc
Labels: Reviewed and ready to merge, ready to test

#9934 Explicitly =delete copy operators for TaskDescriptor.
  include/deal.II/base/thread_management.h
Labels: ready for review, ready to test

#9919 Extend OutputStyle
  include/deal.II/base/parameter_handler.h
  source/base/parameter_handler.cc
  tests/parameter_handler/parameter_handler_3_with_sorting_01.cc
  tests/parameter_handler/parameter_handler_subsection_exists.cc
  tests/parameter_handler/parameter_handler_write_json.cc
  tests/parameter_handler/parameter_handler_write_xml.cc
Labels: ready to test

#9748 Improve DiscreteTime and use it in step 21
  doc/doxygen/tutorial/tutorial.h.in
  doc/news/changes/minor/20200326RezaRastak
  examples/step-21/doc/intro.dox
  examples/step-21/doc/results.dox
  examples/step-21/step-21.cc
  include/deal.II/base/discrete_time.h
  source/base/discrete_time.cc
  tests/base/discrete_time_1.cc
  tests/base/discrete_time_1.output
Labels: ready to test

#9898 Remove debug output in step-52.
  examples/step-52/step-52.cc
Labels: Tutorials, ready for review, ready to test

#9929 Split VectorTools up
  include/deal.II/base/parsed_convergence_table.h
  include/deal.II/fe/fe_series.h
  include/deal.II/numerics/fe_field_function.templates.h
  include/deal.II/numerics/vector_tools.h
  include/deal.II/numerics/vector_tools.templates.h
  include/deal.II/numerics/vector_tools_boundary.h
  include/deal.II/numerics/vector_tools_boundary.templates.h
  include/deal.II/numerics/vector_tools_common.h
  include/deal.II/numerics/vector_tools_constraints.h
  include/deal.II/numerics/vector_tools_constraints.templates.h
  include/deal.II/numerics/vector_tools_integrate_difference.h
  include/deal.II/numerics/vector_tools_integrate_difference.templates.h
  include/deal.II/numerics/vector_tools_interpolate.h
  include/deal.II/numerics/vector_tools_interpolate.templates.h
  include/deal.II/numerics/vector_tools_mean_value.h
  include/deal.II/numerics/vector_tools_mean_value.templates.h
  include/deal.II/numerics/vector_tools_point_gradient.h
  include/deal.II/numerics/vector_tools_point_gradient.templates.h
  include/deal.II/numerics/vector_tools_point_value.h
  include/deal.II/numerics/vector_tools_point_value.templates.h
  include/deal.II/numerics/vector_tools_project.h
  include/deal.II/numerics/vector_tools_project.templates.h
  include/deal.II/numerics/vector_tools_rhs.h
  include/deal.II/numerics/vector_tools_rhs.templates.h
  source/grid/grid_tools.cc
  source/numerics/point_value_history.cc
  source/numerics/vector_tools_boundary.cc
  source/numerics/vector_tools_boundary.inst.in
  source/numerics/vector_tools_constraints.cc
  source/numerics/vector_tools_integrate_difference.cc
  source/numerics/vector_tools_interpolate.cc
  source/numerics/vector_tools_mean_value.cc
  source/numerics/vector_tools_point_gradient.cc
  source/numerics/vector_tools_point_value.cc
  source/numerics/vector_tools_project.cc
  source/numerics/vector_tools_project_codim.cc
  source/numerics/vector_tools_project_hp.cc
  source/numerics/vector_tools_project_qp.cc
  source/numerics/vector_tools_project_qpmf.cc
  source/numerics/vector_tools_rhs.cc
  tests/algorithms/newton_02.cc
  tests/base/function_cutoff_01.cc
  tests/base/function_cutoff_02.cc
  tests/base/parsed_convergence_table_01.cc
  tests/base/parsed_convergence_table_03.cc
  tests/base/parsed_convergence_table_04.cc
  tests/base/parsed_convergence_table_05.cc
  tests/base/parsed_convergence_table_06.cc
Labels: ready to test

#9946 Fix a few tests
  include/deal.II/numerics/vector_tools_point_gradient.h
  include/deal.II/numerics/vector_tools_project.h
  tests/matrix_free/iterators.cc
  tests/trilinos/subtract_mean_value_04.cc
Labels: Tests, ready to test

#9943 Remove deprecated TrilinosWrappers constructors and reinitializations
  doc/news/changes/incompatibilities/20200422DanielArndt
  include/deal.II/lac/block_sparsity_pattern.h
  include/deal.II/lac/trilinos_block_sparse_matrix.h
  include/deal.II/lac/trilinos_sparse_matrix.h
  include/deal.II/lac/trilinos_sparsity_pattern.h
  source/lac/block_sparsity_pattern.cc
  source/lac/trilinos_block_sparse_matrix.cc
  source/lac/trilinos_precondition_ml.cc
  source/lac/trilinos_precondition_muelu.cc
  source/lac/trilinos_sparse_matrix.cc
  source/lac/trilinos_sparse_matrix.inst.in
  source/lac/trilinos_sparsity_pattern.cc
  tests/trilinos/64.cc
  tests/trilinos/parallel_sparse_matrix_01.cc
  tests/trilinos/sparse_matrix_02.cc
  tests/trilinos/sparse_matrix_03.cc
  tests/trilinos/sparse_matrix_04.cc
  tests/trilinos/sparse_matrix_05.cc
  tests/trilinos/sparse_matrix_07.cc
  tests/trilinos/sparse_matrix_07_rectangle.cc
  tests/trilinos/sparse_matrix_copy_from_01.cc
Labels: ready to test

#9925 Instantiate AffineConstraints::distribute_local_to_global
  source/lac/affine_constraints.inst.in
  tests/trilinos/direct_solver_3.cc
Labels: Linear Algebra, ready to test

#9953 Include ComponentMask in vector_tools_interpolate.h
  include/deal.II/numerics/vector_tools_interpolate.h
Labels: Reviewed and ready to merge, ready to test

#9949 Make parallel::shared::Triangulation::update_number_cache private
  include/deal.II/distributed/shared_tria.h
Labels: Parallel shared, Triangulation, ready to test

#9952 Remove domain_partitioner and range_partitioner from TrilinosWrappers
  doc/news/changes/incompatibilities/20200424DanielArndt
  include/deal.II/lac/trilinos_block_sparse_matrix.h
  include/deal.II/lac/trilinos_sparse_matrix.h
  include/deal.II/lac/trilinos_vector.h
  source/lac/trilinos_block_sparse_matrix.cc
  source/lac/trilinos_solver.cc
  source/lac/trilinos_sparse_matrix.cc
Labels: Linear Algebra, Reviewed and ready to merge, ready to test

#9955 Remove the last deprecations
  doc/news/changes/incompatibilities/20200424DanielArndt-1
  include/deal.II/base/numbers.h
  include/deal.II/differentiation/ad/ad_number_traits.h
  include/deal.II/lac/slepc_solver.h
  source/lac/slepc_solver.cc
Labels: Reviewed and ready to merge, ready to test

#9920 Remove doc/doxygen/tutorial
  doc/doxygen/options.dox.in
  examples/CMakeLists.txt
  examples/doxygen/CMakeLists.txt
  examples/doxygen/block_dynamic_sparsity_pattern.cc
  examples/doxygen/theta_timestepping.cc
  include/deal.II/algorithms/theta_timestepping.h
  include/deal.II/lac/block_sparsity_pattern.h
Labels: ready to test

#9956 Add documentation for hidden serialize() functions
  include/deal.II/base/aligned_vector.h
  include/deal.II/base/parameter_handler.h
  include/deal.II/base/table_handler.h
  include/deal.II/dofs/dof_handler.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/tria.h
  include/deal.II/hp/dof_handler.h
  include/deal.II/lac/sparsity_pattern.h
  include/deal.II/lac/vector.h
  include/deal.II/particles/particle.h
Labels: Documentation, Reviewed and ready to merge, ready to test

#9959 Fix doxygen appearance copy_new_triangulation_to_p4est
  source/distributed/tria.cc
Labels: Reviewed and ready to merge, ready to test

#9936 Improve calculating boolean values
  include/deal.II/fe/fe_tools.templates.h
  include/deal.II/hp/fe_collection.h
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/numerics/data_out_dof_data.templates.h
  source/base/parameter_handler.cc
  source/base/quadrature.cc
  source/base/quadrature_lib.cc
  source/distributed/tria.cc
  source/dofs/dof_handler_policy.cc
  source/dofs/dof_tools.cc
  source/lac/trilinos_sparse_matrix.cc
  source/multigrid/mg_transfer_internal.cc
Labels: Reviewed and ready to merge, ready to test

#9960 Fix calling TrilinosWrappers::BlockSparseMatrix::reinit with BlockSparseMatrix
  include/deal.II/lac/trilinos_block_sparse_matrix.h
  source/lac/trilinos_block_sparse_matrix.cc
Labels: Reviewed and ready to merge, ready to test

#9958 Remove 1D hack from p:d:t
  include/deal.II/distributed/tria.h
Labels: DoFs, ready to test

#9944 Create GridTools::compute_vertices_with_ghost_neighbors()
  include/deal.II/distributed/p4est_wrappers.h
  include/deal.II/distributed/tria_base.h
  include/deal.II/grid/grid_tools.h
  source/distributed/p4est_wrappers.cc
  source/distributed/p4est_wrappers.inst.in
  source/distributed/tria.cc
  source/distributed/tria_base.cc
  source/dofs/dof_handler_policy.cc
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
Labels: Parallel distributed, ready to test

#9951 Allow LinOp<LA::dist::Vector>(TrilinosMatrix).
  include/deal.II/lac/la_parallel_vector.h
  tests/lac/linear_operator_18.cc
  tests/lac/linear_operator_18.with_trilinos=on.output
Labels: Linear Algebra, Reviewed and ready to merge, ready to test

#9892 Step 58: The nonlinear Schroedinger equation
  doc/doxygen/tutorial/tutorial.h.in
  doc/news/changes/major/20200415step58
  examples/step-21/doc/intro.dox
  examples/step-25/doc/intro.dox
  examples/step-29/doc/intro.dox
  examples/step-31/doc/intro.dox
  examples/step-58/CMakeLists.txt
  examples/step-58/doc/builds-on
  examples/step-58/doc/intro.dox
  examples/step-58/doc/kind
  examples/step-58/doc/results.dox
  examples/step-58/doc/tooltip
  examples/step-58/step-58.cc
  include/deal.II/base/function.h
  include/deal.II/numerics/data_postprocessor.h
Labels: Reviewed and ready to merge, ready for review, ready to test

#9962 Simplify parallel::TriangulationBase::update_number_cache
  include/deal.II/distributed/fully_distributed_tria.h
  include/deal.II/distributed/shared_tria.h
  include/deal.II/distributed/tria.h
  include/deal.II/distributed/tria_base.h
  source/distributed/fully_distributed_tria.cc
  source/distributed/shared_tria.cc
  source/distributed/tria.cc
  source/distributed/tria_base.cc
Labels: Parallel distributed, ready to test

#9963 replace a std::bind by lambda
  tests/quick_tests/tbb.cc
Labels: Reviewed and ready to merge, ready to test

#9938 const is removed from private member variables of DiscreteTime
  include/deal.II/base/discrete_time.h
Labels: Reviewed and ready to merge, ready to test

#9964 Fix assertion in CUDA
  include/deal.II/base/exceptions.h
  include/deal.II/base/undefine_macros.h
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/precondition.h
  include/deal.II/lac/vector_operations_internal.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  source/lac/cuda_sparse_matrix.cu
  source/lac/cuda_vector.cu
  tests/cuda/cuda_point.cu
  tests/cuda/matrix_free_no_index_initialize.cu
Labels: GPU, Reviewed and ready to merge, ready to test

#9967 improve docu of DataOut::add_data_vector()
  include/deal.II/numerics/data_out_dof_data.h
Labels: Documentation

#9977 Duplicate include statements removed
  examples/step-47/step-47.cc
  examples/step-57/step-57.cc
  examples/step-61/step-61.cc
  include/deal.II/base/work_stream.h
  include/deal.II/differentiation/ad/adolc_number_types.h
  include/deal.II/differentiation/ad/sacado_number_types.h
  include/deal.II/lac/generic_linear_algebra.h
  include/deal.II/numerics/matrix_creator.templates.h
  include/deal.II/sundials/arkode.h
  include/deal.II/sundials/ida.h
  source/base/mpi.cc
  source/lac/trilinos_precondition_ml.cc
  source/lac/trilinos_sparse_matrix.cc
  source/lac/trilinos_sparsity_pattern.cc
  source/sundials/arkode.cc
  source/sundials/ida.cc
  source/sundials/kinsol.cc
  tests/bits/static_condensation.cc
  tests/bits/step-11.cc
  tests/bits/step-13.cc
  tests/bits/step-14.cc
  tests/bits/step-16.cc
  tests/bits/step-4.cc
  tests/bits/step-6-racoptimize-2.cc
  tests/bits/step-6-racoptimize.cc
  tests/bits/step-7.cc
  tests/bits/step-8.cc
  tests/fail/step-15.cc
  tests/fe/abf_01.cc
Labels: Reviewed and ready to merge, ready to test

#9975 Fix a funny spacing issue.
  tests/fail/fe_nothing_04.cc
  tests/hp/fe_nothing_01.cc
  tests/hp/fe_nothing_02.cc
  tests/hp/fe_nothing_03.cc
  tests/hp/fe_nothing_05.cc
  tests/hp/fe_nothing_06.cc
  tests/hp/fe_nothing_07.cc
  tests/hp/fe_nothing_08.cc
  tests/hp/fe_nothing_09.cc
  tests/hp/fe_nothing_11.cc
  tests/hp/fe_nothing_15.cc
  tests/hp/fe_nothing_16.cc
  tests/hp/fe_nothing_20.cc
  tests/hp/fe_nothing_21.cc
  tests/hp/interpolate_nothing_03.cc
Labels: Reviewed and ready to merge, ready for review, ready to test

#9970 remove empty virtual destructors
  include/deal.II/lac/eigen.h
  include/deal.II/lac/solver_fire.h
  include/deal.II/lac/solver_relaxation.h
Labels: Reviewed and ready to merge, ready to test

#9985 Remove two unused headers.
  include/deal.II/optimization/line_minimization.h
Labels: Reviewed and ready to merge, ready to test

#9980 Improve error message in SymmetricTensor constructor.
  include/deal.II/base/symmetric_tensor.h
Labels: Reviewed and ready to merge, ready to test

#9981 qualify internal namespace with dealii::
  include/deal.II/lac/la_vector.templates.h
Labels: Reviewed and ready to merge, ready to test

#9979 Implement hessian and laplacian on ConstantFunction.
  include/deal.II/base/function.h
  include/deal.II/base/function.templates.h
Labels: Reviewed and ready to merge, ready to test

#9983 rename header guards in noncontiguous_partitioner
  include/deal.II/base/mpi_noncontiguous_partitioner.h
  include/deal.II/base/mpi_noncontiguous_partitioner.templates.h
Labels: Reviewed and ready to merge, ready to test

#9974 Restrict mpi/petsc_step-27
  tests/mpi/petsc_step-27.with_p4est=true.with_petsc_with_hypre=true.with_petsc_with_complex=false.mpirun=1.output
  tests/mpi/petsc_step-27.with_p4est=true.with_petsc_with_hypre=true.with_petsc_with_complex=false.mpirun=2.output
Labels: ready to test

#9968 Precalculate hp::FEValues.
  doc/news/changes/minor/20200427Fehling
  include/deal.II/hp/fe_values.h
  source/hp/fe_values.cc
  tests/hp/fe_values_01.cc
  tests/hp/fe_values_01.output
Labels: Reviewed and ready to merge, ready to test

#9264 added measure computation for distorted 2d cells
  doc/news/changes/minor/20200123NicolaGiuliani
  source/grid/tria_accessor.cc
  tests/codim_one/measure_of_distorted_codim_one_face.cc
  tests/codim_one/measure_of_distorted_codim_one_face.output
  tests/grid/measure_of_3d_face_01.output
Labels: Reviewed and ready to merge, Triangulation, ready to test

#9984 CI: clang-tidy all headers
  contrib/utilities/run_clang_tidy.sh
  include/deal.II/base/mpi_noncontiguous_partitioner.h
  include/deal.II/base/partitioner.templates.h
  source/dummy.cc
Labels: ready to test

#9950 Add ParameterHandler::print_parameters with std::string as input.
  doc/news/changes/minor/20200424NiklasFehnLucaHeltai
  include/deal.II/base/parameter_acceptor.h
  include/deal.II/base/parameter_handler.h
  source/base/parameter_acceptor.cc
  source/base/parameter_handler.cc
  tests/parameter_handler/parameter_acceptor_05.output
  tests/parameter_handler/parameter_acceptor_06.output
  tests/parameter_handler/parameter_acceptor_07.expect=run.output
  tests/parameter_handler/parameter_acceptor_09.cc
  tests/parameter_handler/parameter_acceptor_09.output
  tests/parameter_handler/parameter_handler_25.output.std
  tests/parameter_handler/parameter_handler_27.cc
  tests/parameter_handler/parameter_handler_27.output
  tests/parameter_handler/parameter_handler_28.cc
  tests/parameter_handler/parameter_handler_28.output
Labels: ready for review, ready to test

#9992 speed up tests/non_matching/coupling_08
  tests/non_matching/coupling_08.cc
  tests/non_matching/coupling_08.with_umfpack=true.output
Labels: Quadrature, Reviewed and ready to merge, ready to test

#9986 Fix copying hp::FEValues objects.
  doc/news/changes/minor/20200428Bangerth
  include/deal.II/hp/fe_values.h
  source/hp/fe_values.cc
  tests/hp/hp_fe_values_copy.cc
  tests/hp/hp_fe_values_copy.output
Labels: ready for review, ready to test
