Repository dealii/dealii, pull requests merged in 2020-11, with the labels that each got.

#10439 Introduce internal::TriangulationImplementation::Policy
  include/deal.II/grid/tria.h
  source/grid/tria.cc
Labels: Triangulation, ready to test

#11129 fix type in Physics rotation_matrix_2d and 3d
  include/deal.II/physics/transformations.h
Labels: Reviewed and ready to merge, ready to test

#11127 Transfinite interpolation: inverse quadratic approximation in pull-back
  doc/news/changes/minor/20201101MartinKronbichler
  include/deal.II/fe/mapping_q_internal.h
  include/deal.II/grid/manifold_lib.h
  source/grid/manifold_lib.cc
Labels: Manifold, ready to test

#11130 set number_cache.n_global_dofs to the right size in MultiGrid scenario
  source/dofs/dof_handler_policy.cc
Labels: DoFs, Reviewed and ready to merge, ready to test

#11126 Transfinite interpolation: Fix refresh of Jacobian
  source/grid/manifold_lib.cc
Labels: Manifold, ready to test

#10490 Give each cell a globally unique (level) ID
  doc/news/changes/minor/20200612Munch
  include/deal.II/distributed/tria_base.h
  include/deal.II/grid/tria.h
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_levels.h
  source/distributed/tria_base.cc
  source/grid/tria.cc
  source/grid/tria_accessor.cc
  tests/grid/global_ids_01.cc
  tests/grid/global_ids_01.with_mpi=true.with_p4est=true.mpirun=1.output
  tests/grid/global_ids_01.with_mpi=true.with_p4est=true.mpirun=4.output
  tests/grid/global_ids_03.cc
  tests/grid/global_ids_03.with_mpi=true.with_p4est=true.mpirun=1.output
  tests/grid/global_ids_03.with_mpi=true.with_p4est=true.mpirun=4.output
Labels: Parallel distributed, Triangulation, ready for review, ready to test

#11103 Pass n_q_points_1D to Simplex::QGauss
  include/deal.II/simplex/quadrature_lib.h
  source/simplex/quadrature_lib.cc
  tests/simplex/fe_lib_02.cc
  tests/simplex/poisson_01.cc
  tests/simplex/poisson_02.cc
  tests/simplex/q_projection_01.cc
  tests/simplex/quadrature_lib_01.cc
  tests/simplex/quadrature_lib_01.output
  tests/simplex/step-12.cc
  tests/simplex/step-18.cc
Labels: Quadrature, ready to test

#11092 MatrixFree: add DoFInfo::dof_indices_contiguous_sm
  include/deal.II/matrix_free/dof_info.h
  include/deal.II/matrix_free/dof_info.templates.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
  include/deal.II/matrix_free/task_info.h
  source/base/mpi_consensus_algorithms.cc
Labels: Matrix-free, ready to test

#11125 Update ghost particles without rebuilding them
  include/deal.II/particles/particle_handler.h
  source/particles/particle_handler.cc
  tests/particles/particle_handler_19.cc
  tests/particles/particle_handler_19.with_p4est=true.mpirun=2.output
Labels: ready to test

#11098 Introduce VectorDataExchange::Full
  include/deal.II/matrix_free/dof_info.h
  include/deal.II/matrix_free/dof_info.templates.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
  include/deal.II/matrix_free/vector_data_exchange.h
  source/matrix_free/vector_data_exchange.cc
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#11135 Extend docu on global_active_cell_index
  include/deal.II/grid/tria_accessor.h
  source/grid/tria.cc
Labels: Documentation, Reviewed and ready to merge, Triangulation, ready to test

#11137 Introduce Utilities::MPI::mpi_processes_within_communicator
  include/deal.II/base/mpi.h
  include/deal.II/matrix_free/matrix_free.templates.h
  source/base/mpi.cc
Labels: Parallel distributed, Reviewed and ready to merge, ready to test

#11123 Hide hp_capability_enabled parameter.
  examples/step-27/doc/intro.dox
  examples/step-27/step-27.cc
  examples/step-46/doc/intro.dox
  examples/step-46/step-46.cc
  include/deal.II/dofs/dof_handler.h
  include/deal.II/matrix_free/matrix_free.templates.h
  include/deal.II/numerics/vector_tools_point_gradient.templates.h
  include/deal.II/numerics/vector_tools_point_value.templates.h
  source/distributed/solution_transfer.cc
  source/dofs/block_info.cc
  source/dofs/dof_handler.cc
  source/dofs/dof_tools.cc
  source/dofs/dof_tools_constraints.cc
  source/dofs/dof_tools_sparsity.cc
  source/hp/dof_handler.cc
  source/numerics/solution_transfer.cc
  tests/grid/accessor_04.cc
  tests/mpi/solution_transfer_06.cc
  tests/mpi/solution_transfer_06.with_p4est=true.mpirun=1.output
  tests/multigrid/mg_level_object_args_01.cc
Labels: ready to test

#11139 Avoid the use of 'illegal' in error messages.
  include/deal.II/grid/tria_accessor.templates.h
Labels: Reviewed and ready to merge, ready to test

#11144 Label functions as such (and not as classes).
  include/deal.II/grid/grid_generator.h
Labels: Documentation

#11143 step-7: mark some ints as doubles
  examples/step-7/step-7.cc
Labels: Reviewed and ready to merge

#11140 Store reference_cell_types in Triangulation
  include/deal.II/distributed/tria_base.h
  include/deal.II/grid/tria.h
  source/distributed/tria_base.cc
  source/grid/tria.cc
Labels: Triangulation, ready for review, ready to test

#11134 Expose mesh loop bug for anisotropic grids.
  doc/news/changes/minor/20201103LucaHeltai
  include/deal.II/meshworker/mesh_loop.h
  tests/meshworker/mesh_loop_anistropic_01.cc
  tests/meshworker/mesh_loop_anistropic_01.output
Labels: Anisotropic, Bug, ready for review, ready to test

#11147 Simplify simplify_categorize_by_boundary_ids
  include/deal.II/matrix_free/tools.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#11141 Add internal::TriangulationImplementation::ImplementationMixedMesh
  include/deal.II/grid/tria.h
  source/grid/tria.cc
Labels: Triangulation, ready to test

#11131 Transfinite interpolation: add a test
  tests/manifold/transfinite_manifold_11.cc
  tests/manifold/transfinite_manifold_11.output
Labels: Tests, ready to test

#11145 Adjusted mg_constrained_dofs for usage of own IndexSets
  include/deal.II/multigrid/mg_constrained_dofs.h
Labels: Reviewed and ready to merge, ready to test

#11097 Use dof_indices_contiguous_sm in evaluation functions
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, ready to test

#11150 Use mpi_processes_within_communicator
  source/matrix_free/vector_data_exchange.cc
Labels: Matrix-free, ready to test

#11109 pass MPI_Comm by const ref
  include/deal.II/base/data_out_base.h
  include/deal.II/base/hdf5.h
  include/deal.II/base/mpi.h
  include/deal.II/base/partitioner.h
  include/deal.II/base/process_grid.h
  include/deal.II/base/timer.h
  include/deal.II/distributed/fully_distributed_tria.h
  include/deal.II/distributed/grid_refinement.h
  include/deal.II/distributed/shared_tria.h
  include/deal.II/distributed/tria.h
  include/deal.II/distributed/tria_base.h
  include/deal.II/dofs/number_cache.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/tria_description.h
  include/deal.II/lac/affine_constraints.h
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/la_parallel_block_vector.h
  include/deal.II/lac/la_parallel_block_vector.templates.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/lac/petsc_precondition.h
  include/deal.II/sundials/arkode.h
  include/deal.II/sundials/ida.h
  include/deal.II/sundials/kinsol.h
  source/base/data_out_base.cc
  source/base/data_out_base.inst.in
  source/base/hdf5.cc
  source/base/mpi.cc
  source/base/partitioner.cc
  source/base/process_grid.cc
  source/base/timer.cc
  source/distributed/fully_distributed_tria.cc
  source/distributed/grid_refinement.cc
  source/distributed/grid_refinement.inst.in
  source/distributed/shared_tria.cc
  source/distributed/tria.cc
  source/distributed/tria_base.cc
  source/dofs/number_cache.cc
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
  source/grid/tria_description.cc
  source/grid/tria_description.inst.in
  source/lac/petsc_precondition.cc
  source/multigrid/mg_level_global_transfer.cc
  source/sundials/arkode.cc
  source/sundials/ida.cc
  source/sundials/kinsol.cc
Labels: ready to test

#11151 Fix sm-mode L:d:V for zero sized vectors
  include/deal.II/lac/la_parallel_vector.templates.h
Labels: Discussion, Linear Algebra, ready to test

#11133 Rework DoFHandler connections to underlying Triangulation.
  include/deal.II/dofs/dof_accessor.templates.h
  include/deal.II/dofs/dof_handler.h
  source/dofs/dof_handler.cc
  source/hp/fe_collection.cc
Labels: DoFs, hp, ready to test

#11157 Fix fe_face_evaluation_process_and_io for multiple components
  include/deal.II/matrix_free/evaluation_kernels.h
Labels: Bug, Matrix-free, ready to test

#11154 Fix compute_shared_memory_contiguous_indices
  include/deal.II/matrix_free/matrix_free.templates.h
Labels: Matrix-free, ready to test

#11156 Improve VectorDataExchange::Full::reset_ghost_values
  source/matrix_free/vector_data_exchange.cc
Labels: Matrix-free, ready to test

#11162 Add reference to skew-symmetric implementation in step-67
  examples/step-67/doc/results.dox
Labels: Documentation, Reviewed and ready to merge, Tutorials

#10899 Support ExodusII with GridIn
  cmake/configure/configure_2_trilinos.cmake
  doc/external-libs/trilinos.html
  doc/news/changes/major/20200909DavidWells
  include/deal.II/base/config.h.in
  include/deal.II/base/exceptions.h
  include/deal.II/base/undefine_macros.h
  include/deal.II/grid/connectivity.h
  include/deal.II/grid/grid_in.h
  include/deal.II/grid/reference_cell.h
  source/base/exceptions.cc
  source/grid/grid_in.cc
  tests/grid/grid_in_exodusii.cc
  tests/grid/grid_in_exodusii.with_trilinos_with_seacas=on.output
  tests/grid/grids/exodusii/five-3d.e
  tests/grid/grids/exodusii/five.e
  tests/grid/grids/exodusii/four-p.e
  tests/grid/grids/exodusii/four-sidesets.e
  tests/grid/grids/exodusii/four.e
Labels: External libraries, Reviewed and ready to merge, Triangulation, ready for review, ready to test

#11161 Functions of hp::Refinement now only available for DoFHandler in hp mode.
  source/hp/refinement.cc
Labels: hp, ready to test

#11165 Fix typo in class documentation of "FEEvaluation"
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#11164 Define DEAL_II_MPI_VERSION_GTE also for serial compilation
  include/deal.II/base/config.h.in
Labels: ready to test

#11170 Deprecated FiniteElement::operator[].
  doc/news/changes/incompatibilities/20201111Fehling
  include/deal.II/fe/fe.h
Labels: Reviewed and ready to merge, ready to test

#11163 Move GhostParticlePartitioner
  include/deal.II/particles/particle_handler.h
  include/deal.II/particles/partitioner.h
Labels: Particles, ready to test

#11159 parallel running version of multigrid Cuthill McKee reordering
  include/deal.II/dofs/dof_renumbering.h
  include/deal.II/dofs/dof_tools.h
  source/dofs/dof_renumbering.cc
  source/dofs/dof_renumbering.inst.in
  source/dofs/dof_tools.cc
  source/dofs/dof_tools.inst.in
  tests/mpi/extract_locally_active_level_dofs.cc
  tests/mpi/extract_locally_active_level_dofs.mpirun=10.with_p4est=true.output
  tests/mpi/extract_locally_active_level_dofs.mpirun=4.with_p4est=true.output
  tests/mpi/renumber_cuthill_mckee.cc
  tests/mpi/renumber_cuthill_mckee.mpirun=1.with_p4est=true.output
  tests/mpi/renumber_cuthill_mckee.mpirun=4.with_p4est=true.output
Labels: DoFs, ready to test

#11179 Step-37: small update to the documentation
  examples/step-37/doc/intro.dox
Labels: Reviewed and ready to merge, Tutorials

#11169 Deprecate MatrixFree::reinit() functions with default Mapping argument
  doc/news/changes/incompatibilities/20201111Munch
  examples/step-37/step-37.cc
  examples/step-48/step-48.cc
  examples/step-50/step-50.cc
  examples/step-59/step-59.cc
  include/deal.II/matrix_free/matrix_free.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#11176 QCollection<dim> accept Quadrature<1>
  doc/news/changes/minor/20201112Munch
  include/deal.II/hp/q_collection.h
Labels: Matrix-free, ready to test

#11128 ADHelpers: Fix indexing for symm tensor extractor
  doc/news/changes/minor/20201101Jean-PaulPelteret
  include/deal.II/differentiation/ad/ad_helpers.h
  tests/ad_common_tests/helper_scalar_coupled_2_components_06a.h
  tests/adolc/helper_scalar_coupled_2_components_06a_1.cc
  tests/adolc/helper_scalar_coupled_2_components_06a_1.output
  tests/adolc/helper_scalar_coupled_2_components_06a_2.cc
  tests/adolc/helper_scalar_coupled_2_components_06a_2.output
  tests/sacado/helper_scalar_coupled_2_components_06a_1.cc
  tests/sacado/helper_scalar_coupled_2_components_06a_1.output
  tests/sacado/helper_scalar_coupled_2_components_06a_2.cc
  tests/sacado/helper_scalar_coupled_2_components_06a_2.output
  tests/sacado/helper_scalar_coupled_2_components_06a_3.cc
  tests/sacado/helper_scalar_coupled_2_components_06a_3.output
  tests/sacado/helper_scalar_coupled_2_components_06a_4.cc
  tests/sacado/helper_scalar_coupled_2_components_06a_4.output
Labels: Automatic differentiation, Bug, ready to test

#11180 Add missing const MPI_Comm &
  source/grid/tria_description.cc
  source/grid/tria_description.inst.in
Labels: Reviewed and ready to merge, ready to test

#11181 Deprecate MatrixFree::get_dof_handler.
  doc/news/changes/incompatibilities/20201113Fehling
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
  source/matrix_free/matrix_free.inst.in
Labels: ready to test

#11183 MatrixFree: deprecate n_macro_cells
  examples/step-37/doc/results.dox
  examples/step-37/step-37.cc
  examples/step-50/step-50.cc
  examples/step-67/step-67.cc
  include/deal.II/matrix_free/dof_info.templates.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/mapping_info.templates.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/operators.h
  include/deal.II/multigrid/multigrid.h
  include/deal.II/numerics/vector_tools_project.templates.h
  source/matrix_free/task_info.cc
  tests/lac/utilities_02.cc
  tests/mappings/mapping_q_eulerian_08.cc
  tests/matrix_free/cell_categorization.cc
  tests/matrix_free/cell_categorization_02.cc
  tests/matrix_free/cell_level_and_index.cc
  tests/matrix_free/compress_mapping.cc
  tests/matrix_free/dof_info_01.cc
  tests/matrix_free/dof_info_02.cc
  tests/matrix_free/jxw_values.cc
  tests/matrix_free/laplace_operator_02.cc
  tests/matrix_free/quadrature_points.cc
  tests/matrix_free/step-37-inhomogeneous-1.cc
  tests/matrix_free/step-37.cc
  tests/matrix_free/step-48.cc
  tests/matrix_free/step-48b.cc
  tests/matrix_free/step-48c.cc
  tests/matrix_free/stokes_computation.cc
  tests/mpi/step-37.cc
  tests/numerics/project_parallel_qpmf_common.h
Labels: Matrix-free, ready to test

#11182 Remove DoFHandlerType from internal::DataOutImplementation::{DataEntryBase|DataEntry|MGDataEntry}.
  include/deal.II/numerics/data_out_dof_data.h
  include/deal.II/numerics/data_out_dof_data.templates.h
  source/numerics/data_out_dof_data.inst.in
  source/numerics/data_out_dof_data_codim.inst.in
Labels: ready to test

#11184 Avoid name macro_cell in matrix-free implementation
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
  source/matrix_free/task_info.cc
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#11187 Fix typo in step 67
  examples/step-67/doc/results.dox
Labels: Documentation, Reviewed and ready to merge

#11171 Deprecate hp::DoFHandler.
  include/deal.II/distributed/error_predictor.h
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/dofs/dof_accessor.templates.h
  include/deal.II/dofs/dof_handler.h
  include/deal.II/grid/tria.h
  include/deal.II/hp/dof_handler.h
  include/deal.II/matrix_free/matrix_free.h
  source/distributed/error_predictor.cc
  source/dofs/dof_accessor_get.cc
  source/dofs/dof_accessor_set.cc
  source/hp/dof_handler.cc
  source/hp/refinement.cc
  tests/hp/get_interpolated_dof_values_01.debug.output
  tests/hp/set_dof_values_by_interpolation_01.debug.output
Labels: ready to test

#11192 Use upper-case letters for vectors in the documentation.
  include/deal.II/numerics/vector_tools.h
Labels: Reviewed and ready to merge

#11177 Make assert more verbose in FEEvaluation
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Discussion, Matrix-free, ready to test

#11193 Better document a bunch of functions.
  include/deal.II/fe/fe_values.h
Labels: ready to test

#11186 Make ShapeInfo compatible with Simplex::FE_P and Simplex::QGauss
  include/deal.II/matrix_free/shape_info.h
  include/deal.II/matrix_free/shape_info.templates.h
  tests/simplex/matrix_free_shape_info_01.cc
  tests/simplex/matrix_free_shape_info_01.with_simplex_support=on.output
Labels: Matrix-free, ready to test

#11189 Deprecate DataPostprocessorInputs::CommonInputs::{get|set}_cell.
  doc/news/changes/incompatibilities/20201115Fehling-2
  include/deal.II/numerics/data_postprocessor.h
  source/numerics/data_out.cc
Labels: ready to test

#11160 Deprecate DoFHandler initialization interface.
  doc/news/changes/incompatibilities/20201030Fehling
  examples/step-69/step-69.cc
  include/deal.II/dofs/dof_handler.h
  source/dofs/dof_handler.cc
Labels: Discussion, DoFs, Reviewed and ready to merge, hp, ready to test

#11194 Better document some FEValues functions.
  include/deal.II/fe/fe_values.h
  source/fe/fe_values.cc
Labels: Documentation, ready to test

#11196 Actually use ShapeInfo for Simplex::FE_P and Simplex::QGauss
  include/deal.II/matrix_free/mapping_info.h
  include/deal.II/matrix_free/mapping_info.templates.h
Labels: Matrix-free, ready to test

#11200 [CI] OSX tester: change to gcc-10.
  .github/workflows/osx.yml
Labels: Reviewed and ready to merge

#11199 Add particle update data function to overwrite particle information
  include/deal.II/particles/particle.h
  source/particles/particle.cc
  source/particles/particle_handler.cc
Labels: ready to test

#11202 Improve MGTransferMatrixFree::interpolate_to_mg
  include/deal.II/multigrid/mg_transfer_matrix_free.h
Labels: Geometric multigrid, Reviewed and ready to merge, ready to test

#11203 Add simplex elements to the MF permitted list.
  include/deal.II/matrix_free/shape_info.templates.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#11205 Avoid printing gcc information in OSX CI
  .github/workflows/osx.yml
Labels: Reviewed and ready to merge

#11197 doxygen: simplify mesh_loop arguments
  include/deal.II/meshworker/mesh_loop.h
Labels: Documentation, Reviewed and ready to merge

#11208 Fix tests with MGTransferMatrixFree::interpolate_to_mg
  include/deal.II/multigrid/mg_transfer_matrix_free.h
  tests/mappings/mapping_q_eulerian_08.cc
  tests/matrix_free/interpolate_to_mg.cc
Labels: Geometric multigrid, Reviewed and ready to merge, ready to test

#11191 Improve the documentation of a couple of AffineConstraints functions.
  include/deal.II/lac/affine_constraints.h
  include/deal.II/lac/affine_constraints.templates.h
Labels: DoFs, Reviewed and ready to merge, ready to test

#11213 Fix bug in constructor of FEEvaluationBaseData
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Bug, Matrix-free, ready to test

#11209 Introduce MappingCollection in MatrixFree
  include/deal.II/matrix_free/mapping_info.h
  include/deal.II/matrix_free/mapping_info.templates.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
  source/matrix_free/matrix_free.inst.in
Labels: ready to test

#11212 FEEvaluation: make active_fe_index and active_quad_index an optional …
  include/deal.II/matrix_free/fe_evaluation.h
  tests/matrix_free/matrix_vector_hp_no_template.cc
  tests/matrix_free/matrix_vector_hp_no_template.output
  tests/matrix_free/matrix_vector_mf.h
Labels: Matrix-free, ready to test

#11207 Use hp::MappingCollection initialize_cell_range
  include/deal.II/matrix_free/mapping_info.templates.h
Labels: ready to test

#11223 Remove a name
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Documentation

#11225 Enable DataOut for mixed meshes
  source/numerics/data_out.cc
Labels: ready to test

#11050 Add documentation for HDF5 and exceptions
  include/deal.II/base/hdf5.h
Labels: Documentation

#11219 Deprecated DoFHandlerType in DataOutStack.
  doc/news/changes/incompatibilities/20201120Fehling-2
  include/deal.II/numerics/data_out_stack.h
  source/numerics/data_out_stack.cc
  source/numerics/data_out_stack.inst.in
Labels: ready to test

#11095 Document reference cells in simplex module page
  doc/doxygen/headers/simplex.h
  doc/doxygen/images/reference_cells_0.png
  doc/doxygen/images/reference_cells_1.png
  doc/doxygen/images/reference_cells_2.png
  doc/doxygen/images/reference_cells_3.png
  doc/doxygen/images/reference_cells_4.png
  doc/doxygen/images/reference_cells_5.png
Labels: Documentation, Triangulation

#11214 Updated documentation to avoid hp::DoFHandler.
  include/deal.II/base/work_stream.h
  include/deal.II/distributed/cell_weights.h
  include/deal.II/distributed/error_predictor.h
  include/deal.II/distributed/shared_tria.h
  include/deal.II/distributed/solution_transfer.h
  include/deal.II/dofs/block_info.h
  include/deal.II/dofs/dof_renumbering.h
  include/deal.II/dofs/dof_tools.h
  include/deal.II/fe/fe_enriched.h
  include/deal.II/fe/fe_nothing.h
  include/deal.II/fe/fe_tools.h
  include/deal.II/grid/grid_generator.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/intergrid_map.h
  include/deal.II/grid/tria_iterator.h
  include/deal.II/hp/fe_collection.h
  include/deal.II/matrix_free/mapping_info.templates.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/numerics/data_out_faces.h
  include/deal.II/numerics/smoothness_estimator.h
  include/deal.II/numerics/solution_transfer.h
  include/deal.II/numerics/vector_tools_boundary.h
  include/deal.II/numerics/vector_tools_integrate_difference.h
  include/deal.II/numerics/vector_tools_point_value.h
  include/deal.II/numerics/vector_tools_project.h
  source/dofs/dof_accessor_get.cc
  source/dofs/dof_handler.cc
Labels: Documentation, ready to test

#11227 Work on some asserts in MatrixFree
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/mapping_info.templates.h
Labels: ready to test

#11228 Drop the words scatter/gather in the documentation of such functions.
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/lac/affine_constraints.h
Labels: Reviewed and ready to merge, ready to test

#11229 Fix MappingQEulerian::clone()
  source/fe/mapping_q_eulerian.cc
Labels: Bug, Mapping, ready to test

#11226 Use EvaluatorTensorProduct in Simplex code path
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/tensor_product_kernels.h
Labels: Matrix-free, ready to test

#11224 Add hp capabilities to Simplex::FE_P
  include/deal.II/simplex/fe_lib.h
  source/simplex/fe_lib.cc
Labels: Finite Element, ready to test

#11190 Deprecated DoFHandlerType in MappingFEField.
  doc/news/changes/incompatibilities/20201115Fehling
  examples/step-60/step-60.cc
  include/deal.II/fe/mapping_fe_field.h
  source/fe/mapping_fe_field.cc
  source/fe/mapping_fe_field.inst.in
Labels: Reviewed and ready to merge, ready to test

#11230 Provide a serial implementation of ConsensusAlgorithms::Interface
  include/deal.II/base/mpi_consensus_algorithms.h
  include/deal.II/base/mpi_consensus_algorithms.templates.h
  source/base/mpi_consensus_algorithms.cc
Labels: Bug, Parallel distributed, Reviewed and ready to merge, ready to test

#11232 Fix output of tests/mpi/parallel_partitioner_05
  tests/mpi/parallel_partitioner_05.mpirun=4.output
Labels: Parallel distributed, Reviewed and ready to merge, ready to test

#11231 Make tests/simplex/step-18 more robust
  tests/simplex/step-18.cc
  tests/simplex/step-18.mpirun=1.with_petsc=false.with_simplex_support=on.output
  tests/simplex/step-18.mpirun=1.with_petsc=true.with_simplex_support=on.output
Labels: Reviewed and ready to merge, Tests, ready to test

#11238 Simplify some code with stuff from later C++ standards.
  include/deal.II/lac/block_vector_base.h
Labels: ready to test

#11218 Better initial guess for Chebyshev eigenvalue estimate with BlockVector
  include/deal.II/lac/precondition.h
Labels: Linear Algebra, Reviewed and ready to merge, ready to test

#11167 Add Poisson/Helmholtz test: MatrixFree + simplex mesh
  tests/simplex/matrix_free_01.cc
  tests/simplex/matrix_free_01.with_simplex_support=on.output
Labels: Matrix-free, ready to test

#11236 Rename an internal variable from 'import' to 'importer'.
  include/deal.II/lac/trilinos_epetra_communication_pattern.h
  source/lac/trilinos_epetra_communication_pattern.cc
Labels: ready to test

#11237 Avoid using 'import' as function name in internal interfaces.
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/lac/vector_operations_internal.h
Labels: ready to test

#11233 Vector data exchange zero vector region vector
  include/deal.II/matrix_free/matrix_free.h
  tests/simplex/matrix_free_01.cc
Labels: ready to test

#11217 Add Poisson/Helmholtz test: MatrixFree + mixed mesh
  tests/simplex/matrix_free_02.cc
  tests/simplex/matrix_free_02.with_simplex_support=on.output
Labels: ready to test

#11239 Update some comments in PreconditionChebyshev::estimate_eigenvalues
  include/deal.II/lac/precondition.h
Labels: Linear Algebra, Reviewed and ready to merge, ready to test

#11240 Multigrid: Only call MGLevelObject::resize() if necessary
  include/deal.II/multigrid/multigrid.templates.h
Labels: Geometric multigrid, ready to test

#11243 Simplify some code with stuff from later C++ standards.
  include/deal.II/lac/affine_constraints.h
Labels: ready to test

#11253 Update documentation to avoid deprecated functions ...
  include/deal.II/dofs/dof_handler.h
  include/deal.II/lac/affine_constraints.h
  include/deal.II/lac/sparsity_tools.h
Labels: Reviewed and ready to merge

#11246 MatrixFree: assert that in hp-mode only a single DoFHandler is used
  include/deal.II/matrix_free/matrix_free.templates.h
Labels: Matrix-free, ready for review, ready to test

#11248 MatrixFree: use active_fe_indices within FaceComparator
  include/deal.II/matrix_free/face_setup_internal.h
  include/deal.II/matrix_free/matrix_free.templates.h
Labels: ready for review, ready to test

#11255 MatrixFree: setup SM capabilities only in non-hp mode
  include/deal.II/matrix_free/matrix_free.templates.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#11257 Add hp capabilities to Simplex::FE_DGP
  include/deal.II/simplex/fe_lib.h
  source/simplex/fe_lib.cc
Labels: Reviewed and ready to merge, hp, ready to test

#11258 MatrixFree: consider cell type within reorder_face_derivative_indices()
  include/deal.II/matrix_free/mapping_info.templates.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#11264 Fix indentation CI
  .github/workflows/indent.yml
Labels: ready to test

#11247 Make MappingInfo::initialize_faces work for multiple fe indices
  include/deal.II/matrix_free/mapping_info.h
  include/deal.II/matrix_free/mapping_info.templates.h
Labels: ready for review, ready to test

#11265 remove data_interpretations in step-68
  examples/step-68/step-68.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#11244 Correct poor naming of a class.
  include/deal.II/lac/affine_constraints.h
  tests/lac/is_block_matrix.cc
Labels: Reviewed and ready to merge, ready to test

#11256 Simplex: create simplex_grids.h for common grid (test) functions
  tests/simplex/matrix_free_02.cc
  tests/simplex/simplex_grids.h
Labels: ready to test

#11263 ShapeInfo: remove outdated comments
  include/deal.II/matrix_free/shape_info.h
Labels: Documentation, Matrix-free

#11261 MatrixFree: set up shape_values_face and shape_gradients_face
  include/deal.II/matrix_free/mapping_info.templates.h
  include/deal.II/matrix_free/matrix_free.templates.h
  include/deal.II/matrix_free/shape_info.h
  include/deal.II/matrix_free/shape_info.templates.h
  include/deal.II/matrix_free/util.h
Labels: Matrix-free, ready to test

#11262 Use ShapeInfo::shape_values_face for evaluation/integration
  include/deal.II/matrix_free/evaluation_kernels.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#11275 Mark a number of input arguments as 'const'.
  include/deal.II/lac/affine_constraints.h
  include/deal.II/lac/affine_constraints.templates.h
Labels: Reviewed and ready to merge, ready to test

#11277 Fix MGLevelObject variadic template constructor with default arguments
  include/deal.II/base/mg_level_object.h
Labels: ready to test

#11281 CUDA: fix failing tests
  tests/cuda/matrix_free_matrix_vector_10.cu
  tests/cuda/matrix_free_matrix_vector_10a.cu
Labels: GPU, Reviewed and ready to merge
