Repository dealii/dealii, pull requests merged in 2020-05, with the labels that each got.

#9996 CMake: Clear all cached variables in FindGINKGO.cmake
  cmake/modules/FindGINKGO.cmake
Labels: Reviewed and ready to merge

#9945 Remove parallel::TriangulationBase::compute_n_locally_owned_active_cellls_per_processor
  examples/step-55/step-55.cc
  include/deal.II/base/mpi.h
  include/deal.II/distributed/tria_base.h
  include/deal.II/dofs/dof_handler.h
  include/deal.II/hp/dof_handler.h
  source/distributed/tria_base.cc
  source/dofs/number_cache.cc
  tests/distributed_grids/dof_handler_number_cache.cc
  tests/distributed_grids/hp_dof_handler_number_cache.cc
  tests/dofs/dof_handler_number_cache.cc
  tests/dofs/dof_handler_number_cache_02.cc
  tests/dofs/dof_handler_number_cache_02.output
  tests/gla/mat_04.cc
  tests/hp/dof_handler_number_cache.cc
  tests/matrix_free/dg_pbc_01.cc
  tests/mpi/cell_weights_01.cc
  tests/mpi/cell_weights_01_back_and_forth_01.cc
  tests/mpi/cell_weights_01_back_and_forth_02.cc
  tests/mpi/cell_weights_02.cc
  tests/mpi/cell_weights_03.cc
  tests/mpi/cell_weights_04.cc
  tests/mpi/cell_weights_05.cc
  tests/mpi/cell_weights_06.cc
  tests/mpi/constraints_consistent_01.cc
  tests/mpi/dof_handler_number_cache.cc
  tests/mpi/hp_step-40.cc
  tests/mpi/hp_step-40_variable_01.cc
  tests/mpi/mg_02.cc
  tests/mpi/p4est_2d_dofhandler_01.cc
  tests/mpi/p4est_2d_dofhandler_02.cc
  tests/mpi/p4est_2d_dofhandler_03.cc
  tests/mpi/p4est_2d_dofhandler_04.cc
  tests/mpi/p4est_2d_renumber_02.cc
  tests/mpi/p4est_data_out_01.cc
  tests/mpi/p4est_get_subdomain_association.cc
  tests/mpi/periodicity_01.cc
  tests/mpi/periodicity_02.cc
  tests/mpi/periodicity_03.cc
  tests/mpi/periodicity_04.cc
  tests/mpi/periodicity_06.cc
  tests/mpi/periodicity_07.cc
  tests/mpi/renumber_cuthill_mckee.cc
  tests/mpi/renumber_cuthill_mckee_02.cc
  tests/mpi/step-40.cc
  tests/mpi/step-40_cuthill_mckee.cc
  tests/mpi/step-40_cuthill_mckee_MPI-subset.cc
  tests/mpi/step-40_direct_solver.cc
  tests/sharedtria/dof_01.cc
  tests/sharedtria/dof_02.cc
  tests/sharedtria/dof_03.cc
  tests/sharedtria/dof_04.cc
  tests/sharedtria/dof_05.cc
  tests/sharedtria/dof_06.cc
  tests/sharedtria/hp_dof_01.cc
  tests/sharedtria/hp_dof_02.cc
  tests/sharedtria/hp_dof_03.cc
  tests/sharedtria/hp_dof_04.cc
  tests/sharedtria/hp_no_cells_01.cc
  tests/sharedtria/mg_dof_02.cc
  tests/sharedtria/no_cells_01.cc
Labels: ready to test

#9999 Convert steps 4,5,6 to FEValues::quadrature_point_indices().
  examples/step-3/step-3.cc
  examples/step-4/step-4.cc
  examples/step-5/step-5.cc
Labels: ready for review, ready to test

#10002 Convert some loops over cells to range-based for loops
  include/deal.II/matrix_free/matrix_free.templates.h
Labels: Matrix-free, ready to test

#10004 Better document missing refinement edge data in MF for DG
  include/deal.II/matrix_free/face_setup_internal.h
  include/deal.II/matrix_free/matrix_free.templates.h
Labels: Matrix-free, ready to test

#10001 Remove quartic complexity from create_coupling_mass_matrix
  source/non_matching/coupling.cc
Labels: Quadrature, ready to test

#10005 Comment on the use of thread-safe BLAS/LAPACK
  examples/step-51/step-51.cc
Labels: Documentation, Tutorials

#9993 Fix SFINAE detection of LinOp for matrix-free operators
  include/deal.II/lac/la_parallel_vector.h
Labels: Linear Algebra, ready to test

#10007 Remove some unneeded backslashes.
  include/deal.II/lac/linear_operator.h
Labels: Documentation

#10011 Fix step-40 test: Output n_dofs rather than IndexSet
  tests/mpi/step-40_direct_solver.cc
Labels: Tests, ready to test

#10014 [step-67] Fix a wrong number in program output
  examples/step-67/doc/results.dox
Labels: Documentation, Reviewed and ready to merge, Tutorials

#10015 Suppress warning that tbb/task.h is deprecated
  include/deal.II/base/thread_management.h
  source/matrix_free/task_info.cc
Labels: Reviewed and ready to merge, ready to test

#10010 Test for project_onto_orthogonal_tensors improved
  tests/tensors/constexpr_tensor.cc
  tests/tensors/constexpr_tensor.output
  tests/tensors/project_orthogonal.cc
  tests/tensors/project_orthogonal.with_lapack=true.output
Labels: Tensors, Tests, ready to test

#10019 Fix a test by using the stream output precision.
  tests/fe/fe_nedelec_singularity_02.cc
Labels: Tests, ready to test

#10020 Remove an unnecessary include file.
  include/deal.II/lac/vector.h
Labels: Linear Algebra, ready to test

#10022 Test: adjust iteration count in ginkgo test
  tests/ginkgo/solver.cc
  tests/ginkgo/solver.output
Labels: Tests

#10024 Fix some clang-10 warnings
  bundled/umfpack/UMFPACK/Source/umf_grow_front.cc
  examples/step-32/step-32.cc
  include/deal.II/base/symbolic_function.h
  include/deal.II/meshworker/dof_info.h
Labels: ready to test

#10026 Avoid using fabs for std::complex
  tests/umfpack/umfpack_09_complex.cc
Labels: Tests, ready to test

#10029 Fix C++20 warnings and errors
  bundled/boost-1.70.0/include/boost/signals2/detail/auto_buffer.hpp
  bundled/tbb-2018_U2/src/tbb/arena.cpp
  examples/step-69/step-69.cc
Labels: Reviewed and ready to merge, ready to test

#9991 Add Utilities::MPI::create_evenly_distributed_partitioning()
  doc/news/changes/minor/20200429DougShiDong
  include/deal.II/base/mpi.h
  source/base/mpi.cc
  tests/base/mpi_create_partitioning_01.mpirun=1.output
  tests/base/mpi_evenly_distributed_partitioning_01.cc
  tests/base/mpi_evenly_distributed_partitioning_01.mpirun=1.output
  tests/base/mpi_evenly_distributed_partitioning_01.mpirun=2.output
  tests/base/mpi_evenly_distributed_partitioning_01.mpirun=4.output
Labels: ready to test

#10032 Suppress more TBB warnings
  source/base/multithread_info.cc
  source/matrix_free/task_info.cc
  tests/quick_tests/tbb.cc
Labels: Reviewed and ready to merge, ready to test

#9998 Minor updates to the DiscreteTime class documentation.
  include/deal.II/base/discrete_time.h
Labels: Documentation, ready to test

#9847 Rename NoncontiguousPartitioner::update_values()
  include/deal.II/base/mpi_noncontiguous_partitioner.h
  include/deal.II/base/mpi_noncontiguous_partitioner.templates.h
  include/deal.II/base/mpi_tags.h
  source/base/mpi_noncontiguous_partitioner.inst.in
  tests/base/mpi_noncontiguous_partitioner_01.cc
  tests/base/mpi_noncontiguous_partitioner_02.cc
  tests/base/mpi_noncontiguous_partitioner_03.cc
Labels: Parallel distributed, ready to test

#10040 Fix some more doxygen issues.
  doc/doxygen/extra.sty
  doc/doxygen/options.dox.in
  doc/doxygen/scripts/mod_header.pl.in
  include/deal.II/lac/linear_operator.h
Labels: Documentation

#9076 Particle interpolation sparsity matrix
  doc/news/changes/minor/20200331LucaHeltai
  include/deal.II/particles/utilities.h
  source/particles/CMakeLists.txt
  source/particles/utilities.cc
  source/particles/utilities.inst.in
  tests/particles/particle_interpolation_01.cc
  tests/particles/particle_interpolation_01.with_p4est=true.mpirun=1.output
  tests/particles/particle_interpolation_01.with_p4est=true.mpirun=2.output
  tests/particles/particle_interpolation_02.cc
  tests/particles/particle_interpolation_02.with_p4est=true.mpirun=1.output
  tests/particles/particle_interpolation_02.with_p4est=true.mpirun=2.output
  tests/particles/particle_interpolation_03.cc
  tests/particles/particle_interpolation_03.with_p4est=true.mpirun=1.output
  tests/particles/particle_interpolation_03.with_p4est=true.mpirun=2.output
  tests/particles/particle_interpolation_04.cc
  tests/particles/particle_interpolation_04.with_p4est=true.mpirun=1.output
  tests/particles/particle_interpolation_05.cc
  tests/particles/particle_interpolation_05.with_p4est=true.mpirun=1.with_trilinos=true.output
  tests/particles/particle_interpolation_05.with_p4est=true.mpirun=2.output
Labels: Particles, ready for review, ready to test

#10038 Remove some non-ascii characters.
  include/deal.II/base/tensor_product_polynomials.h
  include/deal.II/lac/utilities.h
  include/deal.II/numerics/vector_tools_boundary.h
  include/deal.II/numerics/vector_tools_boundary.templates.h
  include/deal.II/opencascade/utilities.h
  include/deal.II/sundials/arkode.h
  include/deal.II/sundials/kinsol.h
Labels: Documentation

#10030 Add a reference to the code gallery.
  examples/step-57/doc/results.dox
Labels: Documentation, Tutorials

#9997 Remove MeshWorker::CopyData::operator=(double)
  doc/news/changes/incompatibilities/20200430Jean-PaulPelteret
  include/deal.II/meshworker/copy_data.h
  include/deal.II/meshworker/mesh_loop.h
  tests/meshworker/mesh_loop_04.cc
  tests/meshworker/mesh_loop_05.cc
  tests/meshworker/mesh_loop_06.cc
  tests/meshworker/mesh_loop_07.cc
  tests/meshworker/mesh_loop_07.output
  tests/meshworker/scratch_data_01.cc
  tests/meshworker/scratch_data_02.cc
  tests/meshworker/scratch_data_03.cc
  tests/meshworker/scratch_data_05.cc
  tests/meshworker/scratch_data_06.cc
  tests/meshworker/scratch_data_07.cc
Labels: ready to test

#10041 Move a reference to references.bib.
  doc/doxygen/references.bib
  include/deal.II/numerics/error_estimator.h
Labels: Documentation, Reviewed and ready to merge

#9930 CI: update clang-tidy to clang10
  .clang-tidy
  contrib/ci/Jenkinsfile.tidy
  include/deal.II/base/thread_management.h
Labels: ready to test

#10045 add missing override in MatrixFree LaplaceOperator
  include/deal.II/matrix_free/operators.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#10039 Incompatible: Fix operator<< with Vector
  doc/news/changes/incompatibilities/20200505Bangerth
  include/deal.II/lac/vector.h
  tests/base/function_parser_08.with_muparser=true.output
  tests/feinterface/fe_interface_values_02.cc
  tests/feinterface/fe_interface_values_02.output
  tests/feinterface/fe_interface_values_03.cc
  tests/feinterface/fe_interface_values_03.output
  tests/feinterface/fe_interface_values_04.cc
  tests/feinterface/fe_interface_values_04.output
  tests/feinterface/fe_interface_values_06.cc
  tests/feinterface/fe_interface_values_06.output
  tests/feinterface/fe_interface_values_07.cc
  tests/feinterface/fe_interface_values_07.output
  tests/feinterface/fe_interface_values_08.cc
  tests/feinterface/fe_interface_values_08.output
  tests/feinterface/fe_interface_values_09.cc
  tests/feinterface/fe_interface_values_09.output
  tests/lac/block_linear_operator_04.cc
  tests/lac/block_linear_operator_04.output
  tests/lac/block_linear_operator_06.cc
  tests/lac/block_linear_operator_06.output
  tests/lac/block_vector_move_operations.cc
  tests/lac/block_vector_move_operations.output
  tests/lac/linear_operator_02.output
  tests/lac/linear_operator_02a.with_complex_values=on.output
  tests/lac/linear_operator_03.output
  tests/lac/linear_operator_17.output
  tests/lac/linear_operator_17a.output
  tests/lac/packaged_operation_01.output
  tests/lac/packaged_operation_01a.output
  tests/lac/packaged_operation_02.output
  tests/lac/schur_complement_01.cc
  tests/lac/schur_complement_01.output
  tests/lac/schur_complement_02.cc
  tests/lac/schur_complement_02.output
  tests/lac/vector_move_operations.cc
  tests/lac/vector_move_operations.output
Labels: ready for review, ready to test

#10034 Add codim 1 instantiations of make_hanging_node_constraints()
  doc/news/changes/minor/20200505SebastianStark
  source/dofs/dof_tools_constraints.cc
  source/dofs/dof_tools_constraints.inst.in
  tests/hp/hp_hanging_nodes_01.cc
  tests/hp/hp_hanging_nodes_01.output
Labels: DoFs, ready to test

#10042 Improve the formatting of a formula in a .h file.
  include/deal.II/numerics/error_estimator.h
Labels: Reviewed and ready to merge

#10036 Allow hp::DoFHandler with parallel::DistributedTriangulationBase
  doc/news/changes/minor/20200506SebastianStark
  source/hp/dof_handler.cc
Labels: Reviewed and ready to merge, ready to test

#9990 Add ranged based loops for local DoF indices to FEValuesBase
  doc/news/changes/minor/20200429Jean-PaulPelteret-1
  include/deal.II/fe/fe_values.h
  tests/physics/step-18-rotation_matrix.cc
  tests/physics/step-18.cc
  tests/physics/step-44-standard_tensors-material_push_forward.cc
  tests/physics/step-44-standard_tensors-spatial.cc
  tests/physics/step-44.cc
Labels: Reviewed and ready to merge, ready to test

#10048 base/utilities_pack_unpack_07: make test more robust
  tests/base/utilities_pack_unpack_07.cc
  tests/base/utilities_pack_unpack_07.with_zlib=on.debug.output
  tests/base/utilities_pack_unpack_07.with_zlib=on.output
  tests/base/utilities_pack_unpack_07.with_zlib=on.release.output2
Labels: ready for review, ready to test

#10052 mpi/petsc_step-27*: add a test variant for petsc-3.13 and newer
  tests/mpi/petsc_step-27.with_p4est=true.with_petsc_with_hypre=true.with_petsc_with_complex=false.mpirun=1.output.petsc3.13.0
  tests/mpi/petsc_step-27.with_p4est=true.with_petsc_with_hypre=true.with_petsc_with_complex=false.mpirun=2.output.petsc3.13.0
Labels: External libraries

#10054 serialization/fe_series_0?: Add test variants for libc++
  tests/serialization/fe_series_01.output.libc++
  tests/serialization/fe_series_02.with_gsl=on.output.libc++
Labels: ready to test

#10051 fe/memory_consumption_01: remove test
  tests/fe/memory_consumption_01.cc
  tests/fe/memory_consumption_01.output
Labels: Finite Element

#10033 The tolerance parameter is removed from project_tensor
  include/deal.II/base/tensor.h
  tests/tensors/project_orthogonal.cc
  tests/tensors/project_orthogonal.with_lapack=true.output
Labels: Reviewed and ready to merge, ready to test

#9978 Fix FEInterface for MG support
  include/deal.II/fe/fe_interface_values.h
Labels: ready to test

#10053 CUDA matrix-free: overlap communication and computation
  doc/news/changes/minor/20200506PeterMunchBrunoTurcksin
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/matrix_free/cuda_matrix_free.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
Labels: GPU, ready to test

#10050 Some tests depend on lapack
  tests/lac/qr_03.output
  tests/lac/qr_03.with_lapack=true.output
  tests/lac/qr_04.with_lapack=true.output
  tests/lac/qr_05.output
  tests/lac/qr_05.with_lapack=true.output
  tests/lac/qr_06.output
  tests/lac/qr_06.with_lapack=true.output
  tests/lac/qr_07.output
  tests/lac/qr_07.with_lapack=true.output
  tests/lac/qr_09.output
  tests/lac/qr_09.with_lapack=true.output
  tests/lac/qr_10.output
  tests/lac/qr_10.with_lapack=true.output
  tests/matrix_free/multigrid_dg_periodic.with_lapack=true.with_trilinos=true.with_mpi=true.with_p4est=true.mpirun=1.output
  tests/matrix_free/multigrid_dg_periodic.with_lapack=true.with_trilinos=true.with_mpi=true.with_p4est=true.mpirun=3.output
  tests/matrix_free/multigrid_dg_periodic.with_lapack=true.with_trilinos=true.with_mpi=true.with_p4est=true.mpirun=5.output
  tests/matrix_free/multigrid_dg_sip_01.with_lapack=true.with_mpi=true.with_p4est=true.mpirun=1.output
  tests/matrix_free/multigrid_dg_sip_01.with_lapack=true.with_mpi=true.with_p4est=true.mpirun=5.output
  tests/matrix_free/multigrid_dg_sip_02.with_lapack=true.with_mpi=true.with_p4est=true.mpirun=5.output
  tests/matrix_free/parallel_multigrid_fullydistributed.with_lapack=true.with_mpi=true.with_p4est=true.mpirun=3.output
  tests/matrix_free/step-37-inhomogeneous-1.with_lapack=true.with_mpi=true.mpirun=4.with_p4est=true.output
  tests/matrix_free/stokes_computation.with_lapack=true.with_mpi=true.with_p4est=true.mpirun=4.output
Labels: Reviewed and ready to merge, ready to test

#10063 Improve documentation of a BatchOptimizer function
  include/deal.II/differentiation/sd/symengine_optimizer.h
Labels: Documentation, Symbolic differentiation

#10056 Convert steps 3,4,5,6,8 and 44 to use FEValues range based loops
  examples/step-3/step-3.cc
  examples/step-4/step-4.cc
  examples/step-44/step-44.cc
  examples/step-5/step-5.cc
  examples/step-6/step-6.cc
  examples/step-8/step-8.cc
  tests/physics/step-44-standard_tensors-material_push_forward.cc
  tests/physics/step-44-standard_tensors-spatial.cc
  tests/physics/step-44.cc
Labels: Reviewed and ready to merge, ready to test

#10066 Disable a fallback option in the BatchOptimizer
  include/deal.II/differentiation/sd/symengine_optimizer.h
  source/differentiation/sd/symengine_optimizer.cc
Labels: Reviewed and ready to merge, Symbolic differentiation

#10062 Fix bug in FEFaceEvaluation::read_dof_values_plain
  doc/news/changes/minor/20200507MartinKronbichlerNiklasFehn
  include/deal.II/matrix_free/fe_evaluation.h
  tests/matrix_free/loop_boundary_02.cc
  tests/matrix_free/loop_boundary_02.output
Labels: Matrix-free, ready to test

#10047 Better document C++11/14/17/20.
  doc/doxygen/headers/c++.h
  doc/doxygen/headers/c++11.h
  include/deal.II/base/geometry_info.h
  include/deal.II/base/std_cxx11/type_traits.h
  include/deal.II/base/std_cxx14/algorithm.h
  include/deal.II/base/std_cxx14/memory.h
  include/deal.II/base/std_cxx14/utility.h
  include/deal.II/fe/fe_values.h
Labels: Documentation

#10075 Run codespell.
  doc/doxygen/headers/multithreading.h
  examples/step-3/doc/results.dox
  examples/step-58/doc/results.dox
  examples/step-62/step-62.cc
  examples/step-63/step-63.cc
  examples/step-64/step-64.cu
  examples/step-65/doc/intro.dox
  examples/step-67/doc/intro.dox
  examples/step-67/doc/results.dox
  examples/step-67/step-67.cc
  include/deal.II/base/data_out_base.h
  include/deal.II/base/mpi.h
  include/deal.II/base/mutable_bind.h
  include/deal.II/base/parameter_handler.h
  include/deal.II/base/parsed_convergence_table.h
  include/deal.II/base/polynomials_piecewise.h
  include/deal.II/base/symbolic_function.h
  include/deal.II/base/tensor.h
  include/deal.II/base/vectorization.h
  include/deal.II/differentiation/sd/symengine_optimizer.h
  include/deal.II/fe/fe_tools_extrapolate.templates.h
  include/deal.II/fe/mapping_q_cache.h
  include/deal.II/grid/grid_generator.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/tria_description.h
  include/deal.II/hp/fe_collection.h
  include/deal.II/hp/refinement.h
  include/deal.II/matrix_free/task_info.h
  include/deal.II/meshworker/local_results.h
  source/base/parameter_handler.cc
  source/differentiation/ad/ad_drivers.cc
  source/differentiation/sd/symengine_optimizer.cc
  source/fe/mapping_q_generic.cc
  source/grid/grid_generator.cc
  source/grid/grid_generator_from_name.cc
  source/grid/grid_tools.cc
  source/grid/grid_tools_dof_handlers.cc
  source/multigrid/mg_transfer_component.cc
  source/particles/particle_handler.cc
Labels: Documentation

#10074 Remove double word typos.
  include/deal.II/base/discrete_time.h
  include/deal.II/base/mpi.h
  include/deal.II/base/mpi_consensus_algorithms.templates.h
  include/deal.II/base/numbers.h
  include/deal.II/base/parameter_handler.h
  include/deal.II/base/vectorization.h
  include/deal.II/differentiation/sd/symengine_optimizer.h
  include/deal.II/differentiation/sd/symengine_scalar_operations.h
  include/deal.II/dofs/dof_tools.h
  include/deal.II/fe/fe_interface_values.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/lac/lapack_full_matrix.h
  include/deal.II/lac/sparsity_tools.h
Labels: Documentation

#10071 adolc/helper_tape_index_01: Increase tolerance
  tests/adolc/helper_tape_index_01.cc
Labels: Reviewed and ready to merge, ready to test

#10077 Minor update to the section on uploading test results.
  doc/developers/testsuite.html
Labels: Documentation

#9948 Make coarse_cell_*_to_coarse_cell_* private
  include/deal.II/distributed/fully_distributed_tria.h
  include/deal.II/grid/tria.h
Labels: Triangulation, ready to test

#10080 Undo accidental change in test result file with LAPACK
  tests/matrix_free/step-37-inhomogeneous-1.with_lapack=true.with_mpi=true.mpirun=4.with_p4est=true.output
Labels: Tests, ready to test

#10083 Make a few tests check what they are supposed to
  tests/matrix_free/pre_and_post_loops_01.cc
  tests/matrix_free/pre_and_post_loops_02.cc
  tests/matrix_free/pre_and_post_loops_03.cc
  tests/matrix_free/pre_and_post_loops_04.cc
  tests/matrix_free/pre_and_post_loops_05.cc
Labels: Matrix-free, Reviewed and ready to merge, Tests, ready to test

#10079 correct docu of GridTools::transform() and GridGenerator::cylinder()
  include/deal.II/grid/grid_generator.h
  include/deal.II/grid/grid_tools.h
Labels: Documentation

#10089 remove boost include to fix compilation
  include/deal.II/grid/grid_tools.h
Labels: Reviewed and ready to merge, ready to test

#10091 hide boost deprecation warning with 1.73
  source/base/parameter_handler.cc
  source/base/patterns.cc
  source/base/utilities.cc
  source/dofs/dof_renumbering.cc
Labels: Reviewed and ready to merge, ready to test

#10096 add some empty lines
  include/deal.II/algorithms/operator.h
Labels: ready to test

#10095 add missing override
  include/deal.II/matrix_free/operators.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#10094 release step 0c: doxygen formatting
  include/deal.II/base/mpi.h
  include/deal.II/base/types.h
  include/deal.II/distributed/tria_base.h
  include/deal.II/fe/fe_nedelec_sz.h
  include/deal.II/grid/cell_id.h
  include/deal.II/grid/tria.h
  include/deal.II/grid/tria_description.h
  include/deal.II/hp/refinement.h
  include/deal.II/numerics/vector_tools_interpolate.h
Labels: ready to test

#10065 Silence gcc-10 warnings about invalid array accesses
  include/deal.II/base/tensor.h
  source/fe/fe_bernardi_raugel.cc
  source/grid/manifold_lib.cc
Labels: ready to test

#10098 fix copyright update script updating itself
  contrib/utilities/update-copyright
Labels: ready to test

#10092 Fix sorting of cells in p:f:t
  source/distributed/fully_distributed_tria.cc
  tests/fullydistributed_grids/copy_serial_tria_10.cc
  tests/fullydistributed_grids/copy_serial_tria_10.mpirun=1.output
Labels: Parallel distributed, Reviewed and ready to merge, ready to test

#10099 Fix compilation with gcc-10
  include/deal.II/differentiation/ad/ad_helpers.h
Labels: Automatic differentiation, Compiler, Reviewed and ready to merge, ready to test

#10084 Fix matrix-free pre/post loops with threads
  include/deal.II/matrix_free/matrix_free.h
  source/matrix_free/task_info.cc
  tests/matrix_free/pre_and_post_loops_06.cc
  tests/matrix_free/pre_and_post_loops_06.with_mpi=true.with_p4est=true.mpirun=1.output
  tests/matrix_free/pre_and_post_loops_06.with_mpi=true.with_p4est=true.mpirun=3.output
Labels: Matrix-free, ready to test

#10087 Disable hold_all_faces_to_owned_cells for FE_Q
  include/deal.II/matrix_free/matrix_free.templates.h
  tests/matrix_free/partitioner_02.cc
  tests/matrix_free/partitioner_02.output
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#10102 Qualify a call to parallel::apply_to_subrange
  include/deal.II/matrix_free/matrix_free.h
Labels: Matrix-free, ready to test

#10103 Mark LaplaceOperator::apply_add as override
  include/deal.II/matrix_free/operators.h
Labels: Matrix-free, ready to test

#9883 Finish step-50
  doc/doxygen/tutorial/tutorial.h.in
  doc/news/changes/major/20200420step50
  examples/step-50/CMakeLists.txt
  examples/step-50/amg_2d.prm
  examples/step-50/amg_3d.prm
  examples/step-50/doc/builds-on
  examples/step-50/doc/intro.dox
  examples/step-50/doc/results.dox
  examples/step-50/doc/tooltip
  examples/step-50/gmg_mb_2d.prm
  examples/step-50/gmg_mb_3d.prm
  examples/step-50/gmg_mf_2d.prm
  examples/step-50/gmg_mf_3d.prm
  examples/step-50/step-50.cc
Labels: Tutorials, ready to test

#9835 Parallelize the main loops of MappingInfo::compute_mapping_q
  include/deal.II/matrix_free/mapping_info.templates.h
Labels: Matrix-free, Parallel shared, ready to test

#10107 Run cppcheck
  include/deal.II/base/aligned_vector.h
  include/deal.II/base/mpi_compute_index_owner_internal.h
  include/deal.II/base/table.h
  include/deal.II/base/timer.h
  include/deal.II/base/utilities.h
  include/deal.II/lac/full_matrix.templates.h
  include/deal.II/lac/precondition.h
  include/deal.II/lac/precondition_block.h
  include/deal.II/lac/sparse_decomposition.templates.h
  include/deal.II/lac/sparse_matrix.templates.h
  include/deal.II/lac/sparse_mic.templates.h
Labels: Reviewed and ready to merge, ready to test

#10100 Properly initalization of velocity vector
  examples/step-35/step-35.cc
Labels: Tutorials, ready to test

#10018 Introduce std_cxx20::ranges::iota_view
  examples/step-69/step-69.cc
  include/deal.II/base/geometry_info.h
  include/deal.II/base/std_cxx20/iota_view.h
  include/deal.II/fe/fe_values.h
Labels: ready to test

#10111 Make clang-tidy happy with parallel::apply_to_subranges
  include/deal.II/matrix_free/mapping_info.templates.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#10110 Fix ICC compilation
  include/deal.II/matrix_free/mapping_info.templates.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#10112 Add author in changelog
  doc/news/changes/major/20191112LucaHeltaiBrunoBlais
Labels: Reviewed and ready to merge

#9891 Interpolate field on particles
  include/deal.II/particles/utilities.h
  tests/particles/interpolate_on_particle_01.cc
  tests/particles/interpolate_on_particle_01.with_p4est=true.mpirun=2.with_trilinos=true.output
Labels: Particles, ready for review, ready to test

#10108 Add mapping argument to find_closest_vertex_of_cell().
  doc/news/changes/minor/20200510LucaHeltai
  include/deal.II/grid/grid_tools.h
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
  tests/grid/grid_tools_find_closest_vertex_02.cc
  tests/grid/grid_tools_find_closest_vertex_02.output
Labels: Mapping, Reviewed and ready to merge, ready for review, ready to test

#10113 p:f:t: Test repeated local refinement of base triangulation
  tests/fullydistributed_grids/copy_serial_tria_11.cc
  tests/fullydistributed_grids/copy_serial_tria_11.mpirun=1.output
Labels: Parallel distributed, Triangulation, ready to test

#10116 step-50: set kind to techniques
  examples/step-50/doc/kind
Labels: Reviewed and ready to merge, Tutorials

#10117 step-50: fix references
  doc/doxygen/references.bib
  examples/step-50/doc/intro.dox
Labels: Reviewed and ready to merge, Tutorials

#10021 New extract_rtree_level function, and RTree visitor.
  doc/doxygen/images/rtree-process-0.png
  doc/doxygen/images/rtree-process-1.png
  doc/doxygen/images/rtree-process-2.png
  doc/news/changes/minor/20200503LucaHeltai
  include/deal.II/base/patterns.h
  include/deal.II/numerics/rtree.h
  tests/boost/extract_reprsentative_set_01.cc
  tests/boost/extract_reprsentative_set_01.output
  tests/boost/extract_reprsentative_set_02.cc
  tests/boost/extract_reprsentative_set_02.with_p4est=true.mpirun=3.output
  tests/parameter_handler/pattern_tools_02.output
Labels: ready for review, ready to test

#10121 add missing instantiations for make_boundary_sparsity_pattern
  source/dofs/dof_tools_sparsity.inst.in
Labels: Reviewed and ready to merge, ready to test

#10122 fix warning about braces
  source/matrix_free/task_info.cc
Labels: Reviewed and ready to merge, ready to test

#9802 Add alternative GridGenerator::hyper_ball with better balance of cells
  doc/doxygen/images/hyper_ball_balanced_2d.png
  doc/doxygen/images/hyper_ball_balanced_3d.png
  doc/news/changes/minor/20200402MartinKronbichler-1
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  source/grid/grid_generator.inst.in
  tests/grid/grid_generator_hyper_ball_balanced.cc
  tests/grid/grid_generator_hyper_ball_balanced.output
Labels: Triangulation, ready to test

#10125 Fix dim<spacedim case in create_triangulation with TriaDescription
  source/grid/tria.cc
Labels: Reviewed and ready to merge, Triangulation, ready to test

#10124 Reverse order of mapping and triangulation in compute_aspect_ratio
  include/deal.II/grid/grid_tools.h
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
  tests/grid/grid_generator_open_torus.cc
  tests/grid/grid_tools_aspect_ratio.cc
Labels: Mapping, Reviewed and ready to merge, ready to test

#10123 fix no-return warning in step-67
  examples/step-67/step-67.cc
Labels: Reviewed and ready to merge, ready to test

#10126 cmake: restrict p4est tests
  cmake/configure/configure_p4est.cmake
  cmake/modules/FindP4EST.cmake
  tests/distributed_grids/2d_coarse_grid_01.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/2d_coarse_grid_01.with_p4est_with_vtk_binary=false.debug.output.1
  tests/distributed_grids/2d_coarse_grid_02.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/2d_coarse_grid_02.with_p4est_with_vtk_binary=false.debug.output.1
  tests/distributed_grids/2d_coarse_grid_03.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/2d_coarse_grid_03.with_p4est_with_vtk_binary=false.debug.output.1
  tests/distributed_grids/2d_coarse_grid_04.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/2d_coarse_grid_04.with_p4est_with_vtk_binary=false.debug.output.1
  tests/distributed_grids/2d_coarsening_01.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/2d_coarsening_01.with_p4est_with_vtk_binary=false.debug.output.1
  tests/distributed_grids/2d_coarsening_02.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/2d_coarsening_02.with_p4est_with_vtk_binary=false.debug.output.1
  tests/distributed_grids/2d_refinement_01.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/2d_refinement_01.with_p4est_with_vtk_binary=false.debug.output.1
  tests/distributed_grids/2d_refinement_02.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/2d_refinement_02.with_p4est_with_vtk_binary=false.debug.output.1
  tests/distributed_grids/3d_coarse_grid_01.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/3d_coarse_grid_01.with_p4est_with_vtk_binary=false.debug.output.1
  tests/distributed_grids/3d_coarse_grid_02.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/3d_coarse_grid_02.with_p4est_with_vtk_binary=false.debug.output.1
  tests/distributed_grids/3d_coarse_grid_03.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/3d_coarse_grid_03.with_p4est_with_vtk_binary=false.debug.output.1
  tests/distributed_grids/3d_coarse_grid_04.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/3d_coarse_grid_04.with_p4est_with_vtk_binary=false.debug.output.1
  tests/distributed_grids/3d_coarse_grid_05.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/3d_coarse_grid_05.with_p4est_with_vtk_binary=false.debug.output.1
  tests/distributed_grids/3d_coarsening_01.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/3d_coarsening_01.with_p4est_with_vtk_binary=false.debug.output.1
  tests/distributed_grids/3d_coarsening_02.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/3d_coarsening_02.with_p4est_with_vtk_binary=false.debug.output.1
  tests/distributed_grids/3d_refinement_01.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/3d_refinement_01.with_p4est_with_vtk_binary=false.debug.output.1
  tests/distributed_grids/3d_refinement_02.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/3d_refinement_02.with_p4est_with_vtk_binary=false.debug.output.1
  tests/distributed_grids/3d_refinement_03.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/3d_refinement_03.with_p4est_with_vtk_binary=false.debug.output.1
  tests/distributed_grids/codim_01.with_p4est_with_vtk_binary=false.debug.output
  tests/distributed_grids/codim_01.with_p4est_with_vtk_binary=false.debug.output.1
  tests/mpi/codim_01.mpirun=3.with_zlib=on.with_p4est=true.with_p4est_with_vtk_binary=false.debug.output
  tests/mpi/codim_01.mpirun=3.with_zlib=on.with_p4est=true.with_p4est_with_vtk_binary=false.debug.output.1
Labels: ready to test

#10127 python_bindings: Also update order of compute_aspect_ratio
  contrib/python-bindings/source/triangulation_wrapper.cc
Labels: Bug, Python

#9558 step-47: Add derivation for the simply supported plates to result section.
  examples/step-47/doc/intro.dox
  examples/step-47/doc/results.dox
Labels: Tutorials

#10131 Tests: grid/refine_boundary_domain - avoid roundoff errros
  tests/grid/refine_boundary_domain.cc
Labels: Reviewed and ready to merge, Triangulation, ready for review, ready to test

#10132 Test vector_tools/integrate_difference_04_hp_02: Make test less expensive
  tests/vector_tools/integrate_difference_04_hp_02.cc
  tests/vector_tools/integrate_difference_04_hp_02.with_trilinos=true.with_metis=true.mpirun=2.output
  tests/vector_tools/integrate_difference_04_hp_02.with_trilinos=true.with_metis=true.mpirun=3.output
Labels: Reviewed and ready to merge, ready to test

#10133 Test lac/gmres_reorthogonalize_04: Only output iteration count
  tests/lac/gmres_reorthogonalize_04.cc
  tests/lac/gmres_reorthogonalize_04.output
Labels: Linear Algebra, Reviewed and ready to merge, ready to test

#10135 Remove some "dealii::"s from code examples.
  include/deal.II/lac/packaged_operation.h
Labels: Documentation

#10134 Make new GridGenerator images appear in the online documentation
  include/deal.II/grid/grid_generator.h
Labels: Documentation

#10141 doc: update supported version numbers of trilinos and petsc
  doc/external-libs/petsc.html
  doc/external-libs/trilinos.html
Labels: Reviewed and ready to merge

#10138 Remove some commented code.
  examples/step-16/step-16.cc
Labels: Documentation, Reviewed and ready to merge, ready for review

#10136 Fix some small things in step-44's introduction.
  examples/step-44/doc/intro.dox
Labels: Documentation, Reviewed and ready to merge

#10143 Tests opencascade/*: Add three output variants
  tests/opencascade/stl_creation_single_patch.output.opencascade7.4.0
  tests/opencascade/stl_creation_watertight.output.opencascade7.4.0
  tests/opencascade/stl_refinement.output.libstdc++10
Labels: Reviewed and ready to merge, ready to test

#10144 step-50: Possible extensions
  examples/step-50/doc/results.dox
Labels: Documentation

#10150 Test petsc/reinit_preconditioner_0?: disable for 64bit indices
  tests/petsc/reinit_preconditioner_01.with_petsc_with_hypre=true.with_64bit_indices=off.with_mpi=true.mpirun=3.output
  tests/petsc/reinit_preconditioner_02.with_petsc_with_hypre=true.with_64bit_indices=off.with_mpi=true.output
Labels: Reviewed and ready to merge, ready to test

#9807 Add additional cell options for 3D hyper shell
  doc/news/changes/minor/20200407MartinKronbichler
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  tests/grid/grid_hyper_shell_07.cc
  tests/grid/grid_hyper_shell_07.output
  tests/grid/grid_hyper_shell_08.cc
  tests/grid/grid_hyper_shell_08.output
Labels: Triangulation, ready to test

#10147 doxygen: disable stuff in grid_generator.cc
  source/grid/grid_generator.cc
Labels: Documentation

#10149 Fix compilation with gcc-4.9.4
  include/deal.II/matrix_free/mapping_info.templates.h
Labels: Reviewed and ready to merge, ready to test

#10148 github actions: split windows build
  .github/workflows/main.yml
  .github/workflows/windows.yml
Labels: Infrastructure, Reviewed and ready to merge

#9954 Reworked error prediction algorithm.
  doc/doxygen/references.bib
  include/deal.II/distributed/cell_data_transfer.h
  include/deal.II/distributed/cell_data_transfer.templates.h
  include/deal.II/hp/refinement.h
  include/deal.II/numerics/adaptation_strategies.h
  include/deal.II/numerics/cell_data_transfer.h
  include/deal.II/numerics/cell_data_transfer.templates.h
  include/deal.II/numerics/coarsening_strategies.h
  source/distributed/cell_weights.cc
  source/distributed/solution_transfer.cc
  source/hp/dof_handler.cc
  source/hp/refinement.cc
  source/numerics/solution_transfer.cc
  tests/hp/error_prediction.output
  tests/hp/error_prediction_01.cc
  tests/hp/error_prediction_01.output
  tests/mpi/cell_data_transfer_03.cc
Labels: Reviewed and ready to merge, ready to test

#8603 add failing p4est test
  tests/mpi/p4est_bug_01.cc
  tests/mpi/p4est_bug_01.with_p4est=true.expect=run.output
Labels: Reviewed and ready to merge, Triangulation

#10152 Updated doc for hp::Refinement::predict_error().
  include/deal.II/hp/refinement.h
  source/hp/refinement.cc
Labels: Documentation

#10155 Instantiate OpenCASCADE
  source/opencascade/boundary_lib.inst.in
  source/opencascade/manifold_lib.cc
  source/opencascade/manifold_lib.inst.in
Labels: External libraries, Reviewed and ready to merge

#10156 Release step 1a: Update tag list
  doc/users/doxygen.html
Labels: Reviewed and ready to merge

#10157 Release step 5: update VERSION
  VERSION
Labels: Reviewed and ready to merge

#10167 [9.2] Take over #10166
  examples/step-69/doc/intro.dox
Labels: Release

#10170 [9.2] remove test mpi/p4est_bug
  tests/mpi/p4est_bug_01.cc
  tests/mpi/p4est_bug_01.with_p4est=true.expect=run.output
Labels: Release

#10172 [9.2] Take over #10171
  tests/serialization/fe_series_01.output.libc++
  tests/serialization/fe_series_02.with_gsl=on.output.libc++
Labels: Release

#10168 do not print mesh in opencascade/stl_* tests
  tests/opencascade/stl_creation_single_patch.cc
  tests/opencascade/stl_creation_single_patch.output
  tests/opencascade/stl_creation_single_patch.output.opencascade7.4.0
  tests/opencascade/stl_creation_watertight.cc
  tests/opencascade/stl_creation_watertight.output
  tests/opencascade/stl_creation_watertight.output.opencascade7.4.0
Labels: Reviewed and ready to merge, ready to test

#10169 [9.2.] Take over #10168
  tests/opencascade/stl_creation_single_patch.cc
  tests/opencascade/stl_creation_single_patch.output
  tests/opencascade/stl_creation_single_patch.output.opencascade7.4.0
  tests/opencascade/stl_creation_watertight.cc
  tests/opencascade/stl_creation_watertight.output
  tests/opencascade/stl_creation_watertight.output.opencascade7.4.0
Labels: Release

#10173 Jenkins: also test release branches
  Jenkinsfile
  contrib/ci/Jenkinsfile.osx
  contrib/ci/Jenkinsfile.tidy
Labels: ready to test

#10159 [9.2] Take over #10173: Jenkins: also test release branches
  Jenkinsfile
  contrib/ci/Jenkinsfile.osx
  contrib/ci/Jenkinsfile.tidy
Labels: ready to test

#10161 Removed two variables which were not used in particles/utilities.h
  include/deal.II/particles/utilities.h
Labels: Reviewed and ready to merge, ready to test

#10176 CUDA: multiple fixes
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  include/deal.II/matrix_free/cuda_matrix_free.h
  tests/cuda/parallel_vector_11.cu
Labels: GPU, Reviewed and ready to merge, ready to test

#10178 doxygen: Strip full @CMAKE_SOURCE_DIR@ and @CMAKE_BINARY_DIR@
  doc/doxygen/options.dox.in
Labels: Documentation

#10181 Always inline FEEvaluationBase::inverse_jacobian
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, Reviewed and ready to merge, ready to test

#10185 [9.2] Take over #10179: contrib/utilities/makeofflinedoc.sh: Also install jpg
  contrib/utilities/makeofflinedoc.sh
Labels: Reviewed and ready to merge

#10186 [9.2] Take over #10176
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  include/deal.II/matrix_free/cuda_matrix_free.h
  tests/cuda/parallel_vector_11.cu
Labels: Reviewed and ready to merge

#10187 [9.2] Take over #10178
  doc/doxygen/options.dox.in
Labels: Reviewed and ready to merge

#10191 Documentation: fix make_gallery.pl
  doc/doxygen/scripts/make_gallery.pl
Labels: Bug, Documentation

#10189 Documentation: Treat code gallery projects as examples
  doc/doxygen/code-gallery/CMakeLists.txt
Labels: Bug, Documentation, Reviewed and ready to merge

#10199 Choose output files for mpi/condense_01 correctly
  tests/mpi/condense_01.with_petsc=true.with_petsc_with_complex=false.mpirun=2.with_p4est=true.output
  tests/mpi/condense_01.with_petsc=true.with_petsc_with_complex=false.mpirun=7.with_p4est=true.output
  tests/mpi/condense_01.with_petsc_with_complex=true.mpirun=2.with_p4est=true.output
  tests/mpi/condense_01.with_petsc_with_complex=true.mpirun=7.with_p4est=true.output
Labels: Reviewed and ready to merge

#10200 [9.2] Take over #10199: Choose output files for mpi/condense_01 correctly
  tests/mpi/condense_01.with_petsc=true.with_petsc_with_complex=false.mpirun=2.with_p4est=true.output
  tests/mpi/condense_01.with_petsc=true.with_petsc_with_complex=false.mpirun=7.with_p4est=true.output
  tests/mpi/condense_01.with_petsc_with_complex=true.mpirun=2.with_p4est=true.output
  tests/mpi/condense_01.with_petsc_with_complex=true.mpirun=7.with_p4est=true.output
Labels: Reviewed and ready to merge

#10207 Fix extract_rtree_level for small problem sizes
  include/deal.II/numerics/rtree.h
  tests/boost/extract_representative_set_02.cc
  tests/boost/extract_representative_set_02.with_p4est=true.mpirun=3.output
Labels: Reviewed and ready to merge, ready for review, ready to test

#10201 CMake: relax arpack and parpack library directory requirements
  cmake/modules/FindARPACK.cmake
Labels: Reviewed and ready to merge, ready to test

#10194 Avoid using std::cout in a test.
  tests/mpi/petsc_step-27.cc
  tests/mpi/petsc_step-27.with_p4est=true.with_petsc_with_hypre=true.with_petsc_with_complex=false.mpirun=1.output
  tests/mpi/petsc_step-27.with_p4est=true.with_petsc_with_hypre=true.with_petsc_with_complex=false.mpirun=1.output.petsc3.13.0
  tests/mpi/petsc_step-27.with_p4est=true.with_petsc_with_hypre=true.with_petsc_with_complex=false.mpirun=2.output
  tests/mpi/petsc_step-27.with_p4est=true.with_petsc_with_hypre=true.with_petsc_with_complex=false.mpirun=2.output.petsc3.13.0
Labels: Reviewed and ready to merge, Tests, ready to test

#10013 Introduced p::d::ErrorPredictor.
  include/deal.II/distributed/error_predictor.h
  include/deal.II/hp/refinement.h
  source/distributed/CMakeLists.txt
  source/distributed/error_predictor.cc
  source/distributed/error_predictor.inst.in
  tests/mpi/error_predictor_01.cc
  tests/mpi/error_predictor_01.with_p4est=true.mpirun=1.output
  tests/mpi/error_predictor_01.with_p4est=true.mpirun=4.output
  tests/mpi/error_predictor_02.cc
  tests/mpi/error_predictor_02.with_p4est=true.mpirun=1.output
  tests/mpi/error_predictor_02.with_p4est=true.mpirun=4.output
Labels: ready to test

#10208 Fix python FunctionManifold
  contrib/python-bindings/tests/manifold_wrapper.py
  include/deal.II/grid/manifold_lib.h
  source/grid/manifold_lib.cc
Labels: Reviewed and ready to merge, ready to test

#10182 clarify documentation of FEEvaluation::set_dof_values()
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Documentation

#10209 [9.2] Take over #10013: Introduced p::d::ErrorPredictor.
  include/deal.II/distributed/error_predictor.h
  include/deal.II/hp/refinement.h
  source/distributed/CMakeLists.txt
  source/distributed/error_predictor.cc
  source/distributed/error_predictor.inst.in
  tests/mpi/error_predictor_01.cc
  tests/mpi/error_predictor_01.with_p4est=true.mpirun=1.output
  tests/mpi/error_predictor_01.with_p4est=true.mpirun=4.output
  tests/mpi/error_predictor_02.cc
  tests/mpi/error_predictor_02.with_p4est=true.mpirun=1.output
  tests/mpi/error_predictor_02.with_p4est=true.mpirun=4.output
Labels: Reviewed and ready to merge, ready to test

#10198 Updates to step-50
  examples/step-50/doc/intro.dox
  examples/step-50/doc/results.dox
  examples/step-50/step-50.cc
Labels: Tutorials, ready for review, ready to test

#10213 [9.2] Take over #10207
  include/deal.II/numerics/rtree.h
  tests/boost/extract_representative_set_02.cc
  tests/boost/extract_representative_set_02.with_p4est=true.mpirun=3.output
Labels: ready to test

#10210 [9.2] Take over #9969: Revisited binary search for parallel::distributed::GridRefinement.
  source/distributed/grid_refinement.cc
  tests/grid/refine_and_coarsen_fixed_number_03.cc
  tests/grid/refine_and_coarsen_fixed_number_03.output
  tests/mpi/refine_and_coarsen_fixed_number_08.cc
  tests/mpi/refine_and_coarsen_fixed_number_08.mpirun=1.with_p4est=true.output
  tests/mpi/refine_and_coarsen_fixed_number_08.mpirun=4.with_p4est=true.output
  tests/mpi/tria_ghost_owners_01.mpirun=7.with_p4est=true.output
  tests/mpi/tria_ghost_owners_02.mpirun=11.with_p4est=true.output
Labels: Reviewed and ready to merge, ready to test

#10216 [9.2] Take over #10215: Bugfix: Cells may not receive any variable size data.
  source/distributed/tria.cc
  tests/particles/particle_handler_14.cc
  tests/particles/particle_handler_14.with_p4est=true.mpirun=2.output
Labels: Reviewed and ready to merge, ready to test

#10215 Bugfix: Cells may not receive any variable size data.
  source/distributed/tria.cc
  tests/particles/particle_handler_14.cc
  tests/particles/particle_handler_14.with_p4est=true.mpirun=2.output
Labels: Reviewed and ready to merge, ready to test

#9969 Revisited binary search for parallel::distributed::GridRefinement.
  source/distributed/grid_refinement.cc
  tests/grid/refine_and_coarsen_fixed_number_03.cc
  tests/grid/refine_and_coarsen_fixed_number_03.output
  tests/mpi/refine_and_coarsen_fixed_number_08.cc
  tests/mpi/refine_and_coarsen_fixed_number_08.mpirun=1.with_p4est=true.output
  tests/mpi/refine_and_coarsen_fixed_number_08.mpirun=4.with_p4est=true.output
  tests/mpi/tria_ghost_owners_01.mpirun=7.with_p4est=true.output
  tests/mpi/tria_ghost_owners_02.mpirun=11.with_p4est=true.output
Labels: Reviewed and ready to merge, ready to test

#10220 tests: add additional output file for intel
  tests/parameter_handler/parameter_handler_25.output2
Labels: Reviewed and ready to merge, ready to test

#10174 Fix find active cell around point.
  source/grid/grid_tools.cc
  tests/grid/find_active_cell_around_point_04.cc
  tests/grid/find_active_cell_around_point_04.mpirun=2.with_p4est=true.output
Labels: ready for review, ready to test

#10225 Fix test output forgotten in #9969
  tests/mpi/tria_ghost_owners_01.mpirun=7.with_p4est=true.output
  tests/mpi/tria_ghost_owners_02.mpirun=11.with_p4est=true.output
  tests/mpi/tria_ghost_owners_02.mpirun=5.with_p4est=true.output
Labels: Tests

#10227 Fix warning in step-70
  examples/step-70/step-70.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#10229 [9.2] Take over #10227
  examples/step-70/step-70.cc
Labels: ready to test
