Repository dealii/dealii, pull requests merged in 2021-11, with the labels that each got.

#12901 Fix a test.
  tests/mpi/data_out_hdf5_02.cc
Labels: Tests, ready to test

#12896 Split up matrix_tools.h -> matrix_creator.h
  include/deal.II/numerics/matrix_creator.h
  include/deal.II/numerics/matrix_creator.templates.h
  include/deal.II/numerics/matrix_tools.h
Labels: Miscellaneous, ready to test

#12895 Make DataOutFaces work with simplices
  include/deal.II/numerics/data_out_dof_data.templates.h
  tests/simplex/data_out_faces_01.cc
  tests/simplex/data_out_faces_01.output
  tests/simplex/step-04-data_out_faces.cc
  tests/simplex/step-04-data_out_faces.output
Labels: Post-processing, ready to test

#12903 Inline active_cell_index functions
  include/deal.II/grid/tria_accessor.templates.h
  source/grid/tria_accessor.cc
Labels: Reviewed and ready to merge, Triangulation, ready to test

#12907 Avoid code duplication.
  tests/mpi/data_out_hdf5_02.cc
Labels: ready to test

#12904 Simplify code by using cell->is_locally_owned() and friends
  include/deal.II/matrix_free/matrix_free.templates.h
  source/multigrid/mg_tools.cc
  source/multigrid/mg_transfer_prebuilt.cc
Labels: Reviewed and ready to merge, Multigrid, Matrix-free, ready to test

#12905 Cleanups in data_out_base.cc
  source/base/data_out_base.cc
Labels: ready to test

#12902 Apply some range-based for loops
  source/dofs/dof_tools.cc
  source/dofs/dof_tools_sparsity.cc
Labels: C++11, ready to test

#12908 Simplify a test.
  tests/simplex/data_out_write_gnuplot_01.cc
  tests/simplex/data_out_write_gnuplot_01.output
Labels: ready to test

#12912 Fix the dates in four changelog entries.
  doc/news/changes/minor/20211013Bangerth
  doc/news/changes/minor/20211013Bangerth-b
  doc/news/changes/minor/20211025Bangerth
  doc/news/changes/minor/20211025Bangerth-b
Labels: Documentation, ready to test

#12910 Fix a typo in step38 doc
  examples/step-38/doc/intro.dox
Labels: Documentation, Reviewed and ready to merge, ready to test

#12909 FEEvaluation: Evaluate and integrate functions which use a user shape_info object
  include/deal.II/matrix_free/evaluation_kernels.h
Labels: Matrix-free, ready to test

#12919 Fix some errors revealed by STL debug compile
  source/distributed/tria_base.cc
  source/grid/grid_generator.cc
Labels: Reviewed and ready to merge, Miscellaneous, ready to test

#12921 N_Vector now returns a pointer to MPI_Comm
  include/deal.II/sundials/n_vector.templates.h
  tests/sundials/n_vector.cc
Labels: Reviewed and ready to merge, ready to test

#12922 CylindricalManifold: make member variable const.
  include/deal.II/grid/manifold_lib.h
Labels: ready to test

#12918 [9.3] add changelog entry for point release
  doc/news/9.3.1-vs-9.3.2.h
Labels: Release, Documentation

#12915 [9.3.2] Revert "Remove copy from SUNDIALS::KINSOL"
  include/deal.II/sundials/copy.h
  include/deal.II/sundials/ida.h
  include/deal.II/sundials/kinsol.h
  include/deal.II/sundials/n_vector.templates.h
  source/sundials/CMakeLists.txt
  source/sundials/copy.cc
  source/sundials/ida.cc
  source/sundials/kinsol.cc
  source/sundials/n_vector.inst.in
  tests/sundials/copy_01.cc
  tests/sundials/copy_01.with_mpi=true.with_petsc=true.with_petsc_with_complex=false.mpirun=4.output
  tests/sundials/ida_01.cc
  tests/sundials/ida_01.with_sundials.geq.4.0.0.output
  tests/sundials/ida_02.cc
  tests/sundials/ida_02.with_sundials.geq.4.0.0.output
  tests/sundials/kinsol_01.cc
  tests/sundials/kinsol_01.prm
  tests/sundials/kinsol_01.with_sundials=true.output
  tests/sundials/kinsol_02.cc
  tests/sundials/kinsol_02.with_sundials=true.output
  tests/sundials/kinsol_03.cc
  tests/sundials/kinsol_03_new_interface.cc
  tests/sundials/kinsol_04.cc
  tests/sundials/kinsol_04_new_interface.cc
  tests/sundials/kinsol_05.cc
  tests/sundials/kinsol_05_new_interface.cc
  tests/sundials/kinsol_fixed_point.prm
  tests/sundials/kinsol_newton.prm
  tests/sundials/kinsol_picard.prm
Labels: ready to test

#12925 Fix typo
  include/deal.II/fe/fe.h
Labels: Documentation

#12926 Update predict_error doc entry
  include/deal.II/hp/refinement.h
Labels: Documentation

#12928 minor MGRepartining edits
  include/deal.II/distributed/repartitioning_policy_tools.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.h
  source/distributed/repartitioning_policy_tools.cc
Labels: Multigrid, ready to test

#12927 Minor fixes to `predict_error` doc.
  include/deal.II/hp/refinement.h
Labels: Documentation

#12920 Add signed distance function for 1D and 2D ellipsoids
  doc/news/changes/minor/20211105Much
  include/deal.II/base/function_signed_distance.h
  source/base/function_signed_distance.cc
  source/base/function_signed_distance.inst.in
  tests/base/function_signed_distance.cc
  tests/base/function_signed_distance.output
Labels: Reviewed and ready to merge, ready to test, Non-matching

#12929 Rename some tests
  tests/base/function_signed_distance_01.cc
  tests/base/function_signed_distance_01.output
  tests/base/function_signed_distance_02.cc
  tests/base/function_signed_distance_02.output
Labels: Tests, ready to test

#12923 Enable FETools::get_projection_matrix() for multiple components
  include/deal.II/fe/fe_tools.templates.h
  tests/fe/get_projection_matrix_fe_system_01.cc
  tests/fe/get_projection_matrix_fe_system_01.output
Labels: Finite Element, ready to test

#12913 ParticleHandler: Store vector of particles per cell in std::list
  include/deal.II/particles/particle_accessor.h
  include/deal.II/particles/particle_handler.h
  include/deal.II/particles/particle_iterator.h
  source/particles/particle_handler.cc
  source/particles/property_pool.cc
  tests/particles/data_out_02.output
  tests/particles/data_out_03.output
  tests/particles/data_out_04.output
  tests/particles/particle_iterator_02.cc
  tests/particles/step-19.output
  tests/particles/step-68.with_p4est=true.mpirun=1.output
  tests/particles/step-68.with_p4est=true.mpirun=2.output
  tests/simplex/step-68.mpirun=1.output
  tests/simplex/step-68.mpirun=4.output
Labels: Particles, ready to test

#12935 Improve an error message.
  source/lac/trilinos_sparse_matrix.cc
Labels: Reviewed and ready to merge, ready to test

#12936 MatrixFreeFunctions::ConstraintKinds: rename and reorder
  include/deal.II/matrix_free/cuda_hanging_nodes_internal.h
  include/deal.II/matrix_free/evaluation_kernels_hanging_nodes.h
  include/deal.II/matrix_free/hanging_nodes_internal.h
  tests/matrix_free/hanging_node_kernels_01.cc
Labels: ready to test

#12934 Mark FEValuesExtrator objects as 'const'.
  examples/step-18/step-18.cc
  examples/step-22/step-22.cc
  examples/step-31/step-31.cc
  examples/step-32/step-32.cc
  examples/step-43/step-43.cc
  examples/step-45/step-45.cc
  examples/step-47/step-47.cc
  examples/step-51/step-51.cc
  examples/step-55/step-55.cc
  examples/step-57/step-57.cc
  examples/step-70/step-70.cc
Labels: Reviewed and ready to merge, ready to test

#12932 FEValues: simplify CellIteratorBase
  source/fe/CMakeLists.txt
  source/fe/fe_values.cc
  source/fe/fe_values.decl.1.inst.in
  source/fe/fe_values.decl.2.inst.in
  source/fe/fe_values.impl.1.inst.in
  source/fe/fe_values.impl.2.inst.in
  source/fe/fe_values.inst.in
Labels: Finite Element, ready to test

#12939 Streamline documentation.
  include/deal.II/grid/grid_in.h
Labels: Documentation, Reviewed and ready to merge, ready to test

#12941 FEValuesBase: move content around
  include/deal.II/fe/fe_values.h
  source/fe/fe_values.cc
Labels: Enhancement, ready to test

#12942 Convert loops in some tests to reference-cell-independent form.
  tests/grid/grid_in.cc
  tests/grid/grid_in_3d.cc
  tests/grid/grid_in_3d_02.cc
  tests/grid/grid_in_abaqus_01.cc
  tests/grid/grid_in_abaqus_02.cc
  tests/grid/grid_in_gmsh_01.cc
  tests/grid/grid_in_gmsh_01_v4.cc
  tests/grid/grid_in_gmsh_01_v41.cc
Labels: Tests, ready to test

#12938 Minor cleanups in thread_management.h.
  include/deal.II/base/thread_management.h
Labels: Reviewed and ready to merge, Parallel shared, ready to test

#12943 Improve an error message.
  source/grid/tria.cc
Labels: ready to test, Meshes

#12944 Check ConstraintKinds
  include/deal.II/matrix_free/hanging_nodes_internal.h
Labels: Matrix-free, ready to test

#12937 Improve assert message in DictionaryPayLoad
  include/deal.II/base/mpi_compute_index_owner_internal.h
Labels: Reviewed and ready to merge, ready to test

#12931 Optimize particle generation
  include/deal.II/particles/generators.h
  include/deal.II/particles/particle_handler.h
  source/particles/generators.cc
  source/particles/particle_handler.cc
Labels: Particles, ready to test

#12948 Step-64: be explicit regarding templater parameter
  examples/step-64/step-64.cu
Labels: Reviewed and ready to merge, ready to test

#12947 Fix types
  source/distributed/tria.cc
Labels: Reviewed and ready to merge, ready to test

#12955 Introduce mask in read_dof_values
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, ready to test

#12956 Remove some duplication in MappingCartesian
  include/deal.II/fe/mapping_cartesian.h
  source/fe/mapping_cartesian.cc
Labels: Mapping, ready to test

#12950 Add the ability to output tet meshes in gnuplot format.
  doc/news/changes/minor/20211115Bangerth-b
  source/grid/grid_out.cc
Labels: ready to test

#12946 std::unique_ptr<const CellIteratorBase> -> CellIteratorContainer
  include/deal.II/fe/fe_values.h
  source/fe/fe_values.cc
Labels: ready to test

#12961 Make the 'direction' argument of some GridTools functions 'unsigned'.
  include/deal.II/grid/grid_tools.h
  source/grid/grid_tools_dof_handlers.cc
  source/grid/grid_tools_dof_handlers.inst.in
Labels: DoFs, ready to test

#12951 Minor updates to the documentation of CellData.
  include/deal.II/grid/tria_description.h
Labels: Documentation, ready to test

#12945 Rename ConstraintKinds::type to subcell
  include/deal.II/matrix_free/cuda_hanging_nodes_internal.h
  include/deal.II/matrix_free/evaluation_kernels_hanging_nodes.h
  include/deal.II/matrix_free/hanging_nodes_internal.h
  tests/matrix_free/hanging_node_kernels_01.cc
Labels: Matrix-free, ready to test

#12959 ConstraintKinds: implement memory_consumption()
  include/deal.II/matrix_free/hanging_nodes_internal.h
  source/matrix_free/dof_info.cc
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#12962 CellIteratorContainer: inline function
  include/deal.II/fe/fe_values.h
  source/fe/fe_values.cc
Labels: Reviewed and ready to merge, Finite Element, ready to test

#12963 Fix assert in DictionaryPayLoad
  include/deal.II/base/mpi_compute_index_owner_internal.h
Labels: Bug, ready to test

#12957 Work around a (wrong) warning about an unused variable.
  include/deal.II/matrix_free/evaluation_kernels.h
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#12024 Add class FEImmersedSurfaceValues
  include/deal.II/fe/fe.h
  include/deal.II/fe/mapping.h
  include/deal.II/fe/mapping_cartesian.h
  include/deal.II/fe/mapping_q.h
  include/deal.II/non_matching/fe_immersed_values.h
  source/fe/mapping.cc
  source/fe/mapping_cartesian.cc
  source/fe/mapping_q.cc
  source/non_matching/CMakeLists.txt
  source/non_matching/fe_immersed_values.cc
  source/non_matching/fe_immersed_values.inst.in
  tests/non_matching/fe_immersed_surface_values.cc
  tests/non_matching/fe_immersed_surface_values.output
Labels: Enhancement, ready to test, Non-matching

#12966 FEEvaluation: Select correct code path for cell neighbors
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#12949 Add the ability to read COMSOL .mphtxt files.
  doc/doxygen/images/comsol-mesh-boundary-lines.png
  doc/doxygen/images/comsol-mesh-boundary-triangles.png
  doc/doxygen/images/comsol-mesh-boundary-volume-mesh.png
  doc/doxygen/images/comsol-mesh-marked-lines.png
  doc/doxygen/images/comsol-mesh-marked-triangles.png
  doc/news/changes/minor/20211115Bangerth
  include/deal.II/grid/grid_in.h
  source/grid/grid_in.cc
  tests/grid/grid_in_comsol_mphtxt_01.cc
  tests/grid/grid_in_comsol_mphtxt_01.output
  tests/grid/grids/comsol/mesh_1.mphtxt
Labels: ready to test

#12964 Utilities::MPI::create_mpi_data_type_n_bytes
  doc/news/changes/minor/20211117tjhei
  include/deal.II/base/mpi.h
  source/base/mpi.cc
  tests/mpi/create_mpi_datatype_01.cc
  tests/mpi/create_mpi_datatype_01.mpirun=2.output
Labels: ready to test

#12965 Use iterator filters in our code base.
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  include/deal.II/numerics/vector_tools_interpolate.templates.h
  include/deal.II/numerics/vector_tools_mean_value.templates.h
  source/base/mpi_remote_point_evaluation.cc
  source/distributed/repartitioning_policy_tools.cc
  source/dofs/dof_handler.cc
  source/dofs/dof_tools.cc
  source/dofs/dof_tools_constraints.cc
  source/grid/grid_tools.cc
  source/hp/refinement.cc
  source/non_matching/coupling.cc
  source/numerics/smoothness_estimator.cc
Labels: ready to test

#12978 add Assert to get_mg_dof_indices
  include/deal.II/dofs/dof_accessor.templates.h
Labels: ready to test

#12981 VectorizedArray: Simplify compare_and_apply_mask by blend instruction
  include/deal.II/base/vectorization.h
Labels: SIMD, ready to test

#12976 Add assert to FEImmersedSurfaceValues
  source/non_matching/fe_immersed_values.cc
Labels: ready to test, Non-matching

#12979 Fix GridGenerator::merge_triangulations() for simplex meshes
  source/grid/grid_generator.cc
Labels: ready to test, simplices

#12980 Fix CellAccessor::neighbor_child_on_subface()
  include/deal.II/grid/reference_cell.h
  source/grid/tria_accessor.cc
Labels: Bug, ready to test, simplices

#12982 Add iterator traits to hp::CollectionIterator
  include/deal.II/hp/collection.h
Labels: ready to test

#12984 Remove set_vertex_dof_index().
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/dofs/dof_accessor.templates.h
Labels: ready to test

#12985 Improve default behaviour of CUDAWrappers::MatrixFree::reinit()
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
Labels: Reviewed and ready to merge, GPU, Matrix-free, ready to test

#12973 fix checkpointing with >2GB per process
  source/distributed/tria_base.cc
  tests/distributed_grids/checkpointing_02.cc
Labels: ready to test

#12977 Refactor HangingNodes::setup_constraints()
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  include/deal.II/matrix_free/dof_info.h
  include/deal.II/matrix_free/dof_info.templates.h
  include/deal.II/matrix_free/hanging_nodes_internal.h
  include/deal.II/matrix_free/matrix_free.templates.h
  source/matrix_free/dof_info.cc
  tests/matrix_free/mixed_mesh_hn_algorithm_01.cc
  tests/matrix_free/mixed_mesh_hn_algorithm_01.output
Labels: Matrix-free, ready to test

#12969 Fix bug in build system when using Kokkos
  cmake/configure/configure_2_trilinos.cmake
  cmake/modules/FindKOKKOS.cmake
Labels: Build system, Reviewed and ready to merge, ready to test

#12988 Use extractors for local_rhs in step-22
  doc/news/changes/minor/20211123MarcoFeder
  examples/step-22/step-22.cc
Labels: ready to test

#12989 Fix compile warning by adding copy constructor to hp iterator
  include/deal.II/hp/collection.h
Labels: Reviewed and ready to merge, hp, ready to test

#12991 delete sequential code in big MPI datatype
  source/base/mpi.cc
Labels: Reviewed and ready to merge, ready to test

#12992 Fix bug MatrixFree::reinit
  include/deal.II/matrix_free/matrix_free.h
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#12972 Update the documentation on iterator filters.
  include/deal.II/grid/filtered_iterator.h
Labels: Documentation

#12994 Vectorize evaluation of hanging node interpolation
  include/deal.II/matrix_free/evaluation_kernels_hanging_nodes.h
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#12996 Stylist clean-up in FEEvaluationImplHangingNodes
  include/deal.II/matrix_free/evaluation_kernels_hanging_nodes.h
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#12995 Use std::vector instead of Table
  include/deal.II/base/polynomials_barycentric.h
  source/base/polynomials_barycentric.cc
Labels: ready to test

#12997 Move FEEvaluationImplHangingNodes::run_internal() into a specialized class
  include/deal.II/matrix_free/evaluation_kernels_hanging_nodes.h
Labels: Matrix-free, ready to test

#13000 Help compiler exploit hanging-node symmetries by reduced reg loads
  include/deal.II/matrix_free/evaluation_kernels_hanging_nodes.h
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#13001 Introduce internal::VectorizedArrayTrait and use it
  include/deal.II/base/vectorization.h
  include/deal.II/matrix_free/shape_info.h
  include/deal.II/matrix_free/shape_info.templates.h
Labels: SIMD, ready to test

#13002 Fix and augment documentation.
  include/deal.II/grid/grid_generator.h
Labels: Documentation

#13003 Use pre-compiled code for CellwiseInverseMassMatrix
  doc/news/changes/minor/20211129MartinKronbichler
  include/deal.II/matrix_free/evaluation_template_factory.h
  include/deal.II/matrix_free/evaluation_template_factory.templates.h
  include/deal.II/matrix_free/operators.h
Labels: Matrix-free, ready to test

#13004 Avoid dereferencing a past-the-end iterator
  include/deal.II/base/utilities.h
Labels: Reviewed and ready to merge, Miscellaneous, ready to test

#13006 Use internal rotation matrix for airfoil.
  source/grid/grid_generator.cc
Labels: Reviewed and ready to merge, ready to test

#13009 Use a simpler way to initialize default arguments.
  include/deal.II/numerics/data_out_dof_data.h
Labels: Reviewed and ready to merge, ready to test

#13010 Use a simpler way to clear a vector.
  include/deal.II/matrix_free/face_info.h
Labels: Reviewed and ready to merge, ready to test

#12999 Add FEEvaluationImplHangingNodes::RunTypes::scalar
  include/deal.II/matrix_free/evaluation_kernels_hanging_nodes.h
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#13005 Fix a memory leak in AlignedVector.
  include/deal.II/base/aligned_vector.h
  tests/base/aligned_vector_memory_02.cc
  tests/base/aligned_vector_memory_02.output
Labels: Bug, ready to test

#13011 Use narrowest possible SIMD vector for MappingQ::InternalData
  include/deal.II/fe/mapping_q.h
  include/deal.II/fe/mapping_q_internal.h
Labels: Mapping, SIMD, ready to test

#13008 Functions for calculating angles between vectors.
  doc/news/changes/minor/20211129Fehling
  include/deal.II/physics/vector_relations.h
  source/grid/manifold_lib.cc
Labels: Reviewed and ready to merge, ready to test

#13015 Guard a forward declaration.
  include/deal.II/base/multithread_info.h
Labels: Reviewed and ready to merge, ready to test

#13013 Move implementation for ShapeInfo to templates.h file
  doc/news/changes/incompatibilities/20211130MartinKronbichler
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/shape_info.h
  include/deal.II/matrix_free/shape_info.templates.h
  source/matrix_free/shape_info.inst.in
  tests/matrix_free/shape_info.cc
  tests/matrix_free/shape_info_inverse.cc
Labels: Matrix-free, ready to test

#12756 Add class NonMatching::FEValues
  include/deal.II/non_matching/fe_values.h
  source/fe/fe_values.inst.in
  source/non_matching/CMakeLists.txt
  source/non_matching/fe_values.cc
  source/non_matching/fe_values.inst.in
  tests/non_matching/fe_values.cc
  tests/non_matching/fe_values.output
Labels: ready to test, Non-matching
