Repository dealii/dealii, pull requests merged in 2021-04, with the labels that each got.

#11992 Delete default constructor FESystem
  include/deal.II/fe/fe_system.h
Labels: Reviewed and ready to merge, ready to test

#11993 Add query methods for vtk cell types in ReferenceCell
  include/deal.II/grid/reference_cell.h
  source/grid/reference_cell.cc
Labels: Enhancement, Reviewed and ready to merge, ready to test

#12000 Remove an unnecessary destructor in step-15
  examples/step-15/step-15.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#11997 Rename a variable.
  examples/step-15/step-15.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#11991 Add settings to BoomerAMG
  doc/news/changes/minor/20210331MaximilianBergbauer
  include/deal.II/lac/petsc_precondition.h
  source/lac/petsc_precondition.cc
Labels: Reviewed and ready to merge, ready to test

#11981 Added `p:d:TemporarilyMatchRefineFlags`.
  include/deal.II/distributed/tria.h
  source/distributed/tria.cc
  source/distributed/tria.inst.in
  tests/mpi/limit_p_level_difference_01.cc
  tests/mpi/limit_p_level_difference_02.cc
  tests/mpi/limit_p_level_difference_03.cc
  tests/mpi/limit_p_level_difference_04.cc
Labels: ready to test

#12003 Add a subdivided_cylinder grid generator and test
  doc/doxygen/images/subdivided_cylinder_3D.png
  doc/news/changes/minor/20210401Blais
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  source/grid/grid_generator_from_name.cc
  tests/grid/grid_generator_subdivided_cylinder.cc
  tests/grid/grid_generator_subdivided_cylinder.output
Labels: ready to test

#12002 FindARBORX: Remove library variable
  cmake/modules/FindARBORX.cmake
Labels: Build system, Reviewed and ready to merge, ready for review, ready to test

#11999 Avoid usage of the ArborX access traits in polymorphic contexts
  include/deal.II/arborx/access_traits.h
Labels: Reviewed and ready to merge, ready to test

#12004 Use an easier-to-read do...while loop.
  examples/step-15/step-15.cc
Labels: Tutorials, ready to test

#12006 Unify endlines at the end of files.
  doc/README.md
  doc/doxygen/scripts/program2html
  doc/doxygen/scripts/program2plain
  doc/doxygen/scripts/validate-xrefs.pl
  doc/news/changes/header
  doc/news/changes/header_incompatibilities
  doc/news/changes/header_major
  doc/news/changes/header_minor
  doc/news/changes/incompatibilities/20200526Maier
  doc/news/changes/minor/20200605Roth
  doc/news/changes/minor/20201020Munch
  doc/news/changes/minor/20201101Jean-PaulPelteret
  doc/news/changes/minor/20201112Munch
  doc/news/changes/minor/20210115Munch
  doc/news/changes/minor/20210205Munch
  doc/news/changes/minor/20210209Munch
  doc/news/changes/minor/20210310Fehn
  doc/news/changes/minor/20210310Munch
  doc/news/changes/minor/20210313Jean-PaulPelteret
  doc/news/changes/minor/20210313Jean-PaulPelteret-2
  doc/news/changes/minor/20210313Jean-PaulPelteret-3
  doc/news/changes/minor/20210313Jean-PaulPelteret-4
  doc/news/changes/minor/20210318Munch
  doc/news/changes/minor/20210322Schreter
  doc/news/changes/minor/20210401Blais
  examples/step-32/step-32.prm
  examples/step-34/parameters.prm
  examples/step-44/parameters.prm
  examples/step-68/parameters.prm
  examples/step-69/step-69.prm
  tests/parameter_handler/parameter_acceptor_parameters/parameter_acceptor_04.prm
  tests/parameter_handler/parameter_acceptor_parameters/parameter_acceptor_05.prm
  tests/parameter_handler/parameter_acceptor_parameters/parameter_acceptor_proxy_01.prm
  tests/parameter_handler/parameter_handler_16.prm
  tests/parameter_handler/parameter_handler_18.prm
  tests/parameter_handler/prm/multiple_parameter_loop_01.prm
  tests/parameter_handler/prm/multiple_parameter_loop_02.prm
  tests/parameter_handler/prm/parameter_handler_8.prm
  tests/parameter_handler/prm/parameter_handler_backslash_05.prm
  tests/parameter_handler/prm/parameter_handler_read_json.prm
  tests/parameter_handler/prm/parameter_handler_read_json_02.prm
Labels: ready to test

#12005 Some KINSOL documentation updates.
  include/deal.II/sundials/kinsol.h
Labels: Documentation

#11990 Fix mistake in parameter description
  include/deal.II/grid/grid_generator.h
Labels: Documentation, Reviewed and ready to merge, ready to test

#11995 Deprecate DoFTools::extract_boundary_dofs() with std::vector<bool> argument
  doc/news/changes/minor/20210330Bangerth
  doc/news/changes/minor/20210330Bangerth-2
  examples/step-11/step-11.cc
  examples/step-15/step-15.cc
  include/deal.II/dofs/dof_tools.h
  source/dofs/dof_tools.cc
  source/dofs/dof_tools.inst.in
  tests/fe/fe_q_dg0.cc
  tests/mpi/constraint_matrix_condense_01.cc
  tests/mpi/extract_boundary_dofs.cc
  tests/simplex/extract_boundary_dofs.cc
Labels: Reviewed and ready to merge, ready to test

#12010 p::d:Triangulation: fewer prepare_coarsening_and_refinement calls
  source/distributed/tria.cc
  source/grid/tria.cc
  tests/distributed_grids/refine_periodic_01.cc
  tests/distributed_grids/refine_periodic_01.mpirun=1.with_p4est=true.debug.output
  tests/distributed_grids/refine_periodic_01.mpirun=3.with_p4est=true.debug.output
  tests/distributed_grids/refine_periodic_02.cc
  tests/distributed_grids/refine_periodic_02.mpirun=1.with_p4est=true.debug.output
Labels: ready to test

#11965 FETools::Compositing::compute_nonzero_components(): add assert
  include/deal.II/fe/fe_tools.templates.h
Labels: Reviewed and ready to merge, ready to test

#12009 Use std::unique_ptr to manage memory in AlignedVector.
  include/deal.II/base/aligned_vector.h
  tests/base/aligned_vector_06.cc
  tests/base/aligned_vector_06.output
Labels: ready to test

#12017 Rename member variables.
  include/deal.II/base/aligned_vector.h
Labels: ready to test

#12018 More work on AlignedVector
  include/deal.II/base/aligned_vector.h
Labels: ready to test

#11869 Add bool type to HDF5
  doc/news/changes/minor/20210403GarciaSanchez
  include/deal.II/base/hdf5.h
  tests/base/hdf5_07.cc
  tests/base/hdf5_07.with_hdf5=true.mpirun=1.output
  tests/base/hdf5_07.with_hdf5=true.mpirun=4.output
Labels: ready to test

#12021 Play with include files
  include/deal.II/base/array_view.h
  include/deal.II/base/incremental_function.h
  include/deal.II/base/mpi.h
  include/deal.II/lac/read_write_vector.h
  tests/base/array_view_04.cc
  tests/base/array_view_05.cc
  tests/base/functions_incremental_01.cc
  tests/base/functions_incremental_02.cc
Labels: ready to test

#12019 Break generation of graphical data into its own function in step-15.
  examples/step-15/step-15.cc
Labels: ready to test

#12020 Fix a typo.
  tests/base/aligned_vector_06.cc
Labels: Documentation, Reviewed and ready to merge, ready to test

#12028 Make cmake messages easier to read.
  cmake/configure/configure_2_trilinos.cmake
Labels: ready to test

#12033 Compare pointers in find_vector_in_mf
  include/deal.II/matrix_free/matrix_free.h
Labels: Matrix-free, ready to test

#12032 Do not allocate memory for DoFs on artificial cells
  include/deal.II/dofs/dof_accessor.templates.h
  source/dofs/dof_handler.cc
  tests/serialization/dof_handler_01.with_64bit_indices=off.output
  tests/serialization/dof_handler_01.with_64bit_indices=on.output
Labels: DoFs, ready to test

#12038 Clarify an issue in the introduction of step-61.
  examples/step-61/doc/intro.dox
Labels: Documentation

#12040 Fix process_dof_indices (for artificial faces in DoFTools::set_periodicity_constraints)
  include/deal.II/dofs/dof_accessor.templates.h
Labels: Bug, DoFs, Parallel distributed, Reviewed and ready to merge, ready to test

#12041 Bug in weighting_callback for uninitialized DoFHandlers.
  include/deal.II/distributed/cell_weights.h
  source/distributed/cell_weights.cc
Labels: Bug, Parallel, hp, ready to test

#12042 Get rid of create_triangulation_compatibility in the UCD reader.
  source/grid/grid_in.cc
  source/grid/grid_reordering.cc
Labels: Triangulation, ready to test

#12043 Remove hp::DoFHandler from tutorial list.
  doc/doxygen/tutorial/tutorial.h.in
Labels: Documentation

#12044 CMake: FindKOKKOS: Work around configuration failure
  cmake/modules/FindKOKKOS.cmake
Labels: Reviewed and ready to merge, ready to test

#12046 Remove calls to create_triangulation_compatibility in GridGenerator.
  source/grid/grid_generator.cc
Labels: Triangulation, ready to test

#12045 Remove two more create_triangulation_compatibility calls.
  source/grid/grid_in.cc
Labels: Triangulation, ready to test

#12030 Support different KINSOL versions.
  include/deal.II/sundials/kinsol.h
  source/sundials/kinsol.cc
Labels: ready to test

#12026 Use a better filename for SUNDIALS finding.
  cmake/modules/FindSUNDIALS.cmake
Labels: ready to test

#12027 Improve error messages during configuration.
  cmake/macros/macro_deal_ii_find_file.cmake
  cmake/macros/macro_deal_ii_find_library.cmake
  cmake/macros/macro_deal_ii_find_path.cmake
  cmake/macros/macro_deal_ii_find_program.cmake
Labels: Build system, ready to test

#12048 Get rid of create_triangulation_compatibility in the GMSH reader.
  source/grid/grid_in.cc
Labels: Triangulation, ready to test

#12049 Remove remaining create_triangulation_compatibility calls.
  include/deal.II/grid/persistent_tria.h
  include/deal.II/grid/tria.h
  source/grid/grid_in.cc
  source/grid/grid_reordering.cc
Labels: Triangulation, ready to test

#12031 Update the KINSOL callbacks to what KINSOL current provides.
  include/deal.II/sundials/kinsol.h
  source/sundials/kinsol.cc
  tests/sundials/kinsol_03_new_interface.cc
  tests/sundials/kinsol_03_new_interface.with_sundials.geq.5.0.0.output
  tests/sundials/kinsol_04_new_interface.cc
  tests/sundials/kinsol_04_new_interface.with_sundials.geq.5.0.0.output
  tests/sundials/kinsol_05_new_interface.cc
  tests/sundials/kinsol_05_new_interface.with_sundials.geq.5.0.0.output
Labels: ready to test

#12053 Fix test matrix_free/ecl_02
  tests/matrix_free/ecl_02.cc
  tests/matrix_free/ecl_02.output.novec
Labels: ready to test

#12051 Fix matrix_free/compute_diagonal tests in release mode
  tests/matrix_free/compute_diagonal_util.h
Labels: ready to test

#12055 Fix grammar.
  examples/step-58/doc/intro.dox
Labels: Reviewed and ready to merge

#12060 fix a -Wdtor warning
  source/sundials/sunlinsol_wrapper.cc
Labels: ready for review, ready to test

#12054 Utilities::MPI::mpi_sum_avg: create MPI_Datatype and MPI_Op once
  doc/news/changes/minor/20210418Maier
  doc/news/changes/minor/20210419Maier
  include/deal.II/base/mpi.h
  source/base/mpi.cc
  tests/base/mpi_init_finalize_signals_01.cc
  tests/base/mpi_init_finalize_signals_01.mpirun=1.output
Labels: Bug, Parallel, ready for review, ready to test

#12061 fix a warning
  source/base/quadrature_lib.cc
Labels: Reviewed and ready to merge, ready for review, ready to test

#12059 Remove GridReordering part 1
  doc/doxygen/headers/grid.h
  doc/doxygen/headers/reordering.h
  include/deal.II/grid/grid_reordering.h
Labels: Documentation, ready to test

#12063 Add error message to GridIn::ExcNoTriangulationSelected
  include/deal.II/grid/grid_in.h
Labels: Documentation, Reviewed and ready to merge, Triangulation, ready to test

#12064 Add a test for AlignedVector.
  tests/base/aligned_vector_memory_01.cc
  tests/base/aligned_vector_memory_01.output
Labels: ready to test

#12068 Improve the scalar assignment exception message.
  include/deal.II/base/exceptions.h
  include/deal.II/base/tensor.h
Labels: Enhancement, Reviewed and ready to merge, ready to test

#12067 Deprecate TriaAccessor::number_of_children.
  doc/news/changes/minor/20210420Bangerth
  examples/step-30/doc/intro.dox
  examples/step-30/step-30.cc
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_accessor.templates.h
  source/dofs/dof_tools_constraints.cc
  source/dofs/dof_tools_sparsity.cc
  source/fe/fe_values.cc
  source/grid/tria.cc
  source/grid/tria_accessor.cc
  tests/aniso/mesh_3d_21.cc
Labels: Reviewed and ready to merge, ready to test

#12070 Minor optimization in Utilities::MPI::broadcast().
  include/deal.II/base/mpi.h
Labels: Reviewed and ready to merge, ready to test

#12065 Minor updates to the grid reordering module.
  doc/doxygen/headers/reordering.h
  doc/doxygen/references.bib
Labels: Documentation

#12069 Simplify control flow in AlignedVector::resize{,_fast}.
  include/deal.II/base/aligned_vector.h
Labels: ready to test

#12050 Fix test matrix_free/categorize_by_boundary_ids_01
  tests/matrix_free/categorize_by_boundary_ids_01.cc
Labels: ready to test

#12075 Doc: Function has been renamed
  include/deal.II/hp/refinement.h
  tests/hp/limit_p_level_difference_01.cc
  tests/hp/limit_p_level_difference_02.cc
  tests/hp/limit_p_level_difference_03.cc
  tests/hp/limit_p_level_difference_04.cc
  tests/mpi/limit_p_level_difference_01.cc
  tests/mpi/limit_p_level_difference_02.cc
  tests/mpi/limit_p_level_difference_03.cc
  tests/mpi/limit_p_level_difference_04.cc
  tests/sharedtria/limit_p_level_difference_01.cc
  tests/sharedtria/limit_p_level_difference_02.cc
  tests/sharedtria/limit_p_level_difference_03.cc
  tests/sharedtria/limit_p_level_difference_04.cc
Labels: Documentation, hp

#12071 Move GridReordering<dim>::invert_all_negative_measure_cells().
  include/deal.II/grid/grid_reordering.h
  include/deal.II/grid/grid_tools.h
  source/grid/grid_generator.cc
  source/grid/grid_in.cc
  source/grid/grid_reordering.cc
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
  source/grid/grid_tools_nontemplates.cc
Labels: Triangulation, ready to test

#12073 step-27: limit p-level difference
  examples/step-27/doc/results.dox
  examples/step-27/step-27.cc
Labels: Reviewed and ready to merge, Tutorials, hp, ready to test

#12081 Forward declare explicit template specializations for copy_connectivity
  include/deal.II/distributed/p4est_wrappers.h
Labels: ready for review, ready to test

#12076 Correct 2-D FE_Nedelec Interpolation
  doc/news/changes/minor/20210422Harmon
  source/fe/fe_nedelec.cc
  tests/fe/interpolate_common.h
  tests/fe/interpolate_nedelec.cc
  tests/fe/interpolate_nedelec.output
Labels: Bug, Reviewed and ready to merge, ready to test

#12084 Guard SUNDIALS variables more carefully
  include/deal.II/sundials/sundials_backport.h
Labels: Reviewed and ready to merge, ready to test

#12082 Move GridReordering::reorder_cells().
  doc/news/changes/incompatibilities/20210422DavidWells
  include/deal.II/grid/grid_reordering.h
  include/deal.II/grid/grid_tools.h
  source/grid/grid_generator.cc
  source/grid/grid_in.cc
  source/grid/grid_reordering.cc
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
Labels: Reviewed and ready to merge, Triangulation, ready to test

#12086 Fix warning about unused function in PETScWrappers source file
  source/lac/petsc_precondition.cc
Labels: ready to test

#12085 Fix compilation with gcc-5.
  source/hp/refinement.cc
Labels: Reviewed and ready to merge, ready to test

#12088 Fix a static_assert to actually make sense.
  include/deal.II/base/tensor.h
Labels: ready to test

#12057 Provide a move constructor for InterpolatedTensorProductGridData.
  doc/news/changes/minor/20210419Bangerth
  include/deal.II/base/function_lib.h
  source/base/function_lib.cc
  tests/base/functions_10_move.cc
  tests/base/functions_10_move.output
Labels: ready to test

#12077 Remove `parallel::distributed::ErrorPredictor`.
  doc/news/changes/incompatibilities/20210421Fehling
  include/deal.II/distributed/error_predictor.h
  include/deal.II/hp/refinement.h
  source/distributed/CMakeLists.txt
  source/distributed/error_predictor.cc
  source/distributed/error_predictor.inst.in
  tests/mpi/error_prediction_01.cc
  tests/mpi/error_prediction_01.with_p4est=true.mpirun=1.output
  tests/mpi/error_prediction_01.with_p4est=true.mpirun=4.output
  tests/mpi/error_prediction_02.cc
  tests/mpi/error_prediction_02.with_p4est=true.mpirun=1.output
  tests/mpi/error_prediction_02.with_p4est=true.mpirun=4.output
Labels: Parallel distributed, Reviewed and ready to merge, hp, ready to test

#12089 add missing instantiations
  source/dofs/dof_tools_sparsity.inst.in
Labels: Bug, ready for review, ready to test

#12091 tests/sundials/* Use new variants already for version 5.2.0 onwards
  tests/sundials/arkode_01.with_sundials.geq.5.2.0.output
  tests/sundials/arkode_01.with_sundials.le.5.2.0.output
  tests/sundials/arkode_02.with_sundials.geq.5.2.0.output
  tests/sundials/arkode_03.with_sundials.geq.5.2.0.output
  tests/sundials/arkode_03.with_sundials.le.5.2.0.output
  tests/sundials/arkode_06.with_sundials.geq.5.2.0.output
  tests/sundials/arkode_07.with_sundials.geq.5.2.0.output
  tests/sundials/arkode_08.with_sundials.geq.5.2.0.output
  tests/sundials/arkode_repeated_solve.with_sundials.geq.5.2.0.output
Labels: ready for review, ready to test

#11122 Check MSVC's constexpr support.
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/base/table_indices.h
  include/deal.II/base/tensor.h
  include/deal.II/base/tensor_accessors.h
Labels: Miscellaneous, ready for review, ready to test

#12093 Guard if code in MatrixFreeTools if doxygen is used
  include/deal.II/matrix_free/tools.h
Labels: Reviewed and ready to merge, ready to test

#12083 Simplify some type computations in FEValuesViews.
  doc/news/changes/minor/20210425Bangerth
  include/deal.II/fe/fe_values.h
  include/deal.II/meshworker/scratch_data.h
  source/fe/fe_values.cc
  source/fe/fe_values.inst.in
  tests/fe/fe_values_view_get_function_from_local_dof_values_01.cc
  tests/fe/fe_values_view_get_function_from_local_dof_values_02.cc
  tests/fe/fe_values_views_types.cc
Labels: ready to test

#12094 Provide a move constructor for Functions::InterpolatedUniformGridData.
  doc/news/changes/minor/20210419Bangerth
  include/deal.II/base/function_lib.h
  source/base/function_lib.cc
  tests/base/functions_11_move.cc
  tests/base/functions_11_move.output
Labels: ready to test

#12079 Add level set functions for a plane and a sphere
  include/deal.II/base/function_level_set.h
  source/base/CMakeLists.txt
  source/base/function_level_set.cc
  source/base/function_level_set.inst.in
  tests/base/function_level_set.cc
  tests/base/function_level_set.output
Labels: Reviewed and ready to merge, ready to test

#12062 Add function estimating Function bounds over a BoundingBox
  doc/news/changes/minor/20210425SimonSticko
  include/deal.II/base/function_tools.h
  source/base/CMakeLists.txt
  source/base/function_tools.cc
  source/base/function_tools.inst.in
  tests/base/taylor_estimate_function_bounds.cc
  tests/base/taylor_estimate_function_bounds.output
Labels: Reviewed and ready to merge, ready to test

#12095 Fix mpi/extract_boundary_dofs
  tests/mpi/extract_boundary_dofs.cc
Labels: Reviewed and ready to merge, ready to test

#12096 Fix base/unsubscribe_subscriptor for clang
  tests/base/unsubscribe_subscriptor.debug.output.clang-6
Labels: Reviewed and ready to merge, ready to test

#12098 Fix parameter_handler/parameter_handler_25 for clang12
  tests/parameter_handler/parameter_handler_25.output.std
Labels: Reviewed and ready to merge, ready to test

#12099 Fix the number of entries in the FEValues view cache.
  source/fe/fe_values.cc
Labels: Reviewed and ready to merge, ready to test

#12097 Fix lac/vector_memory for Clang12
  tests/lac/vector_memory.debug.output.clang12
Labels: Reviewed and ready to merge, ready to test

#12100 Fix up tests for ICC 2018
  include/deal.II/grid/tria.h
  source/grid/tria.cc
  tests/base/unsubscribe_subscriptor.debug.output.intel
  tests/parameter_handler/parameter_handler_25.output2
Labels: ready to test

#12022 Add AlignedVector::replicate_across_communicator()
  doc/news/changes/minor/20210406Bangerth
  include/deal.II/base/aligned_vector.h
  tests/base/aligned_vector_replicate_01.cc
  tests/base/aligned_vector_replicate_01.mpirun=3.output
  tests/base/aligned_vector_replicate_02.cc
  tests/base/aligned_vector_replicate_02.mpirun=3.output
  tests/base/aligned_vector_replicate_03.cc
  tests/base/aligned_vector_replicate_03.mpirun=3.output
  tests/base/aligned_vector_replicate_04.cc
  tests/base/aligned_vector_replicate_04.mpirun=3.output
Labels: ready to test

#12107 Replace some more occurrences of GeometryInfo.
  source/grid/tria.cc
Labels: Reviewed and ready to merge, ready to test, simplices

#12106 Make Triangulation::get_boundary_ids() work for non-hypercube cells.
  source/grid/tria.cc
  tests/simplex/get_boundary_ids_01.cc
  tests/simplex/get_boundary_ids_01.with_simplex_support=on.output
Labels: Reviewed and ready to merge, ready to test

#12105 Fix a function for non-quads/hexes.
  source/grid/tria.cc
Labels: Reviewed and ready to merge, ready to test

#12103 Simplify use of a function in ReferenceCell.
  include/deal.II/grid/reference_cell.h
Labels: Reviewed and ready to merge, ready to test

#12104 Provide links to tutorial programs.
  include/deal.II/meshworker/mesh_loop.h
Labels: Documentation

#12109 Do not actually define the general Table class.
  include/deal.II/base/table.h
Labels: Reviewed and ready to merge, ready to test

#12110 Improve the documentation of the Table<N,T> classes slightly.
  include/deal.II/base/table.h
Labels: Documentation, ready to test

#12112 Do not redefine functions that we can import from the base class.
  include/deal.II/base/table.h
Labels: Reviewed and ready to merge, ready to test
