Repository dealii/dealii, pull requests merged in 2021-02, with the labels that each got.

#11647 Move the function that generates a reference cell to GridGenerator.
  include/deal.II/fe/fe_tools.templates.h
  include/deal.II/grid/grid_generator.h
  include/deal.II/grid/reference_cell.h
  source/grid/grid_generator.cc
  source/grid/grid_generator.inst.in
  source/grid/reference_cell.cc
  source/grid/reference_cell.inst.in
  tests/simplex/fe_p_bubbles_02.cc
  tests/simplex/orientation_02.cc
Labels: ready to test

#11652 Fix DataOut for mixed meshes and vector quantities
  include/deal.II/numerics/data_out_dof_data.templates.h
  tests/simplex/data_out_write_vtk_02.cc
  tests/simplex/data_out_write_vtk_02.with_simplex_support=on.output
Labels: ready to test, simplices

#11657 Fix missing call to update_cell_relations()
  source/distributed/fully_distributed_tria.cc
Labels: Reviewed and ready to merge, ready to test

#11660 ARKode with L:d:(Block)Vector
  doc/news/changes/minor/20210131Proell
  source/sundials/arkode.cc
  tests/sundials/arkode_03.cc
Labels: ready to test

#11661 ARKode: remove/deprecate unused functionality
  doc/news/changes/incompatibilities/20210201Proell
  include/deal.II/sundials/arkode.h
  source/sundials/arkode.cc
  tests/sundials/arkode_01.cc
  tests/sundials/arkode_02.cc
  tests/sundials/arkode_03.cc
  tests/sundials/arkode_04.cc
  tests/sundials/arkode_05.cc
  tests/sundials/arkode_06.cc
  tests/sundials/arkode_07.cc
  tests/sundials/arkode_08.cc
Labels: Reviewed and ready to merge, ready to test

#11659 Move some BoundingBox access functions to the header.
  include/deal.II/base/bounding_box.h
  source/base/bounding_box.cc
Labels: Enhancement, ready to test

#11662 Make unit_normal_vectors() a member of ReferenceCell::Type.
  include/deal.II/grid/reference_cell.h
  include/deal.II/meshworker/mesh_loop.h
  tests/simplex/unit_tangential_vectors_01.cc
Labels: ready to test

#11641 Shorten a test suite function.
  tests/parameter_handler/parameter_acceptor_09.output
  tests/parameter_handler/parameter_handler_27.output
  tests/parameter_handler/parameter_handler_28.output
  tests/tests.h
Labels: Miscellaneous, ready to test

#11663 Simplify a computation.
  include/deal.II/grid/reference_cell.h
Labels: Reviewed and ready to merge, ready to test

#11665 Move an exception to the top of a function.
  source/distributed/tria.cc
Labels: ready to test

#11664 Make get_gauss_type_quadrature() and get_nodal_type_quadrature() members of ReferenceCell::Type.
  include/deal.II/fe/fe_tools.templates.h
  include/deal.II/grid/reference_cell.h
  source/fe/mapping_fe_field.cc
  source/grid/reference_cell.cc
  source/grid/reference_cell.inst.in
  tests/simplex/fe_p_bubbles_02.cc
Labels: Reviewed and ready to merge, ready to test

#11669 Removed ansi flag from intel compiler setup
  cmake/setup_compiler_flags_intel.cmake
Labels: Reviewed and ready to merge, ready to test

#11666 Improve a few error messages.
  include/deal.II/meshworker/mesh_loop.h
Labels: ready to test

#11673 Move n_vertices_to_type() into ReferenceCell::Type.
  include/deal.II/grid/connectivity.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.templates.h
  source/grid/grid_in.cc
Labels: Reviewed and ready to merge, ready to test

#11671 Make sure we return all manifold ids.
  doc/news/changes/minor/20210203LucaHeltai
  source/grid/tria.cc
  tests/manifold/manifold_id_08.cc
  tests/manifold/manifold_id_08.output
Labels: ready for review, ready to test

#11644 Feature orientation test mesh
  doc/news/changes/incompatibilities/20210128Simon
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  tests/fe/fe_conformity_dim_2_fe_abf.cc
  tests/fe/fe_conformity_dim_2_fe_abf.output
  tests/fe/fe_conformity_dim_2_fe_bdm.cc
  tests/fe/fe_conformity_dim_2_fe_bdm.output
  tests/fe/fe_conformity_dim_2_fe_nedelec.cc
  tests/fe/fe_conformity_dim_2_fe_nedelec.output
  tests/fe/fe_conformity_dim_2_fe_nedelec_sz.cc
  tests/fe/fe_conformity_dim_2_fe_nedelec_sz.output
  tests/fe/fe_conformity_dim_2_fe_q.cc
  tests/fe/fe_conformity_dim_2_fe_q.output
  tests/fe/fe_conformity_dim_2_fe_rt.cc
  tests/fe/fe_conformity_dim_2_fe_rt.output
  tests/fe/fe_conformity_dim_2_fe_rt_nodal.cc
  tests/fe/fe_conformity_dim_2_fe_rt_nodal.output
  tests/fe/fe_conformity_fill_vector_random.h
  tests/fe/fe_conformity_test.h
  tests/grid/grid_generator_non_standard_orientation_mesh_2d.cc
  tests/grid/grid_generator_non_standard_orientation_mesh_2d.output
  tests/grid/grid_generator_non_standard_orientation_mesh_3d.cc
  tests/grid/grid_generator_non_standard_orientation_mesh_3d.output
Labels: ready to test

#11672 Make a serialization function 'public'.
  include/deal.II/lac/la_vector.h
Labels: ready to test

#11677 Get rid of the PolynomialType template argument of FE_Q_Base.
  doc/news/changes/incompatibilities/20210203Bangerth
  include/deal.II/fe/fe_bernstein.h
  include/deal.II/fe/fe_q.h
  include/deal.II/fe/fe_q_base.h
  include/deal.II/fe/fe_q_bubbles.h
  include/deal.II/fe/fe_q_dg0.h
  include/deal.II/fe/fe_q_iso_q1.h
  source/fe/fe_bernstein.cc
  source/fe/fe_q.cc
  source/fe/fe_q_base.cc
  source/fe/fe_q_base.inst.in
  source/fe/fe_q_bubbles.cc
  source/fe/fe_q_dg0.cc
  source/fe/fe_q_iso_q1.cc
Labels: Reviewed and ready to merge, ready to test

#11680 Provide correct mappings to function calls.
  source/grid/grid_generator.cc
  source/particles/particle_handler.cc
Labels: Reviewed and ready to merge, ready to test

#11682 CMake: Add a compatibility check for taskflow-3.0 onwards
  cmake/configure/configure_1_taskflow.cmake
Labels: Build system, External libraries, Reviewed and ready to merge, ready to test

#11638 simplex: step-6
  tests/simplex/step-06.cc
  tests/simplex/step-06.with_simplex_support=on.output
Labels: ready to test

#11383 Add a filter=output attribute to output files
  .gitattributes
Labels: Infrastructure

#11686 Disable warnings before including boost header
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/grid/tria_accessor.h
  source/base/tensor_product_polynomials.cc
  source/fe/fe_values.cc
  source/fe/mapping_fe.cc
  source/fe/mapping_q_generic.cc
  source/grid/manifold.cc
  source/grid/manifold_lib.cc
  source/lac/trilinos_sparse_matrix.cc
Labels: ready to test

#11683 CMake: record the C++ language standard detected during configure
  cmake/setup_write_config.cmake
Labels: Build system, Reviewed and ready to merge, ready to test

#11684 Documentation: Advertise <deal.II/lac/linear_operator_tools.h>
  doc/doxygen/headers/laoperators.h
  include/deal.II/lac/linear_operator.h
Labels: Reviewed and ready to merge, ready to test

#11675 Ensure exactly one newline at the end of each file.
  contrib/utilities/indent
Labels: ready to test

#11690 Fix compilation with ExodusII.
  source/grid/grid_in.cc
Labels: Miscellaneous, Reviewed and ready to merge, ready to test

#11689 Move the get/set_bit() functions into namespace Utilities.
  doc/news/changes/minor/20210205WolfgangBangerth
  include/deal.II/base/utilities.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.templates.h
Labels: ready to test

#11678 Enable AffineConstraints::copy_from for mixed number (double/float)
  doc/news/changes/minor/20210205Munch
  include/deal.II/lac/affine_constraints.h
  include/deal.II/lac/affine_constraints.templates.h
  tests/lac/constraints_copy_from_mixed.cc
  tests/lac/constraints_copy_from_mixed.output
Labels: Reviewed and ready to merge, ready to test

#11693 Rename namespace internal::Info to internal::ReferenceCell.
  include/deal.II/fe/fe_tools.templates.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_accessor.templates.h
  include/deal.II/matrix_free/shape_info.templates.h
  source/base/data_out_base.cc
  source/dofs/dof_tools.cc
  source/fe/fe.cc
  source/fe/fe_data.cc
  source/fe/fe_values.cc
  source/fe/mapping_fe.cc
  source/fe/mapping_fe_field.cc
  source/grid/grid_in.cc
  source/grid/tria_accessor.cc
  source/simplex/fe_lib.cc
  tests/simplex/fe_lib_01.cc
  tests/simplex/orientation_02.cc
  tests/simplex/reference_cell_kind_01.cc
  tests/simplex/unit_tangential_vectors_01.cc
Labels: ready to test

#11694 Remove a couple of unnecessary forward declarations.
  include/deal.II/grid/reference_cell.h
Labels: ready to test

#11700 Fix missing header in sundials/n_vector.h
  include/deal.II/sundials/n_vector.h
Labels: ready to test

#11695 Make a function 'constexpr'.
  include/deal.II/grid/reference_cell.h
  source/grid/reference_cell.cc
Labels: Reviewed and ready to merge, ready to test

#11697 Fix python wrapper.
  contrib/python-bindings/source/wrappers.cc
Labels: Reviewed and ready to merge, ready to test

#11702 Move get_default_linear_mapping() to mapping.h/cc.
  include/deal.II/fe/mapping.h
  include/deal.II/grid/reference_cell.h
  source/fe/mapping.cc
  source/fe/mapping.inst.in
  source/grid/reference_cell.cc
  source/grid/reference_cell.inst.in
Labels: Reviewed and ready to merge, ready to test

#11705 Spell out Tri->Triangle, Quad->Quadrilateral, etc.
  include/deal.II/grid/connectivity.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.templates.h
  include/deal.II/numerics/data_out_dof_data.templates.h
  source/base/data_out_base.cc
  source/base/qprojector.cc
  source/dofs/dof_handler_policy.cc
  source/fe/fe.cc
  source/fe/fe_data.cc
  source/grid/grid_generator.cc
  source/grid/grid_in.cc
  source/grid/grid_out.cc
  source/grid/reference_cell.cc
  source/grid/tria.cc
  source/grid/tria_accessor.cc
  source/simplex/fe_lib.cc
  tests/hp/fe_nothing_22.cc
  tests/simplex/data_out_write_vtk_02.cc
  tests/simplex/matrix_free_02.cc
  tests/simplex/matrix_free_04.cc
  tests/simplex/orientation_01.cc
  tests/simplex/orientation_02.cc
  tests/simplex/q_projection_01.cc
  tests/simplex/reference_cell_kind_01.cc
  tests/simplex/unit_tangential_vectors_01.cc
  tests/simplex/variable_face_quadratures_01.cc
Labels: ready to test

#11692 Avoid using a function in a context in which it makes no sense.
  source/grid/tria.cc
Labels: ready to test

#11704 MatrixFreeTools::compute_matrix() make it work for float
  include/deal.II/matrix_free/tools.h
  tests/matrix_free/compute_diagonal_01.cc
  tests/matrix_free/compute_diagonal_01.with_mpi=true.with_p4est=true.mpirun=1.output
  tests/matrix_free/compute_diagonal_01.with_mpi=true.with_p4est=true.mpirun=3.output
Labels: Reviewed and ready to merge, ready to test

#11701 Deal with no MPI in sundials/n_vector.templates.h
  include/deal.II/sundials/n_vector.templates.h
Labels: ready to test

#11709 Move the special ReferenceCell objects into a namespace of their own.
  include/deal.II/grid/connectivity.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.templates.h
  include/deal.II/matrix_free/mapping_info.templates.h
  include/deal.II/numerics/data_out_dof_data.templates.h
  source/base/data_out_base.cc
  source/base/qprojector.cc
  source/dofs/dof_handler_policy.cc
  source/fe/fe.cc
  source/fe/fe_data.cc
  source/grid/grid_generator.cc
  source/grid/grid_in.cc
  source/grid/grid_out.cc
  source/grid/reference_cell.cc
  source/grid/tria.cc
  source/grid/tria_accessor.cc
  source/simplex/fe_lib.cc
  tests/hp/fe_nothing_22.cc
  tests/simplex/cell_measure_01.cc
  tests/simplex/data_out_write_vtk_02.cc
  tests/simplex/matrix_free_02.cc
  tests/simplex/matrix_free_04.cc
  tests/simplex/orientation_01.cc
  tests/simplex/orientation_02.cc
  tests/simplex/q_projection_01.cc
  tests/simplex/reference_cell_kind_01.cc
  tests/simplex/unit_tangential_vectors_01.cc
  tests/simplex/variable_face_quadratures_01.cc
Labels: ready to test

#11681 Say more about possible extensions for step-34.
  examples/step-34/doc/results.dox
Labels: ready to test

#11703 Fix clear particle locations in property pool
  source/particles/property_pool.cc
  tests/particles/step-68.cc
  tests/particles/step-68.with_p4est=true.mpirun=1.output
  tests/particles/step-68.with_p4est=true.mpirun=2.output
Labels: Reviewed and ready to merge, ready to test

#11712 Hide a forward declaration from doxygen.
  include/deal.II/grid/reference_cell.h
Labels: Reviewed and ready to merge, ready to test

#11710 Minor documentation updates
  include/deal.II/base/polynomials_piecewise.h
  include/deal.II/base/scalar_polynomials_base.h
Labels: Documentation

#11696 Update SparsityPattern/SparseMatrix::copy_from() documentation.
  include/deal.II/lac/sparse_matrix.h
  include/deal.II/lac/sparsity_pattern.h
Labels: Documentation

#11713 Also move get_hypercube/simplex() into namespace ReferenceCells.
  include/deal.II/base/qprojector.h
  include/deal.II/fe/fe_poly_face.h
  include/deal.II/fe/mapping_q1.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/grid_tools_cache.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/matrix_free/mapping_info.templates.h
  include/deal.II/matrix_free/matrix_free.templates.h
  include/deal.II/matrix_free/shape_info.templates.h
  include/deal.II/numerics/vector_tools_constraints.h
  include/deal.II/numerics/vector_tools_project.templates.h
  include/deal.II/particles/generators.h
  source/base/data_out_base.cc
  source/base/qprojector.cc
  source/base/tensor_product_polynomials.cc
  source/fe/fe_nedelec.cc
  source/fe/fe_nothing.cc
  source/fe/fe_q_base.cc
  source/fe/mapping_cartesian.cc
  source/fe/mapping_fe_field.cc
  source/fe/mapping_manifold.cc
  source/fe/mapping_q_generic.cc
  source/grid/grid_generator.cc
  source/grid/manifold.cc
  source/grid/tria.cc
  source/multigrid/mg_tools.cc
  source/numerics/data_out.cc
  source/simplex/fe_lib.cc
  tests/simplex/cell_measure_01.cc
Labels: ready to test

#11685 Add q witherden vincent
  doc/doxygen/references.bib
  include/deal.II/simplex/quadrature_lib.h
  source/simplex/quadrature_lib.cc
  tests/simplex/q_witherden_vincent_01.cc
  tests/simplex/q_witherden_vincent_01.with_simplex_support=on.output
Labels: Quadrature, Reviewed and ready to merge, ready to test, simplices

#11706 Add utility functions to create polynomial coarsening sequences
  include/deal.II/multigrid/mg_transfer_global_coarsening.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  tests/multigrid-global-coarsening/create_polynomial_coarsening_sequence_01.cc
  tests/multigrid-global-coarsening/create_polynomial_coarsening_sequence_01.output
  tests/multigrid-global-coarsening/multigrid_p_01.cc
  tests/multigrid-global-coarsening/multigrid_util.h
Labels: Multigrid, Reviewed and ready to merge, ready to test

#11578 Enable MGTwoLevelTransfer::reinit_geometric_transfer for FECollections
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  tests/multigrid-global-coarsening/mg_transfer_a_03.cc
  tests/multigrid-global-coarsening/mg_transfer_a_03.with_p4est=true.mpirun=2.output
Labels: Multigrid, ready to test

#11670 Rename PETScWrappers::PreconditionerBase to PreconditionBase
  doc/news/changes/minor/20210203PasqualeAfrica
  include/deal.II/lac/petsc_precondition.h
  include/deal.II/lac/petsc_solver.h
  source/lac/petsc_precondition.cc
  source/lac/petsc_solver.cc
  tests/slepc/step-36_parallel.cc
  tests/slepc/step-36_parallel_02.cc
  tests/slepc/step-36_parallel_03.cc
Labels: ready to test

#11707 Add utility functions to create geometric coarsening sequences
  include/deal.II/multigrid/mg_transfer_global_coarsening.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  source/multigrid/mg_transfer_global_coarsening.inst.in
  tests/multigrid-global-coarsening/create_geometric_coarsening_sequence_01.cc
  tests/multigrid-global-coarsening/create_geometric_coarsening_sequence_01.with_p4est=true.mpirun=1.output
  tests/multigrid-global-coarsening/create_geometric_coarsening_sequence_01.with_p4est=true.mpirun=2.output
Labels: Multigrid, Reviewed and ready to merge, ready to test

#11717 Add a link for std::span.
  include/deal.II/base/array_view.h
Labels: Documentation

#11461 Rename zero_out_ghosts() to zero_out_ghost_values()
  doc/news/changes/incompatibilities/20210104Munch
  examples/step-48/step-48.cc
  examples/step-67/step-67.cc
  examples/step-68/step-68.cc
  include/deal.II/distributed/solution_transfer.h
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/la_parallel_block_vector.h
  include/deal.II/lac/la_parallel_block_vector.templates.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/multigrid/mg_transfer.templates.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  source/multigrid/mg_transfer_matrix_free.cc
  tests/cuda/parallel_vector_15.cu
  tests/cuda/parallel_vector_16.cu
  tests/cuda/parallel_vector_22.cu
  tests/dofs/dof_tools_extract_dofs_with_support_contained_within_04.cc
  tests/matrix_free/compare_faces_by_cells.cc
  tests/matrix_free/loop_boundary.cc
  tests/matrix_free/multigrid_dg_sip_01.cc
  tests/matrix_free/multigrid_dg_sip_02.cc
  tests/mpi/parallel_block_vector_02.cc
  tests/mpi/parallel_block_vector_13.cc
  tests/mpi/parallel_vector_15.cc
  tests/mpi/parallel_vector_16.cc
  tests/mpi/parallel_vector_22.cc
  tests/numerics/project_parallel_common.h
Labels: Parallel distributed, ready to test

#11716 Group members of ReferenceCell for the documentation.
  include/deal.II/grid/reference_cell.h
Labels: ready to test, simplices

#11715 MGTransferGlobalCoarseningTools::create_geometric_coarsening_sequence load forest directly
  doc/news/changes/minor/20210209Munch
  include/deal.II/distributed/p4est_wrappers.h
  include/deal.II/distributed/tria.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  source/distributed/p4est_wrappers.cc
  source/distributed/tria.cc
Labels: Multigrid, Reviewed and ready to merge, ready to test

#11720 Allow conversion from C-style array to ArrayView.
  doc/news/changes/minor/20210209WolfgangBangerth
  include/deal.II/base/array_view.h
  tests/base/array_view_17.cc
  tests/base/array_view_17.output
Labels: Reviewed and ready to merge, ready to test

#11698 Accept unique_ptr in different MG-related classes
  include/deal.II/base/utilities.h
  include/deal.II/multigrid/mg_matrix.h
  include/deal.II/multigrid/mg_smoother.h
Labels: Multigrid, Reviewed and ready to merge, ready to test

#11708 Remove MatrixType from MGTransferGlobalCoarsening
  include/deal.II/multigrid/mg_transfer_global_coarsening.h
  tests/multigrid-global-coarsening/multigrid_a_01.cc
  tests/multigrid-global-coarsening/multigrid_p_01.cc
Labels: ready to test

#11429 Generalize MGTwoLevelTransfer for simplex meshes
  include/deal.II/multigrid/mg_transfer_global_coarsening.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  tests/multigrid-global-coarsening/multigrid_a_01.cc
  tests/multigrid-global-coarsening/multigrid_a_01.mpirun=1.with_trilinos=true.with_simplex_support=on.output
  tests/multigrid-global-coarsening/multigrid_p_01.cc
  tests/multigrid-global-coarsening/multigrid_p_01.mpirun=1.with_trilinos=true.with_simplex_support=on.output
Labels: Multigrid, ready for review, ready to test

#11722 Add recv and send data to particle cache
  include/deal.II/particles/partitioner.h
  source/particles/particle_handler.cc
Labels: Particles, Reviewed and ready to merge, ready to test

#11372 Generalize ShapeInfo::reinit
  include/deal.II/matrix_free/shape_info.h
  include/deal.II/matrix_free/shape_info.templates.h
  include/deal.II/matrix_free/util.h
Labels: ready to test

#11724 Extract SUNLinSolver wrapper from ARKode
  include/deal.II/sundials/arkode.h
  include/deal.II/sundials/sunlinsol_wrapper.h
  source/sundials/CMakeLists.txt
  source/sundials/arkode.cc
  source/sundials/sunlinsol_wrapper.cc
Labels: Reviewed and ready to merge, ready to test

#11718 Move some functions from internal::ReferenceCell::Base to ReferenceCell
  include/deal.II/fe/fe_tools.templates.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.templates.h
  include/deal.II/matrix_free/shape_info.templates.h
  source/base/data_out_base.cc
  source/dofs/dof_tools.cc
  source/fe/fe.cc
  source/fe/fe_data.cc
  source/fe/fe_values.cc
  source/fe/mapping_fe.cc
  source/fe/mapping_fe_field.cc
  source/grid/grid_in.cc
  source/simplex/fe_lib.cc
  tests/simplex/fe_lib_01.cc
  tests/simplex/reference_cell_kind_01.cc
  tests/simplex/unit_tangential_vectors_01.cc
Labels: ready to test

#11721 Test for p::d::Tria::load(forest).
  doc/news/changes/minor/20210209Munch
  include/deal.II/distributed/tria.h
  source/distributed/tria.cc
  tests/mpi/p4est_load_01.cc
  tests/mpi/p4est_load_01.with_p4est=true.mpirun=2.output
Labels: Reviewed and ready to merge, ready to test

#11730 Fix documentation in ArrayView.
  include/deal.II/base/array_view.h
Labels: Documentation, Reviewed and ready to merge

#11731 Fix GridIn::read_exodusii
  source/grid/grid_in.cc
Labels: Reviewed and ready to merge, ready to test

#11732 Reduce size of test (multigrid/transfer_matrix_free_06)
  tests/multigrid/transfer_matrix_free_06.cc
  tests/multigrid/transfer_matrix_free_06.with_mpi=true.with_p4est=true.with_trilinos=true.mpirun=15.output
  tests/multigrid/transfer_matrix_free_06.with_mpi=true.with_p4est=true.with_trilinos=true.mpirun=5.output
Labels: Reviewed and ready to merge, Tests, ready to test

#11735 Simplify two statements.
  include/deal.II/grid/tria_accessor.templates.h
Labels: ready to test

#11737 Add some missing header files for sundials_wrapper.h
  include/deal.II/sundials/sunlinsol_wrapper.h
Labels: Reviewed and ready to merge, ready to test

#11459 Use FEPointEvaluation in step-19
  examples/step-19/step-19.cc
Labels: Particles, Tutorials, ready to test

#11734 Move some more functions from internal::ReferenceCell::* classes to ReferenceCell
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.templates.h
  source/fe/fe.cc
  source/grid/tria_accessor.cc
Labels: ready to test

#11754 Fix ReferenceCell usage in read_exodusii_sidesets()
  source/grid/grid_in.cc
Labels: ready to test

#11750 Better document early deprecation.
  cmake/checks/check_01_cxx_features.cmake
  doc/news/changes/minor/20210105DanielArndt
  include/deal.II/base/config.h.in
Labels: Documentation, ready to test

#11755 Improve complexity of compute_set_union
  include/deal.II/base/mpi.templates.h
Labels: Parallel distributed, ready to test

#11756 TriangulationBase::reset_global_cell_indices(): collect indices manually
  source/distributed/tria_base.cc
Labels: Parallel distributed, Reviewed and ready to merge, ready to test

#11753 Add some more MPI datatypes.
  include/deal.II/base/mpi.templates.h
Labels: Miscellaneous, ready to test

#11487 consistently use local_size()
  doc/news/changes/major/20200211ArndtWells
  examples/step-37/step-37.cc
  examples/step-48/step-48.cc
  include/deal.II/base/mpi.h
  include/deal.II/base/mpi_compute_index_owner_internal.h
  include/deal.II/base/partitioner.h
  include/deal.II/base/partitioner.templates.h
  include/deal.II/lac/block_vector_base.h
  include/deal.II/lac/la_parallel_block_vector.templates.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/lac/petsc_block_vector.h
  include/deal.II/lac/petsc_vector.h
  include/deal.II/lac/petsc_vector_base.h
  include/deal.II/lac/precondition.h
  include/deal.II/lac/read_write_vector.h
  include/deal.II/lac/read_write_vector.templates.h
  include/deal.II/lac/trilinos_epetra_vector.h
  include/deal.II/lac/trilinos_precondition.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  include/deal.II/lac/trilinos_vector.h
  include/deal.II/lac/vector.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  include/deal.II/matrix_free/dof_info.templates.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/operators.h
  include/deal.II/matrix_free/vector_data_exchange.h
  include/deal.II/multigrid/mg_transfer.templates.h
  include/deal.II/multigrid/mg_transfer_matrix_free.h
  source/base/mpi.cc
  source/base/partitioner.cc
  source/dofs/dof_renumbering.cc
  source/lac/petsc_parallel_vector.cc
  source/lac/petsc_vector_base.cc
  source/lac/trilinos_epetra_vector.cc
  source/matrix_free/vector_data_exchange.cc
  source/multigrid/mg_transfer_matrix_free.cc
  source/non_matching/coupling.cc
  tests/mpi/local_size.cc
  tests/mpi/local_size.with_trilinos_with_tpetra=on.with_petsc=on.mpirun=4.output
Labels: Linear Algebra, Reviewed and ready to merge, ready to test

#11745 Test p global coarsening for locally refined meshes
  tests/multigrid-global-coarsening/multigrid_p_01.cc
  tests/multigrid-global-coarsening/multigrid_p_01.mpirun=1.with_trilinos=true.with_simplex_support=on.output
Labels: Multigrid, ready to test, simplices

#11758 Adjust minimum grain size of dictionary for consensus algorithm
  include/deal.II/base/mpi_compute_index_owner_internal.h
Labels: Parallel distributed, ready to test

#11761 Remove copy-and-past error in comment
  include/deal.II/lac/trilinos_precondition.h
Labels: Documentation

#11762 Fix matrix_free/face_setup_01
  tests/matrix_free/face_setup_01.cc
Labels: Reviewed and ready to merge, ready to test

#11751 Move LinearAlgebra::CommunicationBase -> Utilities::MPI::CommunicationBase.
  doc/news/changes/minor/20210215DavidWells
  include/deal.II/base/communication_pattern_base.h
  include/deal.II/base/mpi_noncontiguous_partitioner.h
  include/deal.II/base/mpi_noncontiguous_partitioner.templates.h
  include/deal.II/base/partitioner.h
  include/deal.II/lac/communication_pattern_base.h
  include/deal.II/lac/cuda_vector.h
  include/deal.II/lac/la_parallel_block_vector.h
  include/deal.II/lac/la_parallel_block_vector.templates.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/lac/la_vector.h
  include/deal.II/lac/la_vector.templates.h
  include/deal.II/lac/read_write_vector.h
  include/deal.II/lac/read_write_vector.templates.h
  include/deal.II/lac/trilinos_epetra_communication_pattern.h
  include/deal.II/lac/trilinos_epetra_vector.h
  include/deal.II/lac/trilinos_tpetra_communication_pattern.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  include/deal.II/lac/vector_space_vector.h
  source/lac/cuda_vector.cu
  source/lac/read_write_vector.cc
  source/lac/read_write_vector.cu
  source/lac/trilinos_epetra_vector.cc
Labels: Parallel distributed, ready to test

#11765 Add NoncontiguousPartitioner::temporary_storage_size()
  include/deal.II/base/mpi_noncontiguous_partitioner.h
  include/deal.II/base/mpi_noncontiguous_partitioner.templates.h
Labels: ready to test

#11763 Add some assertions to the noncontiguous partitioner.
  include/deal.II/base/mpi_noncontiguous_partitioner.templates.h
Labels: Enhancement, Reviewed and ready to merge, ready to test

#11760 indent-all: ensure only a single newline at end of files
  contrib/python-bindings/source/CMakeLists.txt
  contrib/python-bindings/tests/CMakeLists.txt
  contrib/utilities/indent
  contrib/utilities/indent-all
  contrib/utilities/indent_common.sh
  doc/doxygen/code-gallery/CMakeLists.txt
  doc/doxygen/headers/geometry_and_primitives.h
  doc/doxygen/headers/iterators.h
  doc/doxygen/headers/vector_valued.h
  doc/news/CMakeLists.txt
  examples/step-12b/doc/intro.dox
  examples/step-13/doc/intro.dox
  examples/step-13/doc/results.dox
  examples/step-14/doc/intro.dox
  examples/step-14/doc/results.dox
  examples/step-22/doc/results.dox
  examples/step-3/doc/intro.dox
  examples/step-35/doc/intro.dox
  examples/step-4/doc/results.dox
  examples/step-44/doc/intro.dox
  examples/step-46/doc/intro.dox
  examples/step-53/doc/intro.dox
  examples/step-54/doc/results.dox
  examples/step-56/doc/results.dox
  examples/step-59/doc/intro.dox
  examples/step-63/doc/results.dox
  examples/step-8/doc/results.dox
  include/CMakeLists.txt
  source/sundials/n_vector.cc
  tests/boost/extract_representative_set_01.cc
  tests/fe/fe_conformity_dim_2_fe_nedelec_sz.cc
  tests/fe/fe_conformity_dim_2_fe_rt_nodal.cc
  tests/fe/fe_conformity_fill_vector_random.h
  tests/fe/fe_conformity_test.h
  tests/grid/grid_in_out_vtu_01.cc
  tests/optimization/CMakeLists.txt
  tests/simplex/mapping_fe_fields_01.cc
  tests/symengine/sd_common_tests/utilities.h
Labels: Reviewed and ready to merge, ready to test

#11733 ::SolutionTransfer with p::s::Triangulation and artificial cells.
  source/numerics/solution_transfer.cc
  tests/mpi/solution_transfer_07.cc
  tests/mpi/solution_transfer_07.with_mpi=true.mpirun=2.output
  tests/mpi/solution_transfer_08.cc
  tests/mpi/solution_transfer_08.with_mpi=true.mpirun=2.output
  tests/mpi/solution_transfer_09.cc
  tests/mpi/solution_transfer_09.with_mpi=true.mpirun=2.output
  tests/mpi/solution_transfer_10.cc
  tests/mpi/solution_transfer_10.with_mpi=true.mpirun=2.output
Labels: ready to test

#11767 Update changelogs
  doc/news/changes/major/20210126DavidWells
  doc/news/changes/major/20210126DavidWells-2
  doc/news/changes/major/20210208DavidWells
  doc/news/changes/major/20210211ArndtWells
Labels: Miscellaneous

#11736 N_Vector: get_communicator return nullptr in serial
  include/deal.II/sundials/n_vector.templates.h
  tests/sundials/n_vector.cc
Labels: ready to test

#11772 Move particle ids into PropertyPool
  include/deal.II/particles/particle.h
  include/deal.II/particles/property_pool.h
  source/particles/particle.cc
  source/particles/property_pool.cc
  tests/particles/generators_06.cc
  tests/particles/generators_06.with_p4est=true.mpirun=1.output
  tests/particles/generators_06.with_p4est=true.mpirun=2.output
Labels: Reviewed and ready to merge, ready to test

#11770 Move the exodus conversion functions to RefereneCell.
  include/deal.II/grid/reference_cell.h
  source/grid/grid_in.cc
  source/grid/reference_cell.cc
Labels: ready to test

#11777 Better name for a variables.
  source/grid/grid_in.cc
Labels: ready to test

#11776 Also move combine_face_and_line_orientation() into ReferenceCell.
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.templates.h
Labels: ready to test

#11778 Rename variables.
  include/deal.II/matrix_free/shape_info.templates.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
Labels: ready to test

#11781 Sundials: Mark function as inline
  include/deal.II/sundials/sunlinsol_newempty.h
Labels: Bug, ready for review, ready to test

#11780 Add a version of CUDAWrappers::MatrixFree::reinit() that takes a predicate for cell_loop
  doc/news/changes/minor/20210219Turcksin
  include/deal.II/matrix_free/cuda_matrix_free.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  tests/cuda/matrix_free_matrix_vector_25.cu
  tests/cuda/matrix_free_matrix_vector_25.with_trilinos=true.with_mpi=true.with_p4est=true.mpirun=1.output
  tests/cuda/matrix_free_matrix_vector_25.with_trilinos=true.with_mpi=true.with_p4est=true.mpirun=2.output
Labels: GPU, Reviewed and ready to merge, ready to test

#11782 Remove a deprecated doxygen feature option.
  doc/doxygen/options.dox.in
Labels: Documentation

#11743 add ndarray typedef
  doc/news/changes/minor/202119Maier
  include/deal.II/base/ndarray.h
  tests/base/ndarray.cc
  tests/base/ndarray.output
Labels: ready for review, ready to test

#11783 Remove the internal::ReferenceCell::Base class and derived classes.
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_accessor.templates.h
  tests/simplex/orientation_02.cc
Labels: ready to test

#11787 Fix tags of NoncontiguousPartitioner
  include/deal.II/base/mpi_noncontiguous_partitioner.h
  include/deal.II/base/mpi_noncontiguous_partitioner.templates.h
  include/deal.II/base/mpi_tags.h
Labels: Bug, ready to test

#11714 Replace passing by const std::unique_ptr<T>& by const T&
  doc/news/changes/incompatibilities/20210222DanielArndt
  include/deal.II/base/mutable_bind.h
  include/deal.II/base/parameter_handler.h
  include/deal.II/base/patterns.h
  include/deal.II/numerics/vector_tools_common.h
  source/base/function_parser.cc
  source/base/tensor_function_parser.cc
Labels: ready to test

#11785 Fix fortran mangling
  cmake/checks/check_02_fortran_mangling.cmake
  cmake/configure/configure_1_lapack.cmake
  cmake/macros/macro_enable_language_optional.cmake
  contrib/utilities/generate_lapack_templates
  doc/news/changes/minor/20210220DavidWells
  include/deal.II/base/config.h.in
  include/deal.II/lac/lapack_templates.h
Labels: Build system, ready to test

#11788 Use the new ndarray class instead of nested std::array.
  examples/step-33/step-33.cc
  include/deal.II/base/geometry_info.h
  include/deal.II/base/polynomial_space.h
  include/deal.II/base/tensor_product_polynomials.h
  include/deal.II/fe/fe_p1nc.h
  include/deal.II/grid/connectivity.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/meshworker/copy_data.h
  source/base/geometry_info.cc
  source/base/tensor_product_polynomials.cc
  source/fe/fe_p1nc.cc
  source/grid/grid_generator.cc
  source/simplex/polynomials.cc
Labels: Reviewed and ready to merge, ready to test

#11799 Minor updates to the documentation of step-7.
  examples/step-7/doc/intro.dox
Labels: Reviewed and ready to merge, Tutorials, ready to test

#11796 make remove_trailing_whitespace() works in both MAC OS and Linux system
  contrib/utilities/indent_common.sh
Labels: Reviewed and ready to merge, ready to test

#11800 Remove double negation from exception message.
  include/deal.II/dofs/dof_handler.h
  source/dofs/dof_handler.cc
  source/dofs/dof_handler_policy.cc
  source/hp/refinement.cc
Labels: Reviewed and ready to merge, ready to test

#11797 Provide compile-time error messages if we don't handle a type.
  include/deal.II/base/hdf5.h
Labels: ready to test

#11793 Added hp::FECollection::get_hierarchy_sequence().
  doc/news/changes/minor/20210222Fehling
  include/deal.II/hp/fe_collection.h
  source/hp/fe_collection.cc
  tests/hp/fe_hierarchy_sequence.cc
  tests/hp/fe_hierarchy_sequence.output
Labels: Reviewed and ready to merge, ready to test

#11801 Attach DoFHandler::clear() to Triangulation::Signals::clear.
  source/dofs/dof_handler.cc
Labels: Reviewed and ready to merge, ready to test

#11807 Rename variables to make their names more standard.
  include/deal.II/fe/fe_base.h
  include/deal.II/fe/mapping.h
  include/deal.II/fe/mapping_cartesian.h
  include/deal.II/fe/mapping_fe.h
  include/deal.II/fe/mapping_fe_field.h
  include/deal.II/fe/mapping_q.h
  include/deal.II/fe/mapping_q_generic.h
  source/fe/fe_data.cc
  source/fe/mapping_cartesian.cc
  source/fe/mapping_fe.cc
  source/fe/mapping_fe_field.cc
  source/fe/mapping_q.cc
  source/fe/mapping_q_generic.cc
Labels: ready to test

#11806 examples/step-69: Fix mesh generation
  examples/step-69/step-69.cc
Labels: Bug, Tutorials, ready for review, ready to test

#11803 Introduce three new FEEvaluation functions
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, ready to test

#11808 Mark GeometryInfo as deprecated in favor of ReferenceCell.
  include/deal.II/base/geometry_info.h
  include/deal.II/grid/reference_cell.h
Labels: ready to test

#11741 New class TemporarilyRestoreSubdomainIds.
  include/deal.II/base/aligned_vector.h
  include/deal.II/distributed/shared_tria.h
  source/distributed/shared_tria.cc
  source/distributed/shared_tria.inst.in
  source/dofs/dof_handler.cc
  source/dofs/dof_handler_policy.cc
  source/numerics/solution_transfer.cc
Labels: ready to test

#11775 Rename the write/update particle functions.
  include/deal.II/particles/particle.h
  include/deal.II/particles/particle_accessor.h
  source/particles/particle.cc
  source/particles/particle_handler.cc
  tests/particles/particle_04.cc
  tests/particles/particle_06.cc
Labels: ready to test

#11813 Rename further simplex-related files
  include/deal.II/base/polynomials_pyramid.h
  include/deal.II/base/polynomials_wedge.h
  include/deal.II/base/quadrature_lib.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/matrix_free/util.h
  source/base/polynomials_pyramid.cc
  source/base/polynomials_wedge.cc
  source/base/quadrature_lib.cc
  source/fe/fe_pyramid_p.cc
  source/fe/fe_wedge_p.cc
  tests/simplex/q_witherden_vincent_01.cc
Labels: ready to test, simplices

#11805 Simplify code of create_geometric_coarsening_sequence()
  include/deal.II/multigrid/mg_transfer_global_coarsening.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  source/multigrid/mg_transfer_global_coarsening.inst.in
Labels: ready to test

#11802 Modularized MatrixFreeTools::compute_diagonal()
  include/deal.II/matrix_free/tools.h
Labels: ready to test

#11814 Fix DataAccessOnFaces::values for meshes containing non-hypercube cells
  include/deal.II/matrix_free/dof_info.templates.h
Labels: Matrix-free, ready to test, simplices

#11816 Make sure we live what we preach.
  doc/doxygen/references.bib
  examples/step-15/doc/results.dox
Labels: Documentation, Reviewed and ready to merge, ready to test

#11759 Introduce Utilities::MPI::all_reduce()
  include/deal.II/base/mpi.h
  include/deal.II/base/mpi.templates.h
  source/base/mpi.inst.in
  tests/mpi/allreduce_01.cc
  tests/mpi/allreduce_01.mpirun=1.output
  tests/mpi/allreduce_01.mpirun=5.output
Labels: Parallel, Parallel distributed, ready to test
