Repository dealii/dealii, pull requests merged in 2021-01, with the labels that each got.

#11445 Minor change to CellWeights exception handling.
  source/distributed/cell_weights.cc
  tests/mpi/hp_cell_weights_01.cc
  tests/mpi/hp_cell_weights_01.with_p4est=true.mpirun=2.output
  tests/mpi/hp_cell_weights_02.cc
  tests/mpi/hp_cell_weights_02.with_p4est=true.mpirun=3.output
  tests/mpi/hp_cell_weights_03.cc
  tests/mpi/hp_cell_weights_03.with_mpi=true.with_metis=true.mpirun=2.output
  tests/mpi/hp_cell_weights_03.with_mpi=true.with_metis=true.mpirun=2.output.1
  tests/mpi/hp_cell_weights_04.cc
  tests/mpi/hp_cell_weights_04.with_mpi=true.with_metis=true.mpirun=2.output
  tests/mpi/hp_cell_weights_04.with_mpi=true.with_metis=true.mpirun=2.output.1
Labels: Reviewed and ready to merge, ready to test

#11455 Step-12: select quadrature at a central place
  examples/step-12/step-12.cc
Labels: ready to test

#11453 Remove MF::AD::use_vector_data_exchanger_full
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
Labels: ready to test

#11415 Ignore deprecated-volatile warning when disabling exta diagnostic
  include/deal.II/base/config.h.in
Labels: Miscellaneous, ready to test

#10932 Step 74: Symmetric interior penalty Galerkin (SIPG) method for Poisson's equation
  doc/doxygen/references.bib
  examples/step-74/CMakeLists.txt
  examples/step-74/doc/builds-on
  examples/step-74/doc/intro.dox
  examples/step-74/doc/kind
  examples/step-74/doc/results.dox
  examples/step-74/doc/tooltip
  examples/step-74/step-74.cc
Labels: ready to test

#11469 add step-74 to tutorial page
  doc/doxygen/tutorial/tutorial.h.in
Labels: Tutorials

#11454 Generalize GridGenerator::flatten_triangulation for simplex meshes
  source/grid/grid_generator.cc
Labels: ready to test

#11467 Follow-ups to step 74
  examples/step-47/doc/results.dox
  examples/step-74/doc/intro.dox
  examples/step-74/doc/results.dox
  examples/step-74/step-74.cc
  include/deal.II/base/convergence_table.h
Labels: Tutorials, ready to test

#11470 GSL no longer requirement for FESeries::Legendre in tests.
  tests/fe/fe_series_02.output
  tests/fe/fe_series_04.output
  tests/fe/fe_series_05.output
  tests/hp/laplace_mitchell2014_04_peak.with_trilinos=true.with_lapack=true.output
  tests/numerics/smoothness_estimator_01.output
  tests/serialization/fe_series_02.output
  tests/serialization/fe_series_02.output.libc++
Labels: Reviewed and ready to merge, ready to test

#11460 step-26: Reset time and timestep_number during pre refinement steps
  doc/news/changes/minor/20210105CPraveen
  examples/step-26/step-26.cc
Labels: Reviewed and ready to merge, ready to test

#11473 Minor adjustments
  include/deal.II/particles/utilities.h
  source/particles/generators.cc
Labels: Reviewed and ready to merge, ready to test

#11456 Add a version of update_neighbors() for simplex meshes
  source/grid/tria.cc
  tests/simplex/refinement_02.cc
  tests/simplex/refinement_02.with_simplex_support=on.output
Labels: ready to test

#11471 Adjusted settings for default FESeries object.
  include/deal.II/numerics/smoothness_estimator.h
  source/numerics/smoothness_estimator.cc
  tests/numerics/smoothness_estimator_02.cc
  tests/numerics/smoothness_estimator_02.output
Labels: Reviewed and ready to merge, ready to test

#11476 Avoid using bare 'new'.
  source/grid/tria.cc
Labels: Reviewed and ready to merge, ready to test

#11449 Convert step-2 to a simplex test
  tests/simplex/step-02.cc
  tests/simplex/step-02.with_simplex_support=on.output
Labels: ready to test

#11446 Update grid/cell_id_08 output.
  tests/grid/cell_id_08.cc
  tests/grid/cell_id_08.output
Labels: ready to test

#11388 Allow read access to data in Interpolated*Function
  include/deal.II/base/function_lib.h
  source/base/function_lib.cc
Labels: ready to test

#11474 Clarify a number of comments around FE_Q_Bubbles.
  include/deal.II/base/tensor_product_polynomials_bubbles.h
  include/deal.II/fe/fe_q_bubbles.h
  source/base/tensor_product_polynomials_bubbles.cc
  source/fe/fe_q_bubbles.cc
Labels: Reviewed and ready to merge, ready to test

#11458 Convert step-74 to a simplex test
  tests/simplex/step-74.cc
  tests/simplex/step-74.with_simplex_support=on.output
Labels: Reviewed and ready to merge, ready to test

#11477 step-74 fix: energy norm description
  examples/step-74/step-74.cc
Labels: Reviewed and ready to merge, ready to test

#11392 Better document serialization functions.
  include/deal.II/base/aligned_vector.h
  include/deal.II/base/bounding_box.h
  include/deal.II/base/data_out_base.h
  include/deal.II/base/geometry_info.h
  include/deal.II/base/index_set.h
  include/deal.II/base/parameter_handler.h
  include/deal.II/base/point.h
  include/deal.II/base/polynomial.h
  include/deal.II/base/polynomials_piecewise.h
  include/deal.II/base/quadrature.h
  include/deal.II/base/subscriptor.h
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/base/table.h
  include/deal.II/base/table_handler.h
  include/deal.II/base/table_indices.h
  include/deal.II/base/tensor.h
  include/deal.II/base/utilities.h
  include/deal.II/differentiation/sd/symengine_number_types.h
  include/deal.II/differentiation/sd/symengine_number_visitor_internal.h
  include/deal.II/differentiation/sd/symengine_optimizer.h
  include/deal.II/dofs/block_info.h
  include/deal.II/dofs/dof_faces.h
  include/deal.II/dofs/dof_handler.h
  include/deal.II/dofs/dof_levels.h
  include/deal.II/dofs/dof_objects.h
  include/deal.II/dofs/number_cache.h
  include/deal.II/grid/cell_id.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/tria.h
  include/deal.II/grid/tria_description.h
  include/deal.II/grid/tria_faces.h
  include/deal.II/grid/tria_levels.h
  include/deal.II/grid/tria_objects.h
  include/deal.II/lac/affine_constraints.h
  include/deal.II/lac/la_vector.h
  include/deal.II/lac/sparsity_pattern.h
  include/deal.II/lac/vector.h
  include/deal.II/particles/particle.h
  include/deal.II/particles/particle_accessor.h
  include/deal.II/particles/particle_handler.h
Labels: Documentation, ready to test

#11422 Work on compute_embedding_matrices() for simplex
  include/deal.II/fe/fe_tools.templates.h
  include/deal.II/simplex/fe_lib.h
  source/simplex/fe_lib.cc
  tests/simplex/compute_projection_matrices_01.cc
  tests/simplex/compute_projection_matrices_01.with_simplex_support=on.output
Labels: Geometric multigrid, ready to test

#11418 step-27: Updated to new interface.
  doc/doxygen/references.bib
  doc/news/changes/minor/20201224Fehling
  examples/step-27/doc/intro.dox
  examples/step-27/doc/results.dox
  examples/step-27/step-27.cc
  include/deal.II/grid/grid_generator.h
Labels: Reviewed and ready to merge, ready to test

#11378 Link in the correct figure.
  doc/doxygen/images/convert_hypercube_to_simplex_mesh_visualization_octant.png
  include/deal.II/grid/grid_generator.h
Labels: ready to test

#11468 Better explain the purpose of the L-singularity function.
  include/deal.II/base/function_lib.h
Labels: Reviewed and ready to merge, ready to test

#11491 Clean up some in function_lib.cc.
  source/base/function_lib.cc
Labels: Reviewed and ready to merge, ready to test

#11486 Fix bug in DoFHandler::distribute_dofs
  source/dofs/dof_handler.cc
  tests/dofs/distribute_dofs_01.cc
  tests/dofs/distribute_dofs_01.debug.output
Labels: ready to test

#11492 Make one variable 'const'.
  include/deal.II/fe/fe_point_evaluation.h
Labels: Reviewed and ready to merge, ready to test

#11475 Clarify what the picture shows in step-74.
  examples/step-74/doc/results.dox
Labels: Tutorials

#11494 Fix BoundingBox's Container ctor.
  include/deal.II/base/bounding_box.h
  include/deal.II/grid/tria_accessor.h
  tests/base/bounding_box_1.cc
  tests/base/bounding_box_1.output
Labels: Bug, ready to test

#11495 Fix the VTK output in the exodusii test.
  tests/grid/grid_in_exodusii.with_trilinos_with_seacas=on.output
Labels: Reviewed and ready to merge, Tests, ready to test

#11493 Replace deprecated CellId::to_cell().
  include/deal.II/grid/grid_tools.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  source/grid/grid_tools.cc
  source/particles/particle_handler.cc
Labels: ready to test

#11341 Rework breakdown condition in BiCGSTAB
  include/deal.II/lac/solver_bicgstab.h
Labels: ready to test

#11479 Adjusted settings for default FESeries::Legendre object.
  include/deal.II/numerics/smoothness_estimator.h
  source/numerics/smoothness_estimator.cc
Labels: ready to test

#11498 Fix typo
  source/grid/tria.cc
Labels: Documentation

#11499 improve DynamicSparsityPattern usage documentation
  include/deal.II/lac/dynamic_sparsity_pattern.h
Labels: Documentation, ready to test

#11501 Enabling mixed meshes in GridIn::read_vkt() and read_msh()
  source/grid/grid_in.cc
  source/grid/tria.cc
Labels: ready to test

#11502 Assert type of coarse grid in p:d:T
  source/distributed/tria.cc
Labels: Reviewed and ready to merge, ready to test

#11500 Add some comments to VectorTools::interpolate_boundary_values().
  doc/doxygen/references.bib
  include/deal.II/numerics/vector_tools_boundary.h
Labels: ready to test

#11509 Add an assert to ReferenceCell::compute_orientation()
  include/deal.II/grid/reference_cell.h
Labels: ready to test

#11506 ParameterAcceptor::enter/leave_subsection()
  doc/news/changes/minor/20210112LucaHeltai
  examples/step-70/step-70.cc
  include/deal.II/base/parameter_acceptor.h
  source/base/parameter_acceptor.cc
  tests/parameter_handler/parameter_acceptor_10.cc
  tests/parameter_handler/parameter_acceptor_10.output
Labels: Reviewed and ready to merge, ready for review, ready to test

#11482 Tutorial step-03 with simplex support.
  tests/simplex/step-03.cc
  tests/simplex/step-03.with_simplex_support=on.output
Labels: ready to test

#11516 Add a utility function for Simplex::FE_P's support points.
  source/simplex/fe_lib.cc
Labels: Finite Element, Reviewed and ready to merge, ready to test

#11518 Mark a test as requiring UMFPACK.
  tests/simplex/step-74.with_umfpack=on.with_simplex_support=on.output
Labels: Miscellaneous, Reviewed and ready to merge, Tests

#11517 Convert step-7 to a simplex test
  tests/simplex/step-07.cc
  tests/simplex/step-07.with_simplex_support=on.output
Labels: Reviewed and ready to merge, ready to test

#11523 Fix indentation mishap.
  include/deal.II/fe/fe_tools.templates.h
Labels: ready to test

#11522 Fix missing 'spacedim' template argument.
  include/deal.II/numerics/vector_tools_point_value.templates.h
Labels: ready to test

#11524 Simply a few return statements a bit.
  include/deal.II/base/geometry_info.h
  source/fe/mapping_fe.cc
  source/fe/mapping_fe_field.cc
  source/fe/mapping_manifold.cc
  source/fe/mapping_q_generic.cc
  source/grid/manifold.cc
  source/grid/manifold_lib.cc
  source/grid/tria_accessor.cc
  source/opencascade/utilities.cc
Labels: Reviewed and ready to merge, ready to test

#11510 Fix orientation of triangular faces
  include/deal.II/grid/connectivity.h
  include/deal.II/grid/reference_cell.h
  tests/simplex/orientation_01.cc
  tests/simplex/orientation_01.with_simplex_support=on.output
  tests/simplex/orientation_02.cc
  tests/simplex/orientation_02.with_simplex_support=on.output
  tests/simplex/q_projection_01.output
Labels: Bug, ready to test

#11530 Implement Simplex::FE_P::compute_2nd_derivative()
  include/deal.II/simplex/polynomials.h
  source/simplex/polynomials.cc
  tests/simplex/fe_lib_02.cc
  tests/simplex/fe_lib_02.output
  tests/simplex/step-74.with_umfpack=on.with_simplex_support=on.output
Labels: Reviewed and ready to merge, ready to test

#11513 Improve error message when accessing vector elements in parallel.
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/petsc_vector_base.h
  include/deal.II/lac/trilinos_vector.h
Labels: Documentation, ready to test

#11472 Introduce DEAL_II_DEPRECATED_EARLY
  .github/workflows/linux.yml
  .github/workflows/osx.yml
  Jenkinsfile
  cmake/checks/check_01_cxx_features.cmake
  cmake/setup_cached_variables.cmake
  contrib/ci/Jenkinsfile.osx
  doc/doxygen/options.dox.in
  include/deal.II/base/config.h.in
Labels: ready to test

#11520 Introduce ReferenceCell::get_default_linear_mapping() with triangulation argument. Use it.
  include/deal.II/fe/mapping_q1.h
  include/deal.II/grid/reference_cell.h
  source/fe/fe_q_bubbles.cc
  source/fe/fe_values.cc
  source/fe/mapping_fe_field.cc
  source/grid/grid_tools_dof_handlers.cc
  source/grid/reference_cell.cc
  source/grid/reference_cell.inst.in
  source/grid/tria.cc
  source/grid/tria_accessor.cc
  source/meshworker/scratch_data.cc
  source/numerics/derivative_approximation.cc
Labels: ready to test

#11519 Particles fully distributed/shared triangulation
  source/particles/particle_handler.cc
  tests/particles/particle_handler_fully_distributed_01.cc
  tests/particles/particle_handler_fully_distributed_01.mpirun=2.output
  tests/particles/particle_handler_shared_01.cc
  tests/particles/particle_handler_shared_01.mpirun=2.output
Labels: Particles, ready to test

#11532 Convert step-8 to a simplex test
  tests/simplex/step-08.cc
  tests/simplex/step-08.with_simplex_support=on.output
Labels: ready to test

#11504 Move and rename tensor basis transformations and add documentation
  doc/news/changes/minor/20210112Much
  include/deal.II/physics/transformations.h
Labels: Physics, Tensors, ready to test

#11528 simplex: vertex_dof_identities for FE_P
  source/fe/fe_q_base.cc
  source/simplex/fe_lib.cc
Labels: Reviewed and ready to merge, ready to test

#11534 add step-55 as a simplex test
  tests/simplex/step-55.cc
  tests/simplex/step-55.mpirun=2.with_petsc=true.with_simplex_support=on.output
Labels: Reviewed and ready to merge, ready to test

#11537 Remove some unnecessary #include files.
  source/fe/mapping_q1.cc
  source/fe/mapping_q_generic.cc
Labels: Reviewed and ready to merge, ready to test

#11538 Use default constructed linear mapping.
  include/deal.II/base/parsed_convergence_table.h
  include/deal.II/fe/fe_tools.templates.h
  include/deal.II/numerics/error_estimator.templates.h
  include/deal.II/numerics/matrix_creator.templates.h
  include/deal.II/numerics/vector_tools_boundary.templates.h
  include/deal.II/numerics/vector_tools_interpolate.templates.h
  include/deal.II/numerics/vector_tools_mean_value.templates.h
  include/deal.II/numerics/vector_tools_point_gradient.templates.h
  include/deal.II/numerics/vector_tools_point_value.templates.h
  include/deal.II/numerics/vector_tools_project.templates.h
  include/deal.II/numerics/vector_tools_rhs.templates.h
Labels: Reviewed and ready to merge, ready to test

#11541 Use the correct mapping for a finite element.
  source/fe/fe_values.cc
  source/meshworker/scratch_data.cc
Labels: Reviewed and ready to merge, ready to test

#11531 cell bounding box tests for Simplex grids in 2d and 3d
  tests/simplex/cell_bounding_boxes_2d.cc
  tests/simplex/cell_bounding_boxes_2d.with_simplex_support=on.output
  tests/simplex/cell_bounding_boxes_3d.cc
  tests/simplex/cell_bounding_boxes_3d.with_simplex_support=on.output
Labels: Reviewed and ready to merge, ready to test

#11542 Use the correct type for a variable.
  source/grid/grid_generator.cc
Labels: Reviewed and ready to merge, ready to test

#11527 simplex: compare_for_domination
  source/fe/fe_dgq.cc
  source/fe/fe_q.cc
  source/simplex/fe_lib.cc
Labels: ready to test

#11443 Store particle locations in the PropertyPool
  include/deal.II/particles/particle.h
  include/deal.II/particles/property_pool.h
  source/particles/particle.cc
  source/particles/property_pool.cc
Labels: Particles, Reviewed and ready to merge, ready to test

#11545 Convert step-20 to a simplex test
  tests/simplex/step-20.cc
  tests/simplex/step-20.with_simplex_support=on.output
Labels: ready to test

#11544 Convert ReferenceCell::Type to a class.
  include/deal.II/grid/reference_cell.h
  source/distributed/tria_base.cc
  tests/serialization/triangulation_01.output
  tests/serialization/triangulation_02.output
Labels: ready to test

#11514 MappingFE::transform_real_to_unit_cell()
  doc/news/changes/minor/20210113LucaHeltai
  include/deal.II/fe/mapping_fe.h
  include/deal.II/fe/mapping_q_internal.h
  source/fe/mapping_fe.cc
  tests/simplex/mapping_transformations_01.cc
  tests/simplex/mapping_transformations_01.with_simplex_support=on.output
Labels: ready for review, ready to test, simplices

#11543 Make code slightly easier to read.
  source/simplex/fe_lib.cc
Labels: Reviewed and ready to merge, ready to test

#11547 simplex: line_dof_identities for FE_P
  source/fe/fe_q_base.cc
  source/simplex/fe_lib.cc
Labels: Reviewed and ready to merge, ready to test

#11389 GridGenerator::convert_hypercube_to_simplex_mesh(): manifold_id
  source/grid/grid_generator.cc
  tests/simplex/conv_hex_to_simplex.cc
  tests/simplex/conv_hex_to_simplex.with_simplex_support=on.output
Labels: Reviewed and ready to merge, ready to test

#11555 Implement ReferenceCell::unit_normal_vectors()
  include/deal.II/grid/reference_cell.h
  tests/simplex/unit_tangential_vectors_01.cc
  tests/simplex/unit_tangential_vectors_01.output
Labels: Reviewed and ready to merge, ready to test

#11550 Add assert to p:f:T::create_triangulation()
  source/distributed/fully_distributed_tria.cc
Labels: Reviewed and ready to merge, ready to test

#11557 Fix DoFTools::extract_boundary_dof() for simplex meshes
  source/dofs/dof_tools.cc
  tests/simplex/extract_boundary_dofs.cc
  tests/simplex/extract_boundary_dofs.mpirun=1.with_simplex_support=on.output
  tests/simplex/extract_boundary_dofs.mpirun=5.with_simplex_support=on.output
Labels: Reviewed and ready to merge, ready to test

#11554 Consistent nonlocal access error messages
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/petsc_vector_base.h
  include/deal.II/lac/trilinos_sparse_matrix.h
  include/deal.II/lac/trilinos_sparsity_pattern.h
  include/deal.II/lac/trilinos_vector.h
  source/lac/trilinos_sparse_matrix.cc
Labels: Reviewed and ready to merge, ready to test

#11559 improve Simplex:QGauss error message
  source/simplex/quadrature_lib.cc
Labels: Reviewed and ready to merge, ready to test

#11526 Simplify code flow. Add a bit of documentation.
  source/dofs/dof_tools_constraints.cc
Labels: ready to test

#11548 simplex: hanging node tests
  tests/simplex/hanging_nodes_01.cc
  tests/simplex/hanging_nodes_01.with_simplex_support=on.output
  tests/simplex/hanging_nodes_02.cc
  tests/simplex/hanging_nodes_02.with_simplex_support=on.output
Labels: Reviewed and ready to merge, ready to test

#11560 minor doc change for Simplex::FE_P
  include/deal.II/simplex/fe_lib.h
Labels: Reviewed and ready to merge

#11525 Unit test for GridTools::compute_point_locations in simplex meshes
  tests/simplex/compute_point_locations_01.cc
  tests/simplex/compute_point_locations_01.output
Labels: ready to test

#11562 Add Step-04.cc converted to Simplex
  tests/simplex/step-04.cc
  tests/simplex/step-04.with_simplex_support=on.output
Labels: Reviewed and ready to merge, ready to test

#11484 Tutorial step-01 with simplices support.
  tests/simplex/step-01.cc
  tests/simplex/step-01.with_simplex_support=on.output
Labels: ready to test

#11568 Change the loop of the bounding lines in set_all_manifold_ids
  include/deal.II/grid/tria_accessor.templates.h
Labels: Reviewed and ready to merge, ready to test

#11565 Work on MappingFEField for simplex meshes
  include/deal.II/fe/mapping_fe_field.h
  include/deal.II/grid/reference_cell.h
  source/fe/mapping_fe_field.cc
  source/grid/reference_cell.cc
  source/grid/reference_cell.inst.in
  tests/simplex/mapping_fe_fields_01.cc
  tests/simplex/mapping_fe_fields_01.with_simplex_support=on.output
Labels: Reviewed and ready to merge, ready to test

#11569 A simplex test for step-38
  tests/simplex/step-38.cc
  tests/simplex/step-38.with_simplex_support=on.output
Labels: ready to test

#11573 Rename test output
  tests/simplex/compute_point_locations_01.with_simplex_support=on.output
Labels: ready to test

#11570 Return the box of support points instead of only the vertices.
  doc/news/changes/minor/20210116LucaHeltai
  include/deal.II/fe/mapping.h
  include/deal.II/fe/mapping_fe.h
  include/deal.II/fe/mapping_q.h
  include/deal.II/fe/mapping_q_eulerian.h
  include/deal.II/fe/mapping_q_generic.h
  source/fe/mapping_fe.cc
  source/fe/mapping_q.cc
  source/fe/mapping_q_eulerian.cc
  source/fe/mapping_q_generic.cc
  tests/mappings/mapping_get_bounding_box_01.cc
  tests/mappings/mapping_get_bounding_box_01.output
Labels: ready to test

#11567 Fix: single test output dir per test
  cmake/macros/macro_deal_ii_add_test.cmake
Labels: Build system, ready to test

#11574 Add warning to convert_hypercube_to_simplex_mesh
  include/deal.II/grid/grid_generator.h
Labels: Documentation

#11576 Implement ReferenceCell::vertex_faces()
  include/deal.II/grid/reference_cell.h
  source/grid/grid_tools.cc
  source/grid/grid_tools_dof_handlers.cc
  tests/simplex/reference_cell_kind_01.cc
  tests/simplex/reference_cell_kind_01.output
Labels: Reviewed and ready to merge, ready to test

#11571 Add new test for MappingFEField for simplex meshes
  tests/simplex/mapping_fe_fields_02.cc
  tests/simplex/mapping_fe_fields_02.with_simplex_support=on.output
Labels: Mapping, ready to test

#11563 Work on higher-order MappingFE
  include/deal.II/fe/mapping_fe.h
  include/deal.II/grid/reference_cell.h
  source/fe/mapping_fe.cc
  source/grid/reference_cell.cc
  tests/simplex/mapping_fe_01.cc
  tests/simplex/mapping_fe_01.with_simplex_support=on.output
Labels: ready to test

#11572 Generalize VectorTools::get_position_vector for simplex meshes
  include/deal.II/grid/reference_cell.h
  include/deal.II/numerics/vector_tools_interpolate.templates.h
  source/grid/reference_cell.cc
  source/grid/reference_cell.inst.in
  tests/simplex/mapping_fe_fields_01.cc
Labels: ready to test

#11539 Use linear Q1 mapping even in places where we know that that may be wrong
  include/deal.II/fe/fe_interface_values.h
  include/deal.II/fe/fe_tools.templates.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/grid_tools_cache.h
  include/deal.II/numerics/vector_tools_constraints.h
  include/deal.II/particles/generators.h
Labels: ready to test

#11586 Use VTK nomenclature.
  source/base/data_out_base.cc
Labels: ready to test

#11579 Use both quadratic element and quadrature mapping in simplex/step-38
  tests/simplex/step-38.cc
  tests/simplex/step-38.with_simplex_support=on.output
Labels: ready to test

#11558 Convert step-23 to a simplex test
  tests/simplex/step-23.cc
  tests/simplex/step-23.with_simplex_support=on.output
Labels: ready to test

#11575 Step 68 simplex
  source/particles/particle_handler.cc
  tests/simplex/step-68.cc
  tests/simplex/step-68.mpirun=1.with_simplex_support=on.output
  tests/simplex/step-68.mpirun=4.with_simplex_support=on.output
Labels: Reviewed and ready to merge, ready to test

#11580 Provide abstract interface to p::d::Triangulation::load()/save()
  doc/news/changes/minor/20210118PasqualeAfrica
  include/deal.II/distributed/fully_distributed_tria.h
  include/deal.II/distributed/tria.h
  include/deal.II/distributed/tria_base.h
  source/distributed/fully_distributed_tria.cc
  source/distributed/tria.cc
  source/distributed/tria_base.cc
Labels: Reviewed and ready to merge, ready to test

#11556 Move two free functions into class ReferenceCell.
  include/deal.II/grid/connectivity.h
  include/deal.II/grid/reference_cell.h
  source/base/qprojector.cc
  source/fe/fe_nothing.cc
  source/fe/mapping_fe.cc
  source/fe/mapping_fe_field.cc
  source/grid/manifold.cc
  source/grid/reference_cell.cc
  tests/simplex/orientation_01.cc
  tests/simplex/orientation_02.cc
  tests/simplex/unit_tangential_vectors_01.cc
Labels: ready to test

#11553 Generalize communicate_locally_moved_vertices()
  doc/news/changes/minor/20210115Munch
  include/deal.II/base/template_constraints.h
  include/deal.II/distributed/tria.h
  include/deal.II/distributed/tria_base.h
  include/deal.II/grid/grid_tools.h
  source/distributed/tria.cc
  source/distributed/tria_base.cc
  source/grid/grid_tools.cc
Labels: Parallel distributed, Triangulation, ready to test

#11593 Compile subdivided_hyper_rectangle_with_simplices ...
  include/deal.II/simplex/grid_generator.h
  source/simplex/grid_generator.cc
  source/simplex/grid_generator.inst.in
Labels: ready to test

#11546 Barycentric polynomials
  include/deal.II/simplex/barycentric_polynomials.h
  include/deal.II/simplex/polynomials.h
  source/base/qprojector.cc
  source/simplex/CMakeLists.txt
  source/simplex/barycentric_polynomials.cc
  source/simplex/fe_lib.cc
  source/simplex/polynomials.cc
  tests/simplex/barycentric_01.cc
  tests/simplex/barycentric_01.output
  tests/simplex/polynomials_01.cc
Labels: Finite Element, ready to test

#11595 Make the special ReferenceCell objects objects, not enums.
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.templates.h
  include/deal.II/numerics/data_out_dof_data.templates.h
  source/base/qprojector.cc
  source/distributed/tria_base.cc
  source/grid/grid_out.cc
  source/grid/reference_cell.cc
  source/grid/tria.cc
Labels: ready to test

#11597 Remove now unnecessary things in ReferenceCell::Type. Make some things constexpr.
  include/deal.II/grid/reference_cell.h
Labels: ready to test

#11598 add ReferenceCell::Type::is_hyper_cube
  include/deal.II/grid/reference_cell.h
Labels: Reviewed and ready to merge, ready to test, simplices

#11603 Hide the ability to create ReferenceCell objects from users.
  include/deal.II/grid/reference_cell.h
  source/distributed/tria_base.cc
  source/grid/reference_cell.cc
Labels: ready to test

#11602 Turn get_hypercube/simple() into templates. Move them into ReferenceCell::Type
  include/deal.II/base/qprojector.h
  include/deal.II/fe/fe_poly_face.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/grid_tools_cache.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/matrix_free/mapping_info.templates.h
  include/deal.II/matrix_free/matrix_free.templates.h
  include/deal.II/matrix_free/shape_info.templates.h
  include/deal.II/numerics/vector_tools_constraints.h
  include/deal.II/numerics/vector_tools_project.templates.h
  include/deal.II/particles/generators.h
  source/base/data_out_base.cc
  source/base/qprojector.cc
  source/fe/fe_nedelec.cc
  source/fe/fe_nothing.cc
  source/fe/fe_q_base.cc
  source/fe/mapping_cartesian.cc
  source/fe/mapping_fe_field.cc
  source/fe/mapping_manifold.cc
  source/fe/mapping_q_generic.cc
  source/grid/manifold.cc
  source/grid/reference_cell.cc
  source/grid/tria.cc
  source/multigrid/mg_tools.cc
  source/numerics/data_out.cc
  tests/simplex/cell_measure_01.cc
Labels: ready to test

#11582 Python wrappers for simplex and mixed meshes
  contrib/python-bindings/include/cell_accessor_wrapper.h
  contrib/python-bindings/include/reference_cell_wrapper.h
  contrib/python-bindings/include/tria_accessor_wrapper.h
  contrib/python-bindings/include/triangulation_wrapper.h
  contrib/python-bindings/source/CMakeLists.txt
  contrib/python-bindings/source/cell_accessor_wrapper.cc
  contrib/python-bindings/source/export_cell_accessor.cc
  contrib/python-bindings/source/export_reference_cell.cc
  contrib/python-bindings/source/export_triangulation.cc
  contrib/python-bindings/source/reference_cell_wrapper.cc
  contrib/python-bindings/source/tria_accessor_wrapper.cc
  contrib/python-bindings/source/triangulation_wrapper.cc
  contrib/python-bindings/source/wrappers.cc
  contrib/python-bindings/tests/triangulation_wrapper.py
  doc/news/changes/minor/20210118AlexanderGrayver
Labels: Python, Reviewed and ready to merge, Triangulation, ready to test

#11601 Let ReferenceCell::get_nodal_type_quadrature() return a 'const' reference
  include/deal.II/grid/reference_cell.h
  source/grid/reference_cell.cc
  source/grid/reference_cell.inst.in
Labels: ready to test

#11395 Introduce SUNDIALS N_Vector module
  include/deal.II/sundials/n_vector.h
  include/deal.II/sundials/n_vector.templates.h
  source/sundials/CMakeLists.txt
  source/sundials/n_vector.cc
  source/sundials/n_vector.inst.in
  tests/sundials/n_vector.cc
  tests/sundials/n_vector.with_sundials.geq.5.0.0.output
  tests/sundials/n_vector.with_sundials.geq.5.0.0.with_mpi=true.with_trilinos=true.mpirun=2.output
Labels: Reviewed and ready to merge, ready to test

#11605 Fix comparisons in ReferenceCell
  include/deal.II/grid/reference_cell.h
Labels: Reviewed and ready to merge, ready to test

#11596 Fix ThreadLocalStorage assigment operators
  include/deal.II/base/thread_local_storage.h
  tests/multithreading/thread_local_storage_07.cc
  tests/multithreading/thread_local_storage_07.output
  tests/multithreading/thread_local_storage_08.cc
  tests/multithreading/thread_local_storage_08.output
Labels: ready to test

#11611 Improve an error message.
  source/grid/grid_out.cc
Labels: ready to test

#11613 Fix a variety of small simplex things.
  include/deal.II/simplex/fe_lib.h
  source/grid/reference_cell.cc
  source/grid/tria_accessor.cc
  source/simplex/quadrature_lib.cc
  tests/simplex/q_projection_01.output
  tests/simplex/quadrature_lib_01.output
Labels: Reviewed and ready to merge, ready to test, simplices

#11607 Move a function that is not performance-critical to the .cc file.
  include/deal.II/grid/reference_cell.h
  source/grid/reference_cell.cc
Labels: ready to test

#11610 Replace gsl_sf_legendre_Pl with std_cxx17::legendre in tests.
  tests/fe/fe_series_02.cc
  tests/fe/fe_series_04.cc
  tests/fe/fe_series_05.cc
  tests/numerics/smoothness_estimator_01.cc
Labels: ready to test

#11629 Enable PYTHON_BINDINGS in linux-release-serial
  .github/workflows/linux.yml
Labels: Reviewed and ready to merge

#11617 Simplify some code.
  source/grid/reference_cell.cc
Labels: ready to test

#11630 Update interface of FEPointEvaluation
  include/deal.II/fe/fe_point_evaluation.h
  tests/fe/point_evaluation_01.cc
  tests/fe/point_evaluation_02.cc
  tests/fe/point_evaluation_03.cc
  tests/fe/point_evaluation_04.cc
  tests/fe/point_evaluation_05.cc
  tests/fe/point_evaluation_06.cc
  tests/fe/point_evaluation_07.cc
  tests/fe/point_evaluation_08.cc
  tests/fe/point_evaluation_09.cc
Labels: Finite Element, Reviewed and ready to merge, ready to test

#11635 Add missing include file for SUNDIALS
  include/deal.II/sundials/n_vector.h
Labels: Reviewed and ready to merge, ready to test

#11634 fix array bounds warning
  source/fe/mapping_fe_field.cc
Labels: Reviewed and ready to merge, ready to test

#11639 Fix FEPointEvaluation if only grad is requested
  include/deal.II/fe/fe_point_evaluation.h
Labels: Finite Element, Reviewed and ready to merge, ready to test

#11623 Work on FEPointEvaluation::integrate
  include/deal.II/fe/fe_point_evaluation.h
  include/deal.II/matrix_free/tensor_product_kernels.h
  tests/fe/point_evaluation_01.cc
  tests/fe/point_evaluation_01.output
  tests/fe/point_evaluation_02.cc
  tests/fe/point_evaluation_02.output
  tests/fe/point_evaluation_03.cc
  tests/fe/point_evaluation_03.output
  tests/fe/point_evaluation_04.cc
  tests/fe/point_evaluation_04.output
  tests/fe/point_evaluation_05.cc
  tests/fe/point_evaluation_05.output
  tests/fe/point_evaluation_06.cc
  tests/fe/point_evaluation_06.output
  tests/fe/point_evaluation_07.cc
  tests/fe/point_evaluation_07.output
  tests/fe/point_evaluation_08.cc
  tests/fe/point_evaluation_08.output
  tests/fe/point_evaluation_09.cc
  tests/fe/point_evaluation_09.output
Labels: Finite Element, Reviewed and ready to merge, ready to test

#11640 Minor simplification in QProjector.
  source/base/qprojector.cc
Labels: ready to test

#11604 Move the get_*mapping() functions into ReferenceCell::Type.
  include/deal.II/fe/fe_interface_values.h
  include/deal.II/fe/fe_tools.templates.h
  include/deal.II/fe/mapping_q1.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/grid_tools_cache.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/numerics/error_estimator.templates.h
  include/deal.II/numerics/vector_tools_constraints.h
  include/deal.II/numerics/vector_tools_interpolate.templates.h
  include/deal.II/particles/generators.h
  source/fe/fe_values.cc
  source/grid/reference_cell.cc
  source/grid/reference_cell.inst.in
  source/grid/tria.cc
  source/grid/tria_accessor.cc
  source/meshworker/scratch_data.cc
  source/numerics/derivative_approximation.cc
Labels: ready to test

#11505 Add FE_P_Bubbles
  doc/doxygen/references.bib
  include/deal.II/simplex/barycentric_polynomials.h
  include/deal.II/simplex/fe_lib.h
  source/simplex/fe_lib.cc
  source/simplex/fe_lib.inst.in
  source/simplex/polynomials.cc
  source/simplex/quadrature_lib.cc
  tests/simplex/fe_p_bubbles_01.cc
  tests/simplex/fe_p_bubbles_01.with_simplex_support=on.out
  tests/simplex/fe_p_bubbles_02.cc
  tests/simplex/fe_p_bubbles_02.with_simplex_support=on.out
Labels: Enhancement, Finite Element, Reviewed and ready to merge, ready to test

#11642 Move make_triangulation into ReferenceCell::Type
  include/deal.II/fe/fe_tools.templates.h
  include/deal.II/grid/reference_cell.h
  source/grid/reference_cell.cc
  source/grid/reference_cell.inst.in
  tests/simplex/orientation_02.cc
Labels: ready to test

#11643 Cancelling workflow for github actions.
  .github/workflows/cancelling.yml
  .github/workflows/docker.yml
Labels: Infrastructure, Reviewed and ready to merge

#11366 Added GridTools::get_subdomain_association(Tria, CellId).
  doc/news/changes/minor/20210107Fehling
  include/deal.II/grid/grid_tools.h
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
  tests/grid/grid_tools_subdomain_association_01.cc
  tests/grid/grid_tools_subdomain_association_01.with_p4est=true.mpirun=4.output
Labels: Parallel distributed, Triangulation, ready to test

#11515 Generalize p::d::SolutionTransfer for p::f::Triangulation
  doc/news/changes/minor/20210118PasqualeAfrica-2
  include/deal.II/distributed/fully_distributed_tria.h
  source/distributed/fully_distributed_tria.cc
  source/distributed/solution_transfer.cc
  source/distributed/tria.cc
  tests/fullydistributed_grids/save_load_01.cc
  tests/fullydistributed_grids/save_load_01.mpirun=1.output
  tests/fullydistributed_grids/save_load_01.mpirun=4.output
  tests/fullydistributed_grids/solution_transfer_01.cc
  tests/fullydistributed_grids/solution_transfer_01.mpirun=1.output
  tests/fullydistributed_grids/solution_transfer_01.mpirun=4.output
Labels: Parallel distributed, Reviewed and ready to merge, Triangulation, ready to test

#11606 Introduce Mapping::is_compatible_with
  include/deal.II/fe/mapping.h
  include/deal.II/fe/mapping_cartesian.h
  include/deal.II/fe/mapping_fe.h
  include/deal.II/fe/mapping_fe_field.h
  include/deal.II/fe/mapping_manifold.h
  include/deal.II/fe/mapping_q.h
  include/deal.II/fe/mapping_q_generic.h
  source/fe/fe_values.cc
  source/fe/mapping_cartesian.cc
  source/fe/mapping_fe.cc
  source/fe/mapping_fe_field.cc
  source/fe/mapping_q.cc
  source/fe/mapping_q_generic.cc
Labels: ready to test, simplices

#11646 Pass 'const double' objects by-value, rather than by-reference.
  include/deal.II/fe/fe_point_evaluation.h
Labels: Reviewed and ready to merge, ready to test

#11645 Simplify code.
  source/grid/reference_cell.cc
Labels: Reviewed and ready to merge, ready to test

#11627 Bugfix: Clear DoFHandler in Triangulation create signal.
  include/deal.II/grid/grid_generator.h
  include/deal.II/grid/tria.h
  source/dofs/dof_handler.cc
  tests/hp/crash_22.cc
  tests/hp/crash_22.output
Labels: Reviewed and ready to merge, ready to test

#11637 simplex: Adapt CellAccessor::neighbor_child_on_subface for triangles.
  include/deal.II/grid/reference_cell.h
  source/grid/tria_accessor.cc
  tests/simplex/refinement_03.cc
  tests/simplex/refinement_03.with_simplex_support=on.output
Labels: ready to test, simplices

#11624 Nicely format exception texts.
  doc/news/changes/minor/20210125WolfgangBangerth
  source/base/exceptions.cc
  tests/base/exception_nothrow.debug.output
  tests/base/unsubscribe_subscriptor.debug.output
  tests/parameter_handler/parameter_handler_19.debug.output
  tests/parameter_handler/parameter_handler_25.output
  tests/parameter_handler/parameter_handler_26.output
Labels: ready to test

#11648 Move two static private functions into an internal namespace.
  include/deal.II/base/qprojector.h
  source/base/qprojector.cc
Labels: ready to test

#11592 Added support for gmsh library - new write_msh()/read_msh() with manifolds
  cmake/configure/configure_gmsh.cmake
  cmake/modules/FindGMSH.cmake
  doc/news/changes/minor/20210120LucaHeltai
  include/deal.II/base/config.h.in
  include/deal.II/grid/grid_in.h
  include/deal.II/grid/grid_out.h
  source/grid/grid_in.cc
  source/grid/grid_out.cc
  source/grid/grid_out.inst.in
  tests/gmsh/gmsh_api_01.cc
  tests/gmsh/gmsh_api_01.with_gmsh_with_api=on.output
  tests/gmsh/gmsh_api_02.cc
  tests/gmsh/gmsh_api_02.with_gmsh_with_api=on.output
  tests/gmsh/gmsh_api_03.cc
  tests/gmsh/gmsh_api_03.with_gmsh_with_api=on.output
  tests/gmsh/gmsh_api_04.cc
  tests/gmsh/gmsh_api_04.with_gmsh_with_api=on.output
Labels: ready for review, ready to test

#11448 Added tests for FENothing constraints.
  tests/hp/fe_nothing_dominates.h
  tests/hp/fe_nothing_dominates_01.cc
  tests/hp/fe_nothing_dominates_01.output
  tests/hp/fe_nothing_dominates_02.cc
  tests/hp/fe_nothing_dominates_02.output
  tests/hp/fe_nothing_dominates_03.cc
  tests/hp/fe_nothing_dominates_03.output
Labels: Reviewed and ready to merge, ready to test

#11625 simplex: implement 'interface_constraints' for FE_Poly.
  source/simplex/fe_lib.cc
  tests/simplex/hanging_nodes_01.cc
  tests/simplex/hanging_nodes_01.with_simplex_support=on.output
Labels: ready to test

#11653 Fixed minor warnings.
  examples/step-70/step-70.cc
  source/grid/grid_in.cc
  source/grid/grid_out.cc
Labels: ready to test

#11654 Make N_Vector module compatible with SUNDIALS 3.2.1
  include/deal.II/sundials/n_vector.h
  include/deal.II/sundials/n_vector.templates.h
  include/deal.II/sundials/sundials_backport.h
  source/sundials/n_vector.cc
  source/sundials/n_vector.inst.in
  tests/sundials/n_vector.cc
  tests/sundials/n_vector.with_sundials.geq.5.0.0.output
  tests/sundials/n_vector.with_sundials.geq.5.0.0.with_mpi=true.with_trilinos=true.mpirun=2.output
Labels: Reviewed and ready to merge, ready to test

#11649 CMake: Update Sundials version check
  cmake/configure/configure_sundials.cmake
  doc/news/changes/incompatibilities/20210128Maier
Labels: Build system

#11656 Fix assert message
  include/deal.II/grid/reference_cell.h
Labels: ready to test

#11658 N_Vector: Support PETSc (Block)Vector and Trilinos' BlockVector
  include/deal.II/sundials/n_vector.templates.h
  source/sundials/n_vector.inst.in
  tests/sundials/n_vector.cc
  tests/sundials/n_vector.with_sundials.geq.5.0.0.with_mpi=true.mpirun=2.with_trilinos=true.with_petsc=true.output
  tests/sundials/n_vector.with_sundials.geq.5.0.0.with_trilinos=true.with_petsc=true.output
Labels: ready to test

#11655 SUNDIALS: Use new N_Vector module in ARKode wrapper
  include/deal.II/sundials/arkode.h
  source/sundials/arkode.cc
  tests/sundials/arkode_03.with_sundials.geq.5.4.0.output
Labels: Reviewed and ready to merge, ready to test
