Repository dealii/dealii, pull requests merged in 2022-02, with the labels that each got.

#13323 Micro simplication.
  source/base/data_out_base.cc
Labels: ready to test

#13316 MatrixFreeTools::compute_diagonal(): do not initialize vector
  doc/news/changes/incompatibilities/20220201SchreterMunch
  include/deal.II/matrix_free/tools.h
  tests/matrix_free/compute_diagonal_util.h
Labels: Matrix-free, ready to test

#13324 Fix warning regarding unused parameter
  include/deal.II/base/mpi_consensus_algorithms.templates.h
Labels: Parallel distributed, ready to test

#13322 Deal with empty function objects in CA algorithms.
  include/deal.II/base/mpi_consensus_algorithms.templates.h
Labels: Parallel distributed, ready to test

#13320 Replace is_detected (type) by is_supported_operation (variable).
  include/deal.II/base/template_constraints.h
  include/deal.II/base/work_stream.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/precondition.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/type_traits.h
  include/deal.II/matrix_free/vector_access_internal.h
  tests/matrix_free/fe_evaluation_type_traits.cc
  tests/matrix_free/fe_evaluation_type_traits_02.cc
  tests/matrix_free/matrix_free_type_traits.cc
Labels: ready to test

#13315 `MatrixFreeTools::compute_diagonal`: introduce template parameter `VectorType`
  doc/news/changes/minor/20220202Schreter
  include/deal.II/matrix_free/tools.h
  tests/matrix_free/compute_diagonal_07.cc
  tests/matrix_free/compute_diagonal_07.output
Labels: Matrix-free, ready to test

#13330 remove forward declarations of MappingQ
  include/deal.II/fe/mapping_manifold.h
  include/deal.II/fe/mapping_q.h
Labels: Mapping, ready to test

#13335 SolverControl: make constructors explicit
  include/deal.II/lac/solver_control.h
Labels: ready to test

#13332 fix a formula
  include/deal.II/grid/grid_generator.h
Labels: ready to test

#13336 VTU: put closing XML on separate line
  source/base/data_out_base.cc
  tests/data_out/data_out_12.with_zlib=off.output
  tests/data_out/data_out_12.with_zlib=on.output
  tests/data_out/data_out_13.with_zlib=off.output
  tests/data_out/data_out_13.with_zlib=on.output
  tests/data_out/data_out_base_vtu_02.with_zlib=true.output
  tests/data_out/data_out_base_vtu_04.with_zlib=off.output
  tests/data_out/data_out_base_vtu_04.with_zlib=on.output
  tests/data_out/data_out_base_vtu_05.with_zlib=off.output
  tests/data_out/data_out_base_vtu_05.with_zlib=on.output
  tests/data_out/data_out_base_vtu_compression_levels.with_zlib=true.output
  tests/data_out/data_out_postprocessor_tensor_02.output
  tests/grid/grid_out_07.with_zlib=on.output
  tests/grid/grid_out_08.with_zlib=on.output
  tests/grid/grid_out_per_processor_vtu_01.with_p4est=true.mpirun=3.with_zlib=off.output
  tests/grid/grid_out_per_processor_vtu_01.with_p4est=true.mpirun=3.with_zlib=on.output
  tests/grid/grid_out_per_processor_vtu_02.with_metis=true.mpirun=2.with_zlib=off.output
  tests/grid/grid_out_per_processor_vtu_02.with_metis=true.mpirun=2.with_zlib=on.output
  tests/grid/grid_out_per_processor_vtu_03.with_zlib=off.output
  tests/grid/grid_out_per_processor_vtu_03.with_zlib=on.output
  tests/hp/solution_transfer_03.with_zlib=true.output
  tests/hp/solution_transfer_05.with_zlib=off.output
  tests/hp/solution_transfer_05.with_zlib=on.output
  tests/mpi/codim_01.mpirun=3.with_zlib=on.with_p4est=true.with_p4est_with_vtk_binary=false.output
  tests/mpi/codim_01.mpirun=3.with_zlib=on.with_p4est=true.with_p4est_with_vtk_binary=false.output.1
  tests/mpi/parallel_vtu_01.with_trilinos=true.mpirun=1.with_zlib=on.with_p4est=true.output
  tests/mpi/parallel_vtu_01.with_trilinos=true.mpirun=3.with_zlib=on.with_p4est=true.output
  tests/simplex/data_out_write_vtu_01.output
  tests/simplex/write_mesh_per_processor_as_vtu_01.mpirun=3.output
Labels: ready to test

#13333 PreconditionIdentity: move implementation out of declaration
  include/deal.II/lac/precondition.h
Labels: ready to test

#13337 Fix deduction matrix free
  include/deal.II/lac/la_parallel_vector.h
  tests/matrix_free/laplace_operator_01.cc
  tests/matrix_free/laplace_operator_02.cc
  tests/matrix_free/laplace_operator_03.cc
Labels: Bug, ready to test

#13334 documentation fixes
  include/deal.II/lac/precondition.h
  include/deal.II/lac/solver_bicgstab.h
  include/deal.II/lac/solver_control.h
Labels: Documentation, ready to test

#13327 FEEval::reinit(std::array): use MappingDataOnTheFly
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/mapping_data_on_the_fly.h
Labels: Matrix-free, ready to test

#13328 Add MatrixFree::initialize_cell_data_vector()
  include/deal.II/matrix_free/matrix_free.h
Labels: Matrix-free, ready to test

#13342 Fix name of change-log entry
  doc/news/changes/minor/20220105SimonStickoJean-PaulPelteret
Labels: Documentation

#13340 Fix assert message for empty vector
  include/deal.II/lac/la_parallel_vector.h
Labels: Reviewed and ready to merge, Parallel distributed, ready to test

#13338 correcting some notations
  include/deal.II/lac/solver_cg.h
Labels: Documentation, ready to test

#13349 Reduce the runtime of the test fe_nedelec_sz_hessian_divergence_theorem
  tests/fe/fe_nedelec_sz_hessian_divergence_theorem.cc
  tests/fe/fe_nedelec_sz_hessian_divergence_theorem.output
Labels: ready to test

#13350 Add performance testing framework: preparatory refactoring
  cmake/macros/macro_deal_ii_add_test.cmake
  cmake/macros/macro_deal_ii_pickup_tests.cmake
  cmake/scripts/run_test.sh
  doc/developers/testsuite.html
  doc/users/testsuite.html
  tests/CMakeLists.txt
  tests/performance/CMakeLists.txt
  tests/setup_testsubproject.cmake
  tests/tests.h
Labels: ready for review, Build system, Tests, ready to test

#13353 make GridGenerator::hyper_ball_balanced() work with nonzero origins.
  doc/news/changes/minor/20220209DavidWells
  source/grid/grid_generator.cc
  tests/grid/grid_generator_hyper_ball_balanced.cc
  tests/grid/grid_generator_hyper_ball_balanced.output
Labels: Bug, Triangulation, ready to test

#13354 Make a variable 'const'.
  include/deal.II/lac/affine_constraints.templates.h
Labels: ready to test

#13355 Rename a variable.
  include/deal.II/base/mpi.h
Labels: ready to test

#13356 Document macro DEAL_II_VERSION_GTE
  include/deal.II/base/config.h.in
Labels: Reviewed and ready to merge

#13351 Add performance testing framework: implement .run_only keyword.
  cmake/macros/macro_deal_ii_add_test.cmake
  cmake/macros/macro_deal_ii_pickup_tests.cmake
  cmake/scripts/run_test.cmake
  doc/developers/testsuite.html
  tests/a-framework/run_only.cc
  tests/a-framework/run_only.run_only
Labels: ready for review, Build system, Tests, ready to test

#13326 Use the new CA interface instead of using AnonymousProcess.
  include/deal.II/fe/fe_tools_extrapolate.templates.h
  include/deal.II/matrix_free/matrix_free.templates.h
  source/base/mpi.cc
  source/grid/grid_tools.cc
  source/grid/tria_description.cc
Labels: ready to test

#13360 Use standard spacing between functions.
  include/deal.II/base/mpi.h
Labels: ready to test

#13361 Do not free objects we still need.
  include/deal.II/base/aligned_vector.h
Labels: ready to test

#13370 BlockDynamicSparsityPattern: Update doc for parallel distributed applications.
  include/deal.II/lac/block_sparsity_pattern.h
Labels: Documentation, Reviewed and ready to merge

#13373 MatrixFreeTools: small clean up
  include/deal.II/matrix_free/tools.h
  tests/matrix_free/compute_diagonal_07.cc
Labels: Matrix-free, ready to test

#13372 Performance tests: minor tweak for timing_step_22
  tests/performance/timing_step_22.cc
  tests/performance/timing_step_3.cc
Labels: Reviewed and ready to merge, ready to test

#13371 CMake: allow to use TEST_PICKUP_REGEX with run_performance_tests.cmake
  tests/run_performance_tests.cmake
  tests/run_testsuite.cmake
Labels: Build system

#13367 MPI: move mpi_type_id() out of internal
  include/deal.II/base/mpi.h
  include/deal.II/base/mpi.templates.h
  include/deal.II/base/mpi_noncontiguous_partitioner.templates.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  source/base/partitioner.cc
  source/base/process_grid.cc
  source/distributed/repartitioning_policy_tools.cc
  source/distributed/tria_base.cc
  source/lac/scalapack.cc
  source/matrix_free/vector_data_exchange.cc
  tests/mpi/renumber_cuthill_mckee.cc
  tests/mpi/renumber_cuthill_mckee_02.cc
Labels: Parallel, ready to test

#13364 Implement new Table<3, T>::reinit()
  include/deal.II/base/table.h
Labels: ready to test

#13363 step-55: init sparsity pattern with relevant dofs
  examples/step-55/step-55.cc
Labels: Reviewed and ready to merge, ready to test

#13382 Unify deal.II spelling
  contrib/utilities/check_encoding.py
  include/deal.II/lac/la_parallel_block_vector.templates.h
  include/deal.II/lac/trilinos_precondition.h
Labels: Documentation, Reviewed and ready to merge

#13375 Augment a doc string.
  include/deal.II/base/table_indices.h
Labels: Documentation, ready to test

#13385 Improve an error message.
  include/deal.II/lac/petsc_vector_base.h
Labels: ready to test

#13380 Indent scripts
  contrib/utilities/indent
  contrib/utilities/indent-all
Labels: ready to test

#13387 CMake: Set ${CTEST_SITE} if unset
  tests/run_testsuite.cmake
Labels: Bug, High Priority :warning:, Build system, Tests

#13386 CMake: Bugfix: Do not error out when not running performance tests
  tests/performance/performance_test_driver.h
Labels: ready to test

#13390 Overwrite LocationToLevelSet values with unassigned in MeshClassifier
  source/non_matching/mesh_classifier.cc
  tests/non_matching/mesh_classifier.cc
  tests/non_matching/mesh_classifier.output
Labels: Bug, ready to test, Non-matching

#13368 new MPI:broadcast with big count support
  include/deal.II/base/mpi.h
  tests/mpi/broadcast_02.cc
  tests/mpi/broadcast_02.mpirun=3.output
Labels: Reviewed and ready to merge, Parallel distributed, ready to test

#13313 Enable FE_Nothing in DoFTools::extract_constant_modes
  doc/news/changes/minor/20220207Proell
  include/deal.II/fe/fe_nothing.h
  source/dofs/dof_tools.cc
  source/fe/fe_nothing.cc
  tests/mpi/extract_constant_modes_03.cc
  tests/mpi/extract_constant_modes_03.mpirun=2.with_p4est=true.output
Labels: ready to test

#13379 support large buffers in MPI::broadcast()
  include/deal.II/base/mpi.h
Labels: Reviewed and ready to merge, ready to test

#13393 Explicitly delete a function that we don't want to be called.
  include/deal.II/base/mpi.h
Labels: ready to test

#13389 Testsuite: add a test checking test.json + test.output support
  tests/a-framework/parameter_file_3.json
  tests/a-framework/parameter_file_3.output
Labels: Tests, ready to test

#13396 LA::d::BV add copy_locally_owned_data_from()
  include/deal.II/lac/la_parallel_block_vector.h
  include/deal.II/lac/la_parallel_block_vector.templates.h
  source/lac/la_parallel_block_vector.inst.in
Labels: Reviewed and ready to merge, Parallel distributed, ready to test

#13398 Minor cleanup to test of non_matching::FEValues
  tests/non_matching/fe_values.cc
Labels: Reviewed and ready to merge, ready to test, Non-matching

#13374 CMake: Adjust MPI and ZLIB support query for p4est version 2.8
  cmake/modules/FindP4EST.cmake
Labels: Build system, ready to test

#13403 remove useless assert
  include/deal.II/base/mpi.h
Labels: Reviewed and ready to merge, ready to test

#13399 Improve instruction-level parallelism for precondition_SSOR
  include/deal.II/lac/sparse_matrix.templates.h
Labels: Reviewed and ready to merge, Linear Algebra, ready to test

#13384 Avoid implicit-bool conversion for stream objects.
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/chunk_sparse_matrix.templates.h
  include/deal.II/lac/cuda_sparse_matrix.h
  include/deal.II/lac/full_matrix.templates.h
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/lac/la_vector.templates.h
  include/deal.II/lac/read_write_vector.templates.h
  include/deal.II/lac/sparse_matrix.templates.h
  include/deal.II/lac/sparse_matrix_ez.templates.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  include/deal.II/lac/vector.h
  include/deal.II/lac/vector.templates.h
  source/base/data_out_base.cc
  source/base/index_set.cc
  source/base/parameter_acceptor.cc
  source/base/parameter_handler.cc
  source/base/table_handler.cc
  source/base/utilities.cc
  source/distributed/fully_distributed_tria.cc
  source/distributed/tria.cc
  source/dofs/dof_tools.cc
  source/gmsh/utilities.cc
  source/grid/grid_in.cc
  source/grid/grid_out.cc
  source/grid/persistent_tria.cc
  source/grid/reference_cell.cc
  source/grid/tria.cc
  source/lac/chunk_sparsity_pattern.cc
  source/lac/cuda_vector.cu
  source/lac/dynamic_sparsity_pattern.cc
  source/lac/lapack_full_matrix.cc
  source/lac/petsc_matrix_base.cc
  source/lac/petsc_parallel_vector.cc
  source/lac/petsc_vector_base.cc
  source/lac/sparsity_pattern.cc
  source/lac/trilinos_epetra_vector.cc
  source/lac/trilinos_sparse_matrix.cc
  source/lac/trilinos_sparsity_pattern.cc
  source/lac/trilinos_vector.cc
  source/numerics/histogram.cc
Labels: ready to test

#13365 Early deprecate functions in DoFTools
  doc/news/changes/incompatibilities/20220212Munch
  examples/step-16/step-16.cc
  examples/step-18/step-18.cc
  examples/step-32/step-32.cc
  examples/step-37/doc/results.dox
  examples/step-37/step-37.cc
  examples/step-40/step-40.cc
  examples/step-42/step-42.cc
  examples/step-45/step-45.cc
  examples/step-48/step-48.cc
  examples/step-50/step-50.cc
  examples/step-55/step-55.cc
  examples/step-62/step-62.cc
  examples/step-63/step-63.cc
  examples/step-64/step-64.cu
  examples/step-66/step-66.cc
  examples/step-68/step-68.cc
  examples/step-69/step-69.cc
  examples/step-70/step-70.cc
  examples/step-75/step-75.cc
  include/deal.II/dofs/dof_tools.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  include/deal.II/multigrid/mg_constrained_dofs.h
  source/dofs/dof_tools.cc
  source/dofs/dof_tools.inst.in
Labels: ready to test

#13400 Fix typo
  tests/performance/performance_test_driver.h
  tests/performance/timing_step_22.cc
  tests/performance/timing_step_3.cc
Labels: Reviewed and ready to merge, Tests

#13388 CMake: Allow to define multiple threads= variant tests
  cmake/macros/macro_deal_ii_add_test.cmake
  tests/a-framework/concurrent_threads.cc
  tests/a-framework/concurrent_threads.threads=2.output
  tests/a-framework/concurrent_threads.threads=4.output
  tests/performance/collect_measurements
Labels: ready to test

#13405 Add matrix-free benchmark based on step-37
  tests/performance/timing_step_37.cc
  tests/performance/timing_step_37.threads=1.mpirun=max.release.run_only
Labels: Tests, ready to test

#13392 CMake: Simplify some logic in DEAL_II_ADD_TEST and add verbose error messages
  cmake/macros/macro_deal_ii_add_test.cmake
  tests/parameter_handler/parameter_handler_16.cc
  tests/parameter_handler/parameter_handler_16_in.prm
  tests/parameter_handler/parameter_handler_18.cc
  tests/parameter_handler/parameter_handler_18_in.prm
  tests/parameter_handler/parameter_handler_1_include.cc
  tests/parameter_handler/parameter_handler_1_include.prm
  tests/parameter_handler/parameter_handler_1_include_fail.cc
  tests/parameter_handler/parameter_handler_1_include_fail.output
  tests/parameter_handler/parameter_handler_1_include_fail_in.prm
  tests/parameter_handler/parameter_handler_1_include_in.prm
  tests/parameter_handler/parameter_handler_1_include_in.prm2
  tests/parameter_handler/parameter_handler_22_last_line.cc
  tests/parameter_handler/parameter_handler_22_last_line_in.prm
  tests/parameter_handler/parameter_handler_24.cc
  tests/parameter_handler/parameter_handler_24_in.prm
  tests/sundials/arkode_01.cc
  tests/sundials/arkode_01_in.prm
  tests/sundials/arkode_02.cc
  tests/sundials/arkode_03.cc
  tests/sundials/arkode_03_in.prm
  tests/sundials/arkode_04.cc
  tests/sundials/arkode_04_in.prm
  tests/sundials/arkode_05.cc
  tests/sundials/arkode_05_in.prm
  tests/sundials/arkode_06.cc
  tests/sundials/arkode_06_in.prm
  tests/sundials/arkode_07.cc
  tests/sundials/arkode_07_in.prm
  tests/sundials/arkode_08.cc
  tests/sundials/arkode_08_in.prm
  tests/sundials/arkode_repeated_solve.cc
  tests/sundials/arkode_repeated_solve_in.prm
  tests/sundials/ida_01.cc
  tests/sundials/ida_01_in.prm
  tests/sundials/ida_02.cc
Labels: Build system, ready to test

#13397 Add support in Patterns::Tools::Convert for std::array
  doc/news/changes/minor/20220216LucaHeltai
  include/deal.II/base/patterns.h
  tests/parameter_handler/pattern_tools_13.cc
  tests/parameter_handler/pattern_tools_13.output
Labels: ready for review, ready to test

#13406 Improve indentation in a few tutorials
  examples/step-37/step-37.cc
  examples/step-48/step-48.cc
  examples/step-59/step-59.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#13413 CMake: Do not use "\." in CMake regular expression
  cmake/macros/macro_deal_ii_add_test.cmake
Labels: Reviewed and ready to merge, ready to test

#13407 step-40/step-17 grammar edits
  examples/step-17/doc/intro.dox
  examples/step-40/doc/intro.dox
  examples/step-40/step-40.cc
Labels: Reviewed and ready to merge, ready to test

#13401 Harden cmake regexes when looking for #define strings.
  cmake/modules/FindADOLC.cmake
  cmake/modules/FindGSL.cmake
  cmake/modules/FindMUPARSER.cmake
  cmake/modules/FindOPENCASCADE.cmake
  cmake/modules/FindP4EST.cmake
  cmake/modules/FindTRILINOS.cmake
Labels: ready to test

#13408 CMake: also record git commit timestamp
  cmake/macros/macro_deal_ii_query_git_information.cmake
  cmake/setup_write_config.cmake
  doc/news/changes/minor/20220217Maier
  tests/performance/collect_measurements
Labels: Reviewed and ready to merge, ready to test

#13423 Bugfix: adjust collect_measurements to new directory layout
  tests/performance/collect_measurements
Labels: Tests, ready to test

#13421 Fixed bug in gmsh api.
  doc/news/changes/minor/20220220LucaHeltai
  source/grid/grid_out.cc
  tests/gmsh/gmsh_api_05.cc
  tests/gmsh/gmsh_api_05.with_gmsh_with_api=on.output
Labels: ready for review, External libraries, ready to test, Meshes

#13426 CMake: Fix typo
  tests/run_performance_tests.cmake
Labels: Reviewed and ready to merge

#13425 Add erf function to deal.II muparser functions
  include/deal.II/base/mu_parser_internal.h
  source/base/function_parser.cc
  source/base/mu_parser_internal.cc
Labels: Reviewed and ready to merge, ready to test

#13420 FEEval::check_vector_compatibility: improve assert message
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/vector_access_internal.h
Labels: Matrix-free, ready to test

#13429 Replace present_index by index() in DoFAccessor
  include/deal.II/dofs/dof_accessor.templates.h
Labels: Bug, ready to test

#13430 Improve assert message for invalid FE indices in DoFAccessor
  include/deal.II/dofs/dof_accessor.templates.h
Labels: ready to test

#13422 Remove some unnecessary includes of grid_tools.h
  doc/news/changes/incompatibilities/20220222MartinKronbichler
  examples/step-75/step-75.cc
  examples/step-85/step-85.cc
  include/deal.II/base/mpi_remote_point_evaluation.h
  include/deal.II/distributed/fully_distributed_tria.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  include/deal.II/numerics/point_value_history.h
  source/numerics/point_value_history.cc
  tests/distributed_grids/checkpointing_02.cc
  tests/distributed_grids/checkpointing_03.cc
  tests/matrix_free/compress_mapping.cc
  tests/matrix_free/ecl.h
  tests/matrix_free/ecl_02.cc
  tests/matrix_free/fe_evaluation_renumbered.cc
  tests/matrix_free/parallel_multigrid_fullydistributed.cc
  tests/multigrid-global-coarsening/mg_transfer_p_04.cc
  tests/multigrid-global-coarsening/multigrid_util.h
  tests/remote_point_evaluation/mapping_02.cc
  tests/simplex/data_out_write_hdf5_02.cc
  tests/simplex/step-40.cc
  tests/simplex/step-67.cc
Labels: ready to test

#13435 Fixed ParsedConvergenceTable::difference()
  doc/news/changes/minor/20220222LucaHeltai
  include/deal.II/base/parsed_convergence_table.h
  tests/base/parsed_convergence_table_11.cc
  tests/base/parsed_convergence_table_11.output
Labels: ready for review, Reviewed and ready to merge, ready to test

#13432 change logic in tensor product kernels to positive statements?
  include/deal.II/matrix_free/tensor_product_kernels.h
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#13433 New DoFAccessor test added for vertex dofs
  tests/dofs/dof_accessor_02.cc
  tests/dofs/dof_accessor_02.output
Labels: Reviewed and ready to merge, DoFs, ready to test

#13434 Fix p:d:T::copy_triangulation()
  doc/news/changes/minor/20220222Dravins
  source/distributed/tria.cc
Labels: Bug, Reviewed and ready to merge, Parallel distributed, ready to test

#13439 Declare a number of static consts as constexpr
  include/deal.II/base/function.h
  include/deal.II/base/incremental_function.h
  include/deal.II/base/polynomial_space.h
  include/deal.II/base/polynomials_barycentric.h
  include/deal.II/base/polynomials_p.h
  include/deal.II/base/polynomials_pyramid.h
  include/deal.II/base/polynomials_rannacher_turek.h
  include/deal.II/base/polynomials_wedge.h
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/base/tensor_product_polynomials.h
  include/deal.II/base/tensor_product_polynomials_bubbles.h
  include/deal.II/base/tensor_product_polynomials_const.h
  include/deal.II/differentiation/ad/ad_helpers.h
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/dofs/dof_handler.h
  include/deal.II/fe/fe.h
  include/deal.II/fe/fe_base.h
  include/deal.II/fe/fe_poly.h
  include/deal.II/fe/fe_values.h
  include/deal.II/grid/persistent_tria.h
  include/deal.II/grid/tria.h
  include/deal.II/grid/tria_accessor.h
  include/deal.II/hp/fe_values.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/meshworker/integration_info.h
Labels: ready to test

#13441 Fix run time error in step-75: initialize diagonal vector
  examples/step-75/step-75.cc
Labels: Reviewed and ready to merge, Matrix-free, Tutorials, ready to test

#13436 Move a couple of functions out of line.
  include/deal.II/sundials/arkode.h
Labels: ready to test

#13416 Fix non matching coupling
  doc/news/changes/minor/20220218LucaHeltai_b
  include/deal.II/non_matching/coupling.h
  source/non_matching/coupling.cc
  source/non_matching/coupling.inst.in
  tests/non_matching/coupling_09.cc
  tests/non_matching/coupling_09.with_umfpack=on.output
Labels: ready for review, ready to test, Non-matching

#13437 Replace present_index by index() in DoFAccessor
  include/deal.II/dofs/dof_accessor.templates.h
Labels: ready to test

#13450 Fix instantiation for add_entries_local_to_global
  source/lac/affine_constraints.inst.in
Labels: ready to test

#13449 cell_weight: not implemented for partition_zorder
  source/grid/grid_tools.cc
Labels: Parallel shared, ready to test

#13453 Avoid a warning about comparison of differently sized integers.
  source/distributed/tria.cc
Labels: ready to test

#13454 add changelog for gmsh inverted cell fix
  doc/news/changes/minor/20220226tjhei
Labels: Documentation, Reviewed and ready to merge

#13455 add test for invert_cells_with_negative_measure
  tests/grid/grid_invert_02.cc
  tests/grid/grid_invert_02.output
Labels: Reviewed and ready to merge, ready to test

#13427 Add shape function illustrations for FE_Nedelec
  doc/doxygen/images/fe_nedelec_shape_function_0_00.png
  doc/doxygen/images/fe_nedelec_shape_function_0_01.png
  doc/doxygen/images/fe_nedelec_shape_function_0_02.png
  doc/doxygen/images/fe_nedelec_shape_function_0_03.png
  doc/doxygen/images/fe_nedelec_shape_function_1_00.png
  doc/doxygen/images/fe_nedelec_shape_function_1_01.png
  doc/doxygen/images/fe_nedelec_shape_function_1_02.png
  doc/doxygen/images/fe_nedelec_shape_function_1_03.png
  doc/doxygen/images/fe_nedelec_shape_function_1_04.png
  doc/doxygen/images/fe_nedelec_shape_function_1_05.png
  doc/doxygen/images/fe_nedelec_shape_function_1_06.png
  doc/doxygen/images/fe_nedelec_shape_function_1_07.png
  doc/doxygen/images/fe_nedelec_shape_function_1_08.png
  doc/doxygen/images/fe_nedelec_shape_function_1_09.png
  doc/doxygen/images/fe_nedelec_shape_function_1_10.png
  doc/doxygen/images/fe_nedelec_shape_function_1_11.png
  doc/doxygen/images/fe_nedelec_shape_function_2_00.png
  doc/doxygen/images/fe_nedelec_shape_function_2_01.png
  doc/doxygen/images/fe_nedelec_shape_function_2_02.png
  doc/doxygen/images/fe_nedelec_shape_function_2_03.png
  doc/doxygen/images/fe_nedelec_shape_function_2_04.png
  doc/doxygen/images/fe_nedelec_shape_function_2_05.png
  doc/doxygen/images/fe_nedelec_shape_function_2_06.png
  doc/doxygen/images/fe_nedelec_shape_function_2_07.png
  doc/doxygen/images/fe_nedelec_shape_function_2_08.png
  doc/doxygen/images/fe_nedelec_shape_function_2_09.png
  doc/doxygen/images/fe_nedelec_shape_function_2_10.png
  doc/doxygen/images/fe_nedelec_shape_function_2_11.png
  doc/doxygen/images/fe_nedelec_shape_function_2_12.png
  doc/doxygen/images/fe_nedelec_shape_function_2_13.png
  doc/doxygen/images/fe_nedelec_shape_function_2_14.png
  doc/doxygen/images/fe_nedelec_shape_function_2_15.png
  doc/doxygen/images/fe_nedelec_shape_function_2_16.png
  doc/doxygen/images/fe_nedelec_shape_function_2_17.png
  doc/doxygen/images/fe_nedelec_shape_function_2_18.png
  doc/doxygen/images/fe_nedelec_shape_function_2_19.png
  doc/doxygen/images/fe_nedelec_shape_function_2_20.png
  doc/doxygen/images/fe_nedelec_shape_function_2_21.png
  doc/doxygen/images/fe_nedelec_shape_function_2_22.png
  doc/doxygen/images/fe_nedelec_shape_function_2_23.png
  include/deal.II/fe/fe_nedelec.h
Labels: Documentation, Reviewed and ready to merge, Finite Element, ready to test

#13461 CMake: require MPI 3.0
  cmake/configure/configure_1_mpi.cmake
Labels: ready to test

#13446 Simplify MPI IO in parallel vtu output
  source/base/data_out_base.cc
Labels: ready to test
