Repository dealii/dealii, pull requests merged in 2022-12, with the labels that each got.

#14512 Fix typos in source function name
  include/deal.II/lac/trilinos_solver.h
Labels: Reviewed and ready to merge, ready to test

#14506 CMake: Remove deal.IIFeatureConfig.cmake
  cmake/config/CMakeLists.txt
  cmake/config/Config.cmake.in
  cmake/setup_write_config.cmake
  doc/news/changes/incompatibilities/20221130Maier
Labels: Build system

#14516 step-85: add namespace to documentation
  examples/step-85/doc/intro.dox
Labels: Reviewed and ready to merge, ready to test

#14515 CMake: Bugfix: only add to the linker line what is needed
  cmake/modules/FindDEAL_II_TRILINOS.cmake
Labels: Bug, High Priority :warning:, Build system, Reviewed and ready to merge, ready to test

#14514 github/actions: install kokkos outside of deal.II source directory
  .github/workflows/linux.yml
Labels: Infrastructure, Reviewed and ready to merge

#14517 update changelog for release
  doc/news/9.4.0-vs-9.4.1.h
  doc/news/changes/minor/20220704gassmoeller
Labels: Reviewed and ready to merge

#14513 Fix 'testing equality to None' python issue
  contrib/utilities/parse_ctest_output.py
Labels: Infrastructure

#14504 Run the different parts of creating VTU output in parallel.
  source/base/data_out_base.cc
Labels: ready to test

#14519 fix warning: -1 assignment to unsigned
  include/deal.II/numerics/vector_tools_constraints.templates.h
Labels: Reviewed and ready to merge, ready to test

#14521 Fix some warnings in tests
  tests/base/aligned_vector_memory_02.cc
  tests/base/taylor_estimate_function_bounds.cc
  tests/distributed_grids/solution_transfer_05.cc
  tests/dofs/dof_test.cc
  tests/fe/fe_values_views_types.cc
  tests/grid/grid_in_out_vtu_01.cc
  tests/grid/grid_test.cc
  tests/numerics/no_flux_17.cc
Labels: ready to test

#14523 Just do 'using namespace dealii' in main().
  examples/step-12b/step-12b.cc
  examples/step-81/step-81.cc
Labels: ready to test

#14529 Fix compilation of step-70.
  examples/step-70/step-70.cc
Labels: Tutorials

#14530 [9.4] Fix compilation of step-70.
  examples/step-70/step-70.cc
Labels: Release, Tutorials

#14524 Avoid using dealii:: qualified names.
  examples/step-32/step-32.cc
  examples/step-33/step-33.cc
  examples/step-50/step-50.cc
  examples/step-64/step-64.cc
  examples/step-69/step-69.cc
  examples/step-70/step-70.cc
  examples/step-76/step-76.cc
  examples/step-81/step-81.cc
  examples/step-85/step-85.cc
Labels: ready to test

#14532 Remove a 'using' declaration in step-50 that is in the way.
  examples/step-50/step-50.cc
Labels: ready to test

#14534 Don't use __has_trivial_copy
  include/deal.II/lac/vector_operations_internal.h
Labels: Reviewed and ready to merge, ready to test

#14533 Solver control history
  doc/news/changes/minor/20221205Ivannikov
  source/lac/solver_control.cc
  tests/lac/solver_control_04.cc
  tests/lac/solver_control_04.output
Labels: ready to test

#14528 CMake: remove a number of obscure configuration options
  cmake/checks/check_02_compiler_features.cmake
  cmake/config/Config.cmake.in
  cmake/configure/configure_00_threads.cmake
  cmake/macros/macro_deal_ii_setup_target.cmake
  cmake/macros/macro_switch_library_preference.cmake
  cmake/setup_cached_variables.cmake
  cmake/setup_compiler_flags.cmake
  cmake/setup_compiler_flags_gnu.cmake
  cmake/setup_compiler_flags_intel.cmake
  cmake/setup_deal_ii.cmake
  cmake/setup_write_config.cmake
  doc/developers/porting.html
  doc/news/changes/incompatibilities/20221202Maier
  doc/users/cmake_dealii.html
  doc/users/cmake_user.html
  doc/users/config.sample
Labels: Build system, ready to test

#14531 Step 77: fix bug
  examples/step-77/step-77.cc
  tests/sundials/step-77.cc
  tests/sundials/step-77.with_umfpack=on.output
Labels: Bug, ready to test

#14535 MarchingCubeAlgorithm<1>: Remove determination of a saddle point
  include/deal.II/grid/grid_tools.h
  source/grid/grid_tools.cc
  tests/grid/grid_generator_marching_cube_algorithm_02.cc
  tests/grid/grid_generator_marching_cube_algorithm_02.with_p4est=true.mpirun=1.output
Labels: ready to test

#14540 CMake: Ensure we use "-pthread" instead of "-lpthread" for thread support
  cmake/configure/configure_00_threads.cmake
Labels: Bug, Build system, ready to test

#14541 Fix some deprecations
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/la_vector.templates.h
  include/deal.II/lac/read_write_vector.h
  include/deal.II/lac/read_write_vector.templates.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  source/base/mpi.cc
  source/base/mpi_noncontiguous_partitioner.cc
  source/base/partitioner.cc
  source/distributed/repartitioning_policy_tools.cc
  source/grid/tria_description.cc
  source/matrix_free/dof_info.cc
  source/matrix_free/vector_data_exchange.cc
Labels: ready to test

#14542 [CI] add new MPI Jenkinsfile
  contrib/ci/Jenkinsfile.mpi
Labels: Infrastructure, ready to test

#14548 Fix indentation in Jenkinsfile.mpi
  contrib/ci/Jenkinsfile.mpi
Labels: ready to test

#14417 Introduce 4th-kind Chebyshev preconditioner
  doc/doxygen/references.bib
  doc/news/changes/minor/20221112KronbichlerMunch
  include/deal.II/lac/precondition.h
  tests/lac/precondition_chebyshev_06.cc
  tests/lac/precondition_chebyshev_06.output
Labels: ready for review, Linear Algebra, ready to test

#14543 Address Wundefined-var-template
  cmake/setup_compiler_flags_gnu.cmake
  include/deal.II/fe/mapping_q1.h
  include/deal.II/hp/mapping_collection.h
  source/fe/mapping_q1.cc
  source/hp/mapping_collection.cc
Labels: ready to test

#14546 step-70: remove a dependency on boost.
  examples/step-70/step-70.cc
Labels: Tutorials, ready to test

#14550 CMake: Bugfix: only export DEAL_II_GMSH_WITH_API if gmsh is configured
  cmake/configure/configure_50_gmsh.cmake
Labels: Bug, Build system, ready to test

#14552 Modified Gram-Schmidt: add docu
  doc/news/changes/minor/20221208Munch
  include/deal.II/lac/solver_gmres.h
Labels: Documentation

#14551 Take over #14540 and #14544
  cmake/configure/configure_00_threads.cmake
  cmake/configure/configure_50_gmsh.cmake
Labels: Build system

#14331 TensorProductMatrixSymmetricSumCollection: allow to disable compression
  include/deal.II/lac/tensor_product_matrix.h
  include/deal.II/numerics/tensor_product_matrix_creator.h
  tests/lac/tensor_product_matrix.h
  tests/lac/tensor_product_matrix_08.cc
  tests/lac/tensor_product_matrix_08.with_lapack=true.output
Labels: Matrix-free, Linear Algebra, ready to test

#14321 Rotate for dim=1 spacedim=2
  doc/news/changes/minor/20221208Munch_2
  include/deal.II/grid/grid_tools.h
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
  source/grid/grid_tools_nontemplates.cc
  tests/grid/rotate_01.cc
  tests/grid/rotate_01.output
Labels: ready to test

#14556 Replace one more occurrence of dim-predicated loops.
  source/base/data_out_base.cc
Labels: Enhancement, Reviewed and ready to merge, ready to test

#14560 Relax assert
  source/fe/fe_system.cc
Labels: Enhancement, Reviewed and ready to merge, ready to test

#14566 Rename tests
  tests/simplex/convert_hypercube_to_simplex_mesh_01.cc
  tests/simplex/convert_hypercube_to_simplex_mesh_01.output
  tests/simplex/convert_hypercube_to_simplex_mesh_02.cc
  tests/simplex/convert_hypercube_to_simplex_mesh_02.output
  tests/simplex/convert_hypercube_to_simplex_mesh_03.cc
  tests/simplex/convert_hypercube_to_simplex_mesh_03.output
Labels: ready to test

#14565 FEEvaluation: fix assert
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, ready to test

#14563 ParameterHandler: add example for json
  include/deal.II/base/parameter_handler.h
Labels: Documentation

#14549 Add get/set_mesh_smoothing to python bindings.
  contrib/python-bindings/include/triangulation_wrapper.h
  contrib/python-bindings/source/export_triangulation.cc
  contrib/python-bindings/source/triangulation_wrapper.cc
  contrib/python-bindings/tests/triangulation_wrapper.py
Labels: ready to test

#14555 [CI] disable old MPI build on Jenkins
  Jenkinsfile
Labels: ready to test

#14564 Add helper function to indicate power of two
  include/deal.II/matrix_free/util.h
  source/matrix_free/task_info.cc
Labels: ready to test

#14559 Tests: make mpiexec and numdiff optional
  cmake/macros/macro_deal_ii_add_test.cmake
  cmake/macros/macro_deal_ii_pickup_tests.cmake
  cmake/scripts/run_test.sh
Labels: Build system, Tests, ready to test

#14572 Avoid more compiler warnings about array access
  source/base/data_out_base.cc
  source/base/polynomials_rt_bubbles.cc
Labels: ready to test

#14570 Add weight_fe_q_dofs_by_entity_shifted() and compute_weights_fe_q_dofs_by_entity_shifted()
  include/deal.II/matrix_free/tensor_product_kernels.h
  tests/matrix_free/weight_fe_q_dofs_by_entity.cc
  tests/matrix_free/weight_fe_q_dofs_by_entity.output
Labels: Matrix-free, ready to test

#14573 Simplify data passing to vtk_point_index_from_ijk().
  source/base/data_out_base.cc
Labels: ready to test

#14539 Rearrange mapping related data
  include/deal.II/fe/fe.h
  include/deal.II/fe/fe_dgp_nonparametric.h
  include/deal.II/fe/fe_enriched.h
  include/deal.II/fe/fe_face.h
  include/deal.II/fe/fe_nedelec_sz.h
  include/deal.II/fe/fe_nothing.h
  include/deal.II/fe/fe_p1nc.h
  include/deal.II/fe/fe_poly.h
  include/deal.II/fe/fe_poly.templates.h
  include/deal.II/fe/fe_poly_face.h
  include/deal.II/fe/fe_poly_face.templates.h
  include/deal.II/fe/fe_poly_tensor.h
  include/deal.II/fe/fe_system.h
  include/deal.II/fe/fe_update_flags.h
  include/deal.II/fe/fe_values.h
  include/deal.II/fe/mapping.h
  include/deal.II/fe/mapping_cartesian.h
  include/deal.II/fe/mapping_fe.h
  include/deal.II/fe/mapping_fe_field.h
  include/deal.II/fe/mapping_manifold.h
  include/deal.II/fe/mapping_q.h
  include/deal.II/fe/mapping_related_data.h
  include/deal.II/non_matching/mapping_info.h
  source/fe/CMakeLists.txt
  source/fe/fe.cc
  source/fe/fe_dgp_nonparametric.cc
  source/fe/fe_enriched.cc
  source/fe/fe_face.cc
  source/fe/fe_nedelec_sz.cc
  source/fe/fe_nothing.cc
  source/fe/fe_p1nc.cc
  source/fe/fe_poly_tensor.cc
  source/fe/fe_system.cc
  source/fe/fe_values.cc
  source/fe/fe_values.inst.in
  source/fe/mapping.cc
  source/fe/mapping_cartesian.cc
  source/fe/mapping_fe_field.cc
  source/fe/mapping_q.cc
  source/fe/mapping_related_data.cc
  source/fe/mapping_related_data.inst.in
Labels: Mapping, Miscellaneous, ready to test

#14584 Update broken link in step-22 intro.dox
  examples/step-22/doc/intro.dox
Labels: Documentation

#14585 Fix deprecated usage in tests
  tests/quick_tests/step.cc
  tests/quick_tests/sundials-ida.cc
Labels: Reviewed and ready to merge, Tests, ready to test

#14510 Use Kokkos in MemorySpaceData
  include/deal.II/arborx/bvh.h
  include/deal.II/arborx/distributed_tree.h
  include/deal.II/base/kokkos.h
  include/deal.II/base/memory_space.h
  include/deal.II/base/memory_space_data.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/lac/vector_memory.templates.h
  include/deal.II/lac/vector_operations_internal.h
  source/base/CMakeLists.txt
  source/base/kokkos.cc
  source/base/mpi.cc
  tests/base/kokkos_01.cc
  tests/base/kokkos_01.output
Labels: Reviewed and ready to merge, ready to test

#14588 CI: show quicktest failures in Jenkins
  contrib/ci/Jenkinsfile.mpi
Labels: Infrastructure, ready to test

#14590 Some refactoring in connectivity.h
  include/deal.II/grid/connectivity.h
Labels: ready to test

#14586 CMake: quick test fixes for CI
  tests/CMakeLists.txt
  tests/run_quick_tests.cmake
Labels: Bug, Build system, Reviewed and ready to merge, ready to test

#14587 Memory optimizations
  include/deal.II/grid/connectivity.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/reference_cell.h
  source/base/partitioner.cc
  source/grid/grid_in.cc
  source/grid/tria.cc
  source/grid/tria_faces.cc
  source/grid/tria_levels.cc
Labels: Enhancement, Triangulation, ready to test

#14591 Petsc mpi management and getarray
  doc/news/changes/minor/20221220StefanoZampini
  include/deal.II/lac/la_parallel_block_vector.templates.h
  include/deal.II/lac/petsc_vector_base.h
  include/deal.II/lac/read_write_vector.templates.h
  include/deal.II/lac/vector.templates.h
  source/lac/petsc_matrix_base.cc
  source/lac/petsc_matrix_free.cc
  source/lac/petsc_parallel_vector.cc
  source/lac/petsc_vector_base.cc
Labels: Enhancement, Linear Algebra, External libraries, ready to test

#14547 Add hp to FEInterfaceValues
  include/deal.II/fe/fe_interface_values.h
  tests/feinterface/fe_interface_values_11.cc
  tests/feinterface/fe_interface_values_11.output
  tests/feinterface/fe_interface_values_12.cc
  tests/feinterface/fe_interface_values_12.output
Labels: ready for review, hp, ready to test

#14575 Petsc mat mpi getter
  doc/news/changes/minor/20221213StefanoZampini-b
  include/deal.II/lac/petsc_matrix_base.h
  source/lac/petsc_matrix_base.cc
Labels: Enhancement, ready for review, Linear Algebra, External libraries, ready to test

#14592 PETScWrappers:BlockSparseMatrix: create PETSc MATNEST
  doc/news/changes/minor/20221220StefanoZampini-b
  include/deal.II/lac/petsc_block_sparse_matrix.h
  source/lac/petsc_parallel_block_sparse_matrix.cc
  tests/petsc/block_matrices_01.cc
  tests/petsc/block_matrices_01.mpirun=1.output
Labels: Enhancement, ready for review, Linear Algebra, External libraries, ready to test

#14598 Don't install mold linker in CI
  .github/workflows/linux.yml
  .github/workflows/osx.yml
Labels: Infrastructure

#14593 Compress face and line data
  include/deal.II/grid/tria_accessor.templates.h
  include/deal.II/grid/tria_faces.h
  source/grid/tria.cc
  source/grid/tria_faces.cc
  tests/serialization/triangulation_01.output
  tests/serialization/triangulation_02.output
Labels: Enhancement, Triangulation, ready to test

#14603 Fix warning
  source/lac/petsc_parallel_block_sparse_matrix.cc
Labels: Reviewed and ready to merge, ready to test

#14612 small cleanup in tridiagonal_matrix.cc
  source/lac/tridiagonal_matrix.cc
Labels: ready to test

#14613 Better indent documentation of class Function.
  include/deal.II/base/function.h
Labels: Documentation

#14614 Isotropic refinement cleanup
  source/grid/tria.cc
  tests/simplex/refinement_01.cc
  tests/simplex/refinement_02.cc
Labels: Triangulation, ready to test

#14615 CMake: avoid race conditions between concurrent prm tests
  cmake/macros/macro_deal_ii_add_test.cmake
  tests/a-framework/CMakeLists.txt
Labels: Infrastructure, Reviewed and ready to merge, ready to test

#14576 CI: new serial Jenkins
  contrib/ci/Jenkinsfile.serial
Labels: Infrastructure, ready to test

#14617 Fix broken ADOL-C tests
  contrib/ci/Jenkinsfile.serial
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/base/tensor.h
Labels: ready to test

#14618 Fix tests output: replace CUDA with Default
  tests/cuda/array_view_access_data.debug.output
  tests/cuda/array_view_wrong_memory.debug.output
  tests/cuda/vector_memory_02.debug.output
Labels: ready to test

#14611 Extend hp support in FEInterfaceValues
  doc/news/changes/minor/20221228Pelteret
  include/deal.II/fe/fe_interface_values.h
Labels: Reviewed and ready to merge, hp, ready to test

#14620 Jenkins: run tests in random order
  contrib/ci/Jenkinsfile.mpi
Labels: Infrastructure, ready to test

#14624 Move a function to ReferenceCell
  include/deal.II/grid/reference_cell.h
  source/base/data_out_base.cc
  source/grid/reference_cell.cc
Labels: ready to test

#14537 Convert LinearAlgebra::distributed::Vector to Kokkos
  include/deal.II/base/array_view.h
  include/deal.II/base/config.h.in
  include/deal.II/base/memory_space_data.h
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/lac/read_write_vector.templates.h
  include/deal.II/lac/vector_operations_internal.h
  source/lac/CMakeLists.txt
  source/lac/la_parallel_vector.cc
  source/lac/la_parallel_vector_cuda.cc
  source/lac/read_write_vector.cc
  source/lac/vector_memory.cc
  source/lac/vector_memory_cuda.cc
  tests/lac/parallel_vector_01.cc
  tests/lac/parallel_vector_01.mpirun=2.output
  tests/lac/parallel_vector_02.cc
  tests/lac/parallel_vector_02.mpirun=2.output
  tests/lac/parallel_vector_03.cc
  tests/lac/parallel_vector_03.mpirun=2.output
  tests/lac/parallel_vector_03a.cc
  tests/lac/parallel_vector_03a.mpirun=2.output
  tests/lac/parallel_vector_04.cc
  tests/lac/parallel_vector_04.mpirun=2.output
  tests/lac/parallel_vector_05.cc
  tests/lac/parallel_vector_05.mpirun=2.output
  tests/lac/parallel_vector_06.cc
  tests/lac/parallel_vector_06.mpirun=2.output
  tests/lac/parallel_vector_08.cc
  tests/lac/parallel_vector_08.mpirun=2.output
  tests/lac/parallel_vector_10.cc
  tests/lac/parallel_vector_10.mpirun=2.output
  tests/lac/parallel_vector_11.cc
  tests/lac/parallel_vector_11.mpirun=2.output
  tests/lac/parallel_vector_12.cc
  tests/lac/parallel_vector_12.mpirun=2.output
  tests/lac/parallel_vector_13.cc
  tests/lac/parallel_vector_13.mpirun=2.output
  tests/lac/parallel_vector_14.cc
  tests/lac/parallel_vector_14.mpirun=2.output
  tests/lac/parallel_vector_15.cc
  tests/lac/parallel_vector_15.mpirun=2.output
  tests/lac/parallel_vector_16.cc
  tests/lac/parallel_vector_16.with_64bit_indices=on.mpirun=4.output
  tests/lac/parallel_vector_21.cc
  tests/lac/parallel_vector_21.mpirun=2.output
  tests/lac/parallel_vector_22.cc
  tests/lac/parallel_vector_22.mpirun=4.output
  tests/lac/parallel_vector_23.cc
  tests/lac/parallel_vector_23.mpirun=4.output
  tests/lac/parallel_vector_25.cc
  tests/lac/parallel_vector_25.mpirun=2.output
  tests/lac/parallel_vector_26.cc
  tests/lac/parallel_vector_26.mpirun=2.output
Labels: ready for review, ready to test

#14621 Remove DEAL_II_COMPILER_CUDA_AWARE
  doc/doxygen/options.dox.in
  include/deal.II/base/config.h.in
  include/deal.II/base/cuda.h
  include/deal.II/base/numbers.h
  include/deal.II/base/partitioner.templates.h
  include/deal.II/base/tensor.h
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/cuda_atomic.h
  include/deal.II/lac/cuda_kernels.h
  include/deal.II/lac/cuda_kernels.templates.h
  include/deal.II/lac/cuda_precondition.h
  include/deal.II/lac/cuda_solver_direct.h
  include/deal.II/lac/cuda_sparse_matrix.h
  include/deal.II/lac/precondition.h
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  include/deal.II/matrix_free/cuda_hanging_nodes_internal.h
  include/deal.II/matrix_free/cuda_matrix_free.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  include/deal.II/matrix_free/cuda_tensor_product_kernels.h
  tests/tests.h
Labels: Reviewed and ready to merge, ready to test

#14625 Improve documentation.
  include/deal.II/grid/reference_cell.h
Labels: Documentation, ready to test

#14622 Remove some duplication; also simplify VTK code.
  source/base/data_out_base.cc
Labels: ready to test
