Repository dealii/dealii, pull requests merged in 2022-01, with the labels that each got.

#13161 Extend ScratchData's public interface with getter methods to access private data
  doc/news/changes/minor/20211231Jean-PaulPelteret
  include/deal.II/meshworker/scratch_data.h
  source/meshworker/scratch_data.cc
Labels: ready to test

#11358 CI: select 64bit windows platform
  .github/workflows/windows.yml
Labels: ready to test

#13162 Change type of line_orientation in standard_vs_true_line_orientation
  include/deal.II/grid/reference_cell.h
Labels: ready to test

#13157 Avoid a temp array in the UMFPACK interfaces.
  source/lac/sparse_direct.cc
Labels: ready to test

#13156 Also simplify parallel::accumulate_from_subranges() with lambdas.
  include/deal.II/base/parallel.h
Labels: ready to test

#13155 Parallelize some functions setting up UMFPACK.
  source/lac/sparse_direct.cc
Labels: ready to test

#13163 Fix compilation error.
  include/deal.II/matrix_free/cuda_matrix_free.h
Labels: Bug, Reviewed and ready to merge, ready to test

#13082 Better document the NPX algorithm.
  include/deal.II/base/mpi_consensus_algorithms.h
  include/deal.II/base/mpi_consensus_algorithms.templates.h
Labels: ready to test

#12987 Make sure MPI BigData objects are always destroyed.
  include/deal.II/base/mpi.h
  source/base/mpi.cc
  source/distributed/tria_base.cc
  tests/mpi/create_mpi_datatype_01.cc
Labels: ready to test

#12968 Trilinos parallel is_non_negative() function
  doc/news/changes/minor/20211202OConnor
  source/lac/trilinos_vector.cc
  tests/mpi/trilinos_vector_non_negative.cc
  tests/mpi/trilinos_vector_non_negative.with_trilinos=true.mpirun=2.output
Labels: ready to test

#13164 Parallelize more operations in the UMFPACK interfaces.
  source/lac/sparse_direct.cc
Labels: Parallel shared, ready to test

#13165 Fix compilation with boost 1.78.
  cmake/configure/configure_2_boost.cmake
  include/deal.II/numerics/rtree.h
  tests/boost/rtree_01.cc
Labels: External libraries, ready to test

#13167 Simplify some code.
  source/base/patterns.cc
Labels: ready to test

#13170 Add some more tests for iterator filters
  doc/news/changes/minor/2022010531SimonStickoJean-PaulPelteret
  include/deal.II/fe/fe_interface_values.h
  tests/grid/filtered_iterator_07.cc
  tests/grid/filtered_iterator_07.output
  tests/grid/filtered_iterator_07_operator.cc
  tests/grid/filtered_iterator_07_operator.output
  tests/grid/filtered_iterator_08.cc
  tests/grid/filtered_iterator_08.output
Labels: ready to test

#13173 VectorTools::point_values(): fix types
  include/deal.II/numerics/vector_tools_evaluate.h
Labels: ready to test

#13172 Use std::string::size() instead of std::string::length().
  include/deal.II/base/hdf5.h
  include/deal.II/base/memory_consumption.h
  include/deal.II/base/table_handler.h
  source/base/logstream.cc
  source/base/parameter_handler.cc
  source/base/patterns.cc
  source/base/table_handler.cc
  source/base/timer.cc
  source/base/utilities.cc
  source/grid/grid_generator.cc
  source/grid/grid_in.cc
Labels: ready to test

#13152 Refactor PreconditionRelaxation
  include/deal.II/lac/precondition.h
Labels: Linear Algebra, ready to test

#13168 Fix a bug in FE_Face.
  source/fe/fe_face.cc
  tests/bits/faceq_subface_interpolation.output
Labels: ready to test

#13174 Update step-44 documentation.
  examples/step-44/doc/intro.dox
Labels: Documentation

#13147 Add a bit of documentation to MPI::compute_point_to_point_communication_pattern()
  source/base/mpi.cc
Labels: Documentation, ready to test

#13176 OneAPI compatibility: fix most of the API incompatibilities
  include/deal.II/base/work_stream.h
  include/deal.II/matrix_free/matrix_free.templates.h
  source/base/multithread_info.cc
  source/matrix_free/task_info.cc
Labels: ready for review, ready to test

#13177 FEPointEvaluation: fix types for multiple components
  include/deal.II/matrix_free/fe_point_evaluation.h
Labels: ready to test

#13180 [9.3] Boost 1.78
  cmake/configure/configure_2_boost.cmake
  include/deal.II/base/bounding_box_data_out.h
  include/deal.II/base/config.h.in
  include/deal.II/grid/grid_tools.h
  include/deal.II/numerics/rtree.h
  tests/boost/rtree_01.cc
Labels: Release, ready to test

#13178 RemotePointEvalution: pass marked_vertices
  include/deal.II/base/mpi_remote_point_evaluation.h
  include/deal.II/grid/grid_tools.h
  source/base/mpi_remote_point_evaluation.cc
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
Labels: ready to test

#13182 Add some more index range checks.
  include/deal.II/matrix_free/matrix_free.h
Labels: Reviewed and ready to merge, Miscellaneous, ready to test

#13183 Simplify some code.
  source/base/data_out_base.cc
  source/base/parameter_handler.cc
  source/base/utilities.cc
  source/fe/fe_q_dg0.cc
Labels: Reviewed and ready to merge, ready to test

#13189 Fix symbol confusion in step-52.
  examples/step-52/doc/intro.dox
  examples/step-52/step-52.cc
Labels: Reviewed and ready to merge, ready to test

#13190 Simplify initialization of block systems in step-20
  examples/step-20/step-20.cc
Labels: Reviewed and ready to merge, ready to test

#13191 Simplify initialization of block systems in step-21.
  examples/step-21/step-21.cc
Labels: Reviewed and ready to merge, ready to test

#13187 Fix RemotePointEvalution::marked_vertices for vectors with only false
  source/grid/grid_tools.cc
Labels: Parallel distributed, ready to test

#13186 Use better variable names in step-43.
  doc/news/changes/minor/20220107Bangerth-b
  examples/step-43/step-43.cc
Labels: ready to test

#13185 Provide some overloads and instantiations
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_accessor.templates.h
  source/grid/tria_accessor.inst.in
Labels: ready to test

#13188 Document a part of step-43 that confused @tjhei.
  examples/step-43/doc/intro.dox
Labels: Documentation, Reviewed and ready to merge

#13195 Add movie to step-67 tutorial program
  examples/step-67/doc/results.dox
Labels: Documentation, Tutorials

#13198 Be more thoughtful about parallel grain sizes in UMFPACK interfaces.
  source/lac/sparse_direct.cc
Labels: ready to test

#13184 Fix serialization of empty SparsityPattern objects
  doc/news/changes/minor/20220107Bangerth
  include/deal.II/lac/sparsity_pattern.h
  tests/serialization/sparsity_pattern_empty.cc
  tests/serialization/sparsity_pattern_empty.output
Labels: Reviewed and ready to merge, ready to test

#13204 Remove occurances of /// in source/
  include/deal.II/numerics/point_value_history.h
  source/base/data_out_base.cc
  source/base/function_lib.cc
  source/base/function_lib_cutoff.cc
  source/grid/grid_in.cc
  source/grid/tria.cc
  source/grid/tria_accessor.cc
  source/numerics/point_value_history.cc
Labels: Reviewed and ready to merge, ready to test

#13200 Updates to step-10
  examples/step-10/doc/results.dox
  examples/step-10/step-10.cc
Labels: Documentation, Reviewed and ready to merge, Tutorials, ready to test

#13199 Minor edits to the documentation of SparsityPattern.
  include/deal.II/lac/sparsity_pattern.h
Labels: Documentation, Reviewed and ready to merge, ready to test

#13197 Document the meaning of jump_in/average_of_* in FEInterfaceValues.
  include/deal.II/fe/fe_interface_values.h
Labels: Documentation, ready to test

#13203 Convert manual references into bibtex ones in step-43.
  doc/doxygen/references.bib
  examples/step-43/doc/intro.dox
  examples/step-43/step-43.cc
Labels: Documentation

#13206 Fix a bug: Don't reuse buffers for MPI_Isend.
  include/deal.II/fe/fe_tools_extrapolate.templates.h
Labels: ready to test

#13192 Fix manifold copying on lines when converting hexes to tets.
  doc/news/changes/minor/20220107DavidWells
  source/grid/grid_generator.cc
  tests/simplex/conv_hex_to_simplex.cc
  tests/simplex/conv_hex_to_simplex.output
  tests/simplex/conv_hex_to_simplex_02.output
  tests/simplex/conv_hex_to_simplex_03.output
Labels: Reviewed and ready to merge, Manifold, ready to test, simplices

#13159 Extend PreconditionRelaxation
  doc/news/changes/minor/20220101Munch
  include/deal.II/lac/precondition.h
  include/deal.II/matrix_free/operators.h
  tests/lac/precondition_relaxation_01.cc
  tests/lac/precondition_relaxation_01.output
Labels: Linear Algebra, ready to test

#13196 Add to the documentation of SymmetricTensor::operator*.
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/base/tensor.h
Labels: Documentation, ready to test

#13210 Added changelog for p4est installation script.
  doc/news/changes/minor/20210610Fehling
Labels: Documentation

#13209 [9.3] Fix setup script for p4est>=2.3.
  doc/external-libs/p4est-setup.sh
  doc/news/changes/minor/20210610Fehling
Labels: Reviewed and ready to merge, External libraries, ready to test

#13211 Fix a check for zero entries in the lumped mass matrix.
  include/deal.II/matrix_free/operators.h
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#13048 Use FEEvaluationHangingNodes in MGTwoLevelTransfer
  include/deal.II/multigrid/mg_transfer_global_coarsening.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
Labels: Multigrid, Matrix-free, ready to test

#13028 Generator for `pipe_junction` geometries.
  doc/doxygen/images/tee_corner.png
  doc/doxygen/images/tee_tpipe.png
  doc/doxygen/images/tee_ypipe.png
  doc/news/changes/major/20211201Fehling
  include/deal.II/grid/grid_generator.h
  source/grid/CMakeLists.txt
  source/grid/grid_generator_from_name.cc
  source/grid/grid_generator_pipe_junction.cc
  source/grid/grid_generator_pipe_junction.inst.in
  tests/grid/grid_generator_pipe_junction.cc
  tests/grid/grid_generator_pipe_junction.output
Labels: Reviewed and ready to merge, ready to test, Meshes

#13217 Fix some spurious variable names
  include/deal.II/matrix_free/evaluation_template_factory.h
Labels: Matrix-free, ready to test

#13215 Do not reuse an MPI_Status object.
  include/deal.II/base/mpi_consensus_algorithms.templates.h
Labels: Parallel distributed, ready to test

#13220 Fix doxygen problems with `GridGenerator::pipe_junction`
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator_pipe_junction.cc
Labels: Documentation

#12265 Add readability-implicit-bool-conversion
  .clang-tidy
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/mapping_info.templates.h
  include/deal.II/matrix_free/mapping_info_storage.templates.h
  source/fe/mapping_q.cc
  source/grid/tria_description.cc
  source/non_matching/fe_immersed_values.cc
Labels: ready to test

#13222 Add a changelog entry for #13165.
  doc/news/changes/minor/20220103DavidWells
Labels: Documentation

#13221 Fix a redefined variable error in a test.
  tests/mpi/data_out_hdf5_02.cc
Labels: Reviewed and ready to merge, Tests, Miscellaneous, ready to test

#13179 OneAPI compatibility: enable oneAPI configuration in CMake, changelog
  cmake/configure/configure_1_tbb.cmake
  doc/news/changes/minor/20220106BangerthMaier
  include/deal.II/matrix_free/matrix_free.templates.h
  source/matrix_free/task_info.cc
Labels: ready for review, Do not merge :skull_and_crossbones:, ready to test

#13225 Fix Y-pipe example in doc for `pipe_junction`.
  include/deal.II/grid/grid_generator.h
Labels: Documentation

#13224 [9.3] take over oneAPI fixes
  cmake/configure/configure_1_tbb.cmake
  cmake/modules/FindTBB.cmake
  doc/news/changes/minor/20220106BangerthMaier
  include/deal.II/base/config.h.in
  include/deal.II/base/work_stream.h
  include/deal.II/matrix_free/matrix_free.templates.h
  source/base/multithread_info.cc
  source/matrix_free/task_info.cc
Labels: ready for review, ready to test

#13227 CMake: adjust tbb path glob to "lib/intel64/gcc*" layout
  cmake/modules/FindTBB.cmake
Labels: Build system, External libraries, ready to test

#13234 [9.3] CMake: use portable "cmake -E remove" in quick_tests
  tests/quick_tests/CMakeLists.txt
Labels: Build system, Reviewed and ready to merge, Windows, ready to test

#13202 Faster and simpler search for lost particles
  source/particles/particle_handler.cc
Labels: ready to test

#13231 Marginally accelerate compute_point_to_point_communication_pattern().
  source/base/mpi.cc
Labels: Parallel distributed, ready to test

#13230 Add a couple of assertions.
  include/deal.II/base/mpi_consensus_algorithms.h
  include/deal.II/base/mpi_consensus_algorithms.templates.h
Labels: Parallel distributed, ready to test

#13226 Improve usability of PreconditionRelaxation
  include/deal.II/lac/precondition.h
Labels: Linear Algebra, ready to test

#13236 fix two small typos
  include/deal.II/base/mpi_consensus_algorithms.h
Labels: Documentation

#13238 Reference book directly in step-55.
  examples/step-55/doc/intro.dox
Labels: Documentation

#13237 Added bibtex entry for SolverMinRes reference.
  doc/doxygen/references.bib
  include/deal.II/lac/solver_minres.h
Labels: Documentation

#12983 Allow reusing mapping data in FEPointEvaluation
  include/deal.II/matrix_free/fe_point_evaluation.h
  source/matrix_free/fe_point_evaluation.cc
  source/matrix_free/fe_point_evaluation.inst.in
  tests/matrix_free/point_evaluation_15.cc
  tests/matrix_free/point_evaluation_15.output
  tests/matrix_free/point_evaluation_16.cc
  tests/matrix_free/point_evaluation_16.output
Labels: Discussion, Matrix-free, ready to test

#13240 FEEval: do not cast const away during read_dof_values()
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/type_traits.h
  include/deal.II/matrix_free/vector_access_internal.h
Labels: Matrix-free, ready to test

#13241 Make reference to SUNDIALS solvers in step-26.
  examples/step-26/doc/results.dox
Labels: Tutorials, ready to test

#13235 Some updates to the PEX code
  include/deal.II/base/mpi_consensus_algorithms.h
  include/deal.II/base/mpi_consensus_algorithms.templates.h
Labels: ready to test

#13244 Remove unnecessary include file
  source/dofs/dof_tools_sparsity.cc
Labels: DoFs, ready to test

#13248 Typo correction
  include/deal.II/base/parameter_acceptor.h
Labels: Documentation

#13247 Rename variable
  include/deal.II/matrix_free/fe_evaluation.h
Labels: ready to test

#13232 Validate correctness of input arguments.
  include/deal.II/base/mpi_consensus_algorithms.templates.h
Labels: Parallel distributed, ready to test

#13254 Revert "Add clang-tidy check"
  .clang-tidy
Labels: ready to test

#13249 Added bibtex entry for `refine_and_coarsen_optimize` reference.
  doc/doxygen/references.bib
  include/deal.II/grid/grid_refinement.h
Labels: Documentation

#13256 Hotfix: Avoid warning about implicit conversion to bool.
  include/deal.II/matrix_free/fe_point_evaluation.h
Labels: ready to test

#13251 FEEval: use get_cell_ids() at more places
  include/deal.II/matrix_free/fe_evaluation.h
Labels: ready to test

#13258 FEEval: do not use cell as indication if reinit() was called
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/fe_evaluation_data.h
Labels: Matrix-free, ready to test

#13253 Move jacobian_gradients into FEEvalData
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/fe_evaluation_data.h
Labels: Matrix-free, ready to test

#13250 Cleanup `references.bib`.
  doc/doxygen/references.bib
Labels: Documentation

#13255 Use consistent grammar in the list of tutorial programs.
  doc/doxygen/tutorial/tutorial.h.in
Labels: Documentation

#13265 Simplify code by using serialization functionality.
  include/deal.II/fe/fe_tools_extrapolate.templates.h
Labels: ready to test

#13264 Review of `references.bib`.
  doc/doxygen/references.bib
Labels: Documentation, Reviewed and ready to merge

#13219 Replace MPI_Irecv with MPI_Iprobe+MPI_Recv.
  include/deal.II/base/mpi_consensus_algorithms.h
  include/deal.II/base/mpi_consensus_algorithms.templates.h
Labels: ready for review, Parallel distributed, ready to test

#13257 PEX: Replace MPI_Irecv with MPI_Iprobe+MPI_Recv
  include/deal.II/base/mpi_consensus_algorithms.h
  include/deal.II/base/mpi_consensus_algorithms.templates.h
Labels: ready to test

#13262 Do not store some things in the CA::Interface base class.
  include/deal.II/base/mpi_consensus_algorithms.h
  include/deal.II/base/mpi_consensus_algorithms.templates.h
Labels: ready to test

#13073 Convert a few more locally-owned loops with filters.
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  source/distributed/fully_distributed_tria.cc
  source/distributed/grid_refinement.cc
  source/distributed/repartitioning_policy_tools.cc
  source/distributed/shared_tria.cc
  source/distributed/tria_base.cc
  source/dofs/dof_tools.cc
  source/grid/grid_tools.cc
  source/grid/grid_tools_cache.cc
  source/hp/refinement.cc
  source/numerics/data_out_resample.cc
  source/numerics/smoothness_estimator.cc
  tests/matrix_free/laplace_operator_03.cc
  tests/mpi/error_prediction_01.cc
  tests/mpi/error_prediction_02.cc
  tests/mpi/limit_p_level_difference_01.cc
  tests/mpi/limit_p_level_difference_02.cc
  tests/mpi/p_refinement_and_coarsening.cc
  tests/mpi/refine_and_coarsen_fixed_fraction_08.cc
  tests/mpi/refine_and_coarsen_fixed_fraction_09.cc
  tests/mpi/renumber_cuthill_mckee_03.cc
  tests/multigrid-global-coarsening/mg_transfer_a_03.cc
  tests/sharedtria/cell_data_transfer_01.cc
  tests/sharedtria/cell_data_transfer_02.cc
  tests/sharedtria/limit_p_level_difference_01.cc
  tests/sharedtria/limit_p_level_difference_02.cc
  tests/sharedtria/limit_p_level_difference_04.cc
  tests/simplex/step-18.cc
Labels: ready to test

#13266 Fix MF for LA::vector
  include/deal.II/matrix_free/type_traits.h
Labels: Bug, Matrix-free, ready to test

#13144 Fix omissions in GridGenerator::flatten_triangulation().
  doc/news/changes/minor/20211226Bangerth
  doc/news/changes/minor/20211227Bangerth
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  tests/grid/flatten_grid_02.cc
  tests/grid/flatten_grid_02.output
  tests/grid/flatten_grid_03.cc
  tests/grid/flatten_grid_03.output
  tests/simplex/conv_hex_to_simplex.output
  tests/simplex/conv_hex_to_simplex_02.output
  tests/simplex/conv_hex_to_simplex_03.output
Labels: ready to test

#13259 FEEval: replace usages of n_vectorization_actual
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#13252 Move quadrature_points into FEEvalData
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/fe_evaluation_data.h
Labels: Matrix-free, ready to test

#13261 Minor doc update to the consensus algorithms.
  include/deal.II/base/mpi_consensus_algorithms.h
Labels: ready to test

#13268 Fix LA::Vector::reinit()
  include/deal.II/lac/la_vector.templates.h
Labels: Bug, ready to test

#13273 Define MPI_COMM_NULL when not using MPI.
  include/deal.II/base/mpi.h
Labels: Reviewed and ready to merge, ready to test

#13274 Add ifdefs for is_reinitialized in FEEval
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/fe_evaluation_data.h
Labels: Bug, High Priority :warning:, Matrix-free, ready to test

#13270 Explain the use of iterative solvers in the introduction of step-3.
  examples/step-3/doc/intro.dox
Labels: Tutorials

#13275 Small fix to the documentation in step-37
  examples/step-37/doc/intro.dox
Labels: Documentation

#13276 Hide forward declarations in `fe/fe.h` from doxygen.
  include/deal.II/fe/fe.h
Labels: Documentation

#13277 Fix a sign error in step-22's introduction.
  examples/step-22/doc/intro.dox
Labels: Documentation, Reviewed and ready to merge, Tutorials

#13279 Update docu of NonMatching::FEImmersedSurfaceValues
  include/deal.II/non_matching/fe_immersed_values.h
Labels: Documentation, Non-matching

#13280 Use MPI::Utilities::free_communicator() where possible.
  include/deal.II/base/aligned_vector.h
  source/base/data_out_base.cc
  source/base/mpi.cc
  source/base/process_grid.cc
  source/base/utilities.cc
  source/lac/scalapack.cc
  source/sundials/arkode.cc
  source/sundials/ida.cc
Labels: Parallel distributed, ready to test

#13271 Use relative tolerances in step-3.
  examples/step-3/doc/results.dox
  examples/step-3/step-3.cc
Labels: ready to test

#13278 Fix bug in initial condition for transform_real_to_unit_cell
  doc/news/changes/minor/20220121MartinKronbichler
  include/deal.II/fe/mapping_q_internal.h
  tests/mappings/mapping_q_inverse_quadratic_approximation.output
  tests/mappings/mapping_q_points_real_to_unit_02.cc
  tests/mappings/mapping_q_points_real_to_unit_02.output
  tests/mappings/mapping_q_real_to_unit_internal.output
Labels: Mapping, ready to test

#13283 SparseMatrix: rename om to omega
  include/deal.II/lac/sparse_matrix.h
  include/deal.II/lac/sparse_matrix.templates.h
Labels: Reviewed and ready to merge, Linear Algebra, ready to test

#13285 PreconditionRelaxation: vmult/step w. relaxation
  include/deal.II/lac/precondition.h
Labels: Linear Algebra, ready to test

#13284 [9.3] Fix flags bug point_values
  include/deal.II/numerics/vector_tools_evaluate.h
Labels: ready to test

#13267 Remove the prepare_for_answer() callback in consensus algorithms.
  doc/news/changes/incompatibilities/20220118Bangerth
  include/deal.II/base/mpi_compute_index_owner_internal.h
  include/deal.II/base/mpi_consensus_algorithms.h
  include/deal.II/base/mpi_consensus_algorithms.templates.h
  include/deal.II/fe/fe_tools_extrapolate.templates.h
  include/deal.II/matrix_free/matrix_free.templates.h
  source/grid/grid_tools.cc
  tests/base/consensus_algorithm_01.cc
Labels: ready to test

#13289 Fix a bogus warning about a null pointer in a lambda.
  source/base/mpi.cc
Labels: Reviewed and ready to merge, Miscellaneous, ready to test

#13288 Minor edits to type traits classes.
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/precondition.h
  include/deal.II/matrix_free/type_traits.h
Labels: ready to test

#13292 [9.3] update changelog entries for point release
  doc/news/9.3.2-vs-9.3.3.h
  doc/news/changes/minor/20210610Fehling
  doc/news/changes/minor/20220106BangerthMaier
Labels: ready to test

#13286 Make naming of function arguments more uniform.
  include/deal.II/grid/reference_cell.h
Labels: ready to test

#13293 Port 9.3.3 changelog changes to master.
  doc/news/9.3.2-vs-9.3.3.h
  doc/news/changes/minor/20210610Fehling
  doc/news/changes/minor/20220103DavidWells
Labels: Documentation

#13294 fix a rendering issue with doxygen 1.9.3
  examples/step-69/doc/intro.dox
Labels: Documentation

#13269 Add a test for moving particles in a complex geometry and
  tests/particles/particle_handler_21.cc
  tests/particles/particle_handler_21.with_p4est=true.output
Labels: Mapping, Particles, ready to test

#13287 Introduce ReferenceCell::n_isotropic_children().
  include/deal.II/grid/reference_cell.h
  source/grid/tria.cc
Labels: ready to test

#13291 Use standardized detection idiom
  include/deal.II/base/template_constraints.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/precondition.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/type_traits.h
  tests/matrix_free/matrix_free_type_traits.cc
  tests/matrix_free/matrix_free_type_traits.with_trilinos=true.output
Labels: ready to test

#13124 Manifold for `pipe_junction`.
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator_pipe_junction.cc
  tests/grid/grid_generator_pipe_junction.output
Labels: ready for review, Manifold, ready to test, Meshes

#13298 Minor suggestions for step-55
  examples/step-55/step-55.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#13306 Minor adjustments to the pipe junction geometry.
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator_pipe_junction.cc
Labels: ready to test

#13304 Improve the text of an assertion.
  include/deal.II/numerics/data_out_dof_data.h
Labels: ready to test

#13302 Minor updates to the documentation of GridTools::transform().
  include/deal.II/grid/grid_tools.h
Labels: ready to test

#13303 Rename Triangulation::manifold to Triangulation::manifolds.
  include/deal.II/grid/tria.h
  source/grid/tria.cc
Labels: Triangulation, Manifold, ready to test

#13301 Avoid a couple of references to GeometryInfo.
  source/grid/manifold.cc
Labels: ready to test

#13299 Remove an unnecessary 'using namespace std' declaration.
  source/dofs/dof_renumbering.cc
Labels: ready to test

#13300 Avoid 'using namespace' declarations.
  source/algorithms/timestep_control.cc
  source/grid/manifold.cc
  source/non_matching/quadrature_generator.cc
  source/sundials/arkode.cc
  source/sundials/ida.cc
  source/sundials/kinsol.cc
Labels: ready to test

#13296 Follow-up to is_detected.
  include/deal.II/base/template_constraints.h
Labels: ready to test

#13307 Updates to manifolds classes
  include/deal.II/grid/manifold_lib.h
  source/grid/manifold_lib.cc
Labels: ready to test

#13305 Add a missing assertion.
  include/deal.II/numerics/vector_tools_interpolate.templates.h
Labels: ready to test

#12771 Add Hessian to FE_NedelecSZ
  doc/news/changes/minor/20220128Kinnewig
  include/deal.II/fe/fe_nedelec_sz.h
  source/fe/fe_nedelec_sz.cc
  tests/fe/fe_nedelec_sz_hessian_divergence_theorem.cc
  tests/fe/fe_nedelec_sz_hessian_divergence_theorem.output
Labels: Enhancement, Reviewed and ready to merge, Finite Element, ready to test

#12757 Add a CutFEM tutorial as step-85
  doc/doxygen/images/step-85-active-mesh.svg
  doc/doxygen/images/step-85-background-mesh.svg
  doc/doxygen/images/step-85-ghost-faces.svg
  doc/doxygen/images/step-85-level-set.png
  doc/doxygen/images/step-85-solution.png
  doc/doxygen/references.bib
  doc/doxygen/tutorial/tutorial.h.in
  doc/news/changes/major/20220101SimonSticko
  examples/step-85/CMakeLists.txt
  examples/step-85/doc/builds-on
  examples/step-85/doc/intro.dox
  examples/step-85/doc/kind
  examples/step-85/doc/results.dox
  examples/step-85/doc/tooltip
  examples/step-85/step-85.cc
Labels: Tutorials, ready to test, Non-matching

#13309 Added hp-version for `VectorTools::compute_mean_value()`.
  include/deal.II/numerics/vector_tools_mean_value.h
  include/deal.II/numerics/vector_tools_mean_value.templates.h
  tests/mpi/compute_mean_value_01.cc
  tests/mpi/compute_mean_value_01.with_trilinos=true.mpirun=10.with_p4est=true.output
  tests/mpi/compute_mean_value_01.with_trilinos=true.mpirun=4.with_p4est=true.output
  tests/mpi/compute_mean_value_02.cc
  tests/mpi/compute_mean_value_02.with_trilinos=true.mpirun=10.with_p4est=true.output
  tests/mpi/compute_mean_value_02.with_trilinos=true.mpirun=4.with_p4est=true.output
Labels: hp, ready to test

#13311 FEEval: rename get_is_interior_face() to is_interior_face()
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/fe_evaluation_data.h
Labels: Matrix-free, ready to test

#13272 Switch the consensus algorithms interface to using function objects.
  include/deal.II/base/mpi_consensus_algorithms.h
  include/deal.II/base/mpi_consensus_algorithms.templates.h
  source/base/mpi_consensus_algorithms.cc
Labels: ready to test

#13312 Fix MGTwoLevelTransfer::restrict_and_add()
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
Labels: Bug, Multigrid, ready to test
