Repository dealii/dealii, pull requests merged in 2022-05, with the labels that each got.

#13659 Silence warnings from Sacado in user projects.
  include/deal.II/base/numbers.h
  include/deal.II/base/utilities.h
Labels: Miscellaneous, External libraries, ready to test

#13593 Installation problem with MPI on Windows
  doc/news/changes/minor/20220426DanielSun
  include/deal.II/fe/fe_tools_interpolate.templates.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/grid_tools_cache.h
  include/deal.II/numerics/vector_tools_constraints.h
  include/deal.II/particles/generators.h
Labels: Windows, ready to test

#13644 Added support for CGAL library.
  .github/workflows/linux.yml
  cmake/configure/configure_cgal.cmake
  cmake/modules/FindCGAL.cmake
  doc/doxygen/options.dox.in
  doc/news/changes/major/20220426FederHeltai
  doc/readme.html
  doc/users/cmake_dealii.html
  include/deal.II/base/config.h.in
  include/deal.II/cgal/utilities.h
  tests/cgal/CMakeLists.txt
  tests/cgal/cgal_point_01.cc
  tests/cgal/cgal_point_01.output
Labels: ready for review, Feature, Reviewed and ready to merge, Triangulation, External libraries, ready to test

#13660 Fesystem indexing
  doc/news/changes/minor/20220430DavidWells
  include/deal.II/fe/fe_system.h
  source/fe/fe_system.cc
  tests/fe/fe_system_values.cc
  tests/fe/fe_system_values.output
Labels: Enhancement, Finite Element, ready to test

#13627 Glossary edit for material ids
  doc/doxygen/headers/glossary.h
Labels: Documentation

#13543 remove notes on indentation from documentation
  doc/doxygen/headers/coding_conventions.h
Labels: Documentation

#13628 Add a new renumbering function for data locality with MatrixFree
  doc/news/changes/minor/20220421KronbichlerMunchRoschlaubSashko
  include/deal.II/dofs/dof_renumbering.h
  include/deal.II/matrix_free/matrix_free.h
  source/dofs/dof_renumbering.cc
  source/dofs/dof_renumbering.inst.in
  tests/dofs/dof_renumbering_mf_01.cc
  tests/dofs/dof_renumbering_mf_01.output
  tests/dofs/dof_renumbering_mf_02.cc
  tests/dofs/dof_renumbering_mf_02.with_p4est=true.mpirun=4.output
  tests/dofs/dof_renumbering_mf_03.cc
  tests/dofs/dof_renumbering_mf_03.with_p4est=true.mpirun=3.output
  tests/dofs/dof_renumbering_mf_04.cc
  tests/dofs/dof_renumbering_mf_04.with_p4est=true.mpirun=3.output
  tests/dofs/dof_renumbering_mf_05.cc
  tests/dofs/dof_renumbering_mf_05.with_p4est=true.mpirun=3.output
  tests/matrix_free/parallel_multigrid_interleave_renumber.cc
  tests/matrix_free/parallel_multigrid_interleave_renumber.wih_p4est=true.with_lapack=true.mpirun=2.output
Labels: Matrix-free, ready to test

#13667 Fix some problems with renumbering with no local DoFs
  source/dofs/dof_handler_policy.cc
  source/dofs/number_cache.cc
  tests/fe/fe_nothing_02.cc
  tests/fe/fe_nothing_02.output
  tests/sharedtria/dof_04.cc
  tests/sharedtria/dof_04.with_metis=true.mpirun=3.output
Labels: Bug, ready to test

#13653 Add CGAL::Surface_mesh support
  bundled/boost-1.70.0/include/boost/thread/detail/thread_safety.hpp
  cmake/config/template-arguments.in
  cmake/modules/FindCGAL.cmake
  include/deal.II/cgal/surface_mesh.h
  include/deal.II/cgal/utilities.h
  source/CMakeLists.txt
  source/cgal/CMakeLists.txt
  source/cgal/surface_mesh.cc
  source/cgal/surface_mesh.inst.in
  tests/cgal/cgal_surface_mesh_01.cc
  tests/cgal/cgal_surface_mesh_01.output
Labels: ready for review, ready to test

#13663 MGConstrainedDoFs::add_boundary_indices()
  doc/news/changes/minor/20220502JiaqiZhang
  include/deal.II/multigrid/mg_constrained_dofs.h
  tests/multigrid/constrained_dofs_01.cc
  tests/multigrid/constrained_dofs_01.with_p4est=true.mpirun=1.output
  tests/multigrid/constrained_dofs_01.with_p4est=true.mpirun=3.output
Labels: ready to test

#13665 Modernize c++ header
  doc/doxygen/headers/c++.h
Labels: Documentation, C++14

#13669 First try at detecting CGAL more robustly.
  .github/workflows/linux.yml
  cmake/modules/FindCGAL.cmake
Labels: Build system, External libraries, ready to test

#13666 step-75: added link to external repository.
  examples/step-75/doc/results.dox
Labels: Documentation, Tutorials

#13672 Improve tutorial graph
  doc/doxygen/scripts/steps.pl
  examples/step-12b/doc/builds-on
  examples/step-50/doc/builds-on
  examples/step-51/doc/builds-on
  examples/step-75/doc/builds-on
  examples/step-85/doc/builds-on
Labels: Documentation, Tutorials

#13648 Add DataPostprocessors::BoundaryIds.
  doc/doxygen/headers/glossary.h
  doc/news/changes/minor/20220427Bangerth
  include/deal.II/numerics/data_postprocessor.h
  source/numerics/data_postprocessor.cc
  source/numerics/data_postprocessor.inst.in
  tests/data_out/data_out_complex_postprocessor_03.cc
  tests/data_out/data_out_faces_postprocessor_boundary_id_02.cc
  tests/data_out/data_out_faces_postprocessor_boundary_id_02.output
  tests/data_out/data_out_faces_postprocessor_boundary_id_03.cc
  tests/data_out/data_out_faces_postprocessor_boundary_id_03.output
  tests/data_out/data_out_faces_postprocessor_boundary_id_04.cc
  tests/data_out/data_out_faces_postprocessor_boundary_id_04.output
Labels: Post-processing, ready to test

#13675 Minor edits to the C++ namespace documentation.
  doc/doxygen/headers/c++.h
Labels: Documentation

#13599 Use 64-bit integer for `n_nonzero_elements`.
  doc/news/changes/incompatibilities/20220404Fehling
  include/deal.II/base/types.h
  include/deal.II/lac/petsc_block_sparse_matrix.h
  include/deal.II/lac/petsc_matrix_base.h
  include/deal.II/lac/trilinos_block_sparse_matrix.h
  include/deal.II/lac/trilinos_index_access.h
  include/deal.II/lac/trilinos_sparse_matrix.h
  include/deal.II/lac/trilinos_sparsity_pattern.h
  source/lac/petsc_matrix_base.cc
  source/lac/petsc_parallel_block_sparse_matrix.cc
  source/lac/trilinos_block_sparse_matrix.cc
  source/lac/trilinos_sparsity_pattern.cc
Labels: Linear Algebra, External libraries, ready to test

#13679 Fix tests.
  tests/data_out/data_out_faces_postprocessor_boundary_id.cc
  tests/data_out/data_out_faces_postprocessor_boundary_id.output
  tests/data_out/data_out_faces_postprocessor_boundary_id_02.cc
  tests/data_out/data_out_faces_postprocessor_boundary_id_02.output
  tests/data_out/data_out_faces_postprocessor_boundary_id_03.cc
  tests/data_out/data_out_faces_postprocessor_boundary_id_03.output
  tests/data_out/data_out_faces_postprocessor_boundary_id_04.cc
  tests/data_out/data_out_faces_postprocessor_boundary_id_04.output
Labels: ready to test

#13681 Add LinearAlgebra::distributed::BlockVector::set_ghost_state()
  include/deal.II/lac/la_parallel_block_vector.h
  include/deal.II/lac/la_parallel_block_vector.templates.h
Labels: Reviewed and ready to merge, Linear Algebra, ready to test

#13682 SolverCG: Switch to more common variable names
  include/deal.II/lac/solver_cg.h
  tests/lac/solver.output
  tests/lapack/solver_cg.output
Labels: Reviewed and ready to merge, Linear Algebra, ready to test

#13684 Fix a recently added test
  tests/matrix_free/parallel_multigrid_interleave_renumber.cc
Labels: Reviewed and ready to merge, Tests, ready to test

#13678 Add ReferenceCell::volume() and ::barycenter().
  doc/news/changes/minor/20220504Bangerth
  include/deal.II/grid/reference_cell.h
  tests/grid/reference_cell_type_02.cc
  tests/grid/reference_cell_type_02.output
  tests/grid/reference_cell_type_03.cc
  tests/grid/reference_cell_type_03.output
Labels: ready to test

#13685 Reduce number of instantiations of FEEvaluation template factory
  source/matrix_free/CMakeLists.txt
  source/matrix_free/evaluation_template_factory.cc
  source/matrix_free/evaluation_template_factory_inst10.cc
  source/matrix_free/evaluation_template_factory_inst7.cc
  source/matrix_free/evaluation_template_factory_inst8.cc
  source/matrix_free/evaluation_template_factory_inst9.cc
Labels: Matrix-free, ready to test

#13661 Cgal triangulation
  doc/news/changes/major/20220426FederHeltai
  include/deal.II/cgal/triangulation.h
  tests/cgal/cgal_triangulation_01.cc
  tests/cgal/cgal_triangulation_01.output
  tests/cgal/cgal_triangulation_02.cc
  tests/cgal/cgal_triangulation_02.output
  tests/cgal/cgal_triangulation_03.cc
  tests/cgal/cgal_triangulation_03.output
  tests/cgal/cgal_triangulation_04.cc
  tests/cgal/cgal_triangulation_04.output
  tests/cgal/cgal_triangulation_05.cc
  tests/cgal/cgal_triangulation_05.output
Labels: ready for review, Reviewed and ready to merge, ready to test

#13691 Rename some face batches
  include/deal.II/matrix_free/face_setup_internal.h
  include/deal.II/matrix_free/matrix_free.h
Labels: Matrix-free, ready to test

#13688 Fix FEEvaluation::gather_evaluate() for user-defined batches
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Bug, Matrix-free, ready to test

#13697 Add changelog for MappingQ
  doc/news/changes/incompatibilities/20210710MartinKronbichler
Labels: Documentation

#13695 Fix format of table
  include/deal.II/fe/fe_base.h
Labels: Documentation

#13692 Implement ReferenceCell::face_to_cell_lines() for pyramids and wedges
  include/deal.II/grid/reference_cell.h
Labels: ready to test, simplices

#13690 Improve asserts in MF/FEEval regarding FENothing
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/util.h
Labels: Matrix-free, ready to test

#13664 Cgal surface to deal.II triangulation
  doc/news/changes/major/20220426FederHeltai
  include/deal.II/cgal/triangulation.h
  source/grid/tria.cc
  tests/cgal/cgal_surface_triangulation_01.cc
  tests/cgal/cgal_surface_triangulation_01.output
  tests/cgal/cgal_surface_triangulation_02.cc
  tests/cgal/cgal_surface_triangulation_02.output
  tests/cgal/input_grids/torus_quad.off
  tests/cgal/input_grids/tripod.off
Labels: ready for review, ready to test

#13414 Introduce free functions for consensus algorithms.
  include/deal.II/base/mpi_consensus_algorithms.h
  include/deal.II/fe/fe_tools_extrapolate.templates.h
  source/base/mpi.cc
  source/grid/grid_tools.cc
  source/grid/tria_description.cc
  tests/base/consensus_algorithm_01.cc
Labels: ready to test

#13683 Implement flexible variant of conjugate gradient method
  doc/news/changes/minor/20220506Kronbichler
  include/deal.II/lac/solver_cg.h
  tests/lac/solver_cg_flexible.cc
  tests/lac/solver_cg_flexible.output
Labels: Linear Algebra, ready to test

#13696 Add GenericDoFsPerObject::generate()
  include/deal.II/fe/fe_base.h
  tests/fe/generic_dofs_per_object_01.cc
  tests/fe/generic_dofs_per_object_01.output
Labels: ready to test, simplices

#13702 Adjust test output for new FE_RaviartThomasNodal
  tests/trilinos/mg_transfer_prebuilt_01.with_p4est=true.mpirun=1.output
Labels: Tests, ready to test

#13701 Fix test failure: Close the right AffineConstraints object
  tests/mappings/mapping_q_eulerian_14.cc
Labels: Reviewed and ready to merge, Tests, ready to test

#13657 Add class NonMatching::FEInterfaceValues
  doc/doxygen/images/non_matching_fe_interface_values.svg
  include/deal.II/non_matching/fe_values.h
  source/non_matching/fe_values.cc
  source/non_matching/fe_values.inst.in
  tests/non_matching/fe_interface_values.cc
  tests/non_matching/fe_interface_values.output
  tests/non_matching/fe_interface_values_non_standard_meshes.cc
  tests/non_matching/fe_interface_values_non_standard_meshes.output
Labels: ready to test, Non-matching

#13704 SolverFlexibleCG: Slightly improve documentation
  include/deal.II/lac/solver_cg.h
Labels: Documentation

#13707 Add more tests.
  tests/grid/reference_cell_type_02_q.cc
  tests/grid/reference_cell_type_02_q.output
  tests/grid/reference_cell_type_03_q.cc
  tests/grid/reference_cell_type_03_q.output
Labels: ready to test, simplices

#13699 Skip default values in get_coarse_mesh_description().
  doc/news/changes/incompatibilities/20220509DavidWells
  source/grid/grid_tools.cc
Labels: Triangulation, ready to test

#13709 Add two asserts in NonMatching::MeshClassifier.
  source/non_matching/mesh_classifier.cc
  tests/non_matching/mesh_classifier.cc
Labels: ready to test

#13706 Add ReferenceCell::get_midpoint_quadrature().
  doc/news/changes/minor/20220504Bangerth-b
  include/deal.II/base/quadrature_lib.h
  include/deal.II/grid/reference_cell.h
  tests/grid/reference_cell_type_02_midpoint.cc
  tests/grid/reference_cell_type_02_midpoint.output
  tests/grid/reference_cell_type_03_midpoint.cc
  tests/grid/reference_cell_type_03_midpoint.output
Labels: ready to test

#13710 Restrict feinterface/stokes test
  tests/feinterface/stokes.with_umfpack=on.output
Labels: ready to test

#13700 Correctly size CellData::vertices in GridTools.
  source/grid/grid_tools.cc
  tests/grid/get_coarse_mesh_description_01.cc
  tests/grid/get_coarse_mesh_description_01.output
Labels: Reviewed and ready to merge, Triangulation, ready to test

#13713 Server move: Update server URLs
  CTestConfig.cmake
  README.md
  contrib/utilities/query_testsuite
  doc/developers/testsuite.html
  examples/step-69/doc/intro.dox
  examples/step-69/doc/results.dox
Labels: Documentation, Reviewed and ready to merge

#13711 Fix the nodal renumbering tests.
  tests/dofs/nodal_renumbering_01.cc
  tests/dofs/nodal_renumbering_01.mpirun=2.with_p4est=true.debug.output
  tests/dofs/nodal_renumbering_01.mpirun=2.with_p4est=true.output
  tests/dofs/nodal_renumbering_01.mpirun=2.with_p4est=true.release.output
  tests/dofs/nodal_renumbering_01.mpirun=3.with_p4est=true.debug.output
  tests/dofs/nodal_renumbering_01.mpirun=3.with_p4est=true.output
  tests/dofs/nodal_renumbering_01.mpirun=3.with_p4est=true.release.output
  tests/dofs/nodal_renumbering_01.with_p4est=true.debug.output
  tests/dofs/nodal_renumbering_01.with_p4est=true.output
  tests/dofs/nodal_renumbering_01.with_p4est=true.release.output
Labels: Tests, ready to test

#13715 changelog news entry
  doc/news/changes/minor/20220510SeanIngimarson
Labels: Documentation

#13714 Fix test simplex/step-55.
  include/deal.II/lac/trilinos_sparse_matrix.h
Labels: ready to test

#13631 Fixes CMake version > 3.12 python-binding build failure
  contrib/python-bindings/CMakeLists.txt
Labels: Reviewed and ready to merge, ready to test

#13716 Adjust changelog for 64bit nonzeros.
  doc/news/changes/incompatibilities/20220404Fehling
  source/lac/petsc_matrix_base.cc
Labels: Documentation

#12463 Improve asserts in parallel::distributed::SolutionTransfer
  doc/news/changes/minor/20220225Munch
  include/deal.II/base/partitioner.templates.h
  include/deal.II/dofs/dof_accessor.h
  source/distributed/solution_transfer.cc
  source/dofs/dof_accessor_set.cc
  source/dofs/dof_accessor_set.inst.in
  source/numerics/solution_transfer.cc
  tests/codim_one/solution_transfer_01.cc
Labels: ready to test

#13577 Use PIMPL in our muParser implementation.
  bundled/muparser_v2_3_3/CMakeLists.txt
  bundled/muparser_v2_3_3/include/muParser.h
  bundled/muparser_v2_3_3/include/muParserBase.h
  bundled/muparser_v2_3_3/include/muParserBytecode.h
  bundled/muparser_v2_3_3/include/muParserCallback.h
  bundled/muparser_v2_3_3/include/muParserDef.h
  bundled/muparser_v2_3_3/include/muParserError.h
  bundled/muparser_v2_3_3/include/muParserFixes.h
  bundled/muparser_v2_3_3/include/muParserInt.h
  bundled/muparser_v2_3_3/include/muParserStack.h
  bundled/muparser_v2_3_3/include/muParserTemplateMagic.h
  bundled/muparser_v2_3_3/include/muParserTest.h
  bundled/muparser_v2_3_3/include/muParserToken.h
  bundled/muparser_v2_3_3/include/muParserTokenReader.h
  bundled/muparser_v2_3_3/src/muParser.cpp
  bundled/muparser_v2_3_3/src/muParserBase.cpp
  bundled/muparser_v2_3_3/src/muParserBytecode.cpp
  bundled/muparser_v2_3_3/src/muParserCallback.cpp
  bundled/muparser_v2_3_3/src/muParserError.cpp
  bundled/muparser_v2_3_3/src/muParserInt.cpp
  bundled/muparser_v2_3_3/src/muParserTest.cpp
  bundled/muparser_v2_3_3/src/muParserTokenReader.cpp
  doc/news/changes/minor/20220325DavidWells
  include/deal.II/base/function_parser.h
  include/deal.II/base/tensor_function_parser.h
  source/base/function_parser.cc
  source/base/tensor_function_parser.cc
Labels: Reviewed and ready to merge, External libraries, ready to test

#13063 Implement FEFaceEvaluation::evaluate() for ECL/unstructured meshes
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/mapping_info.templates.h
  tests/matrix_free/ecl.h
  tests/matrix_free/ecl_01.cc
  tests/matrix_free/ecl_01.with_p4est=true.mpirun=1.output
  tests/matrix_free/ecl_03.cc
  tests/matrix_free/ecl_04.cc
Labels: Matrix-free, ready to test

#13698 Add a data-locality-optimized iteration scheme to SolverCG
  doc/doxygen/references.bib
  doc/news/changes/minor/20220509Kronbichler
  include/deal.II/lac/diagonal_matrix.h
  include/deal.II/lac/solver_cg.h
  tests/lac/solver.output
  tests/lac/solver_cg_interleave.cc
  tests/lac/solver_cg_interleave.output
  tests/lapack/solver_cg.output
  tests/matrix_free/solver_cg_interleave.cc
  tests/matrix_free/solver_cg_interleave.with_p4est=true.mpirun=3.output
Labels: Matrix-free, Linear Algebra, ready to test

#13718 Fix master face_no
  include/deal.II/matrix_free/evaluation_kernels.h
Labels: Bug, High Priority :warning:, Matrix-free, ready to test

#13719 Clean up delete_duplicated_vertices() a little.
  source/grid/grid_tools.cc
Labels: Miscellaneous, ready to test

#13720 Rename the template type arguments of the consensus algorithms.
  include/deal.II/base/mpi_consensus_algorithms.h
  include/deal.II/base/mpi_consensus_algorithms.templates.h
Labels: ready to test

#13725 MF: fix if all cells of a process are FE_Nothing
  source/matrix_free/dof_info.cc
Labels: Bug, Matrix-free, ready to test

#13724 Choose common SFINAE detection path for PreconditionChebyshev
  include/deal.II/lac/precondition.h
Labels: Linear Algebra, ready to test

#13723 Fix three bugs in interleaved CG method
  include/deal.II/lac/solver_cg.h
  include/deal.II/matrix_free/matrix_free.h
  tests/matrix_free/parallel_multigrid_interleave.cc
  tests/matrix_free/parallel_multigrid_interleave_renumber.cc
  tests/matrix_free/parallel_multigrid_interleave_renumber.wih_p4est=true.with_lapack=true.mpirun=2.output
  tests/matrix_free/parallel_multigrid_interleave_renumber.with_p4est=true.with_lapack=true.mpirun=2.output
Labels: Linear Algebra, ready to test

#13728 New test for MatrixFree::reinit with empty procs
  tests/matrix_free/fe_nothing_01.cc
  tests/matrix_free/fe_nothing_01.with_p4est=true.mpirun=3.output
Labels: Reviewed and ready to merge, Matrix-free, Tests, ready to test

#13722 Replace std::vector<RequestType> by RequestType in consensus algorithms. Same for AnswerType.
  include/deal.II/base/mpi_compute_index_owner_internal.h
  include/deal.II/base/mpi_consensus_algorithms.h
  include/deal.II/base/mpi_consensus_algorithms.templates.h
  include/deal.II/fe/fe_tools_extrapolate.templates.h
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/matrix_free/matrix_free.templates.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  source/base/mpi.cc
  source/base/mpi_compute_index_owner_internal.cc
  source/base/mpi_consensus_algorithms.cc
  source/base/mpi_noncontiguous_partitioner.cc
  source/base/partitioner.cc
  source/distributed/repartitioning_policy_tools.cc
  source/grid/grid_tools.cc
  source/grid/tria_description.cc
  source/matrix_free/vector_data_exchange.cc
  source/multigrid/mg_tools.cc
  tests/base/consensus_algorithm_01.cc
Labels: ready to test

#13729 Set is_tensor_product_flag in Quadrature::initialize(..)
  source/base/quadrature.cc
Labels: Bug, Reviewed and ready to merge, ready to test

#13731 Simplify the type used by ConsensusAlgorithm in compute_n_point_to_point_communications().
  source/base/mpi.cc
Labels: ready to test

#13733 Avoid double packing/unpacking for CA algorithms.
  include/deal.II/fe/fe_tools_extrapolate.templates.h
  source/grid/grid_tools.cc
  source/grid/tria_description.cc
  source/multigrid/mg_tools.cc
Labels: ready to test

#13705 Create coarse mesh out of a CGAL::Surface_mesh
  cmake/config/template-arguments.in
  include/deal.II/cgal/utilities.h
  tests/cgal/cgal_surface_mesh_02.cc
  tests/cgal/cgal_surface_mesh_02.output
  tests/cgal/input_grids/cube.off
  tests/cgal/input_grids/tetrahedron.off
Labels: ready to test

#13712 Restrict permissions for GITHUB_TOKEN.
  .github/workflows/docker.yml
  .github/workflows/indent.yml
  .github/workflows/linux.yml
  .github/workflows/osx.yml
  .github/workflows/windows.yml
Labels: Infrastructure

#13732 CMake: remove -Wl,--as-needed flag setup
  cmake/config/CMakeLists.txt
  cmake/macros/macro_check_compiler_setup.cmake
  cmake/setup_compiler_flags_gnu.cmake
  cmake/setup_compiler_flags_intel.cmake
Labels: Build system, ready to test

#13736 Fix some GCC-12 warnings.
  include/deal.II/base/config.h.in
  source/distributed/fully_distributed_tria.cc
  source/fe/fe_rt_bubbles.cc
Labels: Miscellaneous, ready to test

#13738 Fix typo w_cycle
  include/deal.II/lac/trilinos_precondition.h
Labels: Reviewed and ready to merge, ready to test

#13737 LA:d:V: fix size in the case of shared memory
  include/deal.II/lac/la_parallel_vector.templates.h
Labels: Bug, Linear Algebra, Parallel distributed, ready to test

#13739 Added missing headers to failing test.
  tests/sharedtria/refine_and_coarsen_01.cc
Labels: Reviewed and ready to merge, Tests, ready to test

#13717 Corefine and compute boolean operations in CGAL
  doc/doxygen/images/boolean_difference.png
  doc/doxygen/images/boolean_intersection.png
  doc/doxygen/images/boolean_union.png
  doc/doxygen/images/corefinement.png
  doc/doxygen/images/hedra_cube.png
  include/deal.II/cgal/utilities.h
  tests/cgal/cgal_surface_mesh_02.cc
  tests/cgal/cgal_surface_mesh_03.cc
  tests/cgal/cgal_surface_mesh_03.output
  tests/cgal/input_grids/hedra.off
Labels: ready for review, External libraries, ready to test

#13730 Add another variant for multigrid test
  tests/matrix_free/parallel_multigrid_interleave_renumber.with_p4est=true.with_lapack=true.mpirun=2.output.2
Labels: Tests, ready to test

#13742 Fix a typo.
  contrib/utilities/indent_common.sh
Labels: Documentation

#13746 base/tensor.h: Fix a typo
  include/deal.II/base/tensor.h
Labels: Reviewed and ready to merge

#13744 TransfiniteInterpolationManifold: fix codimension one case
  include/deal.II/fe/mapping_q_internal.h
  source/grid/manifold_lib.cc
  tests/manifold/transfinite_manifold_12.cc
  tests/manifold/transfinite_manifold_12.debug.output
Labels: Manifold, ready to test

#13747 Step-75: use well-formed deleter
  examples/step-75/step-75.cc
Labels: Bug, ready to test

#13749 Rename an exception
  source/non_matching/mesh_classifier.cc
Labels: Reviewed and ready to merge, ready to test, Non-matching

#13748 Assert that the incoming cell is Cartesian in MappingCartesian
  source/fe/mapping_cartesian.cc
Labels: Reviewed and ready to merge, Mapping, ready to test

#13750 Update petsc test output.
  tests/petsc/reinit_preconditioner_01.with_petsc_with_hypre=true.with_64bit_indices=off.mpirun=3.output
Labels: Tests, ready to test

#13756 MatrixFree: Add instantiation for ConstraintValues::insert_entries
  source/matrix_free/dof_info.cc
Labels: Bug, ready to test

#13755 Make multigrid test more robust
  tests/matrix_free/parallel_multigrid_interleave.cc
  tests/matrix_free/parallel_multigrid_interleave.with_p4est=true.with_lapack=true.mpirun=2.output
  tests/matrix_free/parallel_multigrid_interleave_renumber.cc
  tests/matrix_free/parallel_multigrid_interleave_renumber.with_p4est=true.with_lapack=true.mpirun=2.output
  tests/matrix_free/parallel_multigrid_interleave_renumber.with_p4est=true.with_lapack=true.mpirun=2.output.2
Labels: Multigrid, Tests, ready to test

#13752 Fix compute_index_owner_01.
  tests/mpi/compute_index_owner_01.cc
Labels: Tests, ready to test

#13735 CGAL C3T3 to deal.II Triangulation.
  include/deal.II/cgal/triangulation.h
  tests/cgal/cgal_triangulation_06.cc
  tests/cgal/cgal_triangulation_06.output
Labels: ready for review, Triangulation, External libraries, ready to test

#13741 Fix sundials 6 tests, part 1
  include/deal.II/sundials/arkode.h
  include/deal.II/sundials/ida.h
  include/deal.II/sundials/kinsol.h
  include/deal.II/sundials/n_vector.h
  include/deal.II/sundials/n_vector.templates.h
  include/deal.II/sundials/sunlinsol_wrapper.h
  source/sundials/arkode.cc
  tests/sundials/n_vector.cc
Labels: External libraries, ready to test

#13758 Add a comment explaining BOOST_DEFINITIONS
  cmake/configure/configure_2_boost.cmake
Labels: Build system, Reviewed and ready to merge, ready to test

#13757 CMake: Avoid a CMake policy warning
  CMakeLists.txt
Labels: ready to test

#13745 Avoid doing extra TLS lookups in FunctionParser.
  doc/news/changes/minor/20220516DavidWells
  include/deal.II/base/function_parser.h
  include/deal.II/base/tensor_function_parser.h
  source/base/function_parser.cc
  source/base/tensor_function_parser.cc
Labels: Enhancement, ready to test

#13760 Test robustness2
  tests/matrix_free/parallel_multigrid_interleave.cc
  tests/matrix_free/parallel_multigrid_interleave_renumber.cc
  tests/matrix_free/solver_cg_interleave.cc
  tests/matrix_free/solver_cg_interleave.with_p4est=true.mpirun=3.output
Labels: Tests, ready to test

#13761 Properly indent a cmake command.
  doc/doxygen/tutorial/CMakeLists.txt
Labels: ready to test

#13762 Use std::call_once() instead of hand-rolling a solution.
  source/base/multithread_info.cc
Labels: Reviewed and ready to merge, ready to test

#13751 Check for range of function calls in bfgs tests.
  tests/optimization/bfgs_05.cc
  tests/optimization/bfgs_05.output
  tests/optimization/bfgs_05b.cc
  tests/optimization/bfgs_05b.output
Labels: Tests, ready to test

#13759 CMake: Do not configure CGAL with bundled boost
  cmake/configure/configure_cgal.cmake
  cmake/modules/FindCGAL.cmake
Labels: Bug, Build system, ready to test

#13763 Fix compile error of test on certain compilers
  tests/matrix_free/solver_cg_interleave.cc
Labels: Reviewed and ready to merge, Tests, ready to test

#13754 Convert a deal.II tria to a CGAL::Surface_mesh
  include/deal.II/cgal/surface_mesh.h
  include/deal.II/cgal/utilities.h
  source/cgal/surface_mesh.cc
  source/cgal/surface_mesh.inst.in
  tests/cgal/cgal_surface_mesh_01.output
  tests/cgal/cgal_surface_mesh_04.cc
  tests/cgal/cgal_surface_mesh_04.output
  tests/cgal/cgal_surface_mesh_05.cc
  tests/cgal/cgal_surface_mesh_05.output
Labels: ready for review, Triangulation, External libraries, ready to test

#13770 Minor code updates to create_right_hand_side
  include/deal.II/numerics/vector_tools_rhs.templates.h
Labels: Enhancement, ready to test

#13766 Implement pyramid volume and fix wedge volume.
  source/grid/grid_tools_nontemplates.cc
  tests/simplex/cell_measure_01.cc
  tests/simplex/cell_measure_01.output
Labels: Reviewed and ready to merge, ready to test, simplices

#13765 Remove std::abs() from the tet volume calculation.
  source/grid/grid_tools.cc
  source/grid/grid_tools_nontemplates.cc
  tests/simplex/grid_in_msh.cc
  tests/simplex/grid_in_msh.output
  tests/simplex/grid_in_msh/tet_half_twisted.msh
Labels: Reviewed and ready to merge, ready to test, simplices

#13721 step-40: update IO section
  examples/step-40/step-40.cc
Labels: Tutorials, ready to test

#13785 Add an exception for commits from dependabot.
  contrib/utilities/indent_common.sh
Labels: Infrastructure

#13783 TBB oneAPI: make global_control object static
  source/base/multithread_info.cc
  tests/multithreading/threads_01.cc
  tests/multithreading/threads_01.output
Labels: ready to test

#13611 embed BigMPICompat library
  include/deal.II/base/mpi_large_count.h
  source/base/mpi.cc
Labels: Reviewed and ready to merge, Parallel distributed, ready to test

#13789 Clearify LA::d::BlockVector::reinit input argument
  include/deal.II/lac/la_parallel_block_vector.h
  include/deal.II/lac/la_parallel_block_vector.templates.h
Labels: Reviewed and ready to merge, Linear Algebra, ready to test

#13795 Add some missing MPI boolean instantiations.
  source/base/mpi.cc
Labels: Miscellaneous, ready to test

#13784 Optimize pack()/unpack() for std::vector<T> with trivially copyable T.
  doc/news/changes/minor/20220522Bangerth
  examples/step-47/doc/intro.dox
  include/deal.II/base/utilities.h
  include/deal.II/lac/utilities.h
Labels: ready to test

#13792 PreconditionChebyshev: Implement power iteration for eigenvalue estimate
  doc/news/changes/minor/20220523Kronbichler
  include/deal.II/lac/precondition.h
  tests/lac/precondition_chebyshev_03.with_lapack=true.output
  tests/lac/precondition_chebyshev_06.cc
  tests/lac/precondition_chebyshev_06.output
Labels: Linear Algebra, ready to test

#13799 Fix compilation of Utilities::pack with std::vector<bool>
  include/deal.II/base/utilities.h
Labels: Bug, High Priority :warning:, Reviewed and ready to merge, ready to test

#13797 Fix bug in FEEvaluation without vectorization
  include/deal.II/matrix_free/evaluation_kernels.h
Labels: Bug, Matrix-free, ready to test

#13796 Fix two tests with vectorization disabled
  include/deal.II/lac/diagonal_matrix.h
  tests/matrix_free/constraint_info_01.cc
  tests/matrix_free/constraint_info_01.output
  tests/matrix_free/solver_cg_interleave.cc
Labels: Tests, ready to test

#13803 Fix some miscellaneous typos.
  examples/step-12/step-12.cc
  include/deal.II/fe/fe_simplex_p_bubbles.h
Labels: Documentation

#13791 Reduce cost to set up dictionary for compute_index_owner
  include/deal.II/base/mpi_compute_index_owner_internal.h
  source/base/mpi_compute_index_owner_internal.cc
Labels: Reviewed and ready to merge, Parallel distributed, ready to test

#13786 Fix ARKODE for SUNDIALS 6.
  source/sundials/arkode.cc
  tests/sundials/arkode_08.cc
Labels: External libraries, ready to test

#13788 Kinsol sundials 6
  source/sundials/kinsol.cc
Labels: External libraries, ready to test

#13810 Assert reference cell is hypercube in Discrete*QuadratureGenerator
  source/non_matching/quadrature_generator.cc
Labels: Reviewed and ready to merge, ready to test, Non-matching

#13809 Adjust output of tests using PreconditionChebyshev
  tests/matrix_free/parallel_multigrid.with_p4est=true.with_trilinos=true.with_lapack=true.mpirun=3.output
  tests/matrix_free/parallel_multigrid.with_p4est=true.with_trilinos=true.with_lapack=true.mpirun=7.output
  tests/matrix_free/parallel_multigrid_02.with_p4est=true.with_trilinos=true.with_lapack=true.mpirun=3.output
  tests/matrix_free/parallel_multigrid_02.with_p4est=true.with_trilinos=true.with_lapack=true.mpirun=7.output
  tests/matrix_free/parallel_multigrid_interleave.with_p4est=true.with_lapack=true.mpirun=2.output
  tests/matrix_free/parallel_multigrid_interleave_renumber.with_p4est=true.with_lapack=true.mpirun=2.output
Labels: Tests

#13800 Slightly simplify setup of partitioners for global cell ids
  source/distributed/tria_base.cc
Labels: Parallel distributed, ready to test

#13813 Utilities: Fix compile error on certain compilers
  include/deal.II/base/utilities.h
Labels: Miscellaneous, ready to test

#13802 Avoid CellDataTransferBuffer in GridTools::exchange_cell_data_to_ghosts
  include/deal.II/grid/grid_tools.h
Labels: Parallel distributed, ready to test

#13798 Provide function to evaluate polynomial on array of positions
  include/deal.II/base/polynomial.h
  include/deal.II/matrix_free/tensor_product_kernels.h
Labels: Finite Element, ready to test

#13811 Optimize Utilities::pack for std::vector<std::vector<trivial>>
  include/deal.II/base/utilities.h
Labels: Miscellaneous, ready to test

#13812 Remove unnecessary MPI barriers
  source/dofs/dof_handler_policy.cc
Labels: Parallel distributed, ready to test

#13815 ParameterHandler::print_parameters(): Demangle JSON
  doc/news/changes/incompatibilities/20220525SchreterMunch
  source/base/parameter_handler.cc
  tests/parameter_handler/parameter_acceptor_09.output
  tests/parameter_handler/parameter_handler_27.output
  tests/parameter_handler/parameter_handler_28.output
  tests/parameter_handler/parameter_handler_read_json.output
  tests/parameter_handler/parameter_handler_write_json.output
Labels: ready to test

#13768 Consensus Algorithms: Move template functions into .h file.
  include/deal.II/base/mpi_consensus_algorithms.h
  include/deal.II/base/mpi_consensus_algorithms.templates.h
  include/deal.II/fe/fe_tools_extrapolate.templates.h
  source/base/CMakeLists.txt
  source/base/mpi.cc
  source/base/mpi_compute_index_owner_internal.cc
  source/base/mpi_consensus_algorithms.cc
  source/base/mpi_noncontiguous_partitioner.cc
  source/base/mpi_remote_point_evaluation.cc
  source/base/partitioner.cc
  source/grid/grid_tools.cc
  source/grid/tria_description.cc
  source/matrix_free/vector_data_exchange.cc
  source/multigrid/mg_tools.cc
Labels: Reviewed and ready to merge, ready to test

#13769 Deprecate ConsensusAlgorithms::AnonymousProcess.
  include/deal.II/base/mpi_consensus_algorithms.h
Labels: Reviewed and ready to merge, Parallel distributed, ready to test

#13512 Update constant_modes doc
  include/deal.II/lac/trilinos_precondition.h
Labels: Documentation

#13831 Provide a defaulted copy operator.
  include/deal.II/meshworker/copy_data.h
Labels: ready to test

#13825 Fix the function declaration a doc string is attached to.
  include/deal.II/base/mpi_consensus_algorithms.h
Labels: Reviewed and ready to merge, Parallel distributed, ready to test

#13827 CMake: Skip expensive boost test
  cmake/configure/configure_2_boost.cmake
Labels: Build system, Reviewed and ready to merge

#13829 Remove some unneeded header inclusions
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/hanging_nodes_internal.h
Labels: Reviewed and ready to merge, ready to test

#13824 Augment documentation of the consensus algorithm free functions.
  include/deal.II/base/mpi_consensus_algorithms.h
Labels: ready to test

#12807 Tutorial: Time-harmonic Maxwell solver with perfectly matched layer
  doc/doxygen/references.bib
  examples/step-81/CMakeLists.txt
  examples/step-81/doc/builds-on
  examples/step-81/doc/intro.dox
  examples/step-81/doc/kind
  examples/step-81/doc/results.dox
  examples/step-81/doc/tooltip
  examples/step-81/parameters.prm
  examples/step-81/step-81.cc
Labels: ready for review, Tutorials, ready to test

#13823 CMake: Make configure file naming consistent
  cmake/configure/configure_00_threads.cmake
  cmake/configure/configure_10_cuda.cmake
  cmake/configure/configure_10_lapack.cmake
  cmake/configure/configure_10_mpi.cmake
  cmake/configure/configure_10_taskflow.cmake
  cmake/configure/configure_10_tbb.cmake
  cmake/configure/configure_10_zlib.cmake
  cmake/configure/configure_20_boost.cmake
  cmake/configure/configure_20_ginkgo.cmake
  cmake/configure/configure_20_metis.cmake
  cmake/configure/configure_20_trilinos.cmake
  cmake/configure/configure_20_umfpack.cmake
  cmake/configure/configure_30_kokkos.cmake
  cmake/configure/configure_30_petsc.cmake
  cmake/configure/configure_50_adolc.cmake
  cmake/configure/configure_50_arborx.cmake
  cmake/configure/configure_50_arpack.cmake
  cmake/configure/configure_50_assimp.cmake
  cmake/configure/configure_50_cgal.cmake
  cmake/configure/configure_50_complex_values.cmake
  cmake/configure/configure_50_gmsh.cmake
  cmake/configure/configure_50_gsl.cmake
  cmake/configure/configure_50_hdf5.cmake
  cmake/configure/configure_50_muparser.cmake
  cmake/configure/configure_50_opencascade.cmake
  cmake/configure/configure_50_p4est.cmake
  cmake/configure/configure_50_scalapack.cmake
  cmake/configure/configure_50_slepc.cmake
  cmake/configure/configure_50_sundials.cmake
  cmake/configure/configure_50_symengine.cmake
  cmake/configure/configure_50_vectorization.cmake
Labels: Build system, Reviewed and ready to merge

#13832 Minor updates to a few changelog entries.
  doc/news/changes/minor/20210819Bangerthc
  doc/news/changes/minor/20211115Bangerth-c
  doc/news/changes/minor/20220421KronbichlerMunchRoschlaubSashko
  doc/news/changes/minor/20220426DanielSun
Labels: Documentation

#13826 Consensus algorithm specialization for the case where no answer is requested.
  include/deal.II/base/mpi_consensus_algorithms.h
  include/deal.II/fe/fe_tools_extrapolate.templates.h
  source/grid/tria_description.cc
Labels: Reviewed and ready to merge, Parallel distributed, ready to test

#13773 Refactor function parser
  include/deal.II/base/function_parser.h
  include/deal.II/base/mu_parser_internal.h
  include/deal.II/base/tensor_function_parser.h
  source/base/CMakeLists.txt
  source/base/function_parser.cc
  source/base/mu_parser_internal.cc
  source/base/mu_parser_internal.inst.in
  source/base/tensor_function_parser.cc
Labels: Enhancement, ready to test

#13805 Fix test dependencies
  source/non_matching/mesh_classifier.cc
  tests/base/utilities_pack_unpack_06.cc
  tests/data_out/data_out_complex_05.with_complex_values=on.output
  tests/data_out/data_out_complex_05_tensor.with_complex_values=on.output
  tests/data_out/data_out_complex_06.with_complex_values=on.output
  tests/data_out/data_out_postprocessor_tensor_02.with_zlib=off.output
  tests/data_out/data_out_postprocessor_tensor_02.with_zlib=on.output
  tests/lac/packaged_operation_01a.with_complex=on.output
  tests/meshworker/scratch_data_08.with_umfpack=on.output
  tests/non_matching/fe_interface_values.with_lapack=on.output
  tests/non_matching/fe_interface_values_non_standard_meshes.with_lapack=on.output
  tests/non_matching/fe_values.with_lapack=on.output
  tests/non_matching/mesh_classifier.with_lapack=on.output
  tests/simplex/data_out_write_vtu_01.with_zlib=off.output
  tests/simplex/data_out_write_vtu_01.with_zlib=on.output
Labels: Tests, ready to test

#13833 Deprecate GridTools::CellDataTransferBuffer
  include/deal.II/grid/grid_tools.h
Labels: Reviewed and ready to merge, ready to test

#13834 Generalize FETools::Compositing::multiply_dof_numbers()
  include/deal.II/fe/fe_base.h
  include/deal.II/fe/fe_tools.templates.h
  source/fe/fe_data.cc
  tests/fe/generic_dofs_per_object_01.output
Labels: ready to test

#13841 Intel 18: more constexpr problems
  source/grid/grid_generator_pipe_junction.cc
Labels: High Priority :warning:, Compiler, ready to test

#13839 Fix petsc/solver_08 for petsc 3.17.1
  tests/petsc/solver_08.cc
  tests/petsc/solver_08.output
Labels: Tests, External libraries, ready to test

#13840 Fix test output for trilinos 13.2.0
  tests/rol/vector_adaptor_no_ghost_01.mpirun=1.output.1
  tests/rol/vector_adaptor_no_ghost_01.mpirun=5.output.1
  tests/rol/vector_adaptor_with_ghost_01.mpirun=10.output.1
  tests/rol/vector_adaptor_with_ghost_01.mpirun=7.output.1
Labels: Tests, External libraries, ready to test

#13843 Fix FESystem::initialize for pyramids/wedges
  source/fe/fe_system.cc
Labels: ready to test

#13838 Intel 18: static constexpr bool
  include/deal.II/lac/la_parallel_vector.h
Labels: High Priority :warning:, Compiler, ready to test

#13844 Suppress some unused variable warnings when we don't have muParser.
  source/base/mu_parser_internal.cc
Labels: Miscellaneous, ready to test

#13845 Introduce DEAL_II_OPENCASCADE_VERSION_GTE
  cmake/modules/FindOPENCASCADE.cmake
  doc/doxygen/options.dox.in
  include/deal.II/base/config.h.in
  source/opencascade/manifold_lib.cc
  source/opencascade/utilities.cc
Labels: Build system, External libraries, ready to test

#13851 Use LargeCount MPI_write_at and MPI_read_at functions
  source/distributed/tria_base.cc
Labels: Parallel distributed, ready to test

#13673 Upgrade write_vtu_in_parallel based on mpi large IO update
  source/base/data_out_base.cc
Labels: High Priority :warning:, ready to test

#13852 missing changelog entries
  doc/news/changes/major/20220529tjhei
  doc/news/changes/minor/20220529tjhei
Labels: Documentation, Reviewed and ready to merge

#13847 Add a changelog for the new CutFEM functionality in NonMatching.
  doc/news/changes/major/20220529StickoBergbauerKronbichler
Labels: Documentation, Reviewed and ready to merge
