Repository dealii/dealii, pull requests merged in 2022-07, with the labels that each got.

#14083 Fix bug when we have no line dofs in assignment/renumbering of face mg dofs
  source/dofs/dof_handler_policy.cc
Labels: DoFs, ready to test

#14076 Use faster data structure to compute matrix-free renumbering
  source/dofs/dof_renumbering.cc
Labels: Matrix-free, DoFs, ready to test

#14081 Add function to extract raw coarsen flags
  source/grid/tria.cc
Labels: Triangulation, ready to test

#14085 FEEvaluationBase::read_write_operation case 3: enable masking
  include/deal.II/matrix_free/fe_evaluation.h
Labels: ready to test

#14087 doxygen: fix errors in formulas
  examples/step-75/doc/intro.dox
  include/deal.II/non_matching/quadrature_generator.h
Labels: Documentation, ready to test

#14082 Restructure execute_refinement(Triangulation<3, spacedim>&)
  source/grid/tria.cc
Labels: Triangulation, ready to test

#14080 Use get_line_indices_of_cell in DoFHandlerPolicy
  source/dofs/dof_handler_policy.cc
Labels: DoFs, ready to test

#14055 Add cross-references for global indices
  include/deal.II/distributed/tria_base.h
  include/deal.II/grid/tria_accessor.h
Labels: Documentation

#14084 Be explicit regarding zero tolerance in merge_triangulations
  include/deal.II/grid/grid_generator.h
  include/deal.II/grid/grid_tools.h
  source/grid/grid_generator.cc
  source/grid/grid_tools.cc
Labels: ready to test

#14059 find_active_cell_around_point should only find cells with marked vertices
  doc/news/changes/minor/20220628Heinz
  source/grid/grid_tools.cc
  tests/grid/grid_tools_07.cc
  tests/grid/grid_tools_07.output
Labels: ready to test

#14092 Bugfix: Use correct relative tolerance in MappingCartesian assert.
  doc/news/changes/minor/20220704gassmoeller
  source/fe/mapping_cartesian.cc
  tests/mappings/mapping_cartesian_03.cc
  tests/mappings/mapping_cartesian_03.output
Labels: Bug, ready to test

#14093 Fix formatting
  include/deal.II/lac/sparse_matrix.h
Labels: Reviewed and ready to merge, ready to test

#14086 doxygen: fix SymmetricTensor friends
  include/deal.II/base/symmetric_tensor.h
Labels: Documentation, ready to test

#13962 Support HDF5 output with one rank having no cells
  source/base/data_out_base.cc
  tests/data_out/data_out_hdf5_03.cc
  tests/data_out/data_out_hdf5_03.with_hdf5=true.with_p4est=true.mpirun=2.output
  tests/data_out/data_out_hdf5_03.with_hdf5=true.with_p4est=true.mpirun=3.output
Labels: Parallel, ready to test

#14090 FEEvaluationBase::read_write_operation_contiguous enable masking
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, ready to test

#14056 HDF XDMF entry: store reference cell
  doc/news/changes/incompatibilities/20220627Arndt-1
  include/deal.II/base/data_out_base.h
  source/base/data_out_base.cc
  tests/data_out/data_out_hdf5_02.cc
  tests/mpi/data_out_hdf5_02.cc
  tests/serialization/xdmf_entry.cc
  tests/serialization/xdmf_entry.output
Labels: Reviewed and ready to merge, ready to test

#14108 Update outdated documentation of Partitioner
  include/deal.II/lac/la_parallel_vector.h
Labels: Documentation

#14102 Add AssertIndexRange
  include/deal.II/matrix_free/operators.h
Labels: Reviewed and ready to merge, ready to test

#14119 FEEvaluationBase::read_write_operation Chose correct code path for neighbors and activated mask
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, ready to test

#14103 Better document what tolerance to use in MappingCartesian.
  source/fe/mapping_cartesian.cc
Labels: ready for review, Mapping, ready to test

#14120 Simplify some MPI code.
  source/multigrid/mg_transfer_internal.cc
Labels: ready to test

#14109 Add Vector::zero_out_ghost_values
  include/deal.II/lac/vector.h
Labels: ready to test

#14110 Implement parallel intermediate output
  doc/news/changes/minor/20220707tjhei
  include/deal.II/base/data_out_base.h
  source/base/data_out_base.cc
  source/base/data_out_base.inst.in
  tests/data_out/data_out_intermediate_parallel_01.cc
  tests/data_out/data_out_intermediate_parallel_01.mpirun=2.output
Labels: ready to test

#14099 RPE: allow to evaluate cell-data vector
  doc/news/changes/minor/20220706Munch
  include/deal.II/numerics/vector_tools_evaluate.h
  tests/remote_point_evaluation/vector_tools_evaluate_at_points_06.cc
  tests/remote_point_evaluation/vector_tools_evaluate_at_points_06.with_p4est=true.mpirun=4.output
Labels: ready for review, ready to test

#14116 Introduce copy_boundary_ids in merge_triangulation()
  doc/news/changes/minor/20220707Heinz
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  source/grid/grid_generator.inst.in
  tests/grid/grid_tools_07.cc
  tests/grid/merge_triangulations_10.cc
  tests/grid/merge_triangulations_10.output
Labels: ready to test

#14128 Simplify a function by using range-based for loops.
  source/grid/grid_tools.cc
Labels: Triangulation, ready to test

#14072 p:d:GridRefinement: accept other types of triangulations
  include/deal.II/distributed/grid_refinement.h
  source/distributed/grid_refinement.cc
  source/distributed/grid_refinement.inst.in
Labels: ready to test

#14073 Communicate refinement flags in p:s:T
  doc/news/changes/minor/20220712Munch
  include/deal.II/distributed/shared_tria.h
  source/distributed/shared_tria.cc
  tests/sharedtria/refine_and_coarsen_02.cc
  tests/sharedtria/refine_and_coarsen_02.mpirun=2.output
Labels: ready to test

#14139 Use pre-increment operator.
  source/grid/grid_generator.cc
Labels: ready to test

#14137 Use only enough bits in an enum as necessary.
  include/deal.II/base/geometry_info.h
Labels: ready to test

#14136 Clarify documentation of p::s::T.
  include/deal.II/distributed/shared_tria.h
Labels: Documentation, ready to test

#14126 Ensure to look at square of tolerances
  source/fe/mapping_cartesian.cc
Labels: Mapping, ready to test

#14135 Add some assertions about hypercube reference cells.
  source/grid/tria_accessor.cc
Labels: Enhancement, ready to test

#14138 Reduce the volume of communication somewhat.
  source/distributed/shared_tria.cc
Labels: ready to test

#14141 p:d:GridRefinement: actually accept other types of triangulations
  include/deal.II/distributed/grid_refinement.h
  source/distributed/grid_refinement.cc
  source/distributed/grid_refinement.inst.in
Labels: ready to test

#14142 Fix type in FPE
  include/deal.II/matrix_free/fe_point_evaluation.h
Labels: Matrix-free, ready to test

#14114 DoFHandlerPolicy: Avoid one write access to an array
  source/dofs/dof_handler_policy.cc
Labels: DoFs, ready to test

#14147 Do not use 'typename' where not necessary.
  include/deal.II/base/thread_local_storage.h
  include/deal.II/sundials/n_vector.templates.h
Labels: ready to test

#14089 Added explicit instantiations of DoFTools::distribute_cell_to_dof_vector
  doc/news/changes/minor/20220706Ahmad
  source/dofs/dof_tools.inst.in
Labels: ready to test

#14115 MatrixFree DoFInfo: Break out from some expensive loops
  source/matrix_free/dof_info.cc
Labels: Matrix-free, ready to test

#14145 Added quicktests to Intel workflow.
  .github/workflows/linux.yml
Labels: Infrastructure, Build system, Tests, ready to test

#14146 Show a formula.
  include/deal.II/base/symmetric_tensor.h
Labels: Documentation, Reviewed and ready to merge, ready to test

#14143 Add some functions to convert active cell iterators
  doc/news/changes/minor/20220715Pelteret
  examples/step-32/step-32.cc
  examples/step-51/step-51.cc
  include/deal.II/grid/tria_accessor.h
  source/grid/tria_accessor.cc
  tests/dofs/dof_iterators_01.cc
  tests/dofs/dof_iterators_01.output
  tests/dofs/dof_iterators_02.cc
  tests/dofs/dof_iterators_02.output
Labels: Miscellaneous, ready to test

#14153 MatrixFree: Use separate data arrays for two separate evaluators
  include/deal.II/matrix_free/mapping_info.templates.h
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#14154 FEEvaluation: Fix two places where the address sanitizer complained
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, ready to test

#14152 matrix-free FEEvaluation: initialize with nan
  include/deal.II/base/numbers.h
  include/deal.II/matrix_free/fe_evaluation_data.h
Labels: ready to test

#14132 MatrixFree: Implement get_affine_constraints()
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
  tests/matrix_free/affine_constraints_store_and_get.cc
  tests/matrix_free/affine_constraints_store_and_get.output
Labels: Matrix-free, ready to test

#14131 Add test for FEEvaluationShift with FE_Q and FE_DGQ
  tests/matrix_free/fe_evaluation_shift.cc
  tests/matrix_free/fe_evaluation_shift.output
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#14104 AssertThrow for BlockVector usage in MassOperator
  include/deal.II/matrix_free/operators.h
Labels: ready to test

#14041 `QSimplex<dim>::compute_affine_transformation()` in co-dimension one and two
  include/deal.II/base/quadrature_lib.h
  source/base/quadrature_lib.cc
  tests/base/quadrature_simplex_01_codim1.cc
  tests/base/quadrature_simplex_01_codim1.output
  tests/base/quadrature_simplex_02_codim2.cc
  tests/base/quadrature_simplex_02_codim2.output
Labels: Reviewed and ready to merge, Quadrature, ready to test

#14156 [9.4] Make ConsensusAlgorithm deprecations early-deprecated instead.
  include/deal.II/base/mpi_consensus_algorithms.h
Labels: Release, Miscellaneous, ready to test

#14158 CMake: remove find_package override
  cmake/macros/macro_find_package.cmake
  contrib/python-bindings/CMakeLists.txt
Labels: Build system, Reviewed and ready to merge, ready to test

#9937 Remove PETScWrappers deprecations
  doc/news/changes/incompatibilities/20200421DanielArndt
  include/deal.II/lac/petsc_vector.h
  source/lac/petsc_matrix_base.cc
  source/lac/petsc_parallel_sparse_matrix.cc
  source/lac/petsc_parallel_vector.cc
Labels: ready to test

#14161 Bump the minimum PETSc version number.
  cmake/configure/configure_30_petsc.cmake
  doc/external-libs/petsc.html
  doc/news/changes/incompatibilities/20220727Wells
  include/deal.II/lac/slepc_spectral_transformation.h
  source/lac/petsc_parallel_vector.cc
  source/lac/petsc_solver.cc
  source/lac/slepc_spectral_transformation.cc
Labels: External libraries, ready to test

#14162 Fix a typo in deal.II/base/numbers.h
  include/deal.II/base/numbers.h
Labels: Bug, High Priority :warning:, Reviewed and ready to merge, ready to test

#14150 Fix tria::has_hanging_nodes for anisotropically refined meshes
  source/grid/tria.cc
  tests/grid/grid_has_hanging_nodes.cc
  tests/grid/grid_has_hanging_nodes.output
Labels: Bug, ready for review, ready to test, Meshes

#14165 Fix generation of the tutorial graph.
  doc/doxygen/scripts/steps.pl
Labels: Tutorials

#14039 Implement isend/irecv functions.
  doc/news/changes/minor/20220707Bangerth
  include/deal.II/base/mpi.h
  tests/mpi/isend_irecv_01.cc
  tests/mpi/isend_irecv_01.mpirun=2.output
  tests/mpi/isend_irecv_01.mpirun=4.output
Labels: ready to test
