Repository dealii/dealii, pull requests merged in 2022-10, with the labels that each got.

#14326 Fix messages about cgal versions
  include/deal.II/cgal/utilities.h
  source/cgal/intersections.cc
Labels: ready to test

#14329 Use std::all_of
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
Labels: ready to test

#14334 Fix a <dl><dt><dd> type list.
  include/deal.II/base/polynomials_rt_bubbles.h
Labels: ready for review, ready to test

#14330 Implement some memory_consumption() functions
  include/deal.II/matrix_free/constraint_info.h
  include/deal.II/matrix_free/hanging_nodes_internal.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
Labels: ready to test

#14341 Fix check for same face type
  include/deal.II/matrix_free/evaluation_kernels.h
Labels: Matrix-free, ready to test

#14345 Fix transform() doc entry
  include/deal.II/grid/grid_tools.h
Labels: Documentation

#14340 Fix bug in FieldTransfer for ghosted vectors
  source/distributed/field_transfer.cc
  tests/hp/field_transfer_04.cc
  tests/hp/field_transfer_04.with_p4est=true.mpirun=2.output
  tests/hp/field_transfer_04.with_p4est=true.mpirun=3.output
Labels: ready to test

#14347 Remove an unnecessary semicolon.
  include/deal.II/fe/fe_tools_extrapolate.templates.h
Labels: ready to test

#14344 MatrixFree: add early check for ghosted dst vector
  include/deal.II/matrix_free/matrix_free.h
Labels: Matrix-free, ready to test

#14343 MatrixFree pre and post operation for loop()
  doc/news/changes/minor/20221011Proell
  include/deal.II/matrix_free/dof_info.templates.h
  include/deal.II/matrix_free/matrix_free.h
  tests/matrix_free/pre_and_post_loops_07.cc
  tests/matrix_free/pre_and_post_loops_07.with_p4est=true.mpirun=1.output
  tests/matrix_free/pre_and_post_loops_07.with_p4est=true.mpirun=3.output
  tests/matrix_free/pre_and_post_loops_08.cc
  tests/matrix_free/pre_and_post_loops_08.with_p4est=true.mpirun=2.output
Labels: ready to test

#14339 Fix some doxygen problems.
  include/deal.II/base/point.h
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/base/tensor.h
Labels: ready to test

#14348 Implement ReferenceCell::n_face_orientations().
  include/deal.II/grid/reference_cell.h
  source/fe/fe.cc
  source/fe/fe_raviart_thomas.cc
  source/fe/fe_system.cc
  tests/simplex/fe_p_bubbles_03.cc
  tests/simplex/fe_p_bubbles_03.output
Labels: Bug, ready to test

#14350 Refactor SolverGMRES::modified_gram_schmidt
  include/deal.II/lac/solver_gmres.h
Labels: ready to test

#14357 Fix two typos in ConsensusAlgorithm::NBX
  include/deal.II/base/mpi_consensus_algorithms.h
Labels: ready to test

#14349 SolverGMRES: add classical Gram-Schmidt
  include/deal.II/lac/solver_gmres.h
Labels: Linear Algebra, ready to test

#14369 Fix assert message
  include/deal.II/lac/chunk_sparse_matrix.h
  include/deal.II/lac/full_matrix.h
  include/deal.II/lac/petsc_matrix_base.h
  include/deal.II/lac/sparse_matrix.h
  include/deal.II/lac/trilinos_sparse_matrix.h
  include/deal.II/lac/trilinos_sparsity_pattern.h
Labels: Reviewed and ready to merge, ready to test

#14225 Adjust interface in 'dofs' folder to new datatype 'types::fe_index'.
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/dofs/dof_accessor.templates.h
  include/deal.II/dofs/dof_handler.h
  include/deal.II/dofs/dof_objects.h
  include/deal.II/dofs/dof_tools.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  source/distributed/tria.cc
  source/dofs/dof_accessor.cc
  source/dofs/dof_accessor_get.cc
  source/dofs/dof_accessor_get.inst.in
  source/dofs/dof_accessor_set.cc
  source/dofs/dof_accessor_set.inst.in
  source/dofs/dof_handler.cc
  source/dofs/dof_handler_policy.cc
  source/dofs/dof_renumbering.cc
  source/dofs/dof_tools.cc
  source/dofs/dof_tools_constraints.cc
  source/dofs/dof_tools_sparsity.cc
  source/hp/fe_collection.cc
  tests/hp/crash_17.cc
  tests/hp/crash_18.cc
  tests/hp/fe_collection_05.cc
  tests/hp/fe_collection_05.output
  tests/hp/fe_collection_06.cc
  tests/hp/fe_collection_06.output
  tests/hp/get_active_fe_indices.cc
  tests/matrix_free/fe_nothing_01.cc
  tests/multigrid-global-coarsening/mg_transfer_p_02.cc
Labels: hp, ready to test

#14374 Fix dimension selection in COMSOL mphtxt reader.
  source/grid/grid_in.cc
Labels: ready for review, ready to test

#14376 fe_index: added changelog.
  doc/news/changes/incompatibilities/20221027Fehling
Labels: Documentation, hp

#14378 Fix some warnings.
  source/cgal/intersections.cc
  source/dofs/dof_handler_policy.cc
Labels: ready to test

#14381 Make the error message for non-integer IDs in UNV files clearer.
  source/grid/grid_in.cc
Labels: Bug, Reviewed and ready to merge, ready to test
