Repository dealii/dealii, pull requests merged in 2023-04, with the labels that each got.

#15011 Work around nvcc compiler bug in mg_transfer_global_coarsening.templates.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
Labels: Reviewed and ready to merge, ready to test

#15012 FEPointEvaluation::integrate: Choose better loop layout
  include/deal.II/matrix_free/tensor_product_kernels.h
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#15005 Add a test for GridTools::Cache::get_covering_rtree().
  tests/grid/grid_tools_cache_08.cc
  tests/grid/grid_tools_cache_08.mpirun=1.output
  tests/grid/grid_tools_cache_08.mpirun=2.output
  tests/grid/grid_tools_cache_08.mpirun=4.output
Labels: ready to test

#15023 instantiate mapped quadrature for dim=1 and spacedim=2
  source/base/quadrature_lib.cc
Labels: ready to test

#15015 FEPointEvaluation: disconnect from MappingInfo
  include/deal.II/matrix_free/fe_point_evaluation.h
Labels: Matrix-free, ready to test

#15014 Clean up notions of CUDA in the codebase
  doc/doxygen/headers/glossary.h
  include/deal.II/base/cuda.h
  include/deal.II/base/memory_space.h
  include/deal.II/base/memory_space_data.h
  include/deal.II/base/numbers.h
  include/deal.II/base/partitioner.h
  include/deal.II/base/partitioner.templates.h
  include/deal.II/base/point.h
  include/deal.II/base/tensor.h
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/cuda_precondition.h
  include/deal.II/lac/cuda_solver_direct.h
  include/deal.II/lac/cuda_sparse_matrix.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/lac/precondition.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/vector_operations_internal.h
  include/deal.II/matrix_free/cuda_matrix_free.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  tests/lac/vector_memory_01.cc
  tests/lac/vector_memory_02.cc
  tests/lac/vector_reinit_04.cc
Labels: ready to test

#15027 Make step-29 marginally easier to understand.
  examples/step-29/step-29.cc
Labels: Tutorials, ready to test

#15028 Update the documentation of GridGenerator::extrude_triangulation().
  include/deal.II/grid/grid_generator.h
Labels: Documentation

#14983 Change default `compression_level` of vtu output
  doc/news/changes/minor/20230328Schmidt
  include/deal.II/base/data_out_base.h
  source/grid/grid_out.cc
  tests/data_out/data_out_12.cc
  tests/data_out/data_out_13.cc
  tests/data_out/data_out_base_vtu_02.cc
  tests/data_out/data_out_base_vtu_04.cc
  tests/data_out/data_out_base_vtu_05.cc
  tests/data_out/data_out_postprocessor_tensor_02.cc
  tests/grid/grid_out_07.cc
  tests/grid/grid_out_08.cc
  tests/grid/grid_out_per_processor_vtu_01.cc
  tests/grid/grid_out_per_processor_vtu_02.cc
  tests/grid/grid_out_per_processor_vtu_03.cc
  tests/hp/solution_transfer_03.cc
  tests/hp/solution_transfer_05.cc
  tests/mpi/codim_01.cc
  tests/mpi/parallel_vtu_01.cc
  tests/simplex/data_out_write_vtu_01.cc
  tests/simplex/write_mesh_per_processor_as_vtu_01.cc
Labels: ready to test

#15030 Use American English spelling for 'initialize'.
  include/deal.II/differentiation/ad/ad_number_traits.h
  include/deal.II/differentiation/ad/sacado_number_types.h
  include/deal.II/fe/fe_interface_values.h
  source/lac/scalapack.cc
Labels: Documentation

#15008 Add Functions::SignedDistance::Rectangle
  doc/doxygen/images/signed_distance_hyper_rectangle.png
  doc/news/changes/minor/20230331Schreter
  include/deal.II/base/bounding_box.h
  include/deal.II/base/function_signed_distance.h
  source/base/bounding_box.cc
  source/base/function_signed_distance.cc
  source/base/function_signed_distance.inst.in
  tests/base/function_signed_distance_03.cc
  tests/base/function_signed_distance_03.output
Labels: Reviewed and ready to merge, ready to test

#15032 Remove QuickMatrix
  tests/lac/quickmatrix.h
Labels: ready to test

#15009 Check whether construct_multigrid_hierarchy is set ealier.
  source/dofs/dof_handler_policy.cc
Labels: Reviewed and ready to merge, ready to test

#14717 Fix ghost indices handling for PETSc vectors
  include/deal.II/lac/petsc_vector_base.h
  source/lac/petsc_vector_base.cc
  tests/petsc/copy_to_dealvec_block.cc
Labels: ready to test

#15041 Don't overallocate memory.
  source/grid/grid_tools_cache.cc
Labels: ready to test

#15043 Rename a few variables to make their intent clearer.
  source/lac/petsc_vector_base.cc
Labels: ready to test

#15042 Update documentation in IndexSet for a couple of functions.
  include/deal.II/base/index_set.h
Labels: Documentation

#15037 Replace make_2_cells() with TestGrids::hyper_line().
  tests/feinterface/fe_interface_values_01.cc
  tests/feinterface/fe_interface_values_02.cc
  tests/feinterface/fe_interface_values_03.cc
  tests/feinterface/fe_interface_values_05.cc
  tests/feinterface/fe_interface_values_06.cc
  tests/feinterface/fe_interface_values_07.cc
  tests/feinterface/fe_interface_values_08.cc
  tests/feinterface/fe_interface_values_09.cc
  tests/feinterface/fe_interface_values_11.cc
  tests/feinterface/fe_interface_values_12.cc
  tests/feinterface/multigrid_01.cc
Labels: Reviewed and ready to merge, Tests, ready to test

#15029 Make fepointevaluation copyable/moveable
  include/deal.II/matrix_free/fe_point_evaluation.h
  tests/matrix_free/point_evaluation_21.cc
  tests/matrix_free/point_evaluation_21.output
Labels: Matrix-free, ready to test

#15040 Simplify code slightly.
  source/grid/grid_tools_cache.cc
Labels: ready to test

#14818 step-2: Make program more useful.
  examples/step-2/doc/intro.dox
  examples/step-2/doc/results.dox
  examples/step-2/step-2.cc
  include/deal.II/dofs/dof_tools.h
Labels: Tutorials, ready to test

#15046 Add entries to an IndexSet in already-sorted order.
  source/lac/petsc_vector_base.cc
Labels: ready to test

#15049 Add an assertion.
  include/deal.II/lac/affine_constraints.templates.h
Labels: ready to test

#15047 Clarifications in commentary in various places.
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/sparse_matrix.h
  include/deal.II/lac/sparse_matrix.templates.h
Labels: ready to test

#15050 Optimize insertion of elements into a matrix.
  include/deal.II/lac/sparse_matrix.h
Labels: ready to test

#15052 Fix malformed @return statements.
  include/deal.II/cgal/utilities.h
Labels: Documentation

#15053 Fix a typo.
  source/base/mpi.cc
Labels: Reviewed and ready to merge, ready to test

#15055 Add assert
  include/deal.II/matrix_free/matrix_free.h
Labels: Matrix-free, ready to test

#15004 Minor doc updates in GridTools.
  include/deal.II/grid/grid_tools.h
Labels: Documentation

#15057 Initialize Quadrature with move argument
  include/deal.II/base/quadrature.h
  source/base/quadrature.cc
Labels: Quadrature, ready to test

#15003 Use Kokkos for data structures in CUDA matrix-free framework
  doc/news/changes/incompatibilities/20230330Turcksin
  include/deal.II/base/cuda_size.h
  include/deal.II/base/geometry_info.h
  include/deal.II/base/numbers.h
  include/deal.II/base/tensor.h
  include/deal.II/base/utilities.h
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  include/deal.II/matrix_free/cuda_hanging_nodes_internal.h
  include/deal.II/matrix_free/cuda_matrix_free.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  include/deal.II/matrix_free/cuda_tensor_product_kernels.h
  source/matrix_free/cuda_matrix_free.cc
  tests/cuda/coefficient_eval.cc
  tests/cuda/cuda_evaluate_1d_shape.cc
  tests/cuda/cuda_evaluate_2d_shape.cc
  tests/cuda/matrix_free_initialize_vector.cc
  tests/cuda/matrix_free_multiple_objects.cc
  tests/cuda/matrix_free_no_index_initialize.cc
  tests/cuda/matrix_vector_common.h
  tests/cuda/matrix_vector_mf.h
Labels: Reviewed and ready to merge, GPU, ready to test

#15062 Remove write_tecplot_binary and related code
  examples/step-13/step-13.cc
  include/deal.II/base/data_out_base.h
  source/base/data_out_base.cc
  source/base/data_out_base.inst.in
Labels: ready to test

#15068 Fix reference
  doc/doxygen/references.bib
  include/deal.II/lac/petsc_precondition.h
Labels: Documentation

#15071 Do not infringe on the compiler's use of names.
  source/lac/petsc_communication_pattern.cc
Labels: Reviewed and ready to merge, ready to test

#15072 Minor updates to the ndarray documentation.
  include/deal.II/base/ndarray.h
Labels: Documentation, Reviewed and ready to merge

#14791 Improvements to the NOXSolver class documentation
  include/deal.II/trilinos/nox.h
Labels: Documentation

#15081 Avoid using include with quotation marks
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/grid/tria_accessor.h
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  include/deal.II/matrix_free/cuda_matrix_free.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  source/base/polynomials_rt_bubbles.cc
Labels: Reviewed and ready to merge, ready to test

#15082 Minor updates to the NOX solver interfaces.
  include/deal.II/trilinos/nox.h
Labels: Documentation, Reviewed and ready to merge

#15059 Optimize FlatManifold::get_new_points
  source/grid/manifold.cc
Labels: Manifold, ready to test

#15063 Improve support for MATNEST
  include/deal.II/lac/petsc_block_sparse_matrix.h
  include/deal.II/lac/petsc_matrix_base.h
  source/lac/petsc_matrix_base.cc
  source/lac/petsc_parallel_block_sparse_matrix.cc
  tests/petsc/block_matrices_01.cc
Labels: Reviewed and ready to merge, ready to test

#15066 PETScWrappers: Add support for ODE solver
  include/deal.II/base/exceptions.h
  include/deal.II/lac/petsc_ts.h
  include/deal.II/lac/petsc_ts.templates.h
  source/lac/CMakeLists.txt
  source/lac/petsc_ts.cc
  tests/petsc/petsc_ts_00.cc
  tests/petsc/petsc_ts_00.output
  tests/petsc/petsc_ts_00_in.prm
  tests/petsc/petsc_ts_01.cc
  tests/petsc/petsc_ts_01.output
  tests/petsc/petsc_ts_02.cc
  tests/petsc/petsc_ts_02.output
Labels: Reviewed and ready to merge, ready to test

#15098 Better document ExcFunctionNonzeroReturn exception.
  include/deal.II/base/exceptions.h
Labels: Documentation, ready to test

#15100 Better document an argument to hp::FEFaceValues.
  include/deal.II/hp/fe_values.h
Labels: Documentation, Finite Element

#15097 Better document FEInterfaceValues::reinit().
  include/deal.II/fe/fe_interface_values.h
Labels: Documentation, Finite Element

#15099 Add a check and produce better errors in FEInterfaceValues::reinit().
  doc/news/changes/minor/20230413Bangerth
  include/deal.II/fe/fe_interface_values.h
Labels: ready to test

#15092 Use latest ubuntu image in docker.yml.
  .github/workflows/docker.yml
Labels: Infrastructure

#15091 Convert PreconditionChebyshev::set_initial_guess_kernel to Kokkos
  include/deal.II/lac/precondition.h
Labels: Linear Algebra, ready to test

#15103 Add a test for FEInterfaceValues::reinit with no dominating FE.
  tests/feinterface/fe_interface_values_13.cc
  tests/feinterface/fe_interface_values_13.debug.output
Labels: Tests, Finite Element, ready to test

#15033 Add signed distance function for Zalesak's disk
  doc/doxygen/references.bib
  doc/news/changes/minor/20230406Schreter
  include/deal.II/base/function_signed_distance.h
  source/base/function_signed_distance.cc
  source/base/function_signed_distance.inst.in
  tests/base/function_signed_distance_04.cc
  tests/base/function_signed_distance_04.output
Labels: Enhancement, ready to test

#15104 Improve error message.
  include/deal.II/dofs/dof_accessor.templates.h
Labels: Reviewed and ready to merge, ready to test

#15106 Add 'requires' clauses to the rest of the triangulation classes.
  include/deal.II/base/template_constraints.h
  include/deal.II/distributed/fully_distributed_tria.h
  include/deal.II/distributed/p4est_wrappers.h
  include/deal.II/distributed/shared_tria.h
  include/deal.II/distributed/tria.h
  include/deal.II/distributed/tria_base.h
  include/deal.II/grid/grid_tools.h
  source/distributed/fully_distributed_tria.cc
  source/distributed/shared_tria.cc
  source/distributed/tria.cc
  source/distributed/tria_base.cc
Labels: ready to test

#15105 Fix interface mismatch in ScratchData in hp mode.
  source/meshworker/scratch_data.cc
Labels: hp, ready to test

#15101 extend distributed_compute_point_locations
  include/deal.II/grid/grid_tools.h
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
Labels: Triangulation, ready to test

#14988 Rework the introduction to step-7.
  examples/step-7/doc/intro.dox
Labels: Tutorials

#15035 Optimize mapping computation in MappingQ
  include/deal.II/base/qprojector.h
  include/deal.II/fe/mapping_q.h
  include/deal.II/fe/mapping_q_internal.h
  include/deal.II/non_matching/mapping_info.h
  source/base/qprojector.cc
  source/fe/mapping_q.cc
Labels: Mapping, ready to test

#14987 Leave a hint in step-7.
  doc/doxygen/references.bib
  examples/step-7/doc/results.dox
Labels: Tutorials

#15109 Remove PETSc compatibility things.
  include/deal.II/lac/petsc_compatibility.h
  source/lac/petsc_precondition.cc
Labels: ready to test

#15093 examples/step-1: undo accidental changes to CMakeLists.txt
  examples/step-1/CMakeLists.txt
Labels: Bug

#15013 Enable vectorization over quadrature points in whole FEPointEvaluation
  include/deal.II/base/signaling_nan.h
  include/deal.II/matrix_free/fe_point_evaluation.h
  tests/matrix_free/point_evaluation_22.cc
  tests/matrix_free/point_evaluation_22.output
Labels: Matrix-free, ready to test

#15083 Fix some minor typos
  doc/doxygen/tutorial/tutorial.h.in
  examples/step-12/doc/intro.dox
  examples/step-21/step-21.cc
  examples/step-22/doc/intro.dox
  examples/step-31/doc/intro.dox
  examples/step-33/step-33.cc
  examples/step-6/doc/intro.dox
  include/deal.II/algorithms/theta_timestepping.h
  include/deal.II/base/parameter_acceptor.h
  include/deal.II/grid/grid_out.h
Labels: Reviewed and ready to merge, ready to test

#15115 Fix a class name in step-69 commentary.
  examples/step-69/step-69.cc
Labels: Documentation

#15113 Address the pesky 'MPI_Comm as void*' problem with the SUNDIALS interfaces
  include/deal.II/sundials/n_vector.templates.h
  tests/sundials/n_vector.cc
Labels: ready to test

#15117 PETScWrappers Fix docs for SF classes
  include/deal.II/lac/petsc_communication_pattern.h
Labels: Reviewed and ready to merge, ready to test

#15086 All get_mpi_communicator methods now return MPI_Comm by value
  doc/news/changes/incompatibilities/20230412Zampini
  include/deal.II/base/communication_pattern_base.h
  include/deal.II/base/mpi.h
  include/deal.II/base/mpi_noncontiguous_partitioner.h
  include/deal.II/base/partitioner.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/petsc_block_sparse_matrix.h
  include/deal.II/lac/petsc_block_vector.h
  include/deal.II/lac/petsc_communication_pattern.h
  include/deal.II/lac/petsc_matrix_base.h
  include/deal.II/lac/petsc_precondition.h
  include/deal.II/lac/petsc_vector_base.h
  include/deal.II/lac/trilinos_block_sparse_matrix.h
  include/deal.II/lac/trilinos_epetra_communication_pattern.h
  include/deal.II/lac/trilinos_epetra_vector.h
  include/deal.II/lac/trilinos_precondition.h
  include/deal.II/lac/trilinos_sparse_matrix.h
  include/deal.II/lac/trilinos_sparsity_pattern.h
  include/deal.II/lac/trilinos_tpetra_communication_pattern.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_vector.h
  include/deal.II/matrix_free/vector_data_exchange.h
  include/deal.II/multigrid/multigrid.h
  source/base/mpi_noncontiguous_partitioner.cc
  source/lac/petsc_communication_pattern.cc
  source/lac/petsc_parallel_block_sparse_matrix.cc
  source/lac/petsc_precondition.cc
  source/lac/trilinos_epetra_communication_pattern.cc
  source/lac/trilinos_tpetra_communication_pattern.cc
  source/matrix_free/vector_data_exchange.cc
  tests/sundials/n_vector.cc
  tests/sundials/n_vector.mpirun=1.with_trilinos=off.with_petsc=on.output
  tests/sundials/n_vector.mpirun=1.with_trilinos=on.with_petsc=off.output
Labels: Reviewed and ready to merge, ready to test

#15079 More gracefully deal with Windoze line endings.
  doc/news/changes/minor/20230420Bangerth
  source/grid/grid_in.cc
  tests/grid/grid_in_comsol_mphtxt_04.cc
  tests/grid/grid_in_comsol_mphtxt_04.output
Labels: ready to test

#15120 Add an example to the documentation of GridTools::transform().
  include/deal.II/grid/grid_tools.h
Labels: Documentation

#14969 Add a move assignment operator to LA::d::V.
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/la_parallel_vector.templates.h
  tests/lac/parallel_vector_08.cc
Labels: Miscellaneous, ready to test

#15119 Update PETSc compatibility stuff for SNES and TS
  include/deal.II/lac/petsc_compatibility.h
  source/lac/CMakeLists.txt
  source/lac/petsc_compatibility.cc
  source/lac/petsc_full_matrix.cc
  source/lac/petsc_matrix_base.cc
  source/lac/petsc_matrix_free.cc
  source/lac/petsc_parallel_block_sparse_matrix.cc
  source/lac/petsc_parallel_block_vector.cc
  source/lac/petsc_parallel_sparse_matrix.cc
  source/lac/petsc_sparse_matrix.cc
Labels: ready for review, Reviewed and ready to merge, ready to test

#14866 Warn users about FE index mismatch instead of silently dropping them.
  include/deal.II/dofs/dof_accessor.templates.h
  source/dofs/dof_handler.cc
  source/grid/tria.cc
  tests/hp/non_hp_mode.cc
  tests/hp/non_hp_mode.debug.output
Labels: ready for review, hp, ready to test

#15118 PETScWrappers: update KSP support
  include/deal.II/lac/petsc_compatibility.h
  include/deal.II/lac/petsc_solver.h
  source/lac/petsc_solver.cc
  source/lac/slepc_spectral_transformation.cc
Labels: ready to test

#15126 PETScWrappers::TimeStepper fix backward compatibility to 3.7
  include/deal.II/lac/petsc_ts.h
  include/deal.II/lac/petsc_ts.templates.h
  source/lac/petsc_ts.cc
  tests/petsc/petsc_ts_00.cc
  tests/petsc/petsc_ts_00.output
  tests/petsc/petsc_ts_01.cc
  tests/petsc/petsc_ts_02.cc
Labels: Reviewed and ready to merge, ready to test

#15122 ParameterAcceptor now uses a set.
  doc/news/changes/minor/20230420LucaHeltai
  include/deal.II/base/parameter_acceptor.h
  source/base/parameter_acceptor.cc
  tests/parameter_handler/parameter_acceptor_11.cc
  tests/parameter_handler/parameter_acceptor_11.output
Labels: ready for review, ready to test

#15125 Remove tabulated shape functions from MappingQ
  include/deal.II/fe/fe_values.h
  include/deal.II/fe/mapping_q.h
  include/deal.II/fe/mapping_q_internal.h
  include/deal.II/matrix_free/tensor_product_kernels.h
  source/fe/mapping_q.cc
  tests/matrix_free/tensor_product_evaluate_07.cc
  tests/matrix_free/tensor_product_evaluate_07.output
  tests/matrix_free/tensor_product_evaluate_08.cc
  tests/matrix_free/tensor_product_evaluate_08.output
Labels: Mapping, ready to test

#15051 Return objects by value, rather than via a reference.
  doc/news/changes/minor/20230407Bangerth
  examples/step-2/step-2.cc
  examples/step-60/step-60.cc
  include/deal.II/dofs/dof_tools.h
  source/dofs/dof_tools.cc
  source/dofs/dof_tools.inst.in
  source/particles/generators.cc
Labels: DoFs, ready to test

#15127 Sort terms so that the bilinear form has ...phi_i * phi_j ... in step-57.
  examples/step-57/step-57.cc
Labels: Documentation, Tutorials, ready to test

#15065 PETScWrappers: Add support for nonlinear solver
  include/deal.II/lac/petsc_snes.h
  include/deal.II/lac/petsc_snes.templates.h
  source/lac/CMakeLists.txt
  source/lac/petsc_snes.cc
  tests/petsc/petsc_snes_00.cc
  tests/petsc/petsc_snes_00.output
  tests/petsc/petsc_snes_00_in.prm
  tests/petsc/petsc_snes_01.cc
  tests/petsc/petsc_snes_01.output
  tests/petsc/petsc_snes_02.cc
  tests/petsc/petsc_snes_02.output
  tests/petsc/petsc_snes_03.cc
  tests/petsc/petsc_snes_03.mpirun=3.output
  tests/petsc/petsc_snes_03.output
  tests/petsc/petsc_snes_04.cc
  tests/petsc/petsc_snes_04.mpirun=3.output
  tests/petsc/petsc_snes_04.output
Labels: ready for review, ready to test

#15130 Added changelog for #14866.
  doc/news/changes/minor/20230421Fehling
Labels: Documentation

#15133 Add changelog entry for SNES and TS
  doc/news/changes/major/20230422StefanoZampini
  include/deal.II/lac/petsc_snes.h
  include/deal.II/lac/petsc_ts.h
  include/deal.II/lac/petsc_ts.templates.h
  source/lac/petsc_ts.cc
  tests/petsc/petsc_ts_02.cc
Labels: ready for review, Reviewed and ready to merge, ready to test

#15139 Add necessary include files to a code snippet in the glossary.
  doc/doxygen/headers/glossary.h
Labels: Documentation

#15142 Convert step-57 references to bibtex, with proper cross-referencing.
  doc/doxygen/references.bib
  examples/step-57/doc/intro.dox
  examples/step-57/doc/results.dox
Labels: Documentation, Tutorials

#15143 Update bibtex entries of preprints.
  doc/doxygen/references.bib
Labels: Documentation, Reviewed and ready to merge

#15145 Various changes to bibliography.
  doc/doxygen/references.bib
Labels: Documentation

#15135 MatrixFree diagonal: Avoid quadratic complexity & memory allocations
  include/deal.II/matrix_free/tools.h
Labels: Matrix-free, ready to test

#15153 Format journals in bibliography.
  doc/doxygen/references.bib
Labels: Documentation

#15152 Format authors in bibliography.
  doc/doxygen/references.bib
Labels: Documentation, Reviewed and ready to merge

#15155 Fix bug in integrate_add_tensor_product_value_and_gradient_linear() for 1d
  include/deal.II/matrix_free/tensor_product_kernels.h
  tests/matrix_free/point_evaluation_22.cc
  tests/matrix_free/point_evaluation_22.output
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#15149 Introduce `MGTwoLevelTransferBase`
  include/deal.II/multigrid/mg_transfer_global_coarsening.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
Labels: Reviewed and ready to merge, Multigrid, ready to test

#15150 Add getter for cell_data in RPE
  include/deal.II/base/mpi_remote_point_evaluation.h
  source/base/mpi_remote_point_evaluation.cc
Labels: Reviewed and ready to merge, ready to test, Non-matching

#15151 Allow MappingInfo::reinit_cells() to work on containers
  include/deal.II/non_matching/mapping_info.h
Labels: ready to test

#15146 Document how we deal with errors in call-backs.
  doc/doxygen/headers/glossary.h
Labels: Documentation
