Repository dealii/dealii, pull requests merged in 2023-12, with the labels that each got.

#16314 Evaluation template factory: Remove unused template
  include/deal.II/matrix_free/evaluation_kernels_hanging_nodes.h
  include/deal.II/matrix_free/evaluation_template_factory_internal.h
  tests/matrix_free/hanging_node_kernels_01.cc
Labels: ready to test

#16319 fix a few comments in GridTools implementation
  source/grid/grid_tools_dof_handlers.cc
Labels: Documentation

#16315 unify some example output
  examples/step-14/doc/results.dox
  examples/step-14/step-14.cc
  examples/step-3/doc/results.dox
  examples/step-3/step-3.cc
  examples/step-9/step-9.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#16320 Fix the spelling of a function in the documentation.
  include/deal.II/dofs/dof_handler.h
Labels: Documentation

#16322 MGTwoLevelTransfer: improve setup of weights
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
Labels: Multigrid, ready to test

#16335 Fix mistaken std::move assignment.
  examples/step-31/step-31.cc
  examples/step-32/step-32.cc
Labels: Tutorials, ready to test

#16334 Leave a note in step-32.
  doc/doxygen/references.bib
  examples/step-32/step-32.cc
Labels: Documentation

#16002 Changes in p:f:T
  include/deal.II/grid/tria_description.h
  tests/fullydistributed_grids/create_manually_01.cc
  tests/fullydistributed_grids/create_manually_01.mpirun=1.output
  tests/fullydistributed_grids/create_manually_01.mpirun=4.output
Labels: Triangulation, Parallel distributed, ready to test

#16340 MatrixFree::reinit: Fix case with MPI and threading
  include/deal.II/matrix_free/matrix_free.templates.h
Labels: Matrix-free, ready to test

#16338 Support PETSc's new logging infrastructure in our test suite.
  tests/a-framework/petsc_leak.cc
  tests/a-framework/petsc_leak.with_petsc=on.mpirun=2.expect=run.output
  tests/tests.h
Labels: Tests, ready to test

#16344 Do not query direction flags for Triangulation<1,3> objects.
  source/fe/fe_values_base.cc
Labels: Triangulation, ready to test

#16342 Provide some context to an exception.
  include/deal.II/grid/tria.h
  source/grid/tria.cc
Labels: Triangulation, ready to test

#16325 Rewrite the introduction of step-5.
  examples/step-5/doc/intro.dox
  examples/step-5/step-5.cc
Labels: Tutorials, ready to test

#16341 Make control flow easier to read.
  source/grid/grid_generator.cc
Labels: ready to test

#16336 Add failing test for multiple ranks and threads
  tests/matrix_free/reinit_matrix_free_threading.cc
  tests/matrix_free/reinit_matrix_free_threading.with_p4est=true.mpirun=2.output
Labels: Matrix-free, ready to test

#16347 Add a test for a recent patch.
  tests/grid/grid_in_vtk_1d_3d.cc
  tests/grid/grid_in_vtk_1d_3d.output
  tests/grid/grid_in_vtk_1d_3d.tria1.vtk
  tests/grid/grid_in_vtk_1d_3d.tria2.vtk
  tests/grid/grid_in_vtk_1d_3d_replicate.cc
  tests/grid/grid_in_vtk_1d_3d_replicate.output
Labels: Reviewed and ready to merge, ready to test

#16349 Disallow using direction flags for spacedim>dim+1.
  doc/doxygen/headers/glossary.h
  include/deal.II/grid/tria.h
  include/deal.II/grid/tria_accessor.h
  source/grid/tria.cc
  source/grid/tria_accessor.cc
Labels: ready to test

#16351 Do not create arrays we do not use.
  source/grid/tria.cc
Labels: Triangulation, ready to test

#16350 Use std::optional instead of a hand-rolled version of it.
  include/deal.II/fe/fe_values_base.h
  source/fe/fe_values_base.cc
Labels: Finite Element, ready to test

#16354 Use a C++17 feature to make code more readable.
  include/deal.II/lac/sparse_matrix_tools.h
Labels: Reviewed and ready to merge, Linear Algebra, ready to test

#16352 Correct a condition.
  include/deal.II/lac/sparse_matrix_tools.h
Labels: ready to test

#16357 Choose a more efficient algorithm.
  include/deal.II/lac/sparse_matrix_tools.h
Labels: ready to test

#16355 Use std::variant instead of a hand-rolled version.
  include/deal.II/fe/fe_values_base.h
  source/fe/fe_values_base.cc
Labels: ready to test

#16361 Some more FEValuesBase cleanups
  include/deal.II/fe/fe_values_base.h
  source/fe/fe_values_base.cc
  source/fe/fe_values_base.inst.in
Labels: Finite Element, ready to test

#16365 Fix the names of functions in the documentation of step-42.
  examples/step-42/step-42.cc
Labels: Documentation

#16358 Minor update to the introduction of step-41.
  examples/step-41/doc/intro.dox
Labels: Documentation, Tutorials

#16368 Better document create_description_from_triangulation().
  include/deal.II/grid/tria_description.h
Labels: Documentation, ready to test

#16370 Improve documentation of TriangulationDescription and members.
  include/deal.II/grid/tria_description.h
Labels: Documentation, ready to test

#16367 Choose a better name for a template argument.
  source/grid/tria_description.cc
Labels: ready to test

#16375 Fix an unused variable warning.
  source/grid/tria_accessor.cc
Labels: Miscellaneous, ready to test

#16371 Introduce a function Utilities::MPI::partial_and_total_sum().
  doc/news/changes/minor/20231219Bangerth
  include/deal.II/base/mpi.h
  include/deal.II/lac/sparse_matrix_tools.h
  source/distributed/repartitioning_policy_tools.cc
  source/dofs/dof_handler_policy.cc
  source/particles/generators.cc
Labels: ready to test

#16369 Some cleanups to create_description_from_triangulation().
  source/grid/tria_description.cc
Labels: ready to test

#16373 Use face_orientation to encode 2D orientation information.
  doc/news/changes/incompatibilities/20231220DavidWells
  include/deal.II/base/geometry_info.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.templates.h
  source/distributed/tria.cc
  source/dofs/dof_tools_constraints.cc
  source/fe/fe_q_base.cc
  source/grid/grid_tools_dof_handlers.cc
  source/grid/tria.cc
  tests/base/geometry_info_2.output
  tests/base/geometry_info_8.output
  tests/dofs/dof_tools_21_b.output
  tests/dofs/dof_tools_21_b_x.cc
  tests/dofs/dof_tools_21_b_x_q3.cc
  tests/dofs/dof_tools_21_b_y.cc
  tests/dofs/dof_tools_21_c.output
  tests/fe/face_to_cell_q1_2d.cc
  tests/fe/face_to_cell_q1_2d.output
  tests/fe/face_to_cell_q2_2d.cc
  tests/fe/face_to_cell_q2_2d.output
  tests/fe/face_to_cell_q2xq2_2d.cc
  tests/fe/face_to_cell_q2xq2_2d.output
  tests/fe/face_to_cell_q3_2d.cc
  tests/fe/face_to_cell_q3_2d.output
  tests/fe/face_to_cell_q3xq4_2d.cc
  tests/fe/face_to_cell_q3xq4_2d.output
  tests/fe/face_to_cell_q4_2d.cc
  tests/fe/face_to_cell_q4_2d.output
  tests/grid/grid_tools_06.output
Labels: Triangulation, ready to test

#16239 KINSOL: option to select QR orthogonalization strategy
  include/deal.II/sundials/kinsol.h
  source/sundials/kinsol.cc
Labels: ready to test

#16379 Use combined_orientation in two more FiniteElement functions.
  doc/news/changes/incompatibilities/20231221DavidWells
  include/deal.II/dofs/dof_accessor.templates.h
  include/deal.II/fe/fe.h
  include/deal.II/fe/fe_q_base.h
  include/deal.II/fe/fe_system.h
  include/deal.II/numerics/vector_tools_boundary.templates.h
  source/dofs/dof_tools_constraints.cc
  source/fe/fe.cc
  source/fe/fe_q_base.cc
  source/fe/fe_system.cc
  tests/fe/face_to_cell_q1_2d.cc
  tests/fe/face_to_cell_q2_2d.cc
  tests/fe/face_to_cell_q2xq2_2d.cc
  tests/fe/face_to_cell_q3_2d.cc
  tests/fe/face_to_cell_q3xq4_2d.cc
  tests/fe/face_to_cell_q4_2d.cc
Labels: Finite Element, Triangulation, ready to test

#16385 Test examples
  tests/examples/README.md
  tests/examples/step-10.diff
  tests/examples/step-10.output
  tests/examples/step-11.diff
  tests/examples/step-11.output
  tests/examples/step-12.diff
  tests/examples/step-12.output
  tests/examples/step-13.diff
  tests/examples/step-13.output
  tests/examples/step-14.diff
  tests/examples/step-14.output
  tests/examples/step-16.diff
  tests/examples/step-16.output
  tests/examples/step-17.diff
  tests/examples/step-17.with_petsc=true.output
  tests/examples/step-3.diff
  tests/examples/step-3.output
  tests/examples/step-4.diff
  tests/examples/step-4.output
  tests/examples/step-40.diff
  tests/examples/step-56.diff
  tests/examples/step-6.diff
  tests/examples/step-6.output
  tests/examples/step-7.diff
  tests/examples/step-7.output
  tests/examples/step-8.diff
  tests/examples/step-8.output
Labels: Tests, ready to test

#16387 Revise the top of the ReadMe file.
  doc/readme.html
Labels: Documentation

#16378 Prohibit calling compress() on vectors with ghost elements.
  doc/news/changes/incompatibilities/20231227Bangerth
  source/lac/petsc_vector_base.cc
  source/lac/trilinos_vector.cc
Labels: Linear Algebra, External libraries, ready to test

#16377 More small updates to tria_description.cc.
  source/grid/tria_description.cc
Labels: Triangulation, Parallel distributed, ready to test

#16388 Use the combined orientation in another FiniteElement function.
  doc/news/changes/incompatibilities/20231221DavidWells
  include/deal.II/fe/fe.h
  include/deal.II/grid/tria_accessor.templates.h
  source/fe/fe.cc
Labels: Finite Element, ready to test

#16329 NOXSolver: add a test demonstrating the issue with pending_exception
  doc/news/changes/minor/20231226VladimirIvannikov
  include/deal.II/trilinos/nox.h
  include/deal.II/trilinos/nox.templates.h
  tests/trilinos/nox_solver_05.cc
  tests/trilinos/nox_solver_05.with_trilinos_with_nox=true.output
  tests/trilinos/nox_solver_06.cc
  tests/trilinos/nox_solver_06.with_trilinos_with_nox=true.output
Labels: ready to test

#16300 Classes used by Step 89
  doc/news/changes/major/20231127HeinzMunch
  include/deal.II/matrix_free/fe_remote_evaluation.h
  tests/matrix_free/fe_remote_evaluation_01.cc
  tests/matrix_free/fe_remote_evaluation_01.with_p4est=true.mpirun=1.output
  tests/matrix_free/fe_remote_evaluation_01.with_p4est=true.mpirun=2.output
  tests/matrix_free/fe_remote_evaluation_02.cc
  tests/matrix_free/fe_remote_evaluation_02.with_p4est=true.mpirun=1.output
  tests/matrix_free/fe_remote_evaluation_02.with_p4est=true.mpirun=2.output
Labels: ready to test
