Repository dealii/dealii, pull requests merged in 2023-02, with the labels that each got.

#14744 Some edits of the KINSol documentation.
  include/deal.II/sundials/kinsol.h
Labels: Reviewed and ready to merge

#14746 Remove a BOOST src directory we don't use.
  bundled/boost-1.70.0/libs/thread/src/CMakeLists.txt
  bundled/boost-1.70.0/libs/thread/src/future.cpp
  bundled/boost-1.70.0/libs/thread/src/pthread/once.cpp
  bundled/boost-1.70.0/libs/thread/src/pthread/once_atomic.cpp
  bundled/boost-1.70.0/libs/thread/src/pthread/thread.cpp
  bundled/boost-1.70.0/libs/thread/src/tss_null.cpp
  bundled/boost-1.70.0/libs/thread/src/win32/thread.cpp
  bundled/boost-1.70.0/libs/thread/src/win32/tss_dll.cpp
  bundled/boost-1.70.0/libs/thread/src/win32/tss_pe.cpp
Labels: External libraries, ready to test

#14726 cgal: disable diagnostics when including CGAL headers
  include/deal.II/base/config.h.in
  source/cgal/intersections.cc
Labels: External libraries, ready to test

#14752 Make sure all Kokkos headers are installed
  bundled/CMakeLists.txt
Labels: Reviewed and ready to merge, ready to test

#14753 Avoid __CUDA_ARCH__ in source code
  include/deal.II/base/exceptions.h
  include/deal.II/base/kokkos.h
  include/deal.II/base/point.h
  include/deal.II/base/tensor.h
  source/base/kokkos.cc
Labels: ready to test

#14757 update changelog for release
  doc/news/9.4.1-vs-9.4.2.h
Labels: Release

#14763 Don't use static variables in tests
  tests/lac/parallel_vector_22.cc
  tests/lac/parallel_vector_23.cc
Labels: Reviewed and ready to merge, ready to test

#14728 Fix find_all_active_cells_around_point()
  doc/news/changes/minor/20230207MunchSchreter
  source/grid/grid_tools.cc
  source/grid/grid_tools_dof_handlers.cc
  tests/grid/find_all_active_cells_around_point_04.cc
  tests/grid/find_all_active_cells_around_point_04.output
Labels: Bug, ready for review, ready to test

#14765 Fixing random number generator function parser
  source/base/mu_parser_internal.cc
  tests/base/function_parser_12.cc
  tests/base/function_parser_12.with_muparser=true.output
Labels: Bug, Reviewed and ready to merge, ready to test

#14767 Minor cleanups in PETSc interfaces.
  source/lac/petsc_parallel_sparse_matrix.cc
Labels: ready to test

#14762 QProjector: minor orientation fixes.
  source/base/qprojector.cc
Labels: Miscellaneous, ready to test

#14761 Fix the support points for FE_SimplexDGP.
  source/fe/fe_simplex_p.cc
Labels: ready to test, simplices

#14760 ignore external cast-function-type warnings
  include/deal.II/base/config.h.in
Labels: ready to test

#14736 Add support for partitioning with PetscSF
  doc/doxygen/references.bib
  include/deal.II/base/index_set.h
  include/deal.II/lac/petsc_communication_pattern.h
  source/base/index_set.cc
  source/lac/CMakeLists.txt
  source/lac/petsc_communication_pattern.cc
  source/lac/petsc_communication_pattern.inst.in
  tests/petsc/petsc_noncontiguous_partitioner_01.cc
  tests/petsc/petsc_noncontiguous_partitioner_01.mpirun=2.output
  tests/petsc/petsc_noncontiguous_partitioner_02.cc
  tests/petsc/petsc_noncontiguous_partitioner_02.with_p4est=true.mpirun=1.output
  tests/petsc/petsc_noncontiguous_partitioner_02.with_p4est=true.mpirun=2.output
  tests/petsc/petsc_noncontiguous_partitioner_02.with_p4est=true.mpirun=4.output
  tests/petsc/petsc_noncontiguous_partitioner_02.with_p4est=true.mpirun=5.output
  tests/petsc/petsc_noncontiguous_partitioner_03.cc
  tests/petsc/petsc_noncontiguous_partitioner_03.mpirun=2.output
  tests/petsc/petsc_partitioner_06.cc
  tests/petsc/petsc_partitioner_06.mpirun=4.output
  tests/petsc/petsc_partitioner_07.cc
  tests/petsc/petsc_partitioner_07.mpirun=4.output
Labels: ready to test

#14759 changed std::pow to Utilities::pow in include/ source/
  include/deal.II/optimization/line_minimization.h
  source/base/function_lib_cutoff.cc
  source/base/function_signed_distance.cc
  source/base/quadrature_lib.cc
  source/grid/grid_generator.cc
  source/grid/manifold_lib.cc
  source/numerics/derivative_approximation.cc
Labels: ready to test

#14766 Extend test `find_all_active_cells_around_point_04`
  tests/grid/find_all_active_cells_around_point_04.cc
  tests/grid/find_all_active_cells_around_point_04.output
Labels: ready to test

#14778 Fix a comment for types::boundary_id.
  include/deal.II/base/types.h
Labels: Documentation, ready to test

#14769 Fix an assertion.
  include/deal.II/base/utilities.h
Labels: ready to test

#14773 Fix warnings with Clang-15+Cuda
  include/deal.II/lac/cuda_kernels.h
  include/deal.II/lac/cuda_kernels.templates.h
  include/deal.II/lac/cuda_sparse_matrix.h
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  source/grid/tria.cc
  source/lac/cuda_precondition.cc
  source/lac/cuda_sparse_matrix.cc
  source/numerics/solution_transfer.cc
Labels: ready to test

#14779 doc edits for KINSol
  include/deal.II/sundials/kinsol.h
Labels: Documentation, Reviewed and ready to merge

#14754 Fix the type used to initialize a DerivativeForm from a tensor.
  doc/news/changes/minor/20230201Bangerth
  include/deal.II/base/derivative_form.h
  tests/base/derivative_form_initialization.cc
  tests/base/derivative_form_initialization.output
Labels: ready to test

#14777 Standardize 2D/3D -> 2d/3d in a few strings.
  examples/step-81/step-81.cc
  include/deal.II/base/polynomials_rt_bubbles.h
  include/deal.II/cgal/additional_data.h
  include/deal.II/cgal/utilities.h
  include/deal.II/fe/fe_rt_bubbles.h
  include/deal.II/lac/tensor_product_matrix.h
  include/deal.II/matrix_free/evaluation_kernels_hanging_nodes.h
  include/deal.II/matrix_free/shape_info.templates.h
  include/deal.II/numerics/vector_tools_boundary.templates.h
  source/base/quadrature_lib.cc
  source/dofs/dof_tools_constraints.cc
  source/fe/fe_face.cc
  source/grid/grid_generator.cc
  source/grid/grid_out.cc
  source/grid/tria.cc
  tests/grid/twisted_parallelepiped_01.debug.output
Labels: ready to test

#14776 Standardize 2D/3D -> 2d/3d in the tutorials.
  examples/step-22/step-22.cc
  examples/step-25/step-25.cc
  examples/step-29/step-29.cc
  examples/step-3/step-3.cc
  examples/step-30/step-30.cc
  examples/step-32/step-32.cc
  examples/step-37/step-37.cc
  examples/step-4/step-4.cc
  examples/step-41/step-41.cc
  examples/step-44/step-44.cc
  examples/step-48/step-48.cc
  examples/step-5/step-5.cc
  examples/step-51/step-51.cc
  examples/step-59/step-59.cc
  examples/step-63/step-63.cc
  examples/step-65/step-65.cc
  examples/step-66/step-66.cc
  examples/step-67/step-67.cc
  examples/step-69/step-69.cc
  examples/step-7/step-7.cc
  examples/step-70/step-70.cc
  examples/step-75/step-75.cc
  examples/step-76/step-76.cc
  examples/step-8/step-8.cc
  examples/step-82/step-82.cc
  examples/step-85/step-85.cc
  examples/step-9/step-9.cc
Labels: ready to test

#14785 Remove checks for CMake versions prior to 3.13.4
  cmake/configure/configure_40_cuda.cmake
  cmake/macros/macro_deal_ii_add_library.cmake
  cmake/macros/macro_deal_ii_setup_target.cmake
  cmake/macros/macro_insource_setup_target.cmake
  contrib/python-bindings/CMakeLists.txt
  tests/CMakeLists.txt
Labels: ready to test

#14716 Minor fixes for PETSc testing
  source/lac/petsc_vector_base.cc
  tests/fe/fe_enriched_color_07.cc
  tests/lac/linear_operator_09.cc
  tests/mpi/p4est_save_06.cc
  tests/petsc/assemble_matrix_parallel_01.cc
  tests/petsc/assemble_matrix_parallel_01.output
Labels: ready to test

#14786 Fix DEAL_II_COMPILER_HAS_ATTRIBUTE_ALWAYS_INLINE with -Werror
  cmake/checks/check_02_compiler_features.cmake
  cmake/setup_compiler_flags_intel.cmake
Labels: ready to test

#14788 Fix hp decision on coarse level cells.
  examples/step-75/doc/results.dox
  examples/step-75/step-75.cc
  source/hp/refinement.cc
Labels: Bug, Reviewed and ready to merge, hp, ready to test

#14789 document MatrixFree mapping_update_flags
  include/deal.II/matrix_free/matrix_free.h
Labels: Documentation

#14770 Replace a ReferenceCell function call by a non-deprecated one.
  source/base/qprojector.cc
Labels: Reviewed and ready to merge, ready to test

#14793 doc: replace FE_DGRT with correct name
  examples/step-61/doc/intro.dox
  examples/step-61/step-61.cc
  include/deal.II/fe/fe_dg_vector.h
Labels: Documentation, Reviewed and ready to merge

#14792 doc: move simplex function from module
  include/deal.II/grid/grid_generator.h
Labels: Documentation

#14790 doc: fix GridGenerator::convert_hypercube_to_simplex_mesh
  include/deal.II/grid/grid_generator.h
Labels: Documentation, Reviewed and ready to merge, ready to test

#14771 Use try_compile in macro_check_compiler_setup.cmake
  cmake/macros/check_compiler_setup/CMakeLists.txt
  cmake/macros/check_compiler_setup/dummy.cpp
  cmake/macros/macro_check_compiler_setup.cmake
Labels: ready to test

#14800 Fix a grammar mistake.
  cmake/checks/check_01_cpu_features.cmake
Labels: Documentation

#14802 FieldTransfer: enable coarsening
  include/deal.II/distributed/field_transfer.h
  source/distributed/field_transfer.cc
  tests/hp/field_transfer_05.cc
  tests/hp/field_transfer_05.with_p4est=true.mpirun=2.output
Labels: Reviewed and ready to merge, ready to test

#14808 CI: Jenkins increase timeout
  contrib/ci/Jenkinsfile.mpi
Labels: ready to test

#14781 Added test for SolutionTransfer with hp-refinement and manually set flags.
  tests/mpi/solution_transfer_11.cc
  tests/mpi/solution_transfer_11.mpirun=2.output
Labels: hp, Parallel distributed, ready to test

#14801 Fix description of assemble_system() in step-40.
  examples/step-40/step-40.cc
Labels: ready to test

#14805 fix unused variable warning
  source/grid/manifold.cc
Labels: Reviewed and ready to merge, ready to test

#14810 Fix using mesh_loop with DG and periodic boundary conditions
  include/deal.II/meshworker/mesh_loop.h
  tests/meshworker/mesh_loop_pbc_01.cc
  tests/meshworker/mesh_loop_pbc_01.output
Labels: Reviewed and ready to merge, ready to test

#14811 Fix Tpetra detection and unit tests
  cmake/configure/configure_20_trilinos.cmake
  include/deal.II/base/index_set.h
  include/deal.II/base/types.h
  include/deal.II/lac/read_write_vector.h
  include/deal.II/lac/read_write_vector.templates.h
  include/deal.II/lac/trilinos_tpetra_communication_pattern.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  include/deal.II/lac/vector_element_access.h
  source/base/index_set.cc
  source/lac/trilinos_tpetra_communication_pattern.cc
Labels: ready to test

#14803 Include bundled include directories as CMake SYSTEM paths
  bundled/CMakeLists.txt
  cmake/macros/macro_deal_ii_add_library.cmake
  cmake/macros/macro_insource_setup_target.cmake
  contrib/python-bindings/source/CMakeLists.txt
  include/deal.II/arborx/bvh.h
  include/deal.II/arborx/distributed_tree.h
  include/deal.II/base/bounding_box_data_out.h
  include/deal.II/base/index_set.h
  include/deal.II/base/memory_space.h
  include/deal.II/base/memory_space_data.h
  include/deal.II/base/mpi_stub.h
  include/deal.II/base/parallel.h
  include/deal.II/base/patterns.h
  include/deal.II/base/point.h
  include/deal.II/base/std_cxx17/variant.h
  include/deal.II/base/table_handler.h
  include/deal.II/base/thread_management.h
  include/deal.II/base/trilinos_utilities.h
  include/deal.II/base/utilities.h
  include/deal.II/base/work_stream.h
  include/deal.II/boost_adaptors/bounding_box.h
  include/deal.II/boost_adaptors/segment.h
  include/deal.II/differentiation/ad/ad_drivers.h
  include/deal.II/differentiation/ad/sacado_number_types.h
  include/deal.II/differentiation/sd/symengine_number_visitor_internal.h
  include/deal.II/differentiation/sd/symengine_optimizer.h
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_accessor.templates.h
  include/deal.II/matrix_free/matrix_free.templates.h
  include/deal.II/numerics/rtree.h
  source/base/data_out_base.cc
  source/base/multithread_info.cc
  source/base/parameter_handler.cc
  source/base/patterns.cc
  source/base/tensor_product_polynomials.cc
  source/base/utilities.cc
  source/cgal/intersections.cc
  source/differentiation/ad/ad_drivers.cc
  source/differentiation/sd/symengine_math.cc
  source/dofs/dof_renumbering.cc
  source/fe/fe_values.cc
  source/fe/mapping.cc
  source/fe/mapping_fe.cc
  source/fe/mapping_q.cc
  source/grid/CMakeLists.txt
  source/grid/grid_tools.cc
  source/grid/manifold.cc
  source/grid/manifold_lib.cc
  source/lac/sparsity_pattern_base.cc
  source/lac/trilinos_sparse_matrix.cc
  tests/quick_tests/kokkos.cc
  tests/quick_tests/taskflow.cc
Labels: ready to test

#14813 implement VectorTools::add_constant
  doc/news/changes/minor/20230217tjhei
  include/deal.II/numerics/vector_tools_mean_value.h
  include/deal.II/numerics/vector_tools_mean_value.templates.h
  source/numerics/vector_tools_mean_value.inst.in
  tests/vector_tools/add_constant_01.cc
  tests/vector_tools/add_constant_01.output
  tests/vector_tools/add_constant_02.cc
  tests/vector_tools/add_constant_02.mpirun=2.output
Labels: ready to test

#14783 Suppress some nvcc warnings
  .github/workflows/linux.yml
  cmake/macros/macro_deal_ii_add_library.cmake
  cmake/macros/macro_deal_ii_setup_target.cmake
  cmake/macros/macro_enable_if_supported.cmake
  cmake/macros/macro_insource_setup_target.cmake
  cmake/modules/FindDEAL_II_CUDA.cmake
  include/deal.II/base/parsed_convergence_table.h
  source/base/data_out_base.cc
Labels: ready to test

#14794 doxygen: simplex relates
  doc/doxygen/headers/simplex.h
  include/deal.II/base/quadrature_lib.h
  include/deal.II/fe/fe_pyramid_p.h
  include/deal.II/fe/fe_simplex_p.h
  include/deal.II/fe/fe_wedge_p.h
  include/deal.II/fe/mapping_fe.h
  include/deal.II/grid/grid_generator.h
  include/deal.II/grid/grid_in.h
Labels: Documentation, Reviewed and ready to merge, ready to test, simplices

#14819 fix comment location
  include/deal.II/differentiation/ad/sacado_number_types.h
Labels: Reviewed and ready to merge, ready to test

#14820 simplex doxygen: more cleanup
  doc/doxygen/headers/simplex.h
  include/deal.II/grid/grid_generator.h
Labels: Documentation, simplices

#14821 Fix NVCC CI
  cmake/macros/check_compiler_setup/CMakeLists.txt
Labels: Reviewed and ready to merge, ready to test

#14823 FEPointEvaluation: fix typo
  include/deal.II/matrix_free/fe_point_evaluation.h
Labels: Documentation

#14822 Fix bug in MappingQCache(1) with cell similarity
  doc/news/changes/minor/20230222Kronbichler
  source/fe/mapping_q.cc
  tests/mappings/mapping_q_cache_09.cc
  tests/mappings/mapping_q_cache_09.output
Labels: Mapping, ready to test

#14825 step-82: rename output filename
  examples/step-82/step-82.cc
Labels: Reviewed and ready to merge, ready to test

#14772 Use Kokkos::abort directly
  include/deal.II/base/exceptions.h
  include/deal.II/base/kokkos.h
  include/deal.II/base/tensor.h
  source/base/kokkos.cc
Labels: ready to test

#14817 step-2: Clarify some text.
  examples/step-2/doc/results.dox
Labels: Tutorials

#14827 Fix an 'unused typedef' warning.
  include/deal.II/matrix_free/operators.h
Labels: Reviewed and ready to merge, Miscellaneous, ready to test

#14828 Don't derive InvalidAccessor from TriaAccessorBase.
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_accessor.templates.h
  source/grid/tria_accessor.cc
  source/grid/tria_accessor.inst.in
Labels: Reviewed and ready to merge, ready to test

#14831 Produce .inst files that are easier to read.
  cmake/scripts/expand_instantiations.cc
Labels: ready to test

#14758 Fix compiling with Trilinos+Sacado+Cuda
  include/deal.II/base/numbers.h
  include/deal.II/differentiation/ad/ad_helpers.h
  include/deal.II/differentiation/ad/sacado_number_types.h
Labels: ready to test

#14824 Only instantiate TpetraWrappers::Vector for types that have explicit instantiations in Tpetra
  cmake/configure/configure_20_trilinos.cmake
  include/deal.II/lac/read_write_vector.h
  include/deal.II/lac/read_write_vector.templates.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/numerics/vector_tools_mean_value.templates.h
  source/lac/affine_constraints.cc
  source/lac/read_write_vector.cc
  source/lac/trilinos_sparse_matrix.cc
  source/lac/trilinos_tpetra_vector.cc
  tests/trilinos/tpetra_vector_01.cc
  tests/trilinos/tpetra_vector_02.cc
  tests/trilinos/tpetra_vector_03.cc
  tests/trilinos/tpetra_vector_03.with_trilinos_with_tpetra=on.with_complex_values=off.mpirun=2.output
  tests/trilinos/tpetra_vector_03.with_trilinos_with_tpetra=on.with_complex_values=off.mpirun=4.output
  tests/trilinos/tpetra_vector_03.with_trilinos_with_tpetra=on.with_complex_values=on.mpirun=2.output
  tests/trilinos/tpetra_vector_03.with_trilinos_with_tpetra=on.with_complex_values=on.mpirun=4.output
Labels: ready to test

#14833 Fix grammar in an error message.
  source/dofs/dof_handler.cc
Labels: Miscellaneous

#14834 Fix an array index warning.
  source/base/geometric_utilities.cc
Labels: Miscellaneous, ready to test

#14832 Avoid some more instantiations of class Triangulation for invalid arguments.
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_accessor.templates.h
  source/dofs/dof_accessor.cc
Labels: ready to test
