Repository dealii/dealii, pull requests merged in 2023-10, with the labels that each got.

#16063 Docker: Build images every 12 hours.
  .github/workflows/docker.yml
Labels: Infrastructure

#15995 Extend API of RemotePointEvaluation::CellData
  doc/news/changes/minor/20230917SchreterMunch
  include/deal.II/base/mpi_remote_point_evaluation.h
  source/base/mpi_remote_point_evaluation.cc
Labels: ready to test

#16075 github-actions: fix a race condition.
  .github/workflows/windows.yml
Labels: Infrastructure

#16066 Fix doxygen warnings for template instantiations
  include/deal.II/fe/fe.h
  include/deal.II/lac/solver.h
  source/base/numbers.cc
  source/base/partitioner.cc
  source/dofs/dof_handler.cc
  source/fe/fe.cc
  source/fe/fe_poly.cc
  source/fe/fe_poly_tensor.cc
  source/fe/fe_q_base.cc
  source/fe/fe_system.cc
  source/fe/fe_values.cc
  source/fe/mapping.cc
  source/grid/manifold.cc
  source/grid/tria.cc
  source/grid/tria_accessor.cc
  source/lac/petsc_communication_pattern.cc
Labels: Documentation

#16068 make_flux_sparsity_pattern: Reduce compile time by joining code
  source/dofs/dof_tools_sparsity.cc
Labels: DoFs, ready to test

#16073 Update oneAPI CI
  .github/workflows/linux.yml
Labels: Reviewed and ready to merge

#16082 Print function for DerivativeForm
  include/deal.II/base/derivative_form.h
Labels: ready to test

#16076 Restructure FullMatrix::invert to (hopefully) lower compilation times
  include/deal.II/lac/full_matrix.templates.h
Labels: Linear Algebra, ready to test

#16080 Fix NoncontiguousPartitioner::import_from_ghosted_array()
  include/deal.II/base/mpi_noncontiguous_partitioner.templates.h
Labels: Bug, ready to test

#16055 Fix .pl extensions in copyright update script
  contrib/utilities/update-copyright.sh
Labels: Reviewed and ready to merge

#16086 Swap out burn() for sleep in an erratic test.
  tests/base/timer_03.cc
Labels: Reviewed and ready to merge, Tests, ready to test

#16085 Fix initialize typo in global coarsening functions
  include/deal.II/multigrid/mg_transfer_global_coarsening.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
Labels: ready to test

#16078 Reduce overhead in FEEvaluation::reinit(array of cells)
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, ready to test

#16090 FEPointEvaluation: Fix check in debug mode
  include/deal.II/matrix_free/fe_point_evaluation.h
Labels: Reviewed and ready to merge, ready to test

#16092 Improve two error messages.
  include/deal.II/lac/affine_constraints.h
Labels: ready to test

#16094 Added shasum and download file for arm architecture.
  contrib/utilities/download_clang_format
Labels: Infrastructure

#16089 DerivativeForm output operator: Add test and changelog
  doc/news/changes/minor/20231004Bergbauer
  include/deal.II/base/derivative_form.h
  include/deal.II/base/tensor.h
  tests/base/derivative_forms_05.cc
  tests/base/derivative_forms_05.output
Labels: Reviewed and ready to merge, ready to test

#16079 Add a function to take a view of an index set with regard to an index set mask.
  doc/news/changes/minor/20231002Bangerth
  include/deal.II/base/index_set.h
  source/base/index_set.cc
  tests/base/index_set_36.cc
  tests/base/index_set_36.output
  tests/base/index_set_37.cc
  tests/base/index_set_37.output
  tests/base/index_set_38.cc
  tests/base/index_set_38.output
Labels: DoFs, ready to test

#16093 Fix a bug in AffineConstraints::clear().
  include/deal.II/lac/affine_constraints.templates.h
Labels: DoFs, ready to test

#16072 Add step-87: Tutorial on RemotePointEvaluation
  doc/doxygen/references.bib
  doc/doxygen/tutorial/tutorial.h.in
  doc/news/changes/major/20230905SchreterMunch
  examples/step-87/CMakeLists.txt
  examples/step-87/doc/builds-on
  examples/step-87/doc/intro.dox
  examples/step-87/doc/kind
  examples/step-87/doc/results.dox
  examples/step-87/doc/tooltip
  examples/step-87/step-87.cc
Labels: Tutorials, ready to test

#16095 Add zenodo DOI for step-87
  examples/step-87/doc/intro.dox
Labels: Documentation

#16100 Some cleanups.
  examples/step-62/step-62.cc
  include/deal.II/base/index_set.h
  include/deal.II/lac/affine_constraints.templates.h
Labels: Reviewed and ready to merge, ready to test

#16102 Add another assertion.
  include/deal.II/lac/affine_constraints.templates.h
Labels: Reviewed and ready to merge, ready to test

#16097 Remove unnecessary <sstream> header include.
  tests/mpi/constraint_matrix_trilinos_bug.cc
  tests/mpi/derivative_approximation_01.cc
  tests/mpi/derivative_approximation_02.cc
  tests/mpi/interpolate_01.cc
  tests/mpi/interpolate_02.cc
  tests/mpi/interpolate_05.cc
  tests/mpi/multigrid_adaptive.cc
  tests/mpi/multigrid_uniform.cc
  tests/mpi/no_flux_constraints.cc
  tests/mpi/no_flux_constraints_02.cc
  tests/mpi/no_flux_constraints_03.cc
  tests/mpi/normal_flux_constraints.cc
  tests/mpi/p4est_2d_constraintmatrix_01.cc
  tests/mpi/p4est_2d_constraintmatrix_02.cc
  tests/mpi/p4est_2d_constraintmatrix_03.cc
  tests/mpi/p4est_2d_constraintmatrix_04.cc
  tests/mpi/p4est_3d_constraintmatrix_01.cc
  tests/mpi/p4est_3d_constraintmatrix_02.cc
  tests/mpi/p4est_3d_constraintmatrix_03.cc
  tests/mpi/petsc_distribute_01.cc
  tests/mpi/petsc_distribute_01_block.cc
  tests/mpi/petsc_distribute_01_inhomogenous.cc
  tests/mpi/petsc_locally_owned_elements.cc
  tests/mpi/solution_transfer_01.cc
  tests/mpi/trilinos_distribute_01.cc
  tests/mpi/trilinos_distribute_01_block.cc
  tests/mpi/trilinos_distribute_01_inhomogenous.cc
  tests/mpi/trilinos_distribute_03.cc
  tests/mpi/trilinos_distribute_04.cc
  tests/mpi/trilinos_locally_owned_elements_01.cc
  tests/mpi/trilinos_locally_owned_elements_02.cc
Labels: Reviewed and ready to merge, ready to test

#16101 Fix swapped error messages.
  include/deal.II/lac/affine_constraints.h
Labels: ready to test

#16099 Add AffineConstraints::get_view().
  doc/news/changes/minor/20231005Bangerth
  include/deal.II/lac/affine_constraints.h
  include/deal.II/lac/affine_constraints.templates.h
  tests/mpi/affine_constraints_get_view_01.cc
  tests/mpi/affine_constraints_get_view_01.with_trilinos=true.mpirun=1.output
  tests/mpi/affine_constraints_get_view_01.with_trilinos=true.mpirun=2.output
  tests/mpi/affine_constraints_get_view_01.with_trilinos=true.mpirun=4.output
Labels: ready to test

#16103 Add AffineConstraint::add_constraint().
  doc/news/changes/minor/20231002Bangerth_2
  examples/step-11/step-11.cc
  examples/step-41/step-41.cc
  examples/step-46/doc/intro.dox
  examples/step-46/step-46.cc
  include/deal.II/lac/affine_constraints.h
  include/deal.II/numerics/vector_tools_boundary.templates.h
  include/deal.II/numerics/vector_tools_constraints.templates.h
  source/dofs/dof_tools_constraints.cc
Labels: Reviewed and ready to merge, ready to test

#16109 TriaAccessor: simplify code
  include/deal.II/grid/tria_accessor.templates.h
Labels: ready to test

#16096 Deprecate AffineConstraints::add_selected_constraints().
  include/deal.II/lac/affine_constraints.h
Labels: Linear Algebra, ready to test

#15945 Add code to serialize PETSc vectors.
  include/deal.II/lac/petsc_vector_base.h
  tests/petsc/serialize_vector_01.cc
  tests/petsc/serialize_vector_01.mpirun=2.output
Labels: Enhancement, ready to test

#16112 Make sure ArrayView of an empty array really is a nullptr.
  include/deal.II/base/array_view.h
Labels: ready to test

#16083 Document the intention of the numbers::invalid_* variables.
  doc/doxygen/headers/glossary.h
  include/deal.II/base/index_set.h
  include/deal.II/base/types.h
Labels: Documentation, ready to test

#16115 Restrict checking ArrayView validity to debug mode.
  include/deal.II/base/array_view.h
Labels: ready to test

#16119 Fix ReferenceCell::standard_vs_true_line_orientation() for simplices
  doc/news/changes/minor/20231010Munch
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.templates.h
  tests/simplex/orientation_04.cc
  tests/simplex/orientation_04.output
Labels: ready to test

#16114 Allow creation of an ArrayView from a std::initializer_list.
  doc/news/changes/minor/20231010Bangerth
  include/deal.II/base/array_view.h
  tests/base/array_view_21.cc
  tests/base/array_view_21.output
Labels: Linear Algebra, ready to test

#16088 MGTransferMF: check compatibility of DoFHandlers
  doc/news/changes/minor/20231003Munch
  include/deal.II/multigrid/mg_transfer_global_coarsening.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  tests/multigrid-global-coarsening/multigrid_p_04.cc
  tests/multigrid-global-coarsening/multigrid_p_04.mpirun=1.with_trilinos=true.output
Labels: Multigrid, ready to test

#16126 Make a couple of loop variables 'const'.
  tests/matrix_free/point_evaluation_27.cc
  tests/non_matching/mapping_info_03.cc
Labels: ready to test

#16128 Fix test
  tests/multigrid-global-coarsening/multigrid_p_04.cc
Labels: Reviewed and ready to merge, ready to test

#16123 Further work on AffineConstraints::add_constraint().
  include/deal.II/lac/affine_constraints.h
  include/deal.II/lac/affine_constraints.templates.h
Labels: Linear Algebra, ready to test

#16116 Minor doc updates.
  include/deal.II/base/function_lib.h
  include/deal.II/base/table.h
Labels: Documentation, Reviewed and ready to merge

#16058 Use gmres in step 12
  examples/step-12/doc/intro.dox
  examples/step-12/step-12.cc
Labels: Tutorials, Linear Algebra, ready to test

#16118 Improve an error message in IndexSet::get_view().
  source/base/index_set.cc
Labels: Parallel distributed, ready to test

#16131 Avoid a bare 'new' in step-37.
  examples/step-37/step-37.cc
Labels: Tutorials, ready to test

#16134 AffineConstraints::close(): Replace divisions by multiplication with reciprocal
  include/deal.II/lac/affine_constraints.templates.h
Labels: Reviewed and ready to merge, Linear Algebra, ready to test

#16129 Make ArrayView objects from boost::container::small_vector.
  doc/news/changes/minor/20231012Bangerth
  include/deal.II/base/array_view.h
  tests/base/array_view_22.cc
  tests/base/array_view_22.output
Labels: Infrastructure, ready to test

#16130 Clean up the documentation of PolarManifold.
  include/deal.II/grid/manifold_lib.h
Labels: Documentation

#16125 Demote an assertion from AssertThrow to Assert.
  source/particles/property_pool.cc
Labels: ready to test

#16139 Fix compute_prefix_sum() for serial run
  include/deal.II/lac/sparse_matrix_tools.h
Labels: Reviewed and ready to merge, ready to test

#16140 Remove useless (hp::DoFHandler) test
  tests/hp/n_dofs.cc
  tests/hp/n_dofs.output
Labels: Tests, hp adaptivity

#16124 Add cubic simplex elements.
  doc/news/changes/major/20231011DavidWellsPeterMunch
  source/base/polynomials_barycentric.cc
  source/fe/fe_simplex_p.cc
  tests/simplex/barycentric_01.cc
  tests/simplex/barycentric_01.output
  tests/simplex/simplex_project_cg.cc
  tests/simplex/simplex_project_cg.output
  tests/simplex/simplex_project_dg.cc
  tests/simplex/simplex_project_dg.output
Labels: ready to test, Simplices

#16132 AffineConstraints::close(): Avoid sorting of sorted list
  include/deal.II/lac/affine_constraints.templates.h
Labels: Linear Algebra, ready to test

#16147 Use PetscScalar when compressing vectors.
  include/deal.II/lac/petsc_vector_base.h
Labels: Reviewed and ready to merge, Linear Algebra, ready to test

#16136 AffineConstraints::close(): Simplify combination of constraints
  include/deal.II/lac/affine_constraints.templates.h
Labels: Linear Algebra, ready to test

#16149 Move geometric GridTools functions to a new file.
  include/deal.II/fe/mapping_q_internal.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/grid_tools_geometry.h
  source/grid/CMakeLists.txt
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
  source/grid/grid_tools_geometry.cc
  source/grid/grid_tools_geometry.inst.in
  source/grid/tria_accessor.cc
Labels: Miscellaneous, ready to test

#16155 Make ArrayView constructors more generic.
  include/deal.II/base/array_view.h
  include/deal.II/base/template_constraints.h
Labels: ready to test

#16150 Deprecate the distorted child cell function.
  include/deal.II/grid/grid_tools.h
Labels: Miscellaneous, ready to test

#16153 Make IndexSet compatible with Teuchos::RCP<Tpetra::Map>>
  doc/news/changes/minor/20231017SebastianKinnewig
  include/deal.II/base/index_set.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  source/base/index_set.cc
  source/lac/trilinos_tpetra_communication_pattern.cc
Labels: External libraries, ready to test

#16120 Make an assertion text more informative.
  source/grid/tria_description.cc
Labels: ready to test

#16026 Assert* should end with a semicolon
  include/deal.II/base/exceptions.h
  include/deal.II/lac/petsc_snes.templates.h
  include/deal.II/lac/petsc_ts.templates.h
  source/lac/petsc_communication_pattern.cc
  source/lac/petsc_compatibility.cc
  source/lac/petsc_precondition.cc
  source/lac/petsc_solver.cc
Labels: ready to test

#16145 Use AffineConstraints::add_constraint() throughout.
  examples/step-16/step-16.cc
  examples/step-37/step-37.cc
  examples/step-42/step-42.cc
  examples/step-50/step-50.cc
  examples/step-56/step-56.cc
  examples/step-63/step-63.cc
  examples/step-66/step-66.cc
  examples/step-79/step-79.cc
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/multigrid/mg_constrained_dofs.h
  include/deal.II/numerics/vector_tools_constraints.templates.h
  source/dofs/dof_tools_constraints.cc
  source/grid/grid_tools.cc
Labels: DoFs, ready to test

#16159 Check for the Trilinos version when calling getLocalNumElements.
  source/base/index_set.cc
Labels: Reviewed and ready to merge, ready to test

#16160 Move topological GridTools functions to a new file.
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/grid_tools_geometry.h
  include/deal.II/grid/grid_tools_topology.h
  source/grid/CMakeLists.txt
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
  source/grid/grid_tools_geometry.cc
  source/grid/grid_tools_geometry.inst.in
  source/grid/grid_tools_topology.cc
  source/grid/grid_tools_topology.inst.in
Labels: Reviewed and ready to merge, Miscellaneous, ready to test

#16161 Fix PBC in MGConstrainedDoFs
  doc/news/changes/minor/20231019MunchPrietoSaavedra
  include/deal.II/dofs/dof_tools.h
  include/deal.II/multigrid/mg_constrained_dofs.h
  source/dofs/dof_tools_constraints.cc
  source/dofs/dof_tools_constraints.inst.in
  tests/multigrid-global-coarsening/transfer_matrix_free_11.with_p4est=true.with_trilinos=true.mpirun=1.output
  tests/multigrid/constrained_dofs_05.output
  tests/multigrid/mg_constraints_pbc.cc
  tests/multigrid/mg_constraints_pbc.output
  tests/multigrid/transfer_matrix_free_11.with_p4est=true.with_trilinos=true.mpirun=1.output
Labels: Bug, Multigrid, ready to test

#16164 Copy periodic faces when copying triangulation
  doc/news/changes/minor/20231019PrietoSaavedraMunch
  source/grid/tria.cc
  tests/grid/copy_triangulation_pbc.cc
  tests/grid/copy_triangulation_pbc.output
Labels: Reviewed and ready to merge, ready to test

#16163 Add AffineConstraints::constrain_dof_to_zero().
  doc/news/changes/minor/20231002Bangerth_2
  examples/step-16/step-16.cc
  examples/step-37/step-37.cc
  examples/step-46/doc/intro.dox
  examples/step-46/step-46.cc
  examples/step-50/step-50.cc
  examples/step-56/step-56.cc
  examples/step-63/step-63.cc
  examples/step-66/step-66.cc
  include/deal.II/lac/affine_constraints.h
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/multigrid/mg_constrained_dofs.h
  source/dofs/dof_tools_constraints.cc
Labels: ready to test

#16175 Use std::any instead of boost::any in AnyData.
  include/deal.II/algorithms/any_data.h
Labels: Reviewed and ready to merge, ready to test, C++17

#16172 Use std::any instead of boost::any in GeneralDataStorage.
  include/deal.II/algorithms/general_data_storage.h
Labels: ready to test, C++17

#16171 Use std::any instead of boost::any.
  include/deal.II/numerics/data_postprocessor.h
Labels: ready to test, C++17

#16176 Make it not an error to call constrain_dof_to_zero() more than once. Convert a bunch of tests.
  include/deal.II/lac/affine_constraints.h
  include/deal.II/lac/affine_constraints.templates.h
  tests/data_out/data_out_curved_cells.cc
  tests/fe/fe_enriched_step-36b.cc
  tests/integrators/assembler_simple_system_inhom_01.cc
  tests/lac/affine_constraints_set_zero.cc
  tests/lac/constraint_matrix_distribute_local_global.cc
  tests/lac/constraints_01.cc
  tests/lac/constraints_hanging_nodes_bc.cc
  tests/lac/constraints_make_consistent_in_parallel_01.cc
  tests/lac/constraints_merge_12.cc
  tests/lac/constraints_move.cc
  tests/lac/constraints_zero_condense.cc
  tests/lac/inhomogeneous_constraints.cc
  tests/lac/inhomogeneous_constraints_04.cc
  tests/lac/inhomogeneous_constraints_block.cc
  tests/lac/inhomogeneous_constraints_nonsymmetric.cc
  tests/matrix_free/matrix_vector_mg.cc
  tests/matrix_free/parallel_multigrid.cc
  tests/matrix_free/parallel_multigrid_fullydistributed.cc
  tests/matrix_free/parallel_multigrid_interleave.cc
  tests/matrix_free/parallel_multigrid_interleave_renumber.cc
  tests/matrix_free/parallel_multigrid_mf.cc
  tests/matrix_free/step-37.cc
  tests/mpi/constraint_matrix_set_zero_01.cc
  tests/mpi/constraint_matrix_set_zero_02.cc
  tests/mpi/constraints_crash_01.cc
  tests/mpi/constraints_crash_02.cc
  tests/mpi/constraints_crash_03.cc
  tests/mpi/crash_05.cc
  tests/multigrid-global-coarsening/parallel_multigrid.cc
  tests/multigrid-global-coarsening/parallel_multigrid_fullydistributed.cc
  tests/multigrid-global-coarsening/parallel_multigrid_interleave.cc
  tests/multigrid-global-coarsening/parallel_multigrid_interleave_renumber.cc
  tests/multigrid-global-coarsening/parallel_multigrid_mf.cc
  tests/multigrid/constrained_dofs_07.cc
  tests/multigrid/step-16-02.cc
  tests/multigrid/step-16-03.cc
  tests/multigrid/step-16-04.cc
  tests/multigrid/step-16-05.cc
  tests/multigrid/step-16-06.cc
  tests/multigrid/step-16-07.cc
  tests/multigrid/step-16-08.cc
  tests/multigrid/step-16-50-mpi-linear-operator.cc
  tests/multigrid/step-16-50-mpi-smoother.cc
  tests/multigrid/step-16-50-mpi.cc
  tests/multigrid/step-16-50-serial.cc
  tests/multigrid/step-16-bdry1.cc
  tests/multigrid/step-16.cc
  tests/multigrid/transfer_matrix_free_13.cc
  tests/multigrid/transfer_prebuilt_05.cc
  tests/remote_point_evaluation/vector_tools_evaluate_at_points_02.cc
Labels: ready to test

#16177 Added test for hp-constraints on Q elements with Gauss-Lobatto support points.
  tests/hp/hp_constraints_q_lobatto.cc
  tests/hp/hp_constraints_q_lobatto.output
Labels: Finite Element, hp adaptivity, ready to test

#16174 Split a mutex into two, give them better names.
  include/deal.II/fe/fe_system.h
  source/fe/fe_system.cc
Labels: Finite Element, ready to test

#16173 Move objects into place rather than swapping them.
  source/fe/fe_system.cc
Labels: ready to test

#16180 Make a bunch of arguments 'const'.
  source/base/mu_parser_internal.cc
Labels: ready to test

#16184 Remove a stray comment about pointer lifetimes.
  include/deal.II/grid/tria.h
Labels: Documentation

#16183 Minor clean-up in dof_info.cc.
  source/matrix_free/dof_info.cc
Labels: Matrix-free, ready to test

#16181 Use a shared mutex instead of a unique one.
  include/deal.II/base/polynomial.h
  source/base/polynomial.cc
Labels: ready to test

#16189 Only include Kokkos_Abort.hpp in exceptions.h for Kokkos 4.2.0 and higher
  include/deal.II/base/exceptions.h
Labels: ready to test

#16190 Use std::bool_constant instead of std::integral_constant.
  include/deal.II/base/aligned_vector.h
  include/deal.II/lac/affine_constraints.h
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/trilinos_block_sparse_matrix.h
  include/deal.II/lac/vector_operations_internal.h
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/type_traits.h
  include/deal.II/matrix_free/vector_access_internal.h
  source/lac/affine_constraints.cc
  source/lac/affine_constraints.inst.in
Labels: ready to test, C++17

#16187 Move things into place, rather than swap.
  source/fe/fe_dgq.cc
  source/fe/fe_q_base.cc
  source/fe/fe_raviart_thomas_nodal.cc
  source/fe/fe_simplex_p.cc
  source/fe/fe_system.cc
Labels: ready to test

#16191 Let CITATATIONS file refer to 9.5 paper.
  CITATIONS.bib
Labels: Documentation

#16192 Fix github badges.
  README.md
Labels: Documentation

#16182 Implement a Lazy<T> wrapper providing thread safe, lazy initialization
  doc/news/changes/minor/20231025MatthiasMaier
  include/deal.II/base/lazy.h
  tests/base/lazy_01.cc
  tests/base/lazy_01.output
  tests/base/lazy_02.cc
  tests/base/lazy_02.output
  tests/base/lazy_03.cc
  tests/base/lazy_03.output
  tests/base/lazy_04.cc
  tests/base/lazy_04.threads=4.output
Labels: ready for review, ready to test

#16188 Split a mutex into two that each guard one set of variables.
  include/deal.II/fe/fe_dgq.h
  include/deal.II/fe/fe_nedelec.h
  include/deal.II/fe/fe_q_base.h
  include/deal.II/fe/fe_raviart_thomas.h
  include/deal.II/fe/fe_simplex_p.h
  source/fe/fe_dgq.cc
  source/fe/fe_nedelec.cc
  source/fe/fe_q_base.cc
  source/fe/fe_raviart_thomas_nodal.cc
  source/fe/fe_simplex_p.cc
Labels: ready to test

#16196 Allow container in NonMatching::MappingInfo reinit_faces and reinit_surface
  include/deal.II/non_matching/mapping_info.h
Labels: ready to test

#16205 Fix the assert condition in trilinos_tpetra_vector.templates.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
Labels: External libraries, ready to test

#16194 Use the standardized orientation functions in a few more places.
  source/base/qprojector.cc
  source/fe/fe.cc
Labels: Triangulation, ready to test

#16179 Use FEValues extractors, avoid explicit use of view.
  examples/step-81/step-81.cc
Labels: Tutorials, ready to test

#16207 Fix trilinos_tpetra_vector.h vector access
  include/deal.II/lac/trilinos_tpetra_vector.h
Labels: External libraries, ready to test

#16186 Python: Triangulation::write outputs a serialized mesh
  contrib/python-bindings/source/triangulation_wrapper.cc
Labels: Reviewed and ready to merge, ready to test

#16203 Use EvaluationFlags inside CUDAWrappers::FEEvaluation
  doc/news/changes/incompatibilities/20231027Munch
  examples/step-64/step-64.cc
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  include/deal.II/matrix_free/evaluation_flags.h
  tests/matrix_free/matrix_free_device_no_index_initialize.cc
  tests/matrix_free/matrix_vector_device_mf.h
Labels: GPU, Matrix-free, ready to test

#16212 Rename a variable.
  include/deal.II/lac/petsc_snes.templates.h
Labels: External libraries, ready to test

#16199 Introduce RefinementCase::all_refinement_cases().
  doc/news/changes/minor/20231026Bangerth
  include/deal.II/base/geometry_info.h
  include/deal.II/fe/fe_tools.templates.h
  source/fe/fe.cc
  source/fe/fe_dgp_nonparametric.cc
  source/fe/fe_q_bubbles.cc
  source/fe/fe_rt_bubbles.cc
Labels: Reviewed and ready to merge, ready to test

#16213 Add MemoryConsumption::memory_consumption() overloads for Lazy<T>
  include/deal.II/base/lazy.h
  include/deal.II/base/memory_consumption.h
Labels: ready for review, ready to test

#15920 Add a new feature for 2nd order symmetric tensor split
  doc/news/changes/minor/20230822TaoJin
  include/deal.II/base/symmetric_tensor.h
  tests/physics/positive_negative_split.cc
  tests/physics/positive_negative_split.output
Labels: ready to test

#16200 Periodic cleanup 1
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_orientation.h
  source/grid/grid_tools_dof_handlers.cc
  source/grid/grid_tools_dof_handlers.inst.in
  tests/dofs/dof_tools_21_b.cc
  tests/dofs/dof_tools_21_c.cc
Labels: Triangulation, ready to test

#16024 Add doxygen download action to indent
  .github/workflows/indent.yml
Labels: Documentation, Infrastructure

#16224 Fix use of flags in CUDAWrappers::MatrixFree
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  tests/performance/timing_matrix_free_kokkos.cc
Labels: Bug, Reviewed and ready to merge, GPU, ready to test
