Repository dealii/dealii, pull requests merged in 2023-11, with the labels that each got.

#16229 Replace ACCESSOR -> AccessorType.
  include/deal.II/lac/matrix_iterator.h
Labels: ready to test

#16226 Remove an unnecessary friend declaration.
  include/deal.II/lac/block_matrix_base.h
Labels: ready to test

#16227 Replace ITERATOR -> IteratorType.
  include/deal.II/dofs/dof_renumbering.h
  source/dofs/dof_renumbering.cc
Labels: ready to test

#16230 Better structure some code in the gmsh wrappers.
  include/deal.II/gmsh/utilities.h
  source/gmsh/utilities.cc
Labels: ready to test

#16225 Make sure we declare the correct classes as 'friend'.
  doc/news/changes/minor/20231031Bangerth
  include/deal.II/lac/block_matrix_base.h
  tests/lac/block_matrices_07.cc
  tests/lac/block_matrices_07.output
Labels: ready to test

#16232 Document how to impose boundary values on individual vertices.
  include/deal.II/numerics/vector_tools_boundary.h
Labels: Documentation

#16228 Replace ACCESSOR -> AccessorType and related changes.
  include/deal.II/meshworker/loop.h
Labels: ready to test

#16223 Minor code updates to GrowingVectorMemory.
  include/deal.II/lac/vector_memory.templates.h
Labels: Linear Algebra, ready to test

#16222 Better describe a mutex.
  include/deal.II/base/subscriptor.h
Labels: Documentation

#16219 Move CUDAWrapper::MatrixFree tests to new folder
  tests/matrix_free_kokkos/CMakeLists.txt
  tests/matrix_free_kokkos/coefficient_eval_device.cc
  tests/matrix_free_kokkos/coefficient_eval_device.output
  tests/matrix_free_kokkos/cuda_evaluate_1d_shape.cc
  tests/matrix_free_kokkos/cuda_evaluate_1d_shape.output
  tests/matrix_free_kokkos/cuda_evaluate_2d_shape.cc
  tests/matrix_free_kokkos/cuda_evaluate_2d_shape.output
  tests/matrix_free_kokkos/matrix_free_device_initialize_vector.cc
  tests/matrix_free_kokkos/matrix_free_device_initialize_vector.with_mpi=on.with_p4est=on.mpirun=2.output
  tests/matrix_free_kokkos/matrix_free_device_initialize_vector.with_mpi=on.with_p4est=on.with_cuda=off.mpirun=1.output
  tests/matrix_free_kokkos/matrix_free_device_initialize_vector.with_mpi=on.with_p4est=on.with_cuda=on.mpirun=1.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_01.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_01.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_02.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_02.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_03.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_03.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_03b.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_03b.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_04.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_04.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_05.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_05.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_06.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_06.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_06a.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_06a.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_06b.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_06b.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_09.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_09.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_10.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_10.with_trilinos=true.with_p4est=true.mpirun=1.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_10.with_trilinos=true.with_p4est=true.mpirun=2.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_10a.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_10a.with_trilinos=true.with_p4est=true.mpirun=1.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_10a.with_trilinos=true.with_p4est=true.mpirun=2.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_19.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_19.with_trilinos=true.with_trilinos_with_zoltan=true.mpirun=2.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_25.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_25.with_trilinos=true.with_p4est=true.mpirun=1.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_25.with_trilinos=true.with_p4est=true.mpirun=2.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_26.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_26.with_trilinos=true.with_p4est=true.mpirun=1.output
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_26.with_trilinos=true.with_p4est=true.mpirun=2.output
  tests/matrix_free_kokkos/matrix_free_device_multiple_objects.cc
  tests/matrix_free_kokkos/matrix_free_device_multiple_objects.output
  tests/matrix_free_kokkos/matrix_free_device_no_index_initialize.cc
  tests/matrix_free_kokkos/matrix_free_device_no_index_initialize.output
  tests/matrix_free_kokkos/matrix_free_device_precondition_chebyshev.cc
  tests/matrix_free_kokkos/matrix_free_device_precondition_chebyshev.with_trilinos=true.with_p4est=true.with_lapack=true.mpirun=1.output
  tests/matrix_free_kokkos/matrix_free_device_precondition_chebyshev.with_trilinos=true.with_p4est=true.with_lapack=true.mpirun=2.output
  tests/matrix_free_kokkos/matrix_free_device_reinit_01.cc
  tests/matrix_free_kokkos/matrix_free_device_reinit_01.with_mpi=on.with_p4est=on.mpirun=2.output
  tests/matrix_free_kokkos/matrix_vector_device_common.h
  tests/matrix_free_kokkos/matrix_vector_device_mf.h
Labels: GPU, ready to test

#16233 Update the documentation of SmartPointer.
  include/deal.II/base/smartpointer.h
Labels: Documentation

#16211 Minor doc updates.
  include/deal.II/base/symmetric_tensor.h
Labels: Documentation, ready to test

#16197 Compress NonMatching::MappingInfo for faces
  include/deal.II/non_matching/mapping_info.h
Labels: Matrix-free, ready to test

#16069 Fix Doxygen copydoc references
  .github/workflows/indent.yml
  include/deal.II/distributed/fully_distributed_tria.h
  include/deal.II/distributed/tria_base.h
  include/deal.II/fe/fe_system.h
  include/deal.II/fe/mapping_q_cache.h
  include/deal.II/lac/vector.h
Labels: High Priority :warning:, ready to test

#16234 Remove `hp::DoFHandler` from doxygen headers.
  doc/doxygen/headers/concepts.h
  doc/doxygen/headers/dofs.h
  doc/doxygen/headers/hp.h
  doc/doxygen/headers/iterators.h
Labels: Documentation, hp adaptivity

#16013 Fix Doxygen graphs in dark mode
  doc/doxygen/headers/main.h
  doc/doxygen/options.dox.in
  doc/doxygen/scripts/steps.pl
Labels: Documentation, Infrastructure

#16236 Extend assert message of `GridTools::exchange_cell_data()`
  include/deal.II/grid/grid_tools.h
Labels: ready to test

#16231 Release tbb::task_group data early.
  include/deal.II/base/thread_management.h
Labels: Parallel shared, ready to test

#16240 Use the standard form of lambda expressions.
  include/deal.II/lac/sparse_vanka.templates.h
  source/base/kokkos.cc
  source/dofs/dof_handler.cc
Labels: ready to test

#16242 Make a function not 'virtual'.
  include/deal.II/grid/manifold_lib.h
Labels: Manifold, ready to test

#16208 Simplify code logic.
  source/fe/fe_system.cc
Labels: ready to test

#16245 Remove workarounds for Assert* in tensor.h
  include/deal.II/base/tensor.h
Labels: Reviewed and ready to merge, ready to test

#16246 Update some more documentation to refer to our C++17 requirement.
  cmake/setup_compiler_flags_gnu.cmake
  cmake/setup_write_config.cmake
  doc/developers/cmake-internals.html
  doc/users/cmake_dealii.html
Labels: Documentation

#16247 Add some missing headers to grid_tools_topology.h.
  include/deal.II/grid/grid_tools_topology.h
Labels: Miscellaneous, ready to test

#16244 Clarify when RemotePointEvaluation is reinitialized.
  include/deal.II/numerics/vector_tools_evaluate.h
Labels: Documentation

#16253 Fix clang-tidy-17 complains
  .clang-tidy
  examples/step-87/step-87.cc
  include/deal.II/base/data_out_base.h
  include/deal.II/base/linear_index_iterator.h
  include/deal.II/base/quadrature.h
  include/deal.II/differentiation/ad/ad_number_traits.h
  include/deal.II/differentiation/sd/symengine_optimizer.h
  include/deal.II/lac/block_vector_base.h
  include/deal.II/lac/linear_operator.h
  include/deal.II/lac/petsc_vector_base.h
  source/base/data_out_base.cc
  source/base/quadrature.cc
  source/lac/petsc_vector_base.cc
Labels: ready to test

#16248 Rename internal functions.
  include/deal.II/grid/manifold_lib.h
  source/grid/manifold_lib.cc
Labels: ready to test

#16255 Make an assertion more informative.
  include/deal.II/grid/tria_accessor.templates.h
Labels: ready to test

#16258 Add a changelog entry.
  doc/news/changes/minor/20231109Bangerth
Labels: Documentation

#16257 Add another static assertion on exception types.
  include/deal.II/base/exceptions.h
Labels: Miscellaneous, ready to test

#16259 Erronius VectorTools::NormType::* has been replaced with VectorTools:…
  doc/news/8.2.1-vs-8.3.0.h
  include/deal.II/distributed/grid_refinement.h
  include/deal.II/grid/grid_refinement.h
  source/distributed/grid_refinement.cc
  source/grid/grid_refinement.cc
  tests/grid/refine_and_coarsen_fixed_fraction_03.cc
  tests/grid/refine_and_coarsen_fixed_fraction_04.cc
  tests/matrix_free/poisson_dg_hp.cc
  tests/matrix_free/step-37-inhomogeneous-1.cc
  tests/mpi/refine_and_coarsen_fixed_fraction_08.cc
  tests/mpi/refine_and_coarsen_fixed_fraction_09.cc
  tests/multigrid-global-coarsening/step-37-inhomogeneous-1.cc
  tests/remote_point_evaluation/vector_tools_evaluate_at_points_01.cc
  tests/remote_point_evaluation/vector_tools_evaluate_at_points_03.cc
  tests/remote_point_evaluation/vector_tools_evaluate_at_points_05.cc
  tests/simplex/matrix_free_02.cc
  tests/simplex/matrix_free_03.cc
  tests/simplex/matrix_free_04.cc
  tests/simplex/poisson_01.cc
  tests/simplex/step-40.cc
Labels: ready to test

#16261 Symmetric tensor cleanup
  include/deal.II/base/symmetric_tensor.h
Labels: Enhancement, Tensors, ready to test

#16262 Fix an equation in the tutorial of step-41
  doc/news/changes/minor/20231112TaoJin
  examples/step-41/doc/intro.dox
Labels: Documentation, Tutorials

#16263 SymmetricTensor: Minimize number of instructions for multiply by Tensor
  include/deal.II/base/symmetric_tensor.h
Labels: Tensors, ready to test

#16260 Document constructors and copy/move operators of Threads::Task.
  include/deal.II/base/thread_management.h
Labels: Documentation, ready to test

#16266 Mark an expression as 'constexpr'.
  include/deal.II/base/geometry_info.h
Labels: ready to test

#16185 Use std::shared_mutex in get_fe_by_name().
  include/deal.II/fe/fe_tools.templates.h
  source/fe/fe_tools.cc
Labels: ready to test, C++17

#16268 Another attempt at telling the compiler that everything is initialized.
  include/deal.II/base/geometry_info.h
Labels: ready to test

#16267 Ensure that Lazy functions are called with a callable argument.
  include/deal.II/base/lazy.h
Labels: ready to test

#16254 Add constexpr to Point ctor and member functions with unit test
  doc/news/changes/minor/20231109Yin
  include/deal.II/base/point.h
  tests/base/point_constexpr.cc
  tests/base/point_constexpr.output
Labels: ready to test

#16269 Annotate Lazy functions for 'requires' clauses.
  include/deal.II/base/lazy.h
Labels: Documentation, ready to test

#16276 Remove unused variable and header files
  source/cgal/intersections.cc
Labels: Miscellaneous, ready to test

#16270 Introduce make_rcp(...)
  doc/news/changes/minor/20231115SebastianKinnewig
  include/deal.II/base/index_set.h
  include/deal.II/base/trilinos_utilities.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  source/base/index_set.cc
  source/base/trilinos_utilities.cc
Labels: ready to test

#16280 Fix two warnings in the test suite.
  tests/lac/tensor_product_matrix_08.cc
  tests/multigrid/constrained_dofs_05.cc
Labels: Reviewed and ready to merge, Tests, ready to test

#16278 Turn make_rcp() into an inline function.
  include/deal.II/base/trilinos_utilities.h
  source/base/trilinos_utilities.cc
Labels: Reviewed and ready to merge, ready to test

#16271 Sundials: Replace realtype with sunrealtype from SUNDIALS 6.0 on
  include/deal.II/sundials/arkode.h
  include/deal.II/sundials/ida.h
  include/deal.II/sundials/kinsol.h
  include/deal.II/sundials/n_vector.templates.h
  include/deal.II/sundials/sundials_types.h
  source/sundials/arkode.cc
  source/sundials/ida.cc
  source/sundials/kinsol.cc
  source/sundials/sunlinsol_wrapper.cc
  tests/sundials/arkode_06.cc
  tests/sundials/arkode_07.cc
Labels: Reviewed and ready to merge, ready to test

#16282 Add a function to convert a Teuchos::Comm into an MPI_Comm.
  doc/news/changes/minor/20231120SebastianKinnewig
  include/deal.II/base/trilinos_utilities.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  source/base/trilinos_utilities.cc
Labels: Reviewed and ready to merge, ready to test

#16284 fix TpetraWrappers::Vector<Number>
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
Labels: Reviewed and ready to merge, ready to test

#16252 Fix `active_fe_index` query to consider cell categorization
  doc/news/changes/minor/20231113DavidSchneider
  include/deal.II/matrix_free/matrix_free.h
  tests/matrix_free/compute_diagonal_01.cc
  tests/matrix_free/compute_diagonal_01.with_p4est=true.mpirun=1.output
  tests/matrix_free/compute_diagonal_01.with_p4est=true.mpirun=3.output
Labels: ready to test

#16287 Fix vertex orientations in torus mesh
  doc/news/changes/minor/231122KronbichlerAnselmannMunch
  source/grid/grid_generator.cc
  tests/distributed_grids/create_torus_mesh.cc
  tests/distributed_grids/create_torus_mesh.output
  tests/grid/torus_01.output
Labels: Triangulation, Parallel distributed, ready to test

#16291 Share table between hyperball and torus
  source/grid/grid_generator.cc
  tests/grid/torus_01.output
Labels: Triangulation, ready to test

#16292 MGTransferMatrixFree: assert that only homogeneous or identity constraints are used
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  source/multigrid/mg_transfer_internal.cc
  tests/multigrid/transfer_matrix_free_13.cc
  tests/multigrid/transfer_matrix_free_13.output
Labels: Multigrid, ready to test

#16293 MGTransferMF: simplify code
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
Labels: Multigrid, ready to test

#16281 Periodic cleanup 2
  source/dofs/dof_tools_constraints.cc
  source/grid/grid_tools_dof_handlers.cc
Labels: Miscellaneous, ready to test

#16294 Add a test to instrument Linear Operator.
  include/deal.II/lac/linear_operator.h
  tests/lac/schur_complement_01_instrumented_vmult.cc
  tests/lac/schur_complement_01_instrumented_vmult.output
Labels: ready to test

#16297 Annotate Lazy<T> with requirements on T.
  include/deal.II/base/lazy.h
Labels: ready to test, C++20

#16295 Better document Lazy<T> and fix move semantics.
  include/deal.II/base/lazy.h
  tests/base/lazy_05.cc
  tests/base/lazy_05.output
Labels: ready to test

#16305 Better place a set of parentheses.
  source/dofs/dof_handler_policy.cc
Labels: Reviewed and ready to merge, ready to test

#16309 Remove CITATIONS.bib
  CITATIONS.bib
Labels: Reviewed and ready to merge, ready to test

#16310 Disable the PETSc reference counting check for 3.20 and newer.
  tests/tests.h
Labels: Tests, ready to test

#16302 Set CMP0074 to NEW in CMakeLists
  CMakeLists.txt
Labels: Reviewed and ready to merge, ready to test

#16306 Make the elements of FEValuesViews::Cache lazily constructed.
  doc/news/changes/minor/20231128Bangerth
  include/deal.II/base/lazy.h
  include/deal.II/fe/fe_values_base.h
  include/deal.II/fe/fe_values_views.h
  source/fe/fe_values_views.cc
Labels: ready to test

#16216 Add missing include
  doc/news/changes/incompatibilities/20231031Munch
  examples/step-87/step-87.cc
  include/deal.II/multigrid/mg_constrained_dofs.h
  include/deal.II/numerics/vector_tools_project.templates.h
  source/multigrid/CMakeLists.txt
  source/multigrid/mg_constrained_dofs.cc
  source/multigrid/mg_constrained_dofs.inst.in
  tests/grid/grid_generator_marching_cube_algorithm_02.cc
  tests/integrators/assembler_simple_matrix_03.cc
  tests/integrators/assembler_simple_matrix_03m.cc
  tests/integrators/assembler_simple_matrix_03tri.cc
  tests/integrators/assembler_simple_matrix_04.cc
  tests/matrix_free/mass_operator_04.cc
  tests/matrix_free/matrix_vector_stokes_base.cc
  tests/multigrid-global-coarsening/block_01.cc
  tests/multigrid-global-coarsening/fe_nothing_01.cc
  tests/multigrid-global-coarsening/interpolate_01.cc
  tests/multigrid-global-coarsening/interpolate_to_mg_01.cc
  tests/multigrid-global-coarsening/mg_transfer_a_01.cc
  tests/multigrid-global-coarsening/mg_transfer_a_02.cc
  tests/multigrid-global-coarsening/mg_transfer_a_03.cc
  tests/multigrid-global-coarsening/mg_transfer_a_04.cc
  tests/multigrid-global-coarsening/mg_transfer_a_05.cc
  tests/multigrid-global-coarsening/mg_transfer_p_01.cc
  tests/multigrid-global-coarsening/mg_transfer_p_02.cc
  tests/multigrid-global-coarsening/mg_transfer_p_03.cc
  tests/multigrid-global-coarsening/mg_transfer_p_04.cc
  tests/multigrid-global-coarsening/mg_transfer_p_05.cc
  tests/multigrid-global-coarsening/mg_transfer_p_06.cc
  tests/multigrid-global-coarsening/mg_transfer_p_07.cc
  tests/multigrid-global-coarsening/non_nested_transfer_01.cc
  tests/multigrid-global-coarsening/non_nested_transfer_02.cc
  tests/multigrid-global-coarsening/non_nested_transfer_03.cc
  tests/multigrid-global-coarsening/non_nested_transfer_04.cc
  tests/multigrid-global-coarsening/non_nested_transfer_05.cc
  tests/multigrid-global-coarsening/transfer_matrix_free_04.cc
  tests/multigrid/constrained_dofs_04.cc
  tests/multigrid/constrained_dofs_07.cc
  tests/multigrid/flux_sparsity_pattern_constraints.cc
  tests/multigrid/interface_matrix_entry_01.cc
  tests/multigrid/interpolate_to_mg_01.cc
  tests/multigrid/max_level_for_coarse_mesh.cc
  tests/multigrid/mg_stats_01.cc
  tests/multigrid/transfer_matrix_free_04.cc
  tests/multigrid/transfer_matrix_free_13.cc
  tests/multigrid/transfer_prebuilt_05.cc
  tests/multigrid/workload_imbalance.cc
  tests/simplex/step-67.cc
Labels: Reviewed and ready to merge, ready to test
