Repository dealii/dealii, pull requests merged in 2024-02, with the labels that each got.

#16571 More work in tria_description.h/cc.
  include/deal.II/grid/tria_description.h
  source/grid/tria_description.cc
Labels: Parallel distributed, ready to test

#16580 Add a missing template argument.
  include/deal.II/base/template_constraints.h
Labels: External libraries, ready to test

#16579 Provide an example of use for DEAL_II_NOT_IMPLEMENTED().
  include/deal.II/base/exceptions.h
Labels: Documentation, ready to test

#16577 [main] take over point release changelog entry
  doc/news/9.5.0-vs-9.5.2.h
Labels: Documentation

#16582 Require support for attribute [[assume]] for C++23 support
  cmake/checks/check_01_cxx_features.cmake
Labels: ready to test

#16584 Fix mpi/local_size
  tests/mpi/local_size.with_trilinos_with_tpetra=on.with_petsc=on.mpirun=4.output
Labels: Reviewed and ready to merge, ready to test

#16394 Add factory functions for FERemoteEvaluationCommunicator
  doc/news/changes/minor/20231231Heinz
  include/deal.II/matrix_free/fe_remote_evaluation.h
  tests/matrix_free/fe_remote_evaluation_03.cc
  tests/matrix_free/fe_remote_evaluation_03.with_p4est=true.mpirun=1.with_cgal=true.output
  tests/matrix_free/fe_remote_evaluation_03.with_p4est=true.mpirun=2.with_cgal=true.output
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#16585 Simplify step-7 somewhat.
  examples/step-7/step-7.cc
Labels: Tutorials, ready to test

#16583 Use DEAL_II_CXX23_ASSERT in the Tensor class.
  include/deal.II/base/tensor.h
Labels: Infrastructure, ready to test

#16587 Use correct function names in test
  tests/matrix_free/fe_remote_evaluation_03.cc
Labels: Tests, ready to test

#16591 Simplify some calls to make_array_view().
  source/grid/manifold.cc
Labels: Enhancement, ready to test

#16590 Enable a couple unit tests for LinearAlgebra::TpetraWrappers::Vector
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  tests/lac/linear_operator_04.cc
  tests/lac/vector_reinit_02.cc
Labels: ready to test

#16597 Tpetra: fix lac/vector_reinit_02
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  tests/lac/vector_reinit_02.cc
  tests/lac/vector_reinit_02.with_trilinos=true.with_trilinos_with_tpetra=off.output
  tests/lac/vector_reinit_02.with_trilinos=true.with_trilinos_with_tpetra=on.output
Labels: ready to test

#16532 Fix performance quadrature generator
  include/deal.II/base/lazy.h
  source/non_matching/quadrature_generator.cc
Labels: Finite Element, ready to test

#16596 NonMatching::MappingInfo: Remove quadrature projection
  include/deal.II/non_matching/mapping_info.h
Labels: Matrix-free, ready to test

#16593 More minor edits to tria_description.cc.
  source/grid/tria_description.cc
Labels: Reviewed and ready to merge, Triangulation, ready to test

#16594 Better document problems with failed MPI I/O calls.
  include/deal.II/base/data_out_base.h
Labels: Documentation

#16592 Better document one aspect of what you can't do with ghosted vectors.
  doc/doxygen/headers/glossary.h
  include/deal.II/base/exceptions.h
Labels: ready to test

#16598 Tpetra: Enable lac/linear_operator_15
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  source/lac/trilinos_tpetra_sparse_matrix.cc
  tests/lac/linear_operator_15.cc
Labels: Reviewed and ready to merge, ready to test

#16601 Better document a funny construct.
  examples/step-31/step-31.cc
  examples/step-55/step-55.cc
Labels: Documentation, Tutorials, ready to test

#16599 Explain how DEAL_II_ASSERT_UNREACHABLE() is used.
  examples/step-7/step-7.cc
  include/deal.II/base/exceptions.h
Labels: ready to test

#16603 Fix deal.II CMake flag in Tpetra configure warning
  cmake/configure/configure_20_trilinos.cmake
Labels: Reviewed and ready to merge

#16604 Tpetra: Replace TrilinosScalar
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
  include/deal.II/lac/trilinos_tpetra_vector.h
Labels: Reviewed and ready to merge, ready to test

#16606 Fix compilation error arising with Intel ICC compiler in `trilinos_tpetra_sparsity_pattern.cc`
  source/lac/trilinos_tpetra_sparsity_pattern.cc
Labels: Reviewed and ready to merge, ready to test

#16600 Convert tutorials to use DEAL_II_ASSERT_UNREACHABLE().
  examples/step-17/step-17.cc
  examples/step-34/step-34.cc
  examples/step-35/step-35.cc
  examples/step-50/step-50.cc
  examples/step-6/doc/results.dox
  examples/step-62/step-62.cc
  examples/step-68/step-68.cc
Labels: Tutorials, ready to test

#16609 Fix 64-bit compilation with old PETSc versions.
  source/lac/petsc_communication_pattern.cc
Labels: Reviewed and ready to merge, External libraries, ready to test

#16615 FlexibleIndexStorage: fix memory allocation
  source/base/mpi_compute_index_owner_internal.cc
Labels: Multigrid, ready to test

#16612 fix strip_comments target
  cmake/macros/macro_deal_ii_invoke_autopilot.cmake
Labels: ready to test

#16613 Implementation for TpetraWrappers::Vector::operator Number()
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
Labels: Reviewed and ready to merge, ready to test

#16616 Tpetra: Implement operator(), el(), and diag_element() for SparseMatrix
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
  tests/trilinos_tpetra/01.cc
  tests/trilinos_tpetra/01.output
  tests/trilinos_tpetra/02.cc
  tests/trilinos_tpetra/02.output
  tests/trilinos_tpetra/03a.cc
  tests/trilinos_tpetra/03a.output
  tests/trilinos_tpetra/04.cc
  tests/trilinos_tpetra/04.output
  tests/trilinos_tpetra/05.cc
  tests/trilinos_tpetra/05.output
  tests/trilinos_tpetra/09.cc
  tests/trilinos_tpetra/09.output
  tests/trilinos_tpetra/CMakeLists.txt
Labels: Reviewed and ready to merge, ready to test

#16620 Fix the name by which we reference an exception class.
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
Labels: ready to test

#16625 Add tests for deal.II solvers with TpetraWrappers classes
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  tests/trilinos_tpetra/deal_solver_01.cc
  tests/trilinos_tpetra/deal_solver_01.output
  tests/trilinos_tpetra/deal_solver_02.cc
  tests/trilinos_tpetra/deal_solver_02.output
  tests/trilinos_tpetra/deal_solver_03.cc
  tests/trilinos_tpetra/deal_solver_03.output
  tests/trilinos_tpetra/deal_solver_04.cc
  tests/trilinos_tpetra/deal_solver_04.output
  tests/trilinos_tpetra/deal_solver_05.cc
  tests/trilinos_tpetra/deal_solver_05.output
  tests/trilinos_tpetra/deal_solver_06.cc
  tests/trilinos_tpetra/deal_solver_06.output
Labels: Reviewed and ready to merge, ready to test

#16626 Tpetra: Fix compiling with Trilinos versions prior to 13.2
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
Labels: Reviewed and ready to merge, ready to test

#16628 Specify when Tpetra tests should be run
  tests/trilinos_tpetra/CMakeLists.txt
Labels: Reviewed and ready to merge, ready to test

#16617 CMake: make sure that bundled include directory gets created
  bundled/CMakeLists.txt
Labels: Build system, ready to test

#16619 FEFaceEvaluation + DG + hp: fix quadrature indexing
  doc/news/changes/minor/20240209BergbauerMunchRitthalerSchreter
  include/deal.II/matrix_free/fe_evaluation.h
  tests/matrix_free/hp_dg_01.cc
  tests/matrix_free/hp_dg_01.output
Labels: Bug, Matrix-free, ready to test

#16631 ConsensusAlgorithmsPayload: switch internal data type
  include/deal.II/base/mpi_compute_index_owner_internal.h
  source/base/mpi_compute_index_owner_internal.cc
Labels: Parallel distributed, ready to test

#16630 Add colorize option to cylinder_shell
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  source/grid/grid_generator_from_name.cc
  tests/grid/grid_generator_cylinder_shell_colorized.cc
  tests/grid/grid_generator_cylinder_shell_colorized.output
Labels: ready for review, ready to test, Meshes

#16610 Also instantiate the Trilinos Tpetra VectorReference class.
  source/lac/trilinos_tpetra_vector.cc
Labels: ready to test

#16607 Improve the error message we get for DEAL_II_ASSERT_UNREACHABLE().
  include/deal.II/base/exceptions.h
Labels: Infrastructure, ready to test

#16608 Work around an issue in Teuchos::rcpFromRef() with types only forward declared.
  source/lac/trilinos_tpetra_communication_pattern.cc
Labels: External libraries, ready to test

#16634 MPI compute index owner: improve documentation of flag
  include/deal.II/base/mpi_compute_index_owner_internal.h
Labels: Documentation

#16497 Move matrix free classes from CUDAWrappers namespace to Portable namespace
  doc/news/changes/minor/20240209BrunoTurcksin
  examples/step-64/doc/results.dox
  examples/step-64/step-64.cc
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  include/deal.II/matrix_free/cuda_hanging_nodes_internal.h
  include/deal.II/matrix_free/cuda_matrix_free.h
  include/deal.II/matrix_free/cuda_matrix_free.templates.h
  include/deal.II/matrix_free/cuda_tensor_product_kernels.h
  include/deal.II/matrix_free/portable_fe_evaluation.h
  include/deal.II/matrix_free/portable_hanging_nodes_internal.h
  include/deal.II/matrix_free/portable_matrix_free.h
  include/deal.II/matrix_free/portable_matrix_free.templates.h
  include/deal.II/matrix_free/portable_tensor_product_kernels.h
  source/matrix_free/CMakeLists.txt
  source/matrix_free/portable_matrix_free.cc
  tests/matrix_free_kokkos/coefficient_eval_device.cc
  tests/matrix_free_kokkos/evaluate_1d_shape.cc
  tests/matrix_free_kokkos/evaluate_1d_shape.output
  tests/matrix_free_kokkos/evaluate_2d_shape.cc
  tests/matrix_free_kokkos/evaluate_2d_shape.output
  tests/matrix_free_kokkos/matrix_free_device_initialize_vector.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_10.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_10a.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_19.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_25.cc
  tests/matrix_free_kokkos/matrix_free_device_matrix_vector_26.cc
  tests/matrix_free_kokkos/matrix_free_device_multiple_objects.cc
  tests/matrix_free_kokkos/matrix_free_device_no_index_initialize.cc
  tests/matrix_free_kokkos/matrix_free_device_precondition_chebyshev.cc
  tests/matrix_free_kokkos/matrix_free_device_reinit_01.cc
  tests/matrix_free_kokkos/matrix_vector_device_common.h
  tests/matrix_free_kokkos/matrix_vector_device_mf.h
Labels: Discussion, ready to test

#16637 Fix Tpetra vector element access.
  include/deal.II/lac/trilinos_tpetra_vector.h
Labels: External libraries, ready to test

#16629 GitHub CI: Test building with Trilinos+Tpetra
  .github/workflows/linux.yml
  cmake/configure/configure_20_trilinos.cmake
Labels: Infrastructure, ready to test

#16649 Add missing <optional> header for trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.h
Labels: Reviewed and ready to merge, ready to test

#16648 Tpetra: Add frobenius_norm to SparseMatrix
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
Labels: ready to test

#16653 Fix segmentation fault when using mpich
  include/deal.II/base/mpi.h
  source/base/mpi.cc
Labels: ready to test

#16633 MG transfer global coarsening: Avoid sending empty messages
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
Labels: Multigrid, Parallel distributed, ready to test

#16632 GridTools::compute_active_cell_halo_layer() for periodic meshes
  doc/news/changes/minor/20240212Munch
  source/dofs/dof_tools_constraints.cc
  source/grid/grid_tools_dof_handlers.cc
  tests/sharedtria/pbc_01.cc
  tests/sharedtria/pbc_01.mpirun=2.output
Labels: Bug, Parallel shared, ready to test

#16645 SUNDIALS N_Vector: implement efficient operations
  doc/news/changes/minor/20240215Proell
  include/deal.II/sundials/n_vector.templates.h
  tests/sundials/n_vector.cc
  tests/sundials/n_vector.mpirun=1.with_trilinos=off.with_petsc=on.output
  tests/sundials/n_vector.mpirun=1.with_trilinos=on.with_petsc=off.output
  tests/sundials/n_vector.mpirun=1.with_trilinos=true.with_petsc=true.output
  tests/sundials/n_vector.mpirun=2.with_trilinos=true.with_petsc=true.output
Labels: Reviewed and ready to merge, ready to test

#16654 Only enable a function if a template type is right.
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
  source/lac/trilinos_tpetra_sparse_matrix.cc
Labels: ready to test

#16657 Assert that we only extrude quadrilateral meshes.
  source/grid/grid_generator.cc
Labels: Reviewed and ready to merge, Miscellaneous, ready to test

#16658 Find active cell around point simplices 9.5
  include/deal.II/grid/grid_tools.h
  source/grid/grid_tools.cc
  source/grid/grid_tools_dof_handlers.cc
  source/grid/grid_tools_dof_handlers.inst.in
  tests/remote_point_evaluation/find_all_active_cells_around_point_01.cc
  tests/remote_point_evaluation/find_all_active_cells_around_point_01.output
Labels: Reviewed and ready to merge, ready to test

#16602 Add SolverDirect for Tpetra Wrappers
  cmake/configure/configure_20_trilinos.cmake
  doc/doxygen/options.dox.in
  include/deal.II/base/config.h.in
  include/deal.II/lac/trilinos_tpetra_solver_direct.h
  include/deal.II/lac/trilinos_tpetra_solver_direct.templates.h
  source/lac/CMakeLists.txt
  source/lac/trilinos_tpetra_solver_direct.cc
  tests/trilinos_tpetra/direct_solver_01.cc
  tests/trilinos_tpetra/direct_solver_01.with_p4est=true.with_trilinos_with_amesos2=true.mpirun=1.output
  tests/trilinos_tpetra/direct_solver_02.cc
  tests/trilinos_tpetra/direct_solver_02.with_p4est=true.with_trilinos_with_amesos2=true.mpirun=1.output
Labels: ready to test

#16664 Add a comparison operator to LA::TpetraWrappers::Vector
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
Labels: Reviewed and ready to merge, ready to test

#16660 Remove verbose output from Tpetra direct solver
  include/deal.II/lac/trilinos_tpetra_solver_direct.h
  include/deal.II/lac/trilinos_tpetra_solver_direct.templates.h
  tests/trilinos_tpetra/direct_solver_01.cc
Labels: Reviewed and ready to merge, ready to test

#16588 Add TpetraWrapper::BlockVector and TpetraWrappers::BlockSparseMatrix
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/trilinos_tpetra_block_sparse_matrix.h
  include/deal.II/lac/trilinos_tpetra_block_sparse_matrix.templates.h
  include/deal.II/lac/trilinos_tpetra_block_vector.h
  include/deal.II/lac/trilinos_tpetra_block_vector.templates.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  source/lac/CMakeLists.txt
  source/lac/affine_constraints.inst.in
  source/lac/trilinos_tpetra_block_sparse_matrix.cc
  source/lac/trilinos_tpetra_block_vector.cc
Labels: Reviewed and ready to merge, ready to test

#16668 Make LA::TpetraWrappers::SparseMatrix::copy_from compatible with older Trilinos versions.
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
Labels: Reviewed and ready to merge, ready to test

#16669 Fix bundled boost 1.70.0 to avoid using std::unary_function
  bundled/boost-1.70.0/include/boost/container_hash/hash.hpp
Labels: Reviewed and ready to merge, ready to test

#16651 Add the remaining SUNDIALS 7 output variants.
  tests/sundials/arkode_08.output.sundials7
  tests/sundials/arkode_10.output.sundials7
  tests/sundials/arkode_11.output.sundials7
Labels: ready to test

#16457 [C++23] When using C++23, use [[assume]] attribute.
  include/deal.II/base/config.h.in
  include/deal.II/base/exceptions.h
Labels: ready to test, C++23

#16650 Add output variants for SUNDIALS 7.
  tests/sundials/arkode_04.output.sundials7
  tests/sundials/arkode_09.output.sundials7
  tests/sundials/ida_03.output.sundials7
  tests/sundials/ida_05.output.sundials7
Labels: ready to test

#16672 Tpetra: Implement Vector::is_non_negative
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  tests/trilinos_tpetra/57.cc
  tests/trilinos_tpetra/57.output
Labels: Reviewed and ready to merge, ready to test

#16673 Fix `make_flux_sparsity_pattern` for `FENothing`
  doc/news/changes/minor/20240219SchreterRitthaler
  include/deal.II/lac/affine_constraints.templates.h
  tests/hp/flux_sparsity_03.cc
  tests/hp/flux_sparsity_03.output
Labels: Reviewed and ready to merge, ready to test

#16677 Add Tpetra SparseMatrix::matrix_scalar_product() and matrix_norm_square().
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
  source/lac/petsc_matrix_base.cc
  source/lac/trilinos_sparse_matrix.cc
  tests/trilinos_tpetra/sparse_matrix_vector_05.cc
  tests/trilinos_tpetra/sparse_matrix_vector_05.output
  tests/trilinos_tpetra/sparse_matrix_vector_06.cc
  tests/trilinos_tpetra/sparse_matrix_vector_06.output
  tests/trilinos_tpetra/sparse_matrix_vector_07.cc
  tests/trilinos_tpetra/sparse_matrix_vector_07.output
Labels: ready to test

#16670 Use size_type as return type of SparseMatrix::m().
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
Labels: ready to test

#16674 CMake: honor `optimized`,`debug`, and `general` keywords in `LIBRARIES` and `TARGETS`
  cmake/macros/macro_process_feature.cmake
Labels: ready for review, ready to test

#16676 Tpetra: Add SparseMatrix::clear_row[s]
  include/deal.II/lac/petsc_matrix_base.h
  include/deal.II/lac/trilinos_sparse_matrix.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
  source/lac/petsc_matrix_base.cc
  source/lac/trilinos_sparse_matrix.cc
  tests/trilinos_tpetra/62.cc
  tests/trilinos_tpetra/62.output
  tests/trilinos_tpetra/64.cc
  tests/trilinos_tpetra/64.output
  tests/trilinos_tpetra/66.cc
  tests/trilinos_tpetra/66.output
  tests/trilinos_tpetra/67.cc
  tests/trilinos_tpetra/67.output
  tests/trilinos_tpetra/68.cc
  tests/trilinos_tpetra/68.output
  tests/trilinos_tpetra/69.cc
  tests/trilinos_tpetra/69.output
Labels: ready to test

#16679 Tpetra: Fix compiling with complex values
  include/deal.II/lac/read_write_vector.templates.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
Labels: ready to test

#16683 Tpetra: Fix instantiations for SolverDirect* with complex number types
  source/lac/trilinos_tpetra_solver_direct.cc
Labels: Reviewed and ready to merge, ready to test

#16681 Minor efficiency improvement.
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
  source/lac/petsc_matrix_base.cc
Labels: Reviewed and ready to merge, ready to test

#16682 GitHub CI: Also compile matrix_free_kokkos tests in CUDA CI
  .github/workflows/linux.yml
Labels: Reviewed and ready to merge

#16680 Minor updates to the documentation of a few functions.
  include/deal.II/multigrid/mg_transfer_global_coarsening.h
  include/deal.II/numerics/vector_tools_interpolate.h
Labels: Documentation, ready to test

#16659 Update Trilinos readme.
  doc/external-libs/trilinos.html
Labels: Documentation

#16663 Declare conversion assignments for Tpetra vectors.
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  include/deal.II/lac/vector.h
  include/deal.II/lac/vector.templates.h
  source/lac/trilinos_tpetra_vector.cc
  source/lac/vector.cc
Labels: Reviewed and ready to merge, ready to test

#16690 Fix typo one ':' between class names
  examples/step-64/step-64.cc
  include/deal.II/arborx/distributed_tree.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/lac/trilinos_tpetra_sparsity_pattern.h
Labels: Documentation, Reviewed and ready to merge, ready to test

#16691 `ParticleHandler`: use tolerance for is_inside_unit_cell() check
  doc/news/changes/minor/20240222SchreterBrotz
  include/deal.II/particles/particle_handler.h
  source/particles/particle_handler.cc
  tests/particles/particle_handler_sort_02.cc
  tests/particles/particle_handler_sort_02.with_mpi=true.with_p4est=true.output
Labels: Mapping, Particles, ready to test

#16666 Relicensing: require all new contributions to be dual licensed
  CONTRIBUTING.md
  LICENSE.md
  doc/README.md
  doc/readme.html
Labels: ready for review, ready to test

#16697 Mailmap: add missing entries
  .mailmap
Labels: High Priority :warning:

#16695 MatrixFree: Fix function name in docu
  include/deal.II/matrix_free/matrix_free.h
Labels: Documentation

#16689 contrib/utilities/update-copyright.sh: several improvements
  contrib/utilities/update-copyright.sh
Labels: ready for review

#16694 Fix issue with colorized cylinder shell
  doc/news/changes/minor/20240227Blais
  source/grid/grid_generator.cc
  tests/grid/grid_generator_cylinder_shell_colorized.cc
  tests/grid/grid_generator_cylinder_shell_colorized.output
Labels: Triangulation, ready to test

#16614 Template TpetraWrappers::SparseMatrix::vmult on the vector type.
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
  source/lac/trilinos_tpetra_sparse_matrix.cc
Labels: ready to test
