Repository dealii/dealii, pull requests merged in 2024-01, with the labels that each got.

#16397 Make a couple of functions 'private'.
  include/deal.II/lac/trilinos_sparse_matrix.h
Labels: ready to test

#16398 Deal with IndexSet operations in a more efficient way.
  source/lac/trilinos_sparse_matrix.cc
Labels: ready to test

#16396 Remove a likely mistaken attribute.
  include/deal.II/base/mpi_consensus_algorithms.h
Labels: ready to test

#16374 Convert CreateDescriptionFromTriangulationHelper into a function.
  source/grid/tria_description.cc
Labels: Triangulation, ready to test

#16399 Optimize setting a matrix to zero.
  source/lac/trilinos_sparse_matrix.cc
Labels: ready to test

#16402 Change a few variable names.
  source/grid/grid_in.cc
Labels: ready to test

#16401 Avoid a global 'typedef' and qualify things locally.
  source/lac/trilinos_sparse_matrix.cc
Labels: ready to test

#16405 Avoid dynamic memory allocation when we know that we won't need it.
  source/lac/trilinos_sparse_matrix.cc
Labels: ready to test

#16408 Simplify some locations.
  source/lac/trilinos_sparsity_pattern.cc
Labels: ready to test

#16409 Push a variable declaration down to its first use.
  source/lac/trilinos_sparsity_pattern.cc
Labels: ready to test

#16410 Unify if-else branches with common code.
  source/lac/trilinos_sparsity_pattern.cc
Labels: ready to test

#16404 Do not mark a pointer as 'mutable' where not necessary.
  include/deal.II/lac/trilinos_sparsity_pattern.h
Labels: ready to test

#16411 Move the error check next to the checked statement.
  source/lac/trilinos_vector.cc
Labels: ready to test

#16403 Use prefix ++ universally.
  examples/step-32/step-32.cc
  examples/step-75/step-75.cc
  include/deal.II/base/partitioner.templates.h
  include/deal.II/base/vectorization.h
  include/deal.II/grid/connectivity.h
  include/deal.II/hp/collection.h
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/block_vector_base.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/petsc_matrix_base.h
  include/deal.II/lac/read_write_vector.h
  include/deal.II/lac/solver_cg.h
  include/deal.II/lac/solver_qmrs.h
  include/deal.II/lac/trilinos_vector.h
  include/deal.II/lac/vector.h
  include/deal.II/matrix_free/constraint_info.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/optimization/line_minimization.h
  include/deal.II/optimization/solver_bfgs.h
  include/deal.II/trilinos/nox.templates.h
  source/base/data_out_base.cc
  source/base/function_signed_distance.cc
  source/base/mpi_compute_index_owner_internal.cc
  source/dofs/dof_handler.cc
  source/dofs/dof_tools_constraints.cc
  source/fe/fe_q_bubbles.cc
  source/fe/fe_q_dg0.cc
  source/grid/grid_generator.cc
  source/grid/grid_out.cc
  source/grid/grid_tools.cc
  source/grid/grid_tools_dof_handlers.cc
  source/grid/grid_tools_topology.cc
  source/grid/tria.cc
  source/lac/petsc_communication_pattern.cc
  source/lac/solver_control.cc
  source/lac/trilinos_sparse_matrix.cc
  source/matrix_free/task_info.cc
  source/numerics/data_out_resample.cc
  source/numerics/matrix_tools_once.cc
  source/numerics/point_value_history.cc
  source/particles/particle_handler.cc
  source/sundials/ida.cc
Labels: ready to test

#16419 Indent: format also change-log entries
  contrib/utilities/indent
  contrib/utilities/indent-all
  doc/news/changes/incompatibilities/20221209Munch
  doc/news/changes/incompatibilities/202306230DanielArndt
  doc/news/changes/incompatibilities/20230703DanielArndt-3
  doc/news/changes/incompatibilities/20231031Munch
  doc/news/changes/major/20230905SchreterMunch
  doc/news/changes/minor/20230412LucaHeltai
  doc/news/changes/minor/20230630MatthiasMaier
  doc/news/changes/minor/20230707BrunoBlais
  doc/news/changes/minor/20230725Munch
  doc/news/changes/minor/20230730AbbasBallout
  doc/news/changes/minor/20230801Munch_3
  doc/news/changes/minor/20230822TaoJin
  doc/news/changes/minor/20230915Thiele
  doc/news/changes/minor/20230916Thiele
  doc/news/changes/minor/20230917SchreterMunch_2
  doc/news/changes/minor/20231017SebastianKinnewig
  doc/news/changes/minor/20231019PrietoSaavedraMunch
  doc/news/changes/minor/20231109Yin
  doc/news/changes/minor/20231226VladimirIvannikov
Labels: Documentation

#16418 Remove unnecessary change-log entries
  doc/news/changes/incompatibilities/20230627MatthiasMaier
  doc/news/changes/major/20230627MatthiasMaier
  doc/news/changes/minor/20230627MatthiasMaier
Labels: Documentation

#16417 Simplify code internal::extract_remote_rows()
  include/deal.II/lac/sparse_matrix_tools.h
Labels: ready to test

#16416 Fix allocation in TrilinosWrappers::SparseMatrix::AccessorBase
  source/lac/trilinos_sparse_matrix.cc
Labels: Reviewed and ready to merge, ready to test

#16420 Fix TrilinosWrappers::SparsityPattern::Accessor::visit_present_row()
  source/lac/trilinos_sparsity_pattern.cc
Labels: Reviewed and ready to merge, ready to test

#16421 Fix variable name.
  include/deal.II/base/polynomials_barycentric.h
Labels: ready to test

#16422 FPE: split up declaration and definition
  include/deal.II/matrix_free/fe_point_evaluation.h
Labels: ready to test

#16429 Fix the indent script.
  contrib/utilities/indent
  contrib/utilities/indent-all
Labels: High Priority :warning:, Reviewed and ready to merge, ready to test

#16434 Boost-1.83 compatibility: remove long double overloads of special functions
  cmake/checks/check_01_cxx_features.cmake
  doc/news/changes/incompatibilities/20240108Maier
  include/deal.II/base/std_cxx17/cmath.h
Labels: ready for review, ready to test

#16426 Add a test.
  doc/news/changes/minor/20240107Wiesheier
  tests/trilinos/trilinos_sparsity_pattern_iterators_03.cc
  tests/trilinos/trilinos_sparsity_pattern_iterators_03.mpirun=1.output
  tests/trilinos/trilinos_sparsity_pattern_iterators_03.mpirun=2.output
Labels: ready to test

#16430 Add another test.
  tests/trilinos/sparse_matrix_iterator_02.cc
  tests/trilinos/sparse_matrix_iterator_02.mpirun=1.output
  tests/trilinos/sparse_matrix_iterator_02.mpirun=2.output
Labels: ready to test

#16391 Hand back used quadratures during conversion of intersections to points
  doc/news/changes/minor/20231229Heinz
  include/deal.II/grid/grid_tools.h
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
  tests/remote_point_evaluation/convert_intersections_to_rpe_data_01.cc
  tests/remote_point_evaluation/convert_intersections_to_rpe_data_02.cc
  tests/remote_point_evaluation/convert_intersections_to_rpe_data_03.cc
  tests/remote_point_evaluation/convert_intersections_to_rpe_data_04.cc
  tests/remote_point_evaluation/setup_rpe_with_intersections_02.cc
Labels: ready to test

#16432 Template VectorType in TrilinosWrappers::SparseMatrix::residual()
  include/deal.II/lac/trilinos_sparse_matrix.h
  source/lac/trilinos_sparse_matrix.cc
Labels: Reviewed and ready to merge, ready to test

#16436 rename template parameters
  include/deal.II/cgal/intersections.h
  source/cgal/intersections.cc
  source/cgal/intersections.inst.in
Labels: ready to test

#16288 Add a Tpetra-based version of Trilinos SparseMatrix and SparsityPattern.
  cmake/config/template-arguments.in
  cmake/configure/configure_20_trilinos.cmake
  doc/news/changes/major/20231122SebastianKinnewig
  include/deal.II/base/template_constraints.h
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
  include/deal.II/lac/trilinos_tpetra_sparsity_pattern.h
  source/lac/CMakeLists.txt
  source/lac/affine_constraints.inst.in
  source/lac/trilinos_tpetra_sparse_matrix.cc
  source/lac/trilinos_tpetra_sparsity_pattern.cc
Labels: ready to test

#16440 Change accidental unicode character.
  examples/step-82/step-82.cc
Labels: ready to test

#16442 Better document Utilities::pow(). Also make it 'constexpr'.
  include/deal.II/base/utilities.h
Labels: ready to test

#16424 Rename some functions in CUDAWrappers::EvaluatorTensorProduct
  include/deal.II/matrix_free/cuda_fe_evaluation.h
  include/deal.II/matrix_free/cuda_tensor_product_kernels.h
Labels: GPU, Matrix-free, ready to test

#16439 Make Utilities::pow() available for floating point types.
  include/deal.II/base/utilities.h
Labels: ready to test

#16448 Fix compatibility issues of TpetraWrappers with older Trilinos versions.
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
  include/deal.II/lac/trilinos_tpetra_sparsity_pattern.h
  source/lac/trilinos_tpetra_sparsity_pattern.cc
Labels: ready to test

#16443 Minor doc updates to the sparse direct solvers.
  include/deal.II/lac/petsc_solver.h
  include/deal.II/lac/sparse_direct.h
  source/lac/petsc_solver.cc
Labels: Documentation, ready to test

#16454 Avoid using two temporary vectors when not necessary.
  include/deal.II/numerics/data_out_dof_data.templates.h
Labels: ready to test

#16452 Address more places where we call std::pow.
  source/base/function_lib.cc
  source/base/quadrature_lib.cc
  source/fe/fe_q_hierarchical.cc
  source/grid/grid_generator.cc
  source/grid/grid_refinement.cc
  source/grid/grid_tools.cc
  source/grid/tria.cc
  source/hp/refinement.cc
Labels: ready to test

#16456 Fix constraint_info.h for g++-13 on MacOS X
  include/deal.II/matrix_free/constraint_info.h
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#16450 Avoid a warning.
  source/lac/trilinos_tpetra_sparsity_pattern.cc
Labels: ready to test

#16437 Add a DEAL_II_ASSUME macro.
  cmake/setup_compiler_flags_gnu.cmake
  include/deal.II/base/exceptions.h
  source/fe/fe_q_base.cc
  source/grid/grid_generator.cc
Labels: Reviewed and ready to merge, ready to test

#16459 Export C++23 status to config.h.
  cmake/checks/check_01_cxx_features.cmake
  include/deal.II/base/config.h.in
Labels: ready to test

#16461 Fix a doc issue.
  include/deal.II/base/tensor.h
Labels: Documentation

#16460 Simplify a function's implementation for tensors.
  include/deal.II/base/tensor.h
Labels: ready to test, C++17

#16451 Fix the type of an array.
  include/deal.II/lac/trilinos_tpetra_sparsity_pattern.h
Labels: External libraries, ready to test

#16449 Use Utilities::fixed_power() in step-82.
  examples/step-82/step-82.cc
Labels: Tutorials, ready to test

#16431 Document what a collective operation actually is.
  doc/doxygen/headers/glossary.h
  include/deal.II/base/mpi.h
  include/deal.II/distributed/tria.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/grid_tools_cache.h
  include/deal.II/grid/grid_tools_geometry.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/petsc_sparse_matrix.h
  include/deal.II/lac/petsc_vector.h
  include/deal.II/lac/petsc_vector_base.h
  include/deal.II/lac/trilinos_block_sparse_matrix.h
  include/deal.II/lac/trilinos_sparse_matrix.h
  include/deal.II/lac/trilinos_sparsity_pattern.h
  include/deal.II/lac/trilinos_vector.h
  include/deal.II/lac/vector.h
Labels: Documentation, ready to test

#16462 step-32: move initial guess assignment
  examples/step-32/step-32.cc
Labels: Tutorials, ready to test

#16466 Fix a trilinos array type.
  source/lac/trilinos_tpetra_sparsity_pattern.cc
Labels: Reviewed and ready to merge, ready to test

#16467 Simplify Tensor::unroll().
  include/deal.II/base/tensor.h
Labels: Tensors, ready to test

#16330 exchange refinement flags
  source/distributed/tria.cc
  tests/examples/step-40.mpirun=2.with_p4est=true.with_petsc=true.output
  tests/matrix_free/cell_categorization.with_p4est=true.mpirun=7.output
  tests/matrix_free/cell_categorization.with_p4est=true.mpirun=7.output.avx
  tests/matrix_free/cell_categorization.with_p4est=true.mpirun=7.output.novec
  tests/mpi/affine_constraints_get_view_01.with_trilinos=true.mpirun=2.output
  tests/mpi/affine_constraints_get_view_01.with_trilinos=true.mpirun=4.output
  tests/mpi/count_dofs_per_block_02.mpirun=10.with_p4est=true.output
  tests/mpi/count_dofs_per_block_02.mpirun=4.with_p4est=true.output
  tests/mpi/interpolate_to_different_mesh_01.with_trilinos=true.mpirun=3.with_p4est=true.output
  tests/mpi/p4est_2d_constraintmatrix_03.with_trilinos=true.mpirun=10.with_p4est=true.output
  tests/mpi/p4est_2d_constraintmatrix_03.with_trilinos=true.mpirun=4.with_p4est=true.output
  tests/mpi/p4est_2d_refine_03.mpirun=10.with_p4est=true.output
  tests/mpi/p4est_2d_refine_03.mpirun=4.with_p4est=true.output
  tests/mpi/p4est_3d_constraintmatrix_01.mpirun=10.with_p4est=true.output
  tests/mpi/p4est_3d_constraintmatrix_01.mpirun=4.with_p4est=true.output
  tests/mpi/p4est_3d_constraintmatrix_02.with_trilinos=true.mpirun=10.with_p4est=true.output
  tests/mpi/p4est_3d_constraintmatrix_02.with_trilinos=true.mpirun=4.with_p4est=true.output
  tests/mpi/p4est_3d_refine_01.mpirun=10.with_p4est=true.output
  tests/mpi/p4est_3d_refine_01.mpirun=4.with_p4est=true.output
  tests/mpi/tria_signals_03.mpirun=4.with_p4est=true.output
  tests/mpi/tria_signals_04.mpirun=11.with_p4est=true.output
  tests/mpi/tria_signals_04.mpirun=4.with_p4est=true.output
  tests/mpi/tria_signals_06.cc
  tests/mpi/tria_signals_06.mpirun=4.with_p4est=true.output
Labels: Triangulation, Parallel, ready to test

#16468 Use if-constexpr more in Tensor.
  include/deal.II/base/tensor.h
Labels: Tensors, ready to test

#16415 Fix ecl access cells
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, ready to test

#16382 Enhance documentation for sum_into_values
  include/deal.II/matrix_free/fe_point_evaluation.h
Labels: Documentation, ready to test

#16470 CMake: print newline when vectorization is disabled.
  cmake/setup_write_config.cmake
Labels: Build system, Reviewed and ready to merge, ready to test

#16473 More Tensor simplifications with if constexpr.
  include/deal.II/base/tensor.h
Labels: Tensors, ready to test

#16477 Fix typo in changelog
  doc/news/changes/minor/20230917SchreterMunch_2
Labels: Documentation

#16327 make tests/mpi/affine_constraints_get_view_01 more robust
  tests/mpi/affine_constraints_get_view_01.cc
Labels: Tests, ready to test

#16471 test examples: support loading files
  tests/examples/CMakeLists.txt.in
Labels: Tutorials, Tests, ready to test

#16474 Use a std::array instead of a C-style array for tensor elements.
  include/deal.II/base/tensor.h
  tests/fullydistributed_grids/copy_serial_tria_grouped_01.mpirun=7.output
  tests/serialization/fe_series_01.output
  tests/serialization/fe_series_02.output
  tests/serialization/parallel_fullydistributed_construction_data_1.output
  tests/serialization/particle_01.with_p4est=true.mpirun=1.output
  tests/serialization/particle_handler_02.with_p4est=true.mpirun=1.output
  tests/serialization/point.output
  tests/serialization/quadrature.output
  tests/serialization/quadrature_qanisotropic.output
  tests/serialization/quadrature_qiterated.output
  tests/serialization/symmetric_tensor.output
  tests/serialization/tensor.output
  tests/serialization/tensor_base.output
  tests/serialization/triangulation_01.output
  tests/serialization/triangulation_02.output
Labels: Tensors, ready to test

#16476 cell_categorization test: Adjust output
  tests/matrix_free/cell_categorization.with_p4est=true.mpirun=7.output.avx512
Labels: Reviewed and ready to merge, Matrix-free, Tests, ready to test

#16478 exchange refinement flags: doc and changelog
  doc/news/changes/minor/20240115tjhei
  include/deal.II/distributed/tria.h
Labels: Documentation, Reviewed and ready to merge, ready to test

#16444 Also test MUMPS symmetric mode.
  tests/petsc/sparse_direct_mumps.cc
  tests/petsc/sparse_direct_mumps.with_petsc_with_mumps=on.with_64bit_indices=off.output
Labels: Tests, External libraries, ready to test

#16481 Work around warnings about invalid array accesses.
  source/base/polynomials_rannacher_turek.cc
Labels: Finite Element, ready to test

#16482 Initialize NumberCache::n_global_active_cells
  source/distributed/tria_base.cc
Labels: Reviewed and ready to merge, ready to test

#16290 Add parallel support to TpetraWrappers::Vector.
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/read_write_vector.templates.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  include/deal.II/numerics/data_out_dof_data.templates.h
  tests/trilinos/tpetra_vector_03.with_trilinos_with_tpetra=on.with_complex_values=off.mpirun=2.output
  tests/trilinos/tpetra_vector_03.with_trilinos_with_tpetra=on.with_complex_values=off.mpirun=4.output
  tests/trilinos/tpetra_vector_03.with_trilinos_with_tpetra=on.with_complex_values=on.mpirun=2.output
  tests/trilinos/tpetra_vector_03.with_trilinos_with_tpetra=on.with_complex_values=on.mpirun=4.output
Labels: Linear Algebra, External libraries, ready to test

#16490 Check if the global vector in distribute_local_to_global has ghost elements.
  include/deal.II/lac/affine_constraints.h
  include/deal.II/lac/affine_constraints.templates.h
Labels: Linear Algebra, ready to test

#16480 Use an array-of-scalars as the base case for Tensor.
  include/deal.II/base/numbers.h
  include/deal.II/base/tensor.h
  tests/fullydistributed_grids/copy_serial_tria_grouped_01.mpirun=7.output
  tests/serialization/fe_series_01.output
  tests/serialization/fe_series_02.output
  tests/serialization/parallel_fullydistributed_construction_data_1.output
  tests/serialization/particle_01.with_p4est=true.mpirun=1.output
  tests/serialization/particle_handler_02.with_p4est=true.mpirun=1.output
  tests/serialization/point.output
  tests/serialization/quadrature.output
  tests/serialization/quadrature_qanisotropic.output
  tests/serialization/quadrature_qiterated.output
  tests/serialization/symmetric_tensor.output
  tests/serialization/tensor.output
  tests/serialization/tensor_base.output
  tests/serialization/triangulation_01.output
  tests/serialization/triangulation_02.output
Labels: ready to test

#16494 DofTools: add missing codimension-one instantiation
  source/dofs/dof_tools_sparsity.inst.in
Labels: Reviewed and ready to merge, ready to test

#16438 Treat ICPX as gcc-style compiler
  cmake/setup_compiler_flags.cmake
  cmake/setup_compiler_flags_gnu.cmake
Labels: Build system, Compiler, ready to test

#16486 CMake: fix compilation with bundled boost and modern clang
  bundled/setup_bundled.cmake
Labels: Bug, Build system, External libraries, ready to test

#16496 Enable `FE_DGQ::get_interpolation_matrix()` for source finite element type `FENothing`
  doc/news/changes/minor/20240118Schreter
  source/fe/fe_dgq.cc
  tests/fe/dgq_1.cc
  tests/fe/dgq_1.output
  tests/hp/solution_transfer_03.cc
Labels: Reviewed and ready to merge, ready to test

#16498 TpetraWrappers: fix various compiler warnings
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  source/lac/trilinos_tpetra_sparsity_pattern.cc
Labels: Reviewed and ready to merge, ready to test

#16499 base/tensor.h: work around bogus compiler warning
  include/deal.II/base/tensor.h
Labels: Reviewed and ready to merge, ready to test

#16323 RemotePointEvaluation: add AdditionalData struct
  doc/news/changes/minor/20231206Schreter
  include/deal.II/base/mpi_remote_point_evaluation.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  source/base/mpi_remote_point_evaluation.cc
  tests/remote_point_evaluation/mapping_01.cc
  tests/remote_point_evaluation/mapping_03.cc
  tests/remote_point_evaluation/mapping_04.cc
  tests/remote_point_evaluation/search_adjacent_cells.cc
Labels: ready to test

#16500 Iterate space_dimension over the dedicated template argument list.
  source/dofs/dof_tools.inst.in
  source/dofs/dof_tools_sparsity.inst.in
  source/fe/fe_nothing.inst.in
  source/grid/grid_in.inst.in
  source/matrix_free/fe_point_evaluation.inst.in
Labels: Reviewed and ready to merge, ready to test

#16501 Fix types and names in step-30.
  examples/step-30/step-30.cc
Labels: Reviewed and ready to merge, ready to test

#16503 Use p[index] instead of p(index) for class Point in one source file.
  include/deal.II/lac/matrix_out.h
Labels: ready to test

#16502 Disable DEAL_II(_CXX23)_ASSUME macro for now
  include/deal.II/base/config.h.in
  include/deal.II/base/exceptions.h
Labels: Bug, High Priority :warning:, Compiler, ready to test

#16505 Use simpler copy/move initialization in Tensor.
  include/deal.II/base/tensor.h
Labels: Tensors, ready to test

#16506 Fix type in Tensor initialization.
  include/deal.II/base/tensor.h
Labels: Tensors, ready to test

#16509 fix compiler warning
  source/fe/fe_q_base.cc
Labels: ready to test

#16435 Make FERemoteEvaluation work for FCL
  include/deal.II/matrix_free/fe_remote_evaluation.h
  tests/matrix_free/fe_remote_evaluation_01.cc
  tests/matrix_free/fe_remote_evaluation_02.cc
Labels: ready to test

#16510 Fix one more warning
  source/grid/grid_generator.cc
Labels: ready to test

#16489 fix bug in function DoFCellAccessor::distribute_local_to_global()
  include/deal.II/dofs/dof_accessor.templates.h
  tests/dofs/dof_accessor_04.cc
  tests/dofs/dof_accessor_04.output
Labels: Bug, DoFs, ready to test

#16304 Add support for hanging nodes to the NedelecSZ class.
  doc/news/changes/major/20231128SebastianKinnewig
  include/deal.II/fe/fe_nedelec_sz.h
  source/dofs/dof_tools_constraints.cc
  source/fe/fe_nedelec_sz.cc
  tests/fe/fe_nedelec_sz_divergence_theorem_hanging_nodes.cc
  tests/fe/fe_nedelec_sz_divergence_theorem_hanging_nodes.output
  tests/fe/fe_nedelec_sz_hanging_nodes_convergence.cc
  tests/fe/fe_nedelec_sz_hanging_nodes_convergence.output
  tests/fe/fe_nedelec_sz_hanging_nodes_on_inhomogeneous_boundary.cc
  tests/fe/fe_nedelec_sz_hanging_nodes_on_inhomogeneous_boundary.output
Labels: Finite Element, ready to test

#16512 DoFTools: Remove unnecessary template specializations
  source/dofs/dof_tools_constraints.cc
Labels: DoFs, ready to test

#16513 Reenable assume macro
  cmake/setup_compiler_flags_gnu.cmake
  include/deal.II/base/config.h.in
  include/deal.II/base/exceptions.h
Labels: ready to test

#16519 Tensor<k, dim, Number::unroll(): fix copy statement
  include/deal.II/base/tensor.h
Labels: Bug, ready to test

#16518 Physics::Elasticity::Kinematics::w: change intermediate value to 'auto'
  include/deal.II/physics/elasticity/kinematics.h
Labels: Bug, ready to test

#16523 changelog for PR 16489
  doc/news/changes/minor/20240123jin
Labels: Documentation

#16339 MGTwoLevelTransfer: improve setup of indices
  include/deal.II/matrix_free/constraint_info.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
Labels: Multigrid, ready to test

#16521 ParameterAcceptor: check that we set values correctly for multiple live objects of the same class
  tests/parameter_handler/parameter_acceptor_12.cc
  tests/parameter_handler/parameter_acceptor_12.output
Labels: Reviewed and ready to merge, ready to test

#16529 Fix TpetraWrappers::Vector::operator=(double)
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
Labels: Reviewed and ready to merge, ready to test

#16524 Fix type confusion in Tensor initialization.
  include/deal.II/base/tensor.h
  tests/sacado/tensor_01.cc
  tests/sacado/tensor_01.output
Labels: Reviewed and ready to merge, ready to test

#16526 Make some parts of VectorizedArray infrastructure 'constexpr'.
  include/deal.II/base/vectorization.h
Labels: Reviewed and ready to merge, ready to test

#16527 base/mpi.h: also instantiate for signed long long int
  cmake/config/template-arguments.in
Labels: Reviewed and ready to merge, ready to test

#16533 Clean up a test.
  tests/ad_common_tests/tensor_functions_02.h
Labels: Reviewed and ready to merge, ready to test

#16531 Kokkos+Cuda: enforce expt-relaxed-constexpr
  cmake/modules/FindDEAL_II_KOKKOS.cmake
Labels: ready to test

#16542 Tests serialization/fe_series_0?.output: update libc++ output variant
  tests/serialization/fe_series_01.output.libc++
  tests/serialization/fe_series_02.output.libc++
Labels: Reviewed and ready to merge, ready to test

#16540 [9.5] base/mpi.h: also instantiate for signed long long int
  cmake/config/template-arguments.in
Labels: ready to test

#16541 [9.5] CMake: fix compilation with bundled boost and modern clang
  bundled/setup_bundled.cmake
Labels: ready to test

#16539 [9.5] DofTools: add missing codimension-one instantiation
  source/dofs/dof_tools_sparsity.inst.in
Labels: ready to test

#16359 Introduce FEFacePointEvaluation with optimized FCL path
  include/deal.II/matrix_free/evaluation_kernels_face.h
  include/deal.II/matrix_free/evaluation_template_face_factory.templates.h
  include/deal.II/matrix_free/evaluation_template_factory.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/fe_point_evaluation.h
  include/deal.II/matrix_free/tensor_product_kernels.h
  include/deal.II/non_matching/mapping_info.h
  tests/matrix_free/point_evaluation_23.cc
  tests/matrix_free/point_evaluation_24.cc
  tests/matrix_free/point_evaluation_27.cc
  tests/matrix_free/point_evaluation_29.cc
  tests/matrix_free/point_evaluation_29.output
  tests/non_matching/mapping_info.cc
  tests/non_matching/mapping_info_03.cc
  tests/non_matching/mapping_info_04.cc
  tests/non_matching/mapping_info_04.output
  tests/non_matching/mapping_info_05.cc
  tests/non_matching/mapping_info_05.output
Labels: Matrix-free, ready to test

#16547 Simplify locally_owned_elements in TpetraWrappers::Vector.
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
Labels: Reviewed and ready to merge, External libraries, ready to test

#16548 Simplify generation of a cmake message.
  cmake/configure/configure_20_trilinos.cmake
Labels: ready to test

#16550 Add a couple missing includes
  include/deal.II/base/tensor.h
  include/deal.II/base/vectorization.h
Labels: Reviewed and ready to merge, ready to test

#16545 Fix Copy Constructor in TpetraWrappers::Vector.
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
Labels: External libraries, ready to test

#16551 Testsuite: use `./serial` subdirectory
  cmake/macros/macro_deal_ii_add_test.cmake
  cmake/macros/macro_deal_ii_pickup_tests.cmake
Labels: Build system, ready to test

#16560 Silence a warning.
  include/deal.II/cgal/utilities.h
Labels: Reviewed and ready to merge, ready to test

#16558 Make a deep-copy of the Tpetra::Vector in the assignment operator.
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
Labels: Reviewed and ready to merge, External libraries, ready to test

#16562 Convert tutorial programs to use DEAL_II_NOT_IMPLEMENTED().
  examples/doxygen/step_3_mixed.cc
  examples/step-18/step-18.cc
  examples/step-21/step-21.cc
  examples/step-25/step-25.cc
  examples/step-33/step-33.cc
  examples/step-34/step-34.cc
  examples/step-35/step-35.cc
  examples/step-42/step-42.cc
  examples/step-46/step-46.cc
  examples/step-50/step-50.cc
  examples/step-51/step-51.cc
  examples/step-63/step-63.cc
  examples/step-67/step-67.cc
  examples/step-74/step-74.cc
  examples/step-75/step-75.cc
  examples/step-76/step-76.cc
  examples/step-78/step-78.cc
  examples/step-82/step-82.cc
Labels: ready to test

#16563 Explain the use of DEAL_II_NOT_IMPLEMENTED() in step-8.
  examples/step-8/step-8.cc
  include/deal.II/base/exceptions.h
Labels: ready to test

#16566 Prefer trilinos_vector over trilinos_rcp
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
Labels: Reviewed and ready to merge, ready to test

#16569 Fix TpetraWrappers::SparsityPattern when compiling for GPU backends
  source/lac/trilinos_tpetra_sparsity_pattern.cc
Labels: External libraries, ready to test

#16568 Use AlignedVector in ReadWriteVector.
  include/deal.II/lac/read_write_vector.h
  include/deal.II/lac/read_write_vector.templates.h
Labels: Reviewed and ready to merge, Miscellaneous, ready to test

#16546 Rework import_elements() in read_write_vector for TpetraWrapper::Vector
  include/deal.II/lac/read_write_vector.templates.h
Labels: External libraries, ready to test

#16573 Minor doc update.
  include/deal.II/distributed/cell_weights.h
Labels: Documentation, ready to test

#16572 Convert a few more places of Assert(false, dealii::ExcNotImplemented());
  include/deal.II/base/exceptions.h
  include/deal.II/cgal/point_conversion.h
  include/deal.II/lac/scalapack.templates.h
  source/base/quadrature_lib.cc
  source/lac/scalapack.cc
  source/multigrid/mg_transfer_global_coarsening.cc
Labels: Infrastructure, Reviewed and ready to merge, ready to test

#16565 Template TrilinosWrappers::Vector on memory space
  include/deal.II/base/template_constraints.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
Labels: External libraries, ready to test

#16576 [9.5] update changelog for point release
  doc/news/9.5.0-vs-9.5.2.h
Labels: Reviewed and ready to merge
