Repository dealii/dealii, pull requests merged in 2024-12, with the labels that each got.

#17894 add team barriers to CellAction in matrix_free/tools.h
  include/deal.II/matrix_free/tools.h
Labels: GPU, Parallel, ready to test

#17884 Rename FIV::normal() to normal_vector() and introduce FIV::quadrature_point()
  doc/news/changes/incompatibilities/20241123Munch
  doc/news/changes/minor/20241123Munch
  examples/step-50/step-50.cc
  examples/step-85/step-85.cc
  include/deal.II/fe/fe_interface_values.h
  tests/feinterface/fe_interface_values_12.cc
  tests/feinterface/step-12.cc
Labels: ready to test

#17899 Add another barrier in MatrixFreeTools::compute_diagonal()
  include/deal.II/matrix_free/tools.h
Labels: ready to test

#17905 Fixed normal direction for the last component for RT elements
  include/deal.II/matrix_free/evaluation_kernels.h
Labels: Matrix-free, ready to test

#17904 Fix nightly rocm tests
  source/base/polynomials_piecewise.cc
  source/grid/grid_out.cc
  tests/examples/step-18.mpirun=2.with_petsc=true.output2
Labels: Reviewed and ready to merge, ready to test

#17907 Add new test for repartitioning of p:f:T
  tests/fullydistributed_grids/repartitioning_09.cc
  tests/fullydistributed_grids/repartitioning_09.with_p4est=true.mpirun=4.output
Labels: ready to test

#17891 Make a test more comprehensive
  tests/matrix_free/matrix_vector_rt_common.h
  tests/matrix_free/matrix_vector_rt_face_common.h
Labels: Matrix-free, Tests, ready to test

#17892 Cleanup doxygen defines
  doc/doxygen/options.dox.in
Labels: Documentation

#17902 disable randomly hanging lazy_04 test
  tests/base/lazy_04.cc
  tests/base/lazy_04.threads=4.expect=run.output
Labels: Tests, ready to test

#17915 Remove std::is_trivial from AlignedVector.
  include/deal.II/base/aligned_vector.h
Labels: Enhancement, ready to test, C++26

#17920 MatrixFree/TensorProductPointKernels: fix compilation with Number = float
  include/deal.II/matrix_free/tensor_product_point_kernels.h
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#17918 Periodicity constraints: skip artificial cell face dofs
  source/dofs/dof_tools_constraints.cc
  tests/mpi/periodicity_09.cc
  tests/mpi/periodicity_09.mpirun=5.with_p4est=true.output
Labels: DoFs, Parallel distributed, ready to test

#17866 Extend read_vtk to add FIELD data (Previously PR #10649)
  include/deal.II/grid/grid_in.h
  source/grid/grid_in.cc
  tests/grid/grid_in_vtk_2d_field_data.cc
  tests/grid/grid_in_vtk_2d_field_data.output
  tests/grid/grid_in_vtk_2d_field_data/mesh
Labels: Enhancement, ready to test

#17896 parallel::distributed::Triangulation: should we clarify clear() method?
  source/distributed/tria.cc
Labels: Discussion, ready to test

#17923 Return empty vector for FE_DGP::hp_vertex_dof_identities()
  source/fe/fe_dgp.cc
Labels: Finite Element, ready to test

#17806 Chunking for WorkStream with Taskflow
  include/deal.II/base/work_stream.h
Labels: Parallel, ready to test

#17931 Fix wrong copyright header in three files.
  include/deal.II/base/init_finalize.h
  include/deal.II/base/task_result.h
  include/deal.II/fe/fe_coupling_values.h
Labels: ready to test

#17930 Use properly scoped include directive.
  include/deal.II/grid/tria_iterator.h
Labels: ready to test

#17938 Avoid the final incorrect use of std::is_trivial.
  include/deal.II/lac/vector_operations_internal.h
Labels: Miscellaneous, ready to test

#17937 Avoid another incorrect use of std::is_trivial.
  source/base/vectorization.cc
Labels: SIMD, ready to test

#17936 Avoid another incorrect use of std::is_trivial.
  include/deal.II/lac/sparse_matrix.templates.h
Labels: Miscellaneous, ready to test

#17935 Fix a place incorrectly using std::is_trivial.
  include/deal.II/base/partitioner.templates.h
Labels: Linear Algebra, Miscellaneous, ready to test

#17940 Avoid infinities in another place.
  source/particles/particle_handler.cc
Labels: Particles, ready to test

#17941 More places of avoiding infinities.
  source/numerics/smoothness_estimator.cc
Labels: Miscellaneous, ready to test

#17934 Fix markup.
  include/deal.II/grid/grid_in.h
Labels: Documentation, ready to test

#17944 Fix a typo in a comment
  source/base/polynomials_piecewise.cc
Labels: Documentation, ready to test

#17933 Just include a file directly.
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_accessor.templates.h
  source/grid/tria_accessor.cc
Labels: Miscellaneous, ready to test

#17939 Avoid the use of infinities.
  doc/news/changes/incompatibilities/20241217Bangerth
  include/deal.II/fe/mapping.h
  include/deal.II/fe/mapping_q_internal.h
  source/fe/mapping.cc
  source/fe/mapping_q.cc
  tests/mappings/mapping_q_points_real_to_unit.output
Labels: ready to test

#17943 Deprecate parallel::transform().
  doc/news/changes/minor/20241218Bangerth
  include/deal.II/base/parallel.h
Labels: Reviewed and ready to merge, ready to test

#17949 Fix the name of an object library.
  source/particles/CMakeLists.txt
Labels: Build system, ready to test

#17947 Add explanatory comment to step-71.
  examples/step-71/step-71.cc
Labels: Tutorials, ready to test

#17953 [9.6] CMake: tests: fix tests in release tarball
  .gitattributes
Labels: High Priority :warning:

#17950 Fix VectorTools::interpolate for FE_Nothing
  include/deal.II/numerics/vector_tools_interpolate.templates.h
Labels: Finite Element, hp adaptivity, ready to test

#17945 Hide the implementation functions of EnableObserverPointer.
  include/deal.II/base/enable_observer_pointer.h
  include/deal.II/lac/matrix_block.h
  tests/base/unsubscribe_subscriptor.cc
  tests/base/unsubscribe_subscriptor.debug.output
  tests/base/unsubscribe_subscriptor.debug.output.clang-6
  tests/base/unsubscribe_subscriptor.debug.output.gcc-12
  tests/base/unsubscribe_subscriptor.debug.output.intel
  tests/base/unsubscribe_subscriptor_01.cc
  tests/base/unsubscribe_subscriptor_01.output
Labels: Miscellaneous, ready to test

#17948 Implement FiniteElement::shape_function_belongs_to().
  doc/news/changes/minor/20241218Bangerth-2
  include/deal.II/fe/fe.h
  tests/fe/shape_function_belongs_to_01.cc
  tests/fe/shape_function_belongs_to_01.output
  tests/fe/shape_function_belongs_to_02.cc
  tests/fe/shape_function_belongs_to_02.output
Labels: Enhancement, Finite Element, ready to test

#17960 Combine the line_index() functions.
  include/deal.II/grid/tria_accessor.h
Labels: Triangulation, ready to test, C++17

#17958 Combine the set_line_orientation() functions.
  include/deal.II/grid/tria_accessor.h
Labels: Triangulation, ready to test, C++17

#17959 Look up line orientations from combined orientations in 2d.
  include/deal.II/grid/tria_accessor.h
Labels: Triangulation, ready to test
