Repository dealii/dealii, pull requests merged in 2024-05, with the labels that each got.

#16942 Add a missing 'const'.
  examples/step-2/step-2.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#16934 Add a test for Threads::Task.
  tests/multithreading/task_17.cc
  tests/multithreading/task_17.output
Labels: Parallel shared, ready to test

#16935 Add a comment about task execution.
  include/deal.II/base/thread_management.h
Labels: Documentation, Parallel shared

#16856 Fix MG transfer for Tetrahedrons
  include/deal.II/fe/fe_simplex_p.h
  include/deal.II/fe/fe_tools.templates.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_accessor.templates.h
  include/deal.II/grid/tria_levels.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  source/fe/fe.cc
  source/fe/fe_simplex_p.cc
  source/fe/fe_simplex_p_bubbles.cc
  source/fe/fe_system.cc
  source/grid/tria.cc
  source/grid/tria_levels.cc
  tests/fe/prolongation_restriction.cc
  tests/fe/prolongation_restriction.output
  tests/fe/up_and_down_simplex.cc
  tests/fe/up_and_down_simplex.output
  tests/multigrid-global-coarsening/mg_transfer_a_05.cc
  tests/multigrid-global-coarsening/mg_transfer_a_05.with_p4est=true.mpirun=1.output
Labels: ready to test, Simplices

#16945 Fix another missing 'const'.
  examples/step-3/step-3.cc
Labels: Tutorials, ready to test

#16951 Fix a compiler warning.
  source/fe/fe_simplex_p.cc
Labels: Miscellaneous, ready to test

#16953 Multiply right hand side value from the left with phi_i.
  examples/step-6/step-6.cc
Labels: Tutorials, ready to test

#16952 Say what a bare integer argument is.
  examples/step-3/step-3.cc
  examples/step-4/step-4.cc
  examples/step-5/step-5.cc
  examples/step-6/step-6.cc
Labels: Tutorials, ready to test

#16956 Restate the equation we solve at the beginning of step-6.
  examples/step-5/doc/intro.dox
  examples/step-6/doc/intro.dox
Labels: Tutorials, ready to test

#16955 Be uniform in the order of things we start the assembly loop with.
  examples/step-20/step-20.cc
  examples/step-22/step-22.cc
  examples/step-4/step-4.cc
  examples/step-40/step-40.cc
  examples/step-5/step-5.cc
  examples/step-6/step-6.cc
  examples/step-7/step-7.cc
  examples/step-8/step-8.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#16948 Make it clearer what an integer argument means.
  examples/step-3/doc/results.dox
  examples/step-3/step-3.cc
  examples/step-4/step-4.cc
  examples/step-5/step-5.cc
  examples/step-6/step-6.cc
  examples/step-7/step-7.cc
  examples/step-8/step-8.cc
Labels: Tutorials, ready to test

#16925 FEPointEvaluation: Remove signal to keep track of reinit() state
  include/deal.II/matrix_free/fe_point_evaluation.h
  include/deal.II/non_matching/mapping_info.h
Labels: Matrix-free, ready to test

#16964 Add template argument to VectorTools::compute_no_normal_flux_constraints()
  include/deal.II/numerics/vector_tools_constraints.h
  include/deal.II/numerics/vector_tools_constraints.templates.h
  source/numerics/vector_tools_constraints.inst.in
Labels: Reviewed and ready to merge, ready to test

#16960 Make many more variables 'const'.
  examples/step-14/step-14.cc
  examples/step-17/step-17.cc
  examples/step-20/step-20.cc
  examples/step-21/step-21.cc
  examples/step-22/step-22.cc
  examples/step-25/step-25.cc
  examples/step-29/step-29.cc
  examples/step-31/step-31.cc
  examples/step-35/step-35.cc
  examples/step-36/step-36.cc
  examples/step-4/step-4.cc
  examples/step-42/step-42.cc
  examples/step-43/step-43.cc
  examples/step-45/step-45.cc
  examples/step-5/step-5.cc
  examples/step-50/step-50.cc
  examples/step-55/step-55.cc
  examples/step-56/step-56.cc
  examples/step-57/step-57.cc
  examples/step-59/step-59.cc
  examples/step-60/step-60.cc
  examples/step-62/step-62.cc
  examples/step-7/step-7.cc
  examples/step-70/step-70.cc
  examples/step-72/step-72.cc
  examples/step-78/step-78.cc
  examples/step-79/step-79.cc
  examples/step-8/step-8.cc
  examples/step-81/step-81.cc
  examples/step-82/step-82.cc
  examples/step-87/step-87.cc
  source/base/polynomial.cc
  source/base/quadrature_lib.cc
  source/dofs/dof_renumbering.cc
  source/dofs/dof_tools_constraints.cc
  source/fe/fe_abf.cc
  source/fe/fe_bdm.cc
  source/fe/fe_dgq.cc
  source/fe/fe_q_base.cc
  source/fe/fe_q_iso_q1.cc
  source/fe/fe_raviart_thomas.cc
  source/fe/fe_rt_bubbles.cc
  source/fe/mapping_q_cache.cc
  source/grid/grid_out.cc
  source/grid/grid_tools.cc
  source/grid/manifold_lib.cc
  source/numerics/data_out_resample.cc
  source/numerics/data_out_stack.cc
  source/numerics/derivative_approximation.cc
Labels: Miscellaneous, ready to test

#16971 Rename a poorly named variable.
  examples/step-15/step-15.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#16932 NonMatching::FEValues: accept CellAccessor
  include/deal.II/non_matching/fe_values.h
  source/non_matching/fe_values.cc
  source/non_matching/fe_values.inst.in
  tests/non_matching/fe_values.cc
  tests/non_matching/fe_values.with_lapack=on.output
Labels: Enhancement, ready to test

#16972 autopilot distclean: also remove `compile_commands.json`.
  cmake/macros/macro_deal_ii_invoke_autopilot.cmake
Labels: Reviewed and ready to merge, ready to test

#16973 Mark an input argument as 'const', and in the process give it a reasonable type.
  include/deal.II/fe/mapping_fe_field.h
  source/fe/mapping_fe_field.cc
Labels: Enhancement, Mapping, ready to test

#16966 Fix FEEvaluation gradient layout in step-76 tutorial program
  examples/step-76/step-76.cc
Labels: Matrix-free, Tutorials, ready to test

#16967 step-77: use AffineConstraints only
  examples/step-77/step-77.cc
Labels: ready to test

#16965 Remove extra orientation functions
  include/deal.II/dofs/dof_accessor.templates.h
  include/deal.II/grid/tria_accessor.templates.h
  include/deal.II/grid/tria_objects_orientations.h
Labels: Triangulation, ready to test

#16940 Fix p:f:T::load()
  include/deal.II/distributed/shared_tria.h
  include/deal.II/distributed/tria_base.h
  source/distributed/fully_distributed_tria.cc
  source/distributed/tria_base.cc
  tests/sharedtria/serialization_01.cc
  tests/sharedtria/serialization_01.mpirun=2.output
Labels: ready to test

#16977 Restructure WorkStream slightly.
  include/deal.II/base/work_stream.h
Labels: ready to test

#16982 Matrix-free evaluation kernels: Do not template tensor_none case
  include/deal.II/matrix_free/evaluation_kernels.h
Labels: Matrix-free, ready to test, Simplices

#16991 Name a template argument VectorType as per usual.
  include/deal.II/lac/slepc_solver.h
Labels: External libraries, ready to test

#16992 Fix DEAL_II_ARBORX_CXX20_BUG check
  cmake/configure/configure_50_arborx.cmake
Labels: External libraries, ready to test

#16986 Remove unnecessary references to logstream.h.
  include/deal.II/base/parameter_acceptor.h
  include/deal.II/differentiation/sd/symengine_optimizer.h
  include/deal.II/lac/precondition_block.templates.h
  include/deal.II/lac/precondition_block_base.h
  include/deal.II/lac/vector_memory.h
  include/deal.II/lac/vector_memory.templates.h
  include/deal.II/multigrid/multigrid.templates.h
  include/deal.II/numerics/fe_field_function.templates.h
  include/deal.II/sundials/arkode.h
  include/deal.II/sundials/ida.h
  include/deal.II/sundials/kinsol.h
Labels: ready to test

#16993 Introduce FullMatrix::compress()
  include/deal.II/lac/full_matrix.h
  include/deal.II/lac/full_matrix.templates.h
  include/deal.II/numerics/matrix_creator.templates.h
Labels: ready to test

#16988 add tests/examples/step-77
  tests/examples/step-77.diff
  tests/examples/step-77.with_sundials=true.output
Labels: Tests, ready to test

#16989 Test step-67 and step-76 tutorial programs
  tests/examples/step-67.diff
  tests/examples/step-67.output
  tests/examples/step-76.diff
  tests/examples/step-76.output
Labels: Tests, ready to test

#16994 Add a few more tests for the tutorials
  tests/examples/step-37.diff
  tests/examples/step-37.output
  tests/examples/step-48.diff
  tests/examples/step-48.output
  tests/examples/step-59.diff
  tests/examples/step-59.output
  tests/examples/step-65.diff
  tests/examples/step-65.output
Labels: Tutorials, Tests, ready to test

#16954 Consistently use a relative solver tolerance.
  examples/step-16/doc/results.dox
  examples/step-16/step-16.cc
  examples/step-4/doc/results.dox
  examples/step-4/step-4.cc
  examples/step-40/doc/results.dox
  examples/step-40/step-40.cc
  examples/step-5/doc/results.dox
  examples/step-5/step-5.cc
  examples/step-6/doc/results.dox
  examples/step-6/step-6.cc
  examples/step-7/doc/results.dox
  examples/step-7/step-7.cc
  examples/step-8/step-8.cc
  tests/examples/step-16.output
  tests/examples/step-4.output
  tests/examples/step-40.mpirun=2.with_p4est=true.with_petsc=true.output
  tests/examples/step-6.output
  tests/examples/step-8.output
Labels: Reviewed and ready to merge, Tutorials, ready to test

#16976 Use taskflow to create asynchronous tasks.
  include/deal.II/base/thread_management.h
Labels: ready to test

#16987 Get rid of the use of deallog in step-3 and friends.
  examples/doxygen/step_3_mixed.cc
  examples/doxygen/step_3_simplex.cc
  examples/step-3/doc/results.dox
  examples/step-3/step-3.cc
  examples/step-4/step-4.cc
  include/deal.II/base/logstream.h
  tests/examples/step-3.diff
  tests/examples/step-3.output
Labels: Tutorials, ready to test

#16996 Introduce concepts that matrix template arguments have to satisfy.
  include/deal.II/base/template_constraints.h
Labels: ready to test, C++20

#16957 Include allocated vectors in GrowingVectorMemory's memory consumption
  include/deal.II/lac/vector_memory.templates.h
Labels: Linear Algebra, ready to test

#16998 Fix Compiler warning in `tria.cc`
  source/grid/tria.cc
Labels: Reviewed and ready to merge, ready to test

#16981 step-15: use AffineConstraints for boundary values
  examples/step-15/doc/intro.dox
  examples/step-15/step-15.cc
Labels: Tutorials, ready to test

#17006 Add some commentary about tests/examples.
  tests/examples/README.md
  tests/examples/update_diffs.sh
Labels: Tutorials, Tests

#17004 Test step-39.
  tests/examples/step-39.diff
  tests/examples/step-39.output
Labels: Tutorials, Tests, ready to test

#16995 Annotate solver classes with vector space vector concept.
  include/deal.II/lac/solver.h
  include/deal.II/lac/solver_bicgstab.h
  include/deal.II/lac/solver_cg.h
  include/deal.II/lac/solver_fire.h
  include/deal.II/lac/solver_gmres.h
  include/deal.II/lac/solver_idr.h
  include/deal.II/lac/solver_minres.h
  include/deal.II/lac/solver_qmrs.h
  include/deal.II/lac/solver_relaxation.h
  include/deal.II/lac/solver_richardson.h
  include/deal.II/lac/solver_selector.h
  include/deal.II/lac/trilinos_solver.h
Labels: Linear Algebra, ready to test, C++20

#17007 Remove authors from steps 1-8.
  examples/step-2/step-2.cc
  examples/step-3/step-3.cc
  examples/step-4/step-4.cc
  examples/step-5/step-5.cc
  examples/step-6/step-6.cc
  examples/step-7/step-7.cc
  examples/step-8/step-8.cc
Labels: Tutorials

#17008 step-72: use AffineConstraints only
  examples/step-72/step-72.cc
Labels: Tutorials, ready to test

#17003 Fix documentation in GridGenerator.
  include/deal.II/grid/grid_generator.h
Labels: Documentation

#17014 Fix typo in documentation
  include/deal.II/grid/grid_generator.h
Labels: Documentation

#17013 Test for tutorials step-67 and step-76: Do not write output
  tests/examples/step-67.diff
  tests/examples/step-76.diff
Labels: Tutorials, Tests, ready to test

#17015 step-72: fix warnings
  examples/step-72/step-72.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#17002 Discuss triangular meshes in step-3.
  doc/news/changes/major/20240513Bangerth
  examples/step-3/doc/results.dox
Labels: Documentation, Tutorials

#16984 Tensor product operations: Use loop unrolling for slow mat-vec
  include/deal.II/matrix_free/tensor_product_kernels.h
Labels: Matrix-free, ready to test, Simplices

#16985 MatrixFree: Switch ShapeInfo from VectorizedArray<Number> to Number type
  examples/step-76/step-76.cc
  include/deal.II/fe/mapping_q.h
  include/deal.II/matrix_free/constraint_info.h
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/evaluation_kernels_face.h
  include/deal.II/matrix_free/evaluation_kernels_hanging_nodes.h
  include/deal.II/matrix_free/evaluation_template_factory.h
  include/deal.II/matrix_free/evaluation_template_factory_hanging_nodes.templates.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/fe_evaluation_data.h
  include/deal.II/matrix_free/mapping_info.templates.h
  include/deal.II/matrix_free/matrix_free.h
  tests/matrix_free/fe_evaluation_shift.cc
  tests/matrix_free/hanging_node_kernels_01.cc
  tests/performance/timing_navier_stokes.cc
Labels: Discussion, Matrix-free, ready to test

#16363 github-actions: simplify oneAPI setup with external action.
  .github/workflows/linux.yml
Labels: Infrastructure, ready to test

#17019 Deprecate two fields in MeshWorker::LocalIntegrator.
  doc/news/changes/minor/20240514Bangerth
  include/deal.II/meshworker/local_integrator.h
Labels: ready to test

#17020 Zap step-16b.
  doc/doxygen/headers/mg.h
  doc/doxygen/tutorial/tutorial.h.in
  examples/step-16/doc/intro.dox
  examples/step-16b/CMakeLists.txt
  examples/step-16b/doc/builds-on
  examples/step-16b/doc/intro.dox
  examples/step-16b/doc/kind
  examples/step-16b/doc/results.dox
  examples/step-16b/doc/tooltip
  examples/step-16b/step-16b.cc
Labels: Tutorials, ready to test

#17011 Link FE_Q, FE_SimplexP, and friends in the documentation.
  include/deal.II/fe/fe_pyramid_p.h
  include/deal.II/fe/fe_q.h
  include/deal.II/fe/fe_simplex_p.h
  include/deal.II/fe/fe_wedge_p.h
Labels: Documentation, ready to test

#17010 Annotate MatrixType with linear operator concepts.
  include/deal.II/lac/solver_bicgstab.h
  include/deal.II/lac/solver_cg.h
  include/deal.II/lac/solver_fire.h
  include/deal.II/lac/solver_gmres.h
  include/deal.II/lac/solver_idr.h
  include/deal.II/lac/solver_minres.h
  include/deal.II/lac/solver_qmrs.h
  include/deal.II/lac/solver_relaxation.h
  include/deal.II/lac/solver_richardson.h
  include/deal.II/lac/solver_selector.h
Labels: Linear Algebra, ready to test

#16990 Zap step-12b.
  doc/doxygen/headers/io.h
  doc/doxygen/tutorial/tutorial.h.in
  doc/news/9.1.1-vs-9.2.0.h
  examples/step-12/doc/intro.dox
  examples/step-12b/CMakeLists.txt
  examples/step-12b/doc/builds-on
  examples/step-12b/doc/intro.dox
  examples/step-12b/doc/kind
  examples/step-12b/doc/results.dox
  examples/step-12b/doc/tooltip
  examples/step-12b/step-12b.cc
  examples/step-21/doc/intro.dox
  examples/step-39/doc/builds-on
  examples/step-39/doc/intro.dox
Labels: Tutorials, ready to test

#17030 Fix error message in step-50
  examples/step-50/step-50.cc
Labels: Tutorials

#17024 Use correct stream for output.
  include/deal.II/differentiation/sd/symengine_optimizer.h
  tests/sacado/basic_01b.cc
  tests/sacado/basic_01b.output
  tests/sacado/basic_02b.cc
  tests/sacado/basic_02b.output
  tests/symengine/basic_05.cc
  tests/symengine/basic_05.with_symengine_with_llvm=false.output
  tests/symengine/basic_06.cc
  tests/symengine/basic_06.output
  tests/symengine/basic_07.cc
  tests/symengine/basic_07.output
  tests/symengine/batch_optimizer_01_1a.output
  tests/symengine/batch_optimizer_01_1b.output
  tests/symengine/batch_optimizer_01_2a.output
  tests/symengine/batch_optimizer_01_2b.output
  tests/symengine/batch_optimizer_02_1a.output
  tests/symengine/batch_optimizer_02_1b.output
  tests/symengine/batch_optimizer_02_2a.output
  tests/symengine/batch_optimizer_02_2b.output
  tests/symengine/batch_optimizer_03_1a.output
  tests/symengine/batch_optimizer_03_1b.output
  tests/symengine/batch_optimizer_03_2a.output
  tests/symengine/batch_optimizer_03_2b.output
  tests/symengine/batch_optimizer_05_1a.output
  tests/symengine/batch_optimizer_05_1b.output
  tests/symengine/batch_optimizer_05_2a.output
  tests/symengine/batch_optimizer_05_2b.output
  tests/symengine/batch_optimizer_06_1a.output
  tests/symengine/batch_optimizer_06_1b.output
  tests/symengine/batch_optimizer_06_2a.output
  tests/symengine/batch_optimizer_06_2b.output
  tests/symengine/cse_03_1.output
  tests/symengine/cse_03_2.output
  tests/symengine/cse_04.cc
  tests/symengine/cse_04.output
  tests/symengine/cse_05.cc
  tests/symengine/cse_05.output
  tests/symengine/sd_common_tests/batch_optimizer_01.h
  tests/symengine/sd_common_tests/batch_optimizer_02.h
  tests/symengine/sd_common_tests/batch_optimizer_03.h
  tests/symengine/sd_common_tests/batch_optimizer_05.h
  tests/symengine/sd_common_tests/batch_optimizer_06.h
  tests/symengine/sd_common_tests/cse_03.h
  tests/symengine/sd_common_tests/step-44-sd-quadrature_level.h
  tests/symengine/step-44-sd-quadrature_level_01.cc
  tests/symengine/step-44-sd-quadrature_level_01.output
  tests/symengine/step-44-sd-quadrature_level_02.cc
  tests/symengine/step-44-sd-quadrature_level_02.output
  tests/symengine/step-44-sd-quadrature_level_03.cc
  tests/symengine/substitution_maps_cyclic_dependencies_01.cc
  tests/symengine/substitution_maps_cyclic_dependencies_01.output
  tests/symengine/substitution_maps_cyclic_dependencies_02.cc
  tests/symengine/substitution_maps_cyclic_dependencies_02.output
  tests/symengine/substitution_maps_scalar_01.cc
  tests/symengine/symengine_number_type_01.cc
  tests/symengine/symengine_number_type_01.output
  tests/symengine/symengine_number_type_02.cc
  tests/symengine/symengine_number_type_02.output
  tests/symengine/symengine_tensor_operations_03.cc
  tests/symengine/symengine_tensor_operations_03.output
Labels: Reviewed and ready to merge, ready to test

#17018 Use Kokkos::abort() where necessary.
  source/base/exceptions.cc
Labels: ready to test

#17025 Fix mesh in a test
  tests/matrix_free/matrix_vector_hessians_general_faces.cc
  tests/matrix_free/matrix_vector_hessians_general_faces.output
Labels: Matrix-free, ready to test

#17034 Fix spelling of a Tpetra configuration flag.
  cmake/configure/configure_20_trilinos.cmake
Labels: ready to test

#17027 `VectorizedArray`: Add missing overloads of trigonometric and hyperbolic functions from cmath
  doc/news/changes/minor/20240515Schreter
  include/deal.II/base/vectorization.h
  tests/base/vectorization_01.cc
  tests/base/vectorization_01.output
Labels: SIMD, ready to test

#17026 Add to the documentation of Lazy<T>.
  include/deal.II/base/lazy.h
Labels: Documentation

#17016 Remove dependence of step-39 on LocalIntegrators.
  doc/news/changes/minor/20240513Bangerth
  examples/step-39/step-39.cc
Labels: Tutorials, ready to test

#17040 Link against sundials_core.
  cmake/modules/FindDEAL_II_SUNDIALS.cmake
Labels: Build system, ready to test

#17036 Provide an error message that is more meaningful for global MG transfer operator.
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
Labels: Multigrid, ready to test

#17042 Consistently use cite
  doc/doxygen/references.bib
  include/deal.II/algorithms/general_data_storage.h
  include/deal.II/base/parsed_convergence_table.h
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/fe/fe_bernardi_raugel.h
  include/deal.II/lac/qr.h
  include/deal.II/lac/utilities.h
  include/deal.II/meshworker/scratch_data.h
  include/deal.II/optimization/line_minimization.h
  include/deal.II/physics/notation.h
Labels: Reviewed and ready to merge, ready to test

#17043 Simplify some code.
  include/deal.II/fe/fe_tools.templates.h
Labels: ready to test

#17033 Raise error when DSP is used without IndexSet
  source/lac/sparsity_tools.cc
  tests/lac/linear_operator_12.cc
  tests/lac/linear_operator_12a.cc
  tests/particles/particle_interpolation_01.cc
  tests/particles/particle_interpolation_02.cc
  tests/particles/particle_interpolation_03.cc
  tests/particles/particle_interpolation_04.cc
  tests/particles/particle_interpolation_05.cc
  tests/trilinos/direct_solver_2.cc
  tests/trilinos/direct_solver_3.cc
  tests/trilinos_tpetra/direct_solver_01.cc
  tests/trilinos_tpetra/direct_solver_02.cc
Labels: Parallel, ready to test

#17048 Make multithreading/task_17 more stable
  tests/multithreading/task_17.cc
  tests/multithreading/task_17.output
Labels: ready to test

#17046 Deprecate some functions in FETools.
  doc/news/changes/minor/20240519Bangerth
  include/deal.II/fe/fe_tools.h
  source/fe/fe_system.cc
Labels: ready to test

#17039 Simplify cmath functions for VectorizedArray
  include/deal.II/base/vectorization.h
Labels: SIMD, ready to test

#17047 Allow to renumber AnisotropicPolynomials
  include/deal.II/base/tensor_product_polynomials.h
  include/deal.II/fe/fe_poly.templates.h
  source/base/tensor_product_polynomials.cc
  tests/base/anisotropic_1.cc
  tests/base/anisotropic_1.output
Labels: Reviewed and ready to merge, Finite Element, ready to test

#17057 Remove #include of matrix/vector_tools.h from tutorials that don't need these.
  examples/step-15/step-15.cc
  examples/step-20/step-20.cc
  examples/step-21/step-21.cc
  examples/step-22/step-22.cc
  examples/step-23/step-23.cc
  examples/step-24/step-24.cc
  examples/step-25/step-25.cc
  examples/step-26/step-26.cc
  examples/step-27/step-27.cc
  examples/step-32/step-32.cc
  examples/step-35/step-35.cc
  examples/step-36/step-36.cc
  examples/step-42/step-42.cc
  examples/step-51/step-51.cc
  examples/step-54/step-54.cc
  examples/step-56/step-56.cc
  examples/step-57/step-57.cc
  examples/step-58/step-58.cc
  examples/step-63/step-63.cc
  examples/step-72/step-72.cc
  examples/step-77/step-77.cc
  examples/step-78/step-78.cc
  examples/step-79/step-79.cc
  examples/step-8/step-8.cc
  examples/step-81/step-81.cc
  examples/step-82/step-82.cc
  examples/step-9/step-9.cc
Labels: Tutorials, ready to test

#17051 Add assertions that we can only combine elements defined on the same reference cell.
  include/deal.II/fe/fe_tools.templates.h
  source/fe/fe_system.cc
Labels: Enhancement, Finite Element, ready to test

#17032 Change interface reinit values
  include/deal.II/matrix_free/fe_remote_evaluation.h
  tests/matrix_free/fe_remote_evaluation_01.cc
  tests/matrix_free/fe_remote_evaluation_02.cc
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#17053 taskflow: require 3.7.0
  cmake/configure/configure_10_taskflow.cmake
Labels: ready to test

#17061 Step-76: remove redundant for loop
  examples/step-76/step-76.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#17050 Generalize the signature of MeshWorker::loop().
  include/deal.II/meshworker/loop.h
Labels: Miscellaneous, ready to test

#17056 Remove deallog.depth_console(0) output from tutorial programs.
  examples/step-67/step-67.cc
  examples/step-76/step-76.cc
Labels: ready to test

#17058 Minor updates to step-9.
  examples/step-9/doc/results.dox
  examples/step-9/step-9.cc
Labels: Tutorials, ready to test

#17055 Minor updates to the IDA documentation and test cases.
  include/deal.II/sundials/ida.h
  tests/sundials/ida_01.cc
  tests/sundials/ida_02.cc
Labels: ready to test

#17062 Simplify some code.
  include/deal.II/fe/fe_tools.templates.h
Labels: Finite Element, ready to test

#17064 Remove include of logstream.h from tutorials that don't need it.
  examples/step-11/step-11.cc
  examples/step-13/step-13.cc
  examples/step-14/step-14.cc
  examples/step-16/step-16.cc
  examples/step-17/step-17.cc
  examples/step-18/step-18.cc
  examples/step-20/step-20.cc
  examples/step-21/step-21.cc
  examples/step-22/step-22.cc
  examples/step-24/step-24.cc
  examples/step-26/step-26.cc
  examples/step-27/step-27.cc
  examples/step-29/step-29.cc
  examples/step-31/step-31.cc
  examples/step-32/step-32.cc
  examples/step-36/step-36.cc
  examples/step-4/step-4.cc
  examples/step-43/step-43.cc
  examples/step-46/step-46.cc
  examples/step-48/step-48.cc
  examples/step-5/step-5.cc
  examples/step-50/step-50.cc
  examples/step-51/step-51.cc
  examples/step-56/step-56.cc
  examples/step-58/step-58.cc
  examples/step-59/step-59.cc
  examples/step-61/step-61.cc
  examples/step-67/step-67.cc
  examples/step-7/step-7.cc
  examples/step-76/step-76.cc
  examples/step-78/step-78.cc
  examples/step-9/step-9.cc
Labels: Tutorials, ready to test

#17066 Compile mg_transfer_global_coarsening.cc separately in unity build
  source/multigrid/CMakeLists.txt
Labels: Build system, ready to test

#16759 Let `hp::Refinement::choose_p_over_h()` communicate future FE indices and refinement flags on all types of parallel Triangulation.
  doc/news/changes/minor/20240318Fehling
  include/deal.II/distributed/tria.h
  include/deal.II/dofs/dof_handler.h
  source/distributed/tria.cc
  source/distributed/tria.inst.in
  source/dofs/dof_handler.cc
  source/hp/refinement.cc
  tests/mpi/hp_choose_p_over_h.cc
  tests/mpi/hp_choose_p_over_h.with_p4est=true.mpirun=4.output
Labels: hp adaptivity, Parallel, ready to test

#17068 Fix regression test
  include/deal.II/matrix_free/fe_remote_evaluation.h
Labels: Matrix-free, ready to test

#17069 Avoid a compiler error in symengine tests about mismatched operands.
  tests/symengine/sd_common_tests/batch_optimizer_05.h
  tests/symengine/sd_common_tests/utilities.h
Labels: External libraries, ready to test

#17070 Add a missing header file.
  include/deal.II/numerics/time_dependent.h
Labels: ready to test

#17071 Work around a BOOST issue with C++20.
  include/deal.II/numerics/rtree.h
Labels: ready to test, C++20

#17072 Minor edits to step-55.
  examples/step-55/step-55.cc
Labels: Tutorials, ready to test

#17065 Avoid the use of MeshWorker::LocalIntegrator and MeshWorker::integration_loop().
  examples/step-39/step-39.cc
Labels: Tutorials, ready to test

#17067 Deprecate MeshWorker::LocalIntegrator.
  include/deal.II/meshworker/local_integrator.h
  include/deal.II/meshworker/local_results.h
  include/deal.II/meshworker/loop.h
  include/deal.II/meshworker/vector_selector.h
Labels: ready to test

#16958 FEPointEvaluation: Use separate reinit function for clearer separation
  include/deal.II/matrix_free/fe_point_evaluation.h
Labels: Matrix-free, ready to test

#17079 step-55: Give better names to local matrices.
  examples/step-55/step-55.cc
Labels: Tutorials, ready to test

#17078 step-53: Minor edit.
  examples/step-53/step-53.cc
Labels: Tutorials, ready to test

#17077 step-55: Be uniform where timer sections are placed.
  examples/step-55/step-55.cc
Labels: Tutorials, ready to test

#17017 Remove Quadrature(unsigned int) from the public interface.
  doc/news/changes/incompatibilities/20240513Bangerth-2
  include/deal.II/base/quadrature.h
  include/deal.II/numerics/vector_tools_project.h
  source/base/quadrature.cc
  tests/base/qprojector.cc
  tests/base/quadrature_is_tensor_product.cc
  tests/hp/fe_nothing_dominates_01.cc
  tests/hp/fe_nothing_dominates_02.cc
Labels: Miscellaneous, ready to test

#17081 fix incorrect comment in Tensor::unroll
  include/deal.II/base/tensor.h
Labels: ready to test

#17080 Fix some minor gcc-14 warnings.
  include/deal.II/matrix_free/evaluation_kernels_face.h
  include/deal.II/numerics/rtree.h
  source/grid/grid_tools_dof_handlers.cc
Labels: Reviewed and ready to merge, Miscellaneous, ready to test

#17054 Add doxygen documentation of python functions
  contrib/python-bindings/source/export_triangulation.cc
  include/deal.II/grid/grid_generator.h
Labels: Documentation, Reviewed and ready to merge, ready to test

#17085 fix bug in FESystem degree with 0 multiplicity
  include/deal.II/fe/fe_tools.templates.h
  tests/fe/system_05.cc
  tests/fe/system_05.output
Labels: Reviewed and ready to merge, ready to test
