Repository dealii/dealii, pull requests merged in 2024-09, with the labels that each got.

#17491 Added support for magic_enum.
  cmake/configure/configure_50_magic_enum.cmake
  cmake/modules/FindDEAL_II_MAGIC_ENUM.cmake
  doc/news/changes/minor/20240812LucaHeltai
  include/deal.II/base/config.h.in
  include/deal.II/base/patterns.h
  tests/parameter_handler/pattern_tools_14.cc
  tests/parameter_handler/pattern_tools_14.with_magic_enum=true.output
  tests/parameter_handler/pattern_tools_15.cc
  tests/parameter_handler/pattern_tools_15.with_magic_enum=true.output
Labels: ready to test

#17637 DoFTools::extract_constant_modes() and extract_rigid_body_modes(): make ComponentMask optional
  examples/step-42/step-42.cc
  examples/step-90/step-90.cc
  include/deal.II/dofs/dof_tools.h
  source/dofs/dof_tools.cc
  tests/mpi/extract_rigid_body_modes_01.cc
Labels: ready to test

#17638 Make sure `stride_small_size` is at least 1.
  source/base/mpi_compute_index_owner_internal.cc
Labels: Bug, Do not merge :skull_and_crossbones:, ready to test

#17641 Fix pcout in step-75.
  examples/step-75/step-75.cc
Labels: Bug, Tutorials, ready to test

#17644 Add empty() function to deal.II/lac/vector.h and use it instead of size()==0
  examples/step-28/step-28.cc
  examples/step-39/step-39.cc
  include/deal.II/lac/vector.h
  source/numerics/data_out_stack.cc
Labels: Enhancement, ready to test

#17592 Add TaskResult::emplace_object().
  doc/news/changes/minor/20240821Bangerth
  include/deal.II/base/task_result.h
  tests/multithreading/task_result_06.cc
  tests/multithreading/task_result_06.output
Labels: Parallel, ready to test

#17642 Workstream::run() colored implementation with TaskFlow
  include/deal.II/base/work_stream.h
Labels: Parallel, ready to test

#17648 Add another testcase for make_consistent_in_parallel().
  tests/lac/constraints_make_consistent_in_parallel_05_nonowning.cc
  tests/lac/constraints_make_consistent_in_parallel_05_nonowning.mpirun=5.output
Labels: ready to test

#17649 Rename the argument of a lambda function.
  include/deal.II/lac/affine_constraints.templates.h
Labels: ready to test

#17590 Fix FiniteElement::has_generalized_support_points() and FiniteElement::has_face_support_points() for FE_Nothing. #17584
  doc/news/changes/minor/20240821Marquis
  include/deal.II/fe/fe.h
  source/fe/fe.cc
  source/fe/fe_q_base.cc
  tests/fe/has_face_support_points_01.cc
  tests/fe/has_face_support_points_01.output
  tests/fe/has_generalized_support_points_01.cc
  tests/fe/has_generalized_support_points_01.output
Labels: ready to test

#17655 Fix indentation script
  contrib/utilities/indent
  contrib/utilities/indent-all
  doc/news/changes/incompatibilities/20240103AfricaBlaisMunch
  doc/news/changes/incompatibilities/20240821Munch
  doc/news/changes/minor/20240811Gassmoeller
  doc/news/changes/minor/20240814chaycha
  doc/news/changes/minor/20240828Shi
Labels: Reviewed and ready to merge

#17660 NVCC: work around compiler bug
  include/deal.II/lac/petsc_matrix_base.h
Labels: Reviewed and ready to merge, GPU, ready to test

#17656 Filter output of parameter_handler_29 test
  tests/parameter_handler/parameter_handler_29.cc
  tests/parameter_handler/parameter_handler_29.output
  tests/parameter_handler/parameter_handler_29.output.clang-apple
Labels: Reviewed and ready to merge, ready to test

#17611 Enhance test for hp-constraints.
  tests/lac/constraints_make_consistent_in_parallel_06.cc
  tests/lac/constraints_make_consistent_in_parallel_06.mpirun=2.output
Labels: ready for review, Reviewed and ready to merge, ready to test

#17374 Implement Lazy in terms of TaskResult.
  include/deal.II/base/lazy.h
  include/deal.II/base/task_result.h
Labels: ready to test

#17647 Avoid some copying of data in make_consistent_in_parallel().
  include/deal.II/lac/affine_constraints.h
  include/deal.II/lac/affine_constraints.templates.h
Labels: ready to test

#17661 Fix indent run of changelog entry
  doc/news/changes/minor/20240821Marquis
Labels: Documentation

#17658 fix cmake bug in PETSC_WITH_KOKKOS check
  cmake/configure/configure_20_petsc.cmake
Labels: Reviewed and ready to merge, GPU, ready to test

#17134 Additional Data for Solver CG
  include/deal.II/lac/solver_cg.h
  tests/lac/solver.cc
  tests/lac/solver.output
Labels: Linear Algebra, ready to test

#17663 Flag variable maybe_unused.
  include/deal.II/lac/affine_constraints.templates.h
Labels: Reviewed and ready to merge, ready to test

#17631 cuda-clang tester: update clang version (and ubuntu version)
  .github/workflows/linux.yml
  cmake/modules/FindDEAL_II_KOKKOS.cmake
Labels: Infrastructure, GPU

#17670 Make a lambda function a proper function of its own.
  include/deal.II/lac/affine_constraints.templates.h
Labels: Linear Algebra, ready to test

#17673 Rename function arguments in SmartPointer.
  include/deal.II/base/smartpointer.h
Labels: ready to test

#17668 fix step-2 svg display
  examples/step-2/doc/results.dox
Labels: Documentation

#17675 Rename a member of class SmartPointer.
  include/deal.II/base/smartpointer.h
Labels: ready to test

#17682 Make it possible to include nonlinear.h when no external libs are enabled
  include/deal.II/numerics/nonlinear.h
  tests/numerics/nonlinear_solver_selector_04.cc
  tests/numerics/nonlinear_solver_selector_04.output
Labels: Reviewed and ready to merge, ready to test

#17639 add GridGenerator::alfeld_split_of_simplex_mesh
  doc/doxygen/images/alfeld-split.dia
  doc/doxygen/images/alfeld-split.svg
  doc/doxygen/references.bib
  include/deal.II/grid/grid_generator.h
  source/grid/grid_generator.cc
  source/grid/grid_generator.inst.in
  tests/simplex/alfeld_split_01.cc
  tests/simplex/alfeld_split_01.output
Labels: ready to test, Simplices

#17676 Test that one can put a SmartPointer into a std::any object.
  tests/base/smart_pointer_01.cc
  tests/base/smart_pointer_01.run_only
Labels: ready to test

#17677 Update documentation of class SmartPointer.
  include/deal.II/base/smartpointer.h
Labels: Documentation, ready to test

#17681 GridGenerator::convert_hypercube_to_simplex_mesh: code cleanup
  source/grid/grid_generator.cc
Labels: ready to test

#17678 Triangulation::get_boundary_ids(): don't return duplicates.
  doc/news/changes/minor/20240906Wells
  source/grid/tria.cc
  tests/grid/grid_in_vtk_1d_3d.cc
  tests/grid/grid_in_vtk_1d_3d.output
Labels: Bug, Reviewed and ready to merge, ready to test, Co-dimension one

#17679 Ensure SmartPointer gives useful compiler errors for types not derived from Subscriptor.
  include/deal.II/base/smartpointer.h
Labels: ready to test

#17671 Update tidy tester to ubuntu 24.04.
  .clang-tidy
  .github/workflows/tidy.yml
  contrib/utilities/run_clang_tidy.sh
Labels: Reviewed and ready to merge

#17693 Make the semantics of a lambda capture clear.
  include/deal.II/base/work_stream.h
Labels: ready to test

#17695 Minor cleanups to AffineConstraints to make code easier to read.
  include/deal.II/lac/affine_constraints.templates.h
Labels: Linear Algebra, ready to test

#17690 More tests for ParsedFunction.
  tests/bits/parsed_function_constants.cc
  tests/bits/parsed_function_constants.with_muparser=true.output
  tests/bits/parsed_function_constants_with_errors.cc
  tests/bits/parsed_function_constants_with_errors.with_muparser=true.output
Labels: Tests, ready to test

#17697 Remove references to BlockMatrixArray from the documentation.
  include/deal.II/fe/fe.h
  include/deal.II/lac/matrix_block.h
  include/deal.II/lac/precondition_block.h
  include/deal.II/meshworker/assembler.h
Labels: Documentation

#17699 `AffineConstraints`: Improve loop
  include/deal.II/lac/affine_constraints.templates.h
Labels: Reviewed and ready to merge, ready to test

#17702 Better document an algorithm.
  include/deal.II/lac/affine_constraints.templates.h
Labels: ready to test

#17708 Add a forgotten closing parenthesis.
  examples/step-6/doc/results.dox
Labels: Tutorials

#17408 Symmetrize fourth order tensor
  doc/news/changes/minor/20240731Vinayak
  include/deal.II/base/symmetric_tensor.h
  tests/tensors/symmetric_tensor_47.cc
  tests/tensors/symmetric_tensor_47.output
Labels: Reviewed and ready to merge, ready to test

#17704 Use Utilties::MPI::compute_index_owner() instead of lower-level facilities.
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  source/distributed/repartitioning_policy_tools.cc
  source/multigrid/mg_tools.cc
Labels: ready to test

#17701 Clarify documentation.
  include/deal.II/base/mpi_compute_index_owner_internal.h
Labels: ready to test

#17698 Remove a section about ways to use doxygen that we don't use.
  doc/developers/writing-documentation.html
Labels: Documentation

#17714 Make sure the SmartPointer template remains accessible.
  include/deal.II/base/observer_pointer.h
  include/deal.II/base/smartpointer.h
Labels: ready to test

#17707 Make improvements to the WorkStream colored implementation
  include/deal.II/base/work_stream.h
Labels: Reviewed and ready to merge, Parallel, ready to test

#17700 Make clear what a boolean argument corresponds to.
  include/deal.II/base/mpi_compute_index_owner_internal.h
  source/base/mpi.cc
  source/base/mpi_compute_index_owner_internal.cc
Labels: ready to test

#17720 FunctionParser: document where we use commas.
  include/deal.II/base/function_parser.h
Labels: Documentation, ready to test

#17725 capitalize Python and Jupyter
  examples/step-3/doc/results.dox
  examples/step-49/doc/intro.dox
  examples/step-62/doc/intro.dox
  examples/step-62/doc/results.dox
  examples/step-62/step-62.cc
Labels: Documentation, ready to test

#17726 update tutorial index to mention python notebooks
  doc/doxygen/tutorial/tutorial.h.in
Labels: Documentation, ready to test

#17306 `FEInterfaceValues`: fill indices for `TriaIterator<CellAccessor>`
  include/deal.II/fe/fe_interface_values.h
  tests/feinterface/fe_interface_values_02.cc
  tests/feinterface/fe_interface_values_02.output
Labels: Reviewed and ready to merge, ready to test

#17727 Generalize MGTransferMF so that it works for FE_DGP
  doc/news/changes/minor/20240924Munch
  include/deal.II/multigrid/mg_transfer_global_coarsening.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  tests/multigrid-global-coarsening/mg_transfer_a_07.cc
  tests/multigrid-global-coarsening/mg_transfer_a_07.with_p4est=true.mpirun=1.output
  tests/multigrid-global-coarsening/mg_transfer_util.h
Labels: ready to test

#17666 Generalized read_msh to allow for comments
  source/grid/grid_in.cc
  tests/grid/grid_in_msh_version_2.cc
  tests/grid/grid_in_msh_version_2.output
  tests/grid/grid_in_msh_version_2/hole81_commented.msh
Labels: Reviewed and ready to merge, ready to test

#17733 Remove some tests from linux.yml
  .github/workflows/linux.yml
Labels: ready to test

#17736 Fix typo in an internal class name
  include/deal.II/matrix_free/matrix_free.templates.h
Labels: Matrix-free, ready to test

#17737 A fix for a bug in the time table
  source/base/timer.cc
Labels: Reviewed and ready to merge, ready to test
