Repository dealii/dealii, pull requests merged in 2024-08, with the labels that each got.

#17411 step-64: cleanup intro, remove CUDA, mention Kokkos
  examples/step-64/doc/intro.dox
  include/deal.II/lac/cuda_vector.h
Labels: Reviewed and ready to merge

#17418 step-64: update info
  doc/doxygen/tutorial/tutorial.h.in
  examples/step-64/doc/tooltip
Labels: Tutorials, ready to test

#17417 Kokkos: disable CUDA warnings when using Kokkos from Trilinos
  cmake/modules/FindDEAL_II_KOKKOS.cmake
Labels: ready to test

#17420 patch bundled boost: nvcc and immintrin.h
  bundled/boost-1.84.0/include/boost/multiprecision/cpp_int/intel_intrinsics.hpp
Labels: GPU, ready to test

#17422 PETScWrappers: don't call deprecated viewer functions.
  source/lac/petsc_matrix_base.cc
  source/lac/petsc_vector_base.cc
Labels: External libraries, ready to test

#17426 [9.6] patch bundled boost: nvcc and immintrin.h (PR #17420)
  bundled/boost-1.84.0/include/boost/multiprecision/cpp_int/intel_intrinsics.hpp
Labels: ready to test

#17431 Remove redundant type qualifiers in dynamic_casts
  source/lac/trilinos_solver.cc
Labels: Reviewed and ready to merge, ready to test

#17427 step-75: add a missing reference
  examples/step-75/step-75.cc
Labels: Tutorials, ready to test

#17428 Fix MatrixFreeTools::compute_diagonal
  doc/news/changes/minor/20240803Munch
  include/deal.II/matrix_free/tools.h
  tests/matrix_free/compute_diagonal_07.cc
  tests/matrix_free/compute_diagonal_07.output
Labels: Bug, Matrix-free, ready to test

#17429 [9.6] PETScWrappers: don't call deprecated viewer functions.
  source/lac/petsc_matrix_base.cc
  source/lac/petsc_vector_base.cc
Labels: External libraries, ready to test

#17388 Enable `setup_tests_examples` in Windows workflow.
  .github/workflows/windows.yml
Labels: Reviewed and ready to merge, Tests, Windows

#17410 [9.6] Fix p2_adaptive.prm file for step-42
  examples/step-42/p2_adaptive.prm
Labels: Reviewed and ready to merge, Tutorials, ready to test

#17436 Update print_deprecated.py for python3
  contrib/utilities/print_deprecated.py
Labels: Infrastructure

#17396 VT::interpolate() for multigrid levels
  doc/news/changes/minor/20240726Munch
  include/deal.II/numerics/vector_tools_interpolate.h
  include/deal.II/numerics/vector_tools_interpolate.templates.h
  source/numerics/vector_tools_interpolate.inst.in
  tests/multigrid/mg_data_out_04.cc
  tests/multigrid/mg_data_out_04.with_p4est=true.mpirun=2.output
Labels: ready to test

#17423 PETScWrappers: don't use deprecated functions.
  source/lac/petsc_communication_pattern.cc
Labels: External libraries, ready to test

#17415 Fix pointer traversal range of PETSc vectors on each process
  doc/news/changes/minor/20240801Shi
  source/lac/petsc_vector_base.cc
Labels: Linear Algebra, ready to test

#17425 fix nvcc compilation in particle handler
  include/deal.II/particles/particle_accessor.h
  include/deal.II/particles/property_pool.h
Labels: Reviewed and ready to merge, GPU, ready to test

#17437 Use aliases for TpetraTypes::[Dual]View[Unmanaged]
  examples/step-86/step-86.cc
  include/deal.II/lac/trilinos_tpetra_precondition.templates.h
  include/deal.II/lac/trilinos_tpetra_types.h
Labels: Reviewed and ready to merge, External libraries, ready to test

#17424 silence a Kokkos+CUDA warning
  cmake/modules/FindDEAL_II_KOKKOS.cmake
Labels: Reviewed and ready to merge, GPU, ready to test

#17444 Remove deprecations in 9.5.0 release
  doc/news/changes/20240807DanielArndt
  include/deal.II/base/array_view.h
  include/deal.II/base/data_out_base.h
  include/deal.II/base/mpi.h
  include/deal.II/base/mpi_tags.h
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/base/tensor.h
  include/deal.II/distributed/fully_distributed_tria.h
  include/deal.II/distributed/tria.h
  include/deal.II/distributed/tria_base.h
  include/deal.II/dofs/dof_handler.h
  include/deal.II/fe/mapping_q.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/lac/slepc_spectral_transformation.h
  include/deal.II/particles/particle_accessor.h
  include/deal.II/particles/particle_handler.h
  include/deal.II/physics/transformations.h
  source/base/data_out_base.cc
  source/base/mpi.cc
  source/distributed/fully_distributed_tria.cc
  source/distributed/tria.cc
  source/fe/mapping_q.cc
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
  source/lac/slepc_spectral_transformation.cc
  source/particles/particle_handler.cc
  tests/mpi/create_group_01.cc
  tests/mpi/create_group_01.mpirun=3.output
  tests/mpi/data_out_hdf5_02.cc
  tests/mpi/p4est_save_01.cc
  tests/mpi/p4est_save_02.cc
  tests/mpi/p4est_save_03.cc
  tests/particles/step-19.cc
  tests/tensors/tensor.cc
  tests/tensors/tensor_complex.cc
  tests/tensors/tensor_float.cc
Labels: ready to test

#17446 Add missing assertions.
  source/fe/fe_values_views.cc
Labels: ready to test

#17447 Edit step-86 CMakeLists.txt such that it recognizes dependency on P4EST
  examples/step-86/CMakeLists.txt
Labels: Build system, Reviewed and ready to merge, External libraries, ready to test

#17439 [9.6] Use aliases for TpetraTypes::[Dual]View[Unmanaged]
  examples/step-86/step-86.cc
  include/deal.II/lac/trilinos_tpetra_precondition.templates.h
  include/deal.II/lac/trilinos_tpetra_types.h
Labels: External libraries, ready to test

#17454 Fix Tpetra for 13.0
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
Labels: External libraries, ready to test

#17452 step-86: Fix mathjax error.
  examples/step-86/doc/intro.dox
Labels: Documentation, ready to test

#17457 Fix tests after removing deprecated code
  tests/cgal/cgal_surface_mesh_05.cc
  tests/symengine/symengine_tensor_operations_04.cc
Labels: Reviewed and ready to merge, Tests, ready to test

#17460 Fix documentation for FE_NedelecSZ
  include/deal.II/fe/fe_nedelec_sz.h
Labels: Reviewed and ready to merge

#17462 [9.6] take over Fix Tpetra with MemorySpace::Default #17430
  include/deal.II/base/index_set.h
  include/deal.II/lac/read_write_vector.h
  include/deal.II/lac/read_write_vector.templates.h
  include/deal.II/lac/trilinos_tpetra_block_sparse_matrix.templates.h
  include/deal.II/lac/trilinos_tpetra_communication_pattern.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  include/deal.II/lac/vector.templates.h
  include/deal.II/lac/vector_element_access.h
  source/base/index_set.cc
  source/lac/trilinos_tpetra_communication_pattern.cc
  source/lac/trilinos_tpetra_sparsity_pattern.cc
Labels: ready to test

#17463 Move some references out of the NedelecSZ class.
  doc/doxygen/references.bib
  include/deal.II/fe/fe_nedelec_sz.h
Labels: Documentation

#17449 Improve an error message.
  include/deal.II/dofs/dof_accessor.templates.h
Labels: ready to test

#17465 Kokkos+CUDA: disable warning
  cmake/modules/FindDEAL_II_KOKKOS.cmake
Labels: GPU, ready to test

#17470 CMake: do not set -fstrict-aliasing explicitly
  cmake/setup_compiler_flags_gnu.cmake
Labels: Build system, Reviewed and ready to merge, ready to test

#17467 step-81: do not require WITH_COMPLEX_VALUES
  examples/step-81/CMakeLists.txt
  tests/examples/step-81.with_umfpack=true.output
Labels: Reviewed and ready to merge, Tutorials, ready to test

#17468 PETScWrappers::VectorBase: avoid hard-coding unsigned int indices.
  include/deal.II/lac/petsc_vector_base.h
Labels: Reviewed and ready to merge, External libraries, ready to test

#17475 step-81: print something more to the screen
  examples/step-81/step-81.cc
  tests/examples/step-81.with_umfpack=true.output
Labels: Tutorials, ready to test

#17469 Check all PETSc index conversions.
  include/deal.II/base/exceptions.h
  include/deal.II/lac/petsc_matrix_base.h
  include/deal.II/lac/petsc_vector_base.h
  source/base/index_set.cc
  source/lac/petsc_communication_pattern.cc
  source/lac/petsc_matrix_base.cc
  source/lac/petsc_parallel_sparse_matrix.cc
  source/lac/petsc_parallel_vector.cc
  source/lac/petsc_sparse_matrix.cc
  source/lac/petsc_vector_base.cc
Labels: Reviewed and ready to merge, External libraries, ready to test

#17471 change DEAL_II_WITH_COMPLEX_VALUES default to OFF
  cmake/setup_cached_variables.cmake
  doc/news/changes/20240811tjhei
  tests/lapack/full_matrix_39.with_complex_values=on.output
  tests/numerics/project_complex.with_complex_values=on.output
Labels: ready to test

#17478 Remove `static_cast`
  tests/mpi/extract_constant_modes_01.cc
  tests/mpi/extract_constant_modes_02.cc
  tests/mpi/extract_constant_modes_03.cc
  tests/mpi/extract_constant_modes_04.cc
  tests/mpi/mg_ghost_layer_periodic.cc
  tests/mpi/p4est_2d_renumber_02.cc
Labels: Reviewed and ready to merge, ready to test

#17481 CMake: allow PETSc to be configured with differing ordinals
  cmake/configure/configure_20_petsc.cmake
Labels: Reviewed and ready to merge, ready to test

#17416 Add move operations to SmartPointer.
  include/deal.II/base/smartpointer.h
  include/deal.II/lac/sparse_matrix.templates.h
Labels: ready to test

#17493 Replace void cast with `[[maybe_unused]]` in FESystem source file
  source/fe/fe_system.cc
Labels: Reviewed and ready to merge, ready to test

#17494 Modernize void cast
  source/fe/mapping_q_eulerian.cc
Labels: Reviewed and ready to merge, ready to test

#17498 Remove first 6/13 void casts in fe.cc
  source/fe/fe.cc
Labels: Reviewed and ready to merge, ready to test

#17507 Fix PETScWrappers::MatrixBase::add()
  include/deal.II/lac/petsc_matrix_base.h
Labels: Bug, Linear Algebra, External libraries, ready to test

#17508 remove [[maybe_unused]] in fe.cc
  source/fe/fe.cc
Labels: High Priority :warning:, ready to test

#17510 Assert Macro: avoid unused parameters (etc.) warnings by always using macro arguments
  include/deal.II/base/exceptions.h
Labels: Bug, High Priority :warning:, ready to test

#17489 Use `[[maybe_unused]]` instead of `(void)` cast
  source/base/function_lib.cc
Labels: Reviewed and ready to merge, ready to test

#17490 Removed first four void casts in `source/distributed/tria.cc` and replaced them with `[[maybe_unused]]`
  source/distributed/tria.cc
Labels: Reviewed and ready to merge, ready to test

#17502 Use `[[maybe_unused]]` instead of void cast
  source/grid/grid_tools.cc
Labels: Reviewed and ready to merge, ready to test

#17492 portable::FEEvaluation documentation fixes
  include/deal.II/matrix_free/portable_fe_evaluation.h
Labels: Reviewed and ready to merge, GPU, ready to test

#17495 Replaced void casts with maybe unused
  source/grid/manifold_lib.cc
Labels: Reviewed and ready to merge, ready to test

#17485 enable c++ standard library debug checks
  cmake/setup_compiler_flags_gnu.cmake
  include/deal.II/multigrid/mg_transfer_global_coarsening.h
  tests/mpi/periodicity_03.cc
  tests/mpi/renumber_cuthill_mckee.cc
Labels: ready to test

#17486 Test all examples.
  examples/step-71/parameters.prm
  tests/examples/CMakeLists.txt.in
  tests/examples/step-62.diff
  tests/examples/step-62.with_petsc=true.with_petsc_with_complex=true.with_p4est=true.with_hdf5=true.run_only
  tests/examples/step-66.diff
  tests/examples/step-66.with_lapack=true.with_mpi=true.with_p4est=true.run_only
  tests/examples/step-71.diff
  tests/examples/step-71.with_trilinos=true.with_trilinos_with_sacado=true.with_symengine=true.run_only
  tests/examples/step-83.diff
  tests/examples/step-83.with_mpi=true.run_only
  tests/examples/step-86.diff
  tests/examples/step-86.with_petsc=true.with_petsc_with_complex=true.run_only
  tests/examples/step-87.diff
  tests/examples/step-87.with_mpi=true.run_only
  tests/examples/step-90.diff
  tests/examples/step-90.with_mpi=true.with_p4est=true.with_trilinos=true.run_only
Labels: Build system, Reviewed and ready to merge, Tutorials, Tests, ready to test

#17509 Remove void cast function lib replace with [[maybe_unused]] attribute
  source/base/function_lib.cc
Labels: Reviewed and ready to merge, ready to test

#17519 Change a variable name in Assert().
  include/deal.II/base/exceptions.h
Labels: Miscellaneous, ready to test

#17515 Consistently use std::uncaught_exceptions().
  source/base/hdf5.cc
  source/base/init_finalize.cc
  source/base/mpi.cc
  source/base/subscriptor.cc
  source/base/timer.cc
Labels: Reviewed and ready to merge, ready to test, C++17

#17512 Fix undefined behavior when advancing nullptr
  include/deal.II/dofs/dof_accessor.templates.h
Labels: Reviewed and ready to merge, ready to test

#17514 cleanup maybe-unused in fe.cc
  source/fe/fe.cc
Labels: Reviewed and ready to merge, ready to test

#17461 Update step-49, step-50 and their diffs.
  doc/news/changes/minor/20240725AE7TB99
  doc/news/changes/minor/20240808AE7TB99
  examples/step-49/step-49.cc
  examples/step-50/step-50.cc
  tests/examples/step-49.diff
  tests/examples/step-50.diff
Labels: Reviewed and ready to merge, ready to test

#17513 Adolc/Symengine: always instantiate complex valued variants
  source/differentiation/ad/adolc_number_types.inst.in
  source/differentiation/ad/sacado_number_types.inst1.in
  source/differentiation/ad/sacado_number_types.inst2.in
  source/differentiation/sd/symengine_number_visitor_internal.inst.in
  source/differentiation/sd/symengine_optimizer.inst.in
  tests/symengine/sd_common_tests/batch_optimizer_01.h
Labels: Reviewed and ready to merge, ready to test

#17517 step-37: use MatrixFreeTools::compute_diagonal()
  examples/step-37/step-37.cc
Labels: Matrix-free, Tutorials, ready to test

#17529 Improve an error message.
  source/fe/fe_system.cc
Labels: Reviewed and ready to merge, ready to test

#17518 Remove a lot of reinterpret_casts.
  include/deal.II/base/polynomial_space.h
  include/deal.II/base/polynomials_rannacher_turek.h
  include/deal.II/base/scalar_polynomials_base.h
  include/deal.II/base/tensor_product_polynomials.h
  include/deal.II/base/tensor_product_polynomials_bubbles.h
  source/base/data_out_base.cc
Labels: ready to test, C++17

#17483 Add more C++ resources to step-1.
  examples/step-1/doc/intro.dox
Labels: Tutorials

#17528 Add a note to step-86.
  examples/step-86/doc/results.dox
Labels: Documentation, Tutorials

#17524 Assert: release mode fixes: constexpr context, disable warnings in release mode
  cmake/setup_compiler_flags_gnu.cmake
  include/deal.II/base/exceptions.h
Labels: Bug, High Priority :warning:, Reviewed and ready to merge, ready to test

#17487 Use `[[maybe_unused]]` instead of `(void)` cast
  source/distributed/tria.cc
Labels: ready to test

#17497 Remove void casts and use `[[maybe_unused]]` instead
  source/grid/tria.cc
Labels: ready to test

#17531 Fix a typo test.
  .typos.toml
  tests/parameter_handler/prm/parameter_handler_26_fail.json
  tests/parameter_handler/prm/parameter_handler_26_fail.prm
Labels: Reviewed and ready to merge, ready to test

#17534 Get rid of some more reinterpret_casts.
  include/deal.II/base/tensor_product_polynomials.h
  include/deal.II/lac/affine_constraints.templates.h
Labels: ready to test, C++17

#17538 Fix compiling SolutionTransfer with complex values
  source/numerics/solution_transfer.cc
Labels: ready to test

#17537 fix compilation warning (unused arg)
  source/distributed/tria.cc
  source/grid/tria.cc
Labels: High Priority :warning:, ready to test

#17539 Drop support for p4est versions older than 2.2.
  cmake/configure/configure_50_p4est.cmake
  doc/news/changes/incompatibilities/20240815DavidWells
  source/distributed/tria.cc
Labels: Reviewed and ready to merge, External libraries, ready to test

#17525 Support multiple components in `Portable::MatrixFree`
  doc/news/changes/minor/20240814Munch
  include/deal.II/matrix_free/portable_fe_evaluation.h
  include/deal.II/matrix_free/portable_hanging_nodes_internal.h
  include/deal.II/matrix_free/portable_matrix_free.h
  include/deal.II/matrix_free/portable_matrix_free.templates.h
  tests/matrix_free_kokkos/matrix_vector_host_device_multi_component.cc
  tests/matrix_free_kokkos/matrix_vector_host_device_multi_component.output
Labels: GPU, ready to test

#17504 Replaced void cast with maybe_unused
  source/grid/tria_accessor.cc
Labels: ready to test

#17546 Fix typo: residuum -> residual
  include/deal.II/lac/precondition.h
Labels: Documentation

#17545 MPI sum: Do not invoke MPI function for MPI_COMM_SELF
  include/deal.II/base/mpi.templates.h
Labels: Parallel distributed, ready to test

#17503 Remove void cast mpi
  source/base/mpi.cc
Labels: ready to test

#17501 Use `[[maybe_unused]]` instead of void cast
  source/base/function_lib.cc
Labels: Reviewed and ready to merge, ready to test

#17541 Improve our 32-bit vs 64-bit PETSc documentation.
  cmake/setup_cached_variables.cmake
  doc/developers/packaging.html
  doc/external-libs/petsc.html
  doc/readme.html
Labels: Documentation

#17543 removed (void) occurrences from source/fe/fe_face.cc
  source/fe/fe_face.cc
Labels: Reviewed and ready to merge, ready to test

#17548 Fix some unused warnings.
  source/base/mpi.cc
Labels: ready to test

#17532 Update some uses of [[maybe unused]]
  source/distributed/tria.cc
  source/grid/tria.cc
Labels: Reviewed and ready to merge, ready to test

#17552 Always use Kokkos::abort when it's noreturn
  source/base/exceptions.cc
Labels: Reviewed and ready to merge, ready to test

#17560 Check for Fortran again
  CMakeLists.txt
Labels: ready to test

#17559 Outsource building documentation into separate github workflow.
  .github/workflows/indent.yml
Labels: Infrastructure

#17555 fixed (void) in grid_tools.cc
  source/grid/grid_tools.cc
Labels: ready to test

#17542 Consolidate two Utilities::MPI::broadcast() functions.
  include/deal.II/base/mpi.h
Labels: ready to test, C++17

#17520 Assert correction for issue #17450
  include/deal.II/numerics/vector_tools_interpolate.templates.h
Labels: ready to test

#17558 [9.6] Tpetra: Fix is_vector_space_vector check with complex values
  source/lac/trilinos_tpetra_block_vector.cc
  source/lac/trilinos_tpetra_vector.cc
Labels: ready to test

#17566 Add get_mpi_communicator() to concept vector_space_vector
  doc/news/changes/minor/20240819Kronbichler
  include/deal.II/base/template_constraints.h
  include/deal.II/lac/block_vector_base.h
  include/deal.II/lac/vector.h
Labels: Linear Algebra, ready to test

#17567 Create new string when demangling stacktraces
  source/base/exceptions.cc
Labels: ready to test

#17572 Suppress a warning about an unused variable.
  source/fe/fe_face.cc
Labels: Miscellaneous, ready to test

#17549 FESystem: Compare for domination by component instead of base element
  source/fe/fe_system.cc
  tests/hp/fe_collection_05.cc
  tests/hp/fe_collection_06.cc
Labels: Reviewed and ready to merge, ready to test

#17570 Simplify typos workflow.
  .github/dependabot.yml
  .github/workflows/indent.yml
  .github/workflows/typos.yml
Labels: ready for review, Infrastructure

#17574 Portable matrix-free: Add missing header files
  tests/performance/timing_matrix_free_kokkos.cc
Labels: Matrix-free, Tests, ready to test

#17500 Retire DEAL_II_COMPILE_EXAMPLES.
  cmake/checks/check_02_system_features.cmake
  cmake/setup_cached_variables.cmake
  contrib/docker/Dockerfile
  doc/developers/packaging.html
  doc/news/changes/incompatibilities/20240812Fehling
  doc/users/config.sample
  examples/CMakeLists.txt
  examples/step-17/CMakeLists.txt
  examples/step-18/CMakeLists.txt
  examples/step-22/CMakeLists.txt
  examples/step-29/CMakeLists.txt
  examples/step-31/CMakeLists.txt
  examples/step-32/CMakeLists.txt
  examples/step-33/CMakeLists.txt
  examples/step-34/CMakeLists.txt
  examples/step-35/CMakeLists.txt
  examples/step-36/CMakeLists.txt
  examples/step-37/CMakeLists.txt
  examples/step-40/CMakeLists.txt
  examples/step-41/CMakeLists.txt
  examples/step-42/CMakeLists.txt
  examples/step-43/CMakeLists.txt
  examples/step-45/CMakeLists.txt
  examples/step-46/CMakeLists.txt
  examples/step-47/CMakeLists.txt
  examples/step-50/CMakeLists.txt
  examples/step-52/CMakeLists.txt
  examples/step-53/CMakeLists.txt
  examples/step-54/CMakeLists.txt
  examples/step-55/CMakeLists.txt
  examples/step-56/CMakeLists.txt
  examples/step-57/CMakeLists.txt
  examples/step-58/CMakeLists.txt
  examples/step-59/CMakeLists.txt
  examples/step-60/CMakeLists.txt
  examples/step-62/CMakeLists.txt
  examples/step-64/CMakeLists.txt
  examples/step-66/CMakeLists.txt
  examples/step-68/CMakeLists.txt
  examples/step-69/CMakeLists.txt
  examples/step-70/CMakeLists.txt
  examples/step-71/CMakeLists.txt
  examples/step-72/CMakeLists.txt
  examples/step-74/CMakeLists.txt
  examples/step-75/CMakeLists.txt
  examples/step-77/CMakeLists.txt
  examples/step-79/CMakeLists.txt
  examples/step-81/CMakeLists.txt
  examples/step-82/CMakeLists.txt
  examples/step-83/CMakeLists.txt
  examples/step-85/CMakeLists.txt
  examples/step-86/CMakeLists.txt
  examples/step-87/CMakeLists.txt
  examples/step-89/CMakeLists.txt
  examples/step-90/CMakeLists.txt
  tests/run_buildtest.cmake
  tests/run_performance_tests.cmake
Labels: Build system, Tutorials, ready to test

#17383 Add clear() and Tvmult() for SparseVanka
  doc/news/changes/minor/20240814chaycha
  include/deal.II/lac/sparse_vanka.h
  include/deal.II/lac/sparse_vanka.templates.h
  source/lac/sparse_vanka.cc
Labels: Linear Algebra, ready to test

#17577 Leave a comment in the documentation.
  include/deal.II/dofs/dof_tools.h
Labels: Documentation

#17569 Allow to place FEFaceEvaluation objects in std::vector
  doc/news/changes/minor/20240819Kronbichler-1
  include/deal.II/matrix_free/fe_evaluation.h
  tests/matrix_free/fe_face_evaluation_vector.cc
  tests/matrix_free/fe_face_evaluation_vector.output
Labels: Matrix-free, ready to test

#17580 Fix some warnings
  source/distributed/tria.cc
Labels: Reviewed and ready to merge, ready to test

#17575 [9.6] Create new string when demangling stacktraces
  source/base/exceptions.cc
Labels: Reviewed and ready to merge, ready to test

#17587 Reintroduce a fast path for FESystem::compare_for_domination().
  source/fe/fe_system.cc
Labels: Reviewed and ready to merge, ready to test

#17585 Adjust a variable name in a test.
  tests/fe/fe_data_test.cc
Labels: Reviewed and ready to merge, ready to test

#17581 Enhance documentation of SolutionTransfer.
  include/deal.II/numerics/solution_transfer.h
Labels: Documentation

#17582 Portable MatrixFree: Allow initializing host vector
  include/deal.II/matrix_free/portable_matrix_free.h
  include/deal.II/matrix_free/portable_matrix_free.templates.h
  source/matrix_free/portable_matrix_free.cc
  tests/matrix_free_kokkos/matrix_free_device_initialize_vector.cc
  tests/matrix_free_kokkos/matrix_free_device_initialize_vector.with_mpi=on.with_p4est=on.mpirun=1.output
  tests/matrix_free_kokkos/matrix_free_device_initialize_vector.with_mpi=on.with_p4est=on.mpirun=2.output
  tests/matrix_free_kokkos/matrix_free_device_initialize_vector.with_mpi=on.with_p4est=on.with_cuda=off.mpirun=1.output
Labels: Reviewed and ready to merge, ready to test

#17571 Update typos to 1.23.6.
  .github/dependabot.yml
  .github/workflows/indent.yml
  .typos.toml
  examples/step-53/topography.license
  include/deal.II/base/thread_management.h
  include/deal.II/differentiation/sd/symengine_number_visitor_internal.h
  include/deal.II/lac/trilinos_sparse_matrix.h
  include/deal.II/multigrid/mg_constrained_dofs.h
  include/deal.II/numerics/point_value_history.h
  include/deal.II/numerics/rtree.h
  tests/bits/fe_tools_09.cc
  tests/bits/fe_tools_10.cc
  tests/bits/fe_tools_11.cc
  tests/fullydistributed_grids/copy_serial_tria_04.cc
  tests/gmsh/gmsh_api_06.cc
  tests/matrix_free/get_cell_category_01.cc
  tests/matrix_free/get_cell_category_01.output
  tests/petsc_complex/vector_equality_1.cc
Labels: ready for review, Infrastructure, Reviewed and ready to merge, ready to test

#17557 Use doxygen-awesome template for the documentation
  doc/doxygen/CMakeLists.txt
  doc/doxygen/custom.css
  doc/doxygen/doxygen-awesome.css
  doc/doxygen/options.dox.in
Labels: Documentation, Reviewed and ready to merge, ready to test

#17589 remove a forgotten cuda quick_test output
  tests/quick_tests/cuda.with_cuda=true.run_only
Labels: ready to test

#17593 ParameterHandler: Only keep non-default parameters during printing
  doc/news/changes/minor/20240822Munch
  include/deal.II/base/parameter_handler.h
  source/base/parameter_handler.cc
  tests/parameter_handler/parameter_handler_read_json_05.cc
  tests/parameter_handler/parameter_handler_read_json_05.output
Labels: Reviewed and ready to merge, ready to test

#17398 Remove step-52
  doc/doxygen/tutorial/tutorial.h.in
  doc/news/8.1.0-vs-8.2.0.h
  doc/news/9.1.1-vs-9.2.0.h
  doc/news/changes/incompatibilities/20240728DanielArndt
  examples/step-26/doc/intro.dox
  examples/step-26/doc/results.dox
  examples/step-52/CMakeLists.txt
  examples/step-52/doc/builds-on
  examples/step-52/doc/intro.dox
  examples/step-52/doc/kind
  examples/step-52/doc/results.dox
  examples/step-52/doc/tooltip
  examples/step-52/step-52.cc
  tests/examples/step-52.diff
  tests/examples/step-52.with_umfpack=true.output
Labels: Reviewed and ready to merge, ready to test

#17477 `DoFTools`: Extract elasticity modes
  doc/news/changes/minor/20240810Munch
  include/deal.II/dofs/dof_tools.h
  include/deal.II/lac/trilinos_precondition.h
  source/dofs/dof_tools.cc
  source/dofs/dof_tools.inst.in
  source/lac/trilinos_precondition_ml.cc
  tests/mpi/extract_rigid_body_modes_01.cc
  tests/mpi/extract_rigid_body_modes_01.mpirun=4.with_p4est=true.output
  tests/mpi/extract_rigid_body_modes_02.cc
  tests/mpi/extract_rigid_body_modes_02.mpirun=4.with_p4est=true.output
  tests/simplex/step-31.cc
Labels: ready to test

#17591 Remove deprecated entries in OutputStyle
  doc/news/changes/incompatibilities/20240821Munch
  examples/step-32/step-32.cc
  examples/step-50/step-50.cc
  examples/step-63/step-63.cc
  include/deal.II/base/parameter_handler.h
  source/base/parameter_handler.cc
  tests/parameter_handler/multiple_parameter_loop_01.cc
  tests/parameter_handler/multiple_parameter_loop_02.cc
  tests/parameter_handler/parameter_handler_24.cc
  tests/parameter_handler/parameter_handler_3.cc
  tests/parameter_handler/parameter_handler_3_with_alias_01.cc
  tests/parameter_handler/parameter_handler_3_with_alias_02.cc
  tests/parameter_handler/parameter_handler_3_with_alias_03.cc
  tests/parameter_handler/parameter_handler_3_with_alias_04.cc
  tests/parameter_handler/parameter_handler_3_with_sorting_01.cc
  tests/parameter_handler/parameter_handler_3_with_space.cc
  tests/parameter_handler/parameter_handler_5.cc
  tests/parameter_handler/parameter_handler_6.cc
  tests/parameter_handler/parameter_handler_6_bool.cc
  tests/parameter_handler/parameter_handler_8.cc
  tests/parameter_handler/parameter_handler_9.cc
  tests/parameter_handler/parameter_handler_subsection_exists.cc
  tests/petsc/petsc_snes_00.cc
  tests/petsc/petsc_ts_00.cc
  tests/petsc/petsc_ts_03.cc
  tests/petsc/petsc_ts_03_compat.cc
  tests/petsc/petsc_ts_04.cc
  tests/petsc/petsc_ts_05.cc
  tests/sundials/arkode_01.cc
  tests/sundials/arkode_03.cc
  tests/sundials/arkode_04.cc
  tests/sundials/arkode_06.cc
  tests/sundials/arkode_07.cc
  tests/sundials/arkode_08.cc
  tests/sundials/arkode_09.cc
  tests/sundials/arkode_10.cc
  tests/sundials/arkode_11.cc
  tests/sundials/ida_01.cc
  tests/sundials/ida_02.cc
  tests/sundials/ida_03.cc
  tests/sundials/ida_04.cc
  tests/sundials/ida_05.cc
Labels: ready to test

#17553 Enable cubic simplex output by DataOut
  doc/news/changes/minor/20240820Munch
  source/base/data_out_base.cc
  tests/simplex/mapping_fe_01.cc
  tests/simplex/mapping_fe_01.output
Labels: ready to test, Simplices

#17119 Implementing Workstream::run() with Taskflow (no coloring)
  include/deal.II/base/work_stream.h
  tests/mpi/mesh_worker_01.cc
  tests/mpi/mesh_worker_02.cc
  tests/mpi/mesh_worker_04.cc
Labels: Parallel shared, Parallel, ready to test

#17604 class graph: remove cuda
  doc/doxygen/headers/main.h
  include/deal.II/base/work_stream.h
Labels: Documentation, GPU

#17602 Convert some GeometryInfos
  source/grid/tria.cc
Labels: Reviewed and ready to merge, Triangulation, ready to test

#17605 doc: wording improvements for simplex functions
  include/deal.II/grid/grid_generator.h
Labels: Documentation, ready to test

#17547 SolverGMRES: Implement optimized orthogonalization also for dealii::Vector
  doc/news/changes/minor/20240816Kronbichler
  include/deal.II/lac/solver_gmres.h
  source/lac/CMakeLists.txt
  source/lac/solver_gmres.cc
  source/lac/solver_gmres.inst.in
Labels: Linear Algebra, ready to test

#17479 `DoFTools::extract_constant_modes()`: return vectors
  examples/step-31/step-31.cc
  examples/step-32/step-32.cc
  examples/step-42/step-42.cc
  examples/step-90/step-90.cc
  include/deal.II/dofs/dof_tools.h
  source/dofs/dof_tools.cc
  source/dofs/dof_tools.inst.in
  tests/dofs/extract_dofs_by_component_04.cc
  tests/mpi/extract_constant_modes_01.cc
  tests/mpi/extract_constant_modes_02.cc
  tests/mpi/extract_constant_modes_03.cc
  tests/mpi/extract_constant_modes_04.cc
  tests/simplex/step-31.cc
  tests/trilinos/precondition_amg_dgp_01.cc
  tests/trilinos/precondition_muelu_dgp.cc
Labels: ready to test

#17466 Allow to deprecate entries in ParameterHandler.
  doc/news/changes/minor/20240811Gassmoeller
  include/deal.II/base/parameter_handler.h
  source/base/parameter_handler.cc
  tests/parameter_handler/parameter_handler_29.cc
  tests/parameter_handler/parameter_handler_29.output
Labels: Reviewed and ready to merge, ready to test

#17612 Give a number of variables explicit types.
  include/deal.II/lac/affine_constraints.templates.h
Labels: ready to test

#17550 Generalize MappingFE::compute_mapping_support_points()
  doc/news/changes/minor/20240816Munch
  source/fe/mapping_fe.cc
  tests/simplex/mapping_fe_02.cc
  tests/simplex/mapping_fe_02.output
Labels: Manifold, ready to test, Simplices

#17618 Substantially simplify code by using MPI::some_to_some().
  include/deal.II/lac/affine_constraints.templates.h
Labels: Reviewed and ready to merge, ready to test

#17617 Finish remaining void cast tutorial PRs
  source/base/function_lib.cc
  source/base/mpi.cc
  source/grid/tria.cc
  tests/matrix_free/matrix_vector_hessians_cells.cc
Labels: Reviewed and ready to merge, ready to test

#17616 Do not print unnecessary whitespace in ParameterHandler
  source/base/parameter_handler.cc
Labels: Reviewed and ready to merge, ready to test

#17596 Add hp hanging node face test.
  tests/hp/hp_hanging_nodes_03.cc
  tests/hp/hp_hanging_nodes_03.output
Labels: Tests, hp adaptivity, ready to test

#17621 Simplify a test.
  tests/lac/constraints_make_consistent_in_parallel_03.cc
Labels: ready to test

#17619 Remove an MPI tag now no longer used.
  include/deal.II/base/mpi_tags.h
Labels: Reviewed and ready to merge, ready to test

#17622 Rename a variable and better document steps.
  include/deal.II/lac/affine_constraints.templates.h
Labels: ready to test

#17584 Fix FiniteElement::has_support_points() for FE_Nothing.
  doc/news/changes/minor/20240820Bangerth
  include/deal.II/fe/fe.h
  source/fe/fe.cc
  tests/fe/has_support_points_01.cc
  tests/fe/has_support_points_01.output
Labels: Finite Element, ready to test

#17625 Make a condition easier to read.
  include/deal.II/lac/affine_constraints.templates.h
Labels: Linear Algebra, ready to test

#17624 Sort a set of indices before importing into IndexSet.
  include/deal.II/lac/affine_constraints.templates.h
Labels: Reviewed and ready to merge, ready to test

#17629 add test for simplex smoothing flags
  tests/simplex/smoothing_01.cc
  tests/simplex/smoothing_01.output
Labels: Reviewed and ready to merge, Tests, ready to test, Simplices

#17630 doxygen: do not zoom out of tutorial graph
  doc/doxygen/doxygen-awesome.css
Labels: Documentation, Reviewed and ready to merge, Tutorials, ready to test

#17606 enable taskflow by default
  bundled/taskflow-3.7.0/taskflow/utility/macros.hpp
  cmake/configure/configure_10_taskflow.cmake
Labels: Reviewed and ready to merge, ready to test, dependencies

#17623 Close an AffineConstraints object before doing anything with it.
  include/deal.II/lac/affine_constraints.templates.h
Labels: ready to test

#17628 Fix Tpetra vector compression state after add() into locally owned entry
  doc/news/changes/minor/20240828Shi
  include/deal.II/lac/trilinos_tpetra_vector.h
  tests/trilinos_tpetra/vector_nonlocal_addition.cc
  tests/trilinos_tpetra/vector_nonlocal_addition.mpirun=3.output
Labels: Reviewed and ready to merge, ready to test

#17634 Fix more warnings for unused variables
  source/grid/tria.cc
Labels: Reviewed and ready to merge, ready to test

#17635 Fix formatting issue in tutorials.
  doc/doxygen/scripts/program2toc.pl
  examples/step-12/doc/intro.dox
  examples/step-15/doc/intro.dox
  examples/step-16/doc/intro.dox
  examples/step-19/doc/intro.dox
  examples/step-22/doc/intro.dox
  examples/step-28/doc/intro.dox
  examples/step-29/doc/intro.dox
  examples/step-31/doc/intro.dox
  examples/step-32/doc/intro.dox
  examples/step-33/doc/intro.dox
  examples/step-34/doc/intro.dox
  examples/step-35/doc/intro.dox
  examples/step-36/doc/intro.dox
  examples/step-37/doc/intro.dox
  examples/step-38/doc/intro.dox
  examples/step-40/doc/intro.dox
  examples/step-41/doc/intro.dox
  examples/step-42/doc/intro.dox
  examples/step-43/doc/intro.dox
  examples/step-44/doc/intro.dox
  examples/step-45/doc/intro.dox
  examples/step-46/doc/intro.dox
  examples/step-47/doc/intro.dox
  examples/step-48/doc/intro.dox
  examples/step-50/doc/intro.dox
  examples/step-51/doc/intro.dox
  examples/step-53/doc/intro.dox
  examples/step-54/doc/intro.dox
  examples/step-55/doc/intro.dox
  examples/step-57/doc/intro.dox
  examples/step-58/doc/intro.dox
  examples/step-59/doc/intro.dox
  examples/step-60/doc/intro.dox
  examples/step-61/doc/intro.dox
  examples/step-62/doc/intro.dox
  examples/step-63/doc/intro.dox
  examples/step-64/doc/intro.dox
  examples/step-65/doc/intro.dox
  examples/step-66/doc/intro.dox
  examples/step-67/doc/intro.dox
  examples/step-68/doc/intro.dox
  examples/step-70/doc/intro.dox
  examples/step-71/doc/intro.dox
  examples/step-72/doc/intro.dox
  examples/step-74/doc/intro.dox
  examples/step-75/doc/intro.dox
  examples/step-76/doc/intro.dox
  examples/step-77/doc/intro.dox
  examples/step-83/doc/intro.dox
  examples/step-86/doc/intro.dox
  examples/step-87/doc/intro.dox
  examples/step-89/doc/intro.dox
Labels: Documentation, Tutorials

#17640 Add a test output file variant.
  tests/parameter_handler/parameter_handler_29.output.clang-apple
Labels: Reviewed and ready to merge, Tests, ready to test
