Repository dealii/dealii, pull requests merged in 2024-11, with the labels that each got.

#17824 Also exclude 'doc/entry-name' from showing up in code gallery programs.
  doc/doxygen/code-gallery/CMakeLists.txt
Labels: Documentation, Tutorials

#17744 Replace std::array with Kokkos::Array in Tensor
  cmake/modules/FindDEAL_II_KOKKOS.cmake
  include/deal.II/base/tensor.h
  tests/serialization/tensor.output
Labels: ready to test

#17815 github-actions: use all available processors for building and testing.
  .github/workflows/indent.yml
  .github/workflows/linux.yml
  .github/workflows/osx.yml
  .github/workflows/windows.yml
Labels: Infrastructure

#17799 allow to attach non-hp- and hp-DoFHandlers to MatrixFree
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
  tests/matrix_free/get_functions_multife3.cc
  tests/matrix_free/get_functions_multife3.output
Labels: Matrix-free, hp adaptivity, ready to test

#17822 Fix up Utilities::posix_memalign().
  source/base/utilities.cc
Labels: Miscellaneous, ready to test

#17778 Introduce Utilities::MPI::compute_index_owner_and_requesters()
  doc/news/changes/minor/20241015Munch-2
  include/deal.II/base/mpi.h
  include/deal.II/lac/sparse_matrix_tools.h
  source/base/mpi.cc
Labels: ready to test

#17823 Improve a cmake variable doc string.
  cmake/setup_cached_variables.cmake
Labels: Documentation, Build system

#17825 MatrixFree: Make DoFInfo::memory_consumption more accurate
  source/matrix_free/dof_info.cc
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#17829 Use Peter's new function in a number of places.
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  source/base/mpi_noncontiguous_partitioner.cc
  source/base/partitioner.cc
  source/matrix_free/vector_data_exchange.cc
Labels: ready to test

#17830 FE_Poly: move content from .templates.h to .cc
  include/deal.II/fe/fe_poly.templates.h
  source/fe/fe_poly.cc
Labels: ready to test

#17833 Fix link
  include/deal.II/non_matching/quadrature_generator.h
Labels: ready to test

#17831 data_out_base.cc: Guard anonymous namespace
  source/base/data_out_base.cc
Labels: ready to test

#17826 Enable DoFRenumbering::matrix_free_data_locality for FE_SimplexP
  doc/news/changes/minor/20241101Kronbichler
  source/dofs/dof_renumbering.cc
  tests/dofs/dof_renumbering_mf_06.cc
  tests/dofs/dof_renumbering_mf_06.mpirun=2.output
Labels: Matrix-free, DoFs, ready to test

#17838 Fix tensor conversion
  include/deal.II/base/tensor.h
  tests/tensors/tensor_33.cc
  tests/tensors/tensor_33.output
Labels: Reviewed and ready to merge, Miscellaneous, ready to test

#17780 FunctionFromFunctionObjects: accept single function
  doc/news/changes/minor/20241015Munch
  include/deal.II/base/function.h
  include/deal.II/base/function.templates.h
Labels: Reviewed and ready to merge, ready to test

#17705 AffineConstraints::compute_locally_relevant_constraints() skip step
  include/deal.II/lac/affine_constraints.templates.h
Labels: Linear Algebra, ready to test

#17842 Add a test.
  tests/simplex/fe_system_01.cc
  tests/simplex/fe_system_01.output
Labels: ready to test

#17844 fix iterator type in parallel::transform()
  include/deal.II/base/parallel.h
Labels: Reviewed and ready to merge, ready to test

#17845 Remove the last calls of an internal MPI implementation.
  include/deal.II/lac/affine_constraints.templates.h
Labels: ready to test

#17846 Improve a p::fd::T exception message.
  source/distributed/fully_distributed_tria.cc
Labels: Documentation, Triangulation, ready to test

#17797 Enable batched matrix-vector product
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/evaluation_kernels_face.h
  include/deal.II/matrix_free/tensor_product_kernels.h
  tests/matrix_free/tensor_product_kernels_01.cc
  tests/matrix_free/tensor_product_kernels_01.output
  tests/simplex/matrix_free_05.cc
  tests/simplex/matrix_free_05.output
Labels: Matrix-free, ready to test

#17847 Move ComputeIndexOwner into mpi.cc.
  include/deal.II/base/mpi_compute_index_owner_internal.h
  include/deal.II/base/mpi_noncontiguous_partitioner.h
  include/deal.II/base/mpi_noncontiguous_partitioner.templates.h
  include/deal.II/lac/sparse_matrix_tools.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  source/base/CMakeLists.txt
  source/base/mpi.cc
  source/base/mpi_compute_index_owner_internal.cc
  source/base/partitioner.cc
  source/matrix_free/vector_data_exchange.cc
  tests/mpi/compute_index_owner_01.cc
Labels: ready to test

#17850 Fix types in parallel.h for TBB.
  include/deal.II/base/parallel.h
Labels: High Priority :warning:, Reviewed and ready to merge, ready to test

#17853 Fix initialization of partitioners in two performance tests
  tests/performance/timing_step_37.cc
  tests/performance/timing_step_37_gc.cc
Labels: Matrix-free, ready to test, Performance tester

#17851 step-59: Do not adjust ghost ranges
  examples/step-59/step-59.cc
Labels: Tutorials, ready to test

#17852 Preconditioners: Make access to vector pointers more uniform
  include/deal.II/lac/precondition.h
Labels: Linear Algebra, ready to test

#17793 Try using interprocedural/link-time optimization.
  cmake/checks/check_02_compiler_features.cmake
  cmake/macros/macro_populate_target_properties.cmake
  cmake/setup_cached_variables.cmake
  doc/news/changes/minor/20241104Bangerth
  doc/users/cmake_dealii.html
  source/CMakeLists.txt
Labels: Build system, Reviewed and ready to merge, ready to test

#17854 Add another resource for people learning how to debug codes.
  examples/step-1/doc/intro.dox
Labels: Documentation

#17856 Be less verbose in cmake.
  cmake/checks/check_02_compiler_features.cmake
Labels: Build system, ready to test

#17849 Adjust return type of eigenvectors(SymmetricTensor).
  include/deal.II/base/symmetric_tensor.h
  include/deal.II/base/symmetric_tensor.templates.h
  source/base/symmetric_tensor.cc
  source/base/symmetric_tensor.inst.in
Labels: ready to test

#17855 No longer base ConsensusAlgorithmsPayload on MPI::ConsensusAlgorithms::Process.
  source/base/mpi.cc
Labels: Parallel distributed, ready to test

#17858 Add MGTwoLevelTransfer and MGTransferMF to doxygen group 'mg'
  include/deal.II/multigrid/mg_transfer_global_coarsening.h
Labels: Documentation, Multigrid

#17859 Deprecate the ConsensusAlgorithms::Payload class.
  doc/news/changes/minor/20241112Bangerth
  include/deal.II/base/mpi_consensus_algorithms.h
Labels: ready to test

#17863 Portable MatrixFree: Some cleanup for fe_degree+1 != n_q_points_1d
  include/deal.II/matrix_free/portable_matrix_free.templates.h
  include/deal.II/matrix_free/tools.h
Labels: Reviewed and ready to merge, GPU, Matrix-free, ready to test

#17864 Better document a case about boundary ids for p::d::T.
  include/deal.II/distributed/tria.h
Labels: Documentation, ready to test

#17867 Require hypre to run some tests
  tests/examples/step-50.mpirun=2.with_p4est=true.with_petsc_with_hypre=true.output
  tests/examples/step-55.mpirun=2.with_p4est=true.with_petsc_with_hypre=true.output
  tests/examples/step-70.with_trilinos=false.with_petsc_with_hypre=true.with_p4est=true.mpirun=1.output
  tests/non_matching/step-70.with_p4est=true.with_petsc_with_hypre=true.mpirun=2.output
Labels: ready to test

#17862 Minor cleanup.
  source/dofs/dof_tools_constraints.cc
Labels: ready to test

#17872 Fix get_communicator_by_value for SUNDIALS 7
  include/deal.II/sundials/n_vector.templates.h
Labels: Reviewed and ready to merge, ready to test

#17871 Fix bug in MatrixFreeTools::compute_diagonal for FE_Nothing
  include/deal.II/matrix_free/tools.h
  tests/matrix_free/compute_diagonal_12.cc
  tests/matrix_free/compute_diagonal_12.with_p4est=true.mpirun=1.output
Labels: Matrix-free, ready to test

#17875 Document the choice of 16 neighbors.
  source/grid/grid_tools_topology.cc
Labels: Documentation, Reviewed and ready to merge

#17876 Manifolds: make the documentation consistent with the 'new' scheme.
  doc/doxygen/headers/glossary.h
  include/deal.II/grid/tria.h
Labels: Documentation, Manifold

#17877 Require hypre to run step-40 in the CI
  tests/examples/step-40.mpirun=2.with_p4est=true.with_petsc_with_hypre=true.output
  tests/examples/step-40.mpirun=2.with_p4est=true.with_petsc_with_hypre=true.output2
Labels: Reviewed and ready to merge, ready to test

#17880 Fix an obviously wrong comment.
  source/fe/mapping_q.cc
Labels: ready to test

#17882 Explain an otherwise unreadable condition.
  include/deal.II/fe/mapping_q_internal.h
Labels: Documentation, ready to test

#17883 Update the usage of MPIEXEC_EXECUTABLE/MPIEXEC
  cmake/modules/FindDEAL_II_MPI.cmake
Labels: Build system

#17885 Fix warning
  source/grid/manifold_lib.cc
Labels: ready to test

#17886 Add assert
  source/grid/tria.cc
Labels: ready to test

#17888 Portable MatrixFree: Export variable for n_q_points
  include/deal.II/matrix_free/tools.h
Labels: GPU, ready to test

#17874 [9.6.1] Cherry-pick bug fixes
  examples/step-59/step-59.cc
  include/deal.II/base/config.h.in
  include/deal.II/base/vectorization.h
  include/deal.II/sundials/n_vector.templates.h
Labels: Reviewed and ready to merge, ready to test

#17889 Remove COMPONENT_EXAMPLES from linux workflow.
  .github/workflows/linux.yml
Labels: Infrastructure, Reviewed and ready to merge

#17865 enable MemorySpace in GMG transfer
  cmake/config/template-arguments.in
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/multigrid/mg_transfer.h
  include/deal.II/multigrid/mg_transfer.templates.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  source/lac/trilinos_sparse_matrix.cc
  source/multigrid/mg_level_global_transfer.cc
  source/multigrid/mg_level_global_transfer.inst.in
  source/multigrid/mg_transfer_global_coarsening.inst.in
  source/multigrid/mg_transfer_prebuilt.inst.in
Labels: GPU, Multigrid, ready to test

#17890 Fix some changelog entries.
  doc/news/changes/incompatibilities/20240811tjhei
  doc/news/changes/minor/20240725AE7TB99
  doc/news/changes/minor/20240730AE7TB99
  doc/news/changes/minor/20240808AE7TB99
Labels: Documentation

#17895 MemorySpace data: Also swap sm pointer
  include/deal.II/base/memory_space_data.h
Labels: Reviewed and ready to merge, Linear Algebra, Parallel shared, ready to test
