Repository dealii/dealii, pull requests merged in 2024-10, with the labels that each got.

#17739 CMake: Bugfix: use #cmakedefine defining/undefining preprocessor macro
  include/deal.II/base/config.h.in
  include/deal.II/base/vectorization.h
Labels: Reviewed and ready to merge, SIMD, ready to test

#17734 Add AlignedVector::insert().
  doc/news/changes/minor/20240926DavidWells
  include/deal.II/base/aligned_vector.h
  tests/base/aligned_vector_01.cc
  tests/base/aligned_vector_01.output
Labels: Enhancement, ready to test

#17740 Return earlier if possible inside `FEPointEvaluation::evaluate`
  include/deal.II/matrix_free/fe_point_evaluation.h
Labels: Matrix-free, ready to test

#17730 NoncontiguousPartitioner: introduce n_components
  doc/news/changes/minor/20240925Munch
  include/deal.II/base/mpi_noncontiguous_partitioner.h
  include/deal.II/base/mpi_noncontiguous_partitioner.templates.h
  source/base/mpi_noncontiguous_partitioner.inst.in
  tests/base/mpi_noncontiguous_partitioner_05.cc
  tests/base/mpi_noncontiguous_partitioner_05.mpirun=2.output
Labels: Parallel distributed, ready to test

#17743 Update documentation of some SolutionTransfer functions.
  include/deal.II/numerics/solution_transfer.h
Labels: Documentation

#17748 Increase performance of GridTools::get_vertex_connectivity_of_cells
  source/grid/grid_tools_topology.cc
Labels: Triangulation, ready to test

#17746 Update indent worker to ubuntu-24.04.
  .github/workflows/indent.yml
  include/deal.II/numerics/solution_transfer.h
  source/grid/tria.cc
Labels: ready to test

#17750 Use CMAKE_TRY_COMPILE_CONFIGURATION for MSVC
  cmake/modules/FindDEAL_II_MPI.cmake
  cmake/setup_compiler_flags.cmake
  cmake/setup_sanity_checks.cmake
Labels: Build system, Reviewed and ready to merge, ready to test

#17753 replaced void cast with [[maybe_unused]]
  include/deal.II/matrix_free/operators.h
  include/deal.II/matrix_free/tools.h
Labels: ready to test

#17751 TableHandler::set_scientific(): fix int
  doc/news/changes/minor/20241005Munch
  source/base/table_handler.cc
  tests/base/table_handler_10.cc
  tests/base/table_handler_10.output
Labels: ready to test

#17764 FEInterfaceValues: fix some warnings.
  include/deal.II/fe/fe_interface_values.h
Labels: Miscellaneous, ready to test

#17756 Simplify MGCoarseGridIterativeSolver
  include/deal.II/multigrid/mg_coarse.h
Labels: ready to test

#17747 SparsityTools::reorder_hierarchical: better documentation and implementation
  source/lac/sparsity_tools.cc
Labels: Linear Algebra, ready to test

#12663 Add MGCoarseGridApplyPreconditioner
  include/deal.II/multigrid/mg_coarse.h
  tests/multigrid/mg_coarse_01.cc
  tests/multigrid/mg_coarse_01.with_p4est=true.with_trilinos=true.mpirun=1.output
  tests/multigrid/mg_coarse_01.with_p4est=true.with_trilinos=true.mpirun=3.output
Labels: Multigrid, ready to test

#17433 Modularize MatrixFreeTools::compute_diagonal()
  include/deal.II/matrix_free/tools.h
  tests/matrix_free/compute_diagonal_11.cc
  tests/matrix_free/compute_diagonal_11.output
Labels: Matrix-free, ready to test

#17717 Add empty() function to deal.II/hp/collection.h and use it instead of size() == 0
  include/deal.II/hp/collection.h
  source/distributed/cell_weights.cc
  source/hp/fe_collection.cc
  source/hp/refinement.cc
Labels: ready to test

#17761 Error out for situations clearly not implemented.
  source/fe/fe_system.cc
Labels: ready to test

#17760 Add comments clarifying some numbers.
  source/fe/fe.cc
Labels: ready to test

#17769 Fix warning
  source/lac/sparsity_tools.cc
Labels: ready to test

#17765 Don't define _LIBCPP_ENABLE_ASSERTIONS for clang++-19 and later
  cmake/setup_compiler_flags_gnu.cmake
Labels: ready to test

#17763 check an invariant of class IndexSet
  tests/base/index_set_empty.cc
  tests/base/index_set_empty.output
Labels: ready to test

#17772 Fix type in SparsityPattern
  source/lac/sparsity_pattern.cc
Labels: ready to test

#17768 CMake: force a single configuration in "multiple generator" mode
  cmake/macros/check_compiler_setup/CMakeLists.txt
  cmake/setup_cached_variables.cmake
Labels: Build system, Reviewed and ready to merge, ready to test

#17754 FEFaceEvaluation: Enable access of exterior values on ghosted faces
  include/deal.II/matrix_free/dof_info.h
  include/deal.II/matrix_free/dof_info.templates.h
  include/deal.II/matrix_free/face_setup_internal.h
  include/deal.II/matrix_free/matrix_free.templates.h
  source/matrix_free/dof_info.cc
  tests/matrix_free/matrix_vector_faces_24.cc
  tests/matrix_free/matrix_vector_faces_24.with_p4est=true.mpirun=2.output
  tests/matrix_free/matrix_vector_faces_common.h
Labels: Matrix-free, ready to test

#17779 Add assert to `FE_Hermite`
  source/fe/fe_hermite.cc
Labels: ready to test

#17782 Introduce `LAPACKFullMatrix::get_state()`
  doc/news/changes/minor/20241015Munch-1
  include/deal.II/lac/lapack_full_matrix.h
  source/lac/lapack_full_matrix.cc
Labels: Linear Algebra, ready to test

#17781 Introduce `CellIDTranslator.translate_level()`
  include/deal.II/grid/cell_id_translator.h
Labels: ready to test

#17783 Improve an error message.
  source/grid/tria.cc
Labels: ready to test

#17784 fix flaky trilinos/solver_control_06
  tests/trilinos/solver_control_06.cc
  tests/trilinos/solver_control_06.with_p4est=true.mpirun=2.output
  tests/trilinos/solver_control_06.with_p4est=true.mpirun=2.output.3
Labels: Tests, ready to test

#17791 Improve the error messages one gets when an external dependency is not found.
  include/deal.II/base/exceptions.h
Labels: Documentation, ready to test

#17788 Modifications in ReadVector
  include/deal.II/lac/block_vector_base.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/lac/petsc_vector_base.h
  include/deal.II/lac/read_vector.h
  include/deal.II/lac/read_write_vector.h
  include/deal.II/lac/trilinos_epetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  include/deal.II/lac/trilinos_vector.h
  include/deal.II/lac/vector.h
  include/deal.II/lac/vector.templates.h
  include/deal.II/non_matching/fe_values.h
  include/deal.II/non_matching/quadrature_generator.h
  source/lac/petsc_vector_base.cc
  source/lac/trilinos_epetra_vector.cc
  source/lac/trilinos_vector.cc
  source/non_matching/fe_values.cc
  source/non_matching/fe_values.inst.in
  source/non_matching/quadrature_generator.cc
  source/non_matching/quadrature_generator.inst.in
Labels: Linear Algebra, ready to test

#17794 Add necessary EnableObserverPointer header to ReadVector
  include/deal.II/lac/read_vector.h
Labels: Reviewed and ready to merge, ready to test

#17796 Remove some includes
  include/deal.II/lac/block_vector_base.h
  include/deal.II/lac/petsc_vector_base.h
  include/deal.II/lac/read_write_vector.h
  include/deal.II/lac/trilinos_epetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_vector.h
  include/deal.II/lac/vector.h
Labels: ready to test

#17785 Fix cubic simplex constraints.
  doc/news/changes/minor/20241015DavidWells
  source/fe/fe_q_base.cc
  source/fe/fe_simplex_p.cc
  tests/simplex/mapping_01.cc
  tests/simplex/mapping_01.output
  tests/simplex/simplex_project_cg.cc
  tests/simplex/simplex_project_cg.output
Labels: Finite Element, ready to test, Simplices

#17789 Better document the EnableObserverPointer class.
  include/deal.II/base/enable_observer_pointer.h
Labels: ready to test

#17802 Simplify string handling.
  include/deal.II/base/hdf5.h
  include/deal.II/base/patterns.h
  include/deal.II/fe/fe_tools.templates.h
  include/deal.II/lac/read_write_vector.templates.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  include/deal.II/numerics/dof_output_operator.h
  source/base/convergence_table.cc
  source/base/enable_observer_pointer.cc
  source/base/hdf5.cc
  source/base/job_identifier.cc
  source/base/logstream.cc
  source/base/parsed_convergence_table.cc
  source/base/path_search.cc
  source/base/timer.cc
  source/differentiation/sd/symengine_tensor_operations.cc
  source/grid/grid_out.cc
  source/lac/trilinos_epetra_vector.cc
  source/lac/trilinos_solver.cc
Labels: ready to test

#17803 Simplify string handling in examples/.
  examples/step-13/step-13.cc
  examples/step-28/step-28.cc
  examples/step-35/step-35.cc
  examples/step-36/step-36.cc
  examples/step-42/step-42.cc
  examples/step-62/step-62.cc
  examples/step-71/step-71.cc
Labels: Tutorials, ready to test

#17787 doxygen runner: let upload-artifact deal with compression.
  .github/workflows/indent.yml
Labels: ready for review, Documentation, Infrastructure

#17805 FEPointEvaluation: Implement get_curl()
  include/deal.II/matrix_free/fe_point_evaluation.h
  tests/matrix_free/point_evaluation_35.cc
  tests/matrix_free/point_evaluation_35.output
Labels: Matrix-free, ready to test

#17814 Skip an assert for posix_memalign if size==0.
  source/base/utilities.cc
Labels: ready to test

#17801 Cleanup some github workflows.
  .github/workflows/indent.yml
  .github/workflows/linux.yml
  .github/workflows/osx.yml
  .github/workflows/tidy.yml
  .github/workflows/windows.yml
Labels: ready for review, Infrastructure

#17800 windows: let upload-artifact deal with archiving.
  .github/workflows/windows.yml
Labels: ready for review, Infrastructure, Windows

#17816 Make sure the tutorial text doesn't run into the table of contents.
  doc/doxygen/scripts/make_step.pl
Labels: Tutorials

#17817 Make table of contents of tutorials wider.
  doc/doxygen/scripts/make_step.pl
Labels: Tutorials

#17813 Call find_package(Kokkos) if PETSc is compiled with Kokkos support
  cmake/modules/FindDEAL_II_PETSC.cmake
Labels: ready to test

#17818 Fix terminology.
  include/deal.II/fe/fe_q.h
  include/deal.II/fe/fe_q_hierarchical.h
Labels: Documentation, Reviewed and ready to merge
