Repository dealii/dealii, pull requests merged in 2025-07, with the labels that each got.

#18608 step-19: update the output.
  examples/step-19/doc/results.dox
Labels: Documentation, Reviewed and ready to merge, Tutorials, ready to test

#18604 Use MappingCollection for hp variant of KellyErrorEstimator.
  doc/news/changes/incompatibilities/20250620Fehling
  include/deal.II/numerics/error_estimator.h
  include/deal.II/numerics/error_estimator.templates.h
  source/numerics/error_estimator.inst.in
  source/numerics/error_estimator_1d.cc
  source/numerics/error_estimator_1d.inst.in
  tests/hp/error_estimator_01.cc
  tests/hp/error_estimator_01.output
Labels: ready for review, Reviewed and ready to merge, hp adaptivity, ready to test

#18616 `parallel::distributed::Vector` with `MemorySpace::Default`: disallow complex instantiations
  include/deal.II/lac/la_parallel_vector.h
  source/lac/la_parallel_block_vector.inst.in
Labels: ready for review, Reviewed and ready to merge, ready to test

#18618 Do not use deprecated p::d::SolutionTransfer in examples and tests.
  examples/step-32/step-32.cc
  examples/step-42/step-42.cc
  examples/step-48/step-48.cc
  examples/step-70/step-70.cc
  examples/step-86/step-86.cc
  tests/distributed_grids/checkpointing_02.cc
  tests/distributed_grids/checkpointing_03.cc
  tests/distributed_grids/solution_transfer_01.cc
  tests/distributed_grids/solution_transfer_02.cc
  tests/distributed_grids/solution_transfer_03.cc
  tests/distributed_grids/solution_transfer_04.cc
  tests/fullydistributed_grids/solution_transfer_01.cc
  tests/mpi/p4est_2d_constraintmatrix_04.cc
  tests/mpi/p4est_3d_constraintmatrix_03.cc
  tests/mpi/p4est_save_02.cc
  tests/mpi/p4est_save_03.cc
  tests/mpi/p4est_save_04.cc
  tests/mpi/p4est_save_06.cc
  tests/mpi/solution_transfer_01.cc
  tests/mpi/solution_transfer_04.cc
  tests/mpi/solution_transfer_06.cc
  tests/non_matching/step-70.cc
  tests/petsc/step-77-snes.cc
Labels: Reviewed and ready to merge, ready to test

#18623 Fix two warnings about use of deprecated interfaces
  examples/step-47/step-47.cc
  examples/step-90/step-90.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#18624 Add doxygen deprecation tag to already `DEAL_II_DEPRECATED_EARLY` function.
  include/deal.II/fe/fe_interface_values.h
Labels: Documentation

#18625 Remove remaining occurences of p::d::SolutionTransfer in examples and tests.
  examples/step-68/step-68.cc
  examples/step-69/step-69.cc
  tests/distributed_grids/large_vtu_01.cc
  tests/distributed_grids/solution_transfer_05.cc
  tests/mpi/interpolate_to_different_mesh_02.cc
  tests/mpi/p4est_save_01.cc
  tests/mpi/solution_transfer_05.cc
  tests/mpi/solution_transfer_11.cc
  tests/particles/step-68.cc
  tests/performance/timing_step_68.cc
  tests/simplex/step-68.cc
Labels: ready to test

#18629 Use absolute paths to link to figures.
  examples/step-97/doc/intro.dox
  examples/step-97/doc/results.dox
Labels: ready to test

#18617 CMake: do not export -Wno-deprecated-declarations
  cmake/config/CMakeLists.txt
Labels: Build system, Reviewed and ready to merge, ready to test

#18413 Renumber lexicographic
  doc/news/changes/minor/20250502Wichrowski
  doc/news/changes/minor/20250701Wichrowski
  include/deal.II/dofs/dof_renumbering.h
  include/deal.II/fe/fe_tools.h
  include/deal.II/fe/fe_tools.templates.h
  source/dofs/dof_renumbering.cc
  source/dofs/dof_renumbering.inst.in
  source/fe/fe_tools.inst.in
  tests/dofs/dof_renumbering_11.cc
  tests/dofs/dof_renumbering_11.output
  tests/fe/cell_face_lex.cc
  tests/fe/cell_face_lex.output
Labels: DoFs, ready to test

#18637 Fix step-30.
  examples/step-30/step-30.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#18639 Replace `-numeric_limits::max()` by `numeric_limits::lowest()`
  cmake/checks/check_01_cxx_features.cmake
  examples/step-31/step-31.cc
  examples/step-32/step-32.cc
  examples/step-36/step-36.cc
  examples/step-42/step-42.cc
  examples/step-43/step-43.cc
Labels: Reviewed and ready to merge, ready to test

#18645 ArborX: fix compilation with versions < 2
  include/deal.II/arborx/access_traits.h
Labels: Bug, High Priority :warning:, ready to test

#18643 try to hide trilinos 16 warnings
  include/deal.II/base/config.h.in
  include/deal.II/base/index_set.h
  include/deal.II/base/trilinos_utilities.h
  include/deal.II/lac/read_write_vector.h
  include/deal.II/lac/read_write_vector.templates.h
  include/deal.II/lac/trilinos_epetra_communication_pattern.h
  include/deal.II/lac/trilinos_epetra_vector.h
  include/deal.II/lac/trilinos_index_access.h
  include/deal.II/lac/trilinos_precondition.h
  include/deal.II/lac/trilinos_solver.h
  include/deal.II/lac/trilinos_sparse_matrix.h
  include/deal.II/lac/trilinos_sparsity_pattern.h
  include/deal.II/lac/trilinos_vector.h
  source/base/index_set.cc
  source/base/init_finalize.cc
  source/base/trilinos_utilities.cc
  source/lac/trilinos_epetra_communication_pattern.cc
  source/lac/trilinos_precondition.cc
  source/lac/trilinos_precondition_ml.cc
  source/lac/trilinos_solver.cc
  source/lac/trilinos_sparse_matrix.cc
  source/lac/trilinos_sparsity_pattern.cc
  source/lac/trilinos_vector.cc
Labels: Reviewed and ready to merge, ready to test

#18647 CMake: only configure ArborX 2.0 onwards when C++20 is available
  cmake/configure/configure_50_arborx.cmake
Labels: Build system, ready to test

#18648 Update step-70 output
  examples/step-70/doc/results.dox
  examples/step-70/parameters.prm
  tests/examples/step-70.with_trilinos=true.with_p4est=true.mpirun=1.output
Labels: Tutorials, ready to test

#18651 Fix step-79 crash
  examples/step-79/step-79.cc
Labels: Reviewed and ready to merge, ready to test

#18653 Update output of step-81
  examples/step-81/doc/results.dox
Labels: Reviewed and ready to merge, ready to test

#18652 Update step-76 result documentation
  examples/step-76/doc/results.dox
Labels: Tutorials

#18661 Fix interpolation component in step-93
  examples/step-93/doc/intro.dox
  examples/step-93/step-93.cc
Labels: Reviewed and ready to merge, Tutorials, ready to test

#18655 Fix two bugs in step-86
  examples/step-86/step-86.cc
Labels: Reviewed and ready to merge, Tutorials, Parallel distributed, ready to test

#18665 Fix some issues with example tests.
  tests/examples/CMakeLists.txt.in
Labels: Infrastructure, Tutorials, Tests

#18666 silence another Trilinos 16 deprecation warning
  include/deal.II/lac/trilinos_tpetra_solver_direct.h
Labels: Reviewed and ready to merge, ready to test

#18669 Replace deprecated std::shared_ptr<T>::unique
  include/deal.II/base/quadrature_point_data.h
Labels: ready to test

#18673 Step 93: remove unused variables
  examples/step-93/step-93.cc
Labels: Reviewed and ready to merge, ready to test

#18487 Decide whether we want to build C++20 modules.
  cmake/config/Config.cmake.in
  cmake/setup_cached_variables.cmake
  cmake/setup_write_config.cmake
Labels: ready to test

#18679 Add missing anchors.
  examples/step-60/doc/intro.dox
  examples/step-62/doc/intro.dox
  examples/step-64/doc/intro.dox
  examples/step-68/doc/intro.dox
  examples/step-70/doc/intro.dox
  examples/step-71/doc/intro.dox
  examples/step-72/doc/intro.dox
  examples/step-87/doc/intro.dox
  examples/step-89/doc/intro.dox
  examples/step-97/doc/intro.dox
Labels: Documentation, Tutorials, ready to test

#18682 intel compiler: suppress warning
  cmake/setup_compiler_flags_intel.cmake
Labels: ready to test

#18683 [9.7] cherry-pick #18682
  cmake/setup_compiler_flags_intel.cmake
Labels: ready to test

#18690 Fix a regular expression.
  doc/doxygen/scripts/make_gallery.pl
Labels: Documentation

#18622 Adapted FE_RT_Bubbles and polynomialsRT_Bubbles to PolynomialsVectorAnisotropic
  include/deal.II/base/polynomials_rt_bubbles.h
  source/base/polynomials_rt_bubbles.cc
  tests/base/polynomials_rt_bubbles.cc
Labels: Finite Element, ready to test

#18694 std.ccm: fix a preprocessor directive, prefer #ifdef when possible
  module/interface_module_partitions/std.ccm
Labels: Reviewed and ready to merge, ready to test, cherry-pick candidate

#18695 Silence a maybe-uninitialized warning.
  source/grid/manifold.cc
Labels: Reviewed and ready to merge, ready to test, cherry-pick candidate

#18688 `MappingFEField`: store which DoFs are nonzero in each component.
  doc/news/changes/minor/20250714Wells
  include/deal.II/fe/mapping_fe_field.h
  include/deal.II/fe/mapping_fe_field.templates.h
Labels: Mapping, ready to test

#18672 Kokkos with device support: require 3.7
  cmake/configure/configure_30_kokkos.cmake
  doc/readme.html
Labels: Build system, ready to test

#18697 std.ccm: fix a preprocessor directive
  module/interface_module_partitions/std.ccm
Labels: Reviewed and ready to merge, ready to test, cherry-pick candidate

#18650 Provide general description of constraint handling in matrix-free module
  doc/doxygen/headers/matrixfree.h
Labels: Documentation, Tutorials

#18699 Avoid the use of sprintf.
  include/deal.II/lac/vector.templates.h
  module/interface_module_partitions/std.ccm
Labels: ready to test

#18705 Revert "Remove the inclusion of Kokkos_Macros.h from config.h."
  include/deal.II/base/config.h.in
  include/deal.II/base/numbers.h
Labels: ready to test, cherry-pick candidate

#18530 Kokkos: test that exception macros work on device
  include/deal.II/base/exception_macros.h
  include/deal.II/base/exceptions.h
  tests/matrix_free_kokkos/basics_01.cc
  tests/matrix_free_kokkos/basics_01.output
Labels: GPU, ready to test

#18703 Wrap a few more symbols.
  module/interface_module_partitions/boost.ccm
  module/interface_module_partitions/std.ccm
  module/interface_module_partitions/zlib.ccm
Labels: ready to test, cherry-pick candidate

#18658 Use `std::clamp` instead of the `std::min/std::max` pattern
  source/lac/sparsity_pattern.cc
Labels: Reviewed and ready to merge, ready to test

#18702 Replace DEAL_II_DEPRECATED_EARLY with DEAL_II_DEPRECATED
  include/deal.II/base/enable_observer_pointer.h
  include/deal.II/base/index_set.h
  include/deal.II/base/mpi_consensus_algorithms.h
  include/deal.II/base/observer_pointer.h
  include/deal.II/base/parallel.h
  include/deal.II/base/qprojector.h
  include/deal.II/base/std_cxx17/algorithm.h
  include/deal.II/base/std_cxx17/optional.h
  include/deal.II/base/std_cxx17/tuple.h
  include/deal.II/base/std_cxx17/variant.h
  include/deal.II/base/types.h
  include/deal.II/distributed/solution_transfer.h
  include/deal.II/dofs/dof_handler.h
  include/deal.II/dofs/dof_tools.h
  include/deal.II/fe/fe_interface_values.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria.h
  include/deal.II/grid/tria_accessor.templates.h
  include/deal.II/grid/tria_iterator.templates.h
  include/deal.II/numerics/error_estimator.h
  include/deal.II/numerics/solution_transfer.h
Labels: ready to test

#18704 Also include revision.h into macros.h.
  module/CMakeLists.txt
Labels: ready to test, cherry-pick candidate

#18707 [9.7] Take over #18701
  tests/sundials/arkode_01.output.sundials73
  tests/sundials/arkode_02.output.sundials73
  tests/sundials/arkode_04.output.sundials73
  tests/sundials/arkode_08.output.sundials73
  tests/sundials/arkode_09.output.sundials73
  tests/sundials/arkode_10.output.sundials73
Labels: Reviewed and ready to merge, ready to test

#18710 Symengine: avoid anonymous namespace
  include/deal.II/base/symbolic_function.templates.h
Labels: Reviewed and ready to merge, ready to test, cherry-picked to release branch

#18717 Export SUNComm and SUN_COMM_NULL.
  module/interface_module_partitions/sundials.ccm
Labels: ready to test, cherry-pick candidate

#18726 Let doxygen see MUMPS-related documentation
  doc/doxygen/options.dox.in
Labels: cherry-pick candidate

#18714 Fix for broken internal links in the tutorials.
  examples/step-10/doc/results.dox
  examples/step-15/doc/intro.dox
  examples/step-15/doc/results.dox
  examples/step-18/doc/intro.dox
  examples/step-18/doc/results.dox
  examples/step-19/doc/intro.dox
  examples/step-19/doc/results.dox
  examples/step-19/step-19.cc
  examples/step-2/doc/intro.dox
  examples/step-20/doc/intro.dox
  examples/step-20/doc/results.dox
  examples/step-21/doc/intro.dox
  examples/step-21/doc/results.dox
  examples/step-22/doc/intro.dox
  examples/step-22/doc/results.dox
  examples/step-22/step-22.cc
  examples/step-23/doc/intro.dox
  examples/step-26/doc/intro.dox
  examples/step-29/doc/results.dox
  examples/step-29/step-29.cc
  examples/step-3/doc/results.dox
  examples/step-31/doc/intro.dox
  examples/step-32/doc/intro.dox
  examples/step-33/doc/intro.dox
  examples/step-4/doc/results.dox
  examples/step-43/doc/intro.dox
  examples/step-46/doc/intro.dox
  examples/step-49/doc/intro.dox
  examples/step-49/step-49.cc
  examples/step-58/doc/intro.dox
  examples/step-58/doc/results.dox
  examples/step-67/doc/intro.dox
  examples/step-69/step-69.cc
  examples/step-72/doc/intro.dox
  examples/step-77/doc/intro.dox
Labels: Reviewed and ready to merge, ready to test, cherry-pick candidate

#18728 test step-93: use check_solver_within_range
  tests/examples/step-93.diff
  tests/examples/step-93.output
Labels: Reviewed and ready to merge, Tutorials, Tests, ready to test, cherry-pick candidate

#18709 Remove deprecated code from the 9.6 release
  doc/doxygen/headers/io.h
  doc/news/changes/incompatibilities/20250717Arndt
  examples/step-62/step-62.cc
  include/deal.II/base/index_set.h
  include/deal.II/base/path_search.h
  include/deal.II/base/template_constraints.h
  include/deal.II/dofs/dof_handler.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/petsc_solver.h
  include/deal.II/lac/read_write_vector.h
  include/deal.II/lac/trilinos_epetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  include/deal.II/lac/trilinos_vector.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/numerics/nonlinear.h
  source/base/CMakeLists.txt
  source/base/index_set.cc
  source/base/parameter_acceptor.cc
  source/base/parameter_handler.cc
  source/base/path_search.cc
  source/base/patterns.cc
  source/dofs/dof_handler.cc
  source/grid/grid_tools.cc
  source/grid/grid_tools.inst.in
  source/lac/petsc_solver.cc
  tests/bits/distorted_cells_06.cc
  tests/grid/grid_hyper_shell.cc
  tests/grid/grid_hyper_shell.output.2
  tests/grid/grid_hyper_shell.output.with_fma
  tests/matrix_free/fe_evaluation_access_1d.cc
  tests/matrix_free_kokkos/matrix_vector_host_device_multi_component.cc
  tests/mpi/petsc_step-27.cc
  tests/mpi/step-40_direct_solver.cc
  tests/numerics/nonlinear_solver_selector_03.cc
  tests/parameter_handler/parameter_acceptor_04.cc
  tests/parameter_handler/parameter_acceptor_05.cc
  tests/parameter_handler/parameter_acceptor_06.cc
  tests/parameter_handler/parameter_acceptor_07.cc
  tests/parameter_handler/parameter_acceptor_08.cc
  tests/parameter_handler/parameter_acceptor_10.cc
  tests/petsc/petsc_snes_08.cc
  tests/simplex/step-40.cc
Labels: Reviewed and ready to merge, ready to test

#18731 CMake: Module support: refactor installation logic and paths
  cmake/config/CMakeLists.txt
  include/CMakeLists.txt
  module/CMakeLists.txt
  source/CMakeLists.txt
Labels: Reviewed and ready to merge, ready to test, cherry-picked to release branch

#18734 Fix muparser.ccm for bundled muparser
  module/interface_module_partitions/muparser.ccm
Labels: Reviewed and ready to merge, ready to test, cherry-pick candidate

#18732 Reduce includes in std.ccm
  module/interface_module_partitions/std.ccm
Labels: ready to test, cherry-pick candidate

#18534 SymmetricTensor: avoid ndarray for device support
  include/deal.II/base/symmetric_tensor.h
Labels: GPU, ready to test

#18719 Kokkos: implement NumberTraits::abs() on device
  include/deal.II/base/numbers.h
  tests/matrix_free_kokkos/basics_02.cc
  tests/matrix_free_kokkos/basics_02.output
Labels: Reviewed and ready to merge, GPU, ready to test

#18434 Add utility to detect unwanted merges in feature
  .pre-commit-config.yaml
  contrib/utilities/detect_merges_from_master_in_feature_branch.sh
Labels: Infrastructure, ready to test

#18747 std.ccm: add missing include
  module/interface_module_partitions/std.ccm
Labels: Reviewed and ready to merge, ready to test, cherry-picked to release branch

#18745 CMake: Module support: do not link in internal object targets
  module/CMakeLists.txt
Labels: cherry-picked to release branch

#18742 GitHub CI: Add build with C++20 modules
  .github/workflows/linux.yml
Labels: Infrastructure, Reviewed and ready to merge, C++20

#18748 Let our scripts provide proper links to step-xx tutorials.
  examples/step-21/doc/intro.dox
  examples/step-21/doc/results.dox
  examples/step-22/doc/intro.dox
  examples/step-23/doc/intro.dox
  examples/step-24/doc/intro.dox
  examples/step-25/doc/intro.dox
  examples/step-25/doc/results.dox
  examples/step-31/doc/intro.dox
  examples/step-36/doc/intro.dox
  examples/step-36/doc/results.dox
  examples/step-8/doc/intro.dox
  include/deal.II/dofs/dof_tools.h
  include/deal.II/fe/fe.h
  include/deal.II/fe/fe_tools.h
  include/deal.II/grid/tria_accessor.h
  include/deal.II/lac/arpack_solver.h
  include/deal.II/lac/sparse_ilu.h
  include/deal.II/numerics/data_out_dof_data.h
  include/deal.II/numerics/vector_tools_mean_value.h
  include/deal.II/numerics/vector_tools_point_value.h
Labels: Documentation

#18486 Kokkos: support and test SymmetricTensor
  cmake/modules/FindDEAL_II_KOKKOS.cmake
  include/deal.II/base/symmetric_tensor.h
  module/interface_module_partitions/kokkos.ccm
  source/base/symmetric_tensor.inst.in
  tests/matrix_free_kokkos/tensor_01.cc
Labels: Reviewed and ready to merge, GPU, ready to test

#18756 Add test for identification of faces in matrix-free framework
  include/deal.II/matrix_free/face_setup_internal.h
  tests/matrix_free/dg_pbc_03.cc
  tests/matrix_free/dg_pbc_03.output
Labels: Matrix-free, Tests, ready to test

#18758 gh-actions: build deal.II on windows with c++20.
  .github/workflows/windows.yml
Labels: Windows, C++20

#18762 (dealii-9.7) MSVC c++20 compatibility - DoFInvalidAccessor template instantiations
  source/dofs/dof_accessor.inst.in
Labels: Reviewed and ready to merge, ready to test

#18764 Remove the CUDA module.
  cmake/modules/FindDEAL_II_CUDA.cmake
Labels: Build system, ready to test

#18763 Matrix-free face setup in 1d: allow neighbors to differ by more than 1 level
  include/deal.II/matrix_free/face_setup_internal.h
  tests/matrix_free/dg_pbc_03.cc
  tests/matrix_free/dg_pbc_03.output
Labels: Matrix-free, ready to test, cherry-pick candidate

#18766 MappingP1: add default constructor
  include/deal.II/fe/mapping_p1.h
Labels: Reviewed and ready to merge, ready to test, cherry-pick candidate

#18765 Some smaller updates to the 9.7 changelog.
  doc/news/9.6.0-vs-9.7.0.h
Labels: Documentation

#18418 Implementation of Portable::FEEvaluation::get/submit_symmetric_gradient
  include/deal.II/matrix_free/portable_fe_evaluation.h
  tests/matrix_free_kokkos/assemble_matrix_01.cc
  tests/matrix_free_kokkos/assemble_matrix_01.output
Labels: ready to test

#18772 fix nvcc work-around in petsc_matrix_base.h
  include/deal.II/lac/petsc_matrix_base.h
Labels: Bug, GPU, ready to test
