Repository dealii/dealii, pull requests merged in 2025-02, with the labels that each got.

#18064 CMake: Move some code from source/ to cmake/config/.
  CMakeLists.txt
  cmake/config/CMakeLists.txt
  source/CMakeLists.txt
Labels: Build system, Reviewed and ready to merge, ready to test

#18067 Normalize the way we include header files.
  include/deal.II/lac/trilinos_tpetra_communication_pattern.h
  include/deal.II/lac/trilinos_tpetra_precondition.h
  include/deal.II/lac/trilinos_tpetra_precondition.templates.h
  include/deal.II/lac/trilinos_tpetra_solver_direct.h
  include/deal.II/lac/trilinos_tpetra_solver_direct.templates.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
  include/deal.II/lac/trilinos_tpetra_sparsity_pattern.h
  include/deal.II/lac/trilinos_tpetra_types.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/non_matching/mapping_info.h
Labels: ready to test

#18073 Fix "declaration of '' hides class member" warning
  include/deal.II/lac/sparsity_pattern_base.h
Labels: Reviewed and ready to merge, ready to test

#18070 Don't call deprecated QProjector functions.
  source/fe/fe_poly.cc
  source/fe/mapping_q.cc
Labels: Triangulation, ready to test, Simplices

#18069 Get rid of another call to `face_orientation()`.
  include/deal.II/grid/reference_cell.h
  source/grid/tria_accessor.cc
Labels: Triangulation, ready to test, Simplices

#18082 Do not include unnecessary header file.
  include/deal.II/lac/petsc_solver.h
Labels: Reviewed and ready to merge, ready to test

#18079 Normalize the way we write header includes.
  include/deal.II/lac/schur_complement.h
Labels: Documentation, Reviewed and ready to merge

#18078 Don't use .inst files where not necessary.
  source/base/polynomials_bernstein.cc
  source/base/polynomials_bernstein.inst
Labels: ready to test

#18075 Remove #includes from config.h.
  doc/news/changes/incompatibilities/20250203Bangerth
  include/deal.II/base/complex_overloads.h
  include/deal.II/base/config.h.in
  include/deal.II/base/discrete_time.h
  include/deal.II/base/exceptions.h
  include/deal.II/base/memory_consumption.h
Labels: ready to test

#18083 Remove a cycle in header files.
  include/deal.II/lac/la_parallel_block_vector.h
  source/lac/la_parallel_block_vector.cc
Labels: Reviewed and ready to merge, ready to test

#18090 Mark our various constants as 'constexpr'.
  include/deal.II/base/types.h
Labels: ready to test

#18086 Detect header cycles regardless of how we spell the #include.
  contrib/utilities/detect_include_cycles.py
Labels: ready to test

#18093 Make scripts executable.
  contrib/utilities/detect_include_cycles.py
  contrib/utilities/double_word_typos.py
  contrib/utilities/indent.py
  contrib/utilities/indent_common.sh
  contrib/utilities/parse_ctest_output.py
Labels: Miscellaneous

#18076 CMake: rearrange source/CMakeLists.txt
  source/CMakeLists.txt
Labels: Reviewed and ready to merge, ready to test

#18088 Add checks that src is not equal to dst in mmult().
  include/deal.II/lac/full_matrix.templates.h
  tests/lac/full_matrix_mmult_01.cc
  tests/lac/full_matrix_mmult_01.expect=run.debug.output
Labels: Linear Algebra, ready to test

#18097 Print the exception string in a test.
  tests/lac/full_matrix_mmult_01.cc
  tests/lac/full_matrix_mmult_01.debug.output
  tests/lac/full_matrix_mmult_01.expect=run.debug.output
Labels: Tests, ready to test

#18095 Fix compiler error when using nvcc with C++20
  include/deal.II/algorithms/theta_timestepping.templates.h
  include/deal.II/base/tensor.h
  include/deal.II/grid/reference_cell.h
  source/fe/fe_system.cc
  source/fe/mapping_q_cache.cc
Labels: ready to test

#18100 Remove an unnecessary include path.
  source/trilinos/CMakeLists.txt
Labels: Build system, Reviewed and ready to merge, ready to test

#18102 Minor update to config.h.
  include/deal.II/base/config.h.in
Labels: ready to test

#18101 Exclude more files from compiling if they are functionally empty.
  source/base/CMakeLists.txt
  source/gmsh/CMakeLists.txt
  source/gmsh/utilities.cc
Labels: Build system, Reviewed and ready to merge, ready to test

#18104 Do not use 'static const' variables in header files. Use 'constexpr' instead.
  include/deal.II/lac/lapack_support.h
Labels: Reviewed and ready to merge, ready to test

#18106 Use the zorder partitioner in the step-18 test.
  tests/examples/step-18.diff
  tests/examples/step-18.mpirun=2.with_petsc=true.output
  tests/examples/step-18.mpirun=2.with_petsc=true.output2
Labels: Tutorials, Tests, ready to test

#18108 Use proper types (rather than #defines) in mpi_stub.h.
  include/deal.II/base/mpi_stub.h
Labels: ready to test

#18109 No need to say the same thing three times.
  include/deal.II/base/polynomials_wedge.h
Labels: ready to test

#18105 Combine some functions in `QProjector`.
  include/deal.II/base/qprojector.h
  include/deal.II/fe/fe_tools.templates.h
  include/deal.II/non_matching/mapping_info.h
  include/deal.II/numerics/vector_tools_boundary.templates.h
  source/base/qprojector.cc
  source/fe/fe_abf.cc
  source/fe/fe_bernstein.cc
  source/fe/fe_p1nc.cc
  source/fe/fe_q_base.cc
  source/fe/fe_raviart_thomas.cc
  source/fe/fe_raviart_thomas_nodal.cc
  source/fe/fe_simplex_p.cc
  tests/fe/fe_support_points_common.h
Labels: Triangulation, ready to test

#18110 Add necessary header includes.
  include/deal.II/boost_adaptors/point.h
Labels: ready to test

#18107 Reorder includes and declarations in a file.
  include/deal.II/differentiation/ad/adolc_number_types.h
Labels: ready to test

#18112 Fix compiling without TBB and Taskflow
  include/deal.II/base/parallel.h
Labels: Reviewed and ready to merge, ready to test

#18113 Fix grid_tools.cc without MPI and ArborX.
  source/grid/grid_tools.cc
Labels: ready to test

#18115 We cannot have 'static' functions in header files.
  include/deal.II/lac/affine_constraints.templates.h
Labels: ready to test

#18116 Do not use anonymous namespaces in header files.
  include/deal.II/base/mpi_consensus_algorithms.h
Labels: ready to test

#18114 Put the declarations in mpi_stub.h into namespace dealii.
  include/deal.II/base/mpi_stub.h
Labels: ready to test

#18121 Only overload complex-valued operators if T!=U.
  include/deal.II/base/complex_overloads.h
Labels: ready to test

#18122 Combine several specializations into a single template.
  include/deal.II/grid/tria_accessor.h
Labels: ready to test

#18123 Do not use anonymous namespaces in header files.
  include/deal.II/sundials/n_vector.templates.h
Labels: Parallel distributed, ready to test

#18120 Remove DEAL_II_INCLUDE_DIRS
  cmake/setup_sanity_checks.cmake
  doc/developers/cmake-internals.html
  doc/users/cmake_user.html
Labels: ready to test

#18119 Fix more headers for the all-headers test.
  include/deal.II/lac/trilinos_tpetra_precondition.h
  include/deal.II/numerics/nonlinear.h
Labels: ready to test

#18129 Include tria_accessor.h at the top of tria.h
  include/deal.II/grid/tria.h
Labels: ready to test

#18128 Only open/close namespace dealii once.
  source/meshworker/scratch_data.cc
Labels: ready to test

#18127 Move an #include outside namespace dealii.
  source/lac/sparse_direct.cc
Labels: ready to test

#18135 Fix includes for numerics/nonlinear.h
  include/deal.II/numerics/nonlinear.h
Labels: Reviewed and ready to merge, ready to test

#18138 Fix output for trilinos/direct_solver_4
  tests/trilinos/direct_solver_4.output
Labels: Reviewed and ready to merge, ready to test

#18133 do not use gold linker by default
  cmake/checks/check_02_compiler_features.cmake
  cmake/setup_sanity_checks.cmake
Labels: ready to test

#18134 Be more precise with what we #include, part 4: Include ADOLC headers where necessary.
  include/deal.II/differentiation/ad/ad_drivers.h
  source/base/symmetric_tensor.cc
  source/differentiation/ad/adolc_number_types.cc
  source/fe/fe_values_views.cc
  source/fe/fe_values_views_internal.cc
Labels: ready to test

#18141 Exclude CGAL source files when not compiling with CGAL.
  source/cgal/CMakeLists.txt
  source/cgal/intersections.cc
  source/cgal/surface_mesh.cc
Labels: ready to test

#18143 Fix the frequently-failing trilinos/solver_control_06 test.
  tests/trilinos/solver_control_06.cc
  tests/trilinos/solver_control_06.with_p4est=true.mpirun=1.output
  tests/trilinos/solver_control_06.with_p4est=true.mpirun=1.output.2
  tests/trilinos/solver_control_06.with_p4est=true.mpirun=1.output.3
  tests/trilinos/solver_control_06.with_p4est=true.mpirun=2.output
  tests/trilinos/solver_control_06.with_p4est=true.mpirun=2.output.2
  tests/trilinos/solver_control_06.with_p4est=true.mpirun=2.output.3
Labels: Reviewed and ready to merge, Tests, ready to test

#18140 Combine some more functions in `QProjector`.
  include/deal.II/base/qprojector.h
  include/deal.II/fe/fe_tools.templates.h
  source/base/qprojector.cc
  source/fe/fe_abf.cc
  source/fe/fe_bernstein.cc
  source/fe/fe_p1nc.cc
  source/fe/fe_q_base.cc
  source/fe/fe_raviart_thomas.cc
  source/fe/fe_raviart_thomas_nodal.cc
  source/fe/fe_simplex_p.cc
Labels: Triangulation, ready to test

#18146 Simplify code.
  source/distributed/cell_weights.cc
Labels: ready to test

#18147 Fix a preprocessor #define.
  include/deal.II/base/config.h.in
Labels: ready to test

#18149 Remove empty semicolon in a few of our files
  include/deal.II/matrix_free/fe_point_evaluation.h
  include/deal.II/matrix_free/tensor_product_kernels.h
  tests/ad_common_tests/helper_scalar_coupled_2_components_03.h
  tests/arpack/parpack_advection_diffusion_petsc.cc
  tests/arpack/step-36_parpack.cc
  tests/base/simplex.h
  tests/bits/step-12.cc
  tests/codim_one/mapping_fe_field_01.cc
  tests/dofs/block_list_04.cc
  tests/fe/fe_tools_block_renumbering.cc
  tests/grid/filtered_iterator_04.cc
  tests/grid/filtered_iterator_04_operator.cc
  tests/hp/step-12.cc
  tests/lac/block_linear_operator_04.cc
  tests/lac/gmres_eigenvalues_02.cc
  tests/manifold/spherical_manifold_01.cc
  tests/mpi/petsc_bug_ghost_vector_01.cc
  tests/simplex/step-12b.cc
  tests/symengine/symengine_scalar_operations_04.cc
  tests/trilinos_tpetra/vector_reference_01.cc
Labels: Miscellaneous, ready to test

#18150 Use explicit constructor for iota_view.
  include/deal.II/base/geometry_info.h
  include/deal.II/fe/fe_interface_values.h
  include/deal.II/fe/fe_values_base.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/fe_evaluation_data.h
  include/deal.II/matrix_free/fe_point_evaluation.h
  source/base/mpi_remote_point_evaluation.cc
Labels: ready to test

#18136 Break exception macros into a file of their own.
  include/deal.II/base/exception_macros.h
  include/deal.II/base/exceptions.h
  include/deal.II/sundials/arkode.h
  include/deal.II/sundials/ida.h
  include/deal.II/sundials/kinsol.h
Labels: ready to test

#18125 github: Use ubuntu-24.04 instead of ubuntu-latest. Move pre-commit check to indent.yml file.
  .github/workflows/docker.yml
  .github/workflows/indent.yml
  .github/workflows/pre-commit.yml
  .github/workflows/tidy.yml
Labels: Infrastructure, ready to test

#18153 Err on the safe side.
  source/grid/tria.cc
Labels: Triangulation, ready to test

#18154 Use explicit constructor for iota_view.
  include/deal.II/fe/fe_coupling_values.h
Labels: ready to test

#18157 Some code clean-ups.
  source/fe/mapping_q.cc
  source/grid/tria_accessor.cc
Labels: ready to test

#18160 Add missing #include.
  source/dofs/dof_accessor_set.cc
Labels: ready to test

#18163 Remove what I think are unnecessary includes.
  source/base/utilities.cc
Labels: ready to test

#18162 Avoid explicit specializations.
  source/base/tensor_product_polynomials.cc
  source/base/tensor_product_polynomials_bubbles.cc
  source/base/tensor_product_polynomials_const.cc
Labels: ready to test

#18164 Add another missing #include.
  source/base/table_handler.cc
Labels: Miscellaneous, ready to test

#18161 Fix a missing #include.
  include/deal.II/lac/full_matrix.templates.h
Labels: Miscellaneous, ready to test

#18165 Simplify manifold use in matrix-free tests
  tests/matrix_free/assemble_matrix_01.cc
  tests/matrix_free/assemble_matrix_02.cc
  tests/matrix_free/assemble_matrix_03.cc
  tests/matrix_free/copy_feevaluation.cc
  tests/matrix_free/get_functions_circle.cc
  tests/matrix_free/get_functions_gl.cc
  tests/matrix_free/get_functions_mappingq.cc
  tests/matrix_free/get_functions_notempl.cc
  tests/matrix_free/get_functions_q_hierarchical.cc
  tests/matrix_free/get_functions_rect.cc
  tests/matrix_free/get_values_plain.cc
  tests/matrix_free/integrate_functions.cc
  tests/matrix_free/integrate_functions_hessians.cc
  tests/matrix_free/integrate_functions_multife.cc
  tests/matrix_free/inverse_mass_01.cc
  tests/matrix_free/inverse_mass_03.cc
  tests/matrix_free/inverse_mass_05.cc
  tests/matrix_free/inverse_mass_06.cc
  tests/matrix_free/inverse_mass_08.cc
  tests/matrix_free/matrix_vector_04.cc
  tests/matrix_free/matrix_vector_04b.cc
  tests/matrix_free/matrix_vector_07.cc
  tests/matrix_free/matrix_vector_14.cc
  tests/matrix_free/matrix_vector_14_notempl.cc
  tests/matrix_free/matrix_vector_14b.cc
  tests/matrix_free/matrix_vector_15.cc
  tests/matrix_free/matrix_vector_16.cc
  tests/matrix_free/matrix_vector_17.cc
  tests/matrix_free/matrix_vector_curl.cc
  tests/matrix_free/matrix_vector_hp.cc
  tests/matrix_free/matrix_vector_hp_no_template.cc
  tests/matrix_free/matrix_vector_hp_parallel_01.cc
  tests/matrix_free/matrix_vector_mg.cc
  tests/matrix_free/matrix_vector_stokes_noflux.cc
  tests/matrix_free/matrix_vector_stokes_notempl.cc
  tests/matrix_free/matrix_vector_stokes_onedof.cc
  tests/matrix_free/no_index_initialize.cc
  tests/matrix_free/quadrature_points.cc
Labels: Reviewed and ready to merge, Matrix-free, Tests, ready to test

#18148 Add new matrix-free test for different quadrature formulas
  tests/matrix_free/integrate_functions_multife3.cc
  tests/matrix_free/integrate_functions_multife3.output
Labels: Matrix-free, Tests, ready to test

#18169 Tutorial: List step-76 as Euler problem
  doc/doxygen/tutorial/tutorial.h.in
Labels: Documentation, Tutorials

#18167 github: Added matrix strategy for OS versions in MacOS jobs.
  .github/workflows/osx.yml
Labels: Infrastructure

#18166 github: Include OS version in Windows job name.
  .github/workflows/windows.yml
Labels: Infrastructure

#18170 Avoid using namespace directives.
  source/base/utilities.cc
Labels: ready to test

#18152 Fix documentation for analytical solution in step-34
  doc/doxygen/references.bib
  examples/step-34/doc/intro.dox
Labels: ready for review, Documentation, ready to test

#18168 Update some documentation of class GridIn.
  include/deal.II/grid/grid_in.h
Labels: Documentation, ready to test

#18171 github: Build noble docker image.
  .github/workflows/docker.yml
Labels: Infrastructure

#18173 Remove variables that are only ever set, but never read.
  include/deal.II/fe/fe_coupling_values.h
Labels: ready to test

#18099 github: Added matrix strategies for linux workflows.
  .github/workflows/linux.yml
Labels: Infrastructure, ready to test
