Repository dealii/dealii, pull requests merged in 2025-04, with the labels that each got.

#18308 Add necessary header includes.
  include/deal.II/algorithms/any_data.h
  include/deal.II/algorithms/general_data_storage.h
  include/deal.II/base/convergence_table.h
  include/deal.II/base/enable_observer_pointer.h
  include/deal.II/base/observer_pointer.h
  include/deal.II/base/tensor.h
Labels: ready to test

#18311 Include Kokkos headers in files that use Kokkos.
  include/deal.II/lac/precondition.h
  include/deal.II/lac/vector_operations_internal.h
  include/deal.II/matrix_free/portable_tensor_product_kernels.h
  source/base/exceptions.cc
  source/base/partitioner.cc
Labels: ready to test

#18309 Remove the inclusion of Kokkos_Macros.h from config.h.
  include/deal.II/base/config.h.in
  include/deal.II/base/exceptions.h
  include/deal.II/base/numbers.h
Labels: ready to test

#18306 Index Quadrilateral and Triangle face quadratures in the same way.
  include/deal.II/grid/reference_cell.h
  source/base/qprojector.cc
  source/fe/fe_abf.cc
  source/fe/fe_bdm.cc
  source/fe/fe_poly_tensor.cc
  source/fe/fe_raviart_thomas.cc
  source/fe/fe_rt_bubbles.cc
  tests/base/qprojector.output
  tests/base/quadrature_sorted_test.cc
  tests/base/quadrature_test.cc
  tests/base/quadrature_test.output
  tests/fe/rt_normal_02.output
  tests/grid/reference_cell_type_06.cc
  tests/grid/reference_cell_type_06.output
  tests/simplex/variable_face_quadratures_01.cc
Labels: Triangulation, ready to test, Simplices

#18316 Fix two minor orientation bugs.
  include/deal.II/grid/tria_accessor.h
Labels: Reviewed and ready to merge, Triangulation, ready to test

#18310 Let git ignore python compiled module cache.
  .gitignore
Labels: ready to test

#18318 Simplify QProjector.
  source/base/qprojector.cc
Labels: Reviewed and ready to merge, Miscellaneous, ready to test

#18312 Change residual and right preconditioner documentation for step-32.
  examples/step-32/doc/intro.dox
  examples/step-32/step-32.cc
Labels: Reviewed and ready to merge, ready to test

#18255 Revert back MUMPS interface
  .typos.toml
  cmake/configure/configure_60_mumps.cmake
  cmake/modules/FindDEAL_II_MUMPS.cmake
  doc/external-libs/mumps.html
  doc/users/cmake_dealii.html
  doc/users/cmake_user.html
  include/deal.II/base/config.h.in
  include/deal.II/lac/sparse_direct.h
  source/lac/sparse_direct.cc
  tests/mumps/CMakeLists.txt
  tests/mumps/mumps_01.cc
  tests/mumps/mumps_01.output
  tests/mumps/mumps_02.cc
  tests/mumps/mumps_02.output
  tests/run_testsuite.cmake
Labels: ready for review, Linear Algebra, ready to test, dealii-x

#18324 Changelog for mumps.
  doc/news/changes/major/20250402LucaHeltai
Labels: ready for review, Documentation, Reviewed and ready to merge, dealii-x

#18323 base/exceptions.h: add missing standard header `<complex>`
  include/deal.II/base/exceptions.h
Labels: High Priority :warning:, Reviewed and ready to merge, ready to test

#18315 Improve an error message for the SparseILU class.
  include/deal.II/lac/sparse_ilu.h
Labels: Documentation, Linear Algebra, ready to test

#18325 Improve an error message.
  include/deal.II/lac/solver_minres.h
Labels: Documentation, ready to test

#18326 Kokkos: call find_package() without QUIET
  cmake/modules/FindDEAL_II_KOKKOS.cmake
Labels: Build system, GPU, ready to test

#18321 Tests: refactor `tests.h`
  tests/tests.h
Labels: Reviewed and ready to merge, Tests, ready to test

#18327 `QProjector`: use `ReferenceCell::n_face_orientations()`.
  source/base/qprojector.cc
Labels: ready to test, Simplices

#18329 base/table_handler.h: add missing include, remove superfluous include
  include/deal.II/base/table_handler.h
Labels: ready to test

#18328 Portable MatrixFree: arrange arrays for coalesced access
  include/deal.II/matrix_free/portable_fe_evaluation.h
  include/deal.II/matrix_free/portable_matrix_free.h
  include/deal.II/matrix_free/portable_matrix_free.templates.h
  include/deal.II/matrix_free/tools.h
Labels: GPU, Matrix-free, ready to test

#18330 Portable FEEvaluation: Only go into constraints function if constrained
  include/deal.II/matrix_free/portable_fe_evaluation.h
Labels: Reviewed and ready to merge, GPU, Matrix-free, ready to test, dealii-x

#18331 Use the inverse orientation instead of hard-coding it in a test.
  tests/grid/reference_cell_reverse_orientation.cc
Labels: Tests, ready to test, Simplices

#18332 NoncontiguousPartitioner: allow duplicate ghost indices
  include/deal.II/base/mpi_noncontiguous_partitioner.h
  include/deal.II/base/mpi_noncontiguous_partitioner.templates.h
  source/base/mpi_noncontiguous_partitioner.cc
  tests/base/mpi_noncontiguous_partitioner_03.cc
  tests/base/mpi_noncontiguous_partitioner_03.mpirun=2.output
Labels: ready to test

#18334 source/base/parsed_convergence_table.cc: add a missing header
  source/base/parsed_convergence_table.cc
Labels: Reviewed and ready to merge, ready to test

#18333 Make 0 the default combined orientation.
  include/deal.II/base/types.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_objects_orientations.h
  include/deal.II/grid/tria_orientation.h
  include/deal.II/matrix_free/shape_info.templates.h
  source/base/qprojector.cc
  source/fe/fe_nedelec.cc
  source/grid/tria.cc
  tests/dofs/dof_tools_21_b.output
  tests/dofs/dof_tools_21_b_y.cc
  tests/dofs/dof_tools_21_c.output
  tests/fe/face_to_cell_q1_2d.output
  tests/fe/face_to_cell_q2_2d.output
  tests/fe/face_to_cell_q2xq2_2d.output
  tests/fe/face_to_cell_q3_2d.output
  tests/fe/face_to_cell_q3xq4_2d.output
  tests/fe/face_to_cell_q4_2d.output
  tests/fe/fe_nedelec_face_edge_orientation.h
  tests/grid/periodicity_1d.output
  tests/serialization/triangulation_01.output
  tests/serialization/triangulation_02.output
  tests/simplex/orientation_02.output
  tests/simplex/orientation_03.output
  tests/simplex/orientation_05.output
Labels: Triangulation, ready to test

#18319 Elaborate on the compiler requirements for Kokkos+Cuda
  doc/external-libs/cuda.html
Labels: Documentation

#18344 Minimize the use of MPI macros.
  source/base/data_out_base.cc
Labels: Parallel distributed, ready to test

#18343 Avoid the use of macros to denote MPI types.
  include/deal.II/base/types.h
  include/deal.II/particles/property_pool.h
  source/base/mpi.cc
  source/base/partitioner.cc
  source/dofs/dof_handler_policy.cc
  source/dofs/dof_renumbering.cc
  source/dofs/dof_tools.cc
  source/grid/grid_tools.cc
  source/lac/sparsity_tools.cc
  source/particles/generators.cc
  source/particles/particle_handler.cc
Labels: Parallel distributed, ready to test

#18341 Do not use symbols with internal linkage in include files.
  include/deal.II/base/mpi_large_count.h
Labels: Miscellaneous, ready to test

#18338 Fix naming of variables in tria.cc, part 1.
  source/grid/tria.cc
Labels: Triangulation, ready to test

#18345 Get rid of some 1d orientation special cases.
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.h
  source/base/qprojector.cc
Labels: Reviewed and ready to merge, ready to test

#18349 ReferenceCell: remove two more 1d workarounds.
  include/deal.II/grid/reference_cell.h
Labels: Triangulation, ready to test

#18347 MatrixFree: directly use the combined orientation.
  include/deal.II/matrix_free/face_setup_internal.h
Labels: Matrix-free, Triangulation, ready to test

#18353 Add a necessary header.
  include/deal.II/lac/petsc_solver.h
Labels: Reviewed and ready to merge, ready to test

#18346 MatrixFree: remove some hardcoded inverses.
  include/deal.II/matrix_free/face_setup_internal.h
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Reviewed and ready to merge, Matrix-free, Triangulation, ready to test

#18352 Prefer names with std::.
  include/deal.II/lac/petsc_block_sparse_matrix.h
  include/deal.II/lac/petsc_block_vector.h
  include/deal.II/lac/petsc_sparse_matrix.h
Labels: ready to test

#18354 Add header include to import PETSc/SLEPc macro names.
  include/deal.II/base/config.h.in
Labels: ready to test

#18357 Mark some input arguments 'const'.
  include/deal.II/lac/sparse_matrix_ez.h
  include/deal.II/lac/sparse_matrix_ez.templates.h
Labels: ready to test

#18359 MPI::NoncontiguousPartitioner: Fix missing clearing of variables in reinit
  source/base/mpi_noncontiguous_partitioner.cc
Labels: ready to test

#18358 Minor clean-ups in MatrixOut.
  include/deal.II/lac/matrix_out.h
Labels: Linear Algebra, ready to test

#18355 QProjector: combine all `project_to_all_faces()` functions.
  include/deal.II/base/qprojector.h
  include/deal.II/grid/reference_cell.h
  source/base/qprojector.cc
  tests/feinterface/fe_interface_view_01.cc
  tests/feinterface/fe_interface_view_02.cc
Labels: Reviewed and ready to merge, ready to test

#18362 MatrixFree: refactor a face setup routine.
  include/deal.II/matrix_free/face_setup_internal.h
Labels: Matrix-free, Miscellaneous, ready to test

#18366 Remove an outdated Trilinos comment.
  include/deal.II/lac/trilinos_precondition.h
Labels: ready to test

#18368 Add to some documentation.
  include/deal.II/lac/petsc_precondition.h
  include/deal.II/lac/trilinos_precondition.h
Labels: Documentation, Reviewed and ready to merge, ready to test

#18369 Add necessary header includes.
  include/deal.II/lac/petsc_snes.templates.h
  include/deal.II/lac/petsc_ts.templates.h
Labels: ready to test

#18364 QProjector: add a general function for projecting quadrature points to faces or subfaces.
  source/base/qprojector.cc
  tests/base/qprojector_02.cc
  tests/base/qprojector_02.output
Labels: Miscellaneous, ready to test

#18365 Make it possible to create sparse outputs from MatrixOut.
  doc/news/changes/minor/20250418Bangerth
  include/deal.II/lac/matrix_out.h
  source/lac/matrix_out.cc
  tests/lac/matrix_out_03.cc
  tests/lac/matrix_out_03.output
Labels: ready to test

#18367 Add a script that traces which other files a .cc or .h file depends on.
  contrib/utilities/find_header_dependencies.py
Labels: ready to test

#18340 Fix naming of variables in tria.cc, part 3.
  source/grid/tria.cc
Labels: Triangulation, ready to test

#18339 Fix naming of variables in tria.cc, part 2.
  source/grid/tria.cc
Labels: Triangulation, ready to test

#18373 Fix the pictures of oriented faces.
  doc/doxygen/custom.css
  doc/doxygen/headers/reordering.h
  doc/doxygen/headers/simplex.h
  doc/doxygen/images/quadrilateral-0.svg
  doc/doxygen/images/quadrilateral-1.svg
  doc/doxygen/images/quadrilateral-2.svg
  doc/doxygen/images/quadrilateral-3.svg
  doc/doxygen/images/quadrilateral-4.svg
  doc/doxygen/images/quadrilateral-5.svg
  doc/doxygen/images/quadrilateral-6.svg
  doc/doxygen/images/quadrilateral-7.svg
  doc/doxygen/images/reference_cells_1.png
  doc/doxygen/images/triangle-0.svg
  doc/doxygen/images/triangle-1.svg
  doc/doxygen/images/triangle-2.svg
  doc/doxygen/images/triangle-3.svg
  doc/doxygen/images/triangle-4.svg
  doc/doxygen/images/triangle-5.svg
Labels: Documentation

#18374 QProjector documentation fixes
  include/deal.II/base/qprojector.h
  source/base/qprojector.cc
Labels: Miscellaneous, ready to test

#18371 Apply auto-indenter to all python scripts.
  contrib/python-bindings/source/__init__.py
  contrib/python-bindings/tests/cell_accessor_wrapper.py
  contrib/python-bindings/tests/manifold_wrapper.py
  contrib/python-bindings/tests/mapping_wrapper.py
  contrib/python-bindings/tests/point_wrapper.py
  contrib/python-bindings/tests/quadrature_wrapper.py
  contrib/python-bindings/tests/triangulation_wrapper.py
  contrib/utilities/check_encoding.py
  contrib/utilities/checkdoxygen.py
  contrib/utilities/detect_include_cycles.py
  contrib/utilities/double_word_typos.py
  contrib/utilities/indent.py
  contrib/utilities/print_deprecated.py
  contrib/utilities/prm_tools.py
  contrib/utilities/relocate_libraries.py
  contrib/utilities/wrapcomments.py
  examples/step-55/reference.py
Labels: ready to test

#18384 Move a function into namespace dealii.
  source/lac/petsc_parallel_block_sparse_matrix.cc
Labels: ready to test

#18383 Fix HIP build
  cmake/modules/FindDEAL_II_KOKKOS.cmake
  include/deal.II/base/config.h.in
Labels: Reviewed and ready to merge, ready to test

#18081 Add basic periodicity for tetrahedra with a mesh generator and a test.
  doc/news/changes/minor/20250404KyleSchwiebert
  include/deal.II/fe/fe_simplex_p.h
  include/deal.II/grid/grid_generator.h
  source/fe/fe_simplex_p.cc
  source/grid/grid_generator.cc
  source/grid/grid_generator.inst.in
  source/grid/grid_generator_from_name.cc
  source/grid/grid_tools_dof_handlers.cc
  tests/grid/grid_generator_from_name_and_argument_02.cc
  tests/grid/grid_generator_from_name_and_argument_02.output
  tests/simplex/periodic_tet.cc
  tests/simplex/periodic_tet.output
Labels: Enhancement, ready to test, Simplices

#18380 Disentangle the order in a file.
  include/deal.II/lac/generic_linear_algebra.h
Labels: ready to test

#18360 Update docu of FEEvaluationBase::read_dof_values
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Documentation, Matrix-free

#17848 Add the step-93 tutorial program
  doc/doxygen/tutorial/tutorial.h.in
  doc/news/changes/major/20241106Scheuerman
  examples/step-93/CMakeLists.txt
  examples/step-93/doc/builds-on
  examples/step-93/doc/intro.dox
  examples/step-93/doc/kind
  examples/step-93/doc/results.dox
  examples/step-93/doc/tooltip
  examples/step-93/step-93.cc
  tests/examples/step-93.diff
Labels: Tutorials, ready to test

#18387 Fix an include statement.
  source/fe/fe_simplex_p.cc
Labels: ready to test

#18386 Un-guard two p4est declarations.
  include/deal.II/distributed/p4est_wrappers.h
  source/distributed/p4est_wrappers.cc
Labels: ready to test

#18388 Remove `P4EST_WITH_SEARCH_LOCAL`.
  cmake/configure/configure_50_p4est.cmake
  cmake/modules/FindDEAL_II_P4EST.cmake
  tests/mpi/p4est_2d_find_point_owner_rank_01.mpirun=1.with_p4est=true.output
  tests/mpi/p4est_2d_find_point_owner_rank_01.mpirun=3.with_p4est=true.output
  tests/mpi/p4est_2d_find_point_owner_rank_01.mpirun=5.with_p4est=true.output
  tests/mpi/p4est_2d_find_point_owner_rank_02.mpirun=1.with_p4est=true.output
  tests/mpi/p4est_2d_find_point_owner_rank_02.mpirun=3.with_p4est=true.output
  tests/mpi/p4est_2d_find_point_owner_rank_02.mpirun=5.with_p4est=true.output
  tests/mpi/p4est_3d_find_point_owner_rank_01.mpirun=1.with_p4est=true.output
  tests/mpi/p4est_3d_find_point_owner_rank_01.mpirun=3.with_p4est=true.output
  tests/mpi/p4est_3d_find_point_owner_rank_01.mpirun=5.with_p4est=true.output
  tests/mpi/p4est_3d_find_point_owner_rank_02.mpirun=1.with_p4est=true.output
  tests/mpi/p4est_3d_find_point_owner_rank_02.mpirun=3.with_p4est=true.output
  tests/mpi/p4est_3d_find_point_owner_rank_02.mpirun=5.with_p4est=true.output
Labels: Infrastructure, External libraries, ready to test

#18381 FEPointEvaluation: Make DoF numbering a constructor argument
  include/deal.II/matrix_free/fe_point_evaluation.h
  tests/matrix_free/point_evaluation_37.cc
  tests/matrix_free/point_evaluation_37.output
Labels: Matrix-free, ready to test

#18402 Do not separately check for MPI 3+.
  include/deal.II/base/mpi_large_count.h
Labels: ready to test

#18396 Use higher order MappingQ in MappingQEulerian
  doc/news/changes/minor/20250429Gassmoeller
  include/deal.II/fe/mapping_q_eulerian.h
  source/fe/mapping_q_eulerian.cc
  tests/mappings/mapping_q_eulerian_15.cc
  tests/mappings/mapping_q_eulerian_15.output
Labels: Mapping, ready to test

#18377 Switch MatrixOut to default to sparse output.
  doc/news/changes/incompatibilities/20250421Bangerth
  include/deal.II/lac/matrix_out.h
  tests/lac/matrix_out.cc
  tests/lac/matrix_out_02.cc
Labels: ready to test

#18063 Update step-90.cc
  examples/step-90/step-90.cc
Labels: Tutorials, ready to test

#18401 Let files that use MPI include the necessary headers.
  include/deal.II/distributed/p4est_wrappers.h
  include/deal.II/lac/petsc_precondition.h
Labels: ready to test

#18393 Fix: explicitly instantiate tpetra wrapper's BlockSparseMatrix::reinit)
  doc/news/changes/minor/20250427Shi
  source/lac/trilinos_tpetra_block_sparse_matrix.cc
  tests/trilinos_tpetra/block_matrices_01.cc
  tests/trilinos_tpetra/block_matrices_01.output
Labels: ready to test
