Repository dealii/dealii, pull requests merged in 2025-05, with the labels that each got.

#18403 Add some thoughts to step-93.
  doc/doxygen/references.bib
  examples/step-93/doc/intro.dox
  examples/step-93/doc/results.dox
  examples/step-93/step-93.cc
Labels: Tutorials, ready to test

#18398 Add non-standard oriented quadrature on subfaces
  source/base/qprojector.cc
  source/fe/fe_poly_tensor.cc
  tests/base/qprojector_subfaces.cc
  tests/base/qprojector_subfaces.output
  tests/base/quadrature_sorted_test.cc
  tests/base/quadrature_test.cc
Labels: Enhancement, ready to test

#18361 Add 1D matrices to MatrixCreator
  doc/news/changes/minor/20250501Wichrowski
  include/deal.II/lac/full_matrix.h
  include/deal.II/lac/full_matrix.templates.h
  include/deal.II/numerics/tensor_product_matrix_creator.h
  tests/lac/full_matrix_kronecker.cc
  tests/lac/full_matrix_kronecker.output
  tests/numerics/tensor_product_creator_01.cc
  tests/numerics/tensor_product_creator_01.output
  tests/numerics/tensor_product_creator_02.cc
  tests/numerics/tensor_product_creator_02.output
Labels: ready to test

#18409 Add necessary header include.
  include/deal.II/differentiation/ad/adolc_math.h
Labels: ready to test

#18382 Add assertion to check vector compression in AffineConstraints::distribute()
  include/deal.II/lac/affine_constraints.templates.h
Labels: Reviewed and ready to merge, ready to test

#18391 Cleanup `set_periodicity_constraints()`
  include/deal.II/dofs/dof_accessor.h
  source/dofs/dof_tools_constraints.cc
Labels: Triangulation, ready to test

#18415 Add necessary include file.
  include/deal.II/vtk/utilities.h
Labels: ready to test

#18412 Fix some misspellings of Trilinos names.
  include/deal.II/lac/trilinos_precondition.h
  include/deal.II/lac/trilinos_tpetra_sparsity_pattern.h
  include/deal.II/lac/trilinos_vector.h
Labels: ready to test

#18410 Be more precise with which files we compile.
  source/lac/CMakeLists.txt
Labels: ready to test

#18385 Step 81: fix typos and fix logic for enabling/disabling absorbing boundary conditions.
  examples/step-81/doc/intro.dox
  examples/step-81/step-81.cc
Labels: Tutorials, ready to test

#18414 Actually update TaskFlow to 3.10.
  bundled/taskflow-3.10.0/README.md
  bundled/taskflow-3.10.0/taskflow/algorithm/find.hpp
  bundled/taskflow-3.10.0/taskflow/algorithm/for_each.hpp
  bundled/taskflow-3.10.0/taskflow/algorithm/module.hpp
  bundled/taskflow-3.10.0/taskflow/algorithm/partitioner.hpp
  bundled/taskflow-3.10.0/taskflow/algorithm/reduce.hpp
  bundled/taskflow-3.10.0/taskflow/algorithm/sort.hpp
  bundled/taskflow-3.10.0/taskflow/algorithm/transform.hpp
  bundled/taskflow-3.10.0/taskflow/core/async.hpp
  bundled/taskflow-3.10.0/taskflow/core/atomic_notifier.hpp
  bundled/taskflow-3.10.0/taskflow/core/declarations.hpp
  bundled/taskflow-3.10.0/taskflow/core/error.hpp
  bundled/taskflow-3.10.0/taskflow/core/executor.hpp
  bundled/taskflow-3.10.0/taskflow/core/flow_builder.hpp
  bundled/taskflow-3.10.0/taskflow/core/freelist.hpp
  bundled/taskflow-3.10.0/taskflow/core/graph.hpp
  bundled/taskflow-3.10.0/taskflow/core/nonblocking_notifier.hpp
  bundled/taskflow-3.10.0/taskflow/core/observer.hpp
  bundled/taskflow-3.10.0/taskflow/core/runtime.hpp
  bundled/taskflow-3.10.0/taskflow/core/task.hpp
  bundled/taskflow-3.10.0/taskflow/core/taskflow.hpp
  bundled/taskflow-3.10.0/taskflow/core/tsq.hpp
  bundled/taskflow-3.10.0/taskflow/core/worker.hpp
  bundled/taskflow-3.10.0/taskflow/cuda/algorithm/for_each.hpp
  bundled/taskflow-3.10.0/taskflow/cuda/algorithm/reduce.hpp
  bundled/taskflow-3.10.0/taskflow/cuda/algorithm/scan.hpp
  bundled/taskflow-3.10.0/taskflow/cuda/algorithm/single_task.hpp
  bundled/taskflow-3.10.0/taskflow/cuda/algorithm/sort.hpp
  bundled/taskflow-3.10.0/taskflow/cuda/algorithm/transform.hpp
  bundled/taskflow-3.10.0/taskflow/cuda/cuda_capturer.hpp
  bundled/taskflow-3.10.0/taskflow/cuda/cuda_execution_policy.hpp
  bundled/taskflow-3.10.0/taskflow/cuda/cuda_graph.hpp
  bundled/taskflow-3.10.0/taskflow/cuda/cuda_graph_exec.hpp
  bundled/taskflow-3.10.0/taskflow/cuda/cuda_stream.hpp
  bundled/taskflow-3.10.0/taskflow/cuda/cudaflow.hpp
  bundled/taskflow-3.10.0/taskflow/utility/lazy_string.hpp
  bundled/taskflow-3.10.0/taskflow/utility/math.hpp
  bundled/taskflow-3.10.0/taskflow/utility/mpmc.hpp
  bundled/taskflow-3.10.0/taskflow/utility/os.hpp
  bundled/taskflow-3.10.0/taskflow/utility/small_vector.hpp
Labels: ready to test

#18421 Avoid a warning about an unused function argument.
  source/lac/scalapack.cc
Labels: ready to test

#18290 Implement MPGMRES - multiply preconditioned generalized minimal residual method
  doc/doxygen/references.bib
  doc/news/changes/minor/20250410Maier-1
  doc/news/changes/minor/20250410Maier-2
  include/deal.II/lac/solver_gmres.h
  tests/lac/solver_mpgmres_01.cc
  tests/lac/solver_mpgmres_01.output
  tests/lac/solver_mpgmres_02.cc
  tests/lac/solver_mpgmres_02.output
Labels: ready for review, Linear Algebra, ready to test

#18427 Prefer std::ptrdiff_t over ::ptrdiff_t.
  include/deal.II/lac/trilinos_solver.h
Labels: ready to test

#18424 CMake: collect all source and header files
  cmake/macros/macro_collect_source_and_header_files.cmake
  include/deal.II/CMakeLists.txt
  include/deal.II/algorithms/CMakeLists.txt
  include/deal.II/arborx/CMakeLists.txt
  include/deal.II/base/CMakeLists.txt
  include/deal.II/base/std_cxx17/CMakeLists.txt
  include/deal.II/base/std_cxx20/CMakeLists.txt
  include/deal.II/boost_adaptors/CMakeLists.txt
  include/deal.II/cgal/CMakeLists.txt
  include/deal.II/differentiation/CMakeLists.txt
  include/deal.II/differentiation/ad/CMakeLists.txt
  include/deal.II/differentiation/sd/CMakeLists.txt
  include/deal.II/distributed/CMakeLists.txt
  include/deal.II/dofs/CMakeLists.txt
  include/deal.II/fe/CMakeLists.txt
  include/deal.II/gmsh/CMakeLists.txt
  include/deal.II/grid/CMakeLists.txt
  include/deal.II/hp/CMakeLists.txt
  include/deal.II/integrators/CMakeLists.txt
  include/deal.II/lac/CMakeLists.txt
  include/deal.II/matrix_free/CMakeLists.txt
  include/deal.II/meshworker/CMakeLists.txt
  include/deal.II/multigrid/CMakeLists.txt
  include/deal.II/non_matching/CMakeLists.txt
  include/deal.II/numerics/CMakeLists.txt
  include/deal.II/opencascade/CMakeLists.txt
  include/deal.II/optimization/CMakeLists.txt
  include/deal.II/optimization/rol/CMakeLists.txt
  include/deal.II/particles/CMakeLists.txt
  include/deal.II/physics/CMakeLists.txt
  include/deal.II/physics/elasticity/CMakeLists.txt
  include/deal.II/sundials/CMakeLists.txt
  include/deal.II/trilinos/CMakeLists.txt
  include/deal.II/vtk/CMakeLists.txt
  source/algorithms/CMakeLists.txt
  source/arborx/CMakeLists.txt
  source/base/CMakeLists.txt
  source/cgal/CMakeLists.txt
  source/differentiation/ad/CMakeLists.txt
  source/differentiation/sd/CMakeLists.txt
  source/distributed/CMakeLists.txt
  source/dofs/CMakeLists.txt
  source/fe/CMakeLists.txt
  source/gmsh/CMakeLists.txt
  source/grid/CMakeLists.txt
  source/hp/CMakeLists.txt
  source/integrators/CMakeLists.txt
  source/lac/CMakeLists.txt
  source/matrix_free/CMakeLists.txt
  source/meshworker/CMakeLists.txt
  source/multigrid/CMakeLists.txt
  source/non_matching/CMakeLists.txt
  source/numerics/CMakeLists.txt
  source/opencascade/CMakeLists.txt
  source/optimization/rol/CMakeLists.txt
  source/particles/CMakeLists.txt
  source/physics/CMakeLists.txt
  source/physics/elasticity/CMakeLists.txt
  source/sundials/CMakeLists.txt
  source/trilinos/CMakeLists.txt
Labels: Build system, Reviewed and ready to merge, ready to test

#18376 Clarify a couple of things in the introduction to step-44.
  examples/step-44/doc/intro.dox
Labels: Tutorials, ready to test

#18429 Refactor `GridGenerator::convert_hypercube_to_simplex_mesh()`.
  source/grid/grid_generator.cc
Labels: Triangulation, ready to test, Simplices

#18430 Include a necessary header.
  source/distributed/p4est_wrappers.cc
Labels: ready to test

#18411 Improve error message when trying to configure with ArborX 2.0
  cmake/configure/configure_50_arborx.cmake
  cmake/modules/FindDEAL_II_ARBORX.cmake
Labels: ready to test

#18416 Fix some broken links.
  include/deal.II/base/data_out_base.h
Labels: Documentation, Reviewed and ready to merge

#18440 Properly qualify a namespace name.
  include/deal.II/base/exception_macros.h
Labels: Reviewed and ready to merge, ready to test

#18439 Include necessary header file.
  source/particles/generators.cc
Labels: Reviewed and ready to merge, ready to test

#18435 Better document the difference between GMRES and FGMRES.
  include/deal.II/lac/solver_gmres.h
Labels: Documentation

#18438 Prefer std::free() over ::free().
  include/deal.II/base/hdf5.h
Labels: ready to test

#18437 Fix missing assertion for undefined parameters in JSON input parsing
  doc/news/changes/minor/20250508Schreter
  source/base/parameter_handler.cc
  tests/parameter_handler/parameter_handler_read_json_06.cc
  tests/parameter_handler/parameter_handler_read_json_06.output
  tests/parameter_handler/parameter_handler_read_xml_error_01.output
  tests/parameter_handler/prm/parameter_handler_read_json_05.json
Labels: Reviewed and ready to merge, ready to test

#18442 Fix instantiation for `TpetraWrappers::BlockVector`
  cmake/config/template-arguments.in
  cmake/configure/configure_20_trilinos.cmake
  include/deal.II/base/template_constraints.h
  include/deal.II/fe/fe_tools_extrapolate.templates.h
  include/deal.II/fe/fe_tools_interpolate.templates.h
  include/deal.II/lac/read_write_vector.h
  include/deal.II/lac/trilinos_tpetra_block_vector.h
  include/deal.II/lac/vector_element_access.h
  include/deal.II/numerics/vector_tools_point_value.templates.h
  source/base/time_stepping.cc
  source/dofs/dof_accessor_get.cc
  source/dofs/dof_accessor_set.cc
  source/fe/mapping_fe_field.cc
  source/lac/solver.cc
  source/lac/vector_memory.cc
  source/multigrid/mg_base.cc
  source/non_matching/fe_values.cc
  source/non_matching/mesh_classifier.cc
  source/non_matching/quadrature_generator.cc
  source/numerics/data_out_dof_data.cc
  source/numerics/data_out_dof_data_codim.cc
  source/numerics/derivative_approximation.cc
  source/trilinos/nox.cc
Labels: ready to test

#18408 Fix missing copy of nonlocal_vector in `TpetraWrappers::Vector` assignment operator
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
Labels: Reviewed and ready to merge, ready to test

#18068 Fix `extract_boundary_mesh()` for simplex meshes
  source/grid/grid_generator.cc
Labels: Reviewed and ready to merge, ready to test

#18426 Avoid the use of anonymous namespaces in header files.
  include/deal.II/trilinos/nox.templates.h
Labels: ready to test

#18444 Improve error handling in UMFPACK wrappers.
  source/lac/sparse_direct.cc
Labels: ready to test

#18447 CMake: do not FATAL_ERROR when ArborX version is out of range
  cmake/modules/FindDEAL_II_ARBORX.cmake
Labels: Bug, Build system, Reviewed and ready to merge, ready to test

#18451 Fix HTML markup.
  examples/step-59/doc/results.dox
Labels: Documentation, Tutorials

#18452 Fix link to dockerhub in readme.
  README.md
Labels: Documentation

#18453 Make sure Sundials has the same MPI support as deal.II
  cmake/configure/configure_50_sundials.cmake
  cmake/modules/FindDEAL_II_SUNDIALS.cmake
Labels: ready to test

#18455 Fix clang-tidy complaints
  source/distributed/fully_distributed_tria.cc
  source/fe/fe_system.cc
  source/fe/fe_values_base.cc
  source/grid/grid_generator.cc
  source/grid/grid_out.cc
  source/grid/tria.cc
  source/multigrid/mg_level_global_transfer.cc
Labels: ready to test

#18456 Handle template arguments better in grid_out.cc.
  source/grid/grid_out.cc
Labels: ready to test

#18457 Also collect a few forgotten header files.
  source/base/CMakeLists.txt
  source/differentiation/CMakeLists.txt
Labels: ready to test

#18458 Try to avoid some more unused variable warnings.
  include/deal.II/base/exception_macros.h
Labels: Reviewed and ready to merge, Miscellaneous, ready to test

#18460 Modernize executable path handling in code formatting script
  contrib/utilities/indent.py
Labels: Infrastructure

#18459 Fix `IndexSet::make_petsc_is()`.
  source/base/index_set.cc
  tests/petsc/index_set_01.cc
  tests/petsc/index_set_01.output
Labels: Bug, ready to test

#18463 Fix test output.
  tests/petsc/matrix_out_03.with_petsc=true.output
Labels: Reviewed and ready to merge, ready to test

#18464 Avoid static variables and functions in header files.
  bundled/kokkos-4.5.01/core/src/impl/Kokkos_Profiling_Interface.hpp
  bundled/kokkos-4.5.01/tpls/mdspan/include/experimental/__p0009_bits/extents.hpp
  bundled/kokkos-4.5.01/tpls/mdspan/include/experimental/__p0009_bits/utility.hpp
Labels: ready to test

#18468 Improve performance of CellAccessor::has_periodic_neighbor
  source/grid/tria_accessor.cc
Labels: Reviewed and ready to merge, Triangulation, ready to test

#18473 Attempt to make MPGMRES test more robust
  tests/lac/solver_mpgmres_01.cc
  tests/lac/solver_mpgmres_01.output
Labels: Reviewed and ready to merge, Tests, Linear Algebra, ready to test

#18472 Attempt to fix warning
  source/dofs/dof_accessor_set.cc
Labels: Reviewed and ready to merge, Miscellaneous, ready to test

#18474 Work around an issue with non-exportable names.
  include/deal.II/boost_adaptors/bounding_box.h
Labels: ready to test

#18477 Fixed test petsc/index_set_01.cc.
  tests/petsc/index_set_01.cc
Labels: Tests, External libraries, ready to test

#18476 NM::MappingInfo: Allow adaptive meshes in MappingInfo for empty quadratures
  include/deal.II/non_matching/mapping_info.h
Labels: ready to test, Non-matching

#18471 Do not add Tpetra block vectors to multigrid transfer instantiations
  cmake/config/template-arguments.in
Labels: External libraries, ready to test

#18443 Add a testcase for SNES.
  tests/petsc/petsc_snes_08.cc
  tests/petsc/petsc_snes_08.output
Labels: ready to test

#18480 Run the configuration check for BLAS/LAPACK with the C++ compiler.
  cmake/configure/configure_10_lapack.cmake
Labels: Build system, ready to test

#18485 Make sure files are never truly empty.
  include/deal.II/base/mpi_stub.h
Labels: Miscellaneous, ready to test

#18258 New class for nodal variants of Nedelec polynomials with the test
  include/deal.II/base/polynomials_vector_anisotropic.h
  source/base/CMakeLists.txt
  source/base/polynomials_vector_anisotropic.cc
  tests/base/polynomials_vector_anisotropic.cc
  tests/base/polynomials_vector_anisotropic.output
Labels: Finite Element, ready to test

#18484 Avoid an unnecessary detour.
  source/particles/particle.cc
Labels: ready to test

#18496 Remove `(void)` casts for `AssertNothrow()` variables.
  include/deal.II/base/exception_macros.h
  include/deal.II/base/hdf5.h
  source/base/hdf5.cc
  source/base/init_finalize.cc
  source/base/mpi.cc
  source/lac/petsc_matrix_base.cc
  source/lac/petsc_parallel_block_sparse_matrix.cc
  source/lac/petsc_parallel_sparse_matrix.cc
  source/lac/petsc_vector_base.cc
  source/lac/slepc_solver.cc
  source/lac/slepc_spectral_transformation.cc
Labels: Reviewed and ready to merge, Miscellaneous, ready to test

#18504 Avoid including .cc files for split instantiations.
  source/matrix_free/evaluation_template_face_factory.cc
  source/matrix_free/evaluation_template_face_factory_inst2.cc
  source/matrix_free/evaluation_template_face_factory_inst3.cc
  source/matrix_free/evaluation_template_face_factory_inst4.cc
  source/matrix_free/evaluation_template_face_factory_inst5.cc
  source/matrix_free/evaluation_template_face_factory_inst6.cc
  source/matrix_free/evaluation_template_factory.cc
  source/matrix_free/evaluation_template_factory_inst2.cc
  source/matrix_free/evaluation_template_factory_inst3.cc
  source/matrix_free/evaluation_template_factory_inst4.cc
  source/matrix_free/evaluation_template_factory_inst5.cc
  source/matrix_free/evaluation_template_factory_inst6.cc
  source/matrix_free/mapping_info.cc
  source/matrix_free/mapping_info_inst2.cc
  source/matrix_free/mapping_info_inst3.cc
  source/numerics/matrix_creator.cc
  source/numerics/matrix_creator_inst2.cc
  source/numerics/matrix_creator_inst3.cc
Labels: Miscellaneous, ready to test

#18500 Remove a template instantiation optimization when building modules.
  include/deal.II/dofs/dof_handler.h
  include/deal.II/grid/tria.h
  include/deal.II/hp/mapping_collection.h
Labels: Miscellaneous, ready to test

#18503 Provide dummy implementations of SparseDirectMUMPS when not configuring with MUMPS.
  source/lac/sparse_direct.cc
Labels: External libraries, ready to test

#18488 Also indent module files.
  contrib/utilities/indent
  contrib/utilities/indent-all
Labels: ready to test

#18491 Add two utility scripts that help debugging module problems.
  contrib/utilities/detect_module_cycles.py
  contrib/utilities/find_module_partition_dependencies.py
Labels: Reviewed and ready to merge, ready to test

#18489 Add the scripts that convert files to modules.
  contrib/utilities/convert_header_file_to_interface_module_unit.py
  contrib/utilities/convert_source_file_to_implementation_module_unit.py
  contrib/utilities/convert_to_module_units_common.py
Labels: Reviewed and ready to merge, ready to test

#18494 Mark up the scalapack wrapper file for module scripts.
  include/deal.II/lac/scalapack.templates.h
Labels: ready to test

#18514 Clean up the definition of `Assert()`.
  include/deal.II/base/exception_macros.h
Labels: Miscellaneous, ready to test

#18519 Fix output for MUMPS tests
  tests/mumps/mumps_01.output
  tests/mumps/mumps_02.output
  tests/mumps/mumps_03.output
  tests/mumps/mumps_04.output
  tests/mumps/mumps_05.output
Labels: Reviewed and ready to merge, ready to test

#18520 Make step-93 compile.
  examples/step-93/step-93.cc
Labels: Reviewed and ready to merge, ready to test

#18528 Add necessary C++ headers to step-11 and step-51.
  examples/step-11/step-11.cc
  examples/step-51/step-51.cc
Labels: ready to test

#18527 Add std:: qualification to some calls.
  examples/step-38/step-38.cc
  examples/step-49/step-49.cc
Labels: ready to test
