Repository dealii/dealii, pull requests merged in 2025-03, with the labels that each got.

#18179 Fix division by zero in particle generator 'probabilistic_locations'
  doc/news/changes/minor/20250228Gassmoeller
  source/particles/generators.cc
  tests/particles/generators_14.cc
  tests/particles/generators_14.with_p4est=true.mpirun=2.output
Labels: Reviewed and ready to merge, ready to test

#18183 Avoid a warning about an unused variable.
  include/deal.II/numerics/nonlinear.h
Labels: ready to test

#18182 Use proper <deal.II/...> includes instead of "deal.II/...".
  source/non_matching/mesh_classifier.cc
  source/non_matching/quadrature_generator.cc
Labels: ready to test

#18181 Avoid a couple more uses of the DEBUG macro.
  include/deal.II/base/partitioner.templates.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
Labels: ready to test

#18176 Update pre-commit.
  .pre-commit-config.yaml
  doc/news/3.1.0-vs-3.2.0.h
  include/deal.II/base/tensor_function.h
  include/deal.II/matrix_free/tensor_product_kernels.h
  source/grid/grid_out.cc
  tests/base/polynomial_lagrange_order.cc
  tests/grid/grid_out_gnuplot_01.cc
Labels: Reviewed and ready to merge, ready to test

#18186 Update some documentation to reference ReferenceCell.
  doc/doxygen/headers/geometry_and_primitives.h
Labels: Documentation, Reviewed and ready to merge, Simplices

#18158 Added an optional parameter for the ParsedFunction
  doc/news/changes/minor/20250227Gaboriault
  include/deal.II/base/parsed_function.h
  source/base/parsed_function.cc
  tests/base/function_parser_13.cc
  tests/base/function_parser_13.with_muparser=true.output
Labels: Reviewed and ready to merge, ready to test

#18188 Assert: Avoid warnings about unused variables before C++20
  include/deal.II/base/exception_macros.h
Labels: Reviewed and ready to merge, ready to test

#18189 Food warning in assert macro
  include/deal.II/base/exception_macros.h
Labels: ready to test

#18175 FEFaceEvaluation: enable FE_DGP
  include/deal.II/matrix_free/evaluation_kernels.h
  include/deal.II/matrix_free/evaluation_kernels_common.h
  include/deal.II/matrix_free/evaluation_kernels_face.h
  include/deal.II/matrix_free/fe_evaluation_data.h
  tests/matrix_free/matrix_vector_faces_36.cc
  tests/matrix_free/matrix_vector_faces_36.output
Labels: Matrix-free, ready to test

#18098 Include Ghost cells in MatrixFree data starage: active level. Tests.
  doc/news/changes/minor/20250130Wichrowski
  include/deal.II/matrix_free/matrix_free.templates.h
  tests/matrix_free/matrix_vector_26.cc
  tests/matrix_free/matrix_vector_26.with_trilinos=true.with_p4est=true.mpirun=2.output
  tests/matrix_free/matrix_vector_27.cc
  tests/matrix_free/matrix_vector_27.with_trilinos=true.with_p4est=true.mpirun=2.output
Labels: Matrix-free, ready to test

#18197 doxygen: use full page width
  doc/doxygen/doxygen-awesome.css
Labels: Documentation, ready to test

#18194 Explicitly disable mold in failing builds using Docker containers
  .github/workflows/linux.yml
Labels: Infrastructure

#18200 Leave a note with step-58.
  examples/step-58/doc/results.dox
Labels: ready to test

#18202 github-actions: Enable mold again.
  .github/workflows/linux.yml
Labels: Infrastructure

#18203 Only use TeamVectorRange from Kokkos 2.9.00 on
  include/deal.II/matrix_free/portable_tensor_product_kernels.h
Labels: ready to test

#18198 fix local sparsity for Q_iso_Q1
  source/fe/fe_q_iso_q1.cc
Labels: ready to test

#18196 QProjector: overhaul documentation.
  include/deal.II/base/qprojector.h
Labels: Documentation

#18204 Convert a couple places into 'if constexpr'.
  source/base/data_out_base.cc
Labels: ready to test

#18195 Fix tasking deadlocks
  include/deal.II/base/thread_management.h
Labels: Bug, Parallel, ready to test

#18207 improve Q_iso_Q1 test
  tests/fe/local_sparsity_01.cc
  tests/fe/local_sparsity_01.output
Labels: Tests, ready to test

#18211 Un-hardcode some default orientation values.
  include/deal.II/grid/tria_accessor.h
  include/deal.II/matrix_free/shape_info.templates.h
  source/grid/grid_in.cc
  source/grid/tria.cc
Labels: ready to test, Simplices

#18212 Remove hardcoded orientations 2
  source/fe/fe_poly_tensor.cc
  source/grid/tria.cc
Labels: Triangulation, ready to test

#18214 Make a test compile with -Werror.
  tests/hp/fe_face_values_reinit_01.cc
Labels: Tests, ready to test

#18216 Move an #include statement.
  include/deal.II/base/exception_macros.h
  include/deal.II/base/exceptions.h
Labels: ready to test

#18218 Fix the name of variable reporting the Kokkos version.
  cmake/modules/FindDEAL_II_KOKKOS.cmake
Labels: ready to test

#18223 Do not use 'static' functions in header files.
  include/deal.II/fe/fe_tools.templates.h
  include/deal.II/numerics/matrix_creator.templates.h
  include/deal.II/numerics/vector_tools_boundary.templates.h
  include/deal.II/numerics/vector_tools_integrate_difference.templates.h
Labels: Miscellaneous, ready to test

#18222 Use functions/types from std:: instead of ::.
  include/deal.II/base/aligned_vector.h
  include/deal.II/base/memory_consumption.h
  include/deal.II/base/mpi.h
  include/deal.II/base/signaling_nan.h
  include/deal.II/base/table.h
  include/deal.II/base/utilities.h
  include/deal.II/base/vectorization.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/hp/collection.h
  include/deal.II/numerics/data_out_dof_data.h
  include/deal.II/numerics/rtree.h
  source/base/job_identifier.cc
  source/grid/grid_refinement.cc
  source/grid/tria.cc
  source/lac/trilinos_tpetra_sparsity_pattern.cc
Labels: Miscellaneous, ready to test

#18221 Add missing #includes.
  include/deal.II/base/function_derivative.h
  include/deal.II/base/partitioner.h
  include/deal.II/matrix_free/evaluation_template_face_factory.templates.h
  include/deal.II/matrix_free/evaluation_template_factory_hanging_nodes.templates.h
  include/deal.II/particles/partitioner.h
  source/base/function_derivative.cc
  source/lac/matrix_out.cc
  source/numerics/vector_tools_interpolate.cc
  source/numerics/vector_tools_mean_value.cc
  source/numerics/vector_tools_point_gradient.cc
  source/numerics/vector_tools_point_value.cc
  source/particles/utilities.cc
Labels: Miscellaneous, ready to test

#18225 Use _v variables instead of ...::value.
  include/deal.II/hp/fe_collection.h
  include/deal.II/hp/mapping_collection.h
Labels: hp adaptivity, ready to test

#18224 Do not use anonymous namespaces in header files.
  include/deal.II/numerics/data_out_dof_data.templates.h
Labels: Miscellaneous, ready to test

#18215 Do not include <mpi.h> from config.h.
  include/deal.II/base/config.h.in
  include/deal.II/base/mpi.h
  include/deal.II/base/mpi_large_count.h
  include/deal.II/base/mpi_stub.h
  include/deal.II/lac/la_parallel_vector.h
  source/base/exceptions.cc
  source/base/mpi.cc
  tests/base/mpi_exceptions.cc
  tests/mpi/petsc_01.cc
  tests/mpi/petsc_02.cc
  tests/mpi/petsc_03.cc
  tests/mpi/refine_and_coarsen_fixed_number_06.cc
  tests/mpi/simple_mpi_01.cc
  tests/mpi/trilinos_bug_5609.cc
  tests/quick_tests/mpi.cc
  tests/sundials/n_vector.cc
  tests/trilinos/renumbering_01.cc
Labels: Reviewed and ready to merge, ready to test

#18187 Clean up and expand the orientation module.
  doc/doxygen/headers/reordering.h
Labels: Documentation, Reviewed and ready to merge, ready to test, Simplices

#18231 Do not use anonymous namespaces in header files.
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
Labels: ready to test

#18229 Use C++ facilities to convert numbers.
  source/base/utilities.cc
Labels: ready to test

#18233 Remove a header include that is no longer needed.
  source/lac/sparse_direct.cc
Labels: ready to test

#18237 Add necessary std header files.
  source/base/polynomials_integrated_legendre_sz.cc
  source/grid/grid_generator.cc
  source/lac/exceptions.cc
  source/lac/tensor_product_matrix.cc
  source/numerics/vector_tools_project_qp.cc
  source/numerics/vector_tools_project_qpmf.cc
Labels: Miscellaneous, ready to test

#18240 Simplify some type construct.
  include/deal.II/base/exception_macros.h
Labels: Miscellaneous, ready to test

#18239 Do not use anonymous namespaces in header files.
  include/deal.II/matrix_free/matrix_free.templates.h
  include/deal.II/matrix_free/portable_matrix_free.templates.h
Labels: Miscellaneous, ready to test

#18241 github-actions: Use all jobs to build docker image.
  .github/workflows/docker.yml
Labels: Infrastructure

#18238 Qualify more things with std::.
  include/deal.II/matrix_free/portable_matrix_free.templates.h
  source/base/data_out_base.cc
  source/base/exceptions.cc
  source/base/init_finalize.cc
  source/base/path_search.cc
  source/base/polynomials_pyramid.cc
  source/grid/cell_id.cc
  source/grid/grid_generator.cc
  source/grid/grid_in.cc
  source/grid/grid_tools.cc
Labels: ready to test

#18245 Fix clang-tidy complaints
  include/deal.II/base/polynomials_bernstein.h
  include/deal.II/base/tensor.h
  include/deal.II/fe/mapping_q_internal.h
  include/deal.II/lac/block_vector_base.h
  include/deal.II/matrix_free/fe_point_evaluation.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/meshworker/copy_data.h
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
  source/base/polynomials_bernardi_raugel.cc
  source/base/table_handler.cc
  source/base/tensor_product_polynomials.cc
  source/base/tensor_product_polynomials_bubbles.cc
  source/base/tensor_product_polynomials_const.cc
  source/base/utilities.cc
  source/dofs/dof_handler_policy.cc
  source/dofs/dof_tools_sparsity.cc
  source/fe/fe_nedelec.cc
  source/fe/fe_pyramid_p.cc
  source/fe/fe_q_hierarchical.cc
  source/fe/fe_raviart_thomas.cc
  source/fe/fe_wedge_p.cc
  source/grid/grid_generator.cc
  source/grid/grid_out.cc
  source/grid/grid_tools.cc
  source/grid/manifold.cc
  source/grid/tria.cc
  source/grid/tria_accessor.cc
  source/grid/tria_description.cc
  source/hp/fe_values.cc
  source/non_matching/quadrature_generator.cc
  source/numerics/derivative_approximation.cc
  source/numerics/point_value_history.cc
  source/numerics/smoothness_estimator.cc
Labels: Reviewed and ready to merge, ready to test

#18244 Remove `mm_malloc.h`.
  source/base/utilities.cc
Labels: Reviewed and ready to merge, ready to test

#18250 CMake: Bugfix: ensure that `CMAKE_REQUIRED_*` are populated prior to language feature checks
  cmake/checks/check_01_cxx_features.cmake
  cmake/macros/macro_enable_if_links.cmake
  cmake/macros/macro_enable_if_supported.cmake
Labels: Reviewed and ready to merge, ready to test

#18252 Leave a comment in a cmake file.
  cmake/macros/macro_deal_ii_add_test.cmake
Labels: ready to test

#18249 Some more std includes.
  include/deal.II/base/convergence_table.h
  include/deal.II/base/derivative_form.h
  include/deal.II/base/function_bessel.h
  include/deal.II/base/function_tools.h
  include/deal.II/base/linear_index_iterator.h
  include/deal.II/base/tensor_accessors.h
Labels: ready to test

#18235 Refactor Docker workflow to streamline image tagging
  .github/workflows/docker.yml
  contrib/docker/Dockerfile
Labels: Infrastructure, Reviewed and ready to merge

#18242 github-actions: Add arm build to 'linux debug parallel' workflow.
  .github/workflows/linux.yml
  tests/examples/step-51.diff
  tests/examples/step-51.output
Labels: Infrastructure, ready to test

#18256 Replace min(max()) by clamp(). #17722
  examples/step-21/step-21.cc
  examples/step-42/step-42.cc
  examples/step-43/step-43.cc
  examples/step-79/step-79.cc
  include/deal.II/base/geometry_info.h
  source/base/function_lib.cc
  source/base/function_signed_distance.cc
  source/base/process_grid.cc
Labels: Reviewed and ready to merge, ready to test

#18246 Add necessary header includes.
  include/deal.II/matrix_free/evaluation_selector.h
  include/deal.II/multigrid/mg_transfer_matrix_free.templates.h
Labels: ready to test

#18247 Add necessary Kokkos header includes.
  include/deal.II/base/partitioner.h
  include/deal.II/lac/affine_constraints.templates.h
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/lac/trilinos_tpetra_precondition.templates.h
  include/deal.II/lac/vector_memory.templates.h
  include/deal.II/matrix_free/portable_evaluation_kernels.h
  include/deal.II/matrix_free/portable_hanging_nodes_internal.h
  include/deal.II/matrix_free/tools.h
Labels: ready to test

#18257 Fix a linker error
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
Labels: Reviewed and ready to merge, Miscellaneous, ready to test

#18260 portable matrixfree: rename and move kernel
  include/deal.II/matrix_free/tools.h
Labels: Reviewed and ready to merge, GPU, ready to test

#18262 Set a formula in typewriter font
  include/deal.II/lac/lapack_full_matrix.h
Labels: Documentation

#18266 Fix a typo in a code comment
  include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h
Labels: Documentation, Reviewed and ready to merge

#18261 portable matrix-free: fix GPU crash in compute_diagonal()
  doc/news/changes/minor/20250319tjhei
  examples/step-64/step-64.cc
  include/deal.II/matrix_free/portable_fe_evaluation.h
  include/deal.II/matrix_free/tools.h
  tests/matrix_free_kokkos/compute_diagonal_util.h
Labels: GPU, ready to test

#18268 Portable::MatrixFree: fix a typo
  include/deal.II/matrix_free/portable_matrix_free.h
Labels: Documentation, ready to test

#18263 SparsityPattern: order of functions and avoid inlining a function
  include/deal.II/lac/sparsity_pattern.h
  source/lac/sparsity_pattern.cc
Labels: Linear Algebra, ready to test

#18270 step-64: Improve explanation of MPI-GPU assignment
  examples/step-64/step-64.cc
Labels: Documentation, Tutorials

#18267 refactor Portable::MatrixFree by combining Shared and GPU data
  examples/step-64/step-64.cc
  include/deal.II/matrix_free/portable_evaluation_kernels.h
  include/deal.II/matrix_free/portable_fe_evaluation.h
  include/deal.II/matrix_free/portable_matrix_free.h
  include/deal.II/matrix_free/portable_matrix_free.templates.h
  include/deal.II/matrix_free/tools.h
  tests/matrix_free_kokkos/coefficient_eval_device.cc
  tests/matrix_free_kokkos/matrix_free_device_no_index_initialize.cc
  tests/matrix_free_kokkos/matrix_vector_device_mf.h
  tests/matrix_free_kokkos/matrix_vector_host_device_multi_component.cc
Labels: GPU, ready to test

#18269 step-64: require LAPACK
  examples/step-64/CMakeLists.txt
  tests/examples/step-64.mpirun=2.with_p4est=true.with_lapack=true.output
Labels: Build system, Reviewed and ready to merge, ready to test

#18272 Trilinos: require 13.2
  cmake/configure/configure_20_trilinos.cmake
  doc/external-libs/trilinos.html
Labels: ready to test, dependencies

#18275 Trilinos: remove <13.2 code
  doc/news/changes/incompatibilities/20250321tjhei
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.h
  include/deal.II/lac/trilinos_tpetra_sparse_matrix.templates.h
  include/deal.II/lac/trilinos_tpetra_vector.h
  include/deal.II/lac/trilinos_tpetra_vector.templates.h
  source/lac/trilinos_tpetra_sparsity_pattern.cc
  tests/trilinos_tpetra/precondition.cc
Labels: Reviewed and ready to merge, ready to test

#18274 Portable::FEEvaluation: remove deprecated functions taking bool
  include/deal.II/matrix_free/portable_fe_evaluation.h
Labels: GPU, ready to test

#17659 fix Kokkos+CUDA inside PETSc/Trilinos detection
  bundled/setup_bundled.cmake
  cmake/modules/FindDEAL_II_KOKKOS.cmake
  cmake/modules/FindDEAL_II_TRILINOS.cmake
Labels: GPU, ready to test

#18259 Add geometry in GridGenerator pass by arguments
  doc/news/changes/minor/20250320Campos
  source/grid/grid_generator_from_name.cc
  tests/grid/grid_generator_from_name_and_argument_02.cc
  tests/grid/grid_generator_from_name_and_argument_02.output
Labels: ready to test

#18280 Fix a problem with DoFTools::map_dofs_to_support_points() and FE_Nothing.
  doc/news/changes/minor/20250323Bangerth
  source/dofs/dof_tools.cc
  tests/dofs/map_dofs_to_support_points_02.cc
  tests/dofs/map_dofs_to_support_points_02.output
Labels: ready to test

#18284 Clarify documentation.
  include/deal.II/dofs/dof_tools.h
  include/deal.II/fe/fe.h
Labels: Documentation, ready to test

#18273 Portable::MatrixFree: introduce DeviceVector
  examples/step-64/step-64.cc
  include/deal.II/matrix_free/portable_fe_evaluation.h
  include/deal.II/matrix_free/portable_matrix_free.h
  include/deal.II/matrix_free/portable_matrix_free.templates.h
  include/deal.II/matrix_free/tools.h
  tests/matrix_free_kokkos/coefficient_eval_device.cc
  tests/matrix_free_kokkos/matrix_free_device_no_index_initialize.cc
  tests/matrix_free_kokkos/matrix_vector_device_mf.h
  tests/matrix_free_kokkos/matrix_vector_host_device_multi_component.cc
Labels: GPU, ready to test

#18277 p::distributed::BlockVector: add MemorySpace
  include/deal.II/base/template_constraints.h
  include/deal.II/lac/la_parallel_block_vector.h
  include/deal.II/lac/la_parallel_block_vector.templates.h
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/precondition.h
  include/deal.II/numerics/data_out_dof_data.templates.h
  source/lac/la_parallel_block_vector.cc
  source/lac/la_parallel_block_vector.inst.in
  source/lac/la_parallel_vector.cc
Labels: GPU, Matrix-free, ready to test

#18287 Avoid unicode quoting.
  cmake/checks/check_01_cxx_features.cmake
  cmake/macros/macro_copy_target_properties.cmake
  cmake/macros/macro_define_interface_target.cmake
  cmake/macros/macro_process_feature.cmake
  cmake/macros/macro_target_compile_flags.cmake
  cmake/macros/macro_target_link_flags.cmake
Labels: ready to test

#18219 Minor cleanup in reporting in detailed.log.
  cmake/setup_write_config.cmake
Labels: ready to test

#18286 FEPointEvaluation: enable normal derivatives for arbitrary number of components
  include/deal.II/matrix_free/fe_point_evaluation.h
  tests/matrix_free/point_evaluation_36.cc
  tests/matrix_free/point_evaluation_36.output
Labels: Matrix-free, ready to test

#18288 Cmake: clean up Kokkos configuration
  cmake/configure/configure_20_petsc.cmake
  cmake/configure/configure_20_trilinos.cmake
  cmake/configure/configure_30_kokkos.cmake
  cmake/modules/FindDEAL_II_KOKKOS.cmake
  cmake/modules/FindDEAL_II_PETSC.cmake
  cmake/modules/FindDEAL_II_TRILINOS.cmake
Labels: ready to test

#18276 Portable::MatrixFree support cell_loop() with BlockVector
  include/deal.II/matrix_free/portable_matrix_free.h
  include/deal.II/matrix_free/portable_matrix_free.templates.h
  tests/matrix_free_kokkos/cell_loop_block_01.cc
  tests/matrix_free_kokkos/cell_loop_block_01.output
Labels: GPU, ready to test

#18289 Delete code paths for Kokkos versions before 3.4
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/lac/vector_operations_internal.h
  include/deal.II/matrix_free/portable_matrix_free.templates.h
  include/deal.II/matrix_free/portable_tensor_product_kernels.h
  source/base/exceptions.cc
Labels: Reviewed and ready to merge, ready to test

#18265 SparseMatrixTools: speed up a function to extract a sub-matrix
  include/deal.II/lac/sparse_matrix_tools.h
Labels: Linear Algebra, ready to test, dealii-x

#18291 Improve a discussion in step-8.
  examples/step-8/doc/results.dox
  examples/step-8/step-8.cc
Labels: Tutorials, ready to test

#18297 Fix matrix-free Kokkos performance test
  tests/performance/timing_matrix_free_kokkos.cc
Labels: Reviewed and ready to merge, GPU, ready to test, Performance tester

#18293 Portable::MatrixFree: add dof_handler index
  include/deal.II/matrix_free/portable_fe_evaluation.h
  include/deal.II/matrix_free/portable_matrix_free.h
  include/deal.II/matrix_free/portable_matrix_free.templates.h
Labels: GPU, ready to test

#18298 Ensure that Kokkos's symbols have external linkage and, consequently can be re-exported.
  bundled/kokkos-3.7.00/core/src/Kokkos_Core_fwd.hpp
  bundled/kokkos-3.7.00/core/src/Kokkos_View.hpp
Labels: External libraries, ready to test

#18302 Omit 'const' for variables declared 'constexpr const'.
  include/deal.II/base/patterns.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/matrix_free/portable_matrix_free.h
  include/deal.II/meshworker/copy_data.h
Labels: ready to test

#18199 Add support for PSBLAS
  cmake/configure/configure_50_psblas.cmake
  cmake/modules/FindDEAL_II_PSBLAS.cmake
  doc/external-libs/psblas.html
  doc/news/changes/major/20250312LucaHeltai
  doc/readme.html
  include/deal.II/base/config.h.in
  tests/psblas/CMakeLists.txt
  tests/psblas/find_psblas.cc
  tests/psblas/find_psblas.mpirun=2.output
Labels: External libraries, ready to test, dealii-x

#18305 Make use of DEAL_II_KOKKOS_VERSION_GTE.
  include/deal.II/base/exception_macros.h
  include/deal.II/base/exceptions.h
  include/deal.II/base/memory_space_data.h
  include/deal.II/base/tensor.h
  include/deal.II/base/utilities.h
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/lac/vector_operations_internal.h
  include/deal.II/matrix_free/portable_matrix_free.templates.h
  include/deal.II/matrix_free/portable_tensor_product_kernels.h
  source/base/init_finalize.cc
  source/base/kokkos.cc
Labels: Reviewed and ready to merge, ready to test
