Repository dealii/dealii, pull requests merged in 2025-01, with the labels that each got.

#17967 FEEvaluation: Only get shared vector data if we have DoFInfo
  include/deal.II/matrix_free/fe_evaluation.h
Labels: Matrix-free, ready to test

#17966 Update writing-documentation.html
  doc/developers/writing-documentation.html
Labels: Documentation

#17965 Add `ReferenceCell::max_n_lines<dim>()` and `ReferenceCell::max_n_faces<dim>()`.
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.h
  include/deal.II/matrix_free/fe_evaluation_data.h
  include/deal.II/matrix_free/mapping_info.templates.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
  source/grid/grid_in.cc
  source/grid/tria.cc
  source/grid/tria_accessor.cc
Labels: ready to test, Simplices

#17970 MappingManifold: use std::array.
  include/deal.II/fe/mapping_manifold.h
  source/fe/mapping_manifold.cc
Labels: Reviewed and ready to merge, Manifold, ready to test

#17969 fix unused argument warning in TriaAccessor::line_index
  include/deal.II/grid/tria_accessor.h
Labels: Reviewed and ready to merge, ready to test

#17961 Use FiniteElement::shape_function_belongs_to() in step-42.
  examples/step-42/step-42.cc
Labels: ready to test

#17972 Combine the `vertex_index()` functions.
  include/deal.II/grid/tria_accessor.h
  source/grid/tria.cc
Labels: Triangulation, ready to test

#17973 Fix assert about distributed tria in NonMatching namespace
  source/non_matching/coupling.cc
Labels: ready to test, Non-matching

#17976 Improve a few assertions in step-44.
  examples/step-44/step-44.cc
Labels: Miscellaneous, ready to test

#17897 Modernize `dealii::Rol::VectorAdaptor` to use `ROL::Ptr`.
  cmake/configure/configure_20_trilinos.cmake
  doc/news/changes/incompatibilities/20241128Fehling1
  doc/news/changes/incompatibilities/20241128Fehling2
  include/deal.II/optimization/rol/vector_adaptor.h
  tests/rol/vector_adaptor_01.cc
  tests/rol/vector_adaptor_02.cc
  tests/rol/vector_adaptor_02.output
  tests/rol/vector_adaptor_02.output.12.14.1
  tests/rol/vector_adaptor_02.output.12.4.2
  tests/rol/vector_adaptor_apply_binary_01.cc
  tests/rol/vector_adaptor_no_ghost_01.cc
  tests/rol/vector_adaptor_with_ghost_01.cc
Labels: ready for review, External libraries, ready to test

#17977 support DoF coupling in FESystem
  source/fe/fe_system.cc
  tests/fe/assemble_q_iso_q1_01.cc
  tests/fe/assemble_q_iso_q1_01.output
  tests/fe/assemble_q_iso_q1_02.cc
  tests/fe/assemble_q_iso_q1_02.output
  tests/fe/deformed_projection.h
  tests/fe/local_sparsity_01.cc
  tests/fe/local_sparsity_01.output
  tests/fe/local_sparsity_q_iso_q1.cc
Labels: Finite Element, ready to test

#17974 Add ReferenceCell::max_n_vertices<dim>().
  include/deal.II/fe/mapping.h
  include/deal.II/fe/mapping_fe_field.h
  include/deal.II/fe/mapping_q1_eulerian.h
  include/deal.II/fe/mapping_q_cache.h
  include/deal.II/fe/mapping_q_eulerian.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.h
  source/fe/mapping.cc
  source/fe/mapping_fe_field.cc
  source/fe/mapping_q.cc
  source/fe/mapping_q1_eulerian.cc
  source/fe/mapping_q_cache.cc
  source/fe/mapping_q_eulerian.cc
  source/grid/tria.cc
Labels: Triangulation, ready to test, Simplices

#17985 Move `max_n_vertices<structdim>()` etc to `namespace ReferenceCells`.
  include/deal.II/fe/mapping.h
  include/deal.II/fe/mapping_fe_field.h
  include/deal.II/fe/mapping_q1_eulerian.h
  include/deal.II/fe/mapping_q_cache.h
  include/deal.II/fe/mapping_q_eulerian.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.h
  include/deal.II/matrix_free/fe_evaluation_data.h
  include/deal.II/matrix_free/mapping_info.templates.h
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
  source/fe/mapping.cc
  source/fe/mapping_fe_field.cc
  source/fe/mapping_q.cc
  source/fe/mapping_q1_eulerian.cc
  source/fe/mapping_q_cache.cc
  source/fe/mapping_q_eulerian.cc
  source/grid/grid_in.cc
  source/grid/tria.cc
  source/grid/tria_accessor.cc
Labels: Reviewed and ready to merge, Triangulation, ready to test

#17986 Be consistent about escaping names of code gallery programs.
  doc/doxygen/scripts/code-gallery.pl
  doc/doxygen/scripts/make_gallery.pl
  doc/doxygen/scripts/steps.pl
Labels: Documentation, ready to test

#17987 Deprecate `types::geometric_entity_type`.
  include/deal.II/base/types.h
  include/deal.II/grid/connectivity.h
Labels: Miscellaneous, ready to test

#17982 Better document some small pieces of step-44.
  examples/step-44/step-44.cc
Labels: ready to test

#17887 Disable CGAL warning
  source/cgal/intersections.cc
Labels: ready to test

#17516 parallel_for() for transform with taskflow
  include/deal.II/base/parallel.h
  include/deal.II/base/synchronous_iterator.h
Labels: Parallel, ready to test

#17991 Make code in step-44 easier to read.
  examples/step-44/step-44.cc
Labels: Tutorials, Finite Element, ready to test

#17988 Add `types::geometric_orientation`.
  include/deal.II/base/qprojector.h
  include/deal.II/base/types.h
  include/deal.II/dofs/dof_tools.h
  include/deal.II/fe/fe.h
  include/deal.II/fe/fe_q_base.h
  include/deal.II/fe/fe_system.h
  include/deal.II/grid/grid_tools.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria.h
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_objects_orientations.h
  include/deal.II/grid/tria_orientation.h
  include/deal.II/matrix_free/face_setup_internal.h
  source/base/qprojector.cc
  source/distributed/tria.cc
  source/dofs/dof_tools_constraints.cc
  source/dofs/dof_tools_constraints.inst.in
  source/fe/fe.cc
  source/fe/fe_q_base.cc
  source/fe/fe_system.cc
  source/grid/grid_tools.cc
  source/grid/grid_tools_dof_handlers.cc
  source/grid/grid_tools_dof_handlers.inst.in
  source/grid/tria.cc
  tests/dofs/dof_tools_21_b.cc
  tests/dofs/dof_tools_21_b_x.cc
  tests/dofs/dof_tools_21_b_x_q3.cc
  tests/dofs/dof_tools_21_b_y.cc
  tests/dofs/dof_tools_21_c.cc
  tests/fe/face_to_cell_q1_2d.cc
  tests/fe/face_to_cell_q2_2d.cc
  tests/fe/face_to_cell_q2xq2_2d.cc
  tests/fe/face_to_cell_q3_2d.cc
  tests/fe/face_to_cell_q3xq4_2d.cc
  tests/fe/face_to_cell_q4_2d.cc
  tests/grid/grid_tools_05.cc
  tests/grid/grid_tools_06.cc
  tests/grid/reference_cell_reverse_orientation.cc
  tests/mpi/periodicity_04.cc
  tests/simplex/orientation_02.cc
Labels: Triangulation, ready to test

#17996 Combine the quad_index() functions.
  include/deal.II/grid/tria_accessor.h
Labels: Reviewed and ready to merge, Triangulation, ready to test

#18004 Improve some assertions in ReferenceCell.
  include/deal.II/grid/reference_cell.h
Labels: ready to test, Meshes

#17998 Move a function in step-44.
  examples/step-44/step-44.cc
Labels: ready to test

#18000 Initialize some FEValuesExtractors where it is easiest to read (step-44).
  examples/step-44/step-44.cc
Labels: ready to test

#18007 Fix an error message.
  include/deal.II/sundials/ida.h
Labels: ready to test

#18006 Fix a comment.
  source/distributed/tria.cc
Labels: ready to test

#18003 Convert FETools::compute_face_embedding_matrices() to use ArrayView.
  doc/news/changes/incompatibilities/20250116Bangerth-2
  include/deal.II/fe/fe_tools.h
  include/deal.II/fe/fe_tools.templates.h
  source/fe/fe_bdm.cc
  source/fe/fe_raviart_thomas.cc
  source/fe/fe_tools.inst.in
Labels: ready to test

#18002 Avoid some more uses of GeometryInfo.
  source/fe/fe_raviart_thomas.cc
Labels: ready to test

#17994 Don't use a .templates.h file if we unconditionally include it anyway.
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/dofs/dof_accessor.templates.h
  source/hp/refinement.cc
Labels: ready to test

#17992 Add a script that detects cycles in our include files.
  contrib/utilities/detect_include_cycles.py
Labels: Miscellaneous, ready to test

#18010 Consistently format deprecated headers.
  include/deal.II/base/mpi_consensus_algorithms.templates.h
  include/deal.II/base/sacado_product_type.h
  include/deal.II/base/std_cxx17/algorithm.h
  include/deal.II/base/std_cxx17/optional.h
  include/deal.II/base/std_cxx17/tuple.h
  include/deal.II/base/std_cxx17/variant.h
  include/deal.II/base/vector_slice.h
  include/deal.II/dofs/dof_accessor.templates.h
  include/deal.II/fe/fe_base.h
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_accessor.templates.h
  include/deal.II/grid/tria_iterator.templates.h
  include/deal.II/lac/constraint_matrix.h
  include/deal.II/lac/petsc_parallel_block_sparse_matrix.h
  include/deal.II/lac/petsc_parallel_block_vector.h
  include/deal.II/lac/petsc_parallel_sparse_matrix.h
  include/deal.II/lac/petsc_parallel_vector.h
  include/deal.II/opencascade/boundary_lib.h
  source/dofs/dof_accessor.cc
  source/dofs/dof_accessor_get.cc
  source/dofs/dof_accessor_set.cc
  source/grid/tria_accessor.cc
Labels: Miscellaneous, ready to test

#18014 Update pre-commit hooks. Fix typos.
  .pre-commit-config.yaml
  examples/step-56/step-56.cc
  include/deal.II/lac/precondition.h
  include/deal.II/matrix_free/mapping_info.templates.h
  tests/fe/fe_enriched_01.cc
  tests/feinterface/stokes.cc
  tests/hp/fe_nothing_22.cc
Labels: Reviewed and ready to merge, ready to test

#18017 Add some necessary header files to tests.
  tests/base/mpi_noncontiguous_partitioner_01.cc
  tests/base/mpi_noncontiguous_partitioner_03.cc
  tests/base/mpi_noncontiguous_partitioner_04.cc
Labels: Reviewed and ready to merge, Tests, ready to test

#18016 Include tests.h in one of the tests.
  tests/hp/step-27.cc
Labels: Reviewed and ready to merge, ready to test

#18018 Include ../tests.h into a couple more tests.
  tests/fe/2d_grid_projection_hermite.cc
  tests/mpi/step-37.cc
  tests/rol/vector_adaptor_02.cc
  tests/simplex/step-12.cc
  tests/simplex/step-38.cc
Labels: Tests, ready to test

#17997 Break another cycle in header file includes.
  doc/news/changes/incompatibilities/20250116Bangerth
  include/deal.II/cgal/triangulation.h
  include/deal.II/distributed/fully_distributed_tria.h
  include/deal.II/grid/cell_data.h
  include/deal.II/grid/tria.h
  include/deal.II/grid/tria_description.h
  source/grid/grid_generator_cgal.cc
  source/grid/tria.cc
  source/opencascade/utilities.cc
  tests/hp/step-27.cc
  tests/matrix_free/create_mesh.h
  tests/mpi/petsc_step-27.cc
  tests/mpi/trilinos_step-27.cc
  tests/numerics/project_parallel_common.h
  tests/simplex/simplex_grids.h
  tests/test_grids.h
  tests/tests.h
Labels: ready to test

#18020 Fix misspellings.
  doc/news/changes/incompatibilities/20250116Bangerth
  include/deal.II/grid/tria_description.h
Labels: Reviewed and ready to merge, Triangulation, ready to test

#18009 Represent line orientations with `types::geometric_orientation`.
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.h
  include/deal.II/numerics/vector_tools_boundary.templates.h
  source/fe/fe_poly_tensor.cc
  source/grid/tria.cc
  source/grid/tria_accessor.cc
  tests/fe/fe_conformity_test.h
  tests/grid/extrude_orientation_01.cc
  tests/grid/extrude_orientation_02.cc
  tests/grid/extrude_orientation_03.cc
  tests/grid/grid_generator_10.cc
  tests/grid/grid_generator_non_standard_orientation_mesh_2d.cc
  tests/grid/grid_generator_non_standard_orientation_mesh_3d.cc
  tests/simplex/orientation_04.cc
Labels: Triangulation, ready to test

#18022 Move hardcoded orientation values around
  include/deal.II/base/types.h
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/dofs/dof_tools.h
  include/deal.II/fe/fe.h
  include/deal.II/fe/fe_q_base.h
  include/deal.II/fe/fe_system.h
  include/deal.II/grid/connectivity.h
  include/deal.II/grid/reference_cell.h
  include/deal.II/grid/tria_accessor.h
  include/deal.II/grid/tria_objects_orientations.h
  include/deal.II/non_matching/mapping_info.h
  include/deal.II/numerics/vector_tools_boundary.templates.h
  source/base/qprojector.cc
  source/distributed/tria.cc
  source/fe/fe.cc
  source/fe/fe_abf.cc
  source/fe/fe_bdm.cc
  source/fe/fe_nedelec.cc
  source/fe/fe_poly_tensor.cc
  source/fe/fe_q_base.cc
  source/fe/fe_raviart_thomas.cc
  source/fe/fe_rt_bubbles.cc
  source/fe/fe_simplex_p.cc
  source/fe/fe_simplex_p_bubbles.cc
  source/grid/grid_tools_dof_handlers.cc
  source/grid/reference_cell.cc
  source/grid/tria.cc
  tests/bits/periodicity_09.cc
  tests/dofs/dof_tools_21_b_x.cc
  tests/dofs/dof_tools_21_b_x_q3.cc
  tests/fe/fe_conformity_test.h
  tests/grid/extrude_orientation_01.cc
  tests/grid/extrude_orientation_02.cc
  tests/grid/extrude_orientation_03.cc
  tests/grid/grid_generator_10.cc
  tests/grid/grid_generator_non_standard_orientation_mesh_2d.cc
  tests/grid/grid_generator_non_standard_orientation_mesh_3d.cc
  tests/grid/reference_cell_type_05.cc
  tests/simplex/orientation_03.cc
  tests/simplex/orientation_04.cc
Labels: Triangulation, ready to test

#18019 Break the include cycle between dof_handler.h and dof_accessor.h.
  include/deal.II/dofs/dof_accessor.h
  include/deal.II/dofs/dof_handler.h
  include/deal.II/matrix_free/constraint_info.h
  source/grid/tria_accessor.cc
  source/matrix_free/dof_info.cc
  tests/bits/refine_and_coarsen_for_active_cell_index_03.cc
  tests/bits/refine_and_coarsen_for_active_cell_index_04.cc
  tests/bits/refine_and_coarsen_for_active_cell_index_05.cc
  tests/bits/refine_and_coarsen_for_parents_03.cc
  tests/fe/fe_support_points_common.h
  tests/fe/interpolate_system_2.cc
  tests/fe/interpolate_system_3.cc
  tests/mpi/active_cell_index_01.cc
  tests/multigrid/renumbering_05.cc
  tests/multigrid/renumbering_08.cc
Labels: ready to test

#18024 Break the cycle of header includes between template_constraints.h and complex_overloads.h.
  include/deal.II/base/complex_overloads.h
Labels: ready to test

#18026 Break the include cycle between tria.h and tria_accessor.h.
  include/deal.II/grid/tria_accessor.h
Labels: ready to test

#18029 Deprecate IndexSet::pop_front/back().
  doc/news/changes/minor/20250123Bangerth-2
  include/deal.II/base/index_set.h
Labels: ready to test

#18013 Add detect-include-cycle check to pre-commit.
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  contrib/utilities/detect_include_cycles.py
Labels: Infrastructure

#17755 Nedelec orientation fix nr.1.
  include/deal.II/fe/fe_nedelec.h
  source/fe/fe_nedelec.cc
  source/fe/fe_poly_tensor.cc
  tests/fe/fe_nedelec_face_edge_orientation.h
  tests/fe/fe_nedelec_face_edge_orientation_0.cc
  tests/fe/fe_nedelec_face_edge_orientation_0.output
  tests/fe/fe_nedelec_face_edge_orientation_1.cc
  tests/fe/fe_nedelec_face_edge_orientation_1.output
  tests/fe/fe_nedelec_face_edge_orientation_2.cc
  tests/fe/fe_nedelec_face_edge_orientation_2.output
  tests/fe/fe_nedelec_face_edge_orientation_3.cc
  tests/fe/fe_nedelec_face_edge_orientation_3.output
  tests/fe/fe_nedelec_face_edge_orientation_4.cc
  tests/fe/fe_nedelec_face_edge_orientation_4.output
  tests/fe/fe_nedelec_face_edge_orientation_5.cc
  tests/fe/fe_nedelec_face_edge_orientation_5.output
  tests/fe/fe_nedelec_face_edge_orientation_6.cc
  tests/fe/fe_nedelec_face_edge_orientation_6.output
  tests/fe/fe_nedelec_face_edge_orientation_7.cc
  tests/fe/fe_nedelec_face_edge_orientation_7.output
  tests/fe/fe_nedelec_face_edge_orientation_8.cc
  tests/fe/fe_nedelec_face_edge_orientation_8.output
Labels: ready to test

#18030 Add 3D alfeld (barycenter) refinement capability
  source/grid/grid_generator.cc
  tests/simplex/alfeld_split_01.cc
  tests/simplex/alfeld_split_01.output
  tests/simplex/stokes-sv.cc
  tests/simplex/stokes-sv.output
Labels: Reviewed and ready to merge, ready to test

#17406 TrilinosWrappers::SolverDirect for Epetra data structures
  doc/news/changes/minor/20240731Munch
  include/deal.II/lac/trilinos_solver.h
  source/lac/trilinos_solver.cc
  tests/trilinos/direct_solver_4.cc
  tests/trilinos/direct_solver_4.output
Labels: Linear Algebra, ready to test

#18033 Add missing include
  include/deal.II/base/mpi_noncontiguous_partitioner.h
Labels: ready to test

#18036 Fix MF::get_cell_active_fe_index() for non-hp and hp-DoFHandlers
  include/deal.II/matrix_free/matrix_free.h
Labels: Reviewed and ready to merge, Matrix-free, hp adaptivity, ready to test

#18035 MatrixFree: encode the orientation as (!orientation, rotation, flip).
  include/deal.II/matrix_free/face_info.h
  include/deal.II/matrix_free/face_setup_internal.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/hanging_nodes_internal.h
  include/deal.II/matrix_free/shape_info.templates.h
  tests/matrix_free/matrix_vector_faces_34.cc
  tests/matrix_free/matrix_vector_faces_34.output
  tests/matrix_free/matrix_vector_faces_35.cc
  tests/matrix_free/matrix_vector_faces_35.output
Labels: Matrix-free, Triangulation, ready to test

#18027 Rename unit_tangential/normal_vectors() to face_tangent/normal_vector().
  doc/news/changes/minor/20250123Bangerth
  include/deal.II/grid/reference_cell.h
  source/fe/mapping_fe.cc
  source/fe/mapping_fe_field.cc
  tests/simplex/orientation_03.cc
  tests/simplex/orientation_04.cc
  tests/simplex/unit_tangential_vectors_01.cc
Labels: ready to test

#18042 Consider number of components in n_local_dofs
  include/deal.II/matrix_free/portable_matrix_free.templates.h
  include/deal.II/matrix_free/tools.h
  tests/matrix_free_kokkos/matrix_vector_host_device_multi_component.cc
Labels: GPU, ready to test

#18001 Avoid the use of GeometryInfo in particle_handler.cc.
  doc/news/changes/minor/20250127Bangerth
  source/particles/particle_handler.cc
  tests/simplex/step-68.mpirun=1.output
  tests/simplex/step-68.mpirun=4.output
Labels: ready to test

#18028 Fix an issue with spaces in ParameterHandler output.
  source/base/parameter_handler.cc
  tests/parameter_handler/parameter_handler_6_spaces.cc
  tests/parameter_handler/parameter_handler_6_spaces.output
Labels: ready to test

#18023 Better document our mixed complex overloads.
  cmake/checks/check_01_cxx_features.cmake
  include/deal.II/base/complex_overloads.h
Labels: ready to test

#18008 MatrixFree: enable DiagonalMatrix in loops
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/type_traits.h
  source/lac/affine_constraints.inst.in
  tests/matrix_free/compute_diagonal_08.cc
Labels: Reviewed and ready to merge, Matrix-free, ready to test

#18041 Remove n_dofs_1d from local operation class of matrix-free operation
  doc/news/changes/minor/20250128Munch
  examples/step-64/step-64.cc
  include/deal.II/matrix_free/portable_matrix_free.h
  tests/matrix_free_kokkos/coefficient_eval_device.cc
  tests/matrix_free_kokkos/matrix_free_device_no_index_initialize.cc
  tests/matrix_free_kokkos/matrix_vector_device_mf.h
  tests/matrix_free_kokkos/matrix_vector_host_device_multi_component.cc
Labels: GPU, ready to test

#18052 Fix a file name in a cmake file.
  source/CMakeLists.txt
Labels: ready to test

#18049 Fix various typos
  examples/step-18/step-18.cc
  include/deal.II/lac/sparse_matrix.templates.h
  include/deal.II/matrix_free/fe_evaluation.h
  include/deal.II/matrix_free/fe_evaluation_data.h
  source/base/parameter_handler.cc
  source/base/tensor.cc
  source/multigrid/mg_tools.cc
  tests/fe/fe_face_orientation_nedelec_0.cc
  tests/fe/fe_project_3d.cc
  tests/hp/boundary_matrices_hp.cc
  tests/matrix_free/fe_nothing_02.cc
  tests/quick_tests/step-petsc.cc
  tests/quick_tests/step-slepc.cc
  tests/quick_tests/step-trilinos.cc
Labels: Reviewed and ready to merge, ready to test

#18051 Fix macro name in the documentation; also fix file name.
  cmake/macros/macro_define_object_library.cmake
Labels: Reviewed and ready to merge, ready to test

#18044 Parallel vector: Add assert for ghosts in global vector ops
  include/deal.II/lac/la_parallel_vector.h
  include/deal.II/lac/la_parallel_vector.templates.h
  include/deal.II/lac/vector_operations_internal.h
Labels: Parallel distributed, ready to test

#17926 Update face_setup_internal.h to allow for 1D adaptive meshes
  include/deal.II/matrix_free/face_setup_internal.h
Labels: Matrix-free, ready to test

#18059 Move functions from .cc to .templates.h
  include/deal.II/multigrid/mg_base.templates.h
  source/multigrid/mg_base.cc
Labels: Multigrid, ready to test

#18058 Update a comment in step-38.
  examples/step-38/doc/results.dox
Labels: Documentation, ready to test

#18055 Avoid several more uses of GeometryInfo.
  source/fe/fe_dgp_nonparametric.cc
  source/fe/fe_dgq.cc
  source/fe/fe_nedelec.cc
  source/fe/fe_nedelec_sz.cc
  source/fe/fe_q_base.cc
  source/fe/fe_q_bubbles.cc
  source/fe/fe_q_hierarchical.cc
  source/fe/fe_raviart_thomas.cc
  source/fe/fe_raviart_thomas_nodal.cc
  source/fe/fe_rt_bubbles.cc
  source/fe/mapping_cartesian.cc
Labels: Finite Element, ready to test

#18038 Avoid old orientation functions 2
  include/deal.II/matrix_free/hanging_nodes_internal.h
  include/deal.II/matrix_free/shape_info.templates.h
Labels: Reviewed and ready to merge, Matrix-free, Triangulation, ready to test

#18060 MatrixFree: Update test output in 1D face setup
  include/deal.II/matrix_free/face_setup_internal.h
  tests/matrix_free/matrix_vector_hessians_faces.output
  tests/matrix_free/matrix_vector_normal_hessians.output
Labels: Matrix-free, Tests, ready to test

#18062 Always initialize a variable in AlignedVector.
  include/deal.II/base/aligned_vector.h
Labels: ready to test

#18061 Include ghost cell in Matrix-Free data
  include/deal.II/matrix_free/matrix_free.h
  include/deal.II/matrix_free/matrix_free.templates.h
Labels: Matrix-free, ready to test

#17365 CMake: update boost configuration, fix boost policy warning
  CMakeLists.txt
  cmake/configure/configure_20_boost.cmake
  cmake/modules/FindDEAL_II_BOOST.cmake
  doc/news/changes/incompatibilities/20250130Maier
  doc/readme.html
Labels: Build system, Reviewed and ready to merge, ready to test
